import * as S from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const ActionList = S.Array(S.String);
export class CreateCertificateAuthorityAuditReportRequest extends S.Class<CreateCertificateAuthorityAuditReportRequest>("CreateCertificateAuthorityAuditReportRequest")({CertificateAuthorityArn: S.String, S3BucketName: S.String, AuditReportResponseFormat: S.String}) {}
export class CreatePermissionRequest extends S.Class<CreatePermissionRequest>("CreatePermissionRequest")({CertificateAuthorityArn: S.String, Principal: S.String, SourceAccount: S.optional(S.String), Actions: ActionList}) {}
export class DeleteCertificateAuthorityRequest extends S.Class<DeleteCertificateAuthorityRequest>("DeleteCertificateAuthorityRequest")({CertificateAuthorityArn: S.String, PermanentDeletionTimeInDays: S.optional(S.Number)}) {}
export class DeletePermissionRequest extends S.Class<DeletePermissionRequest>("DeletePermissionRequest")({CertificateAuthorityArn: S.String, Principal: S.String, SourceAccount: S.optional(S.String)}) {}
export class DeletePolicyRequest extends S.Class<DeletePolicyRequest>("DeletePolicyRequest")({ResourceArn: S.String}) {}
export class DescribeCertificateAuthorityRequest extends S.Class<DescribeCertificateAuthorityRequest>("DescribeCertificateAuthorityRequest")({CertificateAuthorityArn: S.String}) {}
export class DescribeCertificateAuthorityAuditReportRequest extends S.Class<DescribeCertificateAuthorityAuditReportRequest>("DescribeCertificateAuthorityAuditReportRequest")({CertificateAuthorityArn: S.String, AuditReportId: S.String}) {}
export class GetCertificateRequest extends S.Class<GetCertificateRequest>("GetCertificateRequest")({CertificateAuthorityArn: S.String, CertificateArn: S.String}) {}
export class GetCertificateAuthorityCertificateRequest extends S.Class<GetCertificateAuthorityCertificateRequest>("GetCertificateAuthorityCertificateRequest")({CertificateAuthorityArn: S.String}) {}
export class GetCertificateAuthorityCsrRequest extends S.Class<GetCertificateAuthorityCsrRequest>("GetCertificateAuthorityCsrRequest")({CertificateAuthorityArn: S.String}) {}
export class GetPolicyRequest extends S.Class<GetPolicyRequest>("GetPolicyRequest")({ResourceArn: S.String}) {}
export class ImportCertificateAuthorityCertificateRequest extends S.Class<ImportCertificateAuthorityCertificateRequest>("ImportCertificateAuthorityCertificateRequest")({CertificateAuthorityArn: S.String, Certificate: H.StreamBody(), CertificateChain: S.optional(H.StreamBody())}) {}
export class ListCertificateAuthoritiesRequest extends S.Class<ListCertificateAuthoritiesRequest>("ListCertificateAuthoritiesRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ResourceOwner: S.optional(S.String)}) {}
export class ListPermissionsRequest extends S.Class<ListPermissionsRequest>("ListPermissionsRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), CertificateAuthorityArn: S.String}) {}
export class ListTagsRequest extends S.Class<ListTagsRequest>("ListTagsRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), CertificateAuthorityArn: S.String}) {}
export class PutPolicyRequest extends S.Class<PutPolicyRequest>("PutPolicyRequest")({ResourceArn: S.String, Policy: S.String}) {}
export class RestoreCertificateAuthorityRequest extends S.Class<RestoreCertificateAuthorityRequest>("RestoreCertificateAuthorityRequest")({CertificateAuthorityArn: S.String}) {}
export class RevokeCertificateRequest extends S.Class<RevokeCertificateRequest>("RevokeCertificateRequest")({CertificateAuthorityArn: S.String, CertificateSerial: S.String, RevocationReason: S.String}) {}
export class Tag extends S.Class<Tag>("Tag")({Key: S.String, Value: S.optional(S.String)}) {}
export const TagList = S.Array(Tag);
export class TagCertificateAuthorityRequest extends S.Class<TagCertificateAuthorityRequest>("TagCertificateAuthorityRequest")({CertificateAuthorityArn: S.String, Tags: TagList}) {}
export class UntagCertificateAuthorityRequest extends S.Class<UntagCertificateAuthorityRequest>("UntagCertificateAuthorityRequest")({CertificateAuthorityArn: S.String, Tags: TagList}) {}
export class CrlDistributionPointExtensionConfiguration extends S.Class<CrlDistributionPointExtensionConfiguration>("CrlDistributionPointExtensionConfiguration")({OmitExtension: S.Boolean}) {}
export class CrlConfiguration extends S.Class<CrlConfiguration>("CrlConfiguration")({Enabled: S.Boolean, ExpirationInDays: S.optional(S.Number), CustomCname: S.optional(S.String), S3BucketName: S.optional(S.String), S3ObjectAcl: S.optional(S.String), CrlDistributionPointExtensionConfiguration: S.optional(CrlDistributionPointExtensionConfiguration), CrlType: S.optional(S.String), CustomPath: S.optional(S.String)}) {}
export class OcspConfiguration extends S.Class<OcspConfiguration>("OcspConfiguration")({Enabled: S.Boolean, OcspCustomCname: S.optional(S.String)}) {}
export class RevocationConfiguration extends S.Class<RevocationConfiguration>("RevocationConfiguration")({CrlConfiguration: S.optional(CrlConfiguration), OcspConfiguration: S.optional(OcspConfiguration)}) {}
export class UpdateCertificateAuthorityRequest extends S.Class<UpdateCertificateAuthorityRequest>("UpdateCertificateAuthorityRequest")({CertificateAuthorityArn: S.String, RevocationConfiguration: S.optional(RevocationConfiguration), Status: S.optional(S.String)}) {}
export class Validity extends S.Class<Validity>("Validity")({Value: S.Number, Type: S.String}) {}
export class CustomAttribute extends S.Class<CustomAttribute>("CustomAttribute")({ObjectIdentifier: S.String, Value: S.String}) {}
export const CustomAttributeList = S.Array(CustomAttribute);
export class ASN1Subject extends S.Class<ASN1Subject>("ASN1Subject")({Country: S.optional(S.String), Organization: S.optional(S.String), OrganizationalUnit: S.optional(S.String), DistinguishedNameQualifier: S.optional(S.String), State: S.optional(S.String), CommonName: S.optional(S.String), SerialNumber: S.optional(S.String), Locality: S.optional(S.String), Title: S.optional(S.String), Surname: S.optional(S.String), GivenName: S.optional(S.String), Initials: S.optional(S.String), Pseudonym: S.optional(S.String), GenerationQualifier: S.optional(S.String), CustomAttributes: S.optional(CustomAttributeList)}) {}
export class KeyUsage extends S.Class<KeyUsage>("KeyUsage")({DigitalSignature: S.optional(S.Boolean), NonRepudiation: S.optional(S.Boolean), KeyEncipherment: S.optional(S.Boolean), DataEncipherment: S.optional(S.Boolean), KeyAgreement: S.optional(S.Boolean), KeyCertSign: S.optional(S.Boolean), CRLSign: S.optional(S.Boolean), EncipherOnly: S.optional(S.Boolean), DecipherOnly: S.optional(S.Boolean)}) {}
export class AccessMethod extends S.Class<AccessMethod>("AccessMethod")({CustomObjectIdentifier: S.optional(S.String), AccessMethodType: S.optional(S.String)}) {}
export class OtherName extends S.Class<OtherName>("OtherName")({TypeId: S.String, Value: S.String}) {}
export class EdiPartyName extends S.Class<EdiPartyName>("EdiPartyName")({PartyName: S.String, NameAssigner: S.optional(S.String)}) {}
export class GeneralName extends S.Class<GeneralName>("GeneralName")({OtherName: S.optional(OtherName), Rfc822Name: S.optional(S.String), DnsName: S.optional(S.String), DirectoryName: S.optional(ASN1Subject), EdiPartyName: S.optional(EdiPartyName), UniformResourceIdentifier: S.optional(S.String), IpAddress: S.optional(S.String), RegisteredId: S.optional(S.String)}) {}
export class AccessDescription extends S.Class<AccessDescription>("AccessDescription")({AccessMethod: AccessMethod, AccessLocation: GeneralName}) {}
export const AccessDescriptionList = S.Array(AccessDescription);
export class CsrExtensions extends S.Class<CsrExtensions>("CsrExtensions")({KeyUsage: S.optional(KeyUsage), SubjectInformationAccess: S.optional(AccessDescriptionList)}) {}
export class CertificateAuthorityConfiguration extends S.Class<CertificateAuthorityConfiguration>("CertificateAuthorityConfiguration")({KeyAlgorithm: S.String, SigningAlgorithm: S.String, Subject: ASN1Subject, CsrExtensions: S.optional(CsrExtensions)}) {}
export class CertificateAuthority extends S.Class<CertificateAuthority>("CertificateAuthority")({Arn: S.optional(S.String), OwnerAccount: S.optional(S.String), CreatedAt: S.optional(S.Date), LastStateChangeAt: S.optional(S.Date), Type: S.optional(S.String), Serial: S.optional(S.String), Status: S.optional(S.String), NotBefore: S.optional(S.Date), NotAfter: S.optional(S.Date), FailureReason: S.optional(S.String), CertificateAuthorityConfiguration: S.optional(CertificateAuthorityConfiguration), RevocationConfiguration: S.optional(RevocationConfiguration), RestorableUntil: S.optional(S.Date), KeyStorageSecurityStandard: S.optional(S.String), UsageMode: S.optional(S.String)}) {}
export const CertificateAuthorities = S.Array(CertificateAuthority);
export class CreateCertificateAuthorityAuditReportResponse extends S.Class<CreateCertificateAuthorityAuditReportResponse>("CreateCertificateAuthorityAuditReportResponse")({AuditReportId: S.optional(S.String), S3Key: S.optional(S.String)}) {}
export class DescribeCertificateAuthorityAuditReportResponse extends S.Class<DescribeCertificateAuthorityAuditReportResponse>("DescribeCertificateAuthorityAuditReportResponse")({AuditReportStatus: S.optional(S.String), S3BucketName: S.optional(S.String), S3Key: S.optional(S.String), CreatedAt: S.optional(S.Date)}) {}
export class GetCertificateResponse extends S.Class<GetCertificateResponse>("GetCertificateResponse")({Certificate: S.optional(S.String), CertificateChain: S.optional(S.String)}) {}
export class GetCertificateAuthorityCertificateResponse extends S.Class<GetCertificateAuthorityCertificateResponse>("GetCertificateAuthorityCertificateResponse")({Certificate: S.optional(S.String), CertificateChain: S.optional(S.String)}) {}
export class GetCertificateAuthorityCsrResponse extends S.Class<GetCertificateAuthorityCsrResponse>("GetCertificateAuthorityCsrResponse")({Csr: S.optional(S.String)}) {}
export class GetPolicyResponse extends S.Class<GetPolicyResponse>("GetPolicyResponse")({Policy: S.optional(S.String)}) {}
export class ListCertificateAuthoritiesResponse extends S.Class<ListCertificateAuthoritiesResponse>("ListCertificateAuthoritiesResponse")({NextToken: S.optional(S.String), CertificateAuthorities: S.optional(CertificateAuthorities)}) {}
export class ListTagsResponse extends S.Class<ListTagsResponse>("ListTagsResponse")({NextToken: S.optional(S.String), Tags: S.optional(TagList)}) {}
export class Permission extends S.Class<Permission>("Permission")({CertificateAuthorityArn: S.optional(S.String), CreatedAt: S.optional(S.Date), Principal: S.optional(S.String), SourceAccount: S.optional(S.String), Actions: S.optional(ActionList), Policy: S.optional(S.String)}) {}
export const PermissionList = S.Array(Permission);
export class ExtendedKeyUsage extends S.Class<ExtendedKeyUsage>("ExtendedKeyUsage")({ExtendedKeyUsageType: S.optional(S.String), ExtendedKeyUsageObjectIdentifier: S.optional(S.String)}) {}
export const ExtendedKeyUsageList = S.Array(ExtendedKeyUsage);
export class CustomExtension extends S.Class<CustomExtension>("CustomExtension")({ObjectIdentifier: S.String, Value: S.String, Critical: S.optional(S.Boolean)}) {}
export const CustomExtensionList = S.Array(CustomExtension);
export class DescribeCertificateAuthorityResponse extends S.Class<DescribeCertificateAuthorityResponse>("DescribeCertificateAuthorityResponse")({CertificateAuthority: S.optional(CertificateAuthority)}) {}
export class ListPermissionsResponse extends S.Class<ListPermissionsResponse>("ListPermissionsResponse")({NextToken: S.optional(S.String), Permissions: S.optional(PermissionList)}) {}
export const GeneralNameList = S.Array(GeneralName);
export class Qualifier extends S.Class<Qualifier>("Qualifier")({CpsUri: S.String}) {}
export class PolicyQualifierInfo extends S.Class<PolicyQualifierInfo>("PolicyQualifierInfo")({PolicyQualifierId: S.String, Qualifier: Qualifier}) {}
export const PolicyQualifierInfoList = S.Array(PolicyQualifierInfo);
export class PolicyInformation extends S.Class<PolicyInformation>("PolicyInformation")({CertPolicyId: S.String, PolicyQualifiers: S.optional(PolicyQualifierInfoList)}) {}
export const CertificatePolicyList = S.Array(PolicyInformation);
export class CreateCertificateAuthorityRequest extends S.Class<CreateCertificateAuthorityRequest>("CreateCertificateAuthorityRequest")({CertificateAuthorityConfiguration: CertificateAuthorityConfiguration, RevocationConfiguration: S.optional(RevocationConfiguration), CertificateAuthorityType: S.String, IdempotencyToken: S.optional(S.String), KeyStorageSecurityStandard: S.optional(S.String), Tags: S.optional(TagList), UsageMode: S.optional(S.String)}) {}
export class Extensions extends S.Class<Extensions>("Extensions")({CertificatePolicies: S.optional(CertificatePolicyList), ExtendedKeyUsage: S.optional(ExtendedKeyUsageList), KeyUsage: S.optional(KeyUsage), SubjectAlternativeNames: S.optional(GeneralNameList), CustomExtensions: S.optional(CustomExtensionList)}) {}
export class ApiPassthrough extends S.Class<ApiPassthrough>("ApiPassthrough")({Extensions: S.optional(Extensions), Subject: S.optional(ASN1Subject)}) {}
export class CreateCertificateAuthorityResponse extends S.Class<CreateCertificateAuthorityResponse>("CreateCertificateAuthorityResponse")({CertificateAuthorityArn: S.optional(S.String)}) {}
export class IssueCertificateRequest extends S.Class<IssueCertificateRequest>("IssueCertificateRequest")({ApiPassthrough: S.optional(ApiPassthrough), CertificateAuthorityArn: S.String, Csr: H.StreamBody(), SigningAlgorithm: S.String, TemplateArn: S.optional(S.String), Validity: Validity, ValidityNotBefore: S.optional(Validity), IdempotencyToken: S.optional(S.String)}) {}
export class IssueCertificateResponse extends S.Class<IssueCertificateResponse>("IssueCertificateResponse")({CertificateArn: S.optional(S.String)}) {}

//# Errors
export class InvalidArnException extends S.TaggedError<InvalidArnException>()("InvalidArnException", {}) {};
export class ConcurrentModificationException extends S.TaggedError<ConcurrentModificationException>()("ConcurrentModificationException", {}) {};
export class InvalidStateException extends S.TaggedError<InvalidStateException>()("InvalidStateException", {}) {};
export class InvalidTagException extends S.TaggedError<InvalidTagException>()("InvalidTagException", {}) {};
export class ResourceNotFoundException extends S.TaggedError<ResourceNotFoundException>()("ResourceNotFoundException", {}) {};
export class InvalidArgsException extends S.TaggedError<InvalidArgsException>()("InvalidArgsException", {}) {};
export class RequestFailedException extends S.TaggedError<RequestFailedException>()("RequestFailedException", {}) {};
export class LockoutPreventedException extends S.TaggedError<LockoutPreventedException>()("LockoutPreventedException", {message: S.optional(S.String)}) {};
export class RequestInProgressException extends S.TaggedError<RequestInProgressException>()("RequestInProgressException", {}) {};
export class CertificateMismatchException extends S.TaggedError<CertificateMismatchException>()("CertificateMismatchException", {message: S.optional(S.String)}) {};
export class InvalidRequestException extends S.TaggedError<InvalidRequestException>()("InvalidRequestException", {}) {};
export class InvalidPolicyException extends S.TaggedError<InvalidPolicyException>()("InvalidPolicyException", {message: S.optional(S.String)}) {};
export class LimitExceededException extends S.TaggedError<LimitExceededException>()("LimitExceededException", {}) {};
export class MalformedCertificateException extends S.TaggedError<MalformedCertificateException>()("MalformedCertificateException", {message: S.optional(S.String)}) {};
export class InvalidNextTokenException extends S.TaggedError<InvalidNextTokenException>()("InvalidNextTokenException", {message: S.optional(S.String)}) {};
export class RequestAlreadyProcessedException extends S.TaggedError<RequestAlreadyProcessedException>()("RequestAlreadyProcessedException", {message: S.optional(S.String)}) {};
export class TooManyTagsException extends S.TaggedError<TooManyTagsException>()("TooManyTagsException", {message: S.optional(S.String)}) {};
export class PermissionAlreadyExistsException extends S.TaggedError<PermissionAlreadyExistsException>()("PermissionAlreadyExistsException", {message: S.optional(S.String)}) {};
export class MalformedCSRException extends S.TaggedError<MalformedCSRException>()("MalformedCSRException", {message: S.optional(S.String)}) {};

//# Operations
export const untagCertificateAuthority = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.UntagCertificateAuthority" }, UntagCertificateAuthorityRequest, S.Struct({}), [InvalidArnException, InvalidStateException, InvalidTagException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteCertificateAuthority = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.DeleteCertificateAuthority" }, DeleteCertificateAuthorityRequest, S.Struct({}), [ConcurrentModificationException, InvalidArnException, InvalidStateException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deletePermission = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.DeletePermission" }, DeletePermissionRequest, S.Struct({}), [InvalidArnException, InvalidStateException, RequestFailedException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deletePolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.DeletePolicy" }, DeletePolicyRequest, S.Struct({}), [ConcurrentModificationException, InvalidArnException, InvalidStateException, LockoutPreventedException, RequestFailedException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeCertificateAuthorityAuditReport = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.DescribeCertificateAuthorityAuditReport" }, DescribeCertificateAuthorityAuditReportRequest, DescribeCertificateAuthorityAuditReportResponse, [InvalidArgsException, InvalidArnException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getCertificateAuthorityCertificate = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.GetCertificateAuthorityCertificate" }, GetCertificateAuthorityCertificateRequest, GetCertificateAuthorityCertificateResponse, [InvalidArnException, InvalidStateException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getCertificateAuthorityCsr = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.GetCertificateAuthorityCsr" }, GetCertificateAuthorityCsrRequest, GetCertificateAuthorityCsrResponse, [InvalidArnException, InvalidStateException, RequestFailedException, RequestInProgressException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.GetPolicy" }, GetPolicyRequest, GetPolicyResponse, [InvalidArnException, InvalidStateException, RequestFailedException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTags = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.ListTags" }, ListTagsRequest, ListTagsResponse, [InvalidArnException, InvalidStateException, RequestFailedException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const putPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.PutPolicy" }, PutPolicyRequest, S.Struct({}), [ConcurrentModificationException, InvalidArnException, InvalidPolicyException, InvalidStateException, LockoutPreventedException, RequestFailedException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const restoreCertificateAuthority = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.RestoreCertificateAuthority" }, RestoreCertificateAuthorityRequest, S.Struct({}), [InvalidArnException, InvalidStateException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateCertificateAuthority = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.UpdateCertificateAuthority" }, UpdateCertificateAuthorityRequest, S.Struct({}), [ConcurrentModificationException, InvalidArgsException, InvalidArnException, InvalidPolicyException, InvalidStateException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createCertificateAuthorityAuditReport = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.CreateCertificateAuthorityAuditReport" }, CreateCertificateAuthorityAuditReportRequest, CreateCertificateAuthorityAuditReportResponse, [InvalidArgsException, InvalidArnException, InvalidStateException, RequestFailedException, RequestInProgressException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeCertificateAuthority = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.DescribeCertificateAuthority" }, DescribeCertificateAuthorityRequest, DescribeCertificateAuthorityResponse, [InvalidArnException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getCertificate = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.GetCertificate" }, GetCertificateRequest, GetCertificateResponse, [InvalidArnException, InvalidStateException, RequestFailedException, RequestInProgressException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const importCertificateAuthorityCertificate = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.ImportCertificateAuthorityCertificate" }, ImportCertificateAuthorityCertificateRequest, S.Struct({}), [CertificateMismatchException, ConcurrentModificationException, InvalidArnException, InvalidRequestException, InvalidStateException, MalformedCertificateException, RequestFailedException, RequestInProgressException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listCertificateAuthorities = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.ListCertificateAuthorities" }, ListCertificateAuthoritiesRequest, ListCertificateAuthoritiesResponse, [InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listPermissions = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.ListPermissions" }, ListPermissionsRequest, ListPermissionsResponse, [InvalidArnException, InvalidNextTokenException, InvalidStateException, RequestFailedException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const revokeCertificate = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.RevokeCertificate" }, RevokeCertificateRequest, S.Struct({}), [ConcurrentModificationException, InvalidArnException, InvalidRequestException, InvalidStateException, LimitExceededException, RequestAlreadyProcessedException, RequestFailedException, RequestInProgressException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagCertificateAuthority = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.TagCertificateAuthority" }, TagCertificateAuthorityRequest, S.Struct({}), [InvalidArnException, InvalidStateException, InvalidTagException, ResourceNotFoundException, TooManyTagsException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createPermission = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.CreatePermission" }, CreatePermissionRequest, S.Struct({}), [InvalidArnException, InvalidStateException, LimitExceededException, PermissionAlreadyExistsException, RequestFailedException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createCertificateAuthority = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.CreateCertificateAuthority" }, CreateCertificateAuthorityRequest, CreateCertificateAuthorityResponse, [InvalidArgsException, InvalidPolicyException, InvalidTagException, LimitExceededException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const issueCertificate = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-08-22", uri: "/", method: "POST", sdkId: "ACM PCA", sigV4ServiceName: "acm-pca", name: "ACMPrivateCA.IssueCertificate" }, IssueCertificateRequest, IssueCertificateResponse, [InvalidArgsException, InvalidArnException, InvalidStateException, LimitExceededException, MalformedCSRException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
