import * as S from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const ResourceIdsMaxLen1600 = S.Array(S.String);
export const TagKeyList = S.Array(S.String);
export class DeleteScalingPolicyRequest extends S.Class<DeleteScalingPolicyRequest>("DeleteScalingPolicyRequest")({PolicyName: S.String, ServiceNamespace: S.String, ResourceId: S.String, ScalableDimension: S.String}) {}
export class DeleteScalingPolicyResponse extends S.Class<DeleteScalingPolicyResponse>("DeleteScalingPolicyResponse")({}) {}
export class DeleteScheduledActionRequest extends S.Class<DeleteScheduledActionRequest>("DeleteScheduledActionRequest")({ServiceNamespace: S.String, ScheduledActionName: S.String, ResourceId: S.String, ScalableDimension: S.String}) {}
export class DeleteScheduledActionResponse extends S.Class<DeleteScheduledActionResponse>("DeleteScheduledActionResponse")({}) {}
export class DeregisterScalableTargetRequest extends S.Class<DeregisterScalableTargetRequest>("DeregisterScalableTargetRequest")({ServiceNamespace: S.String, ResourceId: S.String, ScalableDimension: S.String}) {}
export class DeregisterScalableTargetResponse extends S.Class<DeregisterScalableTargetResponse>("DeregisterScalableTargetResponse")({}) {}
export class DescribeScalableTargetsRequest extends S.Class<DescribeScalableTargetsRequest>("DescribeScalableTargetsRequest")({ServiceNamespace: S.String, ResourceIds: S.optional(ResourceIdsMaxLen1600), ScalableDimension: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class DescribeScalingActivitiesRequest extends S.Class<DescribeScalingActivitiesRequest>("DescribeScalingActivitiesRequest")({ServiceNamespace: S.String, ResourceId: S.optional(S.String), ScalableDimension: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), IncludeNotScaledActivities: S.optional(S.Boolean)}) {}
export class DescribeScalingPoliciesRequest extends S.Class<DescribeScalingPoliciesRequest>("DescribeScalingPoliciesRequest")({PolicyNames: S.optional(ResourceIdsMaxLen1600), ServiceNamespace: S.String, ResourceId: S.optional(S.String), ScalableDimension: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class DescribeScheduledActionsRequest extends S.Class<DescribeScheduledActionsRequest>("DescribeScheduledActionsRequest")({ScheduledActionNames: S.optional(ResourceIdsMaxLen1600), ServiceNamespace: S.String, ResourceId: S.optional(S.String), ScalableDimension: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class GetPredictiveScalingForecastRequest extends S.Class<GetPredictiveScalingForecastRequest>("GetPredictiveScalingForecastRequest")({ServiceNamespace: S.String, ResourceId: S.String, ScalableDimension: S.String, PolicyName: S.String, StartTime: S.Date, EndTime: S.Date}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceARN: S.String}) {}
export const TagMap = S.Record({key: S.String, value: S.String});
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceARN: S.String, Tags: TagMap}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceARN: S.String, TagKeys: TagKeyList}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class ScalableTargetAction extends S.Class<ScalableTargetAction>("ScalableTargetAction")({MinCapacity: S.optional(S.Number), MaxCapacity: S.optional(S.Number)}) {}
export class SuspendedState extends S.Class<SuspendedState>("SuspendedState")({DynamicScalingInSuspended: S.optional(S.Boolean), DynamicScalingOutSuspended: S.optional(S.Boolean), ScheduledScalingSuspended: S.optional(S.Boolean)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: S.optional(TagMap)}) {}
export class PutScheduledActionRequest extends S.Class<PutScheduledActionRequest>("PutScheduledActionRequest")({ServiceNamespace: S.String, Schedule: S.optional(S.String), Timezone: S.optional(S.String), ScheduledActionName: S.String, ResourceId: S.String, ScalableDimension: S.String, StartTime: S.optional(S.Date), EndTime: S.optional(S.Date), ScalableTargetAction: S.optional(ScalableTargetAction)}) {}
export class PutScheduledActionResponse extends S.Class<PutScheduledActionResponse>("PutScheduledActionResponse")({}) {}
export class RegisterScalableTargetRequest extends S.Class<RegisterScalableTargetRequest>("RegisterScalableTargetRequest")({ServiceNamespace: S.String, ResourceId: S.String, ScalableDimension: S.String, MinCapacity: S.optional(S.Number), MaxCapacity: S.optional(S.Number), RoleARN: S.optional(S.String), SuspendedState: S.optional(SuspendedState), Tags: S.optional(TagMap)}) {}
export const PredictiveScalingForecastTimestamps = S.Array(S.Date);
export const PredictiveScalingForecastValues = S.Array(S.Number);
export class StepAdjustment extends S.Class<StepAdjustment>("StepAdjustment")({MetricIntervalLowerBound: S.optional(S.Number), MetricIntervalUpperBound: S.optional(S.Number), ScalingAdjustment: S.Number}) {}
export const StepAdjustments = S.Array(StepAdjustment);
export class PredefinedMetricSpecification extends S.Class<PredefinedMetricSpecification>("PredefinedMetricSpecification")({PredefinedMetricType: S.String, ResourceLabel: S.optional(S.String)}) {}
export class ScalableTarget extends S.Class<ScalableTarget>("ScalableTarget")({ServiceNamespace: S.String, ResourceId: S.String, ScalableDimension: S.String, MinCapacity: S.Number, MaxCapacity: S.Number, PredictedCapacity: S.optional(S.Number), RoleARN: S.String, CreationTime: S.Date, SuspendedState: S.optional(SuspendedState), ScalableTargetARN: S.optional(S.String)}) {}
export const ScalableTargets = S.Array(ScalableTarget);
export class ScheduledAction extends S.Class<ScheduledAction>("ScheduledAction")({ScheduledActionName: S.String, ScheduledActionARN: S.String, ServiceNamespace: S.String, Schedule: S.String, Timezone: S.optional(S.String), ResourceId: S.String, ScalableDimension: S.optional(S.String), StartTime: S.optional(S.Date), EndTime: S.optional(S.Date), ScalableTargetAction: S.optional(ScalableTargetAction), CreationTime: S.Date}) {}
export const ScheduledActions = S.Array(ScheduledAction);
export class PredictiveScalingPredefinedMetricPairSpecification extends S.Class<PredictiveScalingPredefinedMetricPairSpecification>("PredictiveScalingPredefinedMetricPairSpecification")({PredefinedMetricType: S.String, ResourceLabel: S.optional(S.String)}) {}
export class PredictiveScalingPredefinedScalingMetricSpecification extends S.Class<PredictiveScalingPredefinedScalingMetricSpecification>("PredictiveScalingPredefinedScalingMetricSpecification")({PredefinedMetricType: S.String, ResourceLabel: S.optional(S.String)}) {}
export class PredictiveScalingPredefinedLoadMetricSpecification extends S.Class<PredictiveScalingPredefinedLoadMetricSpecification>("PredictiveScalingPredefinedLoadMetricSpecification")({PredefinedMetricType: S.String, ResourceLabel: S.optional(S.String)}) {}
export class PredictiveScalingMetricDimension extends S.Class<PredictiveScalingMetricDimension>("PredictiveScalingMetricDimension")({Name: S.String, Value: S.String}) {}
export const PredictiveScalingMetricDimensions = S.Array(PredictiveScalingMetricDimension);
export class PredictiveScalingMetric extends S.Class<PredictiveScalingMetric>("PredictiveScalingMetric")({Dimensions: S.optional(PredictiveScalingMetricDimensions), MetricName: S.optional(S.String), Namespace: S.optional(S.String)}) {}
export class PredictiveScalingMetricStat extends S.Class<PredictiveScalingMetricStat>("PredictiveScalingMetricStat")({Metric: PredictiveScalingMetric, Stat: S.String, Unit: S.optional(S.String)}) {}
export class PredictiveScalingMetricDataQuery extends S.Class<PredictiveScalingMetricDataQuery>("PredictiveScalingMetricDataQuery")({Id: S.String, Expression: S.optional(S.String), MetricStat: S.optional(PredictiveScalingMetricStat), Label: S.optional(S.String), ReturnData: S.optional(S.Boolean)}) {}
export const PredictiveScalingMetricDataQueries = S.Array(PredictiveScalingMetricDataQuery);
export class PredictiveScalingCustomizedMetricSpecification extends S.Class<PredictiveScalingCustomizedMetricSpecification>("PredictiveScalingCustomizedMetricSpecification")({MetricDataQueries: PredictiveScalingMetricDataQueries}) {}
export class PredictiveScalingMetricSpecification extends S.Class<PredictiveScalingMetricSpecification>("PredictiveScalingMetricSpecification")({TargetValue: S.Number, PredefinedMetricPairSpecification: S.optional(PredictiveScalingPredefinedMetricPairSpecification), PredefinedScalingMetricSpecification: S.optional(PredictiveScalingPredefinedScalingMetricSpecification), PredefinedLoadMetricSpecification: S.optional(PredictiveScalingPredefinedLoadMetricSpecification), CustomizedScalingMetricSpecification: S.optional(PredictiveScalingCustomizedMetricSpecification), CustomizedLoadMetricSpecification: S.optional(PredictiveScalingCustomizedMetricSpecification), CustomizedCapacityMetricSpecification: S.optional(PredictiveScalingCustomizedMetricSpecification)}) {}
export class LoadForecast extends S.Class<LoadForecast>("LoadForecast")({Timestamps: PredictiveScalingForecastTimestamps, Values: PredictiveScalingForecastValues, MetricSpecification: PredictiveScalingMetricSpecification}) {}
export const LoadForecasts = S.Array(LoadForecast);
export class CapacityForecast extends S.Class<CapacityForecast>("CapacityForecast")({Timestamps: PredictiveScalingForecastTimestamps, Values: PredictiveScalingForecastValues}) {}
export class StepScalingPolicyConfiguration extends S.Class<StepScalingPolicyConfiguration>("StepScalingPolicyConfiguration")({AdjustmentType: S.optional(S.String), StepAdjustments: S.optional(StepAdjustments), MinAdjustmentMagnitude: S.optional(S.Number), Cooldown: S.optional(S.Number), MetricAggregationType: S.optional(S.String)}) {}
export class MetricDimension extends S.Class<MetricDimension>("MetricDimension")({Name: S.String, Value: S.String}) {}
export const MetricDimensions = S.Array(MetricDimension);
export class DescribeScalableTargetsResponse extends S.Class<DescribeScalableTargetsResponse>("DescribeScalableTargetsResponse")({ScalableTargets: S.optional(ScalableTargets), NextToken: S.optional(S.String)}) {}
export class DescribeScheduledActionsResponse extends S.Class<DescribeScheduledActionsResponse>("DescribeScheduledActionsResponse")({ScheduledActions: S.optional(ScheduledActions), NextToken: S.optional(S.String)}) {}
export class GetPredictiveScalingForecastResponse extends S.Class<GetPredictiveScalingForecastResponse>("GetPredictiveScalingForecastResponse")({LoadForecast: S.optional(LoadForecasts), CapacityForecast: S.optional(CapacityForecast), UpdateTime: S.optional(S.Date)}) {}
export class RegisterScalableTargetResponse extends S.Class<RegisterScalableTargetResponse>("RegisterScalableTargetResponse")({ScalableTargetARN: S.optional(S.String)}) {}
export class NotScaledReason extends S.Class<NotScaledReason>("NotScaledReason")({Code: S.String, MaxCapacity: S.optional(S.Number), MinCapacity: S.optional(S.Number), CurrentCapacity: S.optional(S.Number)}) {}
export const NotScaledReasons = S.Array(NotScaledReason);
export class Alarm extends S.Class<Alarm>("Alarm")({AlarmName: S.String, AlarmARN: S.String}) {}
export const Alarms = S.Array(Alarm);
export class ScalingActivity extends S.Class<ScalingActivity>("ScalingActivity")({ActivityId: S.String, ServiceNamespace: S.String, ResourceId: S.String, ScalableDimension: S.String, Description: S.String, Cause: S.String, StartTime: S.Date, EndTime: S.optional(S.Date), StatusCode: S.String, StatusMessage: S.optional(S.String), Details: S.optional(S.String), NotScaledReasons: S.optional(NotScaledReasons)}) {}
export const ScalingActivities = S.Array(ScalingActivity);
export class TargetTrackingMetricDimension extends S.Class<TargetTrackingMetricDimension>("TargetTrackingMetricDimension")({Name: S.String, Value: S.String}) {}
export const TargetTrackingMetricDimensions = S.Array(TargetTrackingMetricDimension);
export class TargetTrackingMetric extends S.Class<TargetTrackingMetric>("TargetTrackingMetric")({Dimensions: S.optional(TargetTrackingMetricDimensions), MetricName: S.optional(S.String), Namespace: S.optional(S.String)}) {}
export class TargetTrackingMetricStat extends S.Class<TargetTrackingMetricStat>("TargetTrackingMetricStat")({Metric: TargetTrackingMetric, Stat: S.String, Unit: S.optional(S.String)}) {}
export class TargetTrackingMetricDataQuery extends S.Class<TargetTrackingMetricDataQuery>("TargetTrackingMetricDataQuery")({Expression: S.optional(S.String), Id: S.String, Label: S.optional(S.String), MetricStat: S.optional(TargetTrackingMetricStat), ReturnData: S.optional(S.Boolean)}) {}
export const TargetTrackingMetricDataQueries = S.Array(TargetTrackingMetricDataQuery);
export class CustomizedMetricSpecification extends S.Class<CustomizedMetricSpecification>("CustomizedMetricSpecification")({MetricName: S.optional(S.String), Namespace: S.optional(S.String), Dimensions: S.optional(MetricDimensions), Statistic: S.optional(S.String), Unit: S.optional(S.String), Metrics: S.optional(TargetTrackingMetricDataQueries)}) {}
export class TargetTrackingScalingPolicyConfiguration extends S.Class<TargetTrackingScalingPolicyConfiguration>("TargetTrackingScalingPolicyConfiguration")({TargetValue: S.Number, PredefinedMetricSpecification: S.optional(PredefinedMetricSpecification), CustomizedMetricSpecification: S.optional(CustomizedMetricSpecification), ScaleOutCooldown: S.optional(S.Number), ScaleInCooldown: S.optional(S.Number), DisableScaleIn: S.optional(S.Boolean)}) {}
export const PredictiveScalingMetricSpecifications = S.Array(PredictiveScalingMetricSpecification);
export class PredictiveScalingPolicyConfiguration extends S.Class<PredictiveScalingPolicyConfiguration>("PredictiveScalingPolicyConfiguration")({MetricSpecifications: PredictiveScalingMetricSpecifications, Mode: S.optional(S.String), SchedulingBufferTime: S.optional(S.Number), MaxCapacityBreachBehavior: S.optional(S.String), MaxCapacityBuffer: S.optional(S.Number)}) {}
export class ScalingPolicy extends S.Class<ScalingPolicy>("ScalingPolicy")({PolicyARN: S.String, PolicyName: S.String, ServiceNamespace: S.String, ResourceId: S.String, ScalableDimension: S.String, PolicyType: S.String, StepScalingPolicyConfiguration: S.optional(StepScalingPolicyConfiguration), TargetTrackingScalingPolicyConfiguration: S.optional(TargetTrackingScalingPolicyConfiguration), PredictiveScalingPolicyConfiguration: S.optional(PredictiveScalingPolicyConfiguration), Alarms: S.optional(Alarms), CreationTime: S.Date}) {}
export const ScalingPolicies = S.Array(ScalingPolicy);
export class DescribeScalingActivitiesResponse extends S.Class<DescribeScalingActivitiesResponse>("DescribeScalingActivitiesResponse")({ScalingActivities: S.optional(ScalingActivities), NextToken: S.optional(S.String)}) {}
export class DescribeScalingPoliciesResponse extends S.Class<DescribeScalingPoliciesResponse>("DescribeScalingPoliciesResponse")({ScalingPolicies: S.optional(ScalingPolicies), NextToken: S.optional(S.String)}) {}
export class PutScalingPolicyRequest extends S.Class<PutScalingPolicyRequest>("PutScalingPolicyRequest")({PolicyName: S.String, ServiceNamespace: S.String, ResourceId: S.String, ScalableDimension: S.String, PolicyType: S.optional(S.String), StepScalingPolicyConfiguration: S.optional(StepScalingPolicyConfiguration), TargetTrackingScalingPolicyConfiguration: S.optional(TargetTrackingScalingPolicyConfiguration), PredictiveScalingPolicyConfiguration: S.optional(PredictiveScalingPolicyConfiguration)}) {}
export class PutScalingPolicyResponse extends S.Class<PutScalingPolicyResponse>("PutScalingPolicyResponse")({PolicyARN: S.String, Alarms: S.optional(Alarms)}) {}

//# Errors
export class ConcurrentUpdateException extends S.TaggedError<ConcurrentUpdateException>()("ConcurrentUpdateException", {}) {};
export class InternalServiceException extends S.TaggedError<InternalServiceException>()("InternalServiceException", {}) {};
export class ResourceNotFoundException extends S.TaggedError<ResourceNotFoundException>()("ResourceNotFoundException", {}) {};
export class ObjectNotFoundException extends S.TaggedError<ObjectNotFoundException>()("ObjectNotFoundException", {}) {};
export class ValidationException extends S.TaggedError<ValidationException>()("ValidationException", {}) {};
export class InvalidNextTokenException extends S.TaggedError<InvalidNextTokenException>()("InvalidNextTokenException", {}) {};
export class LimitExceededException extends S.TaggedError<LimitExceededException>()("LimitExceededException", {Message: S.optional(S.String)}) {};
export class TooManyTagsException extends S.TaggedError<TooManyTagsException>()("TooManyTagsException", {Message: S.optional(S.String), ResourceName: S.optional(S.String)}) {};
export class FailedResourceAccessException extends S.TaggedError<FailedResourceAccessException>()("FailedResourceAccessException", {Message: S.optional(S.String)}) {};

//# Operations
export const deleteScalingPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.DeleteScalingPolicy" }, DeleteScalingPolicyRequest, DeleteScalingPolicyResponse, [ConcurrentUpdateException, InternalServiceException, ObjectNotFoundException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteScheduledAction = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.DeleteScheduledAction" }, DeleteScheduledActionRequest, DeleteScheduledActionResponse, [ConcurrentUpdateException, InternalServiceException, ObjectNotFoundException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deregisterScalableTarget = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.DeregisterScalableTarget" }, DeregisterScalableTargetRequest, DeregisterScalableTargetResponse, [ConcurrentUpdateException, InternalServiceException, ObjectNotFoundException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [ResourceNotFoundException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeScheduledActions = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.DescribeScheduledActions" }, DescribeScheduledActionsRequest, DescribeScheduledActionsResponse, [ConcurrentUpdateException, InternalServiceException, InvalidNextTokenException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getPredictiveScalingForecast = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.GetPredictiveScalingForecast" }, GetPredictiveScalingForecastRequest, GetPredictiveScalingForecastResponse, [InternalServiceException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const putScheduledAction = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.PutScheduledAction" }, PutScheduledActionRequest, PutScheduledActionResponse, [ConcurrentUpdateException, InternalServiceException, LimitExceededException, ObjectNotFoundException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const registerScalableTarget = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.RegisterScalableTarget" }, RegisterScalableTargetRequest, RegisterScalableTargetResponse, [ConcurrentUpdateException, InternalServiceException, LimitExceededException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.TagResource" }, TagResourceRequest, TagResourceResponse, [ResourceNotFoundException, TooManyTagsException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeScalableTargets = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.DescribeScalableTargets" }, DescribeScalableTargetsRequest, DescribeScalableTargetsResponse, [ConcurrentUpdateException, InternalServiceException, InvalidNextTokenException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeScalingActivities = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.DescribeScalingActivities" }, DescribeScalingActivitiesRequest, DescribeScalingActivitiesResponse, [ConcurrentUpdateException, InternalServiceException, InvalidNextTokenException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeScalingPolicies = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.DescribeScalingPolicies" }, DescribeScalingPoliciesRequest, DescribeScalingPoliciesResponse, [ConcurrentUpdateException, FailedResourceAccessException, InternalServiceException, InvalidNextTokenException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const putScalingPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2016-02-06", uri: "/", method: "POST", sdkId: "Application Auto Scaling", sigV4ServiceName: "application-autoscaling", name: "AnyScaleFrontendService.PutScalingPolicy" }, PutScalingPolicyRequest, PutScalingPolicyResponse, [ConcurrentUpdateException, FailedResourceAccessException, InternalServiceException, LimitExceededException, ObjectNotFoundException, ValidationException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
