import * as S from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const SecurityGroups = S.Array(S.String);
export const TagKeys = S.Array(S.String);
export class Tag extends S.Class<Tag>("Tag")({Key: S.String, Value: S.String}) {}
export const Tags = S.Array(Tag);
export class CreateFileSystemRequest extends S.Class<CreateFileSystemRequest>("CreateFileSystemRequest")({CreationToken: S.String, PerformanceMode: S.optional(S.String), Encrypted: S.optional(S.Boolean), KmsKeyId: S.optional(S.String), ThroughputMode: S.optional(S.String), ProvisionedThroughputInMibps: S.optional(S.Number), AvailabilityZoneName: S.optional(S.String), Backup: S.optional(S.Boolean), Tags: S.optional(Tags)}) {}
export class CreateMountTargetRequest extends S.Class<CreateMountTargetRequest>("CreateMountTargetRequest")({FileSystemId: S.String, SubnetId: S.String, IpAddress: S.optional(S.String), Ipv6Address: S.optional(S.String), IpAddressType: S.optional(S.String), SecurityGroups: S.optional(SecurityGroups)}) {}
export class CreateTagsRequest extends S.Class<CreateTagsRequest>("CreateTagsRequest")({FileSystemId: S.String, Tags: Tags}) {}
export class DeleteAccessPointRequest extends S.Class<DeleteAccessPointRequest>("DeleteAccessPointRequest")({AccessPointId: S.String}) {}
export class DeleteFileSystemRequest extends S.Class<DeleteFileSystemRequest>("DeleteFileSystemRequest")({FileSystemId: S.String}) {}
export class DeleteFileSystemPolicyRequest extends S.Class<DeleteFileSystemPolicyRequest>("DeleteFileSystemPolicyRequest")({FileSystemId: S.String}) {}
export class DeleteMountTargetRequest extends S.Class<DeleteMountTargetRequest>("DeleteMountTargetRequest")({MountTargetId: S.String}) {}
export class DeleteReplicationConfigurationRequest extends S.Class<DeleteReplicationConfigurationRequest>("DeleteReplicationConfigurationRequest")({SourceFileSystemId: S.String, DeletionMode: S.optional(S.String)}) {}
export class DeleteTagsRequest extends S.Class<DeleteTagsRequest>("DeleteTagsRequest")({FileSystemId: S.String, TagKeys: TagKeys}) {}
export class DescribeAccessPointsRequest extends S.Class<DescribeAccessPointsRequest>("DescribeAccessPointsRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), AccessPointId: S.optional(S.String), FileSystemId: S.optional(S.String)}) {}
export class DescribeAccountPreferencesRequest extends S.Class<DescribeAccountPreferencesRequest>("DescribeAccountPreferencesRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class DescribeBackupPolicyRequest extends S.Class<DescribeBackupPolicyRequest>("DescribeBackupPolicyRequest")({FileSystemId: S.String}) {}
export class DescribeFileSystemPolicyRequest extends S.Class<DescribeFileSystemPolicyRequest>("DescribeFileSystemPolicyRequest")({FileSystemId: S.String}) {}
export class DescribeFileSystemsRequest extends S.Class<DescribeFileSystemsRequest>("DescribeFileSystemsRequest")({MaxItems: S.optional(S.Number), Marker: S.optional(S.String), CreationToken: S.optional(S.String), FileSystemId: S.optional(S.String)}) {}
export class DescribeLifecycleConfigurationRequest extends S.Class<DescribeLifecycleConfigurationRequest>("DescribeLifecycleConfigurationRequest")({FileSystemId: S.String}) {}
export class DescribeMountTargetsRequest extends S.Class<DescribeMountTargetsRequest>("DescribeMountTargetsRequest")({MaxItems: S.optional(S.Number), Marker: S.optional(S.String), FileSystemId: S.optional(S.String), MountTargetId: S.optional(S.String), AccessPointId: S.optional(S.String)}) {}
export class DescribeMountTargetSecurityGroupsRequest extends S.Class<DescribeMountTargetSecurityGroupsRequest>("DescribeMountTargetSecurityGroupsRequest")({MountTargetId: S.String}) {}
export class DescribeReplicationConfigurationsRequest extends S.Class<DescribeReplicationConfigurationsRequest>("DescribeReplicationConfigurationsRequest")({FileSystemId: S.optional(S.String), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class DescribeTagsRequest extends S.Class<DescribeTagsRequest>("DescribeTagsRequest")({MaxItems: S.optional(S.Number), Marker: S.optional(S.String), FileSystemId: S.String}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceId: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ModifyMountTargetSecurityGroupsRequest extends S.Class<ModifyMountTargetSecurityGroupsRequest>("ModifyMountTargetSecurityGroupsRequest")({MountTargetId: S.String, SecurityGroups: S.optional(SecurityGroups)}) {}
export class PutAccountPreferencesRequest extends S.Class<PutAccountPreferencesRequest>("PutAccountPreferencesRequest")({ResourceIdType: S.String}) {}
export class PutFileSystemPolicyRequest extends S.Class<PutFileSystemPolicyRequest>("PutFileSystemPolicyRequest")({FileSystemId: S.String, Policy: S.String, BypassPolicyLockoutSafetyCheck: S.optional(S.Boolean)}) {}
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceId: S.String, Tags: Tags}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceId: S.String, TagKeys: TagKeys}) {}
export class UpdateFileSystemRequest extends S.Class<UpdateFileSystemRequest>("UpdateFileSystemRequest")({FileSystemId: S.String, ThroughputMode: S.optional(S.String), ProvisionedThroughputInMibps: S.optional(S.Number)}) {}
export class UpdateFileSystemProtectionRequest extends S.Class<UpdateFileSystemProtectionRequest>("UpdateFileSystemProtectionRequest")({FileSystemId: S.String, ReplicationOverwriteProtection: S.optional(S.String)}) {}
export const SecondaryGids = S.Array(S.Number);
export class PosixUser extends S.Class<PosixUser>("PosixUser")({Uid: S.Number, Gid: S.Number, SecondaryGids: S.optional(SecondaryGids)}) {}
export class DestinationToCreate extends S.Class<DestinationToCreate>("DestinationToCreate")({Region: S.optional(S.String), AvailabilityZoneName: S.optional(S.String), KmsKeyId: S.optional(S.String), FileSystemId: S.optional(S.String), RoleArn: S.optional(S.String)}) {}
export const DestinationsToCreate = S.Array(DestinationToCreate);
export class FileSystemSize extends S.Class<FileSystemSize>("FileSystemSize")({Value: S.Number, Timestamp: S.optional(S.Date), ValueInIA: S.optional(S.Number), ValueInStandard: S.optional(S.Number), ValueInArchive: S.optional(S.Number)}) {}
export class FileSystemProtectionDescription extends S.Class<FileSystemProtectionDescription>("FileSystemProtectionDescription")({ReplicationOverwriteProtection: S.optional(S.String)}) {}
export class FileSystemDescription extends S.Class<FileSystemDescription>("FileSystemDescription")({OwnerId: S.String, CreationToken: S.String, FileSystemId: S.String, FileSystemArn: S.optional(S.String), CreationTime: S.Date, LifeCycleState: S.String, Name: S.optional(S.String), NumberOfMountTargets: S.Number, SizeInBytes: FileSystemSize, PerformanceMode: S.String, Encrypted: S.optional(S.Boolean), KmsKeyId: S.optional(S.String), ThroughputMode: S.optional(S.String), ProvisionedThroughputInMibps: S.optional(S.Number), AvailabilityZoneName: S.optional(S.String), AvailabilityZoneId: S.optional(S.String), Tags: Tags, FileSystemProtection: S.optional(FileSystemProtectionDescription)}) {}
export const FileSystemDescriptions = S.Array(FileSystemDescription);
export class MountTargetDescription extends S.Class<MountTargetDescription>("MountTargetDescription")({OwnerId: S.optional(S.String), MountTargetId: S.String, FileSystemId: S.String, SubnetId: S.String, LifeCycleState: S.String, IpAddress: S.optional(S.String), Ipv6Address: S.optional(S.String), NetworkInterfaceId: S.optional(S.String), AvailabilityZoneId: S.optional(S.String), AvailabilityZoneName: S.optional(S.String), VpcId: S.optional(S.String)}) {}
export const MountTargetDescriptions = S.Array(MountTargetDescription);
export class BackupPolicy extends S.Class<BackupPolicy>("BackupPolicy")({Status: S.String}) {}
export class LifecyclePolicy extends S.Class<LifecyclePolicy>("LifecyclePolicy")({TransitionToIA: S.optional(S.String), TransitionToPrimaryStorageClass: S.optional(S.String), TransitionToArchive: S.optional(S.String)}) {}
export const LifecyclePolicies = S.Array(LifecyclePolicy);
export class CreateReplicationConfigurationRequest extends S.Class<CreateReplicationConfigurationRequest>("CreateReplicationConfigurationRequest")({SourceFileSystemId: S.String, Destinations: DestinationsToCreate}) {}
export class BackupPolicyDescription extends S.Class<BackupPolicyDescription>("BackupPolicyDescription")({BackupPolicy: S.optional(BackupPolicy)}) {}
export class FileSystemPolicyDescription extends S.Class<FileSystemPolicyDescription>("FileSystemPolicyDescription")({FileSystemId: S.optional(S.String), Policy: S.optional(S.String)}) {}
export class DescribeFileSystemsResponse extends S.Class<DescribeFileSystemsResponse>("DescribeFileSystemsResponse")({Marker: S.optional(S.String), FileSystems: S.optional(FileSystemDescriptions), NextMarker: S.optional(S.String)}) {}
export class LifecycleConfigurationDescription extends S.Class<LifecycleConfigurationDescription>("LifecycleConfigurationDescription")({LifecyclePolicies: S.optional(LifecyclePolicies)}) {}
export class DescribeMountTargetsResponse extends S.Class<DescribeMountTargetsResponse>("DescribeMountTargetsResponse")({Marker: S.optional(S.String), MountTargets: S.optional(MountTargetDescriptions), NextMarker: S.optional(S.String)}) {}
export class DescribeMountTargetSecurityGroupsResponse extends S.Class<DescribeMountTargetSecurityGroupsResponse>("DescribeMountTargetSecurityGroupsResponse")({SecurityGroups: SecurityGroups}) {}
export class DescribeTagsResponse extends S.Class<DescribeTagsResponse>("DescribeTagsResponse")({Marker: S.optional(S.String), Tags: Tags, NextMarker: S.optional(S.String)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: S.optional(Tags), NextToken: S.optional(S.String)}) {}
export const Resources = S.Array(S.String);
export class ResourceIdPreference extends S.Class<ResourceIdPreference>("ResourceIdPreference")({ResourceIdType: S.optional(S.String), Resources: S.optional(Resources)}) {}
export class PutAccountPreferencesResponse extends S.Class<PutAccountPreferencesResponse>("PutAccountPreferencesResponse")({ResourceIdPreference: S.optional(ResourceIdPreference)}) {}
export class PutBackupPolicyRequest extends S.Class<PutBackupPolicyRequest>("PutBackupPolicyRequest")({FileSystemId: S.String, BackupPolicy: BackupPolicy}) {}
export class PutLifecycleConfigurationRequest extends S.Class<PutLifecycleConfigurationRequest>("PutLifecycleConfigurationRequest")({FileSystemId: S.String, LifecyclePolicies: LifecyclePolicies}) {}
export class CreationInfo extends S.Class<CreationInfo>("CreationInfo")({OwnerUid: S.Number, OwnerGid: S.Number, Permissions: S.String}) {}
export class RootDirectory extends S.Class<RootDirectory>("RootDirectory")({Path: S.optional(S.String), CreationInfo: S.optional(CreationInfo)}) {}
export class AccessPointDescription extends S.Class<AccessPointDescription>("AccessPointDescription")({ClientToken: S.optional(S.String), Name: S.optional(S.String), Tags: S.optional(Tags), AccessPointId: S.optional(S.String), AccessPointArn: S.optional(S.String), FileSystemId: S.optional(S.String), PosixUser: S.optional(PosixUser), RootDirectory: S.optional(RootDirectory), OwnerId: S.optional(S.String), LifeCycleState: S.optional(S.String)}) {}
export const AccessPointDescriptions = S.Array(AccessPointDescription);
export class CreateAccessPointRequest extends S.Class<CreateAccessPointRequest>("CreateAccessPointRequest")({ClientToken: S.String, Tags: S.optional(Tags), FileSystemId: S.String, PosixUser: S.optional(PosixUser), RootDirectory: S.optional(RootDirectory)}) {}
export class DescribeAccessPointsResponse extends S.Class<DescribeAccessPointsResponse>("DescribeAccessPointsResponse")({AccessPoints: S.optional(AccessPointDescriptions), NextToken: S.optional(S.String)}) {}
export class DescribeAccountPreferencesResponse extends S.Class<DescribeAccountPreferencesResponse>("DescribeAccountPreferencesResponse")({ResourceIdPreference: S.optional(ResourceIdPreference), NextToken: S.optional(S.String)}) {}
export class Destination extends S.Class<Destination>("Destination")({Status: S.String, FileSystemId: S.String, Region: S.String, LastReplicatedTimestamp: S.optional(S.Date), OwnerId: S.optional(S.String), StatusMessage: S.optional(S.String), RoleArn: S.optional(S.String)}) {}
export const Destinations = S.Array(Destination);
export class ReplicationConfigurationDescription extends S.Class<ReplicationConfigurationDescription>("ReplicationConfigurationDescription")({SourceFileSystemId: S.String, SourceFileSystemRegion: S.String, SourceFileSystemArn: S.String, OriginalSourceFileSystemArn: S.String, CreationTime: S.Date, Destinations: Destinations, SourceFileSystemOwnerId: S.optional(S.String)}) {}
export const ReplicationConfigurationDescriptions = S.Array(ReplicationConfigurationDescription);
export class DescribeReplicationConfigurationsResponse extends S.Class<DescribeReplicationConfigurationsResponse>("DescribeReplicationConfigurationsResponse")({Replications: S.optional(ReplicationConfigurationDescriptions), NextToken: S.optional(S.String)}) {}

//# Errors
export class BadRequest extends S.TaggedError<BadRequest>()("BadRequest", {}) {};
export class FileSystemNotFound extends S.TaggedError<FileSystemNotFound>()("FileSystemNotFound", {}) {};
export class InternalServerError extends S.TaggedError<InternalServerError>()("InternalServerError", {}) {};
export class AccessPointNotFound extends S.TaggedError<AccessPointNotFound>()("AccessPointNotFound", {}) {};
export class IncorrectFileSystemLifeCycleState extends S.TaggedError<IncorrectFileSystemLifeCycleState>()("IncorrectFileSystemLifeCycleState", {}) {};
export class FileSystemInUse extends S.TaggedError<FileSystemInUse>()("FileSystemInUse", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class DependencyTimeout extends S.TaggedError<DependencyTimeout>()("DependencyTimeout", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class PolicyNotFound extends S.TaggedError<PolicyNotFound>()("PolicyNotFound", {}) {};
export class MountTargetNotFound extends S.TaggedError<MountTargetNotFound>()("MountTargetNotFound", {}) {};
export class IncorrectMountTargetState extends S.TaggedError<IncorrectMountTargetState>()("IncorrectMountTargetState", {}) {};
export class InsufficientThroughputCapacity extends S.TaggedError<InsufficientThroughputCapacity>()("InsufficientThroughputCapacity", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class AvailabilityZonesMismatch extends S.TaggedError<AvailabilityZonesMismatch>()("AvailabilityZonesMismatch", {ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {};
export class ConflictException extends S.TaggedError<ConflictException>()("ConflictException", {ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {};
export class ReplicationNotFound extends S.TaggedError<ReplicationNotFound>()("ReplicationNotFound", {ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {};
export class ValidationException extends S.TaggedError<ValidationException>()("ValidationException", {}) {};
export class SecurityGroupLimitExceeded extends S.TaggedError<SecurityGroupLimitExceeded>()("SecurityGroupLimitExceeded", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class InvalidPolicyException extends S.TaggedError<InvalidPolicyException>()("InvalidPolicyException", {ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {};
export class ThroughputLimitExceeded extends S.TaggedError<ThroughputLimitExceeded>()("ThroughputLimitExceeded", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class ReplicationAlreadyExists extends S.TaggedError<ReplicationAlreadyExists>()("ReplicationAlreadyExists", {ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {};
export class TooManyRequests extends S.TaggedError<TooManyRequests>()("TooManyRequests", {}) {};
export class AccessPointAlreadyExists extends S.TaggedError<AccessPointAlreadyExists>()("AccessPointAlreadyExists", {ErrorCode: S.String, Message: S.optional(S.String), AccessPointId: S.String}) {};
export class FileSystemAlreadyExists extends S.TaggedError<FileSystemAlreadyExists>()("FileSystemAlreadyExists", {ErrorCode: S.String, Message: S.optional(S.String), FileSystemId: S.String}) {};
export class FileSystemLimitExceeded extends S.TaggedError<FileSystemLimitExceeded>()("FileSystemLimitExceeded", {}) {};
export class IpAddressInUse extends S.TaggedError<IpAddressInUse>()("IpAddressInUse", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class UnsupportedAvailabilityZone extends S.TaggedError<UnsupportedAvailabilityZone>()("UnsupportedAvailabilityZone", {}) {};
export class SecurityGroupNotFound extends S.TaggedError<SecurityGroupNotFound>()("SecurityGroupNotFound", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class AccessPointLimitExceeded extends S.TaggedError<AccessPointLimitExceeded>()("AccessPointLimitExceeded", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class MountTargetConflict extends S.TaggedError<MountTargetConflict>()("MountTargetConflict", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class ThrottlingException extends S.TaggedError<ThrottlingException>()("ThrottlingException", {ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {};
export class NetworkInterfaceLimitExceeded extends S.TaggedError<NetworkInterfaceLimitExceeded>()("NetworkInterfaceLimitExceeded", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class NoFreeAddressesInSubnet extends S.TaggedError<NoFreeAddressesInSubnet>()("NoFreeAddressesInSubnet", {ErrorCode: S.String, Message: S.optional(S.String)}) {};
export class SubnetNotFound extends S.TaggedError<SubnetNotFound>()("SubnetNotFound", {ErrorCode: S.String, Message: S.optional(S.String)}) {};

//# Operations
export const deleteTags = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/delete-tags/{FileSystemId}", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteTags" }, DeleteTagsRequest, S.Struct({}), [BadRequest, FileSystemNotFound, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/resource-tags/{ResourceId}", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.TagResource" }, TagResourceRequest, S.Struct({}), [AccessPointNotFound, BadRequest, FileSystemNotFound, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/resource-tags/{ResourceId}", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.UntagResource" }, UntagResourceRequest, S.Struct({}), [AccessPointNotFound, BadRequest, FileSystemNotFound, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createTags = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/create-tags/{FileSystemId}", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.CreateTags" }, CreateTagsRequest, S.Struct({}), [BadRequest, FileSystemNotFound, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAccessPoint = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/access-points/{AccessPointId}", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteAccessPoint" }, DeleteAccessPointRequest, S.Struct({}), [AccessPointNotFound, BadRequest, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteFileSystem = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteFileSystem" }, DeleteFileSystemRequest, S.Struct({}), [BadRequest, FileSystemInUse, FileSystemNotFound, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteFileSystemPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/policy", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteFileSystemPolicy" }, DeleteFileSystemPolicyRequest, S.Struct({}), [BadRequest, FileSystemNotFound, IncorrectFileSystemLifeCycleState, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeFileSystemPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/policy", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeFileSystemPolicy" }, DescribeFileSystemPolicyRequest, FileSystemPolicyDescription, [BadRequest, FileSystemNotFound, InternalServerError, PolicyNotFound]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeFileSystems = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeFileSystems" }, DescribeFileSystemsRequest, DescribeFileSystemsResponse, [BadRequest, FileSystemNotFound, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLifecycleConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/lifecycle-configuration", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeLifecycleConfiguration" }, DescribeLifecycleConfigurationRequest, LifecycleConfigurationDescription, [BadRequest, FileSystemNotFound, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeMountTargets = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/mount-targets", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeMountTargets" }, DescribeMountTargetsRequest, DescribeMountTargetsResponse, [AccessPointNotFound, BadRequest, FileSystemNotFound, InternalServerError, MountTargetNotFound]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeMountTargetSecurityGroups = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/mount-targets/{MountTargetId}/security-groups", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeMountTargetSecurityGroups" }, DescribeMountTargetSecurityGroupsRequest, DescribeMountTargetSecurityGroupsResponse, [BadRequest, IncorrectMountTargetState, InternalServerError, MountTargetNotFound]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeTags = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/tags/{FileSystemId}", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeTags" }, DescribeTagsRequest, DescribeTagsResponse, [BadRequest, FileSystemNotFound, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/resource-tags/{ResourceId}", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [AccessPointNotFound, BadRequest, FileSystemNotFound, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putAccountPreferences = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/account-preferences", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.PutAccountPreferences" }, PutAccountPreferencesRequest, PutAccountPreferencesResponse, [BadRequest, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putLifecycleConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/lifecycle-configuration", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.PutLifecycleConfiguration" }, PutLifecycleConfigurationRequest, LifecycleConfigurationDescription, [BadRequest, FileSystemNotFound, IncorrectFileSystemLifeCycleState, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteMountTarget = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/mount-targets/{MountTargetId}", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteMountTarget" }, DeleteMountTargetRequest, S.Struct({}), [BadRequest, DependencyTimeout, InternalServerError, MountTargetNotFound]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteReplicationConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{SourceFileSystemId}/replication-configuration", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteReplicationConfiguration" }, DeleteReplicationConfigurationRequest, S.Struct({}), [BadRequest, FileSystemNotFound, InternalServerError, ReplicationNotFound]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAccessPoints = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/access-points", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeAccessPoints" }, DescribeAccessPointsRequest, DescribeAccessPointsResponse, [AccessPointNotFound, BadRequest, FileSystemNotFound, InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAccountPreferences = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/account-preferences", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeAccountPreferences" }, DescribeAccountPreferencesRequest, DescribeAccountPreferencesResponse, [InternalServerError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeBackupPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/backup-policy", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeBackupPolicy" }, DescribeBackupPolicyRequest, BackupPolicyDescription, [BadRequest, FileSystemNotFound, InternalServerError, PolicyNotFound, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putBackupPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/backup-policy", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.PutBackupPolicy" }, PutBackupPolicyRequest, BackupPolicyDescription, [BadRequest, FileSystemNotFound, IncorrectFileSystemLifeCycleState, InternalServerError, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putFileSystemPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/policy", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.PutFileSystemPolicy" }, PutFileSystemPolicyRequest, FileSystemPolicyDescription, [BadRequest, FileSystemNotFound, IncorrectFileSystemLifeCycleState, InternalServerError, InvalidPolicyException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateFileSystemProtection = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/protection", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.UpdateFileSystemProtection" }, UpdateFileSystemProtectionRequest, FileSystemProtectionDescription, [BadRequest, FileSystemNotFound, IncorrectFileSystemLifeCycleState, InsufficientThroughputCapacity, InternalServerError, ReplicationAlreadyExists, ThroughputLimitExceeded, TooManyRequests]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createReplicationConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{SourceFileSystemId}/replication-configuration", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.CreateReplicationConfiguration" }, CreateReplicationConfigurationRequest, ReplicationConfigurationDescription, [BadRequest, ConflictException, FileSystemLimitExceeded, FileSystemNotFound, IncorrectFileSystemLifeCycleState, InsufficientThroughputCapacity, InternalServerError, ReplicationNotFound, ThroughputLimitExceeded, UnsupportedAvailabilityZone, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeReplicationConfigurations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/replication-configurations", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeReplicationConfigurations" }, DescribeReplicationConfigurationsRequest, DescribeReplicationConfigurationsResponse, [BadRequest, FileSystemNotFound, InternalServerError, ReplicationNotFound, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const modifyMountTargetSecurityGroups = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/mount-targets/{MountTargetId}/security-groups", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.ModifyMountTargetSecurityGroups" }, ModifyMountTargetSecurityGroupsRequest, S.Struct({}), [BadRequest, IncorrectMountTargetState, InternalServerError, MountTargetNotFound, SecurityGroupLimitExceeded, SecurityGroupNotFound]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateFileSystem = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.UpdateFileSystem" }, UpdateFileSystemRequest, FileSystemDescription, [BadRequest, FileSystemNotFound, IncorrectFileSystemLifeCycleState, InsufficientThroughputCapacity, InternalServerError, ThroughputLimitExceeded, TooManyRequests]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createFileSystem = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.CreateFileSystem" }, CreateFileSystemRequest, FileSystemDescription, [BadRequest, FileSystemAlreadyExists, FileSystemLimitExceeded, InsufficientThroughputCapacity, InternalServerError, ThroughputLimitExceeded, UnsupportedAvailabilityZone]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createAccessPoint = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/access-points", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.CreateAccessPoint" }, CreateAccessPointRequest, AccessPointDescription, [AccessPointAlreadyExists, AccessPointLimitExceeded, BadRequest, FileSystemNotFound, IncorrectFileSystemLifeCycleState, InternalServerError, ThrottlingException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createMountTarget = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/mount-targets", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.CreateMountTarget" }, CreateMountTargetRequest, MountTargetDescription, [AvailabilityZonesMismatch, BadRequest, FileSystemNotFound, IncorrectFileSystemLifeCycleState, InternalServerError, IpAddressInUse, MountTargetConflict, NetworkInterfaceLimitExceeded, NoFreeAddressesInSubnet, SecurityGroupLimitExceeded, SecurityGroupNotFound, SubnetNotFound, UnsupportedAvailabilityZone]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
