import * as S from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const DataBundleArns = S.Array(S.String);
export const AvailabilityZoneIds = S.Array(S.String);
export const TagKeyList = S.Array(S.String);
export const TagMap = S.Record({key: S.String, value: S.String});
export class CreateKxDatabaseRequest extends S.Class<CreateKxDatabaseRequest>("CreateKxDatabaseRequest")({environmentId: S.String, databaseName: S.String, description: S.optional(S.String), tags: S.optional(TagMap), clientToken: S.String}) {}
export class CreateKxEnvironmentRequest extends S.Class<CreateKxEnvironmentRequest>("CreateKxEnvironmentRequest")({name: S.String, description: S.optional(S.String), kmsKeyId: S.String, tags: S.optional(TagMap), clientToken: S.optional(S.String)}) {}
export class CreateKxScalingGroupRequest extends S.Class<CreateKxScalingGroupRequest>("CreateKxScalingGroupRequest")({clientToken: S.String, environmentId: S.String, scalingGroupName: S.String, hostType: S.String, availabilityZoneId: S.String, tags: S.optional(TagMap)}) {}
export class CreateKxUserRequest extends S.Class<CreateKxUserRequest>("CreateKxUserRequest")({environmentId: S.String, userName: S.String, iamRole: S.String, tags: S.optional(TagMap), clientToken: S.optional(S.String)}) {}
export class DeleteEnvironmentRequest extends S.Class<DeleteEnvironmentRequest>("DeleteEnvironmentRequest")({environmentId: S.String}) {}
export class DeleteEnvironmentResponse extends S.Class<DeleteEnvironmentResponse>("DeleteEnvironmentResponse")({}) {}
export class DeleteKxClusterRequest extends S.Class<DeleteKxClusterRequest>("DeleteKxClusterRequest")({environmentId: S.String, clusterName: S.String, clientToken: S.optional(S.String)}) {}
export class DeleteKxClusterResponse extends S.Class<DeleteKxClusterResponse>("DeleteKxClusterResponse")({}) {}
export class DeleteKxClusterNodeRequest extends S.Class<DeleteKxClusterNodeRequest>("DeleteKxClusterNodeRequest")({environmentId: S.String, clusterName: S.String, nodeId: S.String}) {}
export class DeleteKxClusterNodeResponse extends S.Class<DeleteKxClusterNodeResponse>("DeleteKxClusterNodeResponse")({}) {}
export class DeleteKxDatabaseRequest extends S.Class<DeleteKxDatabaseRequest>("DeleteKxDatabaseRequest")({environmentId: S.String, databaseName: S.String, clientToken: S.String}) {}
export class DeleteKxDatabaseResponse extends S.Class<DeleteKxDatabaseResponse>("DeleteKxDatabaseResponse")({}) {}
export class DeleteKxDataviewRequest extends S.Class<DeleteKxDataviewRequest>("DeleteKxDataviewRequest")({environmentId: S.String, databaseName: S.String, dataviewName: S.String, clientToken: S.String}) {}
export class DeleteKxDataviewResponse extends S.Class<DeleteKxDataviewResponse>("DeleteKxDataviewResponse")({}) {}
export class DeleteKxEnvironmentRequest extends S.Class<DeleteKxEnvironmentRequest>("DeleteKxEnvironmentRequest")({environmentId: S.String, clientToken: S.optional(S.String)}) {}
export class DeleteKxEnvironmentResponse extends S.Class<DeleteKxEnvironmentResponse>("DeleteKxEnvironmentResponse")({}) {}
export class DeleteKxScalingGroupRequest extends S.Class<DeleteKxScalingGroupRequest>("DeleteKxScalingGroupRequest")({environmentId: S.String, scalingGroupName: S.String, clientToken: S.optional(S.String)}) {}
export class DeleteKxScalingGroupResponse extends S.Class<DeleteKxScalingGroupResponse>("DeleteKxScalingGroupResponse")({}) {}
export class DeleteKxUserRequest extends S.Class<DeleteKxUserRequest>("DeleteKxUserRequest")({userName: S.String, environmentId: S.String, clientToken: S.optional(S.String)}) {}
export class DeleteKxUserResponse extends S.Class<DeleteKxUserResponse>("DeleteKxUserResponse")({}) {}
export class DeleteKxVolumeRequest extends S.Class<DeleteKxVolumeRequest>("DeleteKxVolumeRequest")({environmentId: S.String, volumeName: S.String, clientToken: S.optional(S.String)}) {}
export class DeleteKxVolumeResponse extends S.Class<DeleteKxVolumeResponse>("DeleteKxVolumeResponse")({}) {}
export class GetEnvironmentRequest extends S.Class<GetEnvironmentRequest>("GetEnvironmentRequest")({environmentId: S.String}) {}
export class GetKxChangesetRequest extends S.Class<GetKxChangesetRequest>("GetKxChangesetRequest")({environmentId: S.String, databaseName: S.String, changesetId: S.String}) {}
export class GetKxClusterRequest extends S.Class<GetKxClusterRequest>("GetKxClusterRequest")({environmentId: S.String, clusterName: S.String}) {}
export class GetKxConnectionStringRequest extends S.Class<GetKxConnectionStringRequest>("GetKxConnectionStringRequest")({userArn: S.String, environmentId: S.String, clusterName: S.String}) {}
export class GetKxDatabaseRequest extends S.Class<GetKxDatabaseRequest>("GetKxDatabaseRequest")({environmentId: S.String, databaseName: S.String}) {}
export class GetKxDataviewRequest extends S.Class<GetKxDataviewRequest>("GetKxDataviewRequest")({environmentId: S.String, databaseName: S.String, dataviewName: S.String}) {}
export class GetKxEnvironmentRequest extends S.Class<GetKxEnvironmentRequest>("GetKxEnvironmentRequest")({environmentId: S.String}) {}
export class GetKxScalingGroupRequest extends S.Class<GetKxScalingGroupRequest>("GetKxScalingGroupRequest")({environmentId: S.String, scalingGroupName: S.String}) {}
export class GetKxUserRequest extends S.Class<GetKxUserRequest>("GetKxUserRequest")({userName: S.String, environmentId: S.String}) {}
export class GetKxVolumeRequest extends S.Class<GetKxVolumeRequest>("GetKxVolumeRequest")({environmentId: S.String, volumeName: S.String}) {}
export class ListEnvironmentsRequest extends S.Class<ListEnvironmentsRequest>("ListEnvironmentsRequest")({nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListKxChangesetsRequest extends S.Class<ListKxChangesetsRequest>("ListKxChangesetsRequest")({environmentId: S.String, databaseName: S.String, nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListKxClusterNodesRequest extends S.Class<ListKxClusterNodesRequest>("ListKxClusterNodesRequest")({environmentId: S.String, clusterName: S.String, nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListKxClustersRequest extends S.Class<ListKxClustersRequest>("ListKxClustersRequest")({environmentId: S.String, clusterType: S.optional(S.String), maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export class ListKxDatabasesRequest extends S.Class<ListKxDatabasesRequest>("ListKxDatabasesRequest")({environmentId: S.String, nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListKxDataviewsRequest extends S.Class<ListKxDataviewsRequest>("ListKxDataviewsRequest")({environmentId: S.String, databaseName: S.String, nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListKxEnvironmentsRequest extends S.Class<ListKxEnvironmentsRequest>("ListKxEnvironmentsRequest")({nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListKxScalingGroupsRequest extends S.Class<ListKxScalingGroupsRequest>("ListKxScalingGroupsRequest")({environmentId: S.String, maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export class ListKxUsersRequest extends S.Class<ListKxUsersRequest>("ListKxUsersRequest")({environmentId: S.String, nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListKxVolumesRequest extends S.Class<ListKxVolumesRequest>("ListKxVolumesRequest")({environmentId: S.String, maxResults: S.optional(S.Number), nextToken: S.optional(S.String), volumeType: S.optional(S.String)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({resourceArn: S.String}) {}
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({resourceArn: S.String, tags: TagMap}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({resourceArn: S.String, tagKeys: TagKeyList}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export const AttributeMap = S.Record({key: S.String, value: S.String});
export class FederationParameters extends S.Class<FederationParameters>("FederationParameters")({samlMetadataDocument: S.optional(S.String), samlMetadataURL: S.optional(S.String), applicationCallBackURL: S.optional(S.String), federationURN: S.optional(S.String), federationProviderName: S.optional(S.String), attributeMap: S.optional(AttributeMap)}) {}
export class UpdateEnvironmentRequest extends S.Class<UpdateEnvironmentRequest>("UpdateEnvironmentRequest")({environmentId: S.String, name: S.optional(S.String), description: S.optional(S.String), federationMode: S.optional(S.String), federationParameters: S.optional(FederationParameters)}) {}
export class UpdateKxDatabaseRequest extends S.Class<UpdateKxDatabaseRequest>("UpdateKxDatabaseRequest")({environmentId: S.String, databaseName: S.String, description: S.optional(S.String), clientToken: S.String}) {}
export const SegmentConfigurationDbPathList = S.Array(S.String);
export class KxDataviewSegmentConfiguration extends S.Class<KxDataviewSegmentConfiguration>("KxDataviewSegmentConfiguration")({dbPaths: SegmentConfigurationDbPathList, volumeName: S.String, onDemand: S.optional(S.Boolean)}) {}
export const KxDataviewSegmentConfigurationList = S.Array(KxDataviewSegmentConfiguration);
export class UpdateKxDataviewRequest extends S.Class<UpdateKxDataviewRequest>("UpdateKxDataviewRequest")({environmentId: S.String, databaseName: S.String, dataviewName: S.String, description: S.optional(S.String), changesetId: S.optional(S.String), segmentConfigurations: S.optional(KxDataviewSegmentConfigurationList), clientToken: S.String}) {}
export class UpdateKxEnvironmentRequest extends S.Class<UpdateKxEnvironmentRequest>("UpdateKxEnvironmentRequest")({environmentId: S.String, name: S.optional(S.String), description: S.optional(S.String), clientToken: S.optional(S.String)}) {}
export class UpdateKxUserRequest extends S.Class<UpdateKxUserRequest>("UpdateKxUserRequest")({environmentId: S.String, userName: S.String, iamRole: S.String, clientToken: S.optional(S.String)}) {}
export class KxNAS1Configuration extends S.Class<KxNAS1Configuration>("KxNAS1Configuration")({type: S.optional(S.String), size: S.optional(S.Number)}) {}
export class UpdateKxVolumeRequest extends S.Class<UpdateKxVolumeRequest>("UpdateKxVolumeRequest")({environmentId: S.String, volumeName: S.String, description: S.optional(S.String), clientToken: S.optional(S.String), nas1Configuration: S.optional(KxNAS1Configuration)}) {}
export const TickerplantLogVolumes = S.Array(S.String);
export const SecurityGroupIdList = S.Array(S.String);
export const SubnetIdList = S.Array(S.String);
export class SuperuserParameters extends S.Class<SuperuserParameters>("SuperuserParameters")({emailAddress: S.String, firstName: S.String, lastName: S.String}) {}
export class ChangeRequest extends S.Class<ChangeRequest>("ChangeRequest")({changeType: S.String, s3Path: S.optional(S.String), dbPath: S.String}) {}
export const ChangeRequests = S.Array(ChangeRequest);
export class TickerplantLogConfiguration extends S.Class<TickerplantLogConfiguration>("TickerplantLogConfiguration")({tickerplantLogVolumes: S.optional(TickerplantLogVolumes)}) {}
export class KxCacheStorageConfiguration extends S.Class<KxCacheStorageConfiguration>("KxCacheStorageConfiguration")({type: S.String, size: S.Number}) {}
export const KxCacheStorageConfigurations = S.Array(KxCacheStorageConfiguration);
export class AutoScalingConfiguration extends S.Class<AutoScalingConfiguration>("AutoScalingConfiguration")({minNodeCount: S.optional(S.Number), maxNodeCount: S.optional(S.Number), autoScalingMetric: S.optional(S.String), metricTarget: S.optional(S.Number), scaleInCooldownSeconds: S.optional(S.Number), scaleOutCooldownSeconds: S.optional(S.Number)}) {}
export class CapacityConfiguration extends S.Class<CapacityConfiguration>("CapacityConfiguration")({nodeType: S.optional(S.String), nodeCount: S.optional(S.Number)}) {}
export class VpcConfiguration extends S.Class<VpcConfiguration>("VpcConfiguration")({vpcId: S.optional(S.String), securityGroupIds: S.optional(SecurityGroupIdList), subnetIds: S.optional(SubnetIdList), ipAddressType: S.optional(S.String)}) {}
export class KxCommandLineArgument extends S.Class<KxCommandLineArgument>("KxCommandLineArgument")({key: S.optional(S.String), value: S.optional(S.String)}) {}
export const KxCommandLineArguments = S.Array(KxCommandLineArgument);
export class CodeConfiguration extends S.Class<CodeConfiguration>("CodeConfiguration")({s3Bucket: S.optional(S.String), s3Key: S.optional(S.String), s3ObjectVersion: S.optional(S.String)}) {}
export class KxSavedownStorageConfiguration extends S.Class<KxSavedownStorageConfiguration>("KxSavedownStorageConfiguration")({type: S.optional(S.String), size: S.optional(S.Number), volumeName: S.optional(S.String)}) {}
export class KxScalingGroupConfiguration extends S.Class<KxScalingGroupConfiguration>("KxScalingGroupConfiguration")({scalingGroupName: S.String, memoryLimit: S.optional(S.Number), memoryReservation: S.Number, nodeCount: S.Number, cpu: S.optional(S.Number)}) {}
export const KxClusterNameList = S.Array(S.String);
export class Environment extends S.Class<Environment>("Environment")({name: S.optional(S.String), environmentId: S.optional(S.String), awsAccountId: S.optional(S.String), status: S.optional(S.String), environmentUrl: S.optional(S.String), description: S.optional(S.String), environmentArn: S.optional(S.String), sageMakerStudioDomainUrl: S.optional(S.String), kmsKeyId: S.optional(S.String), dedicatedServiceAccountId: S.optional(S.String), federationMode: S.optional(S.String), federationParameters: S.optional(FederationParameters)}) {}
export const EnvironmentList = S.Array(Environment);
export class KxClusterCodeDeploymentConfiguration extends S.Class<KxClusterCodeDeploymentConfiguration>("KxClusterCodeDeploymentConfiguration")({deploymentStrategy: S.String}) {}
export class KxDeploymentConfiguration extends S.Class<KxDeploymentConfiguration>("KxDeploymentConfiguration")({deploymentStrategy: S.String}) {}
export class CustomDNSServer extends S.Class<CustomDNSServer>("CustomDNSServer")({customDNSServerName: S.String, customDNSServerIP: S.String}) {}
export const CustomDNSConfiguration = S.Array(CustomDNSServer);
export const DbPaths = S.Array(S.String);
export class CreateKxChangesetRequest extends S.Class<CreateKxChangesetRequest>("CreateKxChangesetRequest")({environmentId: S.String, databaseName: S.String, changeRequests: ChangeRequests, clientToken: S.String}) {}
export class CreateKxDatabaseResponse extends S.Class<CreateKxDatabaseResponse>("CreateKxDatabaseResponse")({databaseName: S.optional(S.String), databaseArn: S.optional(S.String), environmentId: S.optional(S.String), description: S.optional(S.String), createdTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date)}) {}
export class CreateKxDataviewRequest extends S.Class<CreateKxDataviewRequest>("CreateKxDataviewRequest")({environmentId: S.String, databaseName: S.String, dataviewName: S.String, azMode: S.String, availabilityZoneId: S.optional(S.String), changesetId: S.optional(S.String), segmentConfigurations: S.optional(KxDataviewSegmentConfigurationList), autoUpdate: S.optional(S.Boolean), readWrite: S.optional(S.Boolean), description: S.optional(S.String), tags: S.optional(TagMap), clientToken: S.String}) {}
export class CreateKxEnvironmentResponse extends S.Class<CreateKxEnvironmentResponse>("CreateKxEnvironmentResponse")({name: S.optional(S.String), status: S.optional(S.String), environmentId: S.optional(S.String), description: S.optional(S.String), environmentArn: S.optional(S.String), kmsKeyId: S.optional(S.String), creationTimestamp: S.optional(S.Date)}) {}
export class CreateKxScalingGroupResponse extends S.Class<CreateKxScalingGroupResponse>("CreateKxScalingGroupResponse")({environmentId: S.optional(S.String), scalingGroupName: S.optional(S.String), hostType: S.optional(S.String), availabilityZoneId: S.optional(S.String), status: S.optional(S.String), lastModifiedTimestamp: S.optional(S.Date), createdTimestamp: S.optional(S.Date)}) {}
export class CreateKxUserResponse extends S.Class<CreateKxUserResponse>("CreateKxUserResponse")({userName: S.optional(S.String), userArn: S.optional(S.String), environmentId: S.optional(S.String), iamRole: S.optional(S.String)}) {}
export class CreateKxVolumeRequest extends S.Class<CreateKxVolumeRequest>("CreateKxVolumeRequest")({clientToken: S.optional(S.String), environmentId: S.String, volumeType: S.String, volumeName: S.String, description: S.optional(S.String), nas1Configuration: S.optional(KxNAS1Configuration), azMode: S.String, availabilityZoneIds: AvailabilityZoneIds, tags: S.optional(TagMap)}) {}
export class GetKxConnectionStringResponse extends S.Class<GetKxConnectionStringResponse>("GetKxConnectionStringResponse")({signedConnectionString: S.optional(S.String)}) {}
export class GetKxDatabaseResponse extends S.Class<GetKxDatabaseResponse>("GetKxDatabaseResponse")({databaseName: S.optional(S.String), databaseArn: S.optional(S.String), environmentId: S.optional(S.String), description: S.optional(S.String), createdTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date), lastCompletedChangesetId: S.optional(S.String), numBytes: S.optional(S.Number), numChangesets: S.optional(S.Number), numFiles: S.optional(S.Number)}) {}
export class PortRange extends S.Class<PortRange>("PortRange")({from: S.Number, to: S.Number}) {}
export class IcmpTypeCode extends S.Class<IcmpTypeCode>("IcmpTypeCode")({type: S.Number, code: S.Number}) {}
export class NetworkACLEntry extends S.Class<NetworkACLEntry>("NetworkACLEntry")({ruleNumber: S.Number, protocol: S.String, ruleAction: S.String, portRange: S.optional(PortRange), icmpTypeCode: S.optional(IcmpTypeCode), cidrBlock: S.String}) {}
export const NetworkACLConfiguration = S.Array(NetworkACLEntry);
export class TransitGatewayConfiguration extends S.Class<TransitGatewayConfiguration>("TransitGatewayConfiguration")({transitGatewayID: S.String, routableCIDRSpace: S.String, attachmentNetworkAclConfiguration: S.optional(NetworkACLConfiguration)}) {}
export class GetKxEnvironmentResponse extends S.Class<GetKxEnvironmentResponse>("GetKxEnvironmentResponse")({name: S.optional(S.String), environmentId: S.optional(S.String), awsAccountId: S.optional(S.String), status: S.optional(S.String), tgwStatus: S.optional(S.String), dnsStatus: S.optional(S.String), errorMessage: S.optional(S.String), description: S.optional(S.String), environmentArn: S.optional(S.String), kmsKeyId: S.optional(S.String), dedicatedServiceAccountId: S.optional(S.String), transitGatewayConfiguration: S.optional(TransitGatewayConfiguration), customDNSConfiguration: S.optional(CustomDNSConfiguration), creationTimestamp: S.optional(S.Date), updateTimestamp: S.optional(S.Date), availabilityZoneIds: S.optional(AvailabilityZoneIds), certificateAuthorityArn: S.optional(S.String)}) {}
export class GetKxScalingGroupResponse extends S.Class<GetKxScalingGroupResponse>("GetKxScalingGroupResponse")({scalingGroupName: S.optional(S.String), scalingGroupArn: S.optional(S.String), hostType: S.optional(S.String), clusters: S.optional(KxClusterNameList), availabilityZoneId: S.optional(S.String), status: S.optional(S.String), statusReason: S.optional(S.String), lastModifiedTimestamp: S.optional(S.Date), createdTimestamp: S.optional(S.Date)}) {}
export class GetKxUserResponse extends S.Class<GetKxUserResponse>("GetKxUserResponse")({userName: S.optional(S.String), userArn: S.optional(S.String), environmentId: S.optional(S.String), iamRole: S.optional(S.String)}) {}
export class ListEnvironmentsResponse extends S.Class<ListEnvironmentsResponse>("ListEnvironmentsResponse")({environments: S.optional(EnvironmentList), nextToken: S.optional(S.String)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({tags: S.optional(TagMap)}) {}
export class UpdateEnvironmentResponse extends S.Class<UpdateEnvironmentResponse>("UpdateEnvironmentResponse")({environment: S.optional(Environment)}) {}
export class UpdateKxClusterCodeConfigurationRequest extends S.Class<UpdateKxClusterCodeConfigurationRequest>("UpdateKxClusterCodeConfigurationRequest")({environmentId: S.String, clusterName: S.String, clientToken: S.optional(S.String), code: CodeConfiguration, initializationScript: S.optional(S.String), commandLineArguments: S.optional(KxCommandLineArguments), deploymentConfiguration: S.optional(KxClusterCodeDeploymentConfiguration)}) {}
export class UpdateKxClusterCodeConfigurationResponse extends S.Class<UpdateKxClusterCodeConfigurationResponse>("UpdateKxClusterCodeConfigurationResponse")({}) {}
export class KxDatabaseCacheConfiguration extends S.Class<KxDatabaseCacheConfiguration>("KxDatabaseCacheConfiguration")({cacheType: S.String, dbPaths: DbPaths, dataviewName: S.optional(S.String)}) {}
export const KxDatabaseCacheConfigurations = S.Array(KxDatabaseCacheConfiguration);
export class KxDataviewConfiguration extends S.Class<KxDataviewConfiguration>("KxDataviewConfiguration")({dataviewName: S.optional(S.String), dataviewVersionId: S.optional(S.String), changesetId: S.optional(S.String), segmentConfigurations: S.optional(KxDataviewSegmentConfigurationList)}) {}
export class KxDatabaseConfiguration extends S.Class<KxDatabaseConfiguration>("KxDatabaseConfiguration")({databaseName: S.String, cacheConfigurations: S.optional(KxDatabaseCacheConfigurations), changesetId: S.optional(S.String), dataviewName: S.optional(S.String), dataviewConfiguration: S.optional(KxDataviewConfiguration)}) {}
export const KxDatabaseConfigurations = S.Array(KxDatabaseConfiguration);
export class UpdateKxClusterDatabasesRequest extends S.Class<UpdateKxClusterDatabasesRequest>("UpdateKxClusterDatabasesRequest")({environmentId: S.String, clusterName: S.String, clientToken: S.optional(S.String), databases: KxDatabaseConfigurations, deploymentConfiguration: S.optional(KxDeploymentConfiguration)}) {}
export class UpdateKxClusterDatabasesResponse extends S.Class<UpdateKxClusterDatabasesResponse>("UpdateKxClusterDatabasesResponse")({}) {}
export class UpdateKxDatabaseResponse extends S.Class<UpdateKxDatabaseResponse>("UpdateKxDatabaseResponse")({databaseName: S.optional(S.String), environmentId: S.optional(S.String), description: S.optional(S.String), lastModifiedTimestamp: S.optional(S.Date)}) {}
export const AttachedClusterList = S.Array(S.String);
export class KxDataviewActiveVersion extends S.Class<KxDataviewActiveVersion>("KxDataviewActiveVersion")({changesetId: S.optional(S.String), segmentConfigurations: S.optional(KxDataviewSegmentConfigurationList), attachedClusters: S.optional(AttachedClusterList), createdTimestamp: S.optional(S.Date), versionId: S.optional(S.String)}) {}
export const KxDataviewActiveVersionList = S.Array(KxDataviewActiveVersion);
export class UpdateKxDataviewResponse extends S.Class<UpdateKxDataviewResponse>("UpdateKxDataviewResponse")({environmentId: S.optional(S.String), databaseName: S.optional(S.String), dataviewName: S.optional(S.String), azMode: S.optional(S.String), availabilityZoneId: S.optional(S.String), changesetId: S.optional(S.String), segmentConfigurations: S.optional(KxDataviewSegmentConfigurationList), activeVersions: S.optional(KxDataviewActiveVersionList), status: S.optional(S.String), autoUpdate: S.optional(S.Boolean), readWrite: S.optional(S.Boolean), description: S.optional(S.String), createdTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date)}) {}
export class UpdateKxEnvironmentResponse extends S.Class<UpdateKxEnvironmentResponse>("UpdateKxEnvironmentResponse")({name: S.optional(S.String), environmentId: S.optional(S.String), awsAccountId: S.optional(S.String), status: S.optional(S.String), tgwStatus: S.optional(S.String), dnsStatus: S.optional(S.String), errorMessage: S.optional(S.String), description: S.optional(S.String), environmentArn: S.optional(S.String), kmsKeyId: S.optional(S.String), dedicatedServiceAccountId: S.optional(S.String), transitGatewayConfiguration: S.optional(TransitGatewayConfiguration), customDNSConfiguration: S.optional(CustomDNSConfiguration), creationTimestamp: S.optional(S.Date), updateTimestamp: S.optional(S.Date), availabilityZoneIds: S.optional(AvailabilityZoneIds)}) {}
export class UpdateKxUserResponse extends S.Class<UpdateKxUserResponse>("UpdateKxUserResponse")({userName: S.optional(S.String), userArn: S.optional(S.String), environmentId: S.optional(S.String), iamRole: S.optional(S.String)}) {}
export class KxAttachedCluster extends S.Class<KxAttachedCluster>("KxAttachedCluster")({clusterName: S.optional(S.String), clusterType: S.optional(S.String), clusterStatus: S.optional(S.String)}) {}
export const KxAttachedClusters = S.Array(KxAttachedCluster);
export class UpdateKxVolumeResponse extends S.Class<UpdateKxVolumeResponse>("UpdateKxVolumeResponse")({environmentId: S.optional(S.String), volumeName: S.optional(S.String), volumeType: S.optional(S.String), volumeArn: S.optional(S.String), nas1Configuration: S.optional(KxNAS1Configuration), status: S.optional(S.String), description: S.optional(S.String), statusReason: S.optional(S.String), createdTimestamp: S.optional(S.Date), azMode: S.optional(S.String), availabilityZoneIds: S.optional(AvailabilityZoneIds), lastModifiedTimestamp: S.optional(S.Date), attachedClusters: S.optional(KxAttachedClusters)}) {}
export class ErrorInfo extends S.Class<ErrorInfo>("ErrorInfo")({errorMessage: S.optional(S.String), errorType: S.optional(S.String)}) {}
export class Volume extends S.Class<Volume>("Volume")({volumeName: S.optional(S.String), volumeType: S.optional(S.String)}) {}
export const Volumes = S.Array(Volume);
export class KxChangesetListEntry extends S.Class<KxChangesetListEntry>("KxChangesetListEntry")({changesetId: S.optional(S.String), createdTimestamp: S.optional(S.Date), activeFromTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date), status: S.optional(S.String)}) {}
export const KxChangesets = S.Array(KxChangesetListEntry);
export class KxNode extends S.Class<KxNode>("KxNode")({nodeId: S.optional(S.String), availabilityZoneId: S.optional(S.String), launchTime: S.optional(S.Date), status: S.optional(S.String)}) {}
export const KxNodeSummaries = S.Array(KxNode);
export class KxCluster extends S.Class<KxCluster>("KxCluster")({status: S.optional(S.String), statusReason: S.optional(S.String), clusterName: S.optional(S.String), clusterType: S.optional(S.String), clusterDescription: S.optional(S.String), releaseLabel: S.optional(S.String), volumes: S.optional(Volumes), initializationScript: S.optional(S.String), executionRole: S.optional(S.String), azMode: S.optional(S.String), availabilityZoneId: S.optional(S.String), lastModifiedTimestamp: S.optional(S.Date), createdTimestamp: S.optional(S.Date)}) {}
export const KxClusters = S.Array(KxCluster);
export class KxDatabaseListEntry extends S.Class<KxDatabaseListEntry>("KxDatabaseListEntry")({databaseName: S.optional(S.String), createdTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date)}) {}
export const KxDatabases = S.Array(KxDatabaseListEntry);
export class KxDataviewListEntry extends S.Class<KxDataviewListEntry>("KxDataviewListEntry")({environmentId: S.optional(S.String), databaseName: S.optional(S.String), dataviewName: S.optional(S.String), azMode: S.optional(S.String), availabilityZoneId: S.optional(S.String), changesetId: S.optional(S.String), segmentConfigurations: S.optional(KxDataviewSegmentConfigurationList), activeVersions: S.optional(KxDataviewActiveVersionList), status: S.optional(S.String), description: S.optional(S.String), autoUpdate: S.optional(S.Boolean), readWrite: S.optional(S.Boolean), createdTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date), statusReason: S.optional(S.String)}) {}
export const KxDataviews = S.Array(KxDataviewListEntry);
export class KxEnvironment extends S.Class<KxEnvironment>("KxEnvironment")({name: S.optional(S.String), environmentId: S.optional(S.String), awsAccountId: S.optional(S.String), status: S.optional(S.String), tgwStatus: S.optional(S.String), dnsStatus: S.optional(S.String), errorMessage: S.optional(S.String), description: S.optional(S.String), environmentArn: S.optional(S.String), kmsKeyId: S.optional(S.String), dedicatedServiceAccountId: S.optional(S.String), transitGatewayConfiguration: S.optional(TransitGatewayConfiguration), customDNSConfiguration: S.optional(CustomDNSConfiguration), creationTimestamp: S.optional(S.Date), updateTimestamp: S.optional(S.Date), availabilityZoneIds: S.optional(AvailabilityZoneIds), certificateAuthorityArn: S.optional(S.String)}) {}
export const KxEnvironmentList = S.Array(KxEnvironment);
export class KxScalingGroup extends S.Class<KxScalingGroup>("KxScalingGroup")({scalingGroupName: S.optional(S.String), hostType: S.optional(S.String), clusters: S.optional(KxClusterNameList), availabilityZoneId: S.optional(S.String), status: S.optional(S.String), statusReason: S.optional(S.String), lastModifiedTimestamp: S.optional(S.Date), createdTimestamp: S.optional(S.Date)}) {}
export const KxScalingGroupList = S.Array(KxScalingGroup);
export class KxUser extends S.Class<KxUser>("KxUser")({userArn: S.optional(S.String), userName: S.optional(S.String), iamRole: S.optional(S.String), createTimestamp: S.optional(S.Date), updateTimestamp: S.optional(S.Date)}) {}
export const KxUserList = S.Array(KxUser);
export class KxVolume extends S.Class<KxVolume>("KxVolume")({volumeName: S.optional(S.String), volumeType: S.optional(S.String), status: S.optional(S.String), description: S.optional(S.String), statusReason: S.optional(S.String), azMode: S.optional(S.String), availabilityZoneIds: S.optional(AvailabilityZoneIds), createdTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date)}) {}
export const KxVolumes = S.Array(KxVolume);
export class CreateEnvironmentRequest extends S.Class<CreateEnvironmentRequest>("CreateEnvironmentRequest")({name: S.String, description: S.optional(S.String), kmsKeyId: S.optional(S.String), tags: S.optional(TagMap), federationMode: S.optional(S.String), federationParameters: S.optional(FederationParameters), superuserParameters: S.optional(SuperuserParameters), dataBundles: S.optional(DataBundleArns)}) {}
export class CreateKxChangesetResponse extends S.Class<CreateKxChangesetResponse>("CreateKxChangesetResponse")({changesetId: S.optional(S.String), databaseName: S.optional(S.String), environmentId: S.optional(S.String), changeRequests: S.optional(ChangeRequests), createdTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date), status: S.optional(S.String), errorInfo: S.optional(ErrorInfo)}) {}
export class CreateKxClusterRequest extends S.Class<CreateKxClusterRequest>("CreateKxClusterRequest")({clientToken: S.optional(S.String), environmentId: S.String, clusterName: S.String, clusterType: S.String, tickerplantLogConfiguration: S.optional(TickerplantLogConfiguration), databases: S.optional(KxDatabaseConfigurations), cacheStorageConfigurations: S.optional(KxCacheStorageConfigurations), autoScalingConfiguration: S.optional(AutoScalingConfiguration), clusterDescription: S.optional(S.String), capacityConfiguration: S.optional(CapacityConfiguration), releaseLabel: S.String, vpcConfiguration: VpcConfiguration, initializationScript: S.optional(S.String), commandLineArguments: S.optional(KxCommandLineArguments), code: S.optional(CodeConfiguration), executionRole: S.optional(S.String), savedownStorageConfiguration: S.optional(KxSavedownStorageConfiguration), azMode: S.String, availabilityZoneId: S.optional(S.String), tags: S.optional(TagMap), scalingGroupConfiguration: S.optional(KxScalingGroupConfiguration)}) {}
export class CreateKxDataviewResponse extends S.Class<CreateKxDataviewResponse>("CreateKxDataviewResponse")({dataviewName: S.optional(S.String), databaseName: S.optional(S.String), environmentId: S.optional(S.String), azMode: S.optional(S.String), availabilityZoneId: S.optional(S.String), changesetId: S.optional(S.String), segmentConfigurations: S.optional(KxDataviewSegmentConfigurationList), description: S.optional(S.String), autoUpdate: S.optional(S.Boolean), readWrite: S.optional(S.Boolean), createdTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date), status: S.optional(S.String)}) {}
export class CreateKxVolumeResponse extends S.Class<CreateKxVolumeResponse>("CreateKxVolumeResponse")({environmentId: S.optional(S.String), volumeName: S.optional(S.String), volumeType: S.optional(S.String), volumeArn: S.optional(S.String), nas1Configuration: S.optional(KxNAS1Configuration), status: S.optional(S.String), statusReason: S.optional(S.String), azMode: S.optional(S.String), description: S.optional(S.String), availabilityZoneIds: S.optional(AvailabilityZoneIds), createdTimestamp: S.optional(S.Date)}) {}
export class GetEnvironmentResponse extends S.Class<GetEnvironmentResponse>("GetEnvironmentResponse")({environment: S.optional(Environment)}) {}
export class GetKxChangesetResponse extends S.Class<GetKxChangesetResponse>("GetKxChangesetResponse")({changesetId: S.optional(S.String), databaseName: S.optional(S.String), environmentId: S.optional(S.String), changeRequests: S.optional(ChangeRequests), createdTimestamp: S.optional(S.Date), activeFromTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date), status: S.optional(S.String), errorInfo: S.optional(ErrorInfo)}) {}
export class GetKxClusterResponse extends S.Class<GetKxClusterResponse>("GetKxClusterResponse")({status: S.optional(S.String), statusReason: S.optional(S.String), clusterName: S.optional(S.String), clusterType: S.optional(S.String), tickerplantLogConfiguration: S.optional(TickerplantLogConfiguration), volumes: S.optional(Volumes), databases: S.optional(KxDatabaseConfigurations), cacheStorageConfigurations: S.optional(KxCacheStorageConfigurations), autoScalingConfiguration: S.optional(AutoScalingConfiguration), clusterDescription: S.optional(S.String), capacityConfiguration: S.optional(CapacityConfiguration), releaseLabel: S.optional(S.String), vpcConfiguration: S.optional(VpcConfiguration), initializationScript: S.optional(S.String), commandLineArguments: S.optional(KxCommandLineArguments), code: S.optional(CodeConfiguration), executionRole: S.optional(S.String), lastModifiedTimestamp: S.optional(S.Date), savedownStorageConfiguration: S.optional(KxSavedownStorageConfiguration), azMode: S.optional(S.String), availabilityZoneId: S.optional(S.String), createdTimestamp: S.optional(S.Date), scalingGroupConfiguration: S.optional(KxScalingGroupConfiguration)}) {}
export class GetKxDataviewResponse extends S.Class<GetKxDataviewResponse>("GetKxDataviewResponse")({databaseName: S.optional(S.String), dataviewName: S.optional(S.String), azMode: S.optional(S.String), availabilityZoneId: S.optional(S.String), changesetId: S.optional(S.String), segmentConfigurations: S.optional(KxDataviewSegmentConfigurationList), activeVersions: S.optional(KxDataviewActiveVersionList), description: S.optional(S.String), autoUpdate: S.optional(S.Boolean), readWrite: S.optional(S.Boolean), environmentId: S.optional(S.String), createdTimestamp: S.optional(S.Date), lastModifiedTimestamp: S.optional(S.Date), status: S.optional(S.String), statusReason: S.optional(S.String)}) {}
export class GetKxVolumeResponse extends S.Class<GetKxVolumeResponse>("GetKxVolumeResponse")({environmentId: S.optional(S.String), volumeName: S.optional(S.String), volumeType: S.optional(S.String), volumeArn: S.optional(S.String), nas1Configuration: S.optional(KxNAS1Configuration), status: S.optional(S.String), statusReason: S.optional(S.String), createdTimestamp: S.optional(S.Date), description: S.optional(S.String), azMode: S.optional(S.String), availabilityZoneIds: S.optional(AvailabilityZoneIds), lastModifiedTimestamp: S.optional(S.Date), attachedClusters: S.optional(KxAttachedClusters)}) {}
export class ListKxChangesetsResponse extends S.Class<ListKxChangesetsResponse>("ListKxChangesetsResponse")({kxChangesets: S.optional(KxChangesets), nextToken: S.optional(S.String)}) {}
export class ListKxClusterNodesResponse extends S.Class<ListKxClusterNodesResponse>("ListKxClusterNodesResponse")({nodes: S.optional(KxNodeSummaries), nextToken: S.optional(S.String)}) {}
export class ListKxClustersResponse extends S.Class<ListKxClustersResponse>("ListKxClustersResponse")({kxClusterSummaries: S.optional(KxClusters), nextToken: S.optional(S.String)}) {}
export class ListKxDatabasesResponse extends S.Class<ListKxDatabasesResponse>("ListKxDatabasesResponse")({kxDatabases: S.optional(KxDatabases), nextToken: S.optional(S.String)}) {}
export class ListKxDataviewsResponse extends S.Class<ListKxDataviewsResponse>("ListKxDataviewsResponse")({kxDataviews: S.optional(KxDataviews), nextToken: S.optional(S.String)}) {}
export class ListKxEnvironmentsResponse extends S.Class<ListKxEnvironmentsResponse>("ListKxEnvironmentsResponse")({environments: S.optional(KxEnvironmentList), nextToken: S.optional(S.String)}) {}
export class ListKxScalingGroupsResponse extends S.Class<ListKxScalingGroupsResponse>("ListKxScalingGroupsResponse")({scalingGroups: S.optional(KxScalingGroupList), nextToken: S.optional(S.String)}) {}
export class ListKxUsersResponse extends S.Class<ListKxUsersResponse>("ListKxUsersResponse")({users: S.optional(KxUserList), nextToken: S.optional(S.String)}) {}
export class ListKxVolumesResponse extends S.Class<ListKxVolumesResponse>("ListKxVolumesResponse")({kxVolumeSummaries: S.optional(KxVolumes), nextToken: S.optional(S.String)}) {}
export class CreateEnvironmentResponse extends S.Class<CreateEnvironmentResponse>("CreateEnvironmentResponse")({environmentId: S.optional(S.String), environmentArn: S.optional(S.String), environmentUrl: S.optional(S.String)}) {}
export class CreateKxClusterResponse extends S.Class<CreateKxClusterResponse>("CreateKxClusterResponse")({environmentId: S.optional(S.String), status: S.optional(S.String), statusReason: S.optional(S.String), clusterName: S.optional(S.String), clusterType: S.optional(S.String), tickerplantLogConfiguration: S.optional(TickerplantLogConfiguration), volumes: S.optional(Volumes), databases: S.optional(KxDatabaseConfigurations), cacheStorageConfigurations: S.optional(KxCacheStorageConfigurations), autoScalingConfiguration: S.optional(AutoScalingConfiguration), clusterDescription: S.optional(S.String), capacityConfiguration: S.optional(CapacityConfiguration), releaseLabel: S.optional(S.String), vpcConfiguration: S.optional(VpcConfiguration), initializationScript: S.optional(S.String), commandLineArguments: S.optional(KxCommandLineArguments), code: S.optional(CodeConfiguration), executionRole: S.optional(S.String), lastModifiedTimestamp: S.optional(S.Date), savedownStorageConfiguration: S.optional(KxSavedownStorageConfiguration), azMode: S.optional(S.String), availabilityZoneId: S.optional(S.String), createdTimestamp: S.optional(S.Date), scalingGroupConfiguration: S.optional(KxScalingGroupConfiguration)}) {}
export class UpdateKxEnvironmentNetworkRequest extends S.Class<UpdateKxEnvironmentNetworkRequest>("UpdateKxEnvironmentNetworkRequest")({environmentId: S.String, transitGatewayConfiguration: S.optional(TransitGatewayConfiguration), customDNSConfiguration: S.optional(CustomDNSConfiguration), clientToken: S.optional(S.String)}) {}
export class UpdateKxEnvironmentNetworkResponse extends S.Class<UpdateKxEnvironmentNetworkResponse>("UpdateKxEnvironmentNetworkResponse")({name: S.optional(S.String), environmentId: S.optional(S.String), awsAccountId: S.optional(S.String), status: S.optional(S.String), tgwStatus: S.optional(S.String), dnsStatus: S.optional(S.String), errorMessage: S.optional(S.String), description: S.optional(S.String), environmentArn: S.optional(S.String), kmsKeyId: S.optional(S.String), dedicatedServiceAccountId: S.optional(S.String), transitGatewayConfiguration: S.optional(TransitGatewayConfiguration), customDNSConfiguration: S.optional(CustomDNSConfiguration), creationTimestamp: S.optional(S.Date), updateTimestamp: S.optional(S.Date), availabilityZoneIds: S.optional(AvailabilityZoneIds)}) {}

//# Errors
export class AccessDeniedException extends S.TaggedError<AccessDeniedException>()("AccessDeniedException", {}) {};
export class ConflictException extends S.TaggedError<ConflictException>()("ConflictException", {}) {};
export class InternalServerException extends S.TaggedError<InternalServerException>()("InternalServerException", {}) {};
export class ResourceNotFoundException extends S.TaggedError<ResourceNotFoundException>()("ResourceNotFoundException", {}) {};
export class ThrottlingException extends S.TaggedError<ThrottlingException>()("ThrottlingException", {}) {};
export class ValidationException extends S.TaggedError<ValidationException>()("ValidationException", {}) {};
export class LimitExceededException extends S.TaggedError<LimitExceededException>()("LimitExceededException", {}) {};
export class InvalidRequestException extends S.TaggedError<InvalidRequestException>()("InvalidRequestException", {}) {};
export class ResourceAlreadyExistsException extends S.TaggedError<ResourceAlreadyExistsException>()("ResourceAlreadyExistsException", {}) {};
export class ServiceQuotaExceededException extends S.TaggedError<ServiceQuotaExceededException>()("ServiceQuotaExceededException", {message: S.optional(S.String)}) {};

//# Operations
/**
 * Deletes a user in the specified kdb environment.
 */export const deleteKxUser = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/users/{userName}", method: "DELETE", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.DeleteKxUser" }, DeleteKxUserRequest, DeleteKxUserResponse, [AccessDeniedException, ConflictException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Deletes a volume. You can only delete a volume if it's not attached to a cluster or a dataview. When a volume is deleted, any data on the volume is lost. This action is irreversible.
 */export const deleteKxVolume = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/kxvolumes/{volumeName}", method: "DELETE", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.DeleteKxVolume" }, DeleteKxVolumeRequest, DeleteKxVolumeResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Removes metadata tags from a FinSpace resource.
 */export const untagResource = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [InternalServerException, InvalidRequestException, ResourceNotFoundException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Creates a new scaling group.
 */export const createKxScalingGroup = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/scalingGroups", method: "POST", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.CreateKxScalingGroup" }, CreateKxScalingGroupRequest, CreateKxScalingGroupResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Creates a user in FinSpace kdb environment with an associated IAM role.
 */export const createKxUser = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/users", method: "POST", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.CreateKxUser" }, CreateKxUserRequest, CreateKxUserResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceAlreadyExistsException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Delete an FinSpace environment.
 */export const deleteEnvironment = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/environment/{environmentId}", method: "DELETE", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.DeleteEnvironment" }, DeleteEnvironmentRequest, DeleteEnvironmentResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Deletes a kdb cluster.
 */export const deleteKxCluster = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/clusters/{clusterName}", method: "DELETE", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.DeleteKxCluster" }, DeleteKxClusterRequest, DeleteKxClusterResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Deletes the specified nodes from a cluster.
 */export const deleteKxClusterNode = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/clusters/{clusterName}/nodes/{nodeId}", method: "DELETE", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.DeleteKxClusterNode" }, DeleteKxClusterNodeRequest, DeleteKxClusterNodeResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Deletes the specified database and all of its associated data. This action is irreversible. You must copy any data out of the database before deleting it if the data is to be retained.
 */export const deleteKxDatabase = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}", method: "DELETE", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.DeleteKxDatabase" }, DeleteKxDatabaseRequest, DeleteKxDatabaseResponse, [AccessDeniedException, ConflictException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Deletes the specified dataview. Before deleting a dataview, make sure that it is not in use by any cluster.
 */export const deleteKxDataview = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}/dataviews/{dataviewName}", method: "DELETE", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.DeleteKxDataview" }, DeleteKxDataviewRequest, DeleteKxDataviewResponse, [AccessDeniedException, ConflictException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Deletes the kdb environment. This action is irreversible. Deleting a kdb environment will remove all the associated data and any services running in it.
 */export const deleteKxEnvironment = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}", method: "DELETE", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.DeleteKxEnvironment" }, DeleteKxEnvironmentRequest, DeleteKxEnvironmentResponse, [AccessDeniedException, ConflictException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Deletes the specified scaling group. This action is irreversible. You cannot delete a scaling group until all the clusters running on it have been deleted.
 */export const deleteKxScalingGroup = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/scalingGroups/{scalingGroupName}", method: "DELETE", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.DeleteKxScalingGroup" }, DeleteKxScalingGroupRequest, DeleteKxScalingGroupResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Retrieves a connection string for a user to connect to a kdb cluster. You must call this API using the same role that you have defined while creating a user.
 */export const getKxConnectionString = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/connectionString", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.GetKxConnectionString" }, GetKxConnectionStringRequest, GetKxConnectionStringResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Returns database information for the specified environment ID.
 */export const getKxDatabase = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.GetKxDatabase" }, GetKxDatabaseRequest, GetKxDatabaseResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Retrieves all the information for the specified kdb environment.
 */export const getKxEnvironment = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.GetKxEnvironment" }, GetKxEnvironmentRequest, GetKxEnvironmentResponse, [AccessDeniedException, ConflictException, InternalServerException, ResourceNotFoundException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Retrieves details of a scaling group.
 */export const getKxScalingGroup = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/scalingGroups/{scalingGroupName}", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.GetKxScalingGroup" }, GetKxScalingGroupRequest, GetKxScalingGroupResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Retrieves information about the specified kdb user.
 */export const getKxUser = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/users/{userName}", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.GetKxUser" }, GetKxUserRequest, GetKxUserResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * A list of all of your FinSpace environments.
 */export const listEnvironments = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/environment", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListEnvironments" }, ListEnvironmentsRequest, ListEnvironmentsResponse, [AccessDeniedException, InternalServerException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * A list of all tags for a resource.
 */export const listTagsForResource = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/tags/{resourceArn}", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [InternalServerException, InvalidRequestException, ResourceNotFoundException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Adds metadata tags to a FinSpace resource.
 */export const tagResource = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/tags/{resourceArn}", method: "POST", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.TagResource" }, TagResourceRequest, TagResourceResponse, [InternalServerException, InvalidRequestException, ResourceNotFoundException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Update your FinSpace environment.
 */export const updateEnvironment = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/environment/{environmentId}", method: "PUT", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.UpdateEnvironment" }, UpdateEnvironmentRequest, UpdateEnvironmentResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Allows you to update code configuration on a running cluster. By using this API you can update the code, the initialization script path, and the command line arguments for a specific cluster.
 * The configuration that you want to update will override any existing configurations on the cluster.
 */export const updateKxClusterCodeConfiguration = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/clusters/{clusterName}/configuration/code", method: "PUT", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.UpdateKxClusterCodeConfiguration" }, UpdateKxClusterCodeConfigurationRequest, UpdateKxClusterCodeConfigurationResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Updates the databases mounted on a kdb cluster, which includes the `changesetId` and all the dbPaths to be cached. This API does not allow you to change a database name or add a database if you created a cluster without one.
 * 
 * 
 * Using this API you can point a cluster to a different changeset and modify a list of partitions being cached.
 */export const updateKxClusterDatabases = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/clusters/{clusterName}/configuration/databases", method: "PUT", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.UpdateKxClusterDatabases" }, UpdateKxClusterDatabasesRequest, UpdateKxClusterDatabasesResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Updates information for the given kdb database.
 */export const updateKxDatabase = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}", method: "PUT", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.UpdateKxDatabase" }, UpdateKxDatabaseRequest, UpdateKxDatabaseResponse, [AccessDeniedException, ConflictException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Updates the specified dataview. The dataviews get automatically updated when any new changesets are ingested. Each update of the dataview creates a new version, including changeset details and cache configurations
 */export const updateKxDataview = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}/dataviews/{dataviewName}", method: "PUT", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.UpdateKxDataview" }, UpdateKxDataviewRequest, UpdateKxDataviewResponse, [AccessDeniedException, ConflictException, InternalServerException, ResourceAlreadyExistsException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Updates information for the given kdb environment.
 */export const updateKxEnvironment = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}", method: "PUT", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.UpdateKxEnvironment" }, UpdateKxEnvironmentRequest, UpdateKxEnvironmentResponse, [AccessDeniedException, ConflictException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Updates the user details. You can only update the IAM role associated with a user.
 */export const updateKxUser = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/users/{userName}", method: "PUT", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.UpdateKxUser" }, UpdateKxUserRequest, UpdateKxUserResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Updates the throughput or capacity of a volume. During the update process, the filesystem
 * might be unavailable for a few minutes. You can retry any operations after the update is complete.
 */export const updateKxVolume = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/kxvolumes/{volumeName}", method: "PATCH", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.UpdateKxVolume" }, UpdateKxVolumeRequest, UpdateKxVolumeResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Creates a changeset for a kdb database. A changeset allows you to add and delete existing files by using an ordered list of change requests.
 */export const createKxChangeset = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}/changesets", method: "POST", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.CreateKxChangeset" }, CreateKxChangesetRequest, CreateKxChangesetResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Creates a new kdb database in the environment.
 */export const createKxDatabase = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases", method: "POST", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.CreateKxDatabase" }, CreateKxDatabaseRequest, CreateKxDatabaseResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceAlreadyExistsException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Creates a snapshot of kdb database with tiered storage capabilities and a pre-warmed cache, ready for mounting on kdb clusters. Dataviews are only available for clusters running on a scaling group. They are not supported on dedicated clusters.
 */export const createKxDataview = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}/dataviews", method: "POST", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.CreateKxDataview" }, CreateKxDataviewRequest, CreateKxDataviewResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceAlreadyExistsException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Creates a managed kdb environment for the account.
 */export const createKxEnvironment = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments", method: "POST", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.CreateKxEnvironment" }, CreateKxEnvironmentRequest, CreateKxEnvironmentResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ServiceQuotaExceededException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Creates a new volume with a specific amount of throughput and storage capacity.
 */export const createKxVolume = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/kxvolumes", method: "POST", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.CreateKxVolume" }, CreateKxVolumeRequest, CreateKxVolumeResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceAlreadyExistsException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Returns the FinSpace environment object.
 */export const getEnvironment = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/environment/{environmentId}", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.GetEnvironment" }, GetEnvironmentRequest, GetEnvironmentResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Returns information about a kdb changeset.
 */export const getKxChangeset = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}/changesets/{changesetId}", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.GetKxChangeset" }, GetKxChangesetRequest, GetKxChangesetResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Retrieves information about a kdb cluster.
 */export const getKxCluster = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/clusters/{clusterName}", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.GetKxCluster" }, GetKxClusterRequest, GetKxClusterResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Retrieves details of the dataview.
 */export const getKxDataview = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}/dataviews/{dataviewName}", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.GetKxDataview" }, GetKxDataviewRequest, GetKxDataviewResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Retrieves the information about the volume.
 */export const getKxVolume = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/kxvolumes/{volumeName}", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.GetKxVolume" }, GetKxVolumeRequest, GetKxVolumeResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Returns a list of all the changesets for a database.
 */export const listKxChangesets = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}/changesets", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListKxChangesets" }, ListKxChangesetsRequest, ListKxChangesetsResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Lists all the nodes in a kdb cluster.
 */export const listKxClusterNodes = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/clusters/{clusterName}/nodes", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListKxClusterNodes" }, ListKxClusterNodesRequest, ListKxClusterNodesResponse, [AccessDeniedException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Returns a list of clusters.
 */export const listKxClusters = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/clusters", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListKxClusters" }, ListKxClustersRequest, ListKxClustersResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Returns a list of all the databases in the kdb environment.
 */export const listKxDatabases = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListKxDatabases" }, ListKxDatabasesRequest, ListKxDatabasesResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Returns a list of all the dataviews in the database.
 */export const listKxDataviews = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/databases/{databaseName}/dataviews", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListKxDataviews" }, ListKxDataviewsRequest, ListKxDataviewsResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Returns a list of kdb environments created in an account.
 */export const listKxEnvironments = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListKxEnvironments" }, ListKxEnvironmentsRequest, ListKxEnvironmentsResponse, [AccessDeniedException, InternalServerException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Returns a list of scaling groups in a kdb environment.
 */export const listKxScalingGroups = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/scalingGroups", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListKxScalingGroups" }, ListKxScalingGroupsRequest, ListKxScalingGroupsResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Lists all the users in a kdb environment.
 */export const listKxUsers = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/users", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListKxUsers" }, ListKxUsersRequest, ListKxUsersResponse, [AccessDeniedException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Lists all the volumes in a kdb environment.
 */export const listKxVolumes = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/kxvolumes", method: "GET", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.ListKxVolumes" }, ListKxVolumesRequest, ListKxVolumesResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Create a new FinSpace environment.
 */export const createEnvironment = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/environment", method: "POST", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.CreateEnvironment" }, CreateEnvironmentRequest, CreateEnvironmentResponse, [AccessDeniedException, InternalServerException, LimitExceededException, ServiceQuotaExceededException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Creates a new kdb cluster.
 */export const createKxCluster = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/clusters", method: "POST", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.CreateKxCluster" }, CreateKxClusterRequest, CreateKxClusterResponse, [AccessDeniedException, ConflictException, InternalServerException, LimitExceededException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
/**
 * Updates environment network to connect to your internal network by using a transit gateway. This API supports request to create a transit gateway attachment from FinSpace VPC to your transit gateway ID and create a custom Route-53 outbound resolvers.
 * 
 * 
 * Once you send a request to update a network, you cannot change it again. Network update might require termination of any clusters that are running in the existing network.
 */export const updateKxEnvironmentNetwork = /*@__PURE__*/ /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-03-12", uri: "/kx/environments/{environmentId}/network", method: "PUT", sdkId: "finspace", sigV4ServiceName: "finspace", name: "AWSHabaneroManagementService.UpdateKxEnvironmentNetwork" }, UpdateKxEnvironmentNetworkRequest, UpdateKxEnvironmentNetworkResponse, [AccessDeniedException, ConflictException, InternalServerException, ResourceNotFoundException, ThrottlingException, ValidationException]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
