import * as S from "effect/Schema"
import { FormatAwsQueryRequest,FormatAwsQueryResponse,FormatAwsXMLError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export class GetCallerIdentityRequest extends S.Class<GetCallerIdentityRequest>("GetCallerIdentityRequest")({}) {}
export const tagKeyListType = S.Array(S.String);
export const webIdentityTokenAudienceListType = S.Array(S.String);
export class PolicyDescriptorType extends S.Class<PolicyDescriptorType>("PolicyDescriptorType")({arn: S.optional(S.String)}) {}
export const policyDescriptorListType = S.Array(PolicyDescriptorType);
export class AssumeRoleWithSAMLRequest extends S.Class<AssumeRoleWithSAMLRequest>("AssumeRoleWithSAMLRequest")({RoleArn: S.String, PrincipalArn: S.String, SAMLAssertion: S.String, PolicyArns: S.optional(policyDescriptorListType), Policy: S.optional(S.String), DurationSeconds: S.optional(S.Number)}) {}
export class AssumeRoleWithWebIdentityRequest extends S.Class<AssumeRoleWithWebIdentityRequest>("AssumeRoleWithWebIdentityRequest")({RoleArn: S.String, RoleSessionName: S.String, WebIdentityToken: S.String, ProviderId: S.optional(S.String), PolicyArns: S.optional(policyDescriptorListType), Policy: S.optional(S.String), DurationSeconds: S.optional(S.Number)}) {}
export class AssumeRootRequest extends S.Class<AssumeRootRequest>("AssumeRootRequest")({TargetPrincipal: S.String, TaskPolicyArn: PolicyDescriptorType, DurationSeconds: S.optional(S.Number)}) {}
export class DecodeAuthorizationMessageRequest extends S.Class<DecodeAuthorizationMessageRequest>("DecodeAuthorizationMessageRequest")({EncodedMessage: S.String}) {}
export class GetAccessKeyInfoRequest extends S.Class<GetAccessKeyInfoRequest>("GetAccessKeyInfoRequest")({AccessKeyId: S.String}) {}
export class GetCallerIdentityResponse extends S.Class<GetCallerIdentityResponse>("GetCallerIdentityResponse")({UserId: S.optional(S.String), Account: S.optional(S.String), Arn: S.optional(S.String)}) {}
export class GetDelegatedAccessTokenRequest extends S.Class<GetDelegatedAccessTokenRequest>("GetDelegatedAccessTokenRequest")({TradeInToken: S.String}) {}
export class Tag extends S.Class<Tag>("Tag")({Key: S.String, Value: S.String}) {}
export const tagListType = S.Array(Tag);
export class GetFederationTokenRequest extends S.Class<GetFederationTokenRequest>("GetFederationTokenRequest")({Name: S.String, Policy: S.optional(S.String), PolicyArns: S.optional(policyDescriptorListType), DurationSeconds: S.optional(S.Number), Tags: S.optional(tagListType)}) {}
export class GetSessionTokenRequest extends S.Class<GetSessionTokenRequest>("GetSessionTokenRequest")({DurationSeconds: S.optional(S.Number), SerialNumber: S.optional(S.String), TokenCode: S.optional(S.String)}) {}
export class GetWebIdentityTokenRequest extends S.Class<GetWebIdentityTokenRequest>("GetWebIdentityTokenRequest")({Audience: webIdentityTokenAudienceListType, DurationSeconds: S.optional(S.Number), SigningAlgorithm: S.String, Tags: S.optional(tagListType)}) {}
export class ProvidedContext extends S.Class<ProvidedContext>("ProvidedContext")({ProviderArn: S.optional(S.String), ContextAssertion: S.optional(S.String)}) {}
export const ProvidedContextsListType = S.Array(ProvidedContext);
export class AssumeRoleRequest extends S.Class<AssumeRoleRequest>("AssumeRoleRequest")({RoleArn: S.String, RoleSessionName: S.String, PolicyArns: S.optional(policyDescriptorListType), Policy: S.optional(S.String), DurationSeconds: S.optional(S.Number), Tags: S.optional(tagListType), TransitiveTagKeys: S.optional(tagKeyListType), ExternalId: S.optional(S.String), SerialNumber: S.optional(S.String), TokenCode: S.optional(S.String), SourceIdentity: S.optional(S.String), ProvidedContexts: S.optional(ProvidedContextsListType)}) {}
export class Credentials extends S.Class<Credentials>("Credentials")({AccessKeyId: S.String, SecretAccessKey: S.String, SessionToken: S.String, Expiration: S.Date}) {}
export class AssumedRoleUser extends S.Class<AssumedRoleUser>("AssumedRoleUser")({AssumedRoleId: S.String, Arn: S.String}) {}
export class AssumeRoleWithWebIdentityResponse extends S.Class<AssumeRoleWithWebIdentityResponse>("AssumeRoleWithWebIdentityResponse")({Credentials: S.optional(Credentials), SubjectFromWebIdentityToken: S.optional(S.String), AssumedRoleUser: S.optional(AssumedRoleUser), PackedPolicySize: S.optional(S.Number), Provider: S.optional(S.String), Audience: S.optional(S.String), SourceIdentity: S.optional(S.String)}) {}
export class AssumeRootResponse extends S.Class<AssumeRootResponse>("AssumeRootResponse")({Credentials: S.optional(Credentials), SourceIdentity: S.optional(S.String)}) {}
export class DecodeAuthorizationMessageResponse extends S.Class<DecodeAuthorizationMessageResponse>("DecodeAuthorizationMessageResponse")({DecodedMessage: S.optional(S.String)}) {}
export class GetAccessKeyInfoResponse extends S.Class<GetAccessKeyInfoResponse>("GetAccessKeyInfoResponse")({Account: S.optional(S.String)}) {}
export class GetDelegatedAccessTokenResponse extends S.Class<GetDelegatedAccessTokenResponse>("GetDelegatedAccessTokenResponse")({Credentials: S.optional(Credentials), PackedPolicySize: S.optional(S.Number), AssumedPrincipal: S.optional(S.String)}) {}
export class GetSessionTokenResponse extends S.Class<GetSessionTokenResponse>("GetSessionTokenResponse")({Credentials: S.optional(Credentials)}) {}
export class GetWebIdentityTokenResponse extends S.Class<GetWebIdentityTokenResponse>("GetWebIdentityTokenResponse")({WebIdentityToken: S.optional(S.String), Expiration: S.optional(S.Date)}) {}
export class FederatedUser extends S.Class<FederatedUser>("FederatedUser")({FederatedUserId: S.String, Arn: S.String}) {}
export class AssumeRoleResponse extends S.Class<AssumeRoleResponse>("AssumeRoleResponse")({Credentials: S.optional(Credentials), AssumedRoleUser: S.optional(AssumedRoleUser), PackedPolicySize: S.optional(S.Number), SourceIdentity: S.optional(S.String)}) {}
export class AssumeRoleWithSAMLResponse extends S.Class<AssumeRoleWithSAMLResponse>("AssumeRoleWithSAMLResponse")({Credentials: S.optional(Credentials), AssumedRoleUser: S.optional(AssumedRoleUser), PackedPolicySize: S.optional(S.Number), Subject: S.optional(S.String), SubjectType: S.optional(S.String), Issuer: S.optional(S.String), Audience: S.optional(S.String), NameQualifier: S.optional(S.String), SourceIdentity: S.optional(S.String)}) {}
export class GetFederationTokenResponse extends S.Class<GetFederationTokenResponse>("GetFederationTokenResponse")({Credentials: S.optional(Credentials), FederatedUser: S.optional(FederatedUser), PackedPolicySize: S.optional(S.Number)}) {}

//# Errors
export class ExpiredTokenException extends S.TaggedError<ExpiredTokenException>()("ExpiredTokenException", {}) {};
export class RegionDisabledException extends S.TaggedError<RegionDisabledException>()("RegionDisabledException", {}) {};
export class InvalidAuthorizationMessageException extends S.TaggedError<InvalidAuthorizationMessageException>()("InvalidAuthorizationMessageException", {message: S.optional(S.String)}) {};
export class ExpiredTradeInTokenException extends S.TaggedError<ExpiredTradeInTokenException>()("ExpiredTradeInTokenException", {message: S.optional(S.String)}) {};
export class MalformedPolicyDocumentException extends S.TaggedError<MalformedPolicyDocumentException>()("MalformedPolicyDocumentException", {}) {};
export class PackedPolicyTooLargeException extends S.TaggedError<PackedPolicyTooLargeException>()("PackedPolicyTooLargeException", {}) {};
export class JWTPayloadSizeExceededException extends S.TaggedError<JWTPayloadSizeExceededException>()("JWTPayloadSizeExceededException", {message: S.optional(S.String)}) {};
export class IDPRejectedClaimException extends S.TaggedError<IDPRejectedClaimException>()("IDPRejectedClaimException", {message: S.optional(S.String)}) {};
export class IDPCommunicationErrorException extends S.TaggedError<IDPCommunicationErrorException>()("IDPCommunicationErrorException", {message: S.optional(S.String)}) {};
export class InvalidIdentityTokenException extends S.TaggedError<InvalidIdentityTokenException>()("InvalidIdentityTokenException", {}) {};
export class OutboundWebIdentityFederationDisabledException extends S.TaggedError<OutboundWebIdentityFederationDisabledException>()("OutboundWebIdentityFederationDisabledException", {message: S.optional(S.String)}) {};
export class SessionDurationEscalationException extends S.TaggedError<SessionDurationEscalationException>()("SessionDurationEscalationException", {message: S.optional(S.String)}) {};

//# Operations
export const getCallerIdentity = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.GetCallerIdentity" }, GetCallerIdentityRequest, GetCallerIdentityResponse, []), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
export const getAccessKeyInfo = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.GetAccessKeyInfo" }, GetAccessKeyInfoRequest, GetAccessKeyInfoResponse, []), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
export const getSessionToken = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.GetSessionToken" }, GetSessionTokenRequest, GetSessionTokenResponse, [RegionDisabledException]), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
export const assumeRoot = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.AssumeRoot" }, AssumeRootRequest, AssumeRootResponse, [ExpiredTokenException, RegionDisabledException]), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
export const decodeAuthorizationMessage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.DecodeAuthorizationMessage" }, DecodeAuthorizationMessageRequest, DecodeAuthorizationMessageResponse, [InvalidAuthorizationMessageException]), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
export const getFederationToken = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.GetFederationToken" }, GetFederationTokenRequest, GetFederationTokenResponse, [MalformedPolicyDocumentException, PackedPolicyTooLargeException, RegionDisabledException]), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
export const assumeRole = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.AssumeRole" }, AssumeRoleRequest, AssumeRoleResponse, [ExpiredTokenException, MalformedPolicyDocumentException, PackedPolicyTooLargeException, RegionDisabledException]), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
export const assumeRoleWithWebIdentity = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.AssumeRoleWithWebIdentity" }, AssumeRoleWithWebIdentityRequest, AssumeRoleWithWebIdentityResponse, [ExpiredTokenException, IDPCommunicationErrorException, IDPRejectedClaimException, InvalidIdentityTokenException, MalformedPolicyDocumentException, PackedPolicyTooLargeException, RegionDisabledException]), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
export const getDelegatedAccessToken = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.GetDelegatedAccessToken" }, GetDelegatedAccessTokenRequest, GetDelegatedAccessTokenResponse, [ExpiredTradeInTokenException, PackedPolicyTooLargeException, RegionDisabledException]), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
export const assumeRoleWithSAML = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.AssumeRoleWithSAML" }, AssumeRoleWithSAMLRequest, AssumeRoleWithSAMLResponse, [ExpiredTokenException, IDPRejectedClaimException, InvalidIdentityTokenException, MalformedPolicyDocumentException, PackedPolicyTooLargeException, RegionDisabledException]), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
export const getWebIdentityToken = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2011-06-15", uri: "/", method: "POST", sdkId: "STS", sigV4ServiceName: "sts", name: "AWSSecurityTokenServiceV20110615.GetWebIdentityToken" }, GetWebIdentityTokenRequest, GetWebIdentityTokenResponse, [JWTPayloadSizeExceededException, OutboundWebIdentityFederationDisabledException, SessionDurationEscalationException]), FormatAwsQueryRequest, FormatAwsQueryResponse, FormatAwsXMLError);
