import { Schema} from "effect"
import { FormatXMLRequest, FormatXMLResponse, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
const IdentitySourceList = Schema.Array(Schema.String)
const AuthorizationScopes = Schema.Array(Schema.String)
const SecurityGroupIdList = Schema.Array(Schema.String)
const SubnetIdList = Schema.Array(Schema.String)
const __listOf__string = Schema.Array(Schema.String)
const CreateApiMappingRequest = Schema.Struct({ApiId: Schema.String, ApiMappingKey: Schema.optional(Schema.String), DomainName: Schema.String, Stage: Schema.String})
const CreateDeploymentRequest = Schema.Struct({ApiId: Schema.String, Description: Schema.optional(Schema.String), StageName: Schema.optional(Schema.String)})
const CreateIntegrationResponseRequest = Schema.Struct({ApiId: Schema.String, ContentHandlingStrategy: Schema.optional(Schema.String), IntegrationId: Schema.String, IntegrationResponseKey: Schema.String, ResponseParameters: Schema.optional(IntegrationParameters), ResponseTemplates: Schema.optional(TemplateMap), TemplateSelectionExpression: Schema.optional(Schema.String)})
const CreateModelRequest = Schema.Struct({ApiId: Schema.String, ContentType: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), Name: Schema.String, Schema: Schema.String})
const CreateRouteResponseRequest = Schema.Struct({ApiId: Schema.String, ModelSelectionExpression: Schema.optional(Schema.String), ResponseModels: Schema.optional(RouteModels), ResponseParameters: Schema.optional(RouteParameters), RouteId: Schema.String, RouteResponseKey: Schema.String})
const CreateVpcLinkRequest = Schema.Struct({Name: Schema.String, SecurityGroupIds: Schema.optional(SecurityGroupIdList), SubnetIds: SubnetIdList, Tags: Schema.optional(Tags)})
const DeleteAccessLogSettingsRequest = Schema.Struct({ApiId: Schema.String, StageName: Schema.String})
const DeleteApiRequest = Schema.Struct({ApiId: Schema.String})
const DeleteApiMappingRequest = Schema.Struct({ApiMappingId: Schema.String, DomainName: Schema.String})
const DeleteAuthorizerRequest = Schema.Struct({ApiId: Schema.String, AuthorizerId: Schema.String})
export const DeleteAuthorizer = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/authorizers/{AuthorizerId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteAuthorizer" }, DeleteAuthorizerRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteCorsConfigurationRequest = Schema.Struct({ApiId: Schema.String})
export const DeleteCorsConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/cors", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteCorsConfiguration" }, DeleteCorsConfigurationRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteDeploymentRequest = Schema.Struct({ApiId: Schema.String, DeploymentId: Schema.String})
export const DeleteDeployment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/deployments/{DeploymentId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteDeployment" }, DeleteDeploymentRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteDomainNameRequest = Schema.Struct({DomainName: Schema.String})
export const DeleteDomainName = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteDomainName" }, DeleteDomainNameRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteIntegrationRequest = Schema.Struct({ApiId: Schema.String, IntegrationId: Schema.String})
export const DeleteIntegration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/integrations/{IntegrationId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteIntegration" }, DeleteIntegrationRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteIntegrationResponseRequest = Schema.Struct({ApiId: Schema.String, IntegrationId: Schema.String, IntegrationResponseId: Schema.String})
export const DeleteIntegrationResponse = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/integrations/{IntegrationId}/integrationresponses/{IntegrationResponseId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteIntegrationResponse" }, DeleteIntegrationResponseRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteModelRequest = Schema.Struct({ApiId: Schema.String, ModelId: Schema.String})
export const DeleteModel = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/models/{ModelId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteModel" }, DeleteModelRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteRouteRequest = Schema.Struct({ApiId: Schema.String, RouteId: Schema.String})
export const DeleteRoute = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes/{RouteId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteRoute" }, DeleteRouteRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteRouteRequestParameterRequest = Schema.Struct({ApiId: Schema.String, RequestParameterKey: Schema.String, RouteId: Schema.String})
export const DeleteRouteRequestParameter = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes/{RouteId}/requestparameters/{RequestParameterKey}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteRouteRequestParameter" }, DeleteRouteRequestParameterRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteRouteResponseRequest = Schema.Struct({ApiId: Schema.String, RouteId: Schema.String, RouteResponseId: Schema.String})
export const DeleteRouteResponse = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes/{RouteId}/routeresponses/{RouteResponseId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteRouteResponse" }, DeleteRouteResponseRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteRouteSettingsRequest = Schema.Struct({ApiId: Schema.String, RouteKey: Schema.String, StageName: Schema.String})
export const DeleteRouteSettings = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/stages/{StageName}/routesettings/{RouteKey}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteRouteSettings" }, DeleteRouteSettingsRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteRoutingRuleRequest = Schema.Struct({DomainName: Schema.String, DomainNameId: Schema.optional(Schema.String), RoutingRuleId: Schema.String})
export const DeleteRoutingRule = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}/routingrules/{RoutingRuleId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteRoutingRule" }, DeleteRoutingRuleRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteStageRequest = Schema.Struct({ApiId: Schema.String, StageName: Schema.String})
export const DeleteStage = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/stages/{StageName}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteStage" }, DeleteStageRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteVpcLinkRequest = Schema.Struct({VpcLinkId: Schema.String})
const DeleteVpcLinkResponse = Schema.Struct({})
export const DeleteVpcLink = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/vpclinks/{VpcLinkId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteVpcLink" }, DeleteVpcLinkRequest, DeleteVpcLinkResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ExportApiRequest = Schema.Struct({ApiId: Schema.String, ExportVersion: Schema.optional(Schema.String), IncludeExtensions: Schema.optional(Schema.Boolean), OutputType: Schema.String, Specification: Schema.String, StageName: Schema.optional(Schema.String)})
const GetApiRequest = Schema.Struct({ApiId: Schema.String})
const GetApiMappingRequest = Schema.Struct({ApiMappingId: Schema.String, DomainName: Schema.String})
const GetApiMappingsRequest = Schema.Struct({DomainName: Schema.String, MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const GetApisRequest = Schema.Struct({MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const GetAuthorizerRequest = Schema.Struct({ApiId: Schema.String, AuthorizerId: Schema.String})
const GetAuthorizersRequest = Schema.Struct({ApiId: Schema.String, MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const GetDeploymentRequest = Schema.Struct({ApiId: Schema.String, DeploymentId: Schema.String})
const GetDeploymentsRequest = Schema.Struct({ApiId: Schema.String, MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const GetDomainNameRequest = Schema.Struct({DomainName: Schema.String})
const GetDomainNamesRequest = Schema.Struct({MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const GetIntegrationRequest = Schema.Struct({ApiId: Schema.String, IntegrationId: Schema.String})
const GetIntegrationResponseRequest = Schema.Struct({ApiId: Schema.String, IntegrationId: Schema.String, IntegrationResponseId: Schema.String})
const GetIntegrationResponsesRequest = Schema.Struct({ApiId: Schema.String, IntegrationId: Schema.String, MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const GetIntegrationsRequest = Schema.Struct({ApiId: Schema.String, MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const GetModelRequest = Schema.Struct({ApiId: Schema.String, ModelId: Schema.String})
const GetModelsRequest = Schema.Struct({ApiId: Schema.String, MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const GetModelTemplateRequest = Schema.Struct({ApiId: Schema.String, ModelId: Schema.String})
const GetRouteRequest = Schema.Struct({ApiId: Schema.String, RouteId: Schema.String})
const GetRouteResponseRequest = Schema.Struct({ApiId: Schema.String, RouteId: Schema.String, RouteResponseId: Schema.String})
const GetRouteResponsesRequest = Schema.Struct({ApiId: Schema.String, MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String), RouteId: Schema.String})
const GetRoutesRequest = Schema.Struct({ApiId: Schema.String, MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const GetRoutingRuleRequest = Schema.Struct({DomainName: Schema.String, DomainNameId: Schema.optional(Schema.String), RoutingRuleId: Schema.String})
const GetStageRequest = Schema.Struct({ApiId: Schema.String, StageName: Schema.String})
const GetStagesRequest = Schema.Struct({ApiId: Schema.String, MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const GetTagsRequest = Schema.Struct({ResourceArn: Schema.String})
const GetVpcLinkRequest = Schema.Struct({VpcLinkId: Schema.String})
const GetVpcLinksRequest = Schema.Struct({MaxResults: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String)})
const ImportApiRequest = Schema.Struct({Basepath: Schema.optional(Schema.String), Body: Schema.String, FailOnWarnings: Schema.optional(Schema.Boolean)})
const ListRoutingRulesRequest = Schema.Struct({DomainName: Schema.String, DomainNameId: Schema.optional(Schema.String), MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)})
const PutRoutingRuleRequest = Schema.Struct({Actions: __listOfRoutingRuleAction, Conditions: __listOfRoutingRuleCondition, DomainName: Schema.String, DomainNameId: Schema.optional(Schema.String), Priority: Schema.Number, RoutingRuleId: Schema.String})
const ReimportApiRequest = Schema.Struct({ApiId: Schema.String, Basepath: Schema.optional(Schema.String), Body: Schema.String, FailOnWarnings: Schema.optional(Schema.Boolean)})
const ResetAuthorizersCacheRequest = Schema.Struct({ApiId: Schema.String, StageName: Schema.String})
export const ResetAuthorizersCache = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/stages/{StageName}/cache/authorizers", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "ResetAuthorizersCache" }, ResetAuthorizersCacheRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const TagResourceRequest = Schema.Struct({ResourceArn: Schema.String, Tags: Schema.optional(Tags)})
const TagResourceResponse = Schema.Struct({})
const UntagResourceRequest = Schema.Struct({ResourceArn: Schema.String, TagKeys: __listOf__string})
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/tags/{ResourceArn}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UntagResource" }, UntagResourceRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateApiRequest = Schema.Struct({ApiId: Schema.String, ApiKeySelectionExpression: Schema.optional(Schema.String), CorsConfiguration: Schema.optional(Cors), CredentialsArn: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), DisableSchemaValidation: Schema.optional(Schema.Boolean), DisableExecuteApiEndpoint: Schema.optional(Schema.Boolean), IpAddressType: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), RouteKey: Schema.optional(Schema.String), RouteSelectionExpression: Schema.optional(Schema.String), Target: Schema.optional(Schema.String), Version: Schema.optional(Schema.String)})
const UpdateApiMappingRequest = Schema.Struct({ApiId: Schema.String, ApiMappingId: Schema.String, ApiMappingKey: Schema.optional(Schema.String), DomainName: Schema.String, Stage: Schema.optional(Schema.String)})
const UpdateAuthorizerRequest = Schema.Struct({ApiId: Schema.String, AuthorizerCredentialsArn: Schema.optional(Schema.String), AuthorizerId: Schema.String, AuthorizerPayloadFormatVersion: Schema.optional(Schema.String), AuthorizerResultTtlInSeconds: Schema.optional(Schema.Number), AuthorizerType: Schema.optional(Schema.String), AuthorizerUri: Schema.optional(Schema.String), EnableSimpleResponses: Schema.optional(Schema.Boolean), IdentitySource: Schema.optional(IdentitySourceList), IdentityValidationExpression: Schema.optional(Schema.String), JwtConfiguration: Schema.optional(JWTConfiguration), Name: Schema.optional(Schema.String)})
const UpdateDeploymentRequest = Schema.Struct({ApiId: Schema.String, DeploymentId: Schema.String, Description: Schema.optional(Schema.String)})
const UpdateDomainNameRequest = Schema.Struct({DomainName: Schema.String, DomainNameConfigurations: Schema.optional(DomainNameConfigurations), MutualTlsAuthentication: Schema.optional(MutualTlsAuthenticationInput), RoutingMode: Schema.optional(Schema.String)})
const UpdateIntegrationRequest = Schema.Struct({ApiId: Schema.String, ConnectionId: Schema.optional(Schema.String), ConnectionType: Schema.optional(Schema.String), ContentHandlingStrategy: Schema.optional(Schema.String), CredentialsArn: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), IntegrationId: Schema.String, IntegrationMethod: Schema.optional(Schema.String), IntegrationSubtype: Schema.optional(Schema.String), IntegrationType: Schema.optional(Schema.String), IntegrationUri: Schema.optional(Schema.String), PassthroughBehavior: Schema.optional(Schema.String), PayloadFormatVersion: Schema.optional(Schema.String), RequestParameters: Schema.optional(IntegrationParameters), RequestTemplates: Schema.optional(TemplateMap), ResponseParameters: Schema.optional(ResponseParameters), TemplateSelectionExpression: Schema.optional(Schema.String), TimeoutInMillis: Schema.optional(Schema.Number), TlsConfig: Schema.optional(TlsConfigInput)})
const UpdateIntegrationResponseRequest = Schema.Struct({ApiId: Schema.String, ContentHandlingStrategy: Schema.optional(Schema.String), IntegrationId: Schema.String, IntegrationResponseId: Schema.String, IntegrationResponseKey: Schema.optional(Schema.String), ResponseParameters: Schema.optional(IntegrationParameters), ResponseTemplates: Schema.optional(TemplateMap), TemplateSelectionExpression: Schema.optional(Schema.String)})
const UpdateModelRequest = Schema.Struct({ApiId: Schema.String, ContentType: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), ModelId: Schema.String, Name: Schema.optional(Schema.String), Schema: Schema.optional(Schema.String)})
const UpdateRouteRequest = Schema.Struct({ApiId: Schema.String, ApiKeyRequired: Schema.optional(Schema.Boolean), AuthorizationScopes: Schema.optional(AuthorizationScopes), AuthorizationType: Schema.optional(Schema.String), AuthorizerId: Schema.optional(Schema.String), ModelSelectionExpression: Schema.optional(Schema.String), OperationName: Schema.optional(Schema.String), RequestModels: Schema.optional(RouteModels), RequestParameters: Schema.optional(RouteParameters), RouteId: Schema.String, RouteKey: Schema.optional(Schema.String), RouteResponseSelectionExpression: Schema.optional(Schema.String), Target: Schema.optional(Schema.String)})
const UpdateRouteResponseRequest = Schema.Struct({ApiId: Schema.String, ModelSelectionExpression: Schema.optional(Schema.String), ResponseModels: Schema.optional(RouteModels), ResponseParameters: Schema.optional(RouteParameters), RouteId: Schema.String, RouteResponseId: Schema.String, RouteResponseKey: Schema.optional(Schema.String)})
const UpdateStageRequest = Schema.Struct({AccessLogSettings: Schema.optional(AccessLogSettings), ApiId: Schema.String, AutoDeploy: Schema.optional(Schema.Boolean), ClientCertificateId: Schema.optional(Schema.String), DefaultRouteSettings: Schema.optional(RouteSettings), DeploymentId: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), RouteSettings: Schema.optional(RouteSettingsMap), StageName: Schema.String, StageVariables: Schema.optional(StageVariablesMap)})
const UpdateVpcLinkRequest = Schema.Struct({Name: Schema.optional(Schema.String), VpcLinkId: Schema.String})
const CorsHeaderList = Schema.Array(Schema.String)
const CorsMethodList = Schema.Array(Schema.String)
const CorsOriginList = Schema.Array(Schema.String)
const Cors = Schema.Struct({AllowCredentials: Schema.optional(Schema.Boolean), AllowHeaders: Schema.optional(CorsHeaderList), AllowMethods: Schema.optional(CorsMethodList), AllowOrigins: Schema.optional(CorsOriginList), ExposeHeaders: Schema.optional(CorsHeaderList), MaxAge: Schema.optional(Schema.Number)})
const Tags = Schema.Record({key: Schema.String, value: Schema.String})
const JWTConfiguration = Schema.Struct({Audience: Schema.optional(__listOf__string), Issuer: Schema.optional(Schema.String)})
const DomainNameConfiguration = Schema.Struct({ApiGatewayDomainName: Schema.optional(Schema.String), CertificateArn: Schema.optional(Schema.String), CertificateName: Schema.optional(Schema.String), CertificateUploadDate: Schema.optional(Schema.Date), DomainNameStatus: Schema.optional(Schema.String), DomainNameStatusMessage: Schema.optional(Schema.String), EndpointType: Schema.optional(Schema.String), HostedZoneId: Schema.optional(Schema.String), IpAddressType: Schema.optional(Schema.String), SecurityPolicy: Schema.optional(Schema.String), OwnershipVerificationCertificateArn: Schema.optional(Schema.String)})
const DomainNameConfigurations = Schema.Array(DomainNameConfiguration)
const MutualTlsAuthenticationInput = Schema.Struct({TruststoreUri: Schema.optional(Schema.String), TruststoreVersion: Schema.optional(Schema.String)})
const IntegrationParameters = Schema.Record({key: Schema.String, value: Schema.String})
const TemplateMap = Schema.Record({key: Schema.String, value: Schema.String})
const ResponseParameters = Schema.Record({key: Schema.String, value: IntegrationParameters})
const TlsConfigInput = Schema.Struct({ServerNameToVerify: Schema.optional(Schema.String)})
const RouteModels = Schema.Record({key: Schema.String, value: Schema.String})
const AccessLogSettings = Schema.Struct({DestinationArn: Schema.optional(Schema.String), Format: Schema.optional(Schema.String)})
const RouteSettings = Schema.Struct({DataTraceEnabled: Schema.optional(Schema.Boolean), DetailedMetricsEnabled: Schema.optional(Schema.Boolean), LoggingLevel: Schema.optional(Schema.String), ThrottlingBurstLimit: Schema.optional(Schema.Number), ThrottlingRateLimit: Schema.optional(Schema.Number)})
const RouteSettingsMap = Schema.Record({key: Schema.String, value: RouteSettings})
const StageVariablesMap = Schema.Record({key: Schema.String, value: Schema.String})
const __listOfSelectionKey = Schema.Array(Schema.String)
const CreateApiRequest = Schema.Struct({ApiKeySelectionExpression: Schema.optional(Schema.String), CorsConfiguration: Schema.optional(Cors), CredentialsArn: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), DisableSchemaValidation: Schema.optional(Schema.Boolean), DisableExecuteApiEndpoint: Schema.optional(Schema.Boolean), IpAddressType: Schema.optional(Schema.String), Name: Schema.String, ProtocolType: Schema.String, RouteKey: Schema.optional(Schema.String), RouteSelectionExpression: Schema.optional(Schema.String), Tags: Schema.optional(Tags), Target: Schema.optional(Schema.String), Version: Schema.optional(Schema.String)})
const CreateApiMappingResponse = Schema.Struct({ApiId: Schema.optional(Schema.String), ApiMappingId: Schema.optional(Schema.String), ApiMappingKey: Schema.optional(Schema.String), Stage: Schema.optional(Schema.String)})
export const CreateApiMapping = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}/apimappings", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateApiMapping" }, CreateApiMappingRequest, CreateApiMappingResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateAuthorizerRequest = Schema.Struct({ApiId: Schema.String, AuthorizerCredentialsArn: Schema.optional(Schema.String), AuthorizerPayloadFormatVersion: Schema.optional(Schema.String), AuthorizerResultTtlInSeconds: Schema.optional(Schema.Number), AuthorizerType: Schema.String, AuthorizerUri: Schema.optional(Schema.String), EnableSimpleResponses: Schema.optional(Schema.Boolean), IdentitySource: IdentitySourceList, IdentityValidationExpression: Schema.optional(Schema.String), JwtConfiguration: Schema.optional(JWTConfiguration), Name: Schema.String})
const CreateDeploymentResponse = Schema.Struct({AutoDeployed: Schema.optional(Schema.Boolean), CreatedDate: Schema.optional(Schema.Date), DeploymentId: Schema.optional(Schema.String), DeploymentStatus: Schema.optional(Schema.String), DeploymentStatusMessage: Schema.optional(Schema.String), Description: Schema.optional(Schema.String)})
export const CreateDeployment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/deployments", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateDeployment" }, CreateDeploymentRequest, CreateDeploymentResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateDomainNameRequest = Schema.Struct({DomainName: Schema.String, DomainNameConfigurations: Schema.optional(DomainNameConfigurations), MutualTlsAuthentication: Schema.optional(MutualTlsAuthenticationInput), RoutingMode: Schema.optional(Schema.String), Tags: Schema.optional(Tags)})
const CreateIntegrationRequest = Schema.Struct({ApiId: Schema.String, ConnectionId: Schema.optional(Schema.String), ConnectionType: Schema.optional(Schema.String), ContentHandlingStrategy: Schema.optional(Schema.String), CredentialsArn: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), IntegrationMethod: Schema.optional(Schema.String), IntegrationSubtype: Schema.optional(Schema.String), IntegrationType: Schema.String, IntegrationUri: Schema.optional(Schema.String), PassthroughBehavior: Schema.optional(Schema.String), PayloadFormatVersion: Schema.optional(Schema.String), RequestParameters: Schema.optional(IntegrationParameters), RequestTemplates: Schema.optional(TemplateMap), ResponseParameters: Schema.optional(ResponseParameters), TemplateSelectionExpression: Schema.optional(Schema.String), TimeoutInMillis: Schema.optional(Schema.Number), TlsConfig: Schema.optional(TlsConfigInput)})
const CreateIntegrationResponseResponse = Schema.Struct({ContentHandlingStrategy: Schema.optional(Schema.String), IntegrationResponseId: Schema.optional(Schema.String), IntegrationResponseKey: Schema.optional(Schema.String), ResponseParameters: Schema.optional(IntegrationParameters), ResponseTemplates: Schema.optional(TemplateMap), TemplateSelectionExpression: Schema.optional(Schema.String)})
export const CreateIntegrationResponse = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/integrations/{IntegrationId}/integrationresponses", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateIntegrationResponse" }, CreateIntegrationResponseRequest, CreateIntegrationResponseResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateModelResponse = Schema.Struct({ContentType: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), ModelId: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), Schema: Schema.optional(Schema.String)})
export const CreateModel = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/models", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateModel" }, CreateModelRequest, CreateModelResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateRouteResponseResponse = Schema.Struct({ModelSelectionExpression: Schema.optional(Schema.String), ResponseModels: Schema.optional(RouteModels), ResponseParameters: Schema.optional(RouteParameters), RouteResponseId: Schema.optional(Schema.String), RouteResponseKey: Schema.optional(Schema.String)})
export const CreateRouteResponse = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes/{RouteId}/routeresponses", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateRouteResponse" }, CreateRouteResponseRequest, CreateRouteResponseResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateStageRequest = Schema.Struct({AccessLogSettings: Schema.optional(AccessLogSettings), ApiId: Schema.String, AutoDeploy: Schema.optional(Schema.Boolean), ClientCertificateId: Schema.optional(Schema.String), DefaultRouteSettings: Schema.optional(RouteSettings), DeploymentId: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), RouteSettings: Schema.optional(RouteSettingsMap), StageName: Schema.String, StageVariables: Schema.optional(StageVariablesMap), Tags: Schema.optional(Tags)})
const CreateVpcLinkResponse = Schema.Struct({CreatedDate: Schema.optional(Schema.Date), Name: Schema.optional(Schema.String), SecurityGroupIds: Schema.optional(SecurityGroupIdList), SubnetIds: Schema.optional(SubnetIdList), Tags: Schema.optional(Tags), VpcLinkId: Schema.optional(Schema.String), VpcLinkStatus: Schema.optional(Schema.String), VpcLinkStatusMessage: Schema.optional(Schema.String), VpcLinkVersion: Schema.optional(Schema.String)})
export const CreateVpcLink = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/vpclinks", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateVpcLink" }, CreateVpcLinkRequest, CreateVpcLinkResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const NotFoundException = Schema.Struct({Message: Schema.optional(Schema.String), ResourceType: Schema.optional(Schema.String)})
export const DeleteAccessLogSettings = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/stages/{StageName}/accesslogsettings", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteAccessLogSettings" }, DeleteAccessLogSettingsRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const TooManyRequestsException = Schema.Struct({LimitType: Schema.optional(Schema.String), Message: Schema.optional(Schema.String)})
export const DeleteApi = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteApi" }, DeleteApiRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const BadRequestException = Schema.Struct({Message: Schema.optional(Schema.String)})
export const DeleteApiMapping = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}/apimappings/{ApiMappingId}", method: "DELETE", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "DeleteApiMapping" }, DeleteApiMappingRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ExportApiResponse = Schema.Struct({body: Schema.optional(Body("undefined", StreamBody()))})
export const ExportApi = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/exports/{Specification}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "ExportApi" }, ExportApiRequest, ExportApiResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetApiResponse = Schema.Struct({ApiEndpoint: Schema.optional(Schema.String), ApiGatewayManaged: Schema.optional(Schema.Boolean), ApiId: Schema.optional(Schema.String), ApiKeySelectionExpression: Schema.optional(Schema.String), CorsConfiguration: Schema.optional(Cors), CreatedDate: Schema.optional(Schema.Date), Description: Schema.optional(Schema.String), DisableSchemaValidation: Schema.optional(Schema.Boolean), DisableExecuteApiEndpoint: Schema.optional(Schema.Boolean), ImportInfo: Schema.optional(__listOf__string), IpAddressType: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), ProtocolType: Schema.optional(Schema.String), RouteSelectionExpression: Schema.optional(Schema.String), Tags: Schema.optional(Tags), Version: Schema.optional(Schema.String), Warnings: Schema.optional(__listOf__string)})
export const GetApi = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetApi" }, GetApiRequest, GetApiResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetApiMappingResponse = Schema.Struct({ApiId: Schema.optional(Schema.String), ApiMappingId: Schema.optional(Schema.String), ApiMappingKey: Schema.optional(Schema.String), Stage: Schema.optional(Schema.String)})
export const GetApiMapping = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}/apimappings/{ApiMappingId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetApiMapping" }, GetApiMappingRequest, GetApiMappingResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetAuthorizerResponse = Schema.Struct({AuthorizerCredentialsArn: Schema.optional(Schema.String), AuthorizerId: Schema.optional(Schema.String), AuthorizerPayloadFormatVersion: Schema.optional(Schema.String), AuthorizerResultTtlInSeconds: Schema.optional(Schema.Number), AuthorizerType: Schema.optional(Schema.String), AuthorizerUri: Schema.optional(Schema.String), EnableSimpleResponses: Schema.optional(Schema.Boolean), IdentitySource: Schema.optional(IdentitySourceList), IdentityValidationExpression: Schema.optional(Schema.String), JwtConfiguration: Schema.optional(JWTConfiguration), Name: Schema.optional(Schema.String)})
export const GetAuthorizer = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/authorizers/{AuthorizerId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetAuthorizer" }, GetAuthorizerRequest, GetAuthorizerResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetDeploymentResponse = Schema.Struct({AutoDeployed: Schema.optional(Schema.Boolean), CreatedDate: Schema.optional(Schema.Date), DeploymentId: Schema.optional(Schema.String), DeploymentStatus: Schema.optional(Schema.String), DeploymentStatusMessage: Schema.optional(Schema.String), Description: Schema.optional(Schema.String)})
export const GetDeployment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/deployments/{DeploymentId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetDeployment" }, GetDeploymentRequest, GetDeploymentResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetIntegrationResponseResponse = Schema.Struct({ContentHandlingStrategy: Schema.optional(Schema.String), IntegrationResponseId: Schema.optional(Schema.String), IntegrationResponseKey: Schema.optional(Schema.String), ResponseParameters: Schema.optional(IntegrationParameters), ResponseTemplates: Schema.optional(TemplateMap), TemplateSelectionExpression: Schema.optional(Schema.String)})
export const GetIntegrationResponse = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/integrations/{IntegrationId}/integrationresponses/{IntegrationResponseId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetIntegrationResponse" }, GetIntegrationResponseRequest, GetIntegrationResponseResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetModelResponse = Schema.Struct({ContentType: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), ModelId: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), Schema: Schema.optional(Schema.String)})
export const GetModel = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/models/{ModelId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetModel" }, GetModelRequest, GetModelResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetModelTemplateResponse = Schema.Struct({Value: Schema.optional(Schema.String)})
export const GetModelTemplate = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/models/{ModelId}/template", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetModelTemplate" }, GetModelTemplateRequest, GetModelTemplateResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetRouteResult = Schema.Struct({ApiGatewayManaged: Schema.optional(Schema.Boolean), ApiKeyRequired: Schema.optional(Schema.Boolean), AuthorizationScopes: Schema.optional(AuthorizationScopes), AuthorizationType: Schema.optional(Schema.String), AuthorizerId: Schema.optional(Schema.String), ModelSelectionExpression: Schema.optional(Schema.String), OperationName: Schema.optional(Schema.String), RequestModels: Schema.optional(RouteModels), RequestParameters: Schema.optional(RouteParameters), RouteId: Schema.optional(Schema.String), RouteKey: Schema.optional(Schema.String), RouteResponseSelectionExpression: Schema.optional(Schema.String), Target: Schema.optional(Schema.String)})
export const GetRoute = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes/{RouteId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetRoute" }, GetRouteRequest, GetRouteResult, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetRouteResponseResponse = Schema.Struct({ModelSelectionExpression: Schema.optional(Schema.String), ResponseModels: Schema.optional(RouteModels), ResponseParameters: Schema.optional(RouteParameters), RouteResponseId: Schema.optional(Schema.String), RouteResponseKey: Schema.optional(Schema.String)})
export const GetRouteResponse = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes/{RouteId}/routeresponses/{RouteResponseId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetRouteResponse" }, GetRouteResponseRequest, GetRouteResponseResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetRoutingRuleResponse = Schema.Struct({Actions: Schema.optional(__listOfRoutingRuleAction), Conditions: Schema.optional(__listOfRoutingRuleCondition), Priority: Schema.optional(Schema.Number), RoutingRuleArn: Schema.optional(Schema.String), RoutingRuleId: Schema.optional(Schema.String)})
export const GetRoutingRule = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}/routingrules/{RoutingRuleId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetRoutingRule" }, GetRoutingRuleRequest, GetRoutingRuleResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetStageResponse = Schema.Struct({AccessLogSettings: Schema.optional(AccessLogSettings), ApiGatewayManaged: Schema.optional(Schema.Boolean), AutoDeploy: Schema.optional(Schema.Boolean), ClientCertificateId: Schema.optional(Schema.String), CreatedDate: Schema.optional(Schema.Date), DefaultRouteSettings: Schema.optional(RouteSettings), DeploymentId: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), LastDeploymentStatusMessage: Schema.optional(Schema.String), LastUpdatedDate: Schema.optional(Schema.Date), RouteSettings: Schema.optional(RouteSettingsMap), StageName: Schema.optional(Schema.String), StageVariables: Schema.optional(StageVariablesMap), Tags: Schema.optional(Tags)})
export const GetStage = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/stages/{StageName}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetStage" }, GetStageRequest, GetStageResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetTagsResponse = Schema.Struct({Tags: Schema.optional(Tags)})
export const GetTags = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/tags/{ResourceArn}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetTags" }, GetTagsRequest, GetTagsResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetVpcLinkResponse = Schema.Struct({CreatedDate: Schema.optional(Schema.Date), Name: Schema.optional(Schema.String), SecurityGroupIds: Schema.optional(SecurityGroupIdList), SubnetIds: Schema.optional(SubnetIdList), Tags: Schema.optional(Tags), VpcLinkId: Schema.optional(Schema.String), VpcLinkStatus: Schema.optional(Schema.String), VpcLinkStatusMessage: Schema.optional(Schema.String), VpcLinkVersion: Schema.optional(Schema.String)})
export const GetVpcLink = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/vpclinks/{VpcLinkId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetVpcLink" }, GetVpcLinkRequest, GetVpcLinkResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ImportApiResponse = Schema.Struct({ApiEndpoint: Schema.optional(Schema.String), ApiGatewayManaged: Schema.optional(Schema.Boolean), ApiId: Schema.optional(Schema.String), ApiKeySelectionExpression: Schema.optional(Schema.String), CorsConfiguration: Schema.optional(Cors), CreatedDate: Schema.optional(Schema.Date), Description: Schema.optional(Schema.String), DisableSchemaValidation: Schema.optional(Schema.Boolean), DisableExecuteApiEndpoint: Schema.optional(Schema.Boolean), ImportInfo: Schema.optional(__listOf__string), IpAddressType: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), ProtocolType: Schema.optional(Schema.String), RouteSelectionExpression: Schema.optional(Schema.String), Tags: Schema.optional(Tags), Version: Schema.optional(Schema.String), Warnings: Schema.optional(__listOf__string)})
export const ImportApi = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis", method: "PUT", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "ImportApi" }, ImportApiRequest, ImportApiResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const PutRoutingRuleResponse = Schema.Struct({Actions: Schema.optional(__listOfRoutingRuleAction), Conditions: Schema.optional(__listOfRoutingRuleCondition), Priority: Schema.optional(Schema.Number), RoutingRuleArn: Schema.optional(Schema.String), RoutingRuleId: Schema.optional(Schema.String)})
export const PutRoutingRule = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}/routingrules/{RoutingRuleId}", method: "PUT", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "PutRoutingRule" }, PutRoutingRuleRequest, PutRoutingRuleResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ReimportApiResponse = Schema.Struct({ApiEndpoint: Schema.optional(Schema.String), ApiGatewayManaged: Schema.optional(Schema.Boolean), ApiId: Schema.optional(Schema.String), ApiKeySelectionExpression: Schema.optional(Schema.String), CorsConfiguration: Schema.optional(Cors), CreatedDate: Schema.optional(Schema.Date), Description: Schema.optional(Schema.String), DisableSchemaValidation: Schema.optional(Schema.Boolean), DisableExecuteApiEndpoint: Schema.optional(Schema.Boolean), ImportInfo: Schema.optional(__listOf__string), IpAddressType: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), ProtocolType: Schema.optional(Schema.String), RouteSelectionExpression: Schema.optional(Schema.String), Tags: Schema.optional(Tags), Version: Schema.optional(Schema.String), Warnings: Schema.optional(__listOf__string)})
export const ReimportApi = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}", method: "PUT", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "ReimportApi" }, ReimportApiRequest, ReimportApiResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ConflictException = Schema.Struct({Message: Schema.optional(Schema.String)})
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/tags/{ResourceArn}", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "TagResource" }, TagResourceRequest, TagResourceResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateApiResponse = Schema.Struct({ApiEndpoint: Schema.optional(Schema.String), ApiGatewayManaged: Schema.optional(Schema.Boolean), ApiId: Schema.optional(Schema.String), ApiKeySelectionExpression: Schema.optional(Schema.String), CorsConfiguration: Schema.optional(Cors), CreatedDate: Schema.optional(Schema.Date), Description: Schema.optional(Schema.String), DisableSchemaValidation: Schema.optional(Schema.Boolean), DisableExecuteApiEndpoint: Schema.optional(Schema.Boolean), ImportInfo: Schema.optional(__listOf__string), IpAddressType: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), ProtocolType: Schema.optional(Schema.String), RouteSelectionExpression: Schema.optional(Schema.String), Tags: Schema.optional(Tags), Version: Schema.optional(Schema.String), Warnings: Schema.optional(__listOf__string)})
export const UpdateApi = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateApi" }, UpdateApiRequest, UpdateApiResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateApiMappingResponse = Schema.Struct({ApiId: Schema.optional(Schema.String), ApiMappingId: Schema.optional(Schema.String), ApiMappingKey: Schema.optional(Schema.String), Stage: Schema.optional(Schema.String)})
export const UpdateApiMapping = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}/apimappings/{ApiMappingId}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateApiMapping" }, UpdateApiMappingRequest, UpdateApiMappingResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateAuthorizerResponse = Schema.Struct({AuthorizerCredentialsArn: Schema.optional(Schema.String), AuthorizerId: Schema.optional(Schema.String), AuthorizerPayloadFormatVersion: Schema.optional(Schema.String), AuthorizerResultTtlInSeconds: Schema.optional(Schema.Number), AuthorizerType: Schema.optional(Schema.String), AuthorizerUri: Schema.optional(Schema.String), EnableSimpleResponses: Schema.optional(Schema.Boolean), IdentitySource: Schema.optional(IdentitySourceList), IdentityValidationExpression: Schema.optional(Schema.String), JwtConfiguration: Schema.optional(JWTConfiguration), Name: Schema.optional(Schema.String)})
export const UpdateAuthorizer = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/authorizers/{AuthorizerId}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateAuthorizer" }, UpdateAuthorizerRequest, UpdateAuthorizerResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateDeploymentResponse = Schema.Struct({AutoDeployed: Schema.optional(Schema.Boolean), CreatedDate: Schema.optional(Schema.Date), DeploymentId: Schema.optional(Schema.String), DeploymentStatus: Schema.optional(Schema.String), DeploymentStatusMessage: Schema.optional(Schema.String), Description: Schema.optional(Schema.String)})
export const UpdateDeployment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/deployments/{DeploymentId}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateDeployment" }, UpdateDeploymentRequest, UpdateDeploymentResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateDomainNameResponse = Schema.Struct({ApiMappingSelectionExpression: Schema.optional(Schema.String), DomainName: Schema.optional(Schema.String), DomainNameArn: Schema.optional(Schema.String), DomainNameConfigurations: Schema.optional(DomainNameConfigurations), MutualTlsAuthentication: Schema.optional(MutualTlsAuthentication), RoutingMode: Schema.optional(Schema.String), Tags: Schema.optional(Tags)})
export const UpdateDomainName = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateDomainName" }, UpdateDomainNameRequest, UpdateDomainNameResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateIntegrationResult = Schema.Struct({ApiGatewayManaged: Schema.optional(Schema.Boolean), ConnectionId: Schema.optional(Schema.String), ConnectionType: Schema.optional(Schema.String), ContentHandlingStrategy: Schema.optional(Schema.String), CredentialsArn: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), IntegrationId: Schema.optional(Schema.String), IntegrationMethod: Schema.optional(Schema.String), IntegrationResponseSelectionExpression: Schema.optional(Schema.String), IntegrationSubtype: Schema.optional(Schema.String), IntegrationType: Schema.optional(Schema.String), IntegrationUri: Schema.optional(Schema.String), PassthroughBehavior: Schema.optional(Schema.String), PayloadFormatVersion: Schema.optional(Schema.String), RequestParameters: Schema.optional(IntegrationParameters), RequestTemplates: Schema.optional(TemplateMap), ResponseParameters: Schema.optional(ResponseParameters), TemplateSelectionExpression: Schema.optional(Schema.String), TimeoutInMillis: Schema.optional(Schema.Number), TlsConfig: Schema.optional(TlsConfig)})
export const UpdateIntegration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/integrations/{IntegrationId}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateIntegration" }, UpdateIntegrationRequest, UpdateIntegrationResult, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateIntegrationResponseResponse = Schema.Struct({ContentHandlingStrategy: Schema.optional(Schema.String), IntegrationResponseId: Schema.optional(Schema.String), IntegrationResponseKey: Schema.optional(Schema.String), ResponseParameters: Schema.optional(IntegrationParameters), ResponseTemplates: Schema.optional(TemplateMap), TemplateSelectionExpression: Schema.optional(Schema.String)})
export const UpdateIntegrationResponse = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/integrations/{IntegrationId}/integrationresponses/{IntegrationResponseId}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateIntegrationResponse" }, UpdateIntegrationResponseRequest, UpdateIntegrationResponseResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateModelResponse = Schema.Struct({ContentType: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), ModelId: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), Schema: Schema.optional(Schema.String)})
export const UpdateModel = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/models/{ModelId}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateModel" }, UpdateModelRequest, UpdateModelResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateRouteResult = Schema.Struct({ApiGatewayManaged: Schema.optional(Schema.Boolean), ApiKeyRequired: Schema.optional(Schema.Boolean), AuthorizationScopes: Schema.optional(AuthorizationScopes), AuthorizationType: Schema.optional(Schema.String), AuthorizerId: Schema.optional(Schema.String), ModelSelectionExpression: Schema.optional(Schema.String), OperationName: Schema.optional(Schema.String), RequestModels: Schema.optional(RouteModels), RequestParameters: Schema.optional(RouteParameters), RouteId: Schema.optional(Schema.String), RouteKey: Schema.optional(Schema.String), RouteResponseSelectionExpression: Schema.optional(Schema.String), Target: Schema.optional(Schema.String)})
export const UpdateRoute = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes/{RouteId}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateRoute" }, UpdateRouteRequest, UpdateRouteResult, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateRouteResponseResponse = Schema.Struct({ModelSelectionExpression: Schema.optional(Schema.String), ResponseModels: Schema.optional(RouteModels), ResponseParameters: Schema.optional(RouteParameters), RouteResponseId: Schema.optional(Schema.String), RouteResponseKey: Schema.optional(Schema.String)})
export const UpdateRouteResponse = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes/{RouteId}/routeresponses/{RouteResponseId}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateRouteResponse" }, UpdateRouteResponseRequest, UpdateRouteResponseResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateStageResponse = Schema.Struct({AccessLogSettings: Schema.optional(AccessLogSettings), ApiGatewayManaged: Schema.optional(Schema.Boolean), AutoDeploy: Schema.optional(Schema.Boolean), ClientCertificateId: Schema.optional(Schema.String), CreatedDate: Schema.optional(Schema.Date), DefaultRouteSettings: Schema.optional(RouteSettings), DeploymentId: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), LastDeploymentStatusMessage: Schema.optional(Schema.String), LastUpdatedDate: Schema.optional(Schema.Date), RouteSettings: Schema.optional(RouteSettingsMap), StageName: Schema.optional(Schema.String), StageVariables: Schema.optional(StageVariablesMap), Tags: Schema.optional(Tags)})
export const UpdateStage = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/stages/{StageName}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateStage" }, UpdateStageRequest, UpdateStageResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateVpcLinkResponse = Schema.Struct({CreatedDate: Schema.optional(Schema.Date), Name: Schema.optional(Schema.String), SecurityGroupIds: Schema.optional(SecurityGroupIdList), SubnetIds: Schema.optional(SubnetIdList), Tags: Schema.optional(Tags), VpcLinkId: Schema.optional(Schema.String), VpcLinkStatus: Schema.optional(Schema.String), VpcLinkStatusMessage: Schema.optional(Schema.String), VpcLinkVersion: Schema.optional(Schema.String)})
export const UpdateVpcLink = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/vpclinks/{VpcLinkId}", method: "PATCH", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "UpdateVpcLink" }, UpdateVpcLinkRequest, UpdateVpcLinkResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ParameterConstraints = Schema.Struct({Required: Schema.optional(Schema.Boolean)})
const RoutingRuleActionInvokeApi = Schema.Struct({ApiId: Schema.String, Stage: Schema.String, StripBasePath: Schema.optional(Schema.Boolean)})
const RoutingRuleMatchBasePaths = Schema.Struct({AnyOf: __listOfSelectionKey})
const RouteParameters = Schema.Record({key: Schema.String, value: ParameterConstraints})
const RoutingRuleAction = Schema.Struct({InvokeApi: RoutingRuleActionInvokeApi})
const __listOfRoutingRuleAction = Schema.Array(RoutingRuleAction)
const ApiMapping = Schema.Struct({ApiId: Schema.String, ApiMappingId: Schema.optional(Schema.String), ApiMappingKey: Schema.optional(Schema.String), Stage: Schema.String})
const __listOfApiMapping = Schema.Array(ApiMapping)
const Api = Schema.Struct({ApiEndpoint: Schema.optional(Schema.String), ApiGatewayManaged: Schema.optional(Schema.Boolean), ApiId: Schema.optional(Schema.String), ApiKeySelectionExpression: Schema.optional(Schema.String), CorsConfiguration: Schema.optional(Cors), CreatedDate: Schema.optional(Schema.Date), Description: Schema.optional(Schema.String), DisableSchemaValidation: Schema.optional(Schema.Boolean), DisableExecuteApiEndpoint: Schema.optional(Schema.Boolean), ImportInfo: Schema.optional(__listOf__string), IpAddressType: Schema.optional(Schema.String), Name: Schema.String, ProtocolType: Schema.String, RouteSelectionExpression: Schema.String, Tags: Schema.optional(Tags), Version: Schema.optional(Schema.String), Warnings: Schema.optional(__listOf__string)})
const __listOfApi = Schema.Array(Api)
const Authorizer = Schema.Struct({AuthorizerCredentialsArn: Schema.optional(Schema.String), AuthorizerId: Schema.optional(Schema.String), AuthorizerPayloadFormatVersion: Schema.optional(Schema.String), AuthorizerResultTtlInSeconds: Schema.optional(Schema.Number), AuthorizerType: Schema.optional(Schema.String), AuthorizerUri: Schema.optional(Schema.String), EnableSimpleResponses: Schema.optional(Schema.Boolean), IdentitySource: Schema.optional(IdentitySourceList), IdentityValidationExpression: Schema.optional(Schema.String), JwtConfiguration: Schema.optional(JWTConfiguration), Name: Schema.String})
const __listOfAuthorizer = Schema.Array(Authorizer)
const Deployment = Schema.Struct({AutoDeployed: Schema.optional(Schema.Boolean), CreatedDate: Schema.optional(Schema.Date), DeploymentId: Schema.optional(Schema.String), DeploymentStatus: Schema.optional(Schema.String), DeploymentStatusMessage: Schema.optional(Schema.String), Description: Schema.optional(Schema.String)})
const __listOfDeployment = Schema.Array(Deployment)
const MutualTlsAuthentication = Schema.Struct({TruststoreUri: Schema.optional(Schema.String), TruststoreVersion: Schema.optional(Schema.String), TruststoreWarnings: Schema.optional(__listOf__string)})
const DomainName = Schema.Struct({ApiMappingSelectionExpression: Schema.optional(Schema.String), DomainName: Schema.String, DomainNameArn: Schema.optional(Schema.String), DomainNameConfigurations: Schema.optional(DomainNameConfigurations), MutualTlsAuthentication: Schema.optional(MutualTlsAuthentication), RoutingMode: Schema.optional(Schema.String), Tags: Schema.optional(Tags)})
const __listOfDomainName = Schema.Array(DomainName)
const TlsConfig = Schema.Struct({ServerNameToVerify: Schema.optional(Schema.String)})
const IntegrationResponse = Schema.Struct({ContentHandlingStrategy: Schema.optional(Schema.String), IntegrationResponseId: Schema.optional(Schema.String), IntegrationResponseKey: Schema.String, ResponseParameters: Schema.optional(IntegrationParameters), ResponseTemplates: Schema.optional(TemplateMap), TemplateSelectionExpression: Schema.optional(Schema.String)})
const __listOfIntegrationResponse = Schema.Array(IntegrationResponse)
const Integration = Schema.Struct({ApiGatewayManaged: Schema.optional(Schema.Boolean), ConnectionId: Schema.optional(Schema.String), ConnectionType: Schema.optional(Schema.String), ContentHandlingStrategy: Schema.optional(Schema.String), CredentialsArn: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), IntegrationId: Schema.optional(Schema.String), IntegrationMethod: Schema.optional(Schema.String), IntegrationResponseSelectionExpression: Schema.optional(Schema.String), IntegrationSubtype: Schema.optional(Schema.String), IntegrationType: Schema.optional(Schema.String), IntegrationUri: Schema.optional(Schema.String), PassthroughBehavior: Schema.optional(Schema.String), PayloadFormatVersion: Schema.optional(Schema.String), RequestParameters: Schema.optional(IntegrationParameters), RequestTemplates: Schema.optional(TemplateMap), ResponseParameters: Schema.optional(ResponseParameters), TemplateSelectionExpression: Schema.optional(Schema.String), TimeoutInMillis: Schema.optional(Schema.Number), TlsConfig: Schema.optional(TlsConfig)})
const __listOfIntegration = Schema.Array(Integration)
const Model = Schema.Struct({ContentType: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), ModelId: Schema.optional(Schema.String), Name: Schema.String, Schema: Schema.optional(Schema.String)})
const __listOfModel = Schema.Array(Model)
const RouteResponse = Schema.Struct({ModelSelectionExpression: Schema.optional(Schema.String), ResponseModels: Schema.optional(RouteModels), ResponseParameters: Schema.optional(RouteParameters), RouteResponseId: Schema.optional(Schema.String), RouteResponseKey: Schema.String})
const __listOfRouteResponse = Schema.Array(RouteResponse)
const Route = Schema.Struct({ApiGatewayManaged: Schema.optional(Schema.Boolean), ApiKeyRequired: Schema.optional(Schema.Boolean), AuthorizationScopes: Schema.optional(AuthorizationScopes), AuthorizationType: Schema.optional(Schema.String), AuthorizerId: Schema.optional(Schema.String), ModelSelectionExpression: Schema.optional(Schema.String), OperationName: Schema.optional(Schema.String), RequestModels: Schema.optional(RouteModels), RequestParameters: Schema.optional(RouteParameters), RouteId: Schema.optional(Schema.String), RouteKey: Schema.String, RouteResponseSelectionExpression: Schema.optional(Schema.String), Target: Schema.optional(Schema.String)})
const __listOfRoute = Schema.Array(Route)
const Stage = Schema.Struct({AccessLogSettings: Schema.optional(AccessLogSettings), ApiGatewayManaged: Schema.optional(Schema.Boolean), AutoDeploy: Schema.optional(Schema.Boolean), ClientCertificateId: Schema.optional(Schema.String), CreatedDate: Schema.optional(Schema.Date), DefaultRouteSettings: Schema.optional(RouteSettings), DeploymentId: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), LastDeploymentStatusMessage: Schema.optional(Schema.String), LastUpdatedDate: Schema.optional(Schema.Date), RouteSettings: Schema.optional(RouteSettingsMap), StageName: Schema.String, StageVariables: Schema.optional(StageVariablesMap), Tags: Schema.optional(Tags)})
const __listOfStage = Schema.Array(Stage)
const VpcLink = Schema.Struct({CreatedDate: Schema.optional(Schema.Date), Name: Schema.String, SecurityGroupIds: SecurityGroupIdList, SubnetIds: SubnetIdList, Tags: Schema.optional(Tags), VpcLinkId: Schema.String, VpcLinkStatus: Schema.optional(Schema.String), VpcLinkStatusMessage: Schema.optional(Schema.String), VpcLinkVersion: Schema.optional(Schema.String)})
const __listOfVpcLink = Schema.Array(VpcLink)
const RoutingRule = Schema.Struct({Actions: Schema.optional(__listOfRoutingRuleAction), Conditions: Schema.optional(__listOfRoutingRuleCondition), Priority: Schema.optional(Schema.Number), RoutingRuleArn: Schema.optional(Schema.String), RoutingRuleId: Schema.optional(Schema.String)})
const __listOfRoutingRule = Schema.Array(RoutingRule)
const RoutingRuleMatchHeaderValue = Schema.Struct({Header: Schema.String, ValueGlob: Schema.String})
const __listOfRoutingRuleMatchHeaderValue = Schema.Array(RoutingRuleMatchHeaderValue)
const CreateApiResponse = Schema.Struct({ApiEndpoint: Schema.optional(Schema.String), ApiGatewayManaged: Schema.optional(Schema.Boolean), ApiId: Schema.optional(Schema.String), ApiKeySelectionExpression: Schema.optional(Schema.String), CorsConfiguration: Schema.optional(Cors), CreatedDate: Schema.optional(Schema.Date), Description: Schema.optional(Schema.String), DisableSchemaValidation: Schema.optional(Schema.Boolean), DisableExecuteApiEndpoint: Schema.optional(Schema.Boolean), ImportInfo: Schema.optional(__listOf__string), IpAddressType: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), ProtocolType: Schema.optional(Schema.String), RouteSelectionExpression: Schema.optional(Schema.String), Tags: Schema.optional(Tags), Version: Schema.optional(Schema.String), Warnings: Schema.optional(__listOf__string)})
export const CreateApi = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateApi" }, CreateApiRequest, CreateApiResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateAuthorizerResponse = Schema.Struct({AuthorizerCredentialsArn: Schema.optional(Schema.String), AuthorizerId: Schema.optional(Schema.String), AuthorizerPayloadFormatVersion: Schema.optional(Schema.String), AuthorizerResultTtlInSeconds: Schema.optional(Schema.Number), AuthorizerType: Schema.optional(Schema.String), AuthorizerUri: Schema.optional(Schema.String), EnableSimpleResponses: Schema.optional(Schema.Boolean), IdentitySource: Schema.optional(IdentitySourceList), IdentityValidationExpression: Schema.optional(Schema.String), JwtConfiguration: Schema.optional(JWTConfiguration), Name: Schema.optional(Schema.String)})
export const CreateAuthorizer = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/authorizers", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateAuthorizer" }, CreateAuthorizerRequest, CreateAuthorizerResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateDomainNameResponse = Schema.Struct({ApiMappingSelectionExpression: Schema.optional(Schema.String), DomainName: Schema.optional(Schema.String), DomainNameArn: Schema.optional(Schema.String), DomainNameConfigurations: Schema.optional(DomainNameConfigurations), MutualTlsAuthentication: Schema.optional(MutualTlsAuthentication), RoutingMode: Schema.optional(Schema.String), Tags: Schema.optional(Tags)})
const CreateIntegrationResult = Schema.Struct({ApiGatewayManaged: Schema.optional(Schema.Boolean), ConnectionId: Schema.optional(Schema.String), ConnectionType: Schema.optional(Schema.String), ContentHandlingStrategy: Schema.optional(Schema.String), CredentialsArn: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), IntegrationId: Schema.optional(Schema.String), IntegrationMethod: Schema.optional(Schema.String), IntegrationResponseSelectionExpression: Schema.optional(Schema.String), IntegrationSubtype: Schema.optional(Schema.String), IntegrationType: Schema.optional(Schema.String), IntegrationUri: Schema.optional(Schema.String), PassthroughBehavior: Schema.optional(Schema.String), PayloadFormatVersion: Schema.optional(Schema.String), RequestParameters: Schema.optional(IntegrationParameters), RequestTemplates: Schema.optional(TemplateMap), ResponseParameters: Schema.optional(ResponseParameters), TemplateSelectionExpression: Schema.optional(Schema.String), TimeoutInMillis: Schema.optional(Schema.Number), TlsConfig: Schema.optional(TlsConfig)})
export const CreateIntegration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/integrations", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateIntegration" }, CreateIntegrationRequest, CreateIntegrationResult, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateRouteRequest = Schema.Struct({ApiId: Schema.String, ApiKeyRequired: Schema.optional(Schema.Boolean), AuthorizationScopes: Schema.optional(AuthorizationScopes), AuthorizationType: Schema.optional(Schema.String), AuthorizerId: Schema.optional(Schema.String), ModelSelectionExpression: Schema.optional(Schema.String), OperationName: Schema.optional(Schema.String), RequestModels: Schema.optional(RouteModels), RequestParameters: Schema.optional(RouteParameters), RouteKey: Schema.String, RouteResponseSelectionExpression: Schema.optional(Schema.String), Target: Schema.optional(Schema.String)})
const CreateStageResponse = Schema.Struct({AccessLogSettings: Schema.optional(AccessLogSettings), ApiGatewayManaged: Schema.optional(Schema.Boolean), AutoDeploy: Schema.optional(Schema.Boolean), ClientCertificateId: Schema.optional(Schema.String), CreatedDate: Schema.optional(Schema.Date), DefaultRouteSettings: Schema.optional(RouteSettings), DeploymentId: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), LastDeploymentStatusMessage: Schema.optional(Schema.String), LastUpdatedDate: Schema.optional(Schema.Date), RouteSettings: Schema.optional(RouteSettingsMap), StageName: Schema.optional(Schema.String), StageVariables: Schema.optional(StageVariablesMap), Tags: Schema.optional(Tags)})
export const CreateStage = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/stages", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateStage" }, CreateStageRequest, CreateStageResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetApiMappingsResponse = Schema.Struct({Items: Schema.optional(__listOfApiMapping), NextToken: Schema.optional(Schema.String)})
export const GetApiMappings = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}/apimappings", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetApiMappings" }, GetApiMappingsRequest, GetApiMappingsResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetApisResponse = Schema.Struct({Items: Schema.optional(__listOfApi), NextToken: Schema.optional(Schema.String)})
export const GetApis = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetApis" }, GetApisRequest, GetApisResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetAuthorizersResponse = Schema.Struct({Items: Schema.optional(__listOfAuthorizer), NextToken: Schema.optional(Schema.String)})
export const GetAuthorizers = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/authorizers", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetAuthorizers" }, GetAuthorizersRequest, GetAuthorizersResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetDeploymentsResponse = Schema.Struct({Items: Schema.optional(__listOfDeployment), NextToken: Schema.optional(Schema.String)})
export const GetDeployments = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/deployments", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetDeployments" }, GetDeploymentsRequest, GetDeploymentsResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetDomainNameResponse = Schema.Struct({ApiMappingSelectionExpression: Schema.optional(Schema.String), DomainName: Schema.optional(Schema.String), DomainNameArn: Schema.optional(Schema.String), DomainNameConfigurations: Schema.optional(DomainNameConfigurations), MutualTlsAuthentication: Schema.optional(MutualTlsAuthentication), RoutingMode: Schema.optional(Schema.String), Tags: Schema.optional(Tags)})
export const GetDomainName = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetDomainName" }, GetDomainNameRequest, GetDomainNameResponse, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetDomainNamesResponse = Schema.Struct({Items: Schema.optional(__listOfDomainName), NextToken: Schema.optional(Schema.String)})
export const GetDomainNames = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetDomainNames" }, GetDomainNamesRequest, GetDomainNamesResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetIntegrationResult = Schema.Struct({ApiGatewayManaged: Schema.optional(Schema.Boolean), ConnectionId: Schema.optional(Schema.String), ConnectionType: Schema.optional(Schema.String), ContentHandlingStrategy: Schema.optional(Schema.String), CredentialsArn: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), IntegrationId: Schema.optional(Schema.String), IntegrationMethod: Schema.optional(Schema.String), IntegrationResponseSelectionExpression: Schema.optional(Schema.String), IntegrationSubtype: Schema.optional(Schema.String), IntegrationType: Schema.optional(Schema.String), IntegrationUri: Schema.optional(Schema.String), PassthroughBehavior: Schema.optional(Schema.String), PayloadFormatVersion: Schema.optional(Schema.String), RequestParameters: Schema.optional(IntegrationParameters), RequestTemplates: Schema.optional(TemplateMap), ResponseParameters: Schema.optional(ResponseParameters), TemplateSelectionExpression: Schema.optional(Schema.String), TimeoutInMillis: Schema.optional(Schema.Number), TlsConfig: Schema.optional(TlsConfig)})
export const GetIntegration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/integrations/{IntegrationId}", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetIntegration" }, GetIntegrationRequest, GetIntegrationResult, Schema.Union(ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetIntegrationResponsesResponse = Schema.Struct({Items: Schema.optional(__listOfIntegrationResponse), NextToken: Schema.optional(Schema.String)})
export const GetIntegrationResponses = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/integrations/{IntegrationId}/integrationresponses", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetIntegrationResponses" }, GetIntegrationResponsesRequest, GetIntegrationResponsesResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetIntegrationsResponse = Schema.Struct({Items: Schema.optional(__listOfIntegration), NextToken: Schema.optional(Schema.String)})
export const GetIntegrations = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/integrations", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetIntegrations" }, GetIntegrationsRequest, GetIntegrationsResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetModelsResponse = Schema.Struct({Items: Schema.optional(__listOfModel), NextToken: Schema.optional(Schema.String)})
export const GetModels = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/models", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetModels" }, GetModelsRequest, GetModelsResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetRouteResponsesResponse = Schema.Struct({Items: Schema.optional(__listOfRouteResponse), NextToken: Schema.optional(Schema.String)})
export const GetRouteResponses = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes/{RouteId}/routeresponses", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetRouteResponses" }, GetRouteResponsesRequest, GetRouteResponsesResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetRoutesResponse = Schema.Struct({Items: Schema.optional(__listOfRoute), NextToken: Schema.optional(Schema.String)})
export const GetRoutes = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetRoutes" }, GetRoutesRequest, GetRoutesResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetStagesResponse = Schema.Struct({Items: Schema.optional(__listOfStage), NextToken: Schema.optional(Schema.String)})
export const GetStages = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/stages", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetStages" }, GetStagesRequest, GetStagesResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetVpcLinksResponse = Schema.Struct({Items: Schema.optional(__listOfVpcLink), NextToken: Schema.optional(Schema.String)})
export const GetVpcLinks = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/vpclinks", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "GetVpcLinks" }, GetVpcLinksRequest, GetVpcLinksResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListRoutingRulesResponse = Schema.Struct({NextToken: Schema.optional(Schema.String), RoutingRules: Schema.optional(__listOfRoutingRule)})
export const ListRoutingRules = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}/routingrules", method: "GET", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "ListRoutingRules" }, ListRoutingRulesRequest, ListRoutingRulesResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const RoutingRuleMatchHeaders = Schema.Struct({AnyOf: __listOfRoutingRuleMatchHeaderValue})
const RoutingRuleCondition = Schema.Struct({MatchBasePaths: Schema.optional(RoutingRuleMatchBasePaths), MatchHeaders: Schema.optional(RoutingRuleMatchHeaders)})
const __listOfRoutingRuleCondition = Schema.Array(RoutingRuleCondition)
const AccessDeniedException = Schema.Struct({Message: Schema.optional(Schema.String)})
export const CreateDomainName = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateDomainName" }, CreateDomainNameRequest, CreateDomainNameResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateRouteResult = Schema.Struct({ApiGatewayManaged: Schema.optional(Schema.Boolean), ApiKeyRequired: Schema.optional(Schema.Boolean), AuthorizationScopes: Schema.optional(AuthorizationScopes), AuthorizationType: Schema.optional(Schema.String), AuthorizerId: Schema.optional(Schema.String), ModelSelectionExpression: Schema.optional(Schema.String), OperationName: Schema.optional(Schema.String), RequestModels: Schema.optional(RouteModels), RequestParameters: Schema.optional(RouteParameters), RouteId: Schema.optional(Schema.String), RouteKey: Schema.optional(Schema.String), RouteResponseSelectionExpression: Schema.optional(Schema.String), Target: Schema.optional(Schema.String)})
export const CreateRoute = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/apis/{ApiId}/routes", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateRoute" }, CreateRouteRequest, CreateRouteResult, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateRoutingRuleRequest = Schema.Struct({Actions: __listOfRoutingRuleAction, Conditions: __listOfRoutingRuleCondition, DomainName: Schema.String, DomainNameId: Schema.optional(Schema.String), Priority: Schema.Number})
const CreateRoutingRuleResponse = Schema.Struct({Actions: Schema.optional(__listOfRoutingRuleAction), Conditions: Schema.optional(__listOfRoutingRuleCondition), Priority: Schema.optional(Schema.Number), RoutingRuleArn: Schema.optional(Schema.String), RoutingRuleId: Schema.optional(Schema.String)})
export const CreateRoutingRule = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/v2/domainnames/{DomainName}/routingrules", method: "POST", sdkId: "ApiGatewayV2", sigV4ServiceName: "apigateway", name: "CreateRoutingRule" }, CreateRoutingRuleRequest, CreateRoutingRuleResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
