import { Schema} from "effect"
import { FormatXMLRequest, FormatXMLResponse, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
const TagKeyList = Schema.Array(Schema.String)
const CreateDeploymentStrategyRequest = Schema.Struct({Name: Schema.String, Description: Schema.optional(Schema.String), DeploymentDurationInMinutes: Schema.Number, FinalBakeTimeInMinutes: Schema.optional(Schema.Number), GrowthFactor: Schema.Number, GrowthType: Schema.optional(Schema.String), ReplicateTo: Schema.optional(Schema.String), Tags: Schema.optional(TagMap)})
const CreateHostedConfigurationVersionRequest = Schema.Struct({ApplicationId: Schema.String, ConfigurationProfileId: Schema.String, Description: Schema.optional(Header("Description")), Content: Body("undefined", StreamBody()), ContentType: Header("Content-Type"), LatestVersionNumber: Schema.optional(Header("Latest-Version-Number", Schema.Number)), VersionLabel: Schema.optional(Header("VersionLabel"))})
const DeleteApplicationRequest = Schema.Struct({ApplicationId: Schema.String})
const DeleteConfigurationProfileRequest = Schema.Struct({ApplicationId: Schema.String, ConfigurationProfileId: Schema.String, DeletionProtectionCheck: Schema.optional(Header("x-amzn-deletion-protection-check"))})
const DeleteDeploymentStrategyRequest = Schema.Struct({DeploymentStrategyId: Schema.String})
const DeleteEnvironmentRequest = Schema.Struct({EnvironmentId: Schema.String, ApplicationId: Schema.String, DeletionProtectionCheck: Schema.optional(Header("x-amzn-deletion-protection-check"))})
const DeleteExtensionRequest = Schema.Struct({ExtensionIdentifier: Schema.String, VersionNumber: Schema.optional(Schema.Number)})
export const DeleteExtension = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/extensions/{ExtensionIdentifier}", method: "DELETE", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "DeleteExtension" }, DeleteExtensionRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteExtensionAssociationRequest = Schema.Struct({ExtensionAssociationId: Schema.String})
export const DeleteExtensionAssociation = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/extensionassociations/{ExtensionAssociationId}", method: "DELETE", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "DeleteExtensionAssociation" }, DeleteExtensionAssociationRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeleteHostedConfigurationVersionRequest = Schema.Struct({ApplicationId: Schema.String, ConfigurationProfileId: Schema.String, VersionNumber: Schema.Number})
export const DeleteHostedConfigurationVersion = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/hostedconfigurationversions/{VersionNumber}", method: "DELETE", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "DeleteHostedConfigurationVersion" }, DeleteHostedConfigurationVersionRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetApplicationRequest = Schema.Struct({ApplicationId: Schema.String})
const GetConfigurationRequest = Schema.Struct({Application: Schema.String, Environment: Schema.String, Configuration: Schema.String, ClientId: Schema.String, ClientConfigurationVersion: Schema.optional(Schema.String)})
const GetConfigurationProfileRequest = Schema.Struct({ApplicationId: Schema.String, ConfigurationProfileId: Schema.String})
const GetDeploymentRequest = Schema.Struct({ApplicationId: Schema.String, EnvironmentId: Schema.String, DeploymentNumber: Schema.Number})
const GetDeploymentStrategyRequest = Schema.Struct({DeploymentStrategyId: Schema.String})
export const GetDeploymentStrategy = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/deploymentstrategies/{DeploymentStrategyId}", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "GetDeploymentStrategy" }, GetDeploymentStrategyRequest, DeploymentStrategy, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetEnvironmentRequest = Schema.Struct({ApplicationId: Schema.String, EnvironmentId: Schema.String})
const GetExtensionRequest = Schema.Struct({ExtensionIdentifier: Schema.String, VersionNumber: Schema.optional(Schema.Number)})
const GetExtensionAssociationRequest = Schema.Struct({ExtensionAssociationId: Schema.String})
const GetHostedConfigurationVersionRequest = Schema.Struct({ApplicationId: Schema.String, ConfigurationProfileId: Schema.String, VersionNumber: Schema.Number})
export const GetHostedConfigurationVersion = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/hostedconfigurationversions/{VersionNumber}", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "GetHostedConfigurationVersion" }, GetHostedConfigurationVersionRequest, HostedConfigurationVersion, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListApplicationsRequest = Schema.Struct({MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)})
const ListConfigurationProfilesRequest = Schema.Struct({ApplicationId: Schema.String, MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String), Type: Schema.optional(Schema.String)})
const ListDeploymentsRequest = Schema.Struct({ApplicationId: Schema.String, EnvironmentId: Schema.String, MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)})
const ListDeploymentStrategiesRequest = Schema.Struct({MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)})
const ListEnvironmentsRequest = Schema.Struct({ApplicationId: Schema.String, MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)})
const ListExtensionAssociationsRequest = Schema.Struct({ResourceIdentifier: Schema.optional(Schema.String), ExtensionIdentifier: Schema.optional(Schema.String), ExtensionVersionNumber: Schema.optional(Schema.Number), MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)})
const ListExtensionsRequest = Schema.Struct({MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String), Name: Schema.optional(Schema.String)})
const ListHostedConfigurationVersionsRequest = Schema.Struct({ApplicationId: Schema.String, ConfigurationProfileId: Schema.String, MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String), VersionLabel: Schema.optional(Schema.String)})
const ListTagsForResourceRequest = Schema.Struct({ResourceArn: Schema.String})
const StopDeploymentRequest = Schema.Struct({ApplicationId: Schema.String, EnvironmentId: Schema.String, DeploymentNumber: Schema.Number, AllowRevert: Schema.optional(Header("Allow-Revert", Schema.Boolean))})
export const StopDeployment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/environments/{EnvironmentId}/deployments/{DeploymentNumber}", method: "DELETE", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "StopDeployment" }, StopDeploymentRequest, Deployment, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const TagResourceRequest = Schema.Struct({ResourceArn: Schema.String, Tags: TagMap})
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{ResourceArn}", method: "POST", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "TagResource" }, TagResourceRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UntagResourceRequest = Schema.Struct({ResourceArn: Schema.String, TagKeys: TagKeyList})
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{ResourceArn}", method: "DELETE", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "UntagResource" }, UntagResourceRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateAccountSettingsRequest = Schema.Struct({DeletionProtection: Schema.optional(DeletionProtectionSettings)})
export const UpdateAccountSettings = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/settings", method: "PATCH", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "UpdateAccountSettings" }, UpdateAccountSettingsRequest, AccountSettings, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateApplicationRequest = Schema.Struct({ApplicationId: Schema.String, Name: Schema.optional(Schema.String), Description: Schema.optional(Schema.String)})
export const UpdateApplication = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}", method: "PATCH", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "UpdateApplication" }, UpdateApplicationRequest, Application, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateConfigurationProfileRequest = Schema.Struct({ApplicationId: Schema.String, ConfigurationProfileId: Schema.String, Name: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), RetrievalRoleArn: Schema.optional(Schema.String), Validators: Schema.optional(ValidatorList), KmsKeyIdentifier: Schema.optional(Schema.String)})
export const UpdateConfigurationProfile = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}", method: "PATCH", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "UpdateConfigurationProfile" }, UpdateConfigurationProfileRequest, ConfigurationProfile, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateDeploymentStrategyRequest = Schema.Struct({DeploymentStrategyId: Schema.String, Description: Schema.optional(Schema.String), DeploymentDurationInMinutes: Schema.optional(Schema.Number), FinalBakeTimeInMinutes: Schema.optional(Schema.Number), GrowthFactor: Schema.optional(Schema.Number), GrowthType: Schema.optional(Schema.String)})
export const UpdateDeploymentStrategy = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/deploymentstrategies/{DeploymentStrategyId}", method: "PATCH", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "UpdateDeploymentStrategy" }, UpdateDeploymentStrategyRequest, DeploymentStrategy, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateEnvironmentRequest = Schema.Struct({ApplicationId: Schema.String, EnvironmentId: Schema.String, Name: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), Monitors: Schema.optional(MonitorList)})
export const UpdateEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/environments/{EnvironmentId}", method: "PATCH", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "UpdateEnvironment" }, UpdateEnvironmentRequest, Environment, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateExtensionRequest = Schema.Struct({ExtensionIdentifier: Schema.String, Description: Schema.optional(Schema.String), Actions: Schema.optional(ActionsMap), Parameters: Schema.optional(ParameterMap), VersionNumber: Schema.optional(Schema.Number)})
export const UpdateExtension = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/extensions/{ExtensionIdentifier}", method: "PATCH", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "UpdateExtension" }, UpdateExtensionRequest, Extension, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateExtensionAssociationRequest = Schema.Struct({ExtensionAssociationId: Schema.String, Parameters: Schema.optional(ParameterValueMap)})
export const UpdateExtensionAssociation = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/extensionassociations/{ExtensionAssociationId}", method: "PATCH", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "UpdateExtensionAssociation" }, UpdateExtensionAssociationRequest, ExtensionAssociation, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ValidateConfigurationRequest = Schema.Struct({ApplicationId: Schema.String, ConfigurationProfileId: Schema.String, ConfigurationVersion: Schema.String})
export const ValidateConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/validators", method: "POST", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "ValidateConfiguration" }, ValidateConfigurationRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const TagMap = Schema.Record({key: Schema.String, value: Schema.String})
const Validator = Schema.Struct({Type: Schema.String, Content: Schema.String})
const ValidatorList = Schema.Array(Validator)
const Monitor = Schema.Struct({AlarmArn: Schema.String, AlarmRoleArn: Schema.optional(Schema.String)})
const MonitorList = Schema.Array(Monitor)
const ParameterValueMap = Schema.Record({key: Schema.String, value: Schema.String})
const DeletionProtectionSettings = Schema.Struct({Enabled: Schema.optional(Schema.Boolean), ProtectionPeriodInMinutes: Schema.optional(Schema.Number)})
const ApplicationList = Schema.Array(Application)
const DeploymentStrategyList = Schema.Array(DeploymentStrategy)
const EnvironmentList = Schema.Array(Environment)
const DynamicParameterMap = Schema.Record({key: Schema.String, value: Schema.String})
const CreateApplicationRequest = Schema.Struct({Name: Schema.String, Description: Schema.optional(Schema.String), Tags: Schema.optional(TagMap)})
const CreateConfigurationProfileRequest = Schema.Struct({ApplicationId: Schema.String, Name: Schema.String, Description: Schema.optional(Schema.String), LocationUri: Schema.String, RetrievalRoleArn: Schema.optional(Schema.String), Validators: Schema.optional(ValidatorList), Tags: Schema.optional(TagMap), Type: Schema.optional(Schema.String), KmsKeyIdentifier: Schema.optional(Schema.String)})
export const CreateConfigurationProfile = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/configurationprofiles", method: "POST", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "CreateConfigurationProfile" }, CreateConfigurationProfileRequest, ConfigurationProfile, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeploymentStrategy = Schema.Struct({Id: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), DeploymentDurationInMinutes: Schema.optional(Schema.Number), GrowthType: Schema.optional(Schema.String), GrowthFactor: Schema.optional(Schema.Number), FinalBakeTimeInMinutes: Schema.optional(Schema.Number), ReplicateTo: Schema.optional(Schema.String)})
export const CreateDeploymentStrategy = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/deploymentstrategies", method: "POST", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "CreateDeploymentStrategy" }, CreateDeploymentStrategyRequest, DeploymentStrategy, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateEnvironmentRequest = Schema.Struct({ApplicationId: Schema.String, Name: Schema.String, Description: Schema.optional(Schema.String), Monitors: Schema.optional(MonitorList), Tags: Schema.optional(TagMap)})
export const CreateEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/environments", method: "POST", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "CreateEnvironment" }, CreateEnvironmentRequest, Environment, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateExtensionAssociationRequest = Schema.Struct({ExtensionIdentifier: Schema.String, ExtensionVersionNumber: Schema.optional(Schema.Number), ResourceIdentifier: Schema.String, Parameters: Schema.optional(ParameterValueMap), Tags: Schema.optional(TagMap)})
export const CreateExtensionAssociation = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/extensionassociations", method: "POST", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "CreateExtensionAssociation" }, CreateExtensionAssociationRequest, ExtensionAssociation, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const HostedConfigurationVersion = Schema.Struct({ApplicationId: Schema.optional(Header("Application-Id")), ConfigurationProfileId: Schema.optional(Header("Configuration-Profile-Id")), VersionNumber: Schema.optional(Header("Version-Number", Schema.Number)), Description: Schema.optional(Header("Description")), Content: Schema.optional(Body("undefined", StreamBody())), ContentType: Schema.optional(Header("Content-Type")), VersionLabel: Schema.optional(Header("VersionLabel")), KmsKeyArn: Schema.optional(Header("KmsKeyArn"))})
const ConflictException = Schema.Struct({Message: Schema.optional(Schema.String)})
export const DeleteConfigurationProfile = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}", method: "DELETE", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "DeleteConfigurationProfile" }, DeleteConfigurationProfileRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const InternalServerException = Schema.Struct({Message: Schema.optional(Schema.String)})
export const DeleteDeploymentStrategy = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/deployementstrategies/{DeploymentStrategyId}", method: "DELETE", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "DeleteDeploymentStrategy" }, DeleteDeploymentStrategyRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ResourceNotFoundException = Schema.Struct({Message: Schema.optional(Schema.String), ResourceName: Schema.optional(Schema.String)})
export const DeleteEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/environments/{EnvironmentId}", method: "DELETE", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "DeleteEnvironment" }, DeleteEnvironmentRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const AccountSettings = Schema.Struct({DeletionProtection: Schema.optional(DeletionProtectionSettings)})
export const GetAccountSettings = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/settings", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "GetAccountSettings" }, Schema.Struct({}), AccountSettings, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Application = Schema.Struct({Id: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), Description: Schema.optional(Schema.String)})
export const GetApplication = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "GetApplication" }, GetApplicationRequest, Application, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Configuration = Schema.Struct({Content: Schema.optional(Body("undefined", StreamBody())), ConfigurationVersion: Schema.optional(Header("Configuration-Version")), ContentType: Schema.optional(Header("Content-Type"))})
export const GetConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{Application}/environments/{Environment}/configurations/{Configuration}", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "GetConfiguration" }, GetConfigurationRequest, Configuration, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ConfigurationProfile = Schema.Struct({ApplicationId: Schema.optional(Schema.String), Id: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), LocationUri: Schema.optional(Schema.String), RetrievalRoleArn: Schema.optional(Schema.String), Validators: Schema.optional(ValidatorList), Type: Schema.optional(Schema.String), KmsKeyArn: Schema.optional(Schema.String), KmsKeyIdentifier: Schema.optional(Schema.String)})
export const GetConfigurationProfile = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "GetConfigurationProfile" }, GetConfigurationProfileRequest, ConfigurationProfile, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Environment = Schema.Struct({ApplicationId: Schema.optional(Schema.String), Id: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), State: Schema.optional(Schema.String), Monitors: Schema.optional(MonitorList)})
export const GetEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/environments/{EnvironmentId}", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "GetEnvironment" }, GetEnvironmentRequest, Environment, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Extension = Schema.Struct({Id: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), VersionNumber: Schema.optional(Schema.Number), Arn: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), Actions: Schema.optional(ActionsMap), Parameters: Schema.optional(ParameterMap)})
export const GetExtension = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/extensions/{ExtensionIdentifier}", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "GetExtension" }, GetExtensionRequest, Extension, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ExtensionAssociation = Schema.Struct({Id: Schema.optional(Schema.String), ExtensionArn: Schema.optional(Schema.String), ResourceArn: Schema.optional(Schema.String), Arn: Schema.optional(Schema.String), Parameters: Schema.optional(ParameterValueMap), ExtensionVersionNumber: Schema.optional(Schema.Number)})
export const GetExtensionAssociation = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/extensionassociations/{ExtensionAssociationId}", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "GetExtensionAssociation" }, GetExtensionAssociationRequest, ExtensionAssociation, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Applications = Schema.Struct({Items: Schema.optional(ApplicationList), NextToken: Schema.optional(Schema.String)})
export const ListApplications = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "ListApplications" }, ListApplicationsRequest, Applications, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DeploymentStrategies = Schema.Struct({Items: Schema.optional(DeploymentStrategyList), NextToken: Schema.optional(Schema.String)})
export const ListDeploymentStrategies = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/deploymentstrategies", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "ListDeploymentStrategies" }, ListDeploymentStrategiesRequest, DeploymentStrategies, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Environments = Schema.Struct({Items: Schema.optional(EnvironmentList), NextToken: Schema.optional(Schema.String)})
export const ListEnvironments = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/environments", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "ListEnvironments" }, ListEnvironmentsRequest, Environments, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ResourceTags = Schema.Struct({Tags: Schema.optional(TagMap)})
export const ListTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{ResourceArn}", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "ListTagsForResource" }, ListTagsForResourceRequest, ResourceTags, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const StartDeploymentRequest = Schema.Struct({ApplicationId: Schema.String, EnvironmentId: Schema.String, DeploymentStrategyId: Schema.String, ConfigurationProfileId: Schema.String, ConfigurationVersion: Schema.String, Description: Schema.optional(Schema.String), Tags: Schema.optional(TagMap), KmsKeyIdentifier: Schema.optional(Schema.String), DynamicExtensionParameters: Schema.optional(DynamicParameterMap)})
export const StartDeployment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/environments/{EnvironmentId}/deployments", method: "POST", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "StartDeployment" }, StartDeploymentRequest, Deployment, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Action = Schema.Struct({Name: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), Uri: Schema.optional(Schema.String), RoleArn: Schema.optional(Schema.String)})
const ActionList = Schema.Array(Action)
const Parameter = Schema.Struct({Description: Schema.optional(Schema.String), Required: Schema.optional(Schema.Boolean), Dynamic: Schema.optional(Schema.Boolean)})
const ValidatorTypeList = Schema.Array(Schema.String)
const ActionsMap = Schema.Record({key: Schema.String, value: ActionList})
const ParameterMap = Schema.Record({key: Schema.String, value: Parameter})
const AppliedExtension = Schema.Struct({ExtensionId: Schema.optional(Schema.String), ExtensionAssociationId: Schema.optional(Schema.String), VersionNumber: Schema.optional(Schema.Number), Parameters: Schema.optional(ParameterValueMap)})
const AppliedExtensions = Schema.Array(AppliedExtension)
const ConfigurationProfileSummary = Schema.Struct({ApplicationId: Schema.optional(Schema.String), Id: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), LocationUri: Schema.optional(Schema.String), ValidatorTypes: Schema.optional(ValidatorTypeList), Type: Schema.optional(Schema.String)})
const ConfigurationProfileSummaryList = Schema.Array(ConfigurationProfileSummary)
const DeploymentSummary = Schema.Struct({DeploymentNumber: Schema.optional(Schema.Number), ConfigurationName: Schema.optional(Schema.String), ConfigurationVersion: Schema.optional(Schema.String), DeploymentDurationInMinutes: Schema.optional(Schema.Number), GrowthType: Schema.optional(Schema.String), GrowthFactor: Schema.optional(Schema.Number), FinalBakeTimeInMinutes: Schema.optional(Schema.Number), State: Schema.optional(Schema.String), PercentageComplete: Schema.optional(Schema.Number), StartedAt: Schema.optional(Schema.Date), CompletedAt: Schema.optional(Schema.Date), VersionLabel: Schema.optional(Schema.String)})
const DeploymentList = Schema.Array(DeploymentSummary)
const ExtensionAssociationSummary = Schema.Struct({Id: Schema.optional(Schema.String), ExtensionArn: Schema.optional(Schema.String), ResourceArn: Schema.optional(Schema.String)})
const ExtensionAssociationSummaries = Schema.Array(ExtensionAssociationSummary)
const ExtensionSummary = Schema.Struct({Id: Schema.optional(Schema.String), Name: Schema.optional(Schema.String), VersionNumber: Schema.optional(Schema.Number), Arn: Schema.optional(Schema.String), Description: Schema.optional(Schema.String)})
const ExtensionSummaries = Schema.Array(ExtensionSummary)
const HostedConfigurationVersionSummary = Schema.Struct({ApplicationId: Schema.optional(Schema.String), ConfigurationProfileId: Schema.optional(Schema.String), VersionNumber: Schema.optional(Schema.Number), Description: Schema.optional(Schema.String), ContentType: Schema.optional(Schema.String), VersionLabel: Schema.optional(Schema.String), KmsKeyArn: Schema.optional(Schema.String)})
const HostedConfigurationVersionSummaryList = Schema.Array(HostedConfigurationVersionSummary)
const ServiceQuotaExceededException = Schema.Struct({Message: Schema.optional(Schema.String)})
export const CreateApplication = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications", method: "POST", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "CreateApplication" }, CreateApplicationRequest, Application, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateExtensionRequest = Schema.Struct({Name: Schema.String, Description: Schema.optional(Schema.String), Actions: ActionsMap, Parameters: Schema.optional(ParameterMap), Tags: Schema.optional(TagMap), LatestVersionNumber: Schema.optional(Header("Latest-Version-Number", Schema.Number))})
export const CreateExtension = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/extensions", method: "POST", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "CreateExtension" }, CreateExtensionRequest, Extension, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const PayloadTooLargeException = Schema.Struct({Message: Schema.optional(Schema.String), Measure: Schema.optional(Schema.String), Limit: Schema.optional(Schema.Number), Size: Schema.optional(Schema.Number)})
export const CreateHostedConfigurationVersion = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/hostedconfigurationversions", method: "POST", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "CreateHostedConfigurationVersion" }, CreateHostedConfigurationVersionRequest, HostedConfigurationVersion, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("PayloadTooLargeException", PayloadTooLargeException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ConfigurationProfiles = Schema.Struct({Items: Schema.optional(ConfigurationProfileSummaryList), NextToken: Schema.optional(Schema.String)})
export const ListConfigurationProfiles = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/configurationprofiles", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "ListConfigurationProfiles" }, ListConfigurationProfilesRequest, ConfigurationProfiles, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Deployments = Schema.Struct({Items: Schema.optional(DeploymentList), NextToken: Schema.optional(Schema.String)})
export const ListDeployments = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/environments/{EnvironmentId}/deployments", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "ListDeployments" }, ListDeploymentsRequest, Deployments, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ExtensionAssociations = Schema.Struct({Items: Schema.optional(ExtensionAssociationSummaries), NextToken: Schema.optional(Schema.String)})
export const ListExtensionAssociations = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/extensionassociations", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "ListExtensionAssociations" }, ListExtensionAssociationsRequest, ExtensionAssociations, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Extensions = Schema.Struct({Items: Schema.optional(ExtensionSummaries), NextToken: Schema.optional(Schema.String)})
export const ListExtensions = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/extensions", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "ListExtensions" }, ListExtensionsRequest, Extensions, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const HostedConfigurationVersions = Schema.Struct({Items: Schema.optional(HostedConfigurationVersionSummaryList), NextToken: Schema.optional(Schema.String)})
export const ListHostedConfigurationVersions = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/hostedconfigurationversions", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "ListHostedConfigurationVersions" }, ListHostedConfigurationVersionsRequest, HostedConfigurationVersions, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const InvalidConfigurationDetail = Schema.Struct({Constraint: Schema.optional(Schema.String), Location: Schema.optional(Schema.String), Reason: Schema.optional(Schema.String), Type: Schema.optional(Schema.String), Value: Schema.optional(Schema.String)})
const InvalidConfigurationDetailList = Schema.Array(InvalidConfigurationDetail)
const ActionInvocation = Schema.Struct({ExtensionIdentifier: Schema.optional(Schema.String), ActionName: Schema.optional(Schema.String), Uri: Schema.optional(Schema.String), RoleArn: Schema.optional(Schema.String), ErrorMessage: Schema.optional(Schema.String), ErrorCode: Schema.optional(Schema.String), InvocationId: Schema.optional(Schema.String)})
const ActionInvocations = Schema.Array(ActionInvocation)
const BadRequestDetails = Schema.Union(InvalidConfigurationDetailList)
const DeploymentEvent = Schema.Struct({EventType: Schema.optional(Schema.String), TriggeredBy: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), ActionInvocations: Schema.optional(ActionInvocations), OccurredAt: Schema.optional(Schema.Date)})
const DeploymentEvents = Schema.Array(DeploymentEvent)
const BadRequestException = Schema.Struct({Message: Schema.optional(Schema.String), Reason: Schema.optional(Schema.String), Details: Schema.optional(BadRequestDetails)})
export const DeleteApplication = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}", method: "DELETE", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "DeleteApplication" }, DeleteApplicationRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Deployment = Schema.Struct({ApplicationId: Schema.optional(Schema.String), EnvironmentId: Schema.optional(Schema.String), DeploymentStrategyId: Schema.optional(Schema.String), ConfigurationProfileId: Schema.optional(Schema.String), DeploymentNumber: Schema.optional(Schema.Number), ConfigurationName: Schema.optional(Schema.String), ConfigurationLocationUri: Schema.optional(Schema.String), ConfigurationVersion: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), DeploymentDurationInMinutes: Schema.optional(Schema.Number), GrowthType: Schema.optional(Schema.String), GrowthFactor: Schema.optional(Schema.Number), FinalBakeTimeInMinutes: Schema.optional(Schema.Number), State: Schema.optional(Schema.String), EventLog: Schema.optional(DeploymentEvents), PercentageComplete: Schema.optional(Schema.Number), StartedAt: Schema.optional(Schema.Date), CompletedAt: Schema.optional(Schema.Date), AppliedExtensions: Schema.optional(AppliedExtensions), KmsKeyArn: Schema.optional(Schema.String), KmsKeyIdentifier: Schema.optional(Schema.String), VersionLabel: Schema.optional(Schema.String)})
export const GetDeployment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/applications/{ApplicationId}/environments/{EnvironmentId}/deployments/{DeploymentNumber}", method: "GET", sdkId: "AppConfig", sigV4ServiceName: "appconfig", name: "GetDeployment" }, GetDeploymentRequest, Deployment, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
