import * as Schema from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import { Operation, Path, Header, StreamBody, Body } from "../schema-helpers.ts";

//# Schemas
export const ExecutionIds = Schema.Array(Schema.String);
export const ConnectorProfileNameList = Schema.Array(Schema.String);
export const ConnectorTypeList = Schema.Array(Schema.String);
export const TagKeyList = Schema.Array(Schema.String);
export class CancelFlowExecutionsRequest extends Schema.Class<CancelFlowExecutionsRequest>("CancelFlowExecutionsRequest")({flowName: Schema.String, executionIds: Schema.optional(ExecutionIds)}) {}
export class DeleteConnectorProfileRequest extends Schema.Class<DeleteConnectorProfileRequest>("DeleteConnectorProfileRequest")({connectorProfileName: Schema.String, forceDelete: Schema.optional(Schema.Boolean)}) {}
export class DeleteConnectorProfileResponse extends Schema.Class<DeleteConnectorProfileResponse>("DeleteConnectorProfileResponse")({}) {}
export class DeleteFlowRequest extends Schema.Class<DeleteFlowRequest>("DeleteFlowRequest")({flowName: Schema.String, forceDelete: Schema.optional(Schema.Boolean)}) {}
export class DeleteFlowResponse extends Schema.Class<DeleteFlowResponse>("DeleteFlowResponse")({}) {}
export class DescribeConnectorRequest extends Schema.Class<DescribeConnectorRequest>("DescribeConnectorRequest")({connectorType: Schema.String, connectorLabel: Schema.optional(Schema.String)}) {}
export class DescribeConnectorEntityRequest extends Schema.Class<DescribeConnectorEntityRequest>("DescribeConnectorEntityRequest")({connectorEntityName: Schema.String, connectorType: Schema.optional(Schema.String), connectorProfileName: Schema.optional(Schema.String), apiVersion: Schema.optional(Schema.String)}) {}
export class DescribeConnectorProfilesRequest extends Schema.Class<DescribeConnectorProfilesRequest>("DescribeConnectorProfilesRequest")({connectorProfileNames: Schema.optional(ConnectorProfileNameList), connectorType: Schema.optional(Schema.String), connectorLabel: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class DescribeConnectorsRequest extends Schema.Class<DescribeConnectorsRequest>("DescribeConnectorsRequest")({connectorTypes: Schema.optional(ConnectorTypeList), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class DescribeFlowRequest extends Schema.Class<DescribeFlowRequest>("DescribeFlowRequest")({flowName: Schema.String}) {}
export class DescribeFlowExecutionRecordsRequest extends Schema.Class<DescribeFlowExecutionRecordsRequest>("DescribeFlowExecutionRecordsRequest")({flowName: Schema.String, maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListConnectorEntitiesRequest extends Schema.Class<ListConnectorEntitiesRequest>("ListConnectorEntitiesRequest")({connectorProfileName: Schema.optional(Schema.String), connectorType: Schema.optional(Schema.String), entitiesPath: Schema.optional(Schema.String), apiVersion: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListConnectorsRequest extends Schema.Class<ListConnectorsRequest>("ListConnectorsRequest")({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListFlowsRequest extends Schema.Class<ListFlowsRequest>("ListFlowsRequest")({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListTagsForResourceRequest extends Schema.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({resourceArn: Schema.String}) {}
export class ResetConnectorMetadataCacheRequest extends Schema.Class<ResetConnectorMetadataCacheRequest>("ResetConnectorMetadataCacheRequest")({connectorProfileName: Schema.optional(Schema.String), connectorType: Schema.optional(Schema.String), connectorEntityName: Schema.optional(Schema.String), entitiesPath: Schema.optional(Schema.String), apiVersion: Schema.optional(Schema.String)}) {}
export class ResetConnectorMetadataCacheResponse extends Schema.Class<ResetConnectorMetadataCacheResponse>("ResetConnectorMetadataCacheResponse")({}) {}
export class StartFlowRequest extends Schema.Class<StartFlowRequest>("StartFlowRequest")({flowName: Schema.String, clientToken: Schema.optional(Schema.String)}) {}
export class StopFlowRequest extends Schema.Class<StopFlowRequest>("StopFlowRequest")({flowName: Schema.String}) {}
export const TagMap = Schema.Record({key: Schema.String, value: Schema.String});
export class TagResourceRequest extends Schema.Class<TagResourceRequest>("TagResourceRequest")({resourceArn: Schema.String, tags: TagMap}) {}
export class TagResourceResponse extends Schema.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UnregisterConnectorRequest extends Schema.Class<UnregisterConnectorRequest>("UnregisterConnectorRequest")({connectorLabel: Schema.String, forceDelete: Schema.optional(Schema.Boolean)}) {}
export class UnregisterConnectorResponse extends Schema.Class<UnregisterConnectorResponse>("UnregisterConnectorResponse")({}) {}
export class UntagResourceRequest extends Schema.Class<UntagResourceRequest>("UntagResourceRequest")({resourceArn: Schema.String, tagKeys: TagKeyList}) {}
export class UntagResourceResponse extends Schema.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class AmplitudeConnectorProfileProperties extends Schema.Class<AmplitudeConnectorProfileProperties>("AmplitudeConnectorProfileProperties")({}) {}
export class DatadogConnectorProfileProperties extends Schema.Class<DatadogConnectorProfileProperties>("DatadogConnectorProfileProperties")({instanceUrl: Schema.String}) {}
export class DynatraceConnectorProfileProperties extends Schema.Class<DynatraceConnectorProfileProperties>("DynatraceConnectorProfileProperties")({instanceUrl: Schema.String}) {}
export class GoogleAnalyticsConnectorProfileProperties extends Schema.Class<GoogleAnalyticsConnectorProfileProperties>("GoogleAnalyticsConnectorProfileProperties")({}) {}
export class HoneycodeConnectorProfileProperties extends Schema.Class<HoneycodeConnectorProfileProperties>("HoneycodeConnectorProfileProperties")({}) {}
export class InforNexusConnectorProfileProperties extends Schema.Class<InforNexusConnectorProfileProperties>("InforNexusConnectorProfileProperties")({instanceUrl: Schema.String}) {}
export class MarketoConnectorProfileProperties extends Schema.Class<MarketoConnectorProfileProperties>("MarketoConnectorProfileProperties")({instanceUrl: Schema.String}) {}
export class RedshiftConnectorProfileProperties extends Schema.Class<RedshiftConnectorProfileProperties>("RedshiftConnectorProfileProperties")({databaseUrl: Schema.optional(Schema.String), bucketName: Schema.String, bucketPrefix: Schema.optional(Schema.String), roleArn: Schema.String, dataApiRoleArn: Schema.optional(Schema.String), isRedshiftServerless: Schema.optional(Schema.Boolean), clusterIdentifier: Schema.optional(Schema.String), workgroupName: Schema.optional(Schema.String), databaseName: Schema.optional(Schema.String)}) {}
export class SalesforceConnectorProfileProperties extends Schema.Class<SalesforceConnectorProfileProperties>("SalesforceConnectorProfileProperties")({instanceUrl: Schema.optional(Schema.String), isSandboxEnvironment: Schema.optional(Schema.Boolean), usePrivateLinkForMetadataAndAuthorization: Schema.optional(Schema.Boolean)}) {}
export class ServiceNowConnectorProfileProperties extends Schema.Class<ServiceNowConnectorProfileProperties>("ServiceNowConnectorProfileProperties")({instanceUrl: Schema.String}) {}
export class SingularConnectorProfileProperties extends Schema.Class<SingularConnectorProfileProperties>("SingularConnectorProfileProperties")({}) {}
export class SlackConnectorProfileProperties extends Schema.Class<SlackConnectorProfileProperties>("SlackConnectorProfileProperties")({instanceUrl: Schema.String}) {}
export class SnowflakeConnectorProfileProperties extends Schema.Class<SnowflakeConnectorProfileProperties>("SnowflakeConnectorProfileProperties")({warehouse: Schema.String, stage: Schema.String, bucketName: Schema.String, bucketPrefix: Schema.optional(Schema.String), privateLinkServiceName: Schema.optional(Schema.String), accountName: Schema.optional(Schema.String), region: Schema.optional(Schema.String)}) {}
export class TrendmicroConnectorProfileProperties extends Schema.Class<TrendmicroConnectorProfileProperties>("TrendmicroConnectorProfileProperties")({}) {}
export class VeevaConnectorProfileProperties extends Schema.Class<VeevaConnectorProfileProperties>("VeevaConnectorProfileProperties")({instanceUrl: Schema.String}) {}
export class ZendeskConnectorProfileProperties extends Schema.Class<ZendeskConnectorProfileProperties>("ZendeskConnectorProfileProperties")({instanceUrl: Schema.String}) {}
export const OAuthScopeList = Schema.Array(Schema.String);
export class OAuthProperties extends Schema.Class<OAuthProperties>("OAuthProperties")({tokenUrl: Schema.String, authCodeUrl: Schema.String, oAuthScopes: OAuthScopeList}) {}
export class SAPODataConnectorProfileProperties extends Schema.Class<SAPODataConnectorProfileProperties>("SAPODataConnectorProfileProperties")({applicationHostUrl: Schema.String, applicationServicePath: Schema.String, portNumber: Schema.Number, clientNumber: Schema.String, logonLanguage: Schema.optional(Schema.String), privateLinkServiceName: Schema.optional(Schema.String), oAuthProperties: Schema.optional(OAuthProperties), disableSSO: Schema.optional(Schema.Boolean)}) {}
export const ProfilePropertiesMap = Schema.Record({key: Schema.String, value: Schema.String});
export const TokenUrlCustomProperties = Schema.Record({key: Schema.String, value: Schema.String});
export class OAuth2Properties extends Schema.Class<OAuth2Properties>("OAuth2Properties")({tokenUrl: Schema.String, oAuth2GrantType: Schema.String, tokenUrlCustomProperties: Schema.optional(TokenUrlCustomProperties)}) {}
export class CustomConnectorProfileProperties extends Schema.Class<CustomConnectorProfileProperties>("CustomConnectorProfileProperties")({profileProperties: Schema.optional(ProfilePropertiesMap), oAuth2Properties: Schema.optional(OAuth2Properties)}) {}
export class PardotConnectorProfileProperties extends Schema.Class<PardotConnectorProfileProperties>("PardotConnectorProfileProperties")({instanceUrl: Schema.optional(Schema.String), isSandboxEnvironment: Schema.optional(Schema.Boolean), businessUnitId: Schema.optional(Schema.String)}) {}
export class ConnectorProfileProperties extends Schema.Class<ConnectorProfileProperties>("ConnectorProfileProperties")({Amplitude: Schema.optional(AmplitudeConnectorProfileProperties), Datadog: Schema.optional(DatadogConnectorProfileProperties), Dynatrace: Schema.optional(DynatraceConnectorProfileProperties), GoogleAnalytics: Schema.optional(GoogleAnalyticsConnectorProfileProperties), Honeycode: Schema.optional(HoneycodeConnectorProfileProperties), InforNexus: Schema.optional(InforNexusConnectorProfileProperties), Marketo: Schema.optional(MarketoConnectorProfileProperties), Redshift: Schema.optional(RedshiftConnectorProfileProperties), Salesforce: Schema.optional(SalesforceConnectorProfileProperties), ServiceNow: Schema.optional(ServiceNowConnectorProfileProperties), Singular: Schema.optional(SingularConnectorProfileProperties), Slack: Schema.optional(SlackConnectorProfileProperties), Snowflake: Schema.optional(SnowflakeConnectorProfileProperties), Trendmicro: Schema.optional(TrendmicroConnectorProfileProperties), Veeva: Schema.optional(VeevaConnectorProfileProperties), Zendesk: Schema.optional(ZendeskConnectorProfileProperties), SAPOData: Schema.optional(SAPODataConnectorProfileProperties), CustomConnector: Schema.optional(CustomConnectorProfileProperties), Pardot: Schema.optional(PardotConnectorProfileProperties)}) {}
export class AmplitudeConnectorProfileCredentials extends Schema.Class<AmplitudeConnectorProfileCredentials>("AmplitudeConnectorProfileCredentials")({apiKey: Schema.String, secretKey: Schema.String}) {}
export class DatadogConnectorProfileCredentials extends Schema.Class<DatadogConnectorProfileCredentials>("DatadogConnectorProfileCredentials")({apiKey: Schema.String, applicationKey: Schema.String}) {}
export class DynatraceConnectorProfileCredentials extends Schema.Class<DynatraceConnectorProfileCredentials>("DynatraceConnectorProfileCredentials")({apiToken: Schema.String}) {}
export class ConnectorOAuthRequest extends Schema.Class<ConnectorOAuthRequest>("ConnectorOAuthRequest")({authCode: Schema.optional(Schema.String), redirectUri: Schema.optional(Schema.String)}) {}
export class GoogleAnalyticsConnectorProfileCredentials extends Schema.Class<GoogleAnalyticsConnectorProfileCredentials>("GoogleAnalyticsConnectorProfileCredentials")({clientId: Schema.String, clientSecret: Schema.String, accessToken: Schema.optional(Schema.String), refreshToken: Schema.optional(Schema.String), oAuthRequest: Schema.optional(ConnectorOAuthRequest)}) {}
export class HoneycodeConnectorProfileCredentials extends Schema.Class<HoneycodeConnectorProfileCredentials>("HoneycodeConnectorProfileCredentials")({accessToken: Schema.optional(Schema.String), refreshToken: Schema.optional(Schema.String), oAuthRequest: Schema.optional(ConnectorOAuthRequest)}) {}
export class InforNexusConnectorProfileCredentials extends Schema.Class<InforNexusConnectorProfileCredentials>("InforNexusConnectorProfileCredentials")({accessKeyId: Schema.String, userId: Schema.String, secretAccessKey: Schema.String, datakey: Schema.String}) {}
export class MarketoConnectorProfileCredentials extends Schema.Class<MarketoConnectorProfileCredentials>("MarketoConnectorProfileCredentials")({clientId: Schema.String, clientSecret: Schema.String, accessToken: Schema.optional(Schema.String), oAuthRequest: Schema.optional(ConnectorOAuthRequest)}) {}
export class RedshiftConnectorProfileCredentials extends Schema.Class<RedshiftConnectorProfileCredentials>("RedshiftConnectorProfileCredentials")({username: Schema.optional(Schema.String), password: Schema.optional(Schema.String)}) {}
export class SalesforceConnectorProfileCredentials extends Schema.Class<SalesforceConnectorProfileCredentials>("SalesforceConnectorProfileCredentials")({accessToken: Schema.optional(Schema.String), refreshToken: Schema.optional(Schema.String), oAuthRequest: Schema.optional(ConnectorOAuthRequest), clientCredentialsArn: Schema.optional(Schema.String), oAuth2GrantType: Schema.optional(Schema.String), jwtToken: Schema.optional(Schema.String)}) {}
export class OAuth2Credentials extends Schema.Class<OAuth2Credentials>("OAuth2Credentials")({clientId: Schema.optional(Schema.String), clientSecret: Schema.optional(Schema.String), accessToken: Schema.optional(Schema.String), refreshToken: Schema.optional(Schema.String), oAuthRequest: Schema.optional(ConnectorOAuthRequest)}) {}
export class ServiceNowConnectorProfileCredentials extends Schema.Class<ServiceNowConnectorProfileCredentials>("ServiceNowConnectorProfileCredentials")({username: Schema.optional(Schema.String), password: Schema.optional(Schema.String), oAuth2Credentials: Schema.optional(OAuth2Credentials)}) {}
export class SingularConnectorProfileCredentials extends Schema.Class<SingularConnectorProfileCredentials>("SingularConnectorProfileCredentials")({apiKey: Schema.String}) {}
export class SlackConnectorProfileCredentials extends Schema.Class<SlackConnectorProfileCredentials>("SlackConnectorProfileCredentials")({clientId: Schema.String, clientSecret: Schema.String, accessToken: Schema.optional(Schema.String), oAuthRequest: Schema.optional(ConnectorOAuthRequest)}) {}
export class SnowflakeConnectorProfileCredentials extends Schema.Class<SnowflakeConnectorProfileCredentials>("SnowflakeConnectorProfileCredentials")({username: Schema.String, password: Schema.String}) {}
export class TrendmicroConnectorProfileCredentials extends Schema.Class<TrendmicroConnectorProfileCredentials>("TrendmicroConnectorProfileCredentials")({apiSecretKey: Schema.String}) {}
export class VeevaConnectorProfileCredentials extends Schema.Class<VeevaConnectorProfileCredentials>("VeevaConnectorProfileCredentials")({username: Schema.String, password: Schema.String}) {}
export class ZendeskConnectorProfileCredentials extends Schema.Class<ZendeskConnectorProfileCredentials>("ZendeskConnectorProfileCredentials")({clientId: Schema.String, clientSecret: Schema.String, accessToken: Schema.optional(Schema.String), oAuthRequest: Schema.optional(ConnectorOAuthRequest)}) {}
export class BasicAuthCredentials extends Schema.Class<BasicAuthCredentials>("BasicAuthCredentials")({username: Schema.String, password: Schema.String}) {}
export class OAuthCredentials extends Schema.Class<OAuthCredentials>("OAuthCredentials")({clientId: Schema.String, clientSecret: Schema.String, accessToken: Schema.optional(Schema.String), refreshToken: Schema.optional(Schema.String), oAuthRequest: Schema.optional(ConnectorOAuthRequest)}) {}
export class SAPODataConnectorProfileCredentials extends Schema.Class<SAPODataConnectorProfileCredentials>("SAPODataConnectorProfileCredentials")({basicAuthCredentials: Schema.optional(BasicAuthCredentials), oAuthCredentials: Schema.optional(OAuthCredentials)}) {}
export class ApiKeyCredentials extends Schema.Class<ApiKeyCredentials>("ApiKeyCredentials")({apiKey: Schema.String, apiSecretKey: Schema.optional(Schema.String)}) {}
export const CredentialsMap = Schema.Record({key: Schema.String, value: Schema.String});
export class CustomAuthCredentials extends Schema.Class<CustomAuthCredentials>("CustomAuthCredentials")({customAuthenticationType: Schema.String, credentialsMap: Schema.optional(CredentialsMap)}) {}
export class CustomConnectorProfileCredentials extends Schema.Class<CustomConnectorProfileCredentials>("CustomConnectorProfileCredentials")({authenticationType: Schema.String, basic: Schema.optional(BasicAuthCredentials), oauth2: Schema.optional(OAuth2Credentials), apiKey: Schema.optional(ApiKeyCredentials), custom: Schema.optional(CustomAuthCredentials)}) {}
export class PardotConnectorProfileCredentials extends Schema.Class<PardotConnectorProfileCredentials>("PardotConnectorProfileCredentials")({accessToken: Schema.optional(Schema.String), refreshToken: Schema.optional(Schema.String), oAuthRequest: Schema.optional(ConnectorOAuthRequest), clientCredentialsArn: Schema.optional(Schema.String)}) {}
export class ConnectorProfileCredentials extends Schema.Class<ConnectorProfileCredentials>("ConnectorProfileCredentials")({Amplitude: Schema.optional(AmplitudeConnectorProfileCredentials), Datadog: Schema.optional(DatadogConnectorProfileCredentials), Dynatrace: Schema.optional(DynatraceConnectorProfileCredentials), GoogleAnalytics: Schema.optional(GoogleAnalyticsConnectorProfileCredentials), Honeycode: Schema.optional(HoneycodeConnectorProfileCredentials), InforNexus: Schema.optional(InforNexusConnectorProfileCredentials), Marketo: Schema.optional(MarketoConnectorProfileCredentials), Redshift: Schema.optional(RedshiftConnectorProfileCredentials), Salesforce: Schema.optional(SalesforceConnectorProfileCredentials), ServiceNow: Schema.optional(ServiceNowConnectorProfileCredentials), Singular: Schema.optional(SingularConnectorProfileCredentials), Slack: Schema.optional(SlackConnectorProfileCredentials), Snowflake: Schema.optional(SnowflakeConnectorProfileCredentials), Trendmicro: Schema.optional(TrendmicroConnectorProfileCredentials), Veeva: Schema.optional(VeevaConnectorProfileCredentials), Zendesk: Schema.optional(ZendeskConnectorProfileCredentials), SAPOData: Schema.optional(SAPODataConnectorProfileCredentials), CustomConnector: Schema.optional(CustomConnectorProfileCredentials), Pardot: Schema.optional(PardotConnectorProfileCredentials)}) {}
export class ConnectorProfileConfig extends Schema.Class<ConnectorProfileConfig>("ConnectorProfileConfig")({connectorProfileProperties: ConnectorProfileProperties, connectorProfileCredentials: Schema.optional(ConnectorProfileCredentials)}) {}
export class UpdateConnectorProfileRequest extends Schema.Class<UpdateConnectorProfileRequest>("UpdateConnectorProfileRequest")({connectorProfileName: Schema.String, connectionMode: Schema.String, connectorProfileConfig: ConnectorProfileConfig, clientToken: Schema.optional(Schema.String)}) {}
export class LambdaConnectorProvisioningConfig extends Schema.Class<LambdaConnectorProvisioningConfig>("LambdaConnectorProvisioningConfig")({lambdaArn: Schema.String}) {}
export class ConnectorProvisioningConfig extends Schema.Class<ConnectorProvisioningConfig>("ConnectorProvisioningConfig")({lambda: Schema.optional(LambdaConnectorProvisioningConfig)}) {}
export class UpdateConnectorRegistrationRequest extends Schema.Class<UpdateConnectorRegistrationRequest>("UpdateConnectorRegistrationRequest")({connectorLabel: Schema.String, description: Schema.optional(Schema.String), connectorProvisioningConfig: Schema.optional(ConnectorProvisioningConfig), clientToken: Schema.optional(Schema.String)}) {}
export class ScheduledTriggerProperties extends Schema.Class<ScheduledTriggerProperties>("ScheduledTriggerProperties")({scheduleExpression: Schema.String, dataPullMode: Schema.optional(Schema.String), scheduleStartTime: Schema.optional(Schema.Date), scheduleEndTime: Schema.optional(Schema.Date), timezone: Schema.optional(Schema.String), scheduleOffset: Schema.optional(Schema.Number), firstExecutionFrom: Schema.optional(Schema.Date), flowErrorDeactivationThreshold: Schema.optional(Schema.Number)}) {}
export class TriggerProperties extends Schema.Class<TriggerProperties>("TriggerProperties")({Scheduled: Schema.optional(ScheduledTriggerProperties)}) {}
export class TriggerConfig extends Schema.Class<TriggerConfig>("TriggerConfig")({triggerType: Schema.String, triggerProperties: Schema.optional(TriggerProperties)}) {}
export class AmplitudeSourceProperties extends Schema.Class<AmplitudeSourceProperties>("AmplitudeSourceProperties")({object: Schema.String}) {}
export class DatadogSourceProperties extends Schema.Class<DatadogSourceProperties>("DatadogSourceProperties")({object: Schema.String}) {}
export class DynatraceSourceProperties extends Schema.Class<DynatraceSourceProperties>("DynatraceSourceProperties")({object: Schema.String}) {}
export class GoogleAnalyticsSourceProperties extends Schema.Class<GoogleAnalyticsSourceProperties>("GoogleAnalyticsSourceProperties")({object: Schema.String}) {}
export class InforNexusSourceProperties extends Schema.Class<InforNexusSourceProperties>("InforNexusSourceProperties")({object: Schema.String}) {}
export class MarketoSourceProperties extends Schema.Class<MarketoSourceProperties>("MarketoSourceProperties")({object: Schema.String}) {}
export class S3InputFormatConfig extends Schema.Class<S3InputFormatConfig>("S3InputFormatConfig")({s3InputFileType: Schema.optional(Schema.String)}) {}
export class S3SourceProperties extends Schema.Class<S3SourceProperties>("S3SourceProperties")({bucketName: Schema.String, bucketPrefix: Schema.optional(Schema.String), s3InputFormatConfig: Schema.optional(S3InputFormatConfig)}) {}
export class SalesforceSourceProperties extends Schema.Class<SalesforceSourceProperties>("SalesforceSourceProperties")({object: Schema.String, enableDynamicFieldUpdate: Schema.optional(Schema.Boolean), includeDeletedRecords: Schema.optional(Schema.Boolean), dataTransferApi: Schema.optional(Schema.String)}) {}
export class ServiceNowSourceProperties extends Schema.Class<ServiceNowSourceProperties>("ServiceNowSourceProperties")({object: Schema.String}) {}
export class SingularSourceProperties extends Schema.Class<SingularSourceProperties>("SingularSourceProperties")({object: Schema.String}) {}
export class SlackSourceProperties extends Schema.Class<SlackSourceProperties>("SlackSourceProperties")({object: Schema.String}) {}
export class TrendmicroSourceProperties extends Schema.Class<TrendmicroSourceProperties>("TrendmicroSourceProperties")({object: Schema.String}) {}
export class VeevaSourceProperties extends Schema.Class<VeevaSourceProperties>("VeevaSourceProperties")({object: Schema.String, documentType: Schema.optional(Schema.String), includeSourceFiles: Schema.optional(Schema.Boolean), includeRenditions: Schema.optional(Schema.Boolean), includeAllVersions: Schema.optional(Schema.Boolean)}) {}
export class ZendeskSourceProperties extends Schema.Class<ZendeskSourceProperties>("ZendeskSourceProperties")({object: Schema.String}) {}
export class SAPODataParallelismConfig extends Schema.Class<SAPODataParallelismConfig>("SAPODataParallelismConfig")({maxParallelism: Schema.Number}) {}
export class SAPODataPaginationConfig extends Schema.Class<SAPODataPaginationConfig>("SAPODataPaginationConfig")({maxPageSize: Schema.Number}) {}
export class SAPODataSourceProperties extends Schema.Class<SAPODataSourceProperties>("SAPODataSourceProperties")({objectPath: Schema.optional(Schema.String), parallelismConfig: Schema.optional(SAPODataParallelismConfig), paginationConfig: Schema.optional(SAPODataPaginationConfig)}) {}
export const CustomProperties = Schema.Record({key: Schema.String, value: Schema.String});
export class DataTransferApi extends Schema.Class<DataTransferApi>("DataTransferApi")({Name: Schema.optional(Schema.String), Type: Schema.optional(Schema.String)}) {}
export class CustomConnectorSourceProperties extends Schema.Class<CustomConnectorSourceProperties>("CustomConnectorSourceProperties")({entityName: Schema.String, customProperties: Schema.optional(CustomProperties), dataTransferApi: Schema.optional(DataTransferApi)}) {}
export class PardotSourceProperties extends Schema.Class<PardotSourceProperties>("PardotSourceProperties")({object: Schema.String}) {}
export class SourceConnectorProperties extends Schema.Class<SourceConnectorProperties>("SourceConnectorProperties")({Amplitude: Schema.optional(AmplitudeSourceProperties), Datadog: Schema.optional(DatadogSourceProperties), Dynatrace: Schema.optional(DynatraceSourceProperties), GoogleAnalytics: Schema.optional(GoogleAnalyticsSourceProperties), InforNexus: Schema.optional(InforNexusSourceProperties), Marketo: Schema.optional(MarketoSourceProperties), S3: Schema.optional(S3SourceProperties), Salesforce: Schema.optional(SalesforceSourceProperties), ServiceNow: Schema.optional(ServiceNowSourceProperties), Singular: Schema.optional(SingularSourceProperties), Slack: Schema.optional(SlackSourceProperties), Trendmicro: Schema.optional(TrendmicroSourceProperties), Veeva: Schema.optional(VeevaSourceProperties), Zendesk: Schema.optional(ZendeskSourceProperties), SAPOData: Schema.optional(SAPODataSourceProperties), CustomConnector: Schema.optional(CustomConnectorSourceProperties), Pardot: Schema.optional(PardotSourceProperties)}) {}
export class IncrementalPullConfig extends Schema.Class<IncrementalPullConfig>("IncrementalPullConfig")({datetimeTypeFieldName: Schema.optional(Schema.String)}) {}
export class SourceFlowConfig extends Schema.Class<SourceFlowConfig>("SourceFlowConfig")({connectorType: Schema.String, apiVersion: Schema.optional(Schema.String), connectorProfileName: Schema.optional(Schema.String), sourceConnectorProperties: SourceConnectorProperties, incrementalPullConfig: Schema.optional(IncrementalPullConfig)}) {}
export class ErrorHandlingConfig extends Schema.Class<ErrorHandlingConfig>("ErrorHandlingConfig")({failOnFirstDestinationError: Schema.optional(Schema.Boolean), bucketPrefix: Schema.optional(Schema.String), bucketName: Schema.optional(Schema.String)}) {}
export class RedshiftDestinationProperties extends Schema.Class<RedshiftDestinationProperties>("RedshiftDestinationProperties")({object: Schema.String, intermediateBucketName: Schema.String, bucketPrefix: Schema.optional(Schema.String), errorHandlingConfig: Schema.optional(ErrorHandlingConfig)}) {}
export const PathPrefixHierarchy = Schema.Array(Schema.String);
export class PrefixConfig extends Schema.Class<PrefixConfig>("PrefixConfig")({prefixType: Schema.optional(Schema.String), prefixFormat: Schema.optional(Schema.String), pathPrefixHierarchy: Schema.optional(PathPrefixHierarchy)}) {}
export class AggregationConfig extends Schema.Class<AggregationConfig>("AggregationConfig")({aggregationType: Schema.optional(Schema.String), targetFileSize: Schema.optional(Schema.Number)}) {}
export class S3OutputFormatConfig extends Schema.Class<S3OutputFormatConfig>("S3OutputFormatConfig")({fileType: Schema.optional(Schema.String), prefixConfig: Schema.optional(PrefixConfig), aggregationConfig: Schema.optional(AggregationConfig), preserveSourceDataTyping: Schema.optional(Schema.Boolean)}) {}
export class S3DestinationProperties extends Schema.Class<S3DestinationProperties>("S3DestinationProperties")({bucketName: Schema.String, bucketPrefix: Schema.optional(Schema.String), s3OutputFormatConfig: Schema.optional(S3OutputFormatConfig)}) {}
export const IdFieldNameList = Schema.Array(Schema.String);
export class SalesforceDestinationProperties extends Schema.Class<SalesforceDestinationProperties>("SalesforceDestinationProperties")({object: Schema.String, idFieldNames: Schema.optional(IdFieldNameList), errorHandlingConfig: Schema.optional(ErrorHandlingConfig), writeOperationType: Schema.optional(Schema.String), dataTransferApi: Schema.optional(Schema.String)}) {}
export class SnowflakeDestinationProperties extends Schema.Class<SnowflakeDestinationProperties>("SnowflakeDestinationProperties")({object: Schema.String, intermediateBucketName: Schema.String, bucketPrefix: Schema.optional(Schema.String), errorHandlingConfig: Schema.optional(ErrorHandlingConfig)}) {}
export class EventBridgeDestinationProperties extends Schema.Class<EventBridgeDestinationProperties>("EventBridgeDestinationProperties")({object: Schema.String, errorHandlingConfig: Schema.optional(ErrorHandlingConfig)}) {}
export class LookoutMetricsDestinationProperties extends Schema.Class<LookoutMetricsDestinationProperties>("LookoutMetricsDestinationProperties")({}) {}
export class UpsolverS3OutputFormatConfig extends Schema.Class<UpsolverS3OutputFormatConfig>("UpsolverS3OutputFormatConfig")({fileType: Schema.optional(Schema.String), prefixConfig: PrefixConfig, aggregationConfig: Schema.optional(AggregationConfig)}) {}
export class UpsolverDestinationProperties extends Schema.Class<UpsolverDestinationProperties>("UpsolverDestinationProperties")({bucketName: Schema.String, bucketPrefix: Schema.optional(Schema.String), s3OutputFormatConfig: UpsolverS3OutputFormatConfig}) {}
export class HoneycodeDestinationProperties extends Schema.Class<HoneycodeDestinationProperties>("HoneycodeDestinationProperties")({object: Schema.String, errorHandlingConfig: Schema.optional(ErrorHandlingConfig)}) {}
export class CustomerProfilesDestinationProperties extends Schema.Class<CustomerProfilesDestinationProperties>("CustomerProfilesDestinationProperties")({domainName: Schema.String, objectTypeName: Schema.optional(Schema.String)}) {}
export class ZendeskDestinationProperties extends Schema.Class<ZendeskDestinationProperties>("ZendeskDestinationProperties")({object: Schema.String, idFieldNames: Schema.optional(IdFieldNameList), errorHandlingConfig: Schema.optional(ErrorHandlingConfig), writeOperationType: Schema.optional(Schema.String)}) {}
export class MarketoDestinationProperties extends Schema.Class<MarketoDestinationProperties>("MarketoDestinationProperties")({object: Schema.String, errorHandlingConfig: Schema.optional(ErrorHandlingConfig)}) {}
export class CustomConnectorDestinationProperties extends Schema.Class<CustomConnectorDestinationProperties>("CustomConnectorDestinationProperties")({entityName: Schema.String, errorHandlingConfig: Schema.optional(ErrorHandlingConfig), writeOperationType: Schema.optional(Schema.String), idFieldNames: Schema.optional(IdFieldNameList), customProperties: Schema.optional(CustomProperties)}) {}
export class SuccessResponseHandlingConfig extends Schema.Class<SuccessResponseHandlingConfig>("SuccessResponseHandlingConfig")({bucketPrefix: Schema.optional(Schema.String), bucketName: Schema.optional(Schema.String)}) {}
export class SAPODataDestinationProperties extends Schema.Class<SAPODataDestinationProperties>("SAPODataDestinationProperties")({objectPath: Schema.String, successResponseHandlingConfig: Schema.optional(SuccessResponseHandlingConfig), idFieldNames: Schema.optional(IdFieldNameList), errorHandlingConfig: Schema.optional(ErrorHandlingConfig), writeOperationType: Schema.optional(Schema.String)}) {}
export class DestinationConnectorProperties extends Schema.Class<DestinationConnectorProperties>("DestinationConnectorProperties")({Redshift: Schema.optional(RedshiftDestinationProperties), S3: Schema.optional(S3DestinationProperties), Salesforce: Schema.optional(SalesforceDestinationProperties), Snowflake: Schema.optional(SnowflakeDestinationProperties), EventBridge: Schema.optional(EventBridgeDestinationProperties), LookoutMetrics: Schema.optional(LookoutMetricsDestinationProperties), Upsolver: Schema.optional(UpsolverDestinationProperties), Honeycode: Schema.optional(HoneycodeDestinationProperties), CustomerProfiles: Schema.optional(CustomerProfilesDestinationProperties), Zendesk: Schema.optional(ZendeskDestinationProperties), Marketo: Schema.optional(MarketoDestinationProperties), CustomConnector: Schema.optional(CustomConnectorDestinationProperties), SAPOData: Schema.optional(SAPODataDestinationProperties)}) {}
export class DestinationFlowConfig extends Schema.Class<DestinationFlowConfig>("DestinationFlowConfig")({connectorType: Schema.String, apiVersion: Schema.optional(Schema.String), connectorProfileName: Schema.optional(Schema.String), destinationConnectorProperties: DestinationConnectorProperties}) {}
export const DestinationFlowConfigList = Schema.Array(DestinationFlowConfig);
export const SourceFields = Schema.Array(Schema.String);
export class ConnectorOperator extends Schema.Class<ConnectorOperator>("ConnectorOperator")({Amplitude: Schema.optional(Schema.String), Datadog: Schema.optional(Schema.String), Dynatrace: Schema.optional(Schema.String), GoogleAnalytics: Schema.optional(Schema.String), InforNexus: Schema.optional(Schema.String), Marketo: Schema.optional(Schema.String), S3: Schema.optional(Schema.String), Salesforce: Schema.optional(Schema.String), ServiceNow: Schema.optional(Schema.String), Singular: Schema.optional(Schema.String), Slack: Schema.optional(Schema.String), Trendmicro: Schema.optional(Schema.String), Veeva: Schema.optional(Schema.String), Zendesk: Schema.optional(Schema.String), SAPOData: Schema.optional(Schema.String), CustomConnector: Schema.optional(Schema.String), Pardot: Schema.optional(Schema.String)}) {}
export const TaskPropertiesMap = Schema.Record({key: Schema.String, value: Schema.String});
export class Task extends Schema.Class<Task>("Task")({sourceFields: SourceFields, connectorOperator: Schema.optional(ConnectorOperator), destinationField: Schema.optional(Schema.String), taskType: Schema.String, taskProperties: Schema.optional(TaskPropertiesMap)}) {}
export const Tasks = Schema.Array(Task);
export class GlueDataCatalogConfig extends Schema.Class<GlueDataCatalogConfig>("GlueDataCatalogConfig")({roleArn: Schema.String, databaseName: Schema.String, tablePrefix: Schema.String}) {}
export class MetadataCatalogConfig extends Schema.Class<MetadataCatalogConfig>("MetadataCatalogConfig")({glueDataCatalog: Schema.optional(GlueDataCatalogConfig)}) {}
export class UpdateFlowRequest extends Schema.Class<UpdateFlowRequest>("UpdateFlowRequest")({flowName: Schema.String, description: Schema.optional(Schema.String), triggerConfig: TriggerConfig, sourceFlowConfig: SourceFlowConfig, destinationFlowConfigList: DestinationFlowConfigList, tasks: Tasks, metadataCatalogConfig: Schema.optional(MetadataCatalogConfig), clientToken: Schema.optional(Schema.String)}) {}
export class CancelFlowExecutionsResponse extends Schema.Class<CancelFlowExecutionsResponse>("CancelFlowExecutionsResponse")({invalidExecutions: Schema.optional(ExecutionIds)}) {}
export class ConflictException extends Schema.Class<ConflictException>("ConflictException")({message: Schema.optional(Schema.String)}) {}
export class InternalServerException extends Schema.Class<InternalServerException>("InternalServerException")({message: Schema.optional(Schema.String)}) {}
export const ConnectorModeList = Schema.Array(Schema.String);
export const SupportedDataTransferTypeList = Schema.Array(Schema.String);
export class ConnectorDetail extends Schema.Class<ConnectorDetail>("ConnectorDetail")({connectorDescription: Schema.optional(Schema.String), connectorName: Schema.optional(Schema.String), connectorOwner: Schema.optional(Schema.String), connectorVersion: Schema.optional(Schema.String), applicationType: Schema.optional(Schema.String), connectorType: Schema.optional(Schema.String), connectorLabel: Schema.optional(Schema.String), registeredAt: Schema.optional(Schema.Date), registeredBy: Schema.optional(Schema.String), connectorProvisioningType: Schema.optional(Schema.String), connectorModes: Schema.optional(ConnectorModeList), supportedDataTransferTypes: Schema.optional(SupportedDataTransferTypeList)}) {}
export const ConnectorList = Schema.Array(ConnectorDetail);
export class ListConnectorsResponse extends Schema.Class<ListConnectorsResponse>("ListConnectorsResponse")({connectors: Schema.optional(ConnectorList), nextToken: Schema.optional(Schema.String)}) {}
export class ListTagsForResourceResponse extends Schema.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({tags: Schema.optional(TagMap)}) {}
export class ResourceNotFoundException extends Schema.Class<ResourceNotFoundException>("ResourceNotFoundException")({message: Schema.optional(Schema.String)}) {}
export class StartFlowResponse extends Schema.Class<StartFlowResponse>("StartFlowResponse")({flowArn: Schema.optional(Schema.String), flowStatus: Schema.optional(Schema.String), executionId: Schema.optional(Schema.String)}) {}
export class StopFlowResponse extends Schema.Class<StopFlowResponse>("StopFlowResponse")({flowArn: Schema.optional(Schema.String), flowStatus: Schema.optional(Schema.String)}) {}
export class ValidationException extends Schema.Class<ValidationException>("ValidationException")({message: Schema.optional(Schema.String)}) {}
export class UpdateConnectorProfileResponse extends Schema.Class<UpdateConnectorProfileResponse>("UpdateConnectorProfileResponse")({connectorProfileArn: Schema.optional(Schema.String)}) {}
export class UpdateConnectorRegistrationResponse extends Schema.Class<UpdateConnectorRegistrationResponse>("UpdateConnectorRegistrationResponse")({connectorArn: Schema.optional(Schema.String)}) {}
export class UpdateFlowResponse extends Schema.Class<UpdateFlowResponse>("UpdateFlowResponse")({flowStatus: Schema.optional(Schema.String)}) {}
export const SchedulingFrequencyTypeList = Schema.Array(Schema.String);
export const TriggerTypeList = Schema.Array(Schema.String);
export const SupportedApiVersionList = Schema.Array(Schema.String);
export const SupportedOperatorList = Schema.Array(Schema.String);
export const SupportedWriteOperationList = Schema.Array(Schema.String);
export class AmplitudeMetadata extends Schema.Class<AmplitudeMetadata>("AmplitudeMetadata")({}) {}
export class DatadogMetadata extends Schema.Class<DatadogMetadata>("DatadogMetadata")({}) {}
export class DynatraceMetadata extends Schema.Class<DynatraceMetadata>("DynatraceMetadata")({}) {}
export class GoogleAnalyticsMetadata extends Schema.Class<GoogleAnalyticsMetadata>("GoogleAnalyticsMetadata")({oAuthScopes: Schema.optional(OAuthScopeList)}) {}
export class InforNexusMetadata extends Schema.Class<InforNexusMetadata>("InforNexusMetadata")({}) {}
export class MarketoMetadata extends Schema.Class<MarketoMetadata>("MarketoMetadata")({}) {}
export class RedshiftMetadata extends Schema.Class<RedshiftMetadata>("RedshiftMetadata")({}) {}
export class S3Metadata extends Schema.Class<S3Metadata>("S3Metadata")({}) {}
export const SalesforceDataTransferApiList = Schema.Array(Schema.String);
export const OAuth2GrantTypeSupportedList = Schema.Array(Schema.String);
export class SalesforceMetadata extends Schema.Class<SalesforceMetadata>("SalesforceMetadata")({oAuthScopes: Schema.optional(OAuthScopeList), dataTransferApis: Schema.optional(SalesforceDataTransferApiList), oauth2GrantTypesSupported: Schema.optional(OAuth2GrantTypeSupportedList)}) {}
export class ServiceNowMetadata extends Schema.Class<ServiceNowMetadata>("ServiceNowMetadata")({}) {}
export class SingularMetadata extends Schema.Class<SingularMetadata>("SingularMetadata")({}) {}
export class SlackMetadata extends Schema.Class<SlackMetadata>("SlackMetadata")({oAuthScopes: Schema.optional(OAuthScopeList)}) {}
export const RegionList = Schema.Array(Schema.String);
export class SnowflakeMetadata extends Schema.Class<SnowflakeMetadata>("SnowflakeMetadata")({supportedRegions: Schema.optional(RegionList)}) {}
export class TrendmicroMetadata extends Schema.Class<TrendmicroMetadata>("TrendmicroMetadata")({}) {}
export class VeevaMetadata extends Schema.Class<VeevaMetadata>("VeevaMetadata")({}) {}
export class ZendeskMetadata extends Schema.Class<ZendeskMetadata>("ZendeskMetadata")({oAuthScopes: Schema.optional(OAuthScopeList)}) {}
export class EventBridgeMetadata extends Schema.Class<EventBridgeMetadata>("EventBridgeMetadata")({}) {}
export class UpsolverMetadata extends Schema.Class<UpsolverMetadata>("UpsolverMetadata")({}) {}
export class CustomerProfilesMetadata extends Schema.Class<CustomerProfilesMetadata>("CustomerProfilesMetadata")({}) {}
export class HoneycodeMetadata extends Schema.Class<HoneycodeMetadata>("HoneycodeMetadata")({oAuthScopes: Schema.optional(OAuthScopeList)}) {}
export class SAPODataMetadata extends Schema.Class<SAPODataMetadata>("SAPODataMetadata")({}) {}
export class PardotMetadata extends Schema.Class<PardotMetadata>("PardotMetadata")({}) {}
export class ConnectorMetadata extends Schema.Class<ConnectorMetadata>("ConnectorMetadata")({Amplitude: Schema.optional(AmplitudeMetadata), Datadog: Schema.optional(DatadogMetadata), Dynatrace: Schema.optional(DynatraceMetadata), GoogleAnalytics: Schema.optional(GoogleAnalyticsMetadata), InforNexus: Schema.optional(InforNexusMetadata), Marketo: Schema.optional(MarketoMetadata), Redshift: Schema.optional(RedshiftMetadata), S3: Schema.optional(S3Metadata), Salesforce: Schema.optional(SalesforceMetadata), ServiceNow: Schema.optional(ServiceNowMetadata), Singular: Schema.optional(SingularMetadata), Slack: Schema.optional(SlackMetadata), Snowflake: Schema.optional(SnowflakeMetadata), Trendmicro: Schema.optional(TrendmicroMetadata), Veeva: Schema.optional(VeevaMetadata), Zendesk: Schema.optional(ZendeskMetadata), EventBridge: Schema.optional(EventBridgeMetadata), Upsolver: Schema.optional(UpsolverMetadata), CustomerProfiles: Schema.optional(CustomerProfilesMetadata), Honeycode: Schema.optional(HoneycodeMetadata), SAPOData: Schema.optional(SAPODataMetadata), Pardot: Schema.optional(PardotMetadata)}) {}
export const TokenUrlList = Schema.Array(Schema.String);
export const AuthCodeUrlList = Schema.Array(Schema.String);
export const ConnectorSuppliedValueList = Schema.Array(Schema.String);
export class OAuth2CustomParameter extends Schema.Class<OAuth2CustomParameter>("OAuth2CustomParameter")({key: Schema.optional(Schema.String), isRequired: Schema.optional(Schema.Boolean), label: Schema.optional(Schema.String), description: Schema.optional(Schema.String), isSensitiveField: Schema.optional(Schema.Boolean), connectorSuppliedValues: Schema.optional(ConnectorSuppliedValueList), type: Schema.optional(Schema.String)}) {}
export const OAuth2CustomPropertiesList = Schema.Array(OAuth2CustomParameter);
export class OAuth2Defaults extends Schema.Class<OAuth2Defaults>("OAuth2Defaults")({oauthScopes: Schema.optional(OAuthScopeList), tokenUrls: Schema.optional(TokenUrlList), authCodeUrls: Schema.optional(AuthCodeUrlList), oauth2GrantTypesSupported: Schema.optional(OAuth2GrantTypeSupportedList), oauth2CustomProperties: Schema.optional(OAuth2CustomPropertiesList)}) {}
export class AuthParameter extends Schema.Class<AuthParameter>("AuthParameter")({key: Schema.optional(Schema.String), isRequired: Schema.optional(Schema.Boolean), label: Schema.optional(Schema.String), description: Schema.optional(Schema.String), isSensitiveField: Schema.optional(Schema.Boolean), connectorSuppliedValues: Schema.optional(ConnectorSuppliedValueList)}) {}
export const AuthParameterList = Schema.Array(AuthParameter);
export class CustomAuthConfig extends Schema.Class<CustomAuthConfig>("CustomAuthConfig")({customAuthenticationType: Schema.optional(Schema.String), authParameters: Schema.optional(AuthParameterList)}) {}
export const CustomAuthConfigList = Schema.Array(CustomAuthConfig);
export class AuthenticationConfig extends Schema.Class<AuthenticationConfig>("AuthenticationConfig")({isBasicAuthSupported: Schema.optional(Schema.Boolean), isApiKeyAuthSupported: Schema.optional(Schema.Boolean), isOAuth2Supported: Schema.optional(Schema.Boolean), isCustomAuthSupported: Schema.optional(Schema.Boolean), oAuth2Defaults: Schema.optional(OAuth2Defaults), customAuthConfigs: Schema.optional(CustomAuthConfigList)}) {}
export const ConnectorSuppliedValueOptionList = Schema.Array(Schema.String);
export class ConnectorRuntimeSetting extends Schema.Class<ConnectorRuntimeSetting>("ConnectorRuntimeSetting")({key: Schema.optional(Schema.String), dataType: Schema.optional(Schema.String), isRequired: Schema.optional(Schema.Boolean), label: Schema.optional(Schema.String), description: Schema.optional(Schema.String), scope: Schema.optional(Schema.String), connectorSuppliedValueOptions: Schema.optional(ConnectorSuppliedValueOptionList)}) {}
export const ConnectorRuntimeSettingList = Schema.Array(ConnectorRuntimeSetting);
export const SupportedDataTransferApis = Schema.Array(DataTransferApi);
export class ConnectorConfiguration extends Schema.Class<ConnectorConfiguration>("ConnectorConfiguration")({canUseAsSource: Schema.optional(Schema.Boolean), canUseAsDestination: Schema.optional(Schema.Boolean), supportedDestinationConnectors: Schema.optional(ConnectorTypeList), supportedSchedulingFrequencies: Schema.optional(SchedulingFrequencyTypeList), isPrivateLinkEnabled: Schema.optional(Schema.Boolean), isPrivateLinkEndpointUrlRequired: Schema.optional(Schema.Boolean), supportedTriggerTypes: Schema.optional(TriggerTypeList), connectorMetadata: Schema.optional(ConnectorMetadata), connectorType: Schema.optional(Schema.String), connectorLabel: Schema.optional(Schema.String), connectorDescription: Schema.optional(Schema.String), connectorOwner: Schema.optional(Schema.String), connectorName: Schema.optional(Schema.String), connectorVersion: Schema.optional(Schema.String), connectorArn: Schema.optional(Schema.String), connectorModes: Schema.optional(ConnectorModeList), authenticationConfig: Schema.optional(AuthenticationConfig), connectorRuntimeSettings: Schema.optional(ConnectorRuntimeSettingList), supportedApiVersions: Schema.optional(SupportedApiVersionList), supportedOperators: Schema.optional(SupportedOperatorList), supportedWriteOperations: Schema.optional(SupportedWriteOperationList), connectorProvisioningType: Schema.optional(Schema.String), connectorProvisioningConfig: Schema.optional(ConnectorProvisioningConfig), logoURL: Schema.optional(Schema.String), registeredAt: Schema.optional(Schema.Date), registeredBy: Schema.optional(Schema.String), supportedDataTransferTypes: Schema.optional(SupportedDataTransferTypeList), supportedDataTransferApis: Schema.optional(SupportedDataTransferApis)}) {}
export const ConnectorConfigurationsMap = Schema.Record({key: Schema.String, value: ConnectorConfiguration});
export class ExecutionDetails extends Schema.Class<ExecutionDetails>("ExecutionDetails")({mostRecentExecutionMessage: Schema.optional(Schema.String), mostRecentExecutionTime: Schema.optional(Schema.Date), mostRecentExecutionStatus: Schema.optional(Schema.String)}) {}
export class FlowDefinition extends Schema.Class<FlowDefinition>("FlowDefinition")({flowArn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), flowName: Schema.optional(Schema.String), flowStatus: Schema.optional(Schema.String), sourceConnectorType: Schema.optional(Schema.String), sourceConnectorLabel: Schema.optional(Schema.String), destinationConnectorType: Schema.optional(Schema.String), destinationConnectorLabel: Schema.optional(Schema.String), triggerType: Schema.optional(Schema.String), createdAt: Schema.optional(Schema.Date), lastUpdatedAt: Schema.optional(Schema.Date), createdBy: Schema.optional(Schema.String), lastUpdatedBy: Schema.optional(Schema.String), tags: Schema.optional(TagMap), lastRunExecutionDetails: Schema.optional(ExecutionDetails)}) {}
export const FlowList = Schema.Array(FlowDefinition);
export class AccessDeniedException extends Schema.Class<AccessDeniedException>("AccessDeniedException")({message: Schema.optional(Schema.String)}) {}
export class DescribeConnectorsResponse extends Schema.Class<DescribeConnectorsResponse>("DescribeConnectorsResponse")({connectorConfigurations: Schema.optional(ConnectorConfigurationsMap), connectors: Schema.optional(ConnectorList), nextToken: Schema.optional(Schema.String)}) {}
export class ListFlowsResponse extends Schema.Class<ListFlowsResponse>("ListFlowsResponse")({flows: Schema.optional(FlowList), nextToken: Schema.optional(Schema.String)}) {}
export class RegisterConnectorRequest extends Schema.Class<RegisterConnectorRequest>("RegisterConnectorRequest")({connectorLabel: Schema.optional(Schema.String), description: Schema.optional(Schema.String), connectorProvisioningType: Schema.optional(Schema.String), connectorProvisioningConfig: Schema.optional(ConnectorProvisioningConfig), clientToken: Schema.optional(Schema.String)}) {}
export class ServiceQuotaExceededException extends Schema.Class<ServiceQuotaExceededException>("ServiceQuotaExceededException")({message: Schema.optional(Schema.String)}) {}
export class UnsupportedOperationException extends Schema.Class<UnsupportedOperationException>("UnsupportedOperationException")({message: Schema.optional(Schema.String)}) {}
export class ConnectorAuthenticationException extends Schema.Class<ConnectorAuthenticationException>("ConnectorAuthenticationException")({message: Schema.optional(Schema.String)}) {}
export class ConnectorServerException extends Schema.Class<ConnectorServerException>("ConnectorServerException")({message: Schema.optional(Schema.String)}) {}
export class SourceFieldProperties extends Schema.Class<SourceFieldProperties>("SourceFieldProperties")({isRetrievable: Schema.optional(Schema.Boolean), isQueryable: Schema.optional(Schema.Boolean), isTimestampFieldForIncrementalQueries: Schema.optional(Schema.Boolean)}) {}
export class DestinationFieldProperties extends Schema.Class<DestinationFieldProperties>("DestinationFieldProperties")({isCreatable: Schema.optional(Schema.Boolean), isNullable: Schema.optional(Schema.Boolean), isUpsertable: Schema.optional(Schema.Boolean), isUpdatable: Schema.optional(Schema.Boolean), isDefaultedOnCreate: Schema.optional(Schema.Boolean), supportedWriteOperations: Schema.optional(SupportedWriteOperationList)}) {}
export class PrivateConnectionProvisioningState extends Schema.Class<PrivateConnectionProvisioningState>("PrivateConnectionProvisioningState")({status: Schema.optional(Schema.String), failureMessage: Schema.optional(Schema.String), failureCause: Schema.optional(Schema.String)}) {}
export class RegistrationOutput extends Schema.Class<RegistrationOutput>("RegistrationOutput")({message: Schema.optional(Schema.String), result: Schema.optional(Schema.String), status: Schema.optional(Schema.String)}) {}
export class ConnectorEntity extends Schema.Class<ConnectorEntity>("ConnectorEntity")({name: Schema.String, label: Schema.optional(Schema.String), hasNestedEntities: Schema.optional(Schema.Boolean)}) {}
export const ConnectorEntityList = Schema.Array(ConnectorEntity);
export const FilterOperatorList = Schema.Array(Schema.String);
export const SupportedValueList = Schema.Array(Schema.String);
export class ConnectorProfile extends Schema.Class<ConnectorProfile>("ConnectorProfile")({connectorProfileArn: Schema.optional(Schema.String), connectorProfileName: Schema.optional(Schema.String), connectorType: Schema.optional(Schema.String), connectorLabel: Schema.optional(Schema.String), connectionMode: Schema.optional(Schema.String), credentialsArn: Schema.optional(Schema.String), connectorProfileProperties: Schema.optional(ConnectorProfileProperties), createdAt: Schema.optional(Schema.Date), lastUpdatedAt: Schema.optional(Schema.Date), privateConnectionProvisioningState: Schema.optional(PrivateConnectionProvisioningState)}) {}
export const ConnectorProfileDetailList = Schema.Array(ConnectorProfile);
export class MetadataCatalogDetail extends Schema.Class<MetadataCatalogDetail>("MetadataCatalogDetail")({catalogType: Schema.optional(Schema.String), tableName: Schema.optional(Schema.String), tableRegistrationOutput: Schema.optional(RegistrationOutput), partitionRegistrationOutput: Schema.optional(RegistrationOutput)}) {}
export const MetadataCatalogDetails = Schema.Array(MetadataCatalogDetail);
export const ConnectorEntityMap = Schema.Record({key: Schema.String, value: ConnectorEntityList});
export class ErrorInfo extends Schema.Class<ErrorInfo>("ErrorInfo")({putFailuresCount: Schema.optional(Schema.Number), executionMessage: Schema.optional(Schema.String)}) {}
export class ThrottlingException extends Schema.Class<ThrottlingException>("ThrottlingException")({message: Schema.optional(Schema.String)}) {}
export class DescribeConnectorProfilesResponse extends Schema.Class<DescribeConnectorProfilesResponse>("DescribeConnectorProfilesResponse")({connectorProfileDetails: Schema.optional(ConnectorProfileDetailList), nextToken: Schema.optional(Schema.String)}) {}
export class DescribeFlowResponse extends Schema.Class<DescribeFlowResponse>("DescribeFlowResponse")({flowArn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), flowName: Schema.optional(Schema.String), kmsArn: Schema.optional(Schema.String), flowStatus: Schema.optional(Schema.String), flowStatusMessage: Schema.optional(Schema.String), sourceFlowConfig: Schema.optional(SourceFlowConfig), destinationFlowConfigList: Schema.optional(DestinationFlowConfigList), lastRunExecutionDetails: Schema.optional(ExecutionDetails), triggerConfig: Schema.optional(TriggerConfig), tasks: Schema.optional(Tasks), createdAt: Schema.optional(Schema.Date), lastUpdatedAt: Schema.optional(Schema.Date), createdBy: Schema.optional(Schema.String), lastUpdatedBy: Schema.optional(Schema.String), tags: Schema.optional(TagMap), metadataCatalogConfig: Schema.optional(MetadataCatalogConfig), lastRunMetadataCatalogDetails: Schema.optional(MetadataCatalogDetails), schemaVersion: Schema.optional(Schema.Number)}) {}
export class ListConnectorEntitiesResponse extends Schema.Class<ListConnectorEntitiesResponse>("ListConnectorEntitiesResponse")({connectorEntityMap: ConnectorEntityMap, nextToken: Schema.optional(Schema.String)}) {}
export class RegisterConnectorResponse extends Schema.Class<RegisterConnectorResponse>("RegisterConnectorResponse")({connectorArn: Schema.optional(Schema.String)}) {}
export class ExecutionResult extends Schema.Class<ExecutionResult>("ExecutionResult")({errorInfo: Schema.optional(ErrorInfo), bytesProcessed: Schema.optional(Schema.Number), bytesWritten: Schema.optional(Schema.Number), recordsProcessed: Schema.optional(Schema.Number), numParallelProcesses: Schema.optional(Schema.Number), maxPageSize: Schema.optional(Schema.Number)}) {}
export class Range extends Schema.Class<Range>("Range")({maximum: Schema.optional(Schema.Number), minimum: Schema.optional(Schema.Number)}) {}
export class ExecutionRecord extends Schema.Class<ExecutionRecord>("ExecutionRecord")({executionId: Schema.optional(Schema.String), executionStatus: Schema.optional(Schema.String), executionResult: Schema.optional(ExecutionResult), startedAt: Schema.optional(Schema.Date), lastUpdatedAt: Schema.optional(Schema.Date), dataPullStartTime: Schema.optional(Schema.Date), dataPullEndTime: Schema.optional(Schema.Date), metadataCatalogDetails: Schema.optional(MetadataCatalogDetails)}) {}
export const FlowExecutionList = Schema.Array(ExecutionRecord);
export class FieldTypeDetails extends Schema.Class<FieldTypeDetails>("FieldTypeDetails")({fieldType: Schema.String, filterOperators: FilterOperatorList, supportedValues: Schema.optional(SupportedValueList), valueRegexPattern: Schema.optional(Schema.String), supportedDateFormat: Schema.optional(Schema.String), fieldValueRange: Schema.optional(Range), fieldLengthRange: Schema.optional(Range)}) {}
export class DescribeFlowExecutionRecordsResponse extends Schema.Class<DescribeFlowExecutionRecordsResponse>("DescribeFlowExecutionRecordsResponse")({flowExecutions: Schema.optional(FlowExecutionList), nextToken: Schema.optional(Schema.String)}) {}
export class SupportedFieldTypeDetails extends Schema.Class<SupportedFieldTypeDetails>("SupportedFieldTypeDetails")({v1: FieldTypeDetails}) {}
export class ConnectorEntityField extends Schema.Class<ConnectorEntityField>("ConnectorEntityField")({identifier: Schema.String, parentIdentifier: Schema.optional(Schema.String), label: Schema.optional(Schema.String), isPrimaryKey: Schema.optional(Schema.Boolean), defaultValue: Schema.optional(Schema.String), isDeprecated: Schema.optional(Schema.Boolean), supportedFieldTypeDetails: Schema.optional(SupportedFieldTypeDetails), description: Schema.optional(Schema.String), sourceProperties: Schema.optional(SourceFieldProperties), destinationProperties: Schema.optional(DestinationFieldProperties), customProperties: Schema.optional(CustomProperties)}) {}
export const ConnectorEntityFieldList = Schema.Array(ConnectorEntityField);
export class CreateConnectorProfileRequest extends Schema.Class<CreateConnectorProfileRequest>("CreateConnectorProfileRequest")({connectorProfileName: Schema.String, kmsArn: Schema.optional(Schema.String), connectorType: Schema.String, connectorLabel: Schema.optional(Schema.String), connectionMode: Schema.String, connectorProfileConfig: ConnectorProfileConfig, clientToken: Schema.optional(Schema.String)}) {}
export class CreateFlowRequest extends Schema.Class<CreateFlowRequest>("CreateFlowRequest")({flowName: Schema.String, description: Schema.optional(Schema.String), kmsArn: Schema.optional(Schema.String), triggerConfig: TriggerConfig, sourceFlowConfig: SourceFlowConfig, destinationFlowConfigList: DestinationFlowConfigList, tasks: Tasks, tags: Schema.optional(TagMap), metadataCatalogConfig: Schema.optional(MetadataCatalogConfig), clientToken: Schema.optional(Schema.String)}) {}
export class DescribeConnectorResponse extends Schema.Class<DescribeConnectorResponse>("DescribeConnectorResponse")({connectorConfiguration: Schema.optional(ConnectorConfiguration)}) {}
export class DescribeConnectorEntityResponse extends Schema.Class<DescribeConnectorEntityResponse>("DescribeConnectorEntityResponse")({connectorEntityFields: ConnectorEntityFieldList}) {}
export class CreateConnectorProfileResponse extends Schema.Class<CreateConnectorProfileResponse>("CreateConnectorProfileResponse")({connectorProfileArn: Schema.optional(Schema.String)}) {}
export class CreateFlowResponse extends Schema.Class<CreateFlowResponse>("CreateFlowResponse")({flowArn: Schema.optional(Schema.String), flowStatus: Schema.optional(Schema.String)}) {}

//# Errors
export class ConflictExceptionError extends Schema.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class InternalServerExceptionError extends Schema.TaggedError<InternalServerExceptionError>()("InternalServerException", InternalServerException.fields) {};
export class ResourceNotFoundExceptionError extends Schema.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ValidationExceptionError extends Schema.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};
export class AccessDeniedExceptionError extends Schema.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class ConnectorAuthenticationExceptionError extends Schema.TaggedError<ConnectorAuthenticationExceptionError>()("ConnectorAuthenticationException", ConnectorAuthenticationException.fields) {};
export class ConnectorServerExceptionError extends Schema.TaggedError<ConnectorServerExceptionError>()("ConnectorServerException", ConnectorServerException.fields) {};
export class ServiceQuotaExceededExceptionError extends Schema.TaggedError<ServiceQuotaExceededExceptionError>()("ServiceQuotaExceededException", ServiceQuotaExceededException.fields) {};
export class UnsupportedOperationExceptionError extends Schema.TaggedError<UnsupportedOperationExceptionError>()("UnsupportedOperationException", UnsupportedOperationException.fields) {};
export class ThrottlingExceptionError extends Schema.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};

//# Operations
export const unregisterConnector = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/unregister-connector", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.UnregisterConnector" }, UnregisterConnectorRequest, UnregisterConnectorResponse, [ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteConnectorProfile = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/delete-connector-profile", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.DeleteConnectorProfile" }, DeleteConnectorProfileRequest, DeleteConnectorProfileResponse, [ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteFlow = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/delete-flow", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.DeleteFlow" }, DeleteFlowRequest, DeleteFlowResponse, [ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listConnectors = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/list-connectors", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.ListConnectors" }, ListConnectorsRequest, ListConnectorsResponse, [InternalServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/tags/{resourceArn}", method: "GET", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const resetConnectorMetadataCache = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/reset-connector-metadata-cache", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.ResetConnectorMetadataCache" }, ResetConnectorMetadataCacheRequest, ResetConnectorMetadataCacheResponse, [ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/tags/{resourceArn}", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.TagResource" }, TagResourceRequest, TagResourceResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateFlow = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/update-flow", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.UpdateFlow" }, UpdateFlowRequest, UpdateFlowResponse, [AccessDeniedExceptionError, ConflictExceptionError, ConnectorAuthenticationExceptionError, ConnectorServerExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeConnectors = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/describe-connectors", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.DescribeConnectors" }, DescribeConnectorsRequest, DescribeConnectorsResponse, [InternalServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listFlows = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/list-flows", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.ListFlows" }, ListFlowsRequest, ListFlowsResponse, [InternalServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const startFlow = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/start-flow", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.StartFlow" }, StartFlowRequest, StartFlowResponse, [ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const stopFlow = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/stop-flow", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.StopFlow" }, StopFlowRequest, StopFlowResponse, [ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, UnsupportedOperationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateConnectorProfile = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/update-connector-profile", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.UpdateConnectorProfile" }, UpdateConnectorProfileRequest, UpdateConnectorProfileResponse, [ConflictExceptionError, ConnectorAuthenticationExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateConnectorRegistration = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/update-connector-registration", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.UpdateConnectorRegistration" }, UpdateConnectorRegistrationRequest, UpdateConnectorRegistrationResponse, [AccessDeniedExceptionError, ConflictExceptionError, ConnectorAuthenticationExceptionError, ConnectorServerExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const cancelFlowExecutions = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/cancel-flow-executions", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.CancelFlowExecutions" }, CancelFlowExecutionsRequest, CancelFlowExecutionsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeConnectorProfiles = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/describe-connector-profiles", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.DescribeConnectorProfiles" }, DescribeConnectorProfilesRequest, DescribeConnectorProfilesResponse, [InternalServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeFlow = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/describe-flow", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.DescribeFlow" }, DescribeFlowRequest, DescribeFlowResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listConnectorEntities = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/list-connector-entities", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.ListConnectorEntities" }, ListConnectorEntitiesRequest, ListConnectorEntitiesResponse, [ConnectorAuthenticationExceptionError, ConnectorServerExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const registerConnector = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/register-connector", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.RegisterConnector" }, RegisterConnectorRequest, RegisterConnectorResponse, [AccessDeniedExceptionError, ConflictExceptionError, ConnectorAuthenticationExceptionError, ConnectorServerExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeFlowExecutionRecords = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/describe-flow-execution-records", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.DescribeFlowExecutionRecords" }, DescribeFlowExecutionRecordsRequest, DescribeFlowExecutionRecordsResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeConnector = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/describe-connector", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.DescribeConnector" }, DescribeConnectorRequest, DescribeConnectorResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeConnectorEntity = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/describe-connector-entity", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.DescribeConnectorEntity" }, DescribeConnectorEntityRequest, DescribeConnectorEntityResponse, [ConnectorAuthenticationExceptionError, ConnectorServerExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createConnectorProfile = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/create-connector-profile", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.CreateConnectorProfile" }, CreateConnectorProfileRequest, CreateConnectorProfileResponse, [ConflictExceptionError, ConnectorAuthenticationExceptionError, InternalServerExceptionError, ServiceQuotaExceededExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createFlow = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-08-23", uri: "/create-flow", method: "POST", sdkId: "Appflow", sigV4ServiceName: "appflow", name: "SandstoneConfigurationServiceLambda.CreateFlow" }, CreateFlowRequest, CreateFlowResponse, [AccessDeniedExceptionError, ConflictExceptionError, ConnectorAuthenticationExceptionError, ConnectorServerExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
