import { Schema} from "effect"
import { FormatAwsJSON10Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
export const GetPreferencesRequest = Schema.Struct({});
export const RateTypes = Schema.Array(Schema.String);
export const ResourceTagKeys = Schema.Array(Schema.String);
export const GetPreferencesResponse = Schema.Struct({managementAccountRateTypeSelections: Schema.optional(RateTypes), memberAccountRateTypeSelections: Schema.optional(RateTypes), standaloneAccountRateTypeSelections: Schema.optional(RateTypes)});
export const ListTagsForResourceRequest = Schema.Struct({arn: Schema.String});
export const UntagResourceRequest = Schema.Struct({arn: Schema.String, tagKeys: ResourceTagKeys});
export const UntagResourceResponse = Schema.Struct({});
export const UpdatePreferencesRequest = Schema.Struct({managementAccountRateTypeSelections: Schema.optional(RateTypes), memberAccountRateTypeSelections: Schema.optional(RateTypes), standaloneAccountRateTypeSelections: Schema.optional(RateTypes)});
export const Tags = Schema.Record({key: Schema.String, value: Schema.String});
export const DataUnavailableException = Schema.Struct({message: Schema.String});
export const ListTagsForResourceResponse = Schema.Struct({tags: Schema.optional(Tags)});
export const TagResourceRequest = Schema.Struct({arn: Schema.String, tags: Tags});
export const TagResourceResponse = Schema.Struct({});
export const ResourceNotFoundException = Schema.Struct({message: Schema.String, resourceId: Schema.String, resourceType: Schema.String});
export const UpdatePreferencesResponse = Schema.Struct({managementAccountRateTypeSelections: Schema.optional(RateTypes), memberAccountRateTypeSelections: Schema.optional(RateTypes), standaloneAccountRateTypeSelections: Schema.optional(RateTypes)});
export const ServiceQuotaExceededException = Schema.Struct({message: Schema.String, resourceId: Schema.String, resourceType: Schema.String, serviceCode: Schema.optional(Schema.String), quotaCode: Schema.optional(Schema.String)});
export const GetPreferences = /*#__PURE__*/ makeOperation(() => Operation({ version: "2024-06-19", uri: "/", method: "POST", sdkId: "BCM Pricing Calculator", sigV4ServiceName: "bcm-pricing-calculator", name: "AWSBCMPricingCalculator.GetPreferences" }, GetPreferencesRequest, GetPreferencesResponse, ErrorAnnotation("DataUnavailableException", DataUnavailableException)), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const ListTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2024-06-19", uri: "/", method: "POST", sdkId: "BCM Pricing Calculator", sigV4ServiceName: "bcm-pricing-calculator", name: "AWSBCMPricingCalculator.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException)), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2024-06-19", uri: "/", method: "POST", sdkId: "BCM Pricing Calculator", sigV4ServiceName: "bcm-pricing-calculator", name: "AWSBCMPricingCalculator.UntagResource" }, UntagResourceRequest, UntagResourceResponse, ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException)), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const UpdatePreferences = /*#__PURE__*/ makeOperation(() => Operation({ version: "2024-06-19", uri: "/", method: "POST", sdkId: "BCM Pricing Calculator", sigV4ServiceName: "bcm-pricing-calculator", name: "AWSBCMPricingCalculator.UpdatePreferences" }, UpdatePreferencesRequest, UpdatePreferencesResponse, Schema.Union(ErrorAnnotation("DataUnavailableException", DataUnavailableException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException))), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2024-06-19", uri: "/", method: "POST", sdkId: "BCM Pricing Calculator", sigV4ServiceName: "bcm-pricing-calculator", name: "AWSBCMPricingCalculator.TagResource" }, TagResourceRequest, TagResourceResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException))), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
