import * as S from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export class GetAccountPreferencesRequest extends S.Class<GetAccountPreferencesRequest>("GetAccountPreferencesRequest")({}) {}
export const SnsTopicArnList = S.Array(S.String);
export const GuardrailPolicyArnList = S.Array(S.String);
export class Tag extends S.Class<Tag>("Tag")({TagKey: S.String, TagValue: S.String}) {}
export const TagList = S.Array(Tag);
export const TagKeyList = S.Array(S.String);
export class AssociateToConfigurationRequest extends S.Class<AssociateToConfigurationRequest>("AssociateToConfigurationRequest")({Resource: S.String, ChatConfiguration: S.String}) {}
export class AssociateToConfigurationResult extends S.Class<AssociateToConfigurationResult>("AssociateToConfigurationResult")({}) {}
export const Tags = S.Array(Tag);
export class CreateTeamsChannelConfigurationRequest extends S.Class<CreateTeamsChannelConfigurationRequest>("CreateTeamsChannelConfigurationRequest")({ChannelId: S.String, ChannelName: S.optional(S.String), TeamId: S.String, TeamName: S.optional(S.String), TenantId: S.String, SnsTopicArns: S.optional(SnsTopicArnList), IamRoleArn: S.String, ConfigurationName: S.String, LoggingLevel: S.optional(S.String), GuardrailPolicyArns: S.optional(GuardrailPolicyArnList), UserAuthorizationRequired: S.optional(S.Boolean), Tags: S.optional(Tags)}) {}
export class CreateSlackChannelConfigurationRequest extends S.Class<CreateSlackChannelConfigurationRequest>("CreateSlackChannelConfigurationRequest")({SlackTeamId: S.String, SlackChannelId: S.String, SlackChannelName: S.optional(S.String), SnsTopicArns: S.optional(SnsTopicArnList), IamRoleArn: S.String, ConfigurationName: S.String, LoggingLevel: S.optional(S.String), GuardrailPolicyArns: S.optional(GuardrailPolicyArnList), UserAuthorizationRequired: S.optional(S.Boolean), Tags: S.optional(Tags)}) {}
export class DeleteChimeWebhookConfigurationRequest extends S.Class<DeleteChimeWebhookConfigurationRequest>("DeleteChimeWebhookConfigurationRequest")({ChatConfigurationArn: S.String}) {}
export class DeleteChimeWebhookConfigurationResult extends S.Class<DeleteChimeWebhookConfigurationResult>("DeleteChimeWebhookConfigurationResult")({}) {}
export class DeleteTeamsChannelConfigurationRequest extends S.Class<DeleteTeamsChannelConfigurationRequest>("DeleteTeamsChannelConfigurationRequest")({ChatConfigurationArn: S.String}) {}
export class DeleteTeamsChannelConfigurationResult extends S.Class<DeleteTeamsChannelConfigurationResult>("DeleteTeamsChannelConfigurationResult")({}) {}
export class DeleteTeamsConfiguredTeamRequest extends S.Class<DeleteTeamsConfiguredTeamRequest>("DeleteTeamsConfiguredTeamRequest")({TeamId: S.String}) {}
export class DeleteTeamsConfiguredTeamResult extends S.Class<DeleteTeamsConfiguredTeamResult>("DeleteTeamsConfiguredTeamResult")({}) {}
export class DeleteMicrosoftTeamsUserIdentityRequest extends S.Class<DeleteMicrosoftTeamsUserIdentityRequest>("DeleteMicrosoftTeamsUserIdentityRequest")({ChatConfigurationArn: S.String, UserId: S.String}) {}
export class DeleteMicrosoftTeamsUserIdentityResult extends S.Class<DeleteMicrosoftTeamsUserIdentityResult>("DeleteMicrosoftTeamsUserIdentityResult")({}) {}
export class DeleteSlackChannelConfigurationRequest extends S.Class<DeleteSlackChannelConfigurationRequest>("DeleteSlackChannelConfigurationRequest")({ChatConfigurationArn: S.String}) {}
export class DeleteSlackChannelConfigurationResult extends S.Class<DeleteSlackChannelConfigurationResult>("DeleteSlackChannelConfigurationResult")({}) {}
export class DeleteSlackUserIdentityRequest extends S.Class<DeleteSlackUserIdentityRequest>("DeleteSlackUserIdentityRequest")({ChatConfigurationArn: S.String, SlackTeamId: S.String, SlackUserId: S.String}) {}
export class DeleteSlackUserIdentityResult extends S.Class<DeleteSlackUserIdentityResult>("DeleteSlackUserIdentityResult")({}) {}
export class DeleteSlackWorkspaceAuthorizationRequest extends S.Class<DeleteSlackWorkspaceAuthorizationRequest>("DeleteSlackWorkspaceAuthorizationRequest")({SlackTeamId: S.String}) {}
export class DeleteSlackWorkspaceAuthorizationResult extends S.Class<DeleteSlackWorkspaceAuthorizationResult>("DeleteSlackWorkspaceAuthorizationResult")({}) {}
export class DescribeChimeWebhookConfigurationsRequest extends S.Class<DescribeChimeWebhookConfigurationsRequest>("DescribeChimeWebhookConfigurationsRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ChatConfigurationArn: S.optional(S.String)}) {}
export class DescribeSlackChannelConfigurationsRequest extends S.Class<DescribeSlackChannelConfigurationsRequest>("DescribeSlackChannelConfigurationsRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ChatConfigurationArn: S.optional(S.String)}) {}
export class DescribeSlackUserIdentitiesRequest extends S.Class<DescribeSlackUserIdentitiesRequest>("DescribeSlackUserIdentitiesRequest")({ChatConfigurationArn: S.optional(S.String), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class DescribeSlackWorkspacesRequest extends S.Class<DescribeSlackWorkspacesRequest>("DescribeSlackWorkspacesRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class DisassociateFromConfigurationRequest extends S.Class<DisassociateFromConfigurationRequest>("DisassociateFromConfigurationRequest")({Resource: S.String, ChatConfiguration: S.String}) {}
export class DisassociateFromConfigurationResult extends S.Class<DisassociateFromConfigurationResult>("DisassociateFromConfigurationResult")({}) {}
export class GetTeamsChannelConfigurationRequest extends S.Class<GetTeamsChannelConfigurationRequest>("GetTeamsChannelConfigurationRequest")({ChatConfigurationArn: S.String}) {}
export class ListAssociationsRequest extends S.Class<ListAssociationsRequest>("ListAssociationsRequest")({ChatConfiguration: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListTeamsChannelConfigurationsRequest extends S.Class<ListTeamsChannelConfigurationsRequest>("ListTeamsChannelConfigurationsRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), TeamId: S.optional(S.String)}) {}
export class ListMicrosoftTeamsConfiguredTeamsRequest extends S.Class<ListMicrosoftTeamsConfiguredTeamsRequest>("ListMicrosoftTeamsConfiguredTeamsRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListMicrosoftTeamsUserIdentitiesRequest extends S.Class<ListMicrosoftTeamsUserIdentitiesRequest>("ListMicrosoftTeamsUserIdentitiesRequest")({ChatConfigurationArn: S.optional(S.String), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceARN: S.String}) {}
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceARN: S.String, Tags: TagList}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceARN: S.String, TagKeys: TagKeyList}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class UpdateAccountPreferencesRequest extends S.Class<UpdateAccountPreferencesRequest>("UpdateAccountPreferencesRequest")({UserAuthorizationRequired: S.optional(S.Boolean), TrainingDataCollectionEnabled: S.optional(S.Boolean)}) {}
export class UpdateChimeWebhookConfigurationRequest extends S.Class<UpdateChimeWebhookConfigurationRequest>("UpdateChimeWebhookConfigurationRequest")({ChatConfigurationArn: S.String, WebhookDescription: S.optional(S.String), WebhookUrl: S.optional(S.String), SnsTopicArns: S.optional(SnsTopicArnList), IamRoleArn: S.optional(S.String), LoggingLevel: S.optional(S.String)}) {}
export class UpdateTeamsChannelConfigurationRequest extends S.Class<UpdateTeamsChannelConfigurationRequest>("UpdateTeamsChannelConfigurationRequest")({ChatConfigurationArn: S.String, ChannelId: S.String, ChannelName: S.optional(S.String), SnsTopicArns: S.optional(SnsTopicArnList), IamRoleArn: S.optional(S.String), LoggingLevel: S.optional(S.String), GuardrailPolicyArns: S.optional(GuardrailPolicyArnList), UserAuthorizationRequired: S.optional(S.Boolean)}) {}
export class UpdateSlackChannelConfigurationRequest extends S.Class<UpdateSlackChannelConfigurationRequest>("UpdateSlackChannelConfigurationRequest")({ChatConfigurationArn: S.String, SlackChannelId: S.String, SlackChannelName: S.optional(S.String), SnsTopicArns: S.optional(SnsTopicArnList), IamRoleArn: S.optional(S.String), LoggingLevel: S.optional(S.String), GuardrailPolicyArns: S.optional(GuardrailPolicyArnList), UserAuthorizationRequired: S.optional(S.Boolean)}) {}
export class SlackChannelConfiguration extends S.Class<SlackChannelConfiguration>("SlackChannelConfiguration")({SlackTeamName: S.String, SlackTeamId: S.String, SlackChannelId: S.String, SlackChannelName: S.String, ChatConfigurationArn: S.String, IamRoleArn: S.String, SnsTopicArns: SnsTopicArnList, ConfigurationName: S.optional(S.String), LoggingLevel: S.optional(S.String), GuardrailPolicyArns: S.optional(GuardrailPolicyArnList), UserAuthorizationRequired: S.optional(S.Boolean), Tags: S.optional(Tags), State: S.optional(S.String), StateReason: S.optional(S.String)}) {}
export const SlackChannelConfigurationList = S.Array(SlackChannelConfiguration);
export class AccountPreferences extends S.Class<AccountPreferences>("AccountPreferences")({UserAuthorizationRequired: S.optional(S.Boolean), TrainingDataCollectionEnabled: S.optional(S.Boolean)}) {}
export class TeamsChannelConfiguration extends S.Class<TeamsChannelConfiguration>("TeamsChannelConfiguration")({ChannelId: S.String, ChannelName: S.optional(S.String), TeamId: S.String, TeamName: S.optional(S.String), TenantId: S.String, ChatConfigurationArn: S.String, IamRoleArn: S.String, SnsTopicArns: SnsTopicArnList, ConfigurationName: S.optional(S.String), LoggingLevel: S.optional(S.String), GuardrailPolicyArns: S.optional(GuardrailPolicyArnList), UserAuthorizationRequired: S.optional(S.Boolean), Tags: S.optional(Tags), State: S.optional(S.String), StateReason: S.optional(S.String)}) {}
export const TeamChannelConfigurationsList = S.Array(TeamsChannelConfiguration);
export class InternalServiceError extends S.Class<InternalServiceError>("InternalServiceError")({Message: S.optional(S.String)}) {}
export class CreateChimeWebhookConfigurationRequest extends S.Class<CreateChimeWebhookConfigurationRequest>("CreateChimeWebhookConfigurationRequest")({WebhookDescription: S.String, WebhookUrl: S.String, SnsTopicArns: SnsTopicArnList, IamRoleArn: S.String, ConfigurationName: S.String, LoggingLevel: S.optional(S.String), Tags: S.optional(Tags)}) {}
export class DeleteChimeWebhookConfigurationException extends S.Class<DeleteChimeWebhookConfigurationException>("DeleteChimeWebhookConfigurationException")({Message: S.optional(S.String)}) {}
export class DeleteTeamsChannelConfigurationException extends S.Class<DeleteTeamsChannelConfigurationException>("DeleteTeamsChannelConfigurationException")({Message: S.optional(S.String)}) {}
export class DeleteTeamsConfiguredTeamException extends S.Class<DeleteTeamsConfiguredTeamException>("DeleteTeamsConfiguredTeamException")({Message: S.optional(S.String)}) {}
export class DeleteMicrosoftTeamsUserIdentityException extends S.Class<DeleteMicrosoftTeamsUserIdentityException>("DeleteMicrosoftTeamsUserIdentityException")({Message: S.optional(S.String)}) {}
export class DeleteSlackChannelConfigurationException extends S.Class<DeleteSlackChannelConfigurationException>("DeleteSlackChannelConfigurationException")({Message: S.optional(S.String)}) {}
export class DeleteSlackUserIdentityException extends S.Class<DeleteSlackUserIdentityException>("DeleteSlackUserIdentityException")({Message: S.optional(S.String)}) {}
export class DeleteSlackWorkspaceAuthorizationFault extends S.Class<DeleteSlackWorkspaceAuthorizationFault>("DeleteSlackWorkspaceAuthorizationFault")({Message: S.optional(S.String)}) {}
export class DescribeSlackChannelConfigurationsResult extends S.Class<DescribeSlackChannelConfigurationsResult>("DescribeSlackChannelConfigurationsResult")({NextToken: S.optional(S.String), SlackChannelConfigurations: S.optional(SlackChannelConfigurationList)}) {}
export class InvalidRequestException extends S.Class<InvalidRequestException>("InvalidRequestException")({message: S.optional(S.String)}) {}
export class GetAccountPreferencesResult extends S.Class<GetAccountPreferencesResult>("GetAccountPreferencesResult")({AccountPreferences: S.optional(AccountPreferences)}) {}
export class GetTeamsChannelConfigurationResult extends S.Class<GetTeamsChannelConfigurationResult>("GetTeamsChannelConfigurationResult")({ChannelConfiguration: S.optional(TeamsChannelConfiguration)}) {}
export class ListTeamsChannelConfigurationsResult extends S.Class<ListTeamsChannelConfigurationsResult>("ListTeamsChannelConfigurationsResult")({NextToken: S.optional(S.String), TeamChannelConfigurations: S.optional(TeamChannelConfigurationsList)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: S.optional(TagList)}) {}
export class ResourceNotFoundException extends S.Class<ResourceNotFoundException>("ResourceNotFoundException")({Message: S.optional(S.String)}) {}
export class ServiceUnavailableException extends S.Class<ServiceUnavailableException>("ServiceUnavailableException")({message: S.optional(S.String)}) {}
export class UpdateAccountPreferencesResult extends S.Class<UpdateAccountPreferencesResult>("UpdateAccountPreferencesResult")({AccountPreferences: S.optional(AccountPreferences)}) {}
export class ChimeWebhookConfiguration extends S.Class<ChimeWebhookConfiguration>("ChimeWebhookConfiguration")({WebhookDescription: S.String, ChatConfigurationArn: S.String, IamRoleArn: S.String, SnsTopicArns: SnsTopicArnList, ConfigurationName: S.optional(S.String), LoggingLevel: S.optional(S.String), Tags: S.optional(Tags), State: S.optional(S.String), StateReason: S.optional(S.String)}) {}
export class UpdateChimeWebhookConfigurationResult extends S.Class<UpdateChimeWebhookConfigurationResult>("UpdateChimeWebhookConfigurationResult")({WebhookConfiguration: S.optional(ChimeWebhookConfiguration)}) {}
export class UpdateTeamsChannelConfigurationResult extends S.Class<UpdateTeamsChannelConfigurationResult>("UpdateTeamsChannelConfigurationResult")({ChannelConfiguration: S.optional(TeamsChannelConfiguration)}) {}
export class UpdateSlackChannelConfigurationResult extends S.Class<UpdateSlackChannelConfigurationResult>("UpdateSlackChannelConfigurationResult")({ChannelConfiguration: S.optional(SlackChannelConfiguration)}) {}
export const ChimeWebhookConfigurationList = S.Array(ChimeWebhookConfiguration);
export class SlackUserIdentity extends S.Class<SlackUserIdentity>("SlackUserIdentity")({IamRoleArn: S.String, ChatConfigurationArn: S.String, SlackTeamId: S.String, SlackUserId: S.String, AwsUserIdentity: S.optional(S.String)}) {}
export const SlackUserIdentitiesList = S.Array(SlackUserIdentity);
export class SlackWorkspace extends S.Class<SlackWorkspace>("SlackWorkspace")({SlackTeamId: S.String, SlackTeamName: S.String, State: S.optional(S.String), StateReason: S.optional(S.String)}) {}
export const SlackWorkspacesList = S.Array(SlackWorkspace);
export class AssociationListing extends S.Class<AssociationListing>("AssociationListing")({Resource: S.String}) {}
export const AssociationList = S.Array(AssociationListing);
export class ConfiguredTeam extends S.Class<ConfiguredTeam>("ConfiguredTeam")({TenantId: S.String, TeamId: S.String, TeamName: S.optional(S.String), State: S.optional(S.String), StateReason: S.optional(S.String)}) {}
export const ConfiguredTeamsList = S.Array(ConfiguredTeam);
export class TeamsUserIdentity extends S.Class<TeamsUserIdentity>("TeamsUserIdentity")({IamRoleArn: S.String, ChatConfigurationArn: S.String, TeamId: S.String, UserId: S.optional(S.String), AwsUserIdentity: S.optional(S.String), TeamsChannelId: S.optional(S.String), TeamsTenantId: S.optional(S.String)}) {}
export const TeamsUserIdentitiesList = S.Array(TeamsUserIdentity);
export class UnauthorizedException extends S.Class<UnauthorizedException>("UnauthorizedException")({message: S.optional(S.String)}) {}
export class CreateChimeWebhookConfigurationResult extends S.Class<CreateChimeWebhookConfigurationResult>("CreateChimeWebhookConfigurationResult")({WebhookConfiguration: S.optional(ChimeWebhookConfiguration)}) {}
export class CreateTeamsChannelConfigurationResult extends S.Class<CreateTeamsChannelConfigurationResult>("CreateTeamsChannelConfigurationResult")({ChannelConfiguration: S.optional(TeamsChannelConfiguration)}) {}
export class CreateSlackChannelConfigurationResult extends S.Class<CreateSlackChannelConfigurationResult>("CreateSlackChannelConfigurationResult")({ChannelConfiguration: S.optional(SlackChannelConfiguration)}) {}
export class InvalidParameterException extends S.Class<InvalidParameterException>("InvalidParameterException")({message: S.optional(S.String)}) {}
export class DescribeChimeWebhookConfigurationsResult extends S.Class<DescribeChimeWebhookConfigurationsResult>("DescribeChimeWebhookConfigurationsResult")({NextToken: S.optional(S.String), WebhookConfigurations: S.optional(ChimeWebhookConfigurationList)}) {}
export class DescribeSlackChannelConfigurationsException extends S.Class<DescribeSlackChannelConfigurationsException>("DescribeSlackChannelConfigurationsException")({Message: S.optional(S.String)}) {}
export class DescribeSlackUserIdentitiesResult extends S.Class<DescribeSlackUserIdentitiesResult>("DescribeSlackUserIdentitiesResult")({SlackUserIdentities: S.optional(SlackUserIdentitiesList), NextToken: S.optional(S.String)}) {}
export class DescribeSlackWorkspacesResult extends S.Class<DescribeSlackWorkspacesResult>("DescribeSlackWorkspacesResult")({SlackWorkspaces: S.optional(SlackWorkspacesList), NextToken: S.optional(S.String)}) {}
export class GetAccountPreferencesException extends S.Class<GetAccountPreferencesException>("GetAccountPreferencesException")({Message: S.optional(S.String)}) {}
export class GetTeamsChannelConfigurationException extends S.Class<GetTeamsChannelConfigurationException>("GetTeamsChannelConfigurationException")({Message: S.optional(S.String)}) {}
export class ListAssociationsResult extends S.Class<ListAssociationsResult>("ListAssociationsResult")({Associations: AssociationList, NextToken: S.optional(S.String)}) {}
export class ListTeamsChannelConfigurationsException extends S.Class<ListTeamsChannelConfigurationsException>("ListTeamsChannelConfigurationsException")({Message: S.optional(S.String)}) {}
export class ListMicrosoftTeamsConfiguredTeamsResult extends S.Class<ListMicrosoftTeamsConfiguredTeamsResult>("ListMicrosoftTeamsConfiguredTeamsResult")({ConfiguredTeams: S.optional(ConfiguredTeamsList), NextToken: S.optional(S.String)}) {}
export class ListMicrosoftTeamsUserIdentitiesResult extends S.Class<ListMicrosoftTeamsUserIdentitiesResult>("ListMicrosoftTeamsUserIdentitiesResult")({TeamsUserIdentities: S.optional(TeamsUserIdentitiesList), NextToken: S.optional(S.String)}) {}
export class TooManyTagsException extends S.Class<TooManyTagsException>("TooManyTagsException")({message: S.optional(S.String)}) {}
export class UpdateAccountPreferencesException extends S.Class<UpdateAccountPreferencesException>("UpdateAccountPreferencesException")({Message: S.optional(S.String)}) {}
export class UpdateChimeWebhookConfigurationException extends S.Class<UpdateChimeWebhookConfigurationException>("UpdateChimeWebhookConfigurationException")({Message: S.optional(S.String)}) {}
export class UpdateTeamsChannelConfigurationException extends S.Class<UpdateTeamsChannelConfigurationException>("UpdateTeamsChannelConfigurationException")({Message: S.optional(S.String)}) {}
export class UpdateSlackChannelConfigurationException extends S.Class<UpdateSlackChannelConfigurationException>("UpdateSlackChannelConfigurationException")({Message: S.optional(S.String)}) {}
export class ConflictException extends S.Class<ConflictException>("ConflictException")({message: S.optional(S.String)}) {}
export class CreateTeamsChannelConfigurationException extends S.Class<CreateTeamsChannelConfigurationException>("CreateTeamsChannelConfigurationException")({Message: S.optional(S.String)}) {}
export class CreateSlackChannelConfigurationException extends S.Class<CreateSlackChannelConfigurationException>("CreateSlackChannelConfigurationException")({Message: S.optional(S.String)}) {}
export class DescribeChimeWebhookConfigurationsException extends S.Class<DescribeChimeWebhookConfigurationsException>("DescribeChimeWebhookConfigurationsException")({Message: S.optional(S.String)}) {}
export class DescribeSlackUserIdentitiesException extends S.Class<DescribeSlackUserIdentitiesException>("DescribeSlackUserIdentitiesException")({Message: S.optional(S.String)}) {}
export class DescribeSlackWorkspacesException extends S.Class<DescribeSlackWorkspacesException>("DescribeSlackWorkspacesException")({Message: S.optional(S.String)}) {}
export class ListMicrosoftTeamsConfiguredTeamsException extends S.Class<ListMicrosoftTeamsConfiguredTeamsException>("ListMicrosoftTeamsConfiguredTeamsException")({Message: S.optional(S.String)}) {}
export class ListMicrosoftTeamsUserIdentitiesException extends S.Class<ListMicrosoftTeamsUserIdentitiesException>("ListMicrosoftTeamsUserIdentitiesException")({Message: S.optional(S.String)}) {}
export class CreateChimeWebhookConfigurationException extends S.Class<CreateChimeWebhookConfigurationException>("CreateChimeWebhookConfigurationException")({Message: S.optional(S.String)}) {}
export class LimitExceededException extends S.Class<LimitExceededException>("LimitExceededException")({message: S.optional(S.String)}) {}

//# Errors
export class InternalServiceErrorError extends S.TaggedError<InternalServiceErrorError>()("InternalServiceError", InternalServiceError.fields) {};
export class ResourceNotFoundExceptionError extends S.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class InvalidRequestExceptionError extends S.TaggedError<InvalidRequestExceptionError>()("InvalidRequestException", InvalidRequestException.fields) {};
export class DeleteChimeWebhookConfigurationExceptionError extends S.TaggedError<DeleteChimeWebhookConfigurationExceptionError>()("DeleteChimeWebhookConfigurationException", DeleteChimeWebhookConfigurationException.fields) {};
export class DeleteTeamsChannelConfigurationExceptionError extends S.TaggedError<DeleteTeamsChannelConfigurationExceptionError>()("DeleteTeamsChannelConfigurationException", DeleteTeamsChannelConfigurationException.fields) {};
export class InvalidParameterExceptionError extends S.TaggedError<InvalidParameterExceptionError>()("InvalidParameterException", InvalidParameterException.fields) {};
export class DeleteTeamsConfiguredTeamExceptionError extends S.TaggedError<DeleteTeamsConfiguredTeamExceptionError>()("DeleteTeamsConfiguredTeamException", DeleteTeamsConfiguredTeamException.fields) {};
export class DeleteMicrosoftTeamsUserIdentityExceptionError extends S.TaggedError<DeleteMicrosoftTeamsUserIdentityExceptionError>()("DeleteMicrosoftTeamsUserIdentityException", DeleteMicrosoftTeamsUserIdentityException.fields) {};
export class DeleteSlackChannelConfigurationExceptionError extends S.TaggedError<DeleteSlackChannelConfigurationExceptionError>()("DeleteSlackChannelConfigurationException", DeleteSlackChannelConfigurationException.fields) {};
export class DeleteSlackUserIdentityExceptionError extends S.TaggedError<DeleteSlackUserIdentityExceptionError>()("DeleteSlackUserIdentityException", DeleteSlackUserIdentityException.fields) {};
export class DeleteSlackWorkspaceAuthorizationFaultError extends S.TaggedError<DeleteSlackWorkspaceAuthorizationFaultError>()("DeleteSlackWorkspaceAuthorizationFault", DeleteSlackWorkspaceAuthorizationFault.fields) {};
export class UnauthorizedExceptionError extends S.TaggedError<UnauthorizedExceptionError>()("UnauthorizedException", UnauthorizedException.fields) {};
export class ServiceUnavailableExceptionError extends S.TaggedError<ServiceUnavailableExceptionError>()("ServiceUnavailableException", ServiceUnavailableException.fields) {};
export class ConflictExceptionError extends S.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class DescribeSlackChannelConfigurationsExceptionError extends S.TaggedError<DescribeSlackChannelConfigurationsExceptionError>()("DescribeSlackChannelConfigurationsException", DescribeSlackChannelConfigurationsException.fields) {};
export class GetAccountPreferencesExceptionError extends S.TaggedError<GetAccountPreferencesExceptionError>()("GetAccountPreferencesException", GetAccountPreferencesException.fields) {};
export class GetTeamsChannelConfigurationExceptionError extends S.TaggedError<GetTeamsChannelConfigurationExceptionError>()("GetTeamsChannelConfigurationException", GetTeamsChannelConfigurationException.fields) {};
export class ListTeamsChannelConfigurationsExceptionError extends S.TaggedError<ListTeamsChannelConfigurationsExceptionError>()("ListTeamsChannelConfigurationsException", ListTeamsChannelConfigurationsException.fields) {};
export class TooManyTagsExceptionError extends S.TaggedError<TooManyTagsExceptionError>()("TooManyTagsException", TooManyTagsException.fields) {};
export class UpdateAccountPreferencesExceptionError extends S.TaggedError<UpdateAccountPreferencesExceptionError>()("UpdateAccountPreferencesException", UpdateAccountPreferencesException.fields) {};
export class UpdateChimeWebhookConfigurationExceptionError extends S.TaggedError<UpdateChimeWebhookConfigurationExceptionError>()("UpdateChimeWebhookConfigurationException", UpdateChimeWebhookConfigurationException.fields) {};
export class UpdateTeamsChannelConfigurationExceptionError extends S.TaggedError<UpdateTeamsChannelConfigurationExceptionError>()("UpdateTeamsChannelConfigurationException", UpdateTeamsChannelConfigurationException.fields) {};
export class UpdateSlackChannelConfigurationExceptionError extends S.TaggedError<UpdateSlackChannelConfigurationExceptionError>()("UpdateSlackChannelConfigurationException", UpdateSlackChannelConfigurationException.fields) {};
export class CreateTeamsChannelConfigurationExceptionError extends S.TaggedError<CreateTeamsChannelConfigurationExceptionError>()("CreateTeamsChannelConfigurationException", CreateTeamsChannelConfigurationException.fields) {};
export class CreateSlackChannelConfigurationExceptionError extends S.TaggedError<CreateSlackChannelConfigurationExceptionError>()("CreateSlackChannelConfigurationException", CreateSlackChannelConfigurationException.fields) {};
export class LimitExceededExceptionError extends S.TaggedError<LimitExceededExceptionError>()("LimitExceededException", LimitExceededException.fields) {};
export class DescribeChimeWebhookConfigurationsExceptionError extends S.TaggedError<DescribeChimeWebhookConfigurationsExceptionError>()("DescribeChimeWebhookConfigurationsException", DescribeChimeWebhookConfigurationsException.fields) {};
export class DescribeSlackUserIdentitiesExceptionError extends S.TaggedError<DescribeSlackUserIdentitiesExceptionError>()("DescribeSlackUserIdentitiesException", DescribeSlackUserIdentitiesException.fields) {};
export class DescribeSlackWorkspacesExceptionError extends S.TaggedError<DescribeSlackWorkspacesExceptionError>()("DescribeSlackWorkspacesException", DescribeSlackWorkspacesException.fields) {};
export class ListMicrosoftTeamsConfiguredTeamsExceptionError extends S.TaggedError<ListMicrosoftTeamsConfiguredTeamsExceptionError>()("ListMicrosoftTeamsConfiguredTeamsException", ListMicrosoftTeamsConfiguredTeamsException.fields) {};
export class ListMicrosoftTeamsUserIdentitiesExceptionError extends S.TaggedError<ListMicrosoftTeamsUserIdentitiesExceptionError>()("ListMicrosoftTeamsUserIdentitiesException", ListMicrosoftTeamsUserIdentitiesException.fields) {};
export class CreateChimeWebhookConfigurationExceptionError extends S.TaggedError<CreateChimeWebhookConfigurationExceptionError>()("CreateChimeWebhookConfigurationException", CreateChimeWebhookConfigurationException.fields) {};

//# Operations
export const deleteMicrosoftTeamsChannelConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/delete-ms-teams-channel-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DeleteMicrosoftTeamsChannelConfiguration" }, DeleteTeamsChannelConfigurationRequest, DeleteTeamsChannelConfigurationResult, [DeleteTeamsChannelConfigurationExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteMicrosoftTeamsConfiguredTeam = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/delete-ms-teams-configured-teams", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DeleteMicrosoftTeamsConfiguredTeam" }, DeleteTeamsConfiguredTeamRequest, DeleteTeamsConfiguredTeamResult, [DeleteTeamsConfiguredTeamExceptionError, InvalidParameterExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteMicrosoftTeamsUserIdentity = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/delete-ms-teams-user-identity", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DeleteMicrosoftTeamsUserIdentity" }, DeleteMicrosoftTeamsUserIdentityRequest, DeleteMicrosoftTeamsUserIdentityResult, [DeleteMicrosoftTeamsUserIdentityExceptionError, InvalidParameterExceptionError, ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteSlackChannelConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/delete-slack-channel-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DeleteSlackChannelConfiguration" }, DeleteSlackChannelConfigurationRequest, DeleteSlackChannelConfigurationResult, [DeleteSlackChannelConfigurationExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteSlackUserIdentity = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/delete-slack-user-identity", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DeleteSlackUserIdentity" }, DeleteSlackUserIdentityRequest, DeleteSlackUserIdentityResult, [DeleteSlackUserIdentityExceptionError, InvalidParameterExceptionError, ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteSlackWorkspaceAuthorization = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/delete-slack-workspace-authorization", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DeleteSlackWorkspaceAuthorization" }, DeleteSlackWorkspaceAuthorizationRequest, DeleteSlackWorkspaceAuthorizationResult, [DeleteSlackWorkspaceAuthorizationFaultError, InvalidParameterExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const disassociateFromConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/disassociate-from-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DisassociateFromConfiguration" }, DisassociateFromConfigurationRequest, DisassociateFromConfigurationResult, [InternalServiceErrorError, InvalidRequestExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/list-tags-for-resource", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [InternalServiceErrorError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/untag-resource", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [InternalServiceErrorError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const associateToConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/associate-to-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.AssociateToConfiguration" }, AssociateToConfigurationRequest, AssociateToConfigurationResult, [InternalServiceErrorError, InvalidRequestExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteChimeWebhookConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/delete-chime-webhook-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DeleteChimeWebhookConfiguration" }, DeleteChimeWebhookConfigurationRequest, DeleteChimeWebhookConfigurationResult, [DeleteChimeWebhookConfigurationExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeSlackChannelConfigurations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/describe-slack-channel-configurations", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DescribeSlackChannelConfigurations" }, DescribeSlackChannelConfigurationsRequest, DescribeSlackChannelConfigurationsResult, [DescribeSlackChannelConfigurationsExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getAccountPreferences = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/get-account-preferences", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.GetAccountPreferences" }, GetAccountPreferencesRequest, GetAccountPreferencesResult, [GetAccountPreferencesExceptionError, InvalidRequestExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getMicrosoftTeamsChannelConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/get-ms-teams-channel-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.GetMicrosoftTeamsChannelConfiguration" }, GetTeamsChannelConfigurationRequest, GetTeamsChannelConfigurationResult, [GetTeamsChannelConfigurationExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAssociations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/list-associations", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.ListAssociations" }, ListAssociationsRequest, ListAssociationsResult, []), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listMicrosoftTeamsChannelConfigurations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/list-ms-teams-channel-configurations", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.ListMicrosoftTeamsChannelConfigurations" }, ListTeamsChannelConfigurationsRequest, ListTeamsChannelConfigurationsResult, [InvalidParameterExceptionError, InvalidRequestExceptionError, ListTeamsChannelConfigurationsExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/tag-resource", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.TagResource" }, TagResourceRequest, TagResourceResponse, [InternalServiceErrorError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, TooManyTagsExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAccountPreferences = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/update-account-preferences", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.UpdateAccountPreferences" }, UpdateAccountPreferencesRequest, UpdateAccountPreferencesResult, [InvalidParameterExceptionError, InvalidRequestExceptionError, UpdateAccountPreferencesExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateChimeWebhookConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/update-chime-webhook-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.UpdateChimeWebhookConfiguration" }, UpdateChimeWebhookConfigurationRequest, UpdateChimeWebhookConfigurationResult, [InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, UpdateChimeWebhookConfigurationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateMicrosoftTeamsChannelConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/update-ms-teams-channel-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.UpdateMicrosoftTeamsChannelConfiguration" }, UpdateTeamsChannelConfigurationRequest, UpdateTeamsChannelConfigurationResult, [InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, UpdateTeamsChannelConfigurationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateSlackChannelConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/update-slack-channel-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.UpdateSlackChannelConfiguration" }, UpdateSlackChannelConfigurationRequest, UpdateSlackChannelConfigurationResult, [InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, UpdateSlackChannelConfigurationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createSlackChannelConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/create-slack-channel-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.CreateSlackChannelConfiguration" }, CreateSlackChannelConfigurationRequest, CreateSlackChannelConfigurationResult, [ConflictExceptionError, CreateSlackChannelConfigurationExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeChimeWebhookConfigurations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/describe-chime-webhook-configurations", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DescribeChimeWebhookConfigurations" }, DescribeChimeWebhookConfigurationsRequest, DescribeChimeWebhookConfigurationsResult, [DescribeChimeWebhookConfigurationsExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeSlackUserIdentities = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/describe-slack-user-identities", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DescribeSlackUserIdentities" }, DescribeSlackUserIdentitiesRequest, DescribeSlackUserIdentitiesResult, [DescribeSlackUserIdentitiesExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeSlackWorkspaces = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/describe-slack-workspaces", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.DescribeSlackWorkspaces" }, DescribeSlackWorkspacesRequest, DescribeSlackWorkspacesResult, [DescribeSlackWorkspacesExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listMicrosoftTeamsConfiguredTeams = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/list-ms-teams-configured-teams", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.ListMicrosoftTeamsConfiguredTeams" }, ListMicrosoftTeamsConfiguredTeamsRequest, ListMicrosoftTeamsConfiguredTeamsResult, [InvalidParameterExceptionError, InvalidRequestExceptionError, ListMicrosoftTeamsConfiguredTeamsExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listMicrosoftTeamsUserIdentities = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/list-ms-teams-user-identities", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.ListMicrosoftTeamsUserIdentities" }, ListMicrosoftTeamsUserIdentitiesRequest, ListMicrosoftTeamsUserIdentitiesResult, [InvalidParameterExceptionError, InvalidRequestExceptionError, ListMicrosoftTeamsUserIdentitiesExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createChimeWebhookConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/create-chime-webhook-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.CreateChimeWebhookConfiguration" }, CreateChimeWebhookConfigurationRequest, CreateChimeWebhookConfigurationResult, [ConflictExceptionError, CreateChimeWebhookConfigurationExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createMicrosoftTeamsChannelConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-11", uri: "/create-ms-teams-channel-configuration", method: "POST", sdkId: "chatbot", sigV4ServiceName: "chatbot", name: "WheatleyOrchestration_20171011.CreateMicrosoftTeamsChannelConfiguration" }, CreateTeamsChannelConfigurationRequest, CreateTeamsChannelConfigurationResult, [ConflictExceptionError, CreateTeamsChannelConfigurationExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
