import * as S from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const TagKeyList = S.Array(S.String);
export class CreateAppInstanceAdminRequest extends S.Class<CreateAppInstanceAdminRequest>("CreateAppInstanceAdminRequest")({AppInstanceAdminArn: S.String, AppInstanceArn: S.String}) {}
export class DeleteAppInstanceRequest extends S.Class<DeleteAppInstanceRequest>("DeleteAppInstanceRequest")({AppInstanceArn: S.String}) {}
export class DeleteAppInstanceAdminRequest extends S.Class<DeleteAppInstanceAdminRequest>("DeleteAppInstanceAdminRequest")({AppInstanceAdminArn: S.String, AppInstanceArn: S.String}) {}
export class DeleteAppInstanceBotRequest extends S.Class<DeleteAppInstanceBotRequest>("DeleteAppInstanceBotRequest")({AppInstanceBotArn: S.String}) {}
export class DeleteAppInstanceUserRequest extends S.Class<DeleteAppInstanceUserRequest>("DeleteAppInstanceUserRequest")({AppInstanceUserArn: S.String}) {}
export class DeregisterAppInstanceUserEndpointRequest extends S.Class<DeregisterAppInstanceUserEndpointRequest>("DeregisterAppInstanceUserEndpointRequest")({AppInstanceUserArn: S.String, EndpointId: S.String}) {}
export class DescribeAppInstanceRequest extends S.Class<DescribeAppInstanceRequest>("DescribeAppInstanceRequest")({AppInstanceArn: S.String}) {}
export class DescribeAppInstanceAdminRequest extends S.Class<DescribeAppInstanceAdminRequest>("DescribeAppInstanceAdminRequest")({AppInstanceAdminArn: S.String, AppInstanceArn: S.String}) {}
export class DescribeAppInstanceBotRequest extends S.Class<DescribeAppInstanceBotRequest>("DescribeAppInstanceBotRequest")({AppInstanceBotArn: S.String}) {}
export class DescribeAppInstanceUserRequest extends S.Class<DescribeAppInstanceUserRequest>("DescribeAppInstanceUserRequest")({AppInstanceUserArn: S.String}) {}
export class DescribeAppInstanceUserEndpointRequest extends S.Class<DescribeAppInstanceUserEndpointRequest>("DescribeAppInstanceUserEndpointRequest")({AppInstanceUserArn: S.String, EndpointId: S.String}) {}
export class GetAppInstanceRetentionSettingsRequest extends S.Class<GetAppInstanceRetentionSettingsRequest>("GetAppInstanceRetentionSettingsRequest")({AppInstanceArn: S.String}) {}
export class ListAppInstanceAdminsRequest extends S.Class<ListAppInstanceAdminsRequest>("ListAppInstanceAdminsRequest")({AppInstanceArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListAppInstanceBotsRequest extends S.Class<ListAppInstanceBotsRequest>("ListAppInstanceBotsRequest")({AppInstanceArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListAppInstancesRequest extends S.Class<ListAppInstancesRequest>("ListAppInstancesRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListAppInstanceUserEndpointsRequest extends S.Class<ListAppInstanceUserEndpointsRequest>("ListAppInstanceUserEndpointsRequest")({AppInstanceUserArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListAppInstanceUsersRequest extends S.Class<ListAppInstanceUsersRequest>("ListAppInstanceUsersRequest")({AppInstanceArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceARN: S.String}) {}
export class ExpirationSettings extends S.Class<ExpirationSettings>("ExpirationSettings")({ExpirationDays: S.Number, ExpirationCriterion: S.String}) {}
export class PutAppInstanceUserExpirationSettingsRequest extends S.Class<PutAppInstanceUserExpirationSettingsRequest>("PutAppInstanceUserExpirationSettingsRequest")({AppInstanceUserArn: S.String, ExpirationSettings: S.optional(ExpirationSettings)}) {}
export class Tag extends S.Class<Tag>("Tag")({Key: S.String, Value: S.String}) {}
export const TagList = S.Array(Tag);
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceARN: S.String, Tags: TagList}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceARN: S.String, TagKeys: TagKeyList}) {}
export class UpdateAppInstanceRequest extends S.Class<UpdateAppInstanceRequest>("UpdateAppInstanceRequest")({AppInstanceArn: S.String, Name: S.String, Metadata: S.String}) {}
export class InvokedBy extends S.Class<InvokedBy>("InvokedBy")({StandardMessages: S.String, TargetedMessages: S.String}) {}
export class LexConfiguration extends S.Class<LexConfiguration>("LexConfiguration")({RespondsTo: S.optional(S.String), InvokedBy: S.optional(InvokedBy), LexBotAliasArn: S.String, LocaleId: S.String, WelcomeIntent: S.optional(S.String)}) {}
export class Configuration extends S.Class<Configuration>("Configuration")({Lex: LexConfiguration}) {}
export class UpdateAppInstanceBotRequest extends S.Class<UpdateAppInstanceBotRequest>("UpdateAppInstanceBotRequest")({AppInstanceBotArn: S.String, Name: S.String, Metadata: S.String, Configuration: S.optional(Configuration)}) {}
export class UpdateAppInstanceUserRequest extends S.Class<UpdateAppInstanceUserRequest>("UpdateAppInstanceUserRequest")({AppInstanceUserArn: S.String, Name: S.String, Metadata: S.String}) {}
export class UpdateAppInstanceUserEndpointRequest extends S.Class<UpdateAppInstanceUserEndpointRequest>("UpdateAppInstanceUserEndpointRequest")({AppInstanceUserArn: S.String, EndpointId: S.String, Name: S.optional(S.String), AllowMessages: S.optional(S.String)}) {}
export class EndpointAttributes extends S.Class<EndpointAttributes>("EndpointAttributes")({DeviceToken: S.String, VoipDeviceToken: S.optional(S.String)}) {}
export class CreateAppInstanceRequest extends S.Class<CreateAppInstanceRequest>("CreateAppInstanceRequest")({Name: S.String, Metadata: S.optional(S.String), ClientRequestToken: S.String, Tags: S.optional(TagList)}) {}
export class CreateAppInstanceUserRequest extends S.Class<CreateAppInstanceUserRequest>("CreateAppInstanceUserRequest")({AppInstanceArn: S.String, AppInstanceUserId: S.String, Name: S.String, Metadata: S.optional(S.String), ClientRequestToken: S.String, Tags: S.optional(TagList), ExpirationSettings: S.optional(ExpirationSettings)}) {}
export class BadRequestException extends S.Class<BadRequestException>("BadRequestException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ConflictException extends S.Class<ConflictException>("ConflictException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ForbiddenException extends S.Class<ForbiddenException>("ForbiddenException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ResourceLimitExceededException extends S.Class<ResourceLimitExceededException>("ResourceLimitExceededException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ServiceFailureException extends S.Class<ServiceFailureException>("ServiceFailureException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ChannelRetentionSettings extends S.Class<ChannelRetentionSettings>("ChannelRetentionSettings")({RetentionDays: S.optional(S.Number)}) {}
export class AppInstanceRetentionSettings extends S.Class<AppInstanceRetentionSettings>("AppInstanceRetentionSettings")({ChannelRetentionSettings: S.optional(ChannelRetentionSettings)}) {}
export class GetAppInstanceRetentionSettingsResponse extends S.Class<GetAppInstanceRetentionSettingsResponse>("GetAppInstanceRetentionSettingsResponse")({AppInstanceRetentionSettings: S.optional(AppInstanceRetentionSettings), InitiateDeletionTimestamp: S.optional(S.Date)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: S.optional(TagList)}) {}
export class PutAppInstanceUserExpirationSettingsResponse extends S.Class<PutAppInstanceUserExpirationSettingsResponse>("PutAppInstanceUserExpirationSettingsResponse")({AppInstanceUserArn: S.optional(S.String), ExpirationSettings: S.optional(ExpirationSettings)}) {}
export class RegisterAppInstanceUserEndpointRequest extends S.Class<RegisterAppInstanceUserEndpointRequest>("RegisterAppInstanceUserEndpointRequest")({AppInstanceUserArn: S.String, Name: S.optional(S.String), Type: S.String, ResourceArn: S.String, EndpointAttributes: EndpointAttributes, ClientRequestToken: S.String, AllowMessages: S.optional(S.String)}) {}
export class ServiceUnavailableException extends S.Class<ServiceUnavailableException>("ServiceUnavailableException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ThrottledClientException extends S.Class<ThrottledClientException>("ThrottledClientException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class UpdateAppInstanceResponse extends S.Class<UpdateAppInstanceResponse>("UpdateAppInstanceResponse")({AppInstanceArn: S.optional(S.String)}) {}
export class UpdateAppInstanceBotResponse extends S.Class<UpdateAppInstanceBotResponse>("UpdateAppInstanceBotResponse")({AppInstanceBotArn: S.optional(S.String)}) {}
export class UpdateAppInstanceUserResponse extends S.Class<UpdateAppInstanceUserResponse>("UpdateAppInstanceUserResponse")({AppInstanceUserArn: S.optional(S.String)}) {}
export class UpdateAppInstanceUserEndpointResponse extends S.Class<UpdateAppInstanceUserEndpointResponse>("UpdateAppInstanceUserEndpointResponse")({AppInstanceUserArn: S.optional(S.String), EndpointId: S.optional(S.String)}) {}
export class Identity extends S.Class<Identity>("Identity")({Arn: S.optional(S.String), Name: S.optional(S.String)}) {}
export class AppInstance extends S.Class<AppInstance>("AppInstance")({AppInstanceArn: S.optional(S.String), Name: S.optional(S.String), CreatedTimestamp: S.optional(S.Date), LastUpdatedTimestamp: S.optional(S.Date), Metadata: S.optional(S.String)}) {}
export class AppInstanceAdmin extends S.Class<AppInstanceAdmin>("AppInstanceAdmin")({Admin: S.optional(Identity), AppInstanceArn: S.optional(S.String), CreatedTimestamp: S.optional(S.Date)}) {}
export class AppInstanceBot extends S.Class<AppInstanceBot>("AppInstanceBot")({AppInstanceBotArn: S.optional(S.String), Name: S.optional(S.String), Configuration: S.optional(Configuration), CreatedTimestamp: S.optional(S.Date), LastUpdatedTimestamp: S.optional(S.Date), Metadata: S.optional(S.String)}) {}
export class AppInstanceUser extends S.Class<AppInstanceUser>("AppInstanceUser")({AppInstanceUserArn: S.optional(S.String), Name: S.optional(S.String), Metadata: S.optional(S.String), CreatedTimestamp: S.optional(S.Date), LastUpdatedTimestamp: S.optional(S.Date), ExpirationSettings: S.optional(ExpirationSettings)}) {}
export class AppInstanceAdminSummary extends S.Class<AppInstanceAdminSummary>("AppInstanceAdminSummary")({Admin: S.optional(Identity)}) {}
export const AppInstanceAdminList = S.Array(AppInstanceAdminSummary);
export class AppInstanceBotSummary extends S.Class<AppInstanceBotSummary>("AppInstanceBotSummary")({AppInstanceBotArn: S.optional(S.String), Name: S.optional(S.String), Metadata: S.optional(S.String)}) {}
export const AppInstanceBotList = S.Array(AppInstanceBotSummary);
export class AppInstanceSummary extends S.Class<AppInstanceSummary>("AppInstanceSummary")({AppInstanceArn: S.optional(S.String), Name: S.optional(S.String), Metadata: S.optional(S.String)}) {}
export const AppInstanceList = S.Array(AppInstanceSummary);
export class EndpointState extends S.Class<EndpointState>("EndpointState")({Status: S.String, StatusReason: S.optional(S.String)}) {}
export class AppInstanceUserEndpointSummary extends S.Class<AppInstanceUserEndpointSummary>("AppInstanceUserEndpointSummary")({AppInstanceUserArn: S.optional(S.String), EndpointId: S.optional(S.String), Name: S.optional(S.String), Type: S.optional(S.String), AllowMessages: S.optional(S.String), EndpointState: S.optional(EndpointState)}) {}
export const AppInstanceUserEndpointSummaryList = S.Array(AppInstanceUserEndpointSummary);
export class AppInstanceUserSummary extends S.Class<AppInstanceUserSummary>("AppInstanceUserSummary")({AppInstanceUserArn: S.optional(S.String), Name: S.optional(S.String), Metadata: S.optional(S.String)}) {}
export const AppInstanceUserList = S.Array(AppInstanceUserSummary);
export class CreateAppInstanceResponse extends S.Class<CreateAppInstanceResponse>("CreateAppInstanceResponse")({AppInstanceArn: S.optional(S.String)}) {}
export class CreateAppInstanceAdminResponse extends S.Class<CreateAppInstanceAdminResponse>("CreateAppInstanceAdminResponse")({AppInstanceAdmin: S.optional(Identity), AppInstanceArn: S.optional(S.String)}) {}
export class CreateAppInstanceUserResponse extends S.Class<CreateAppInstanceUserResponse>("CreateAppInstanceUserResponse")({AppInstanceUserArn: S.optional(S.String)}) {}
export class UnauthorizedClientException extends S.Class<UnauthorizedClientException>("UnauthorizedClientException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class DescribeAppInstanceResponse extends S.Class<DescribeAppInstanceResponse>("DescribeAppInstanceResponse")({AppInstance: S.optional(AppInstance)}) {}
export class DescribeAppInstanceAdminResponse extends S.Class<DescribeAppInstanceAdminResponse>("DescribeAppInstanceAdminResponse")({AppInstanceAdmin: S.optional(AppInstanceAdmin)}) {}
export class DescribeAppInstanceBotResponse extends S.Class<DescribeAppInstanceBotResponse>("DescribeAppInstanceBotResponse")({AppInstanceBot: S.optional(AppInstanceBot)}) {}
export class DescribeAppInstanceUserResponse extends S.Class<DescribeAppInstanceUserResponse>("DescribeAppInstanceUserResponse")({AppInstanceUser: S.optional(AppInstanceUser)}) {}
export class ListAppInstanceAdminsResponse extends S.Class<ListAppInstanceAdminsResponse>("ListAppInstanceAdminsResponse")({AppInstanceArn: S.optional(S.String), AppInstanceAdmins: S.optional(AppInstanceAdminList), NextToken: S.optional(S.String)}) {}
export class ListAppInstanceBotsResponse extends S.Class<ListAppInstanceBotsResponse>("ListAppInstanceBotsResponse")({AppInstanceArn: S.optional(S.String), AppInstanceBots: S.optional(AppInstanceBotList), NextToken: S.optional(S.String)}) {}
export class ListAppInstancesResponse extends S.Class<ListAppInstancesResponse>("ListAppInstancesResponse")({AppInstances: S.optional(AppInstanceList), NextToken: S.optional(S.String)}) {}
export class ListAppInstanceUserEndpointsResponse extends S.Class<ListAppInstanceUserEndpointsResponse>("ListAppInstanceUserEndpointsResponse")({AppInstanceUserEndpoints: S.optional(AppInstanceUserEndpointSummaryList), NextToken: S.optional(S.String)}) {}
export class ListAppInstanceUsersResponse extends S.Class<ListAppInstanceUsersResponse>("ListAppInstanceUsersResponse")({AppInstanceArn: S.optional(S.String), AppInstanceUsers: S.optional(AppInstanceUserList), NextToken: S.optional(S.String)}) {}
export class PutAppInstanceRetentionSettingsRequest extends S.Class<PutAppInstanceRetentionSettingsRequest>("PutAppInstanceRetentionSettingsRequest")({AppInstanceArn: S.String, AppInstanceRetentionSettings: AppInstanceRetentionSettings}) {}
export class RegisterAppInstanceUserEndpointResponse extends S.Class<RegisterAppInstanceUserEndpointResponse>("RegisterAppInstanceUserEndpointResponse")({AppInstanceUserArn: S.optional(S.String), EndpointId: S.optional(S.String)}) {}
export class AppInstanceUserEndpoint extends S.Class<AppInstanceUserEndpoint>("AppInstanceUserEndpoint")({AppInstanceUserArn: S.optional(S.String), EndpointId: S.optional(S.String), Name: S.optional(S.String), Type: S.optional(S.String), ResourceArn: S.optional(S.String), EndpointAttributes: S.optional(EndpointAttributes), CreatedTimestamp: S.optional(S.Date), LastUpdatedTimestamp: S.optional(S.Date), AllowMessages: S.optional(S.String), EndpointState: S.optional(EndpointState)}) {}
export class CreateAppInstanceBotRequest extends S.Class<CreateAppInstanceBotRequest>("CreateAppInstanceBotRequest")({AppInstanceArn: S.String, Name: S.optional(S.String), Metadata: S.optional(S.String), ClientRequestToken: S.String, Tags: S.optional(TagList), Configuration: Configuration}) {}
export class NotFoundException extends S.Class<NotFoundException>("NotFoundException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class DescribeAppInstanceUserEndpointResponse extends S.Class<DescribeAppInstanceUserEndpointResponse>("DescribeAppInstanceUserEndpointResponse")({AppInstanceUserEndpoint: S.optional(AppInstanceUserEndpoint)}) {}
export class PutAppInstanceRetentionSettingsResponse extends S.Class<PutAppInstanceRetentionSettingsResponse>("PutAppInstanceRetentionSettingsResponse")({AppInstanceRetentionSettings: S.optional(AppInstanceRetentionSettings), InitiateDeletionTimestamp: S.optional(S.Date)}) {}
export class CreateAppInstanceBotResponse extends S.Class<CreateAppInstanceBotResponse>("CreateAppInstanceBotResponse")({AppInstanceBotArn: S.optional(S.String)}) {}

//# Errors
export class BadRequestExceptionError extends S.TaggedError<BadRequestExceptionError>()("BadRequestException", BadRequestException.fields) {};
export class ConflictExceptionError extends S.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class ForbiddenExceptionError extends S.TaggedError<ForbiddenExceptionError>()("ForbiddenException", ForbiddenException.fields) {};
export class ResourceLimitExceededExceptionError extends S.TaggedError<ResourceLimitExceededExceptionError>()("ResourceLimitExceededException", ResourceLimitExceededException.fields) {};
export class ServiceFailureExceptionError extends S.TaggedError<ServiceFailureExceptionError>()("ServiceFailureException", ServiceFailureException.fields) {};
export class ServiceUnavailableExceptionError extends S.TaggedError<ServiceUnavailableExceptionError>()("ServiceUnavailableException", ServiceUnavailableException.fields) {};
export class ThrottledClientExceptionError extends S.TaggedError<ThrottledClientExceptionError>()("ThrottledClientException", ThrottledClientException.fields) {};
export class UnauthorizedClientExceptionError extends S.TaggedError<UnauthorizedClientExceptionError>()("UnauthorizedClientException", UnauthorizedClientException.fields) {};
export class NotFoundExceptionError extends S.TaggedError<NotFoundExceptionError>()("NotFoundException", NotFoundException.fields) {};

//# Operations
export const deleteAppInstanceAdmin = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances/{AppInstanceArn}/admins/{AppInstanceAdminArn}", method: "DELETE", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.DeleteAppInstanceAdmin" }, DeleteAppInstanceAdminRequest, S.Struct({}), [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAppInstanceBot = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-bots/{AppInstanceBotArn}", method: "DELETE", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.DeleteAppInstanceBot" }, DeleteAppInstanceBotRequest, S.Struct({}), [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAppInstanceUser = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users/{AppInstanceUserArn}", method: "DELETE", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.DeleteAppInstanceUser" }, DeleteAppInstanceUserRequest, S.Struct({}), [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deregisterAppInstanceUserEndpoint = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users/{AppInstanceUserArn}/endpoints/{EndpointId}", method: "DELETE", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.DeregisterAppInstanceUserEndpoint" }, DeregisterAppInstanceUserEndpointRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getAppInstanceRetentionSettings = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances/{AppInstanceArn}/retention-settings", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.GetAppInstanceRetentionSettings" }, GetAppInstanceRetentionSettingsRequest, GetAppInstanceRetentionSettingsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/tags", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putAppInstanceUserExpirationSettings = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users/{AppInstanceUserArn}/expiration-settings", method: "PUT", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.PutAppInstanceUserExpirationSettings" }, PutAppInstanceUserExpirationSettingsRequest, PutAppInstanceUserExpirationSettingsResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/tags?operation=tag-resource", method: "POST", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.TagResource" }, TagResourceRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/tags?operation=untag-resource", method: "POST", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.UntagResource" }, UntagResourceRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAppInstance = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances/{AppInstanceArn}", method: "PUT", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.UpdateAppInstance" }, UpdateAppInstanceRequest, UpdateAppInstanceResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAppInstanceBot = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-bots/{AppInstanceBotArn}", method: "PUT", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.UpdateAppInstanceBot" }, UpdateAppInstanceBotRequest, UpdateAppInstanceBotResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAppInstanceUser = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users/{AppInstanceUserArn}", method: "PUT", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.UpdateAppInstanceUser" }, UpdateAppInstanceUserRequest, UpdateAppInstanceUserResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAppInstanceUserEndpoint = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users/{AppInstanceUserArn}/endpoints/{EndpointId}", method: "PUT", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.UpdateAppInstanceUserEndpoint" }, UpdateAppInstanceUserEndpointRequest, UpdateAppInstanceUserEndpointResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createAppInstance = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances", method: "POST", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.CreateAppInstance" }, CreateAppInstanceRequest, CreateAppInstanceResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createAppInstanceAdmin = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances/{AppInstanceArn}/admins", method: "POST", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.CreateAppInstanceAdmin" }, CreateAppInstanceAdminRequest, CreateAppInstanceAdminResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createAppInstanceUser = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users", method: "POST", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.CreateAppInstanceUser" }, CreateAppInstanceUserRequest, CreateAppInstanceUserResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAppInstance = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances/{AppInstanceArn}", method: "DELETE", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.DeleteAppInstance" }, DeleteAppInstanceRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAppInstance = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances/{AppInstanceArn}", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.DescribeAppInstance" }, DescribeAppInstanceRequest, DescribeAppInstanceResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAppInstanceAdmin = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances/{AppInstanceArn}/admins/{AppInstanceAdminArn}", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.DescribeAppInstanceAdmin" }, DescribeAppInstanceAdminRequest, DescribeAppInstanceAdminResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAppInstanceUser = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users/{AppInstanceUserArn}", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.DescribeAppInstanceUser" }, DescribeAppInstanceUserRequest, DescribeAppInstanceUserResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppInstanceAdmins = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances/{AppInstanceArn}/admins", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.ListAppInstanceAdmins" }, ListAppInstanceAdminsRequest, ListAppInstanceAdminsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppInstanceBots = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-bots", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.ListAppInstanceBots" }, ListAppInstanceBotsRequest, ListAppInstanceBotsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppInstances = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.ListAppInstances" }, ListAppInstancesRequest, ListAppInstancesResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppInstanceUserEndpoints = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users/{AppInstanceUserArn}/endpoints", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.ListAppInstanceUserEndpoints" }, ListAppInstanceUserEndpointsRequest, ListAppInstanceUserEndpointsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppInstanceUsers = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.ListAppInstanceUsers" }, ListAppInstanceUsersRequest, ListAppInstanceUsersResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const registerAppInstanceUserEndpoint = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users/{AppInstanceUserArn}/endpoints", method: "POST", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.RegisterAppInstanceUserEndpoint" }, RegisterAppInstanceUserEndpointRequest, RegisterAppInstanceUserEndpointResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAppInstanceBot = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-bots/{AppInstanceBotArn}", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.DescribeAppInstanceBot" }, DescribeAppInstanceBotRequest, DescribeAppInstanceBotResponse, [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAppInstanceUserEndpoint = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-users/{AppInstanceUserArn}/endpoints/{EndpointId}", method: "GET", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.DescribeAppInstanceUserEndpoint" }, DescribeAppInstanceUserEndpointRequest, DescribeAppInstanceUserEndpointResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putAppInstanceRetentionSettings = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instances/{AppInstanceArn}/retention-settings", method: "PUT", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.PutAppInstanceRetentionSettings" }, PutAppInstanceRetentionSettingsRequest, PutAppInstanceRetentionSettingsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createAppInstanceBot = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-20", uri: "/app-instance-bots", method: "POST", sdkId: "Chime SDK Identity", sigV4ServiceName: "chime", name: "ChimeIdentityService.CreateAppInstanceBot" }, CreateAppInstanceBotRequest, CreateAppInstanceBotResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
