import * as S from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const MemberArns = S.Array(S.String);
export const ChannelMemberArns = S.Array(S.String);
export const ChannelModeratorArns = S.Array(S.String);
export const TagKeyList = S.Array(S.String);
export class AssociateChannelFlowRequest extends S.Class<AssociateChannelFlowRequest>("AssociateChannelFlowRequest")({ChannelArn: S.String, ChannelFlowArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class BatchCreateChannelMembershipRequest extends S.Class<BatchCreateChannelMembershipRequest>("BatchCreateChannelMembershipRequest")({ChannelArn: S.String, Type: S.optional(S.String), MemberArns: MemberArns, ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String)}) {}
export class CreateChannelBanRequest extends S.Class<CreateChannelBanRequest>("CreateChannelBanRequest")({ChannelArn: S.String, MemberArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class CreateChannelMembershipRequest extends S.Class<CreateChannelMembershipRequest>("CreateChannelMembershipRequest")({ChannelArn: S.String, MemberArn: S.String, Type: S.String, ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String)}) {}
export class CreateChannelModeratorRequest extends S.Class<CreateChannelModeratorRequest>("CreateChannelModeratorRequest")({ChannelArn: S.String, ChannelModeratorArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class DeleteChannelRequest extends S.Class<DeleteChannelRequest>("DeleteChannelRequest")({ChannelArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class DeleteChannelBanRequest extends S.Class<DeleteChannelBanRequest>("DeleteChannelBanRequest")({ChannelArn: S.String, MemberArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class DeleteChannelFlowRequest extends S.Class<DeleteChannelFlowRequest>("DeleteChannelFlowRequest")({ChannelFlowArn: S.String}) {}
export class DeleteChannelMembershipRequest extends S.Class<DeleteChannelMembershipRequest>("DeleteChannelMembershipRequest")({ChannelArn: S.String, MemberArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String)}) {}
export class DeleteChannelMessageRequest extends S.Class<DeleteChannelMessageRequest>("DeleteChannelMessageRequest")({ChannelArn: S.String, MessageId: S.String, ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String)}) {}
export class DeleteChannelModeratorRequest extends S.Class<DeleteChannelModeratorRequest>("DeleteChannelModeratorRequest")({ChannelArn: S.String, ChannelModeratorArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class DeleteMessagingStreamingConfigurationsRequest extends S.Class<DeleteMessagingStreamingConfigurationsRequest>("DeleteMessagingStreamingConfigurationsRequest")({AppInstanceArn: S.String}) {}
export class DescribeChannelRequest extends S.Class<DescribeChannelRequest>("DescribeChannelRequest")({ChannelArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class DescribeChannelBanRequest extends S.Class<DescribeChannelBanRequest>("DescribeChannelBanRequest")({ChannelArn: S.String, MemberArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class DescribeChannelFlowRequest extends S.Class<DescribeChannelFlowRequest>("DescribeChannelFlowRequest")({ChannelFlowArn: S.String}) {}
export class DescribeChannelMembershipRequest extends S.Class<DescribeChannelMembershipRequest>("DescribeChannelMembershipRequest")({ChannelArn: S.String, MemberArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String)}) {}
export class DescribeChannelMembershipForAppInstanceUserRequest extends S.Class<DescribeChannelMembershipForAppInstanceUserRequest>("DescribeChannelMembershipForAppInstanceUserRequest")({ChannelArn: S.String, AppInstanceUserArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class DescribeChannelModeratedByAppInstanceUserRequest extends S.Class<DescribeChannelModeratedByAppInstanceUserRequest>("DescribeChannelModeratedByAppInstanceUserRequest")({ChannelArn: S.String, AppInstanceUserArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class DescribeChannelModeratorRequest extends S.Class<DescribeChannelModeratorRequest>("DescribeChannelModeratorRequest")({ChannelArn: S.String, ChannelModeratorArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class DisassociateChannelFlowRequest extends S.Class<DisassociateChannelFlowRequest>("DisassociateChannelFlowRequest")({ChannelArn: S.String, ChannelFlowArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class GetChannelMembershipPreferencesRequest extends S.Class<GetChannelMembershipPreferencesRequest>("GetChannelMembershipPreferencesRequest")({ChannelArn: S.String, MemberArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class GetChannelMessageRequest extends S.Class<GetChannelMessageRequest>("GetChannelMessageRequest")({ChannelArn: S.String, MessageId: S.String, ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String)}) {}
export class GetChannelMessageStatusRequest extends S.Class<GetChannelMessageStatusRequest>("GetChannelMessageStatusRequest")({ChannelArn: S.String, MessageId: S.String, ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String)}) {}
export class GetMessagingSessionEndpointRequest extends S.Class<GetMessagingSessionEndpointRequest>("GetMessagingSessionEndpointRequest")({NetworkType: S.optional(S.String)}) {}
export class GetMessagingStreamingConfigurationsRequest extends S.Class<GetMessagingStreamingConfigurationsRequest>("GetMessagingStreamingConfigurationsRequest")({AppInstanceArn: S.String}) {}
export class ListChannelBansRequest extends S.Class<ListChannelBansRequest>("ListChannelBansRequest")({ChannelArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class ListChannelFlowsRequest extends S.Class<ListChannelFlowsRequest>("ListChannelFlowsRequest")({AppInstanceArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListChannelMembershipsRequest extends S.Class<ListChannelMembershipsRequest>("ListChannelMembershipsRequest")({ChannelArn: S.String, Type: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String)}) {}
export class ListChannelMembershipsForAppInstanceUserRequest extends S.Class<ListChannelMembershipsForAppInstanceUserRequest>("ListChannelMembershipsForAppInstanceUserRequest")({AppInstanceUserArn: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class ListChannelMessagesRequest extends S.Class<ListChannelMessagesRequest>("ListChannelMessagesRequest")({ChannelArn: S.String, SortOrder: S.optional(S.String), NotBefore: S.optional(S.Date), NotAfter: S.optional(S.Date), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String)}) {}
export class ListChannelModeratorsRequest extends S.Class<ListChannelModeratorsRequest>("ListChannelModeratorsRequest")({ChannelArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class ListChannelsRequest extends S.Class<ListChannelsRequest>("ListChannelsRequest")({AppInstanceArn: S.String, Privacy: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class ListChannelsAssociatedWithChannelFlowRequest extends S.Class<ListChannelsAssociatedWithChannelFlowRequest>("ListChannelsAssociatedWithChannelFlowRequest")({ChannelFlowArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListChannelsModeratedByAppInstanceUserRequest extends S.Class<ListChannelsModeratedByAppInstanceUserRequest>("ListChannelsModeratedByAppInstanceUserRequest")({AppInstanceUserArn: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class ListSubChannelsRequest extends S.Class<ListSubChannelsRequest>("ListSubChannelsRequest")({ChannelArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer"), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceARN: S.String}) {}
export class ExpirationSettings extends S.Class<ExpirationSettings>("ExpirationSettings")({ExpirationDays: S.Number, ExpirationCriterion: S.String}) {}
export class PutChannelExpirationSettingsRequest extends S.Class<PutChannelExpirationSettingsRequest>("PutChannelExpirationSettingsRequest")({ChannelArn: S.String, ChimeBearer: S.optional(H.Header("x-amz-chime-bearer")), ExpirationSettings: S.optional(ExpirationSettings)}) {}
export class RedactChannelMessageRequest extends S.Class<RedactChannelMessageRequest>("RedactChannelMessageRequest")({ChannelArn: S.String, MessageId: S.String, ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String)}) {}
export class Tag extends S.Class<Tag>("Tag")({Key: S.String, Value: S.String}) {}
export const TagList = S.Array(Tag);
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceARN: S.String, Tags: TagList}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceARN: S.String, TagKeys: TagKeyList}) {}
export class UpdateChannelRequest extends S.Class<UpdateChannelRequest>("UpdateChannelRequest")({ChannelArn: S.String, Name: S.optional(S.String), Mode: S.optional(S.String), Metadata: S.optional(S.String), ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export class LambdaConfiguration extends S.Class<LambdaConfiguration>("LambdaConfiguration")({ResourceArn: S.String, InvocationType: S.String}) {}
export class ProcessorConfiguration extends S.Class<ProcessorConfiguration>("ProcessorConfiguration")({Lambda: LambdaConfiguration}) {}
export class Processor extends S.Class<Processor>("Processor")({Name: S.String, Configuration: ProcessorConfiguration, ExecutionOrder: S.Number, FallbackAction: S.String}) {}
export const ProcessorList = S.Array(Processor);
export class UpdateChannelFlowRequest extends S.Class<UpdateChannelFlowRequest>("UpdateChannelFlowRequest")({ChannelFlowArn: S.String, Processors: ProcessorList, Name: S.String}) {}
export class UpdateChannelMessageRequest extends S.Class<UpdateChannelMessageRequest>("UpdateChannelMessageRequest")({ChannelArn: S.String, MessageId: S.String, Content: S.String, Metadata: S.optional(S.String), ChimeBearer: H.Header("x-amz-chime-bearer"), SubChannelId: S.optional(S.String), ContentType: S.optional(S.String)}) {}
export class UpdateChannelReadMarkerRequest extends S.Class<UpdateChannelReadMarkerRequest>("UpdateChannelReadMarkerRequest")({ChannelArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer")}) {}
export const SearchFieldValues = S.Array(S.String);
export class PushNotificationConfiguration extends S.Class<PushNotificationConfiguration>("PushNotificationConfiguration")({Title: S.optional(S.String), Body: S.optional(S.String), Type: S.optional(S.String)}) {}
export const MessageAttributeStringValues = S.Array(S.String);
export class MessageAttributeValue extends S.Class<MessageAttributeValue>("MessageAttributeValue")({StringValues: S.optional(MessageAttributeStringValues)}) {}
export const MessageAttributeMap = S.Record({key: S.String, value: MessageAttributeValue});
export class ChannelMessageCallback extends S.Class<ChannelMessageCallback>("ChannelMessageCallback")({MessageId: S.String, Content: S.optional(S.String), Metadata: S.optional(S.String), PushNotification: S.optional(PushNotificationConfiguration), MessageAttributes: S.optional(MessageAttributeMap), SubChannelId: S.optional(S.String), ContentType: S.optional(S.String)}) {}
export class ElasticChannelConfiguration extends S.Class<ElasticChannelConfiguration>("ElasticChannelConfiguration")({MaximumSubChannels: S.Number, TargetMembershipsPerSubChannel: S.Number, MinimumMembershipPercentage: S.Number}) {}
export class ChannelSummary extends S.Class<ChannelSummary>("ChannelSummary")({Name: S.optional(S.String), ChannelArn: S.optional(S.String), Mode: S.optional(S.String), Privacy: S.optional(S.String), Metadata: S.optional(S.String), LastMessageTimestamp: S.optional(S.Date)}) {}
export class AppInstanceUserMembershipSummary extends S.Class<AppInstanceUserMembershipSummary>("AppInstanceUserMembershipSummary")({Type: S.optional(S.String), ReadMarkerTimestamp: S.optional(S.Date), SubChannelId: S.optional(S.String)}) {}
export class ChannelMembershipForAppInstanceUserSummary extends S.Class<ChannelMembershipForAppInstanceUserSummary>("ChannelMembershipForAppInstanceUserSummary")({ChannelSummary: S.optional(ChannelSummary), AppInstanceUserMembershipSummary: S.optional(AppInstanceUserMembershipSummary)}) {}
export const ChannelMembershipForAppInstanceUserSummaryList = S.Array(ChannelMembershipForAppInstanceUserSummary);
export class ChannelModeratedByAppInstanceUserSummary extends S.Class<ChannelModeratedByAppInstanceUserSummary>("ChannelModeratedByAppInstanceUserSummary")({ChannelSummary: S.optional(ChannelSummary)}) {}
export const ChannelModeratedByAppInstanceUserSummaryList = S.Array(ChannelModeratedByAppInstanceUserSummary);
export class StreamingConfiguration extends S.Class<StreamingConfiguration>("StreamingConfiguration")({DataType: S.String, ResourceArn: S.String}) {}
export const StreamingConfigurationList = S.Array(StreamingConfiguration);
export class SearchField extends S.Class<SearchField>("SearchField")({Key: S.String, Values: SearchFieldValues, Operator: S.String}) {}
export const SearchFields = S.Array(SearchField);
export class Target extends S.Class<Target>("Target")({MemberArn: S.optional(S.String)}) {}
export const TargetList = S.Array(Target);
export class BadRequestException extends S.Class<BadRequestException>("BadRequestException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ChannelFlowCallbackRequest extends S.Class<ChannelFlowCallbackRequest>("ChannelFlowCallbackRequest")({CallbackId: S.String, ChannelArn: S.String, DeleteResource: S.optional(S.Boolean), ChannelMessage: ChannelMessageCallback}) {}
export class CreateChannelRequest extends S.Class<CreateChannelRequest>("CreateChannelRequest")({AppInstanceArn: S.String, Name: S.String, Mode: S.optional(S.String), Privacy: S.optional(S.String), Metadata: S.optional(S.String), ClientRequestToken: S.String, Tags: S.optional(TagList), ChimeBearer: H.Header("x-amz-chime-bearer"), ChannelId: S.optional(S.String), MemberArns: S.optional(ChannelMemberArns), ModeratorArns: S.optional(ChannelModeratorArns), ElasticChannelConfiguration: S.optional(ElasticChannelConfiguration), ExpirationSettings: S.optional(ExpirationSettings)}) {}
export class Identity extends S.Class<Identity>("Identity")({Arn: S.optional(S.String), Name: S.optional(S.String)}) {}
export class CreateChannelMembershipResponse extends S.Class<CreateChannelMembershipResponse>("CreateChannelMembershipResponse")({ChannelArn: S.optional(S.String), Member: S.optional(Identity), SubChannelId: S.optional(S.String)}) {}
export class CreateChannelModeratorResponse extends S.Class<CreateChannelModeratorResponse>("CreateChannelModeratorResponse")({ChannelArn: S.optional(S.String), ChannelModerator: S.optional(Identity)}) {}
export class ConflictException extends S.Class<ConflictException>("ConflictException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ForbiddenException extends S.Class<ForbiddenException>("ForbiddenException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ServiceFailureException extends S.Class<ServiceFailureException>("ServiceFailureException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ServiceUnavailableException extends S.Class<ServiceUnavailableException>("ServiceUnavailableException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ThrottledClientException extends S.Class<ThrottledClientException>("ThrottledClientException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class UnauthorizedClientException extends S.Class<UnauthorizedClientException>("UnauthorizedClientException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class NotFoundException extends S.Class<NotFoundException>("NotFoundException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class PushNotificationPreferences extends S.Class<PushNotificationPreferences>("PushNotificationPreferences")({AllowNotifications: S.String, FilterRule: S.optional(S.String)}) {}
export class ChannelMembershipPreferences extends S.Class<ChannelMembershipPreferences>("ChannelMembershipPreferences")({PushNotifications: S.optional(PushNotificationPreferences)}) {}
export class GetChannelMembershipPreferencesResponse extends S.Class<GetChannelMembershipPreferencesResponse>("GetChannelMembershipPreferencesResponse")({ChannelArn: S.optional(S.String), Member: S.optional(Identity), Preferences: S.optional(ChannelMembershipPreferences)}) {}
export class GetMessagingStreamingConfigurationsResponse extends S.Class<GetMessagingStreamingConfigurationsResponse>("GetMessagingStreamingConfigurationsResponse")({StreamingConfigurations: S.optional(StreamingConfigurationList)}) {}
export class ListChannelMembershipsForAppInstanceUserResponse extends S.Class<ListChannelMembershipsForAppInstanceUserResponse>("ListChannelMembershipsForAppInstanceUserResponse")({ChannelMemberships: S.optional(ChannelMembershipForAppInstanceUserSummaryList), NextToken: S.optional(S.String)}) {}
export class ListChannelsModeratedByAppInstanceUserResponse extends S.Class<ListChannelsModeratedByAppInstanceUserResponse>("ListChannelsModeratedByAppInstanceUserResponse")({Channels: S.optional(ChannelModeratedByAppInstanceUserSummaryList), NextToken: S.optional(S.String)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: S.optional(TagList)}) {}
export class PutChannelExpirationSettingsResponse extends S.Class<PutChannelExpirationSettingsResponse>("PutChannelExpirationSettingsResponse")({ChannelArn: S.optional(S.String), ExpirationSettings: S.optional(ExpirationSettings)}) {}
export class PutMessagingStreamingConfigurationsRequest extends S.Class<PutMessagingStreamingConfigurationsRequest>("PutMessagingStreamingConfigurationsRequest")({AppInstanceArn: S.String, StreamingConfigurations: StreamingConfigurationList}) {}
export class RedactChannelMessageResponse extends S.Class<RedactChannelMessageResponse>("RedactChannelMessageResponse")({ChannelArn: S.optional(S.String), MessageId: S.optional(S.String), SubChannelId: S.optional(S.String)}) {}
export class SearchChannelsRequest extends S.Class<SearchChannelsRequest>("SearchChannelsRequest")({ChimeBearer: S.optional(H.Header("x-amz-chime-bearer")), Fields: SearchFields, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ResourceLimitExceededException extends S.Class<ResourceLimitExceededException>("ResourceLimitExceededException")({Code: S.optional(S.String), Message: S.optional(S.String)}) {}
export class UpdateChannelResponse extends S.Class<UpdateChannelResponse>("UpdateChannelResponse")({ChannelArn: S.optional(S.String)}) {}
export class UpdateChannelFlowResponse extends S.Class<UpdateChannelFlowResponse>("UpdateChannelFlowResponse")({ChannelFlowArn: S.optional(S.String)}) {}
export class ChannelMessageStatusStructure extends S.Class<ChannelMessageStatusStructure>("ChannelMessageStatusStructure")({Value: S.optional(S.String), Detail: S.optional(S.String)}) {}
export class UpdateChannelMessageResponse extends S.Class<UpdateChannelMessageResponse>("UpdateChannelMessageResponse")({ChannelArn: S.optional(S.String), MessageId: S.optional(S.String), Status: S.optional(ChannelMessageStatusStructure), SubChannelId: S.optional(S.String)}) {}
export class UpdateChannelReadMarkerResponse extends S.Class<UpdateChannelReadMarkerResponse>("UpdateChannelReadMarkerResponse")({ChannelArn: S.optional(S.String)}) {}
export const Members = S.Array(Identity);
export class BatchChannelMemberships extends S.Class<BatchChannelMemberships>("BatchChannelMemberships")({InvitedBy: S.optional(Identity), Type: S.optional(S.String), Members: S.optional(Members), ChannelArn: S.optional(S.String), SubChannelId: S.optional(S.String)}) {}
export class BatchCreateChannelMembershipError extends S.Class<BatchCreateChannelMembershipError>("BatchCreateChannelMembershipError")({MemberArn: S.optional(S.String), ErrorCode: S.optional(S.String), ErrorMessage: S.optional(S.String)}) {}
export const BatchCreateChannelMembershipErrors = S.Array(BatchCreateChannelMembershipError);
export class Channel extends S.Class<Channel>("Channel")({Name: S.optional(S.String), ChannelArn: S.optional(S.String), Mode: S.optional(S.String), Privacy: S.optional(S.String), Metadata: S.optional(S.String), CreatedBy: S.optional(Identity), CreatedTimestamp: S.optional(S.Date), LastMessageTimestamp: S.optional(S.Date), LastUpdatedTimestamp: S.optional(S.Date), ChannelFlowArn: S.optional(S.String), ElasticChannelConfiguration: S.optional(ElasticChannelConfiguration), ExpirationSettings: S.optional(ExpirationSettings)}) {}
export class ChannelBan extends S.Class<ChannelBan>("ChannelBan")({Member: S.optional(Identity), ChannelArn: S.optional(S.String), CreatedTimestamp: S.optional(S.Date), CreatedBy: S.optional(Identity)}) {}
export class ChannelFlow extends S.Class<ChannelFlow>("ChannelFlow")({ChannelFlowArn: S.optional(S.String), Processors: S.optional(ProcessorList), Name: S.optional(S.String), CreatedTimestamp: S.optional(S.Date), LastUpdatedTimestamp: S.optional(S.Date)}) {}
export class ChannelMembership extends S.Class<ChannelMembership>("ChannelMembership")({InvitedBy: S.optional(Identity), Type: S.optional(S.String), Member: S.optional(Identity), ChannelArn: S.optional(S.String), CreatedTimestamp: S.optional(S.Date), LastUpdatedTimestamp: S.optional(S.Date), SubChannelId: S.optional(S.String)}) {}
export class ChannelModerator extends S.Class<ChannelModerator>("ChannelModerator")({Moderator: S.optional(Identity), ChannelArn: S.optional(S.String), CreatedTimestamp: S.optional(S.Date), CreatedBy: S.optional(Identity)}) {}
export class ChannelMessage extends S.Class<ChannelMessage>("ChannelMessage")({ChannelArn: S.optional(S.String), MessageId: S.optional(S.String), Content: S.optional(S.String), Metadata: S.optional(S.String), Type: S.optional(S.String), CreatedTimestamp: S.optional(S.Date), LastEditedTimestamp: S.optional(S.Date), LastUpdatedTimestamp: S.optional(S.Date), Sender: S.optional(Identity), Redacted: S.optional(S.Boolean), Persistence: S.optional(S.String), Status: S.optional(ChannelMessageStatusStructure), MessageAttributes: S.optional(MessageAttributeMap), SubChannelId: S.optional(S.String), ContentType: S.optional(S.String), Target: S.optional(TargetList)}) {}
export class MessagingSessionEndpoint extends S.Class<MessagingSessionEndpoint>("MessagingSessionEndpoint")({Url: S.optional(S.String)}) {}
export class ChannelBanSummary extends S.Class<ChannelBanSummary>("ChannelBanSummary")({Member: S.optional(Identity)}) {}
export const ChannelBanSummaryList = S.Array(ChannelBanSummary);
export class ChannelFlowSummary extends S.Class<ChannelFlowSummary>("ChannelFlowSummary")({ChannelFlowArn: S.optional(S.String), Name: S.optional(S.String), Processors: S.optional(ProcessorList)}) {}
export const ChannelFlowSummaryList = S.Array(ChannelFlowSummary);
export class ChannelMembershipSummary extends S.Class<ChannelMembershipSummary>("ChannelMembershipSummary")({Member: S.optional(Identity)}) {}
export const ChannelMembershipSummaryList = S.Array(ChannelMembershipSummary);
export class ChannelMessageSummary extends S.Class<ChannelMessageSummary>("ChannelMessageSummary")({MessageId: S.optional(S.String), Content: S.optional(S.String), Metadata: S.optional(S.String), Type: S.optional(S.String), CreatedTimestamp: S.optional(S.Date), LastUpdatedTimestamp: S.optional(S.Date), LastEditedTimestamp: S.optional(S.Date), Sender: S.optional(Identity), Redacted: S.optional(S.Boolean), Status: S.optional(ChannelMessageStatusStructure), MessageAttributes: S.optional(MessageAttributeMap), ContentType: S.optional(S.String), Target: S.optional(TargetList)}) {}
export const ChannelMessageSummaryList = S.Array(ChannelMessageSummary);
export class ChannelModeratorSummary extends S.Class<ChannelModeratorSummary>("ChannelModeratorSummary")({Moderator: S.optional(Identity)}) {}
export const ChannelModeratorSummaryList = S.Array(ChannelModeratorSummary);
export const ChannelSummaryList = S.Array(ChannelSummary);
export class ChannelAssociatedWithFlowSummary extends S.Class<ChannelAssociatedWithFlowSummary>("ChannelAssociatedWithFlowSummary")({Name: S.optional(S.String), ChannelArn: S.optional(S.String), Mode: S.optional(S.String), Privacy: S.optional(S.String), Metadata: S.optional(S.String)}) {}
export const ChannelAssociatedWithFlowSummaryList = S.Array(ChannelAssociatedWithFlowSummary);
export class SubChannelSummary extends S.Class<SubChannelSummary>("SubChannelSummary")({SubChannelId: S.optional(S.String), MembershipCount: S.optional(S.Number)}) {}
export const SubChannelSummaryList = S.Array(SubChannelSummary);
export class BatchCreateChannelMembershipResponse extends S.Class<BatchCreateChannelMembershipResponse>("BatchCreateChannelMembershipResponse")({BatchChannelMemberships: S.optional(BatchChannelMemberships), Errors: S.optional(BatchCreateChannelMembershipErrors)}) {}
export class ChannelFlowCallbackResponse extends S.Class<ChannelFlowCallbackResponse>("ChannelFlowCallbackResponse")({ChannelArn: S.optional(S.String), CallbackId: S.optional(S.String)}) {}
export class CreateChannelResponse extends S.Class<CreateChannelResponse>("CreateChannelResponse")({ChannelArn: S.optional(S.String)}) {}
export class CreateChannelBanResponse extends S.Class<CreateChannelBanResponse>("CreateChannelBanResponse")({ChannelArn: S.optional(S.String), Member: S.optional(Identity)}) {}
export class DescribeChannelResponse extends S.Class<DescribeChannelResponse>("DescribeChannelResponse")({Channel: S.optional(Channel)}) {}
export class DescribeChannelBanResponse extends S.Class<DescribeChannelBanResponse>("DescribeChannelBanResponse")({ChannelBan: S.optional(ChannelBan)}) {}
export class DescribeChannelFlowResponse extends S.Class<DescribeChannelFlowResponse>("DescribeChannelFlowResponse")({ChannelFlow: S.optional(ChannelFlow)}) {}
export class DescribeChannelMembershipResponse extends S.Class<DescribeChannelMembershipResponse>("DescribeChannelMembershipResponse")({ChannelMembership: S.optional(ChannelMembership)}) {}
export class DescribeChannelModeratedByAppInstanceUserResponse extends S.Class<DescribeChannelModeratedByAppInstanceUserResponse>("DescribeChannelModeratedByAppInstanceUserResponse")({Channel: S.optional(ChannelModeratedByAppInstanceUserSummary)}) {}
export class DescribeChannelModeratorResponse extends S.Class<DescribeChannelModeratorResponse>("DescribeChannelModeratorResponse")({ChannelModerator: S.optional(ChannelModerator)}) {}
export class GetChannelMessageResponse extends S.Class<GetChannelMessageResponse>("GetChannelMessageResponse")({ChannelMessage: S.optional(ChannelMessage)}) {}
export class GetChannelMessageStatusResponse extends S.Class<GetChannelMessageStatusResponse>("GetChannelMessageStatusResponse")({Status: S.optional(ChannelMessageStatusStructure)}) {}
export class GetMessagingSessionEndpointResponse extends S.Class<GetMessagingSessionEndpointResponse>("GetMessagingSessionEndpointResponse")({Endpoint: S.optional(MessagingSessionEndpoint)}) {}
export class ListChannelBansResponse extends S.Class<ListChannelBansResponse>("ListChannelBansResponse")({ChannelArn: S.optional(S.String), NextToken: S.optional(S.String), ChannelBans: S.optional(ChannelBanSummaryList)}) {}
export class ListChannelFlowsResponse extends S.Class<ListChannelFlowsResponse>("ListChannelFlowsResponse")({ChannelFlows: S.optional(ChannelFlowSummaryList), NextToken: S.optional(S.String)}) {}
export class ListChannelMembershipsResponse extends S.Class<ListChannelMembershipsResponse>("ListChannelMembershipsResponse")({ChannelArn: S.optional(S.String), ChannelMemberships: S.optional(ChannelMembershipSummaryList), NextToken: S.optional(S.String)}) {}
export class ListChannelMessagesResponse extends S.Class<ListChannelMessagesResponse>("ListChannelMessagesResponse")({ChannelArn: S.optional(S.String), NextToken: S.optional(S.String), ChannelMessages: S.optional(ChannelMessageSummaryList), SubChannelId: S.optional(S.String)}) {}
export class ListChannelModeratorsResponse extends S.Class<ListChannelModeratorsResponse>("ListChannelModeratorsResponse")({ChannelArn: S.optional(S.String), NextToken: S.optional(S.String), ChannelModerators: S.optional(ChannelModeratorSummaryList)}) {}
export class ListChannelsResponse extends S.Class<ListChannelsResponse>("ListChannelsResponse")({Channels: S.optional(ChannelSummaryList), NextToken: S.optional(S.String)}) {}
export class ListChannelsAssociatedWithChannelFlowResponse extends S.Class<ListChannelsAssociatedWithChannelFlowResponse>("ListChannelsAssociatedWithChannelFlowResponse")({Channels: S.optional(ChannelAssociatedWithFlowSummaryList), NextToken: S.optional(S.String)}) {}
export class ListSubChannelsResponse extends S.Class<ListSubChannelsResponse>("ListSubChannelsResponse")({ChannelArn: S.optional(S.String), SubChannels: S.optional(SubChannelSummaryList), NextToken: S.optional(S.String)}) {}
export class PutChannelMembershipPreferencesRequest extends S.Class<PutChannelMembershipPreferencesRequest>("PutChannelMembershipPreferencesRequest")({ChannelArn: S.String, MemberArn: S.String, ChimeBearer: H.Header("x-amz-chime-bearer"), Preferences: ChannelMembershipPreferences}) {}
export class PutMessagingStreamingConfigurationsResponse extends S.Class<PutMessagingStreamingConfigurationsResponse>("PutMessagingStreamingConfigurationsResponse")({StreamingConfigurations: S.optional(StreamingConfigurationList)}) {}
export class SearchChannelsResponse extends S.Class<SearchChannelsResponse>("SearchChannelsResponse")({Channels: S.optional(ChannelSummaryList), NextToken: S.optional(S.String)}) {}
export class SendChannelMessageRequest extends S.Class<SendChannelMessageRequest>("SendChannelMessageRequest")({ChannelArn: S.String, Content: S.String, Type: S.String, Persistence: S.String, Metadata: S.optional(S.String), ClientRequestToken: S.String, ChimeBearer: H.Header("x-amz-chime-bearer"), PushNotification: S.optional(PushNotificationConfiguration), MessageAttributes: S.optional(MessageAttributeMap), SubChannelId: S.optional(S.String), ContentType: S.optional(S.String), Target: S.optional(TargetList)}) {}
export class CreateChannelFlowRequest extends S.Class<CreateChannelFlowRequest>("CreateChannelFlowRequest")({AppInstanceArn: S.String, Processors: ProcessorList, Name: S.String, Tags: S.optional(TagList), ClientRequestToken: S.String}) {}
export class DescribeChannelMembershipForAppInstanceUserResponse extends S.Class<DescribeChannelMembershipForAppInstanceUserResponse>("DescribeChannelMembershipForAppInstanceUserResponse")({ChannelMembership: S.optional(ChannelMembershipForAppInstanceUserSummary)}) {}
export class PutChannelMembershipPreferencesResponse extends S.Class<PutChannelMembershipPreferencesResponse>("PutChannelMembershipPreferencesResponse")({ChannelArn: S.optional(S.String), Member: S.optional(Identity), Preferences: S.optional(ChannelMembershipPreferences)}) {}
export class SendChannelMessageResponse extends S.Class<SendChannelMessageResponse>("SendChannelMessageResponse")({ChannelArn: S.optional(S.String), MessageId: S.optional(S.String), Status: S.optional(ChannelMessageStatusStructure), SubChannelId: S.optional(S.String)}) {}
export class CreateChannelFlowResponse extends S.Class<CreateChannelFlowResponse>("CreateChannelFlowResponse")({ChannelFlowArn: S.optional(S.String)}) {}

//# Errors
export class BadRequestExceptionError extends S.TaggedError<BadRequestExceptionError>()("BadRequestException", BadRequestException.fields) {};
export class ConflictExceptionError extends S.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class ForbiddenExceptionError extends S.TaggedError<ForbiddenExceptionError>()("ForbiddenException", ForbiddenException.fields) {};
export class ServiceFailureExceptionError extends S.TaggedError<ServiceFailureExceptionError>()("ServiceFailureException", ServiceFailureException.fields) {};
export class ServiceUnavailableExceptionError extends S.TaggedError<ServiceUnavailableExceptionError>()("ServiceUnavailableException", ServiceUnavailableException.fields) {};
export class ThrottledClientExceptionError extends S.TaggedError<ThrottledClientExceptionError>()("ThrottledClientException", ThrottledClientException.fields) {};
export class UnauthorizedClientExceptionError extends S.TaggedError<UnauthorizedClientExceptionError>()("UnauthorizedClientException", UnauthorizedClientException.fields) {};
export class NotFoundExceptionError extends S.TaggedError<NotFoundExceptionError>()("NotFoundException", NotFoundException.fields) {};
export class ResourceLimitExceededExceptionError extends S.TaggedError<ResourceLimitExceededExceptionError>()("ResourceLimitExceededException", ResourceLimitExceededException.fields) {};

//# Operations
export const deleteMessagingStreamingConfigurations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/app-instances/{AppInstanceArn}/streaming-configurations", method: "DELETE", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DeleteMessagingStreamingConfigurations" }, DeleteMessagingStreamingConfigurationsRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/tags?operation=untag-resource", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.UntagResource" }, UntagResourceRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const associateChannelFlow = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/channel-flow", method: "PUT", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.AssociateChannelFlow" }, AssociateChannelFlowRequest, S.Struct({}), [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createChannelMembership = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/memberships", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.CreateChannelMembership" }, CreateChannelMembershipRequest, CreateChannelMembershipResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createChannelModerator = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/moderators", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.CreateChannelModerator" }, CreateChannelModeratorRequest, CreateChannelModeratorResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteChannel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}", method: "DELETE", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DeleteChannel" }, DeleteChannelRequest, S.Struct({}), [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteChannelBan = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/bans/{MemberArn}", method: "DELETE", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DeleteChannelBan" }, DeleteChannelBanRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteChannelFlow = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channel-flows/{ChannelFlowArn}", method: "DELETE", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DeleteChannelFlow" }, DeleteChannelFlowRequest, S.Struct({}), [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteChannelMembership = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/memberships/{MemberArn}", method: "DELETE", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DeleteChannelMembership" }, DeleteChannelMembershipRequest, S.Struct({}), [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteChannelMessage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/messages/{MessageId}", method: "DELETE", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DeleteChannelMessage" }, DeleteChannelMessageRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteChannelModerator = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/moderators/{ChannelModeratorArn}", method: "DELETE", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DeleteChannelModerator" }, DeleteChannelModeratorRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const disassociateChannelFlow = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/channel-flow/{ChannelFlowArn}", method: "DELETE", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DisassociateChannelFlow" }, DisassociateChannelFlowRequest, S.Struct({}), [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getChannelMembershipPreferences = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/memberships/{MemberArn}/preferences", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.GetChannelMembershipPreferences" }, GetChannelMembershipPreferencesRequest, GetChannelMembershipPreferencesResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getMessagingStreamingConfigurations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/app-instances/{AppInstanceArn}/streaming-configurations", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.GetMessagingStreamingConfigurations" }, GetMessagingStreamingConfigurationsRequest, GetMessagingStreamingConfigurationsResponse, [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listChannelMembershipsForAppInstanceUser = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels?scope=app-instance-user-memberships", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListChannelMembershipsForAppInstanceUser" }, ListChannelMembershipsForAppInstanceUserRequest, ListChannelMembershipsForAppInstanceUserResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listChannelsModeratedByAppInstanceUser = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels?scope=app-instance-user-moderated-channels", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListChannelsModeratedByAppInstanceUser" }, ListChannelsModeratedByAppInstanceUserRequest, ListChannelsModeratedByAppInstanceUserResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/tags", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putChannelExpirationSettings = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/expiration-settings", method: "PUT", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.PutChannelExpirationSettings" }, PutChannelExpirationSettingsRequest, PutChannelExpirationSettingsResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const redactChannelMessage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/messages/{MessageId}?operation=redact", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.RedactChannelMessage" }, RedactChannelMessageRequest, RedactChannelMessageResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/tags?operation=tag-resource", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.TagResource" }, TagResourceRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateChannel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}", method: "PUT", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.UpdateChannel" }, UpdateChannelRequest, UpdateChannelResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateChannelFlow = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channel-flows/{ChannelFlowArn}", method: "PUT", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.UpdateChannelFlow" }, UpdateChannelFlowRequest, UpdateChannelFlowResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateChannelMessage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/messages/{MessageId}", method: "PUT", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.UpdateChannelMessage" }, UpdateChannelMessageRequest, UpdateChannelMessageResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateChannelReadMarker = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/readMarker", method: "PUT", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.UpdateChannelReadMarker" }, UpdateChannelReadMarkerRequest, UpdateChannelReadMarkerResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const batchCreateChannelMembership = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/memberships?operation=batch-create", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.BatchCreateChannelMembership" }, BatchCreateChannelMembershipRequest, BatchCreateChannelMembershipResponse, [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const channelFlowCallback = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}?operation=channel-flow-callback", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ChannelFlowCallback" }, ChannelFlowCallbackRequest, ChannelFlowCallbackResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createChannel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.CreateChannel" }, CreateChannelRequest, CreateChannelResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createChannelBan = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/bans", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.CreateChannelBan" }, CreateChannelBanRequest, CreateChannelBanResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeChannel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DescribeChannel" }, DescribeChannelRequest, DescribeChannelResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeChannelBan = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/bans/{MemberArn}", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DescribeChannelBan" }, DescribeChannelBanRequest, DescribeChannelBanResponse, [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeChannelFlow = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channel-flows/{ChannelFlowArn}", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DescribeChannelFlow" }, DescribeChannelFlowRequest, DescribeChannelFlowResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeChannelMembership = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/memberships/{MemberArn}", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DescribeChannelMembership" }, DescribeChannelMembershipRequest, DescribeChannelMembershipResponse, [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeChannelModeratedByAppInstanceUser = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}?scope=app-instance-user-moderated-channel", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DescribeChannelModeratedByAppInstanceUser" }, DescribeChannelModeratedByAppInstanceUserRequest, DescribeChannelModeratedByAppInstanceUserResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeChannelModerator = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/moderators/{ChannelModeratorArn}", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DescribeChannelModerator" }, DescribeChannelModeratorRequest, DescribeChannelModeratorResponse, [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getChannelMessage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/messages/{MessageId}", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.GetChannelMessage" }, GetChannelMessageRequest, GetChannelMessageResponse, [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getChannelMessageStatus = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/messages/{MessageId}?scope=message-status", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.GetChannelMessageStatus" }, GetChannelMessageStatusRequest, GetChannelMessageStatusResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getMessagingSessionEndpoint = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/endpoints/messaging-session", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.GetMessagingSessionEndpoint" }, GetMessagingSessionEndpointRequest, GetMessagingSessionEndpointResponse, [ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listChannelBans = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/bans", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListChannelBans" }, ListChannelBansRequest, ListChannelBansResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listChannelFlows = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channel-flows", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListChannelFlows" }, ListChannelFlowsRequest, ListChannelFlowsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listChannelMemberships = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/memberships", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListChannelMemberships" }, ListChannelMembershipsRequest, ListChannelMembershipsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listChannelMessages = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/messages", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListChannelMessages" }, ListChannelMessagesRequest, ListChannelMessagesResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listChannelModerators = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/moderators", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListChannelModerators" }, ListChannelModeratorsRequest, ListChannelModeratorsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listChannels = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListChannels" }, ListChannelsRequest, ListChannelsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listChannelsAssociatedWithChannelFlow = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels?scope=channel-flow-associations", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListChannelsAssociatedWithChannelFlow" }, ListChannelsAssociatedWithChannelFlowRequest, ListChannelsAssociatedWithChannelFlowResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listSubChannels = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/subchannels", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.ListSubChannels" }, ListSubChannelsRequest, ListSubChannelsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putMessagingStreamingConfigurations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/app-instances/{AppInstanceArn}/streaming-configurations", method: "PUT", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.PutMessagingStreamingConfigurations" }, PutMessagingStreamingConfigurationsRequest, PutMessagingStreamingConfigurationsResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const searchChannels = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels?operation=search", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.SearchChannels" }, SearchChannelsRequest, SearchChannelsResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeChannelMembershipForAppInstanceUser = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}?scope=app-instance-user-membership", method: "GET", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.DescribeChannelMembershipForAppInstanceUser" }, DescribeChannelMembershipForAppInstanceUserRequest, DescribeChannelMembershipForAppInstanceUserResponse, [BadRequestExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putChannelMembershipPreferences = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/memberships/{MemberArn}/preferences", method: "PUT", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.PutChannelMembershipPreferences" }, PutChannelMembershipPreferencesRequest, PutChannelMembershipPreferencesResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const sendChannelMessage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channels/{ChannelArn}/messages", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.SendChannelMessage" }, SendChannelMessageRequest, SendChannelMessageResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createChannelFlow = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-05-15", uri: "/channel-flows", method: "POST", sdkId: "Chime SDK Messaging", sigV4ServiceName: "chime", name: "ChimeMessagingService.CreateChannelFlow" }, CreateChannelFlowRequest, CreateChannelFlowResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, ResourceLimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottledClientExceptionError, UnauthorizedClientExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
