import * as S from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const TenantIdList = S.Array(S.String);
export class AttendeeCapabilities extends S.Class<AttendeeCapabilities>("AttendeeCapabilities")({Audio: S.String, Video: S.String, Content: S.String}) {}
export class CreateAttendeeRequestItem extends S.Class<CreateAttendeeRequestItem>("CreateAttendeeRequestItem")({ExternalUserId: S.String, Capabilities: S.optional(AttendeeCapabilities)}) {}
export const CreateMeetingWithAttendeesRequestItemList = S.Array(CreateAttendeeRequestItem);
export const TagKeyList = S.Array(S.String);
export class CreateAttendeeRequest extends S.Class<CreateAttendeeRequest>("CreateAttendeeRequest")({MeetingId: S.String, ExternalUserId: S.String, Capabilities: S.optional(AttendeeCapabilities)}) {}
export class AudioFeatures extends S.Class<AudioFeatures>("AudioFeatures")({EchoReduction: S.optional(S.String)}) {}
export class VideoFeatures extends S.Class<VideoFeatures>("VideoFeatures")({MaxResolution: S.optional(S.String)}) {}
export class ContentFeatures extends S.Class<ContentFeatures>("ContentFeatures")({MaxResolution: S.optional(S.String)}) {}
export class AttendeeFeatures extends S.Class<AttendeeFeatures>("AttendeeFeatures")({MaxCount: S.optional(S.Number)}) {}
export class MeetingFeaturesConfiguration extends S.Class<MeetingFeaturesConfiguration>("MeetingFeaturesConfiguration")({Audio: S.optional(AudioFeatures), Video: S.optional(VideoFeatures), Content: S.optional(ContentFeatures), Attendee: S.optional(AttendeeFeatures)}) {}
export class NotificationsConfiguration extends S.Class<NotificationsConfiguration>("NotificationsConfiguration")({LambdaFunctionArn: S.optional(S.String), SnsTopicArn: S.optional(S.String), SqsQueueArn: S.optional(S.String)}) {}
export class Tag extends S.Class<Tag>("Tag")({Key: S.String, Value: S.String}) {}
export const TagList = S.Array(Tag);
export class CreateMeetingWithAttendeesRequest extends S.Class<CreateMeetingWithAttendeesRequest>("CreateMeetingWithAttendeesRequest")({ClientRequestToken: S.String, MediaRegion: S.String, MeetingHostId: S.optional(S.String), ExternalMeetingId: S.String, MeetingFeatures: S.optional(MeetingFeaturesConfiguration), NotificationsConfiguration: S.optional(NotificationsConfiguration), Attendees: CreateMeetingWithAttendeesRequestItemList, PrimaryMeetingId: S.optional(S.String), TenantIds: S.optional(TenantIdList), Tags: S.optional(TagList), MediaPlacementNetworkType: S.optional(S.String)}) {}
export class DeleteAttendeeRequest extends S.Class<DeleteAttendeeRequest>("DeleteAttendeeRequest")({MeetingId: S.String, AttendeeId: S.String}) {}
export class DeleteMeetingRequest extends S.Class<DeleteMeetingRequest>("DeleteMeetingRequest")({MeetingId: S.String}) {}
export class GetAttendeeRequest extends S.Class<GetAttendeeRequest>("GetAttendeeRequest")({MeetingId: S.String, AttendeeId: S.String}) {}
export class GetMeetingRequest extends S.Class<GetMeetingRequest>("GetMeetingRequest")({MeetingId: S.String}) {}
export class ListAttendeesRequest extends S.Class<ListAttendeesRequest>("ListAttendeesRequest")({MeetingId: S.String, NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceARN: S.String}) {}
export class StopMeetingTranscriptionRequest extends S.Class<StopMeetingTranscriptionRequest>("StopMeetingTranscriptionRequest")({MeetingId: S.String}) {}
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceARN: S.String, Tags: TagList}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceARN: S.String, TagKeys: TagKeyList}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class UpdateAttendeeCapabilitiesRequest extends S.Class<UpdateAttendeeCapabilitiesRequest>("UpdateAttendeeCapabilitiesRequest")({MeetingId: S.String, AttendeeId: S.String, Capabilities: AttendeeCapabilities}) {}
export const CreateAttendeeRequestItemList = S.Array(CreateAttendeeRequestItem);
export class AttendeeIdItem extends S.Class<AttendeeIdItem>("AttendeeIdItem")({AttendeeId: S.String}) {}
export const AttendeeIdsList = S.Array(AttendeeIdItem);
export class Attendee extends S.Class<Attendee>("Attendee")({ExternalUserId: S.optional(S.String), AttendeeId: S.optional(S.String), JoinToken: S.optional(S.String), Capabilities: S.optional(AttendeeCapabilities)}) {}
export const AttendeeList = S.Array(Attendee);
export class BatchCreateAttendeeRequest extends S.Class<BatchCreateAttendeeRequest>("BatchCreateAttendeeRequest")({MeetingId: S.String, Attendees: CreateAttendeeRequestItemList}) {}
export class BatchUpdateAttendeeCapabilitiesExceptRequest extends S.Class<BatchUpdateAttendeeCapabilitiesExceptRequest>("BatchUpdateAttendeeCapabilitiesExceptRequest")({MeetingId: S.String, ExcludedAttendeeIds: AttendeeIdsList, Capabilities: AttendeeCapabilities}) {}
export class BadRequestException extends S.Class<BadRequestException>("BadRequestException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String)}) {}
export class ForbiddenException extends S.Class<ForbiddenException>("ForbiddenException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String)}) {}
export class GetAttendeeResponse extends S.Class<GetAttendeeResponse>("GetAttendeeResponse")({Attendee: S.optional(Attendee)}) {}
export class MediaPlacement extends S.Class<MediaPlacement>("MediaPlacement")({AudioHostUrl: S.optional(S.String), AudioFallbackUrl: S.optional(S.String), SignalingUrl: S.optional(S.String), TurnControlUrl: S.optional(S.String), ScreenDataUrl: S.optional(S.String), ScreenViewingUrl: S.optional(S.String), ScreenSharingUrl: S.optional(S.String), EventIngestionUrl: S.optional(S.String)}) {}
export class Meeting extends S.Class<Meeting>("Meeting")({MeetingId: S.optional(S.String), MeetingHostId: S.optional(S.String), ExternalMeetingId: S.optional(S.String), MediaRegion: S.optional(S.String), MediaPlacement: S.optional(MediaPlacement), MeetingFeatures: S.optional(MeetingFeaturesConfiguration), PrimaryMeetingId: S.optional(S.String), TenantIds: S.optional(TenantIdList), MeetingArn: S.optional(S.String)}) {}
export class GetMeetingResponse extends S.Class<GetMeetingResponse>("GetMeetingResponse")({Meeting: S.optional(Meeting)}) {}
export class ListAttendeesResponse extends S.Class<ListAttendeesResponse>("ListAttendeesResponse")({Attendees: S.optional(AttendeeList), NextToken: S.optional(S.String)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: S.optional(TagList)}) {}
export class NotFoundException extends S.Class<NotFoundException>("NotFoundException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String)}) {}
export class LimitExceededException extends S.Class<LimitExceededException>("LimitExceededException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String)}) {}
export class ResourceNotFoundException extends S.Class<ResourceNotFoundException>("ResourceNotFoundException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String), ResourceName: S.optional(S.String)}) {}
export class UpdateAttendeeCapabilitiesResponse extends S.Class<UpdateAttendeeCapabilitiesResponse>("UpdateAttendeeCapabilitiesResponse")({Attendee: S.optional(Attendee)}) {}
export class EngineTranscribeSettings extends S.Class<EngineTranscribeSettings>("EngineTranscribeSettings")({LanguageCode: S.optional(S.String), VocabularyFilterMethod: S.optional(S.String), VocabularyFilterName: S.optional(S.String), VocabularyName: S.optional(S.String), Region: S.optional(S.String), EnablePartialResultsStabilization: S.optional(S.Boolean), PartialResultsStability: S.optional(S.String), ContentIdentificationType: S.optional(S.String), ContentRedactionType: S.optional(S.String), PiiEntityTypes: S.optional(S.String), LanguageModelName: S.optional(S.String), IdentifyLanguage: S.optional(S.Boolean), LanguageOptions: S.optional(S.String), PreferredLanguage: S.optional(S.String), VocabularyNames: S.optional(S.String), VocabularyFilterNames: S.optional(S.String)}) {}
export class EngineTranscribeMedicalSettings extends S.Class<EngineTranscribeMedicalSettings>("EngineTranscribeMedicalSettings")({LanguageCode: S.String, Specialty: S.String, Type: S.String, VocabularyName: S.optional(S.String), Region: S.optional(S.String), ContentIdentificationType: S.optional(S.String)}) {}
export class CreateAttendeeError extends S.Class<CreateAttendeeError>("CreateAttendeeError")({ExternalUserId: S.optional(S.String), ErrorCode: S.optional(S.String), ErrorMessage: S.optional(S.String)}) {}
export const BatchCreateAttendeeErrorList = S.Array(CreateAttendeeError);
export class TranscriptionConfiguration extends S.Class<TranscriptionConfiguration>("TranscriptionConfiguration")({EngineTranscribeSettings: S.optional(EngineTranscribeSettings), EngineTranscribeMedicalSettings: S.optional(EngineTranscribeMedicalSettings)}) {}
export class BatchCreateAttendeeResponse extends S.Class<BatchCreateAttendeeResponse>("BatchCreateAttendeeResponse")({Attendees: S.optional(AttendeeList), Errors: S.optional(BatchCreateAttendeeErrorList)}) {}
export class ConflictException extends S.Class<ConflictException>("ConflictException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String)}) {}
export class CreateAttendeeResponse extends S.Class<CreateAttendeeResponse>("CreateAttendeeResponse")({Attendee: S.optional(Attendee)}) {}
export class CreateMeetingRequest extends S.Class<CreateMeetingRequest>("CreateMeetingRequest")({ClientRequestToken: S.String, MediaRegion: S.String, MeetingHostId: S.optional(S.String), ExternalMeetingId: S.String, NotificationsConfiguration: S.optional(NotificationsConfiguration), MeetingFeatures: S.optional(MeetingFeaturesConfiguration), PrimaryMeetingId: S.optional(S.String), TenantIds: S.optional(TenantIdList), Tags: S.optional(TagList), MediaPlacementNetworkType: S.optional(S.String)}) {}
export class ServiceFailureException extends S.Class<ServiceFailureException>("ServiceFailureException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String)}) {}
export class ServiceUnavailableException extends S.Class<ServiceUnavailableException>("ServiceUnavailableException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String), RetryAfterSeconds: S.optional(H.Header("Retry-After"))}) {}
export class ThrottlingException extends S.Class<ThrottlingException>("ThrottlingException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String)}) {}
export class UnauthorizedException extends S.Class<UnauthorizedException>("UnauthorizedException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String)}) {}
export class StartMeetingTranscriptionRequest extends S.Class<StartMeetingTranscriptionRequest>("StartMeetingTranscriptionRequest")({MeetingId: S.String, TranscriptionConfiguration: TranscriptionConfiguration}) {}
export class UnprocessableEntityException extends S.Class<UnprocessableEntityException>("UnprocessableEntityException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String)}) {}
export class TooManyTagsException extends S.Class<TooManyTagsException>("TooManyTagsException")({Code: S.optional(S.String), Message: S.optional(S.String), RequestId: S.optional(S.String), ResourceName: S.optional(S.String)}) {}
export class CreateMeetingResponse extends S.Class<CreateMeetingResponse>("CreateMeetingResponse")({Meeting: S.optional(Meeting)}) {}
export class CreateMeetingWithAttendeesResponse extends S.Class<CreateMeetingWithAttendeesResponse>("CreateMeetingWithAttendeesResponse")({Meeting: S.optional(Meeting), Attendees: S.optional(AttendeeList), Errors: S.optional(BatchCreateAttendeeErrorList)}) {}

//# Errors
export class BadRequestExceptionError extends S.TaggedError<BadRequestExceptionError>()("BadRequestException", BadRequestException.fields) {};
export class ForbiddenExceptionError extends S.TaggedError<ForbiddenExceptionError>()("ForbiddenException", ForbiddenException.fields) {};
export class LimitExceededExceptionError extends S.TaggedError<LimitExceededExceptionError>()("LimitExceededException", LimitExceededException.fields) {};
export class NotFoundExceptionError extends S.TaggedError<NotFoundExceptionError>()("NotFoundException", NotFoundException.fields) {};
export class ServiceFailureExceptionError extends S.TaggedError<ServiceFailureExceptionError>()("ServiceFailureException", ServiceFailureException.fields) {};
export class ServiceUnavailableExceptionError extends S.TaggedError<ServiceUnavailableExceptionError>()("ServiceUnavailableException", ServiceUnavailableException.fields) {};
export class ThrottlingExceptionError extends S.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class UnauthorizedExceptionError extends S.TaggedError<UnauthorizedExceptionError>()("UnauthorizedException", UnauthorizedException.fields) {};
export class ResourceNotFoundExceptionError extends S.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ConflictExceptionError extends S.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class UnprocessableEntityExceptionError extends S.TaggedError<UnprocessableEntityExceptionError>()("UnprocessableEntityException", UnprocessableEntityException.fields) {};
export class TooManyTagsExceptionError extends S.TaggedError<TooManyTagsExceptionError>()("TooManyTagsException", TooManyTagsException.fields) {};

//# Operations
export const listAttendees = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}/attendees", method: "GET", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.ListAttendees" }, ListAttendeesRequest, ListAttendeesResponse, [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/tags", method: "GET", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [BadRequestExceptionError, ForbiddenExceptionError, LimitExceededExceptionError, ResourceNotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/tags?operation=untag-resource", method: "POST", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [BadRequestExceptionError, ForbiddenExceptionError, LimitExceededExceptionError, ResourceNotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAttendeeCapabilities = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}/attendees/{AttendeeId}/capabilities", method: "PUT", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.UpdateAttendeeCapabilities" }, UpdateAttendeeCapabilitiesRequest, UpdateAttendeeCapabilitiesResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const batchCreateAttendee = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}/attendees?operation=batch-create", method: "POST", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.BatchCreateAttendee" }, BatchCreateAttendeeRequest, BatchCreateAttendeeResponse, [BadRequestExceptionError, ForbiddenExceptionError, LimitExceededExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError, UnprocessableEntityExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const batchUpdateAttendeeCapabilitiesExcept = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}/attendees/capabilities?operation=batch-update-except", method: "PUT", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.BatchUpdateAttendeeCapabilitiesExcept" }, BatchUpdateAttendeeCapabilitiesExceptRequest, S.Struct({}), [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createAttendee = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}/attendees", method: "POST", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.CreateAttendee" }, CreateAttendeeRequest, CreateAttendeeResponse, [BadRequestExceptionError, ForbiddenExceptionError, LimitExceededExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError, UnprocessableEntityExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAttendee = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}/attendees/{AttendeeId}", method: "DELETE", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.DeleteAttendee" }, DeleteAttendeeRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteMeeting = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}", method: "DELETE", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.DeleteMeeting" }, DeleteMeetingRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getAttendee = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}/attendees/{AttendeeId}", method: "GET", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.GetAttendee" }, GetAttendeeRequest, GetAttendeeResponse, [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getMeeting = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}", method: "GET", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.GetMeeting" }, GetMeetingRequest, GetMeetingResponse, [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const startMeetingTranscription = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}/transcription?operation=start", method: "POST", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.StartMeetingTranscription" }, StartMeetingTranscriptionRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, LimitExceededExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError, UnprocessableEntityExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const stopMeetingTranscription = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings/{MeetingId}/transcription?operation=stop", method: "POST", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.StopMeetingTranscription" }, StopMeetingTranscriptionRequest, S.Struct({}), [BadRequestExceptionError, ForbiddenExceptionError, NotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError, UnprocessableEntityExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/tags?operation=tag-resource", method: "POST", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.TagResource" }, TagResourceRequest, TagResourceResponse, [BadRequestExceptionError, ForbiddenExceptionError, LimitExceededExceptionError, ResourceNotFoundExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, TooManyTagsExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createMeeting = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings", method: "POST", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.CreateMeeting" }, CreateMeetingRequest, CreateMeetingResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, LimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createMeetingWithAttendees = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-07-15", uri: "/meetings?operation=create-attendees", method: "POST", sdkId: "Chime SDK Meetings", sigV4ServiceName: "chime", name: "ChimeMeetingsSDKService.CreateMeetingWithAttendees" }, CreateMeetingWithAttendeesRequest, CreateMeetingWithAttendeesResponse, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, LimitExceededExceptionError, ServiceFailureExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnauthorizedExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
