import * as S from "effect/Schema"
import { FormatAwsJSON10Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export class CancelResourceRequestInput extends S.Class<CancelResourceRequestInput>("CancelResourceRequestInput")({RequestToken: S.String}) {}
export class CreateResourceInput extends S.Class<CreateResourceInput>("CreateResourceInput")({TypeName: S.String, TypeVersionId: S.optional(S.String), RoleArn: S.optional(S.String), ClientToken: S.optional(S.String), DesiredState: S.String}) {}
export class DeleteResourceInput extends S.Class<DeleteResourceInput>("DeleteResourceInput")({TypeName: S.String, TypeVersionId: S.optional(S.String), RoleArn: S.optional(S.String), ClientToken: S.optional(S.String), Identifier: S.String}) {}
export class GetResourceInput extends S.Class<GetResourceInput>("GetResourceInput")({TypeName: S.String, TypeVersionId: S.optional(S.String), RoleArn: S.optional(S.String), Identifier: S.String}) {}
export class GetResourceRequestStatusInput extends S.Class<GetResourceRequestStatusInput>("GetResourceRequestStatusInput")({RequestToken: S.String}) {}
export class ListResourcesInput extends S.Class<ListResourcesInput>("ListResourcesInput")({TypeName: S.String, TypeVersionId: S.optional(S.String), RoleArn: S.optional(S.String), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), ResourceModel: S.optional(S.String)}) {}
export class UpdateResourceInput extends S.Class<UpdateResourceInput>("UpdateResourceInput")({TypeName: S.String, TypeVersionId: S.optional(S.String), RoleArn: S.optional(S.String), ClientToken: S.optional(S.String), Identifier: S.String, PatchDocument: S.String}) {}
export const Operations = S.Array(S.String);
export const OperationStatuses = S.Array(S.String);
export class ResourceRequestStatusFilter extends S.Class<ResourceRequestStatusFilter>("ResourceRequestStatusFilter")({Operations: S.optional(Operations), OperationStatuses: S.optional(OperationStatuses)}) {}
export class ResourceDescription extends S.Class<ResourceDescription>("ResourceDescription")({Identifier: S.optional(S.String), Properties: S.optional(S.String)}) {}
export const ResourceDescriptions = S.Array(ResourceDescription);
export class ProgressEvent extends S.Class<ProgressEvent>("ProgressEvent")({TypeName: S.optional(S.String), Identifier: S.optional(S.String), RequestToken: S.optional(S.String), HooksRequestToken: S.optional(S.String), Operation: S.optional(S.String), OperationStatus: S.optional(S.String), EventTime: S.optional(S.Date), ResourceModel: S.optional(S.String), StatusMessage: S.optional(S.String), ErrorCode: S.optional(S.String), RetryAfter: S.optional(S.Date)}) {}
export class CreateResourceOutput extends S.Class<CreateResourceOutput>("CreateResourceOutput")({ProgressEvent: S.optional(ProgressEvent)}) {}
export class DeleteResourceOutput extends S.Class<DeleteResourceOutput>("DeleteResourceOutput")({ProgressEvent: S.optional(ProgressEvent)}) {}
export class ListResourceRequestsInput extends S.Class<ListResourceRequestsInput>("ListResourceRequestsInput")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), ResourceRequestStatusFilter: S.optional(ResourceRequestStatusFilter)}) {}
export class ListResourcesOutput extends S.Class<ListResourcesOutput>("ListResourcesOutput")({TypeName: S.optional(S.String), ResourceDescriptions: S.optional(ResourceDescriptions), NextToken: S.optional(S.String)}) {}
export class UpdateResourceOutput extends S.Class<UpdateResourceOutput>("UpdateResourceOutput")({ProgressEvent: S.optional(ProgressEvent)}) {}
export class HookProgressEvent extends S.Class<HookProgressEvent>("HookProgressEvent")({HookTypeName: S.optional(S.String), HookTypeVersionId: S.optional(S.String), HookTypeArn: S.optional(S.String), InvocationPoint: S.optional(S.String), HookStatus: S.optional(S.String), HookEventTime: S.optional(S.Date), HookStatusMessage: S.optional(S.String), FailureMode: S.optional(S.String)}) {}
export const HooksProgressEvent = S.Array(HookProgressEvent);
export const ResourceRequestStatusSummaries = S.Array(ProgressEvent);
export class CancelResourceRequestOutput extends S.Class<CancelResourceRequestOutput>("CancelResourceRequestOutput")({ProgressEvent: S.optional(ProgressEvent)}) {}
export class AlreadyExistsException extends S.Class<AlreadyExistsException>("AlreadyExistsException")({Message: S.optional(S.String)}) {}
export class ClientTokenConflictException extends S.Class<ClientTokenConflictException>("ClientTokenConflictException")({Message: S.optional(S.String)}) {}
export class GetResourceOutput extends S.Class<GetResourceOutput>("GetResourceOutput")({TypeName: S.optional(S.String), ResourceDescription: S.optional(ResourceDescription)}) {}
export class GetResourceRequestStatusOutput extends S.Class<GetResourceRequestStatusOutput>("GetResourceRequestStatusOutput")({ProgressEvent: S.optional(ProgressEvent), HooksProgressEvent: S.optional(HooksProgressEvent)}) {}
export class ListResourceRequestsOutput extends S.Class<ListResourceRequestsOutput>("ListResourceRequestsOutput")({ResourceRequestStatusSummaries: S.optional(ResourceRequestStatusSummaries), NextToken: S.optional(S.String)}) {}
export class GeneralServiceException extends S.Class<GeneralServiceException>("GeneralServiceException")({Message: S.optional(S.String)}) {}
export class ConcurrentOperationException extends S.Class<ConcurrentOperationException>("ConcurrentOperationException")({Message: S.optional(S.String)}) {}
export class ConcurrentModificationException extends S.Class<ConcurrentModificationException>("ConcurrentModificationException")({Message: S.optional(S.String)}) {}
export class HandlerFailureException extends S.Class<HandlerFailureException>("HandlerFailureException")({Message: S.optional(S.String)}) {}
export class HandlerInternalFailureException extends S.Class<HandlerInternalFailureException>("HandlerInternalFailureException")({Message: S.optional(S.String)}) {}
export class InvalidCredentialsException extends S.Class<InvalidCredentialsException>("InvalidCredentialsException")({Message: S.optional(S.String)}) {}
export class RequestTokenNotFoundException extends S.Class<RequestTokenNotFoundException>("RequestTokenNotFoundException")({Message: S.optional(S.String)}) {}
export class InvalidRequestException extends S.Class<InvalidRequestException>("InvalidRequestException")({Message: S.optional(S.String)}) {}
export class NetworkFailureException extends S.Class<NetworkFailureException>("NetworkFailureException")({Message: S.optional(S.String)}) {}
export class NotStabilizedException extends S.Class<NotStabilizedException>("NotStabilizedException")({Message: S.optional(S.String)}) {}
export class NotUpdatableException extends S.Class<NotUpdatableException>("NotUpdatableException")({Message: S.optional(S.String)}) {}
export class PrivateTypeException extends S.Class<PrivateTypeException>("PrivateTypeException")({Message: S.optional(S.String)}) {}
export class ResourceConflictException extends S.Class<ResourceConflictException>("ResourceConflictException")({Message: S.optional(S.String)}) {}
export class ResourceNotFoundException extends S.Class<ResourceNotFoundException>("ResourceNotFoundException")({Message: S.optional(S.String)}) {}
export class ServiceInternalErrorException extends S.Class<ServiceInternalErrorException>("ServiceInternalErrorException")({Message: S.optional(S.String)}) {}
export class ServiceLimitExceededException extends S.Class<ServiceLimitExceededException>("ServiceLimitExceededException")({Message: S.optional(S.String)}) {}
export class ThrottlingException extends S.Class<ThrottlingException>("ThrottlingException")({Message: S.optional(S.String)}) {}
export class TypeNotFoundException extends S.Class<TypeNotFoundException>("TypeNotFoundException")({Message: S.optional(S.String)}) {}
export class UnsupportedActionException extends S.Class<UnsupportedActionException>("UnsupportedActionException")({Message: S.optional(S.String)}) {}

//# Errors
export class AlreadyExistsExceptionError extends S.TaggedError<AlreadyExistsExceptionError>()("AlreadyExistsException", AlreadyExistsException.fields) {};
export class ClientTokenConflictExceptionError extends S.TaggedError<ClientTokenConflictExceptionError>()("ClientTokenConflictException", ClientTokenConflictException.fields) {};
export class ConcurrentOperationExceptionError extends S.TaggedError<ConcurrentOperationExceptionError>()("ConcurrentOperationException", ConcurrentOperationException.fields) {};
export class GeneralServiceExceptionError extends S.TaggedError<GeneralServiceExceptionError>()("GeneralServiceException", GeneralServiceException.fields) {};
export class HandlerFailureExceptionError extends S.TaggedError<HandlerFailureExceptionError>()("HandlerFailureException", HandlerFailureException.fields) {};
export class HandlerInternalFailureExceptionError extends S.TaggedError<HandlerInternalFailureExceptionError>()("HandlerInternalFailureException", HandlerInternalFailureException.fields) {};
export class InvalidCredentialsExceptionError extends S.TaggedError<InvalidCredentialsExceptionError>()("InvalidCredentialsException", InvalidCredentialsException.fields) {};
export class InvalidRequestExceptionError extends S.TaggedError<InvalidRequestExceptionError>()("InvalidRequestException", InvalidRequestException.fields) {};
export class ConcurrentModificationExceptionError extends S.TaggedError<ConcurrentModificationExceptionError>()("ConcurrentModificationException", ConcurrentModificationException.fields) {};
export class RequestTokenNotFoundExceptionError extends S.TaggedError<RequestTokenNotFoundExceptionError>()("RequestTokenNotFoundException", RequestTokenNotFoundException.fields) {};
export class NetworkFailureExceptionError extends S.TaggedError<NetworkFailureExceptionError>()("NetworkFailureException", NetworkFailureException.fields) {};
export class NotStabilizedExceptionError extends S.TaggedError<NotStabilizedExceptionError>()("NotStabilizedException", NotStabilizedException.fields) {};
export class NotUpdatableExceptionError extends S.TaggedError<NotUpdatableExceptionError>()("NotUpdatableException", NotUpdatableException.fields) {};
export class PrivateTypeExceptionError extends S.TaggedError<PrivateTypeExceptionError>()("PrivateTypeException", PrivateTypeException.fields) {};
export class ResourceConflictExceptionError extends S.TaggedError<ResourceConflictExceptionError>()("ResourceConflictException", ResourceConflictException.fields) {};
export class ResourceNotFoundExceptionError extends S.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ServiceInternalErrorExceptionError extends S.TaggedError<ServiceInternalErrorExceptionError>()("ServiceInternalErrorException", ServiceInternalErrorException.fields) {};
export class ServiceLimitExceededExceptionError extends S.TaggedError<ServiceLimitExceededExceptionError>()("ServiceLimitExceededException", ServiceLimitExceededException.fields) {};
export class ThrottlingExceptionError extends S.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class TypeNotFoundExceptionError extends S.TaggedError<TypeNotFoundExceptionError>()("TypeNotFoundException", TypeNotFoundException.fields) {};
export class UnsupportedActionExceptionError extends S.TaggedError<UnsupportedActionExceptionError>()("UnsupportedActionException", UnsupportedActionException.fields) {};

//# Operations
export const listResourceRequests = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-09-30", uri: "/", method: "POST", sdkId: "CloudControl", sigV4ServiceName: "cloudcontrolapi", name: "CloudApiService.ListResourceRequests" }, ListResourceRequestsInput, ListResourceRequestsOutput, []), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const cancelResourceRequest = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-09-30", uri: "/", method: "POST", sdkId: "CloudControl", sigV4ServiceName: "cloudcontrolapi", name: "CloudApiService.CancelResourceRequest" }, CancelResourceRequestInput, CancelResourceRequestOutput, [ConcurrentModificationExceptionError, RequestTokenNotFoundExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getResourceRequestStatus = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-09-30", uri: "/", method: "POST", sdkId: "CloudControl", sigV4ServiceName: "cloudcontrolapi", name: "CloudApiService.GetResourceRequestStatus" }, GetResourceRequestStatusInput, GetResourceRequestStatusOutput, [RequestTokenNotFoundExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-09-30", uri: "/", method: "POST", sdkId: "CloudControl", sigV4ServiceName: "cloudcontrolapi", name: "CloudApiService.CreateResource" }, CreateResourceInput, CreateResourceOutput, [AlreadyExistsExceptionError, ClientTokenConflictExceptionError, ConcurrentOperationExceptionError, GeneralServiceExceptionError, HandlerFailureExceptionError, HandlerInternalFailureExceptionError, InvalidCredentialsExceptionError, InvalidRequestExceptionError, NetworkFailureExceptionError, NotStabilizedExceptionError, NotUpdatableExceptionError, PrivateTypeExceptionError, ResourceConflictExceptionError, ResourceNotFoundExceptionError, ServiceInternalErrorExceptionError, ServiceLimitExceededExceptionError, ThrottlingExceptionError, TypeNotFoundExceptionError, UnsupportedActionExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-09-30", uri: "/", method: "POST", sdkId: "CloudControl", sigV4ServiceName: "cloudcontrolapi", name: "CloudApiService.DeleteResource" }, DeleteResourceInput, DeleteResourceOutput, [AlreadyExistsExceptionError, ClientTokenConflictExceptionError, ConcurrentOperationExceptionError, GeneralServiceExceptionError, HandlerFailureExceptionError, HandlerInternalFailureExceptionError, InvalidCredentialsExceptionError, InvalidRequestExceptionError, NetworkFailureExceptionError, NotStabilizedExceptionError, NotUpdatableExceptionError, PrivateTypeExceptionError, ResourceConflictExceptionError, ResourceNotFoundExceptionError, ServiceInternalErrorExceptionError, ServiceLimitExceededExceptionError, ThrottlingExceptionError, TypeNotFoundExceptionError, UnsupportedActionExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-09-30", uri: "/", method: "POST", sdkId: "CloudControl", sigV4ServiceName: "cloudcontrolapi", name: "CloudApiService.GetResource" }, GetResourceInput, GetResourceOutput, [AlreadyExistsExceptionError, GeneralServiceExceptionError, HandlerFailureExceptionError, HandlerInternalFailureExceptionError, InvalidCredentialsExceptionError, InvalidRequestExceptionError, NetworkFailureExceptionError, NotStabilizedExceptionError, NotUpdatableExceptionError, PrivateTypeExceptionError, ResourceConflictExceptionError, ResourceNotFoundExceptionError, ServiceInternalErrorExceptionError, ServiceLimitExceededExceptionError, ThrottlingExceptionError, TypeNotFoundExceptionError, UnsupportedActionExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listResources = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-09-30", uri: "/", method: "POST", sdkId: "CloudControl", sigV4ServiceName: "cloudcontrolapi", name: "CloudApiService.ListResources" }, ListResourcesInput, ListResourcesOutput, [AlreadyExistsExceptionError, GeneralServiceExceptionError, HandlerFailureExceptionError, HandlerInternalFailureExceptionError, InvalidCredentialsExceptionError, InvalidRequestExceptionError, NetworkFailureExceptionError, NotStabilizedExceptionError, NotUpdatableExceptionError, PrivateTypeExceptionError, ResourceConflictExceptionError, ResourceNotFoundExceptionError, ServiceInternalErrorExceptionError, ServiceLimitExceededExceptionError, ThrottlingExceptionError, TypeNotFoundExceptionError, UnsupportedActionExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-09-30", uri: "/", method: "POST", sdkId: "CloudControl", sigV4ServiceName: "cloudcontrolapi", name: "CloudApiService.UpdateResource" }, UpdateResourceInput, UpdateResourceOutput, [AlreadyExistsExceptionError, ClientTokenConflictExceptionError, ConcurrentOperationExceptionError, GeneralServiceExceptionError, HandlerFailureExceptionError, HandlerInternalFailureExceptionError, InvalidCredentialsExceptionError, InvalidRequestExceptionError, NetworkFailureExceptionError, NotStabilizedExceptionError, NotUpdatableExceptionError, PrivateTypeExceptionError, ResourceConflictExceptionError, ResourceNotFoundExceptionError, ServiceInternalErrorExceptionError, ServiceLimitExceededExceptionError, ThrottlingExceptionError, TypeNotFoundExceptionError, UnsupportedActionExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
