import * as Schema from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import { Operation, Path, Header, StreamBody, Body } from "../schema-helpers.ts";

//# Schemas
export const PermissionsList = Schema.Array(Schema.String);
export const BoundedEnvironmentIdList = Schema.Array(Schema.String);
export const TagKeyList = Schema.Array(Schema.String);
export class CreateEnvironmentMembershipRequest extends Schema.Class<CreateEnvironmentMembershipRequest>("CreateEnvironmentMembershipRequest")({environmentId: Schema.String, userArn: Schema.String, permissions: Schema.String}) {}
export class DeleteEnvironmentRequest extends Schema.Class<DeleteEnvironmentRequest>("DeleteEnvironmentRequest")({environmentId: Schema.String}) {}
export class DeleteEnvironmentResult extends Schema.Class<DeleteEnvironmentResult>("DeleteEnvironmentResult")({}) {}
export class DeleteEnvironmentMembershipRequest extends Schema.Class<DeleteEnvironmentMembershipRequest>("DeleteEnvironmentMembershipRequest")({environmentId: Schema.String, userArn: Schema.String}) {}
export class DeleteEnvironmentMembershipResult extends Schema.Class<DeleteEnvironmentMembershipResult>("DeleteEnvironmentMembershipResult")({}) {}
export class DescribeEnvironmentMembershipsRequest extends Schema.Class<DescribeEnvironmentMembershipsRequest>("DescribeEnvironmentMembershipsRequest")({userArn: Schema.optional(Schema.String), environmentId: Schema.optional(Schema.String), permissions: Schema.optional(PermissionsList), nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class DescribeEnvironmentsRequest extends Schema.Class<DescribeEnvironmentsRequest>("DescribeEnvironmentsRequest")({environmentIds: BoundedEnvironmentIdList}) {}
export class DescribeEnvironmentStatusRequest extends Schema.Class<DescribeEnvironmentStatusRequest>("DescribeEnvironmentStatusRequest")({environmentId: Schema.String}) {}
export class ListEnvironmentsRequest extends Schema.Class<ListEnvironmentsRequest>("ListEnvironmentsRequest")({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListTagsForResourceRequest extends Schema.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceARN: Schema.String}) {}
export class Tag extends Schema.Class<Tag>("Tag")({Key: Schema.String, Value: Schema.String}) {}
export const TagList = Schema.Array(Tag);
export class TagResourceRequest extends Schema.Class<TagResourceRequest>("TagResourceRequest")({ResourceARN: Schema.String, Tags: TagList}) {}
export class TagResourceResponse extends Schema.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends Schema.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceARN: Schema.String, TagKeys: TagKeyList}) {}
export class UntagResourceResponse extends Schema.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class UpdateEnvironmentRequest extends Schema.Class<UpdateEnvironmentRequest>("UpdateEnvironmentRequest")({environmentId: Schema.String, name: Schema.optional(Schema.String), description: Schema.optional(Schema.String), managedCredentialsAction: Schema.optional(Schema.String)}) {}
export class UpdateEnvironmentResult extends Schema.Class<UpdateEnvironmentResult>("UpdateEnvironmentResult")({}) {}
export class UpdateEnvironmentMembershipRequest extends Schema.Class<UpdateEnvironmentMembershipRequest>("UpdateEnvironmentMembershipRequest")({environmentId: Schema.String, userArn: Schema.String, permissions: Schema.String}) {}
export class EnvironmentMember extends Schema.Class<EnvironmentMember>("EnvironmentMember")({permissions: Schema.String, userId: Schema.String, userArn: Schema.String, environmentId: Schema.String, lastAccess: Schema.optional(Schema.Date)}) {}
export const EnvironmentMembersList = Schema.Array(EnvironmentMember);
export const EnvironmentIdList = Schema.Array(Schema.String);
export class CreateEnvironmentEC2Request extends Schema.Class<CreateEnvironmentEC2Request>("CreateEnvironmentEC2Request")({name: Schema.String, description: Schema.optional(Schema.String), clientRequestToken: Schema.optional(Schema.String), instanceType: Schema.String, subnetId: Schema.optional(Schema.String), imageId: Schema.String, automaticStopTimeMinutes: Schema.optional(Schema.Number), ownerArn: Schema.optional(Schema.String), tags: Schema.optional(TagList), connectionType: Schema.optional(Schema.String), dryRun: Schema.optional(Schema.Boolean)}) {}
export class BadRequestException extends Schema.Class<BadRequestException>("BadRequestException")({message: Schema.optional(Schema.String), className: Schema.optional(Schema.String), code: Schema.optional(Schema.Number)}) {}
export class ConflictException extends Schema.Class<ConflictException>("ConflictException")({message: Schema.optional(Schema.String), className: Schema.optional(Schema.String), code: Schema.optional(Schema.Number)}) {}
export class DescribeEnvironmentMembershipsResult extends Schema.Class<DescribeEnvironmentMembershipsResult>("DescribeEnvironmentMembershipsResult")({memberships: Schema.optional(EnvironmentMembersList), nextToken: Schema.optional(Schema.String)}) {}
export class DescribeEnvironmentStatusResult extends Schema.Class<DescribeEnvironmentStatusResult>("DescribeEnvironmentStatusResult")({status: Schema.String, message: Schema.String}) {}
export class ListEnvironmentsResult extends Schema.Class<ListEnvironmentsResult>("ListEnvironmentsResult")({nextToken: Schema.optional(Schema.String), environmentIds: Schema.optional(EnvironmentIdList)}) {}
export class ListTagsForResourceResponse extends Schema.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: Schema.optional(TagList)}) {}
export class ConcurrentAccessException extends Schema.Class<ConcurrentAccessException>("ConcurrentAccessException")({message: Schema.optional(Schema.String), className: Schema.optional(Schema.String), code: Schema.optional(Schema.Number)}) {}
export class InternalServerErrorException extends Schema.Class<InternalServerErrorException>("InternalServerErrorException")({message: Schema.optional(Schema.String), className: Schema.optional(Schema.String), code: Schema.optional(Schema.Number)}) {}
export class ForbiddenException extends Schema.Class<ForbiddenException>("ForbiddenException")({message: Schema.optional(Schema.String), className: Schema.optional(Schema.String), code: Schema.optional(Schema.Number)}) {}
export class UpdateEnvironmentMembershipResult extends Schema.Class<UpdateEnvironmentMembershipResult>("UpdateEnvironmentMembershipResult")({membership: Schema.optional(EnvironmentMember)}) {}
export class CreateEnvironmentEC2Result extends Schema.Class<CreateEnvironmentEC2Result>("CreateEnvironmentEC2Result")({environmentId: Schema.optional(Schema.String)}) {}
export class CreateEnvironmentMembershipResult extends Schema.Class<CreateEnvironmentMembershipResult>("CreateEnvironmentMembershipResult")({membership: EnvironmentMember}) {}
export class LimitExceededException extends Schema.Class<LimitExceededException>("LimitExceededException")({message: Schema.optional(Schema.String), className: Schema.optional(Schema.String), code: Schema.optional(Schema.Number)}) {}
export class NotFoundException extends Schema.Class<NotFoundException>("NotFoundException")({message: Schema.optional(Schema.String), className: Schema.optional(Schema.String), code: Schema.optional(Schema.Number)}) {}
export class TooManyRequestsException extends Schema.Class<TooManyRequestsException>("TooManyRequestsException")({message: Schema.optional(Schema.String), className: Schema.optional(Schema.String), code: Schema.optional(Schema.Number)}) {}
export class EnvironmentLifecycle extends Schema.Class<EnvironmentLifecycle>("EnvironmentLifecycle")({status: Schema.optional(Schema.String), reason: Schema.optional(Schema.String), failureResource: Schema.optional(Schema.String)}) {}
export class Environment extends Schema.Class<Environment>("Environment")({id: Schema.optional(Schema.String), name: Schema.optional(Schema.String), description: Schema.optional(Schema.String), type: Schema.String, connectionType: Schema.optional(Schema.String), arn: Schema.String, ownerArn: Schema.String, lifecycle: Schema.optional(EnvironmentLifecycle), managedCredentialsStatus: Schema.optional(Schema.String)}) {}
export const EnvironmentList = Schema.Array(Environment);
export class DescribeEnvironmentsResult extends Schema.Class<DescribeEnvironmentsResult>("DescribeEnvironmentsResult")({environments: Schema.optional(EnvironmentList)}) {}

//# Errors
export class BadRequestExceptionError extends Schema.TaggedError<BadRequestExceptionError>()("BadRequestException", BadRequestException.fields) {};
export class ConcurrentAccessExceptionError extends Schema.TaggedError<ConcurrentAccessExceptionError>()("ConcurrentAccessException", ConcurrentAccessException.fields) {};
export class ConflictExceptionError extends Schema.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class ForbiddenExceptionError extends Schema.TaggedError<ForbiddenExceptionError>()("ForbiddenException", ForbiddenException.fields) {};
export class InternalServerErrorExceptionError extends Schema.TaggedError<InternalServerErrorExceptionError>()("InternalServerErrorException", InternalServerErrorException.fields) {};
export class LimitExceededExceptionError extends Schema.TaggedError<LimitExceededExceptionError>()("LimitExceededException", LimitExceededException.fields) {};
export class NotFoundExceptionError extends Schema.TaggedError<NotFoundExceptionError>()("NotFoundException", NotFoundException.fields) {};
export class TooManyRequestsExceptionError extends Schema.TaggedError<TooManyRequestsExceptionError>()("TooManyRequestsException", TooManyRequestsException.fields) {};

//# Operations
export const describeEnvironmentStatus = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.DescribeEnvironmentStatus" }, DescribeEnvironmentStatusRequest, DescribeEnvironmentStatusResult, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, InternalServerErrorExceptionError, LimitExceededExceptionError, NotFoundExceptionError, TooManyRequestsExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listEnvironments = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.ListEnvironments" }, ListEnvironmentsRequest, ListEnvironmentsResult, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, InternalServerErrorExceptionError, LimitExceededExceptionError, NotFoundExceptionError, TooManyRequestsExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [BadRequestExceptionError, InternalServerErrorExceptionError, NotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.TagResource" }, TagResourceRequest, TagResourceResponse, [BadRequestExceptionError, ConcurrentAccessExceptionError, InternalServerErrorExceptionError, NotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [BadRequestExceptionError, ConcurrentAccessExceptionError, InternalServerErrorExceptionError, NotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.UpdateEnvironment" }, UpdateEnvironmentRequest, UpdateEnvironmentResult, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, InternalServerErrorExceptionError, LimitExceededExceptionError, NotFoundExceptionError, TooManyRequestsExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateEnvironmentMembership = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.UpdateEnvironmentMembership" }, UpdateEnvironmentMembershipRequest, UpdateEnvironmentMembershipResult, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, InternalServerErrorExceptionError, LimitExceededExceptionError, NotFoundExceptionError, TooManyRequestsExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createEnvironmentEC2 = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.CreateEnvironmentEC2" }, CreateEnvironmentEC2Request, CreateEnvironmentEC2Result, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, InternalServerErrorExceptionError, LimitExceededExceptionError, NotFoundExceptionError, TooManyRequestsExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createEnvironmentMembership = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.CreateEnvironmentMembership" }, CreateEnvironmentMembershipRequest, CreateEnvironmentMembershipResult, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, InternalServerErrorExceptionError, LimitExceededExceptionError, NotFoundExceptionError, TooManyRequestsExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.DeleteEnvironment" }, DeleteEnvironmentRequest, DeleteEnvironmentResult, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, InternalServerErrorExceptionError, LimitExceededExceptionError, NotFoundExceptionError, TooManyRequestsExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteEnvironmentMembership = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.DeleteEnvironmentMembership" }, DeleteEnvironmentMembershipRequest, DeleteEnvironmentMembershipResult, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, InternalServerErrorExceptionError, LimitExceededExceptionError, NotFoundExceptionError, TooManyRequestsExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeEnvironmentMemberships = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.DescribeEnvironmentMemberships" }, DescribeEnvironmentMembershipsRequest, DescribeEnvironmentMembershipsResult, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, InternalServerErrorExceptionError, LimitExceededExceptionError, NotFoundExceptionError, TooManyRequestsExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeEnvironments = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-09-23", uri: "/", method: "POST", sdkId: "Cloud9", sigV4ServiceName: "cloud9", name: "AWSCloud9WorkspaceManagementService.DescribeEnvironments" }, DescribeEnvironmentsRequest, DescribeEnvironmentsResult, [BadRequestExceptionError, ConflictExceptionError, ForbiddenExceptionError, InternalServerErrorExceptionError, LimitExceededExceptionError, NotFoundExceptionError, TooManyRequestsExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
