import * as S from "effect/Schema"
import { FormatAwsJSON10Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const TagKeyList = S.Array(S.String);
export class Tag extends S.Class<Tag>("Tag")({Key: S.String, Value: S.String}) {}
export const TagList = S.Array(Tag);
export class CreateRepositoryLinkInput extends S.Class<CreateRepositoryLinkInput>("CreateRepositoryLinkInput")({ConnectionArn: S.String, OwnerId: S.String, RepositoryName: S.String, EncryptionKeyArn: S.optional(S.String), Tags: S.optional(TagList)}) {}
export class CreateSyncConfigurationInput extends S.Class<CreateSyncConfigurationInput>("CreateSyncConfigurationInput")({Branch: S.String, ConfigFile: S.String, RepositoryLinkId: S.String, ResourceName: S.String, RoleArn: S.String, SyncType: S.String, PublishDeploymentStatus: S.optional(S.String), TriggerResourceUpdateOn: S.optional(S.String)}) {}
export class DeleteConnectionInput extends S.Class<DeleteConnectionInput>("DeleteConnectionInput")({ConnectionArn: S.String}) {}
export class DeleteConnectionOutput extends S.Class<DeleteConnectionOutput>("DeleteConnectionOutput")({}) {}
export class DeleteHostInput extends S.Class<DeleteHostInput>("DeleteHostInput")({HostArn: S.String}) {}
export class DeleteHostOutput extends S.Class<DeleteHostOutput>("DeleteHostOutput")({}) {}
export class DeleteRepositoryLinkInput extends S.Class<DeleteRepositoryLinkInput>("DeleteRepositoryLinkInput")({RepositoryLinkId: S.String}) {}
export class DeleteRepositoryLinkOutput extends S.Class<DeleteRepositoryLinkOutput>("DeleteRepositoryLinkOutput")({}) {}
export class DeleteSyncConfigurationInput extends S.Class<DeleteSyncConfigurationInput>("DeleteSyncConfigurationInput")({SyncType: S.String, ResourceName: S.String}) {}
export class DeleteSyncConfigurationOutput extends S.Class<DeleteSyncConfigurationOutput>("DeleteSyncConfigurationOutput")({}) {}
export class GetConnectionInput extends S.Class<GetConnectionInput>("GetConnectionInput")({ConnectionArn: S.String}) {}
export class GetHostInput extends S.Class<GetHostInput>("GetHostInput")({HostArn: S.String}) {}
export class GetRepositoryLinkInput extends S.Class<GetRepositoryLinkInput>("GetRepositoryLinkInput")({RepositoryLinkId: S.String}) {}
export class GetRepositorySyncStatusInput extends S.Class<GetRepositorySyncStatusInput>("GetRepositorySyncStatusInput")({Branch: S.String, RepositoryLinkId: S.String, SyncType: S.String}) {}
export class GetResourceSyncStatusInput extends S.Class<GetResourceSyncStatusInput>("GetResourceSyncStatusInput")({ResourceName: S.String, SyncType: S.String}) {}
export class GetSyncBlockerSummaryInput extends S.Class<GetSyncBlockerSummaryInput>("GetSyncBlockerSummaryInput")({SyncType: S.String, ResourceName: S.String}) {}
export class GetSyncConfigurationInput extends S.Class<GetSyncConfigurationInput>("GetSyncConfigurationInput")({SyncType: S.String, ResourceName: S.String}) {}
export class ListConnectionsInput extends S.Class<ListConnectionsInput>("ListConnectionsInput")({ProviderTypeFilter: S.optional(S.String), HostArnFilter: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListHostsInput extends S.Class<ListHostsInput>("ListHostsInput")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListRepositoryLinksInput extends S.Class<ListRepositoryLinksInput>("ListRepositoryLinksInput")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListRepositorySyncDefinitionsInput extends S.Class<ListRepositorySyncDefinitionsInput>("ListRepositorySyncDefinitionsInput")({RepositoryLinkId: S.String, SyncType: S.String}) {}
export class ListSyncConfigurationsInput extends S.Class<ListSyncConfigurationsInput>("ListSyncConfigurationsInput")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), RepositoryLinkId: S.String, SyncType: S.String}) {}
export class ListTagsForResourceInput extends S.Class<ListTagsForResourceInput>("ListTagsForResourceInput")({ResourceArn: S.String}) {}
export class TagResourceInput extends S.Class<TagResourceInput>("TagResourceInput")({ResourceArn: S.String, Tags: TagList}) {}
export class TagResourceOutput extends S.Class<TagResourceOutput>("TagResourceOutput")({}) {}
export class UntagResourceInput extends S.Class<UntagResourceInput>("UntagResourceInput")({ResourceArn: S.String, TagKeys: TagKeyList}) {}
export class UntagResourceOutput extends S.Class<UntagResourceOutput>("UntagResourceOutput")({}) {}
export const SubnetIds = S.Array(S.String);
export const SecurityGroupIds = S.Array(S.String);
export class VpcConfiguration extends S.Class<VpcConfiguration>("VpcConfiguration")({VpcId: S.String, SubnetIds: SubnetIds, SecurityGroupIds: SecurityGroupIds, TlsCertificate: S.optional(S.String)}) {}
export class UpdateHostInput extends S.Class<UpdateHostInput>("UpdateHostInput")({HostArn: S.String, ProviderEndpoint: S.optional(S.String), VpcConfiguration: S.optional(VpcConfiguration)}) {}
export class UpdateHostOutput extends S.Class<UpdateHostOutput>("UpdateHostOutput")({}) {}
export class UpdateRepositoryLinkInput extends S.Class<UpdateRepositoryLinkInput>("UpdateRepositoryLinkInput")({ConnectionArn: S.optional(S.String), EncryptionKeyArn: S.optional(S.String), RepositoryLinkId: S.String}) {}
export class UpdateSyncBlockerInput extends S.Class<UpdateSyncBlockerInput>("UpdateSyncBlockerInput")({Id: S.String, SyncType: S.String, ResourceName: S.String, ResolvedReason: S.String}) {}
export class UpdateSyncConfigurationInput extends S.Class<UpdateSyncConfigurationInput>("UpdateSyncConfigurationInput")({Branch: S.optional(S.String), ConfigFile: S.optional(S.String), RepositoryLinkId: S.optional(S.String), ResourceName: S.String, RoleArn: S.optional(S.String), SyncType: S.String, PublishDeploymentStatus: S.optional(S.String), TriggerResourceUpdateOn: S.optional(S.String)}) {}
export class Connection extends S.Class<Connection>("Connection")({ConnectionName: S.optional(S.String), ConnectionArn: S.optional(S.String), ProviderType: S.optional(S.String), OwnerAccountId: S.optional(S.String), ConnectionStatus: S.optional(S.String), HostArn: S.optional(S.String)}) {}
export const ConnectionList = S.Array(Connection);
export class RepositoryLinkInfo extends S.Class<RepositoryLinkInfo>("RepositoryLinkInfo")({ConnectionArn: S.String, EncryptionKeyArn: S.optional(S.String), OwnerId: S.String, ProviderType: S.String, RepositoryLinkArn: S.String, RepositoryLinkId: S.String, RepositoryName: S.String}) {}
export const RepositoryLinkList = S.Array(RepositoryLinkInfo);
export class SyncConfiguration extends S.Class<SyncConfiguration>("SyncConfiguration")({Branch: S.String, ConfigFile: S.optional(S.String), OwnerId: S.String, ProviderType: S.String, RepositoryLinkId: S.String, RepositoryName: S.String, ResourceName: S.String, RoleArn: S.String, SyncType: S.String, PublishDeploymentStatus: S.optional(S.String), TriggerResourceUpdateOn: S.optional(S.String)}) {}
export const SyncConfigurationList = S.Array(SyncConfiguration);
export class CreateConnectionInput extends S.Class<CreateConnectionInput>("CreateConnectionInput")({ProviderType: S.optional(S.String), ConnectionName: S.String, Tags: S.optional(TagList), HostArn: S.optional(S.String)}) {}
export class CreateHostInput extends S.Class<CreateHostInput>("CreateHostInput")({Name: S.String, ProviderType: S.String, ProviderEndpoint: S.String, VpcConfiguration: S.optional(VpcConfiguration), Tags: S.optional(TagList)}) {}
export class ResourceNotFoundException extends S.Class<ResourceNotFoundException>("ResourceNotFoundException")({Message: S.optional(S.String)}) {}
export class ResourceUnavailableException extends S.Class<ResourceUnavailableException>("ResourceUnavailableException")({Message: S.optional(S.String)}) {}
export class AccessDeniedException extends S.Class<AccessDeniedException>("AccessDeniedException")({Message: S.optional(S.String)}) {}
export class ConcurrentModificationException extends S.Class<ConcurrentModificationException>("ConcurrentModificationException")({Message: S.optional(S.String)}) {}
export class GetHostOutput extends S.Class<GetHostOutput>("GetHostOutput")({Name: S.optional(S.String), Status: S.optional(S.String), ProviderType: S.optional(S.String), ProviderEndpoint: S.optional(S.String), VpcConfiguration: S.optional(VpcConfiguration)}) {}
export class GetRepositoryLinkOutput extends S.Class<GetRepositoryLinkOutput>("GetRepositoryLinkOutput")({RepositoryLinkInfo: RepositoryLinkInfo}) {}
export class GetSyncConfigurationOutput extends S.Class<GetSyncConfigurationOutput>("GetSyncConfigurationOutput")({SyncConfiguration: SyncConfiguration}) {}
export class ListConnectionsOutput extends S.Class<ListConnectionsOutput>("ListConnectionsOutput")({Connections: S.optional(ConnectionList), NextToken: S.optional(S.String)}) {}
export class ListRepositoryLinksOutput extends S.Class<ListRepositoryLinksOutput>("ListRepositoryLinksOutput")({RepositoryLinks: RepositoryLinkList, NextToken: S.optional(S.String)}) {}
export class ListSyncConfigurationsOutput extends S.Class<ListSyncConfigurationsOutput>("ListSyncConfigurationsOutput")({SyncConfigurations: SyncConfigurationList, NextToken: S.optional(S.String)}) {}
export class ListTagsForResourceOutput extends S.Class<ListTagsForResourceOutput>("ListTagsForResourceOutput")({Tags: S.optional(TagList)}) {}
export class LimitExceededException extends S.Class<LimitExceededException>("LimitExceededException")({Message: S.optional(S.String)}) {}
export class ConflictException extends S.Class<ConflictException>("ConflictException")({Message: S.optional(S.String)}) {}
export class UpdateRepositoryLinkOutput extends S.Class<UpdateRepositoryLinkOutput>("UpdateRepositoryLinkOutput")({RepositoryLinkInfo: RepositoryLinkInfo}) {}
export class UpdateSyncConfigurationOutput extends S.Class<UpdateSyncConfigurationOutput>("UpdateSyncConfigurationOutput")({SyncConfiguration: SyncConfiguration}) {}
export class SyncBlockerContext extends S.Class<SyncBlockerContext>("SyncBlockerContext")({Key: S.String, Value: S.String}) {}
export const SyncBlockerContextList = S.Array(SyncBlockerContext);
export class SyncBlocker extends S.Class<SyncBlocker>("SyncBlocker")({Id: S.String, Type: S.String, Status: S.String, CreatedReason: S.String, CreatedAt: S.Date, Contexts: S.optional(SyncBlockerContextList), ResolvedReason: S.optional(S.String), ResolvedAt: S.optional(S.Date)}) {}
export const LatestSyncBlockerList = S.Array(SyncBlocker);
export class Revision extends S.Class<Revision>("Revision")({Branch: S.String, Directory: S.String, OwnerId: S.String, RepositoryName: S.String, ProviderType: S.String, Sha: S.String}) {}
export class SyncBlockerSummary extends S.Class<SyncBlockerSummary>("SyncBlockerSummary")({ResourceName: S.String, ParentResourceName: S.optional(S.String), LatestBlockers: S.optional(LatestSyncBlockerList)}) {}
export class Host extends S.Class<Host>("Host")({Name: S.optional(S.String), HostArn: S.optional(S.String), ProviderType: S.optional(S.String), ProviderEndpoint: S.optional(S.String), VpcConfiguration: S.optional(VpcConfiguration), Status: S.optional(S.String), StatusMessage: S.optional(S.String)}) {}
export const HostList = S.Array(Host);
export class RepositorySyncDefinition extends S.Class<RepositorySyncDefinition>("RepositorySyncDefinition")({Branch: S.String, Directory: S.String, Parent: S.String, Target: S.String}) {}
export const RepositorySyncDefinitionList = S.Array(RepositorySyncDefinition);
export class CreateConnectionOutput extends S.Class<CreateConnectionOutput>("CreateConnectionOutput")({ConnectionArn: S.String, Tags: S.optional(TagList)}) {}
export class CreateHostOutput extends S.Class<CreateHostOutput>("CreateHostOutput")({HostArn: S.optional(S.String), Tags: S.optional(TagList)}) {}
export class CreateRepositoryLinkOutput extends S.Class<CreateRepositoryLinkOutput>("CreateRepositoryLinkOutput")({RepositoryLinkInfo: RepositoryLinkInfo}) {}
export class CreateSyncConfigurationOutput extends S.Class<CreateSyncConfigurationOutput>("CreateSyncConfigurationOutput")({SyncConfiguration: SyncConfiguration}) {}
export class InternalServerException extends S.Class<InternalServerException>("InternalServerException")({Message: S.optional(S.String)}) {}
export class InvalidInputException extends S.Class<InvalidInputException>("InvalidInputException")({Message: S.optional(S.String)}) {}
export class GetConnectionOutput extends S.Class<GetConnectionOutput>("GetConnectionOutput")({Connection: S.optional(Connection)}) {}
export class ThrottlingException extends S.Class<ThrottlingException>("ThrottlingException")({Message: S.optional(S.String)}) {}
export class GetSyncBlockerSummaryOutput extends S.Class<GetSyncBlockerSummaryOutput>("GetSyncBlockerSummaryOutput")({SyncBlockerSummary: SyncBlockerSummary}) {}
export class ListHostsOutput extends S.Class<ListHostsOutput>("ListHostsOutput")({Hosts: S.optional(HostList), NextToken: S.optional(S.String)}) {}
export class ListRepositorySyncDefinitionsOutput extends S.Class<ListRepositorySyncDefinitionsOutput>("ListRepositorySyncDefinitionsOutput")({RepositorySyncDefinitions: RepositorySyncDefinitionList, NextToken: S.optional(S.String)}) {}
export class UnsupportedOperationException extends S.Class<UnsupportedOperationException>("UnsupportedOperationException")({Message: S.optional(S.String)}) {}
export class ConditionalCheckFailedException extends S.Class<ConditionalCheckFailedException>("ConditionalCheckFailedException")({Message: S.optional(S.String)}) {}
export class UpdateOutOfSyncException extends S.Class<UpdateOutOfSyncException>("UpdateOutOfSyncException")({Message: S.optional(S.String)}) {}
export class RepositorySyncEvent extends S.Class<RepositorySyncEvent>("RepositorySyncEvent")({Event: S.String, ExternalId: S.optional(S.String), Time: S.Date, Type: S.String}) {}
export const RepositorySyncEventList = S.Array(RepositorySyncEvent);
export class ResourceSyncEvent extends S.Class<ResourceSyncEvent>("ResourceSyncEvent")({Event: S.String, ExternalId: S.optional(S.String), Time: S.Date, Type: S.String}) {}
export const ResourceSyncEventList = S.Array(ResourceSyncEvent);
export class RepositorySyncAttempt extends S.Class<RepositorySyncAttempt>("RepositorySyncAttempt")({StartedAt: S.Date, Status: S.String, Events: RepositorySyncEventList}) {}
export class ResourceSyncAttempt extends S.Class<ResourceSyncAttempt>("ResourceSyncAttempt")({Events: ResourceSyncEventList, InitialRevision: Revision, StartedAt: S.Date, Status: S.String, TargetRevision: Revision, Target: S.String}) {}
export class ResourceAlreadyExistsException extends S.Class<ResourceAlreadyExistsException>("ResourceAlreadyExistsException")({Message: S.optional(S.String)}) {}
export class SyncConfigurationStillExistsException extends S.Class<SyncConfigurationStillExistsException>("SyncConfigurationStillExistsException")({Message: S.optional(S.String)}) {}
export class GetRepositorySyncStatusOutput extends S.Class<GetRepositorySyncStatusOutput>("GetRepositorySyncStatusOutput")({LatestSync: RepositorySyncAttempt}) {}
export class GetResourceSyncStatusOutput extends S.Class<GetResourceSyncStatusOutput>("GetResourceSyncStatusOutput")({DesiredState: S.optional(Revision), LatestSuccessfulSync: S.optional(ResourceSyncAttempt), LatestSync: ResourceSyncAttempt}) {}
export class UpdateSyncBlockerOutput extends S.Class<UpdateSyncBlockerOutput>("UpdateSyncBlockerOutput")({ResourceName: S.String, ParentResourceName: S.optional(S.String), SyncBlocker: SyncBlocker}) {}
export class UnsupportedProviderTypeException extends S.Class<UnsupportedProviderTypeException>("UnsupportedProviderTypeException")({Message: S.optional(S.String)}) {}
export class RetryLatestCommitFailedException extends S.Class<RetryLatestCommitFailedException>("RetryLatestCommitFailedException")({Message: S.optional(S.String)}) {}
export class SyncBlockerDoesNotExistException extends S.Class<SyncBlockerDoesNotExistException>("SyncBlockerDoesNotExistException")({Message: S.optional(S.String)}) {}

//# Errors
export class ResourceNotFoundExceptionError extends S.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class AccessDeniedExceptionError extends S.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class ResourceUnavailableExceptionError extends S.TaggedError<ResourceUnavailableExceptionError>()("ResourceUnavailableException", ResourceUnavailableException.fields) {};
export class ConcurrentModificationExceptionError extends S.TaggedError<ConcurrentModificationExceptionError>()("ConcurrentModificationException", ConcurrentModificationException.fields) {};
export class InternalServerExceptionError extends S.TaggedError<InternalServerExceptionError>()("InternalServerException", InternalServerException.fields) {};
export class InvalidInputExceptionError extends S.TaggedError<InvalidInputExceptionError>()("InvalidInputException", InvalidInputException.fields) {};
export class ThrottlingExceptionError extends S.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class LimitExceededExceptionError extends S.TaggedError<LimitExceededExceptionError>()("LimitExceededException", LimitExceededException.fields) {};
export class ConflictExceptionError extends S.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class ResourceAlreadyExistsExceptionError extends S.TaggedError<ResourceAlreadyExistsExceptionError>()("ResourceAlreadyExistsException", ResourceAlreadyExistsException.fields) {};
export class UnsupportedOperationExceptionError extends S.TaggedError<UnsupportedOperationExceptionError>()("UnsupportedOperationException", UnsupportedOperationException.fields) {};
export class ConditionalCheckFailedExceptionError extends S.TaggedError<ConditionalCheckFailedExceptionError>()("ConditionalCheckFailedException", ConditionalCheckFailedException.fields) {};
export class UpdateOutOfSyncExceptionError extends S.TaggedError<UpdateOutOfSyncExceptionError>()("UpdateOutOfSyncException", UpdateOutOfSyncException.fields) {};
export class SyncConfigurationStillExistsExceptionError extends S.TaggedError<SyncConfigurationStillExistsExceptionError>()("SyncConfigurationStillExistsException", SyncConfigurationStillExistsException.fields) {};
export class UnsupportedProviderTypeExceptionError extends S.TaggedError<UnsupportedProviderTypeExceptionError>()("UnsupportedProviderTypeException", UnsupportedProviderTypeException.fields) {};
export class RetryLatestCommitFailedExceptionError extends S.TaggedError<RetryLatestCommitFailedExceptionError>()("RetryLatestCommitFailedException", RetryLatestCommitFailedException.fields) {};
export class SyncBlockerDoesNotExistExceptionError extends S.TaggedError<SyncBlockerDoesNotExistExceptionError>()("SyncBlockerDoesNotExistException", SyncBlockerDoesNotExistException.fields) {};

//# Operations
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.UntagResource" }, UntagResourceInput, UntagResourceOutput, [ResourceNotFoundExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteConnection = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.DeleteConnection" }, DeleteConnectionInput, DeleteConnectionOutput, [ResourceNotFoundExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteHost = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.DeleteHost" }, DeleteHostInput, DeleteHostOutput, [ResourceNotFoundExceptionError, ResourceUnavailableExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getHost = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.GetHost" }, GetHostInput, GetHostOutput, [ResourceNotFoundExceptionError, ResourceUnavailableExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getSyncConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.GetSyncConfiguration" }, GetSyncConfigurationInput, GetSyncConfigurationOutput, [AccessDeniedExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listConnections = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.ListConnections" }, ListConnectionsInput, ListConnectionsOutput, [ResourceNotFoundExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listRepositoryLinks = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.ListRepositoryLinks" }, ListRepositoryLinksInput, ListRepositoryLinksOutput, [AccessDeniedExceptionError, ConcurrentModificationExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listSyncConfigurations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.ListSyncConfigurations" }, ListSyncConfigurationsInput, ListSyncConfigurationsOutput, [AccessDeniedExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.ListTagsForResource" }, ListTagsForResourceInput, ListTagsForResourceOutput, [ResourceNotFoundExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.TagResource" }, TagResourceInput, TagResourceOutput, [LimitExceededExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createConnection = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.CreateConnection" }, CreateConnectionInput, CreateConnectionOutput, [LimitExceededExceptionError, ResourceNotFoundExceptionError, ResourceUnavailableExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createHost = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.CreateHost" }, CreateHostInput, CreateHostOutput, [LimitExceededExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createSyncConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.CreateSyncConfiguration" }, CreateSyncConfigurationInput, CreateSyncConfigurationOutput, [AccessDeniedExceptionError, ConcurrentModificationExceptionError, InternalServerExceptionError, InvalidInputExceptionError, LimitExceededExceptionError, ResourceAlreadyExistsExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteSyncConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.DeleteSyncConfiguration" }, DeleteSyncConfigurationInput, DeleteSyncConfigurationOutput, [AccessDeniedExceptionError, ConcurrentModificationExceptionError, InternalServerExceptionError, InvalidInputExceptionError, LimitExceededExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getConnection = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.GetConnection" }, GetConnectionInput, GetConnectionOutput, [ResourceNotFoundExceptionError, ResourceUnavailableExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getRepositoryLink = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.GetRepositoryLink" }, GetRepositoryLinkInput, GetRepositoryLinkOutput, [AccessDeniedExceptionError, ConcurrentModificationExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getSyncBlockerSummary = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.GetSyncBlockerSummary" }, GetSyncBlockerSummaryInput, GetSyncBlockerSummaryOutput, [AccessDeniedExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listHosts = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.ListHosts" }, ListHostsInput, ListHostsOutput, []), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listRepositorySyncDefinitions = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.ListRepositorySyncDefinitions" }, ListRepositorySyncDefinitionsInput, ListRepositorySyncDefinitionsOutput, [AccessDeniedExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateHost = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.UpdateHost" }, UpdateHostInput, UpdateHostOutput, [ConflictExceptionError, ResourceNotFoundExceptionError, ResourceUnavailableExceptionError, UnsupportedOperationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateRepositoryLink = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.UpdateRepositoryLink" }, UpdateRepositoryLinkInput, UpdateRepositoryLinkOutput, [AccessDeniedExceptionError, ConditionalCheckFailedExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, UpdateOutOfSyncExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateSyncConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.UpdateSyncConfiguration" }, UpdateSyncConfigurationInput, UpdateSyncConfigurationOutput, [AccessDeniedExceptionError, ConcurrentModificationExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, UpdateOutOfSyncExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createRepositoryLink = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.CreateRepositoryLink" }, CreateRepositoryLinkInput, CreateRepositoryLinkOutput, [AccessDeniedExceptionError, ConcurrentModificationExceptionError, InternalServerExceptionError, InvalidInputExceptionError, LimitExceededExceptionError, ResourceAlreadyExistsExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getRepositorySyncStatus = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.GetRepositorySyncStatus" }, GetRepositorySyncStatusInput, GetRepositorySyncStatusOutput, [AccessDeniedExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getResourceSyncStatus = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.GetResourceSyncStatus" }, GetResourceSyncStatusInput, GetResourceSyncStatusOutput, [AccessDeniedExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteRepositoryLink = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.DeleteRepositoryLink" }, DeleteRepositoryLinkInput, DeleteRepositoryLinkOutput, [AccessDeniedExceptionError, ConcurrentModificationExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, SyncConfigurationStillExistsExceptionError, ThrottlingExceptionError, UnsupportedProviderTypeExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateSyncBlocker = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2019-12-01", uri: "/", method: "POST", sdkId: "CodeStar connections", sigV4ServiceName: "codestar-connections", name: "CodeStar_connections_20191201.UpdateSyncBlocker" }, UpdateSyncBlockerInput, UpdateSyncBlockerOutput, [AccessDeniedExceptionError, InternalServerExceptionError, InvalidInputExceptionError, ResourceNotFoundExceptionError, RetryLatestCommitFailedExceptionError, SyncBlockerDoesNotExistExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
