import { Schema} from "effect"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
export const TagKeyList = Schema.Array(Schema.String);
export const DeleteReportDefinitionRequest = Schema.Struct({ReportName: Schema.String});
export const DescribeReportDefinitionsRequest = Schema.Struct({MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)});
export const ListTagsForResourceRequest = Schema.Struct({ReportName: Schema.String});
export const Tag = Schema.Struct({Key: Schema.String, Value: Schema.String});
export const TagList = Schema.Array(Tag);
export const TagResourceRequest = Schema.Struct({ReportName: Schema.String, Tags: TagList});
export const TagResourceResponse = Schema.Struct({});
export const UntagResourceRequest = Schema.Struct({ReportName: Schema.String, TagKeys: TagKeyList});
export const UntagResourceResponse = Schema.Struct({});
export const SchemaElementList = Schema.Array(Schema.String);
export const AdditionalArtifactList = Schema.Array(Schema.String);
export const ReportStatus = Schema.Struct({lastDelivery: Schema.optional(Schema.String), lastStatus: Schema.optional(Schema.String)});
export const ReportDefinition = Schema.Struct({ReportName: Schema.String, TimeUnit: Schema.String, Format: Schema.String, Compression: Schema.String, AdditionalSchemaElements: SchemaElementList, S3Bucket: Schema.String, S3Prefix: Schema.String, S3Region: Schema.String, AdditionalArtifacts: Schema.optional(AdditionalArtifactList), RefreshClosedReports: Schema.optional(Schema.Boolean), ReportVersioning: Schema.optional(Schema.String), BillingViewArn: Schema.optional(Schema.String), ReportStatus: Schema.optional(ReportStatus)});
export const ReportDefinitionList = Schema.Array(ReportDefinition);
export const DeleteReportDefinitionResponse = Schema.Struct({ResponseMessage: Schema.optional(Schema.String)});
export const DescribeReportDefinitionsResponse = Schema.Struct({ReportDefinitions: Schema.optional(ReportDefinitionList), NextToken: Schema.optional(Schema.String)});
export const ListTagsForResourceResponse = Schema.Struct({Tags: Schema.optional(TagList)});
export const PutReportDefinitionRequest = Schema.Struct({ReportDefinition: ReportDefinition, Tags: Schema.optional(TagList)});
export const PutReportDefinitionResponse = Schema.Struct({});
export const InternalErrorException = Schema.Struct({Message: Schema.optional(Schema.String)});
export const ResourceNotFoundException = Schema.Struct({Message: Schema.optional(Schema.String)});
export const ValidationException = Schema.Struct({Message: Schema.optional(Schema.String)});
export const ModifyReportDefinitionRequest = Schema.Struct({ReportName: Schema.String, ReportDefinition: ReportDefinition});
export const ModifyReportDefinitionResponse = Schema.Struct({});
export const DuplicateReportNameException = Schema.Struct({Message: Schema.optional(Schema.String)});
export const ReportLimitReachedException = Schema.Struct({Message: Schema.optional(Schema.String)});
export const DescribeReportDefinitions = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-01-06", uri: "/", method: "POST", sdkId: "Cost and Usage Report Service", sigV4ServiceName: "cur", name: "AWSOrigamiServiceGatewayService.DescribeReportDefinitions" }, DescribeReportDefinitionsRequest, DescribeReportDefinitionsResponse, ErrorAnnotation("InternalErrorException", InternalErrorException)), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const ListTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-01-06", uri: "/", method: "POST", sdkId: "Cost and Usage Report Service", sigV4ServiceName: "cur", name: "AWSOrigamiServiceGatewayService.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, Schema.Union(ErrorAnnotation("InternalErrorException", InternalErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-01-06", uri: "/", method: "POST", sdkId: "Cost and Usage Report Service", sigV4ServiceName: "cur", name: "AWSOrigamiServiceGatewayService.TagResource" }, TagResourceRequest, TagResourceResponse, Schema.Union(ErrorAnnotation("InternalErrorException", InternalErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-01-06", uri: "/", method: "POST", sdkId: "Cost and Usage Report Service", sigV4ServiceName: "cur", name: "AWSOrigamiServiceGatewayService.UntagResource" }, UntagResourceRequest, UntagResourceResponse, Schema.Union(ErrorAnnotation("InternalErrorException", InternalErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const DeleteReportDefinition = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-01-06", uri: "/", method: "POST", sdkId: "Cost and Usage Report Service", sigV4ServiceName: "cur", name: "AWSOrigamiServiceGatewayService.DeleteReportDefinition" }, DeleteReportDefinitionRequest, DeleteReportDefinitionResponse, Schema.Union(ErrorAnnotation("InternalErrorException", InternalErrorException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const ModifyReportDefinition = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-01-06", uri: "/", method: "POST", sdkId: "Cost and Usage Report Service", sigV4ServiceName: "cur", name: "AWSOrigamiServiceGatewayService.ModifyReportDefinition" }, ModifyReportDefinitionRequest, ModifyReportDefinitionResponse, Schema.Union(ErrorAnnotation("InternalErrorException", InternalErrorException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const PutReportDefinition = /*#__PURE__*/ makeOperation(() => Operation({ version: "2017-01-06", uri: "/", method: "POST", sdkId: "Cost and Usage Report Service", sigV4ServiceName: "cur", name: "AWSOrigamiServiceGatewayService.PutReportDefinition" }, PutReportDefinitionRequest, PutReportDefinitionResponse, Schema.Union(ErrorAnnotation("DuplicateReportNameException", DuplicateReportNameException), ErrorAnnotation("InternalErrorException", InternalErrorException), ErrorAnnotation("ReportLimitReachedException", ReportLimitReachedException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
