import * as S from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const PLSubnetArnList = S.Array(S.String);
export const PLSecurityGroupArnList = S.Array(S.String);
export const AgentArnList = S.Array(S.String);
export const Ec2SecurityGroupArnList = S.Array(S.String);
export const DnsIpList = S.Array(S.String);
export const TagKeyList = S.Array(S.String);
export class CancelTaskExecutionRequest extends S.Class<CancelTaskExecutionRequest>("CancelTaskExecutionRequest")({TaskExecutionArn: S.String}) {}
export class CancelTaskExecutionResponse extends S.Class<CancelTaskExecutionResponse>("CancelTaskExecutionResponse")({}) {}
export class TagListEntry extends S.Class<TagListEntry>("TagListEntry")({Key: S.String, Value: S.optional(S.String)}) {}
export const InputTagList = S.Array(TagListEntry);
export class CreateLocationFsxLustreRequest extends S.Class<CreateLocationFsxLustreRequest>("CreateLocationFsxLustreRequest")({FsxFilesystemArn: S.String, SecurityGroupArns: Ec2SecurityGroupArnList, Subdirectory: S.optional(S.String), Tags: S.optional(InputTagList)}) {}
export class NfsMountOptions extends S.Class<NfsMountOptions>("NfsMountOptions")({Version: S.optional(S.String)}) {}
export class FsxProtocolNfs extends S.Class<FsxProtocolNfs>("FsxProtocolNfs")({MountOptions: S.optional(NfsMountOptions)}) {}
export class SmbMountOptions extends S.Class<SmbMountOptions>("SmbMountOptions")({Version: S.optional(S.String)}) {}
export class FsxProtocolSmb extends S.Class<FsxProtocolSmb>("FsxProtocolSmb")({Domain: S.optional(S.String), MountOptions: S.optional(SmbMountOptions), Password: S.String, User: S.String}) {}
export class FsxProtocol extends S.Class<FsxProtocol>("FsxProtocol")({NFS: S.optional(FsxProtocolNfs), SMB: S.optional(FsxProtocolSmb)}) {}
export class CreateLocationFsxOpenZfsRequest extends S.Class<CreateLocationFsxOpenZfsRequest>("CreateLocationFsxOpenZfsRequest")({FsxFilesystemArn: S.String, Protocol: FsxProtocol, SecurityGroupArns: Ec2SecurityGroupArnList, Subdirectory: S.optional(S.String), Tags: S.optional(InputTagList)}) {}
export class CreateLocationFsxWindowsRequest extends S.Class<CreateLocationFsxWindowsRequest>("CreateLocationFsxWindowsRequest")({Subdirectory: S.optional(S.String), FsxFilesystemArn: S.String, SecurityGroupArns: Ec2SecurityGroupArnList, Tags: S.optional(InputTagList), User: S.String, Domain: S.optional(S.String), Password: S.String}) {}
export class CmkSecretConfig extends S.Class<CmkSecretConfig>("CmkSecretConfig")({SecretArn: S.optional(S.String), KmsKeyArn: S.optional(S.String)}) {}
export class CustomSecretConfig extends S.Class<CustomSecretConfig>("CustomSecretConfig")({SecretArn: S.optional(S.String), SecretAccessRoleArn: S.optional(S.String)}) {}
export class CreateLocationObjectStorageRequest extends S.Class<CreateLocationObjectStorageRequest>("CreateLocationObjectStorageRequest")({ServerHostname: S.String, ServerPort: S.optional(S.Number), ServerProtocol: S.optional(S.String), Subdirectory: S.optional(S.String), BucketName: S.String, AccessKey: S.optional(S.String), SecretKey: S.optional(S.String), AgentArns: S.optional(AgentArnList), Tags: S.optional(InputTagList), ServerCertificate: S.optional(H.StreamBody()), CmkSecretConfig: S.optional(CmkSecretConfig), CustomSecretConfig: S.optional(CustomSecretConfig)}) {}
export class DeleteAgentRequest extends S.Class<DeleteAgentRequest>("DeleteAgentRequest")({AgentArn: S.String}) {}
export class DeleteAgentResponse extends S.Class<DeleteAgentResponse>("DeleteAgentResponse")({}) {}
export class DeleteLocationRequest extends S.Class<DeleteLocationRequest>("DeleteLocationRequest")({LocationArn: S.String}) {}
export class DeleteLocationResponse extends S.Class<DeleteLocationResponse>("DeleteLocationResponse")({}) {}
export class DeleteTaskRequest extends S.Class<DeleteTaskRequest>("DeleteTaskRequest")({TaskArn: S.String}) {}
export class DeleteTaskResponse extends S.Class<DeleteTaskResponse>("DeleteTaskResponse")({}) {}
export class DescribeAgentRequest extends S.Class<DescribeAgentRequest>("DescribeAgentRequest")({AgentArn: S.String}) {}
export class DescribeLocationAzureBlobRequest extends S.Class<DescribeLocationAzureBlobRequest>("DescribeLocationAzureBlobRequest")({LocationArn: S.String}) {}
export class DescribeLocationEfsRequest extends S.Class<DescribeLocationEfsRequest>("DescribeLocationEfsRequest")({LocationArn: S.String}) {}
export class DescribeLocationFsxLustreRequest extends S.Class<DescribeLocationFsxLustreRequest>("DescribeLocationFsxLustreRequest")({LocationArn: S.String}) {}
export class DescribeLocationFsxOntapRequest extends S.Class<DescribeLocationFsxOntapRequest>("DescribeLocationFsxOntapRequest")({LocationArn: S.String}) {}
export class DescribeLocationFsxOpenZfsRequest extends S.Class<DescribeLocationFsxOpenZfsRequest>("DescribeLocationFsxOpenZfsRequest")({LocationArn: S.String}) {}
export class DescribeLocationFsxWindowsRequest extends S.Class<DescribeLocationFsxWindowsRequest>("DescribeLocationFsxWindowsRequest")({LocationArn: S.String}) {}
export class DescribeLocationHdfsRequest extends S.Class<DescribeLocationHdfsRequest>("DescribeLocationHdfsRequest")({LocationArn: S.String}) {}
export class DescribeLocationNfsRequest extends S.Class<DescribeLocationNfsRequest>("DescribeLocationNfsRequest")({LocationArn: S.String}) {}
export class DescribeLocationObjectStorageRequest extends S.Class<DescribeLocationObjectStorageRequest>("DescribeLocationObjectStorageRequest")({LocationArn: S.String}) {}
export class DescribeLocationS3Request extends S.Class<DescribeLocationS3Request>("DescribeLocationS3Request")({LocationArn: S.String}) {}
export class DescribeLocationSmbRequest extends S.Class<DescribeLocationSmbRequest>("DescribeLocationSmbRequest")({LocationArn: S.String}) {}
export class DescribeTaskRequest extends S.Class<DescribeTaskRequest>("DescribeTaskRequest")({TaskArn: S.String}) {}
export class DescribeTaskExecutionRequest extends S.Class<DescribeTaskExecutionRequest>("DescribeTaskExecutionRequest")({TaskExecutionArn: S.String}) {}
export class ListAgentsRequest extends S.Class<ListAgentsRequest>("ListAgentsRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListTaskExecutionsRequest extends S.Class<ListTaskExecutionsRequest>("ListTaskExecutionsRequest")({TaskArn: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class Options extends S.Class<Options>("Options")({VerifyMode: S.optional(S.String), OverwriteMode: S.optional(S.String), Atime: S.optional(S.String), Mtime: S.optional(S.String), Uid: S.optional(S.String), Gid: S.optional(S.String), PreserveDeletedFiles: S.optional(S.String), PreserveDevices: S.optional(S.String), PosixPermissions: S.optional(S.String), BytesPerSecond: S.optional(S.Number), TaskQueueing: S.optional(S.String), LogLevel: S.optional(S.String), TransferMode: S.optional(S.String), SecurityDescriptorCopyFlags: S.optional(S.String), ObjectTags: S.optional(S.String)}) {}
export class FilterRule extends S.Class<FilterRule>("FilterRule")({FilterType: S.optional(S.String), Value: S.optional(S.String)}) {}
export const FilterList = S.Array(FilterRule);
export class S3ManifestConfig extends S.Class<S3ManifestConfig>("S3ManifestConfig")({ManifestObjectPath: S.String, BucketAccessRoleArn: S.String, S3BucketArn: S.String, ManifestObjectVersionId: S.optional(S.String)}) {}
export class SourceManifestConfig extends S.Class<SourceManifestConfig>("SourceManifestConfig")({S3: S3ManifestConfig}) {}
export class ManifestConfig extends S.Class<ManifestConfig>("ManifestConfig")({Action: S.optional(S.String), Format: S.optional(S.String), Source: S.optional(SourceManifestConfig)}) {}
export class ReportDestinationS3 extends S.Class<ReportDestinationS3>("ReportDestinationS3")({Subdirectory: S.optional(S.String), S3BucketArn: S.String, BucketAccessRoleArn: S.String}) {}
export class ReportDestination extends S.Class<ReportDestination>("ReportDestination")({S3: S.optional(ReportDestinationS3)}) {}
export class ReportOverride extends S.Class<ReportOverride>("ReportOverride")({ReportLevel: S.optional(S.String)}) {}
export class ReportOverrides extends S.Class<ReportOverrides>("ReportOverrides")({Transferred: S.optional(ReportOverride), Verified: S.optional(ReportOverride), Deleted: S.optional(ReportOverride), Skipped: S.optional(ReportOverride)}) {}
export class TaskReportConfig extends S.Class<TaskReportConfig>("TaskReportConfig")({Destination: S.optional(ReportDestination), OutputType: S.optional(S.String), ReportLevel: S.optional(S.String), ObjectVersionIds: S.optional(S.String), Overrides: S.optional(ReportOverrides)}) {}
export class StartTaskExecutionRequest extends S.Class<StartTaskExecutionRequest>("StartTaskExecutionRequest")({TaskArn: S.String, OverrideOptions: S.optional(Options), Includes: S.optional(FilterList), Excludes: S.optional(FilterList), ManifestConfig: S.optional(ManifestConfig), TaskReportConfig: S.optional(TaskReportConfig), Tags: S.optional(InputTagList)}) {}
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceArn: S.String, Tags: InputTagList}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceArn: S.String, Keys: TagKeyList}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class UpdateAgentRequest extends S.Class<UpdateAgentRequest>("UpdateAgentRequest")({AgentArn: S.String, Name: S.optional(S.String)}) {}
export class UpdateAgentResponse extends S.Class<UpdateAgentResponse>("UpdateAgentResponse")({}) {}
export class AzureBlobSasConfiguration extends S.Class<AzureBlobSasConfiguration>("AzureBlobSasConfiguration")({Token: S.String}) {}
export class UpdateLocationAzureBlobRequest extends S.Class<UpdateLocationAzureBlobRequest>("UpdateLocationAzureBlobRequest")({LocationArn: S.String, Subdirectory: S.optional(S.String), AuthenticationType: S.optional(S.String), SasConfiguration: S.optional(AzureBlobSasConfiguration), BlobType: S.optional(S.String), AccessTier: S.optional(S.String), AgentArns: S.optional(AgentArnList), CmkSecretConfig: S.optional(CmkSecretConfig), CustomSecretConfig: S.optional(CustomSecretConfig)}) {}
export class UpdateLocationAzureBlobResponse extends S.Class<UpdateLocationAzureBlobResponse>("UpdateLocationAzureBlobResponse")({}) {}
export class UpdateLocationEfsRequest extends S.Class<UpdateLocationEfsRequest>("UpdateLocationEfsRequest")({LocationArn: S.String, Subdirectory: S.optional(S.String), AccessPointArn: S.optional(S.String), FileSystemAccessRoleArn: S.optional(S.String), InTransitEncryption: S.optional(S.String)}) {}
export class UpdateLocationEfsResponse extends S.Class<UpdateLocationEfsResponse>("UpdateLocationEfsResponse")({}) {}
export class UpdateLocationFsxLustreRequest extends S.Class<UpdateLocationFsxLustreRequest>("UpdateLocationFsxLustreRequest")({LocationArn: S.String, Subdirectory: S.optional(S.String)}) {}
export class UpdateLocationFsxLustreResponse extends S.Class<UpdateLocationFsxLustreResponse>("UpdateLocationFsxLustreResponse")({}) {}
export class UpdateLocationFsxOpenZfsRequest extends S.Class<UpdateLocationFsxOpenZfsRequest>("UpdateLocationFsxOpenZfsRequest")({LocationArn: S.String, Protocol: S.optional(FsxProtocol), Subdirectory: S.optional(S.String)}) {}
export class UpdateLocationFsxOpenZfsResponse extends S.Class<UpdateLocationFsxOpenZfsResponse>("UpdateLocationFsxOpenZfsResponse")({}) {}
export class UpdateLocationFsxWindowsRequest extends S.Class<UpdateLocationFsxWindowsRequest>("UpdateLocationFsxWindowsRequest")({LocationArn: S.String, Subdirectory: S.optional(S.String), Domain: S.optional(S.String), User: S.optional(S.String), Password: S.optional(S.String)}) {}
export class UpdateLocationFsxWindowsResponse extends S.Class<UpdateLocationFsxWindowsResponse>("UpdateLocationFsxWindowsResponse")({}) {}
export class HdfsNameNode extends S.Class<HdfsNameNode>("HdfsNameNode")({Hostname: S.String, Port: S.Number}) {}
export const HdfsNameNodeList = S.Array(HdfsNameNode);
export class QopConfiguration extends S.Class<QopConfiguration>("QopConfiguration")({RpcProtection: S.optional(S.String), DataTransferProtection: S.optional(S.String)}) {}
export class UpdateLocationHdfsRequest extends S.Class<UpdateLocationHdfsRequest>("UpdateLocationHdfsRequest")({LocationArn: S.String, Subdirectory: S.optional(S.String), NameNodes: S.optional(HdfsNameNodeList), BlockSize: S.optional(S.Number), ReplicationFactor: S.optional(S.Number), KmsKeyProviderUri: S.optional(S.String), QopConfiguration: S.optional(QopConfiguration), AuthenticationType: S.optional(S.String), SimpleUser: S.optional(S.String), KerberosPrincipal: S.optional(S.String), KerberosKeytab: S.optional(H.StreamBody()), KerberosKrb5Conf: S.optional(H.StreamBody()), AgentArns: S.optional(AgentArnList)}) {}
export class UpdateLocationHdfsResponse extends S.Class<UpdateLocationHdfsResponse>("UpdateLocationHdfsResponse")({}) {}
export class OnPremConfig extends S.Class<OnPremConfig>("OnPremConfig")({AgentArns: AgentArnList}) {}
export class UpdateLocationNfsRequest extends S.Class<UpdateLocationNfsRequest>("UpdateLocationNfsRequest")({LocationArn: S.String, Subdirectory: S.optional(S.String), ServerHostname: S.optional(S.String), OnPremConfig: S.optional(OnPremConfig), MountOptions: S.optional(NfsMountOptions)}) {}
export class UpdateLocationNfsResponse extends S.Class<UpdateLocationNfsResponse>("UpdateLocationNfsResponse")({}) {}
export class UpdateLocationObjectStorageRequest extends S.Class<UpdateLocationObjectStorageRequest>("UpdateLocationObjectStorageRequest")({LocationArn: S.String, ServerPort: S.optional(S.Number), ServerProtocol: S.optional(S.String), Subdirectory: S.optional(S.String), ServerHostname: S.optional(S.String), AccessKey: S.optional(S.String), SecretKey: S.optional(S.String), AgentArns: S.optional(AgentArnList), ServerCertificate: S.optional(H.StreamBody()), CmkSecretConfig: S.optional(CmkSecretConfig), CustomSecretConfig: S.optional(CustomSecretConfig)}) {}
export class UpdateLocationObjectStorageResponse extends S.Class<UpdateLocationObjectStorageResponse>("UpdateLocationObjectStorageResponse")({}) {}
export class S3Config extends S.Class<S3Config>("S3Config")({BucketAccessRoleArn: S.String}) {}
export class UpdateLocationS3Request extends S.Class<UpdateLocationS3Request>("UpdateLocationS3Request")({LocationArn: S.String, Subdirectory: S.optional(S.String), S3StorageClass: S.optional(S.String), S3Config: S.optional(S3Config)}) {}
export class UpdateLocationS3Response extends S.Class<UpdateLocationS3Response>("UpdateLocationS3Response")({}) {}
export class UpdateLocationSmbRequest extends S.Class<UpdateLocationSmbRequest>("UpdateLocationSmbRequest")({LocationArn: S.String, Subdirectory: S.optional(S.String), ServerHostname: S.optional(S.String), User: S.optional(S.String), Domain: S.optional(S.String), Password: S.optional(S.String), CmkSecretConfig: S.optional(CmkSecretConfig), CustomSecretConfig: S.optional(CustomSecretConfig), AgentArns: S.optional(AgentArnList), MountOptions: S.optional(SmbMountOptions), AuthenticationType: S.optional(S.String), DnsIpAddresses: S.optional(DnsIpList), KerberosPrincipal: S.optional(S.String), KerberosKeytab: S.optional(H.StreamBody()), KerberosKrb5Conf: S.optional(H.StreamBody())}) {}
export class UpdateLocationSmbResponse extends S.Class<UpdateLocationSmbResponse>("UpdateLocationSmbResponse")({}) {}
export class TaskSchedule extends S.Class<TaskSchedule>("TaskSchedule")({ScheduleExpression: S.String, Status: S.optional(S.String)}) {}
export class UpdateTaskRequest extends S.Class<UpdateTaskRequest>("UpdateTaskRequest")({TaskArn: S.String, Options: S.optional(Options), Excludes: S.optional(FilterList), Schedule: S.optional(TaskSchedule), Name: S.optional(S.String), CloudWatchLogGroupArn: S.optional(S.String), Includes: S.optional(FilterList), ManifestConfig: S.optional(ManifestConfig), TaskReportConfig: S.optional(TaskReportConfig)}) {}
export class UpdateTaskResponse extends S.Class<UpdateTaskResponse>("UpdateTaskResponse")({}) {}
export class UpdateTaskExecutionRequest extends S.Class<UpdateTaskExecutionRequest>("UpdateTaskExecutionRequest")({TaskExecutionArn: S.String, Options: Options}) {}
export class UpdateTaskExecutionResponse extends S.Class<UpdateTaskExecutionResponse>("UpdateTaskExecutionResponse")({}) {}
export const FilterValues = S.Array(S.String);
export class Ec2Config extends S.Class<Ec2Config>("Ec2Config")({SubnetArn: S.String, SecurityGroupArns: Ec2SecurityGroupArnList}) {}
export const SourceNetworkInterfaceArns = S.Array(S.String);
export const DestinationNetworkInterfaceArns = S.Array(S.String);
export class LocationFilter extends S.Class<LocationFilter>("LocationFilter")({Name: S.String, Values: FilterValues, Operator: S.String}) {}
export const LocationFilters = S.Array(LocationFilter);
export const OutputTagList = S.Array(TagListEntry);
export class TaskFilter extends S.Class<TaskFilter>("TaskFilter")({Name: S.String, Values: FilterValues, Operator: S.String}) {}
export const TaskFilters = S.Array(TaskFilter);
export class InternalException extends S.Class<InternalException>("InternalException")({message: S.optional(S.String), errorCode: S.optional(S.String)}) {}
export class CreateAgentRequest extends S.Class<CreateAgentRequest>("CreateAgentRequest")({ActivationKey: S.String, AgentName: S.optional(S.String), Tags: S.optional(InputTagList), VpcEndpointId: S.optional(S.String), SubnetArns: S.optional(PLSubnetArnList), SecurityGroupArns: S.optional(PLSecurityGroupArnList)}) {}
export class CreateLocationAzureBlobRequest extends S.Class<CreateLocationAzureBlobRequest>("CreateLocationAzureBlobRequest")({ContainerUrl: S.String, AuthenticationType: S.String, SasConfiguration: S.optional(AzureBlobSasConfiguration), BlobType: S.optional(S.String), AccessTier: S.optional(S.String), Subdirectory: S.optional(S.String), AgentArns: S.optional(AgentArnList), Tags: S.optional(InputTagList), CmkSecretConfig: S.optional(CmkSecretConfig), CustomSecretConfig: S.optional(CustomSecretConfig)}) {}
export class CreateLocationEfsRequest extends S.Class<CreateLocationEfsRequest>("CreateLocationEfsRequest")({Subdirectory: S.optional(S.String), EfsFilesystemArn: S.String, Ec2Config: Ec2Config, Tags: S.optional(InputTagList), AccessPointArn: S.optional(S.String), FileSystemAccessRoleArn: S.optional(S.String), InTransitEncryption: S.optional(S.String)}) {}
export class CreateLocationFsxLustreResponse extends S.Class<CreateLocationFsxLustreResponse>("CreateLocationFsxLustreResponse")({LocationArn: S.optional(S.String)}) {}
export class CreateLocationFsxOpenZfsResponse extends S.Class<CreateLocationFsxOpenZfsResponse>("CreateLocationFsxOpenZfsResponse")({LocationArn: S.optional(S.String)}) {}
export class CreateLocationFsxWindowsResponse extends S.Class<CreateLocationFsxWindowsResponse>("CreateLocationFsxWindowsResponse")({LocationArn: S.optional(S.String)}) {}
export class CreateLocationHdfsRequest extends S.Class<CreateLocationHdfsRequest>("CreateLocationHdfsRequest")({Subdirectory: S.optional(S.String), NameNodes: HdfsNameNodeList, BlockSize: S.optional(S.Number), ReplicationFactor: S.optional(S.Number), KmsKeyProviderUri: S.optional(S.String), QopConfiguration: S.optional(QopConfiguration), AuthenticationType: S.String, SimpleUser: S.optional(S.String), KerberosPrincipal: S.optional(S.String), KerberosKeytab: S.optional(H.StreamBody()), KerberosKrb5Conf: S.optional(H.StreamBody()), AgentArns: AgentArnList, Tags: S.optional(InputTagList)}) {}
export class CreateLocationNfsRequest extends S.Class<CreateLocationNfsRequest>("CreateLocationNfsRequest")({Subdirectory: S.String, ServerHostname: S.String, OnPremConfig: OnPremConfig, MountOptions: S.optional(NfsMountOptions), Tags: S.optional(InputTagList)}) {}
export class CreateLocationObjectStorageResponse extends S.Class<CreateLocationObjectStorageResponse>("CreateLocationObjectStorageResponse")({LocationArn: S.optional(S.String)}) {}
export class CreateLocationS3Request extends S.Class<CreateLocationS3Request>("CreateLocationS3Request")({Subdirectory: S.optional(S.String), S3BucketArn: S.String, S3StorageClass: S.optional(S.String), S3Config: S3Config, AgentArns: S.optional(AgentArnList), Tags: S.optional(InputTagList)}) {}
export class CreateLocationSmbRequest extends S.Class<CreateLocationSmbRequest>("CreateLocationSmbRequest")({Subdirectory: S.String, ServerHostname: S.String, User: S.optional(S.String), Domain: S.optional(S.String), Password: S.optional(S.String), CmkSecretConfig: S.optional(CmkSecretConfig), CustomSecretConfig: S.optional(CustomSecretConfig), AgentArns: AgentArnList, MountOptions: S.optional(SmbMountOptions), Tags: S.optional(InputTagList), AuthenticationType: S.optional(S.String), DnsIpAddresses: S.optional(DnsIpList), KerberosPrincipal: S.optional(S.String), KerberosKeytab: S.optional(H.StreamBody()), KerberosKrb5Conf: S.optional(H.StreamBody())}) {}
export class InvalidRequestException extends S.Class<InvalidRequestException>("InvalidRequestException")({message: S.optional(S.String), errorCode: S.optional(S.String), datasyncErrorCode: S.optional(S.String)}) {}
export class DescribeLocationEfsResponse extends S.Class<DescribeLocationEfsResponse>("DescribeLocationEfsResponse")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), Ec2Config: S.optional(Ec2Config), CreationTime: S.optional(S.Date), AccessPointArn: S.optional(S.String), FileSystemAccessRoleArn: S.optional(S.String), InTransitEncryption: S.optional(S.String)}) {}
export class DescribeLocationFsxLustreResponse extends S.Class<DescribeLocationFsxLustreResponse>("DescribeLocationFsxLustreResponse")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), SecurityGroupArns: S.optional(Ec2SecurityGroupArnList), CreationTime: S.optional(S.Date)}) {}
export class DescribeLocationFsxOntapResponse extends S.Class<DescribeLocationFsxOntapResponse>("DescribeLocationFsxOntapResponse")({CreationTime: S.optional(S.Date), LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), Protocol: S.optional(FsxProtocol), SecurityGroupArns: S.optional(Ec2SecurityGroupArnList), StorageVirtualMachineArn: S.optional(S.String), FsxFilesystemArn: S.optional(S.String)}) {}
export class DescribeLocationFsxOpenZfsResponse extends S.Class<DescribeLocationFsxOpenZfsResponse>("DescribeLocationFsxOpenZfsResponse")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), SecurityGroupArns: S.optional(Ec2SecurityGroupArnList), Protocol: S.optional(FsxProtocol), CreationTime: S.optional(S.Date)}) {}
export class DescribeLocationFsxWindowsResponse extends S.Class<DescribeLocationFsxWindowsResponse>("DescribeLocationFsxWindowsResponse")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), SecurityGroupArns: S.optional(Ec2SecurityGroupArnList), CreationTime: S.optional(S.Date), User: S.optional(S.String), Domain: S.optional(S.String)}) {}
export class DescribeLocationHdfsResponse extends S.Class<DescribeLocationHdfsResponse>("DescribeLocationHdfsResponse")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), NameNodes: S.optional(HdfsNameNodeList), BlockSize: S.optional(S.Number), ReplicationFactor: S.optional(S.Number), KmsKeyProviderUri: S.optional(S.String), QopConfiguration: S.optional(QopConfiguration), AuthenticationType: S.optional(S.String), SimpleUser: S.optional(S.String), KerberosPrincipal: S.optional(S.String), AgentArns: S.optional(AgentArnList), CreationTime: S.optional(S.Date)}) {}
export class DescribeLocationNfsResponse extends S.Class<DescribeLocationNfsResponse>("DescribeLocationNfsResponse")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), OnPremConfig: S.optional(OnPremConfig), MountOptions: S.optional(NfsMountOptions), CreationTime: S.optional(S.Date)}) {}
export class ManagedSecretConfig extends S.Class<ManagedSecretConfig>("ManagedSecretConfig")({SecretArn: S.optional(S.String)}) {}
export class DescribeLocationObjectStorageResponse extends S.Class<DescribeLocationObjectStorageResponse>("DescribeLocationObjectStorageResponse")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), AccessKey: S.optional(S.String), ServerPort: S.optional(S.Number), ServerProtocol: S.optional(S.String), AgentArns: S.optional(AgentArnList), CreationTime: S.optional(S.Date), ServerCertificate: S.optional(H.StreamBody()), ManagedSecretConfig: S.optional(ManagedSecretConfig), CmkSecretConfig: S.optional(CmkSecretConfig), CustomSecretConfig: S.optional(CustomSecretConfig)}) {}
export class DescribeLocationS3Response extends S.Class<DescribeLocationS3Response>("DescribeLocationS3Response")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), S3StorageClass: S.optional(S.String), S3Config: S.optional(S3Config), AgentArns: S.optional(AgentArnList), CreationTime: S.optional(S.Date)}) {}
export class DescribeLocationSmbResponse extends S.Class<DescribeLocationSmbResponse>("DescribeLocationSmbResponse")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), AgentArns: S.optional(AgentArnList), User: S.optional(S.String), Domain: S.optional(S.String), MountOptions: S.optional(SmbMountOptions), CreationTime: S.optional(S.Date), DnsIpAddresses: S.optional(DnsIpList), KerberosPrincipal: S.optional(S.String), AuthenticationType: S.optional(S.String), ManagedSecretConfig: S.optional(ManagedSecretConfig), CmkSecretConfig: S.optional(CmkSecretConfig), CustomSecretConfig: S.optional(CustomSecretConfig)}) {}
export class ListLocationsRequest extends S.Class<ListLocationsRequest>("ListLocationsRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), Filters: S.optional(LocationFilters)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: S.optional(OutputTagList), NextToken: S.optional(S.String)}) {}
export class ListTasksRequest extends S.Class<ListTasksRequest>("ListTasksRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), Filters: S.optional(TaskFilters)}) {}
export class StartTaskExecutionResponse extends S.Class<StartTaskExecutionResponse>("StartTaskExecutionResponse")({TaskExecutionArn: S.optional(S.String)}) {}
export class FsxUpdateProtocolSmb extends S.Class<FsxUpdateProtocolSmb>("FsxUpdateProtocolSmb")({Domain: S.optional(S.String), MountOptions: S.optional(SmbMountOptions), Password: S.optional(S.String), User: S.optional(S.String)}) {}
export class PrivateLinkConfig extends S.Class<PrivateLinkConfig>("PrivateLinkConfig")({VpcEndpointId: S.optional(S.String), PrivateLinkEndpoint: S.optional(S.String), SubnetArns: S.optional(PLSubnetArnList), SecurityGroupArns: S.optional(PLSecurityGroupArnList)}) {}
export class Platform extends S.Class<Platform>("Platform")({Version: S.optional(S.String)}) {}
export class TaskScheduleDetails extends S.Class<TaskScheduleDetails>("TaskScheduleDetails")({StatusUpdateTime: S.optional(S.Date), DisabledReason: S.optional(S.String), DisabledBy: S.optional(S.String)}) {}
export class TaskExecutionResultDetail extends S.Class<TaskExecutionResultDetail>("TaskExecutionResultDetail")({PrepareDuration: S.optional(S.Number), PrepareStatus: S.optional(S.String), TotalDuration: S.optional(S.Number), TransferDuration: S.optional(S.Number), TransferStatus: S.optional(S.String), VerifyDuration: S.optional(S.Number), VerifyStatus: S.optional(S.String), ErrorCode: S.optional(S.String), ErrorDetail: S.optional(S.String)}) {}
export class ReportResult extends S.Class<ReportResult>("ReportResult")({Status: S.optional(S.String), ErrorCode: S.optional(S.String), ErrorDetail: S.optional(S.String)}) {}
export class TaskExecutionFilesListedDetail extends S.Class<TaskExecutionFilesListedDetail>("TaskExecutionFilesListedDetail")({AtSource: S.optional(S.Number), AtDestinationForDelete: S.optional(S.Number)}) {}
export class TaskExecutionFilesFailedDetail extends S.Class<TaskExecutionFilesFailedDetail>("TaskExecutionFilesFailedDetail")({Prepare: S.optional(S.Number), Transfer: S.optional(S.Number), Verify: S.optional(S.Number), Delete: S.optional(S.Number)}) {}
export class TaskExecutionFoldersListedDetail extends S.Class<TaskExecutionFoldersListedDetail>("TaskExecutionFoldersListedDetail")({AtSource: S.optional(S.Number), AtDestinationForDelete: S.optional(S.Number)}) {}
export class TaskExecutionFoldersFailedDetail extends S.Class<TaskExecutionFoldersFailedDetail>("TaskExecutionFoldersFailedDetail")({List: S.optional(S.Number), Prepare: S.optional(S.Number), Transfer: S.optional(S.Number), Verify: S.optional(S.Number), Delete: S.optional(S.Number)}) {}
export class AgentListEntry extends S.Class<AgentListEntry>("AgentListEntry")({AgentArn: S.optional(S.String), Name: S.optional(S.String), Status: S.optional(S.String), Platform: S.optional(Platform)}) {}
export const AgentList = S.Array(AgentListEntry);
export class TaskExecutionListEntry extends S.Class<TaskExecutionListEntry>("TaskExecutionListEntry")({TaskExecutionArn: S.optional(S.String), Status: S.optional(S.String), TaskMode: S.optional(S.String)}) {}
export const TaskExecutionList = S.Array(TaskExecutionListEntry);
export class FsxUpdateProtocol extends S.Class<FsxUpdateProtocol>("FsxUpdateProtocol")({NFS: S.optional(FsxProtocolNfs), SMB: S.optional(FsxUpdateProtocolSmb)}) {}
export class CreateAgentResponse extends S.Class<CreateAgentResponse>("CreateAgentResponse")({AgentArn: S.optional(S.String)}) {}
export class CreateLocationAzureBlobResponse extends S.Class<CreateLocationAzureBlobResponse>("CreateLocationAzureBlobResponse")({LocationArn: S.optional(S.String)}) {}
export class CreateLocationEfsResponse extends S.Class<CreateLocationEfsResponse>("CreateLocationEfsResponse")({LocationArn: S.optional(S.String)}) {}
export class CreateLocationFsxOntapRequest extends S.Class<CreateLocationFsxOntapRequest>("CreateLocationFsxOntapRequest")({Protocol: FsxProtocol, SecurityGroupArns: Ec2SecurityGroupArnList, StorageVirtualMachineArn: S.String, Subdirectory: S.optional(S.String), Tags: S.optional(InputTagList)}) {}
export class CreateLocationHdfsResponse extends S.Class<CreateLocationHdfsResponse>("CreateLocationHdfsResponse")({LocationArn: S.optional(S.String)}) {}
export class CreateLocationNfsResponse extends S.Class<CreateLocationNfsResponse>("CreateLocationNfsResponse")({LocationArn: S.optional(S.String)}) {}
export class CreateLocationS3Response extends S.Class<CreateLocationS3Response>("CreateLocationS3Response")({LocationArn: S.optional(S.String)}) {}
export class CreateLocationSmbResponse extends S.Class<CreateLocationSmbResponse>("CreateLocationSmbResponse")({LocationArn: S.optional(S.String)}) {}
export class DescribeAgentResponse extends S.Class<DescribeAgentResponse>("DescribeAgentResponse")({AgentArn: S.optional(S.String), Name: S.optional(S.String), Status: S.optional(S.String), LastConnectionTime: S.optional(S.Date), CreationTime: S.optional(S.Date), EndpointType: S.optional(S.String), PrivateLinkConfig: S.optional(PrivateLinkConfig), Platform: S.optional(Platform)}) {}
export class DescribeLocationAzureBlobResponse extends S.Class<DescribeLocationAzureBlobResponse>("DescribeLocationAzureBlobResponse")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String), AuthenticationType: S.optional(S.String), BlobType: S.optional(S.String), AccessTier: S.optional(S.String), AgentArns: S.optional(AgentArnList), CreationTime: S.optional(S.Date), ManagedSecretConfig: S.optional(ManagedSecretConfig), CmkSecretConfig: S.optional(CmkSecretConfig), CustomSecretConfig: S.optional(CustomSecretConfig)}) {}
export class DescribeTaskResponse extends S.Class<DescribeTaskResponse>("DescribeTaskResponse")({TaskArn: S.optional(S.String), Status: S.optional(S.String), Name: S.optional(S.String), CurrentTaskExecutionArn: S.optional(S.String), SourceLocationArn: S.optional(S.String), DestinationLocationArn: S.optional(S.String), CloudWatchLogGroupArn: S.optional(S.String), SourceNetworkInterfaceArns: S.optional(SourceNetworkInterfaceArns), DestinationNetworkInterfaceArns: S.optional(DestinationNetworkInterfaceArns), Options: S.optional(Options), Excludes: S.optional(FilterList), Schedule: S.optional(TaskSchedule), ErrorCode: S.optional(S.String), ErrorDetail: S.optional(S.String), CreationTime: S.optional(S.Date), Includes: S.optional(FilterList), ManifestConfig: S.optional(ManifestConfig), TaskReportConfig: S.optional(TaskReportConfig), ScheduleDetails: S.optional(TaskScheduleDetails), TaskMode: S.optional(S.String)}) {}
export class DescribeTaskExecutionResponse extends S.Class<DescribeTaskExecutionResponse>("DescribeTaskExecutionResponse")({TaskExecutionArn: S.optional(S.String), Status: S.optional(S.String), Options: S.optional(Options), Excludes: S.optional(FilterList), Includes: S.optional(FilterList), ManifestConfig: S.optional(ManifestConfig), StartTime: S.optional(S.Date), EstimatedFilesToTransfer: S.optional(S.Number), EstimatedBytesToTransfer: S.optional(S.Number), FilesTransferred: S.optional(S.Number), BytesWritten: S.optional(S.Number), BytesTransferred: S.optional(S.Number), BytesCompressed: S.optional(S.Number), Result: S.optional(TaskExecutionResultDetail), TaskReportConfig: S.optional(TaskReportConfig), FilesDeleted: S.optional(S.Number), FilesSkipped: S.optional(S.Number), FilesVerified: S.optional(S.Number), ReportResult: S.optional(ReportResult), EstimatedFilesToDelete: S.optional(S.Number), TaskMode: S.optional(S.String), FilesPrepared: S.optional(S.Number), FilesListed: S.optional(TaskExecutionFilesListedDetail), FilesFailed: S.optional(TaskExecutionFilesFailedDetail), EstimatedFoldersToDelete: S.optional(S.Number), EstimatedFoldersToTransfer: S.optional(S.Number), FoldersSkipped: S.optional(S.Number), FoldersPrepared: S.optional(S.Number), FoldersTransferred: S.optional(S.Number), FoldersVerified: S.optional(S.Number), FoldersDeleted: S.optional(S.Number), FoldersListed: S.optional(TaskExecutionFoldersListedDetail), FoldersFailed: S.optional(TaskExecutionFoldersFailedDetail), LaunchTime: S.optional(S.Date), EndTime: S.optional(S.Date)}) {}
export class ListAgentsResponse extends S.Class<ListAgentsResponse>("ListAgentsResponse")({Agents: S.optional(AgentList), NextToken: S.optional(S.String)}) {}
export class ListTaskExecutionsResponse extends S.Class<ListTaskExecutionsResponse>("ListTaskExecutionsResponse")({TaskExecutions: S.optional(TaskExecutionList), NextToken: S.optional(S.String)}) {}
export class UpdateLocationFsxOntapRequest extends S.Class<UpdateLocationFsxOntapRequest>("UpdateLocationFsxOntapRequest")({LocationArn: S.String, Protocol: S.optional(FsxUpdateProtocol), Subdirectory: S.optional(S.String)}) {}
export class UpdateLocationFsxOntapResponse extends S.Class<UpdateLocationFsxOntapResponse>("UpdateLocationFsxOntapResponse")({}) {}
export class LocationListEntry extends S.Class<LocationListEntry>("LocationListEntry")({LocationArn: S.optional(S.String), LocationUri: S.optional(S.String)}) {}
export const LocationList = S.Array(LocationListEntry);
export class TaskListEntry extends S.Class<TaskListEntry>("TaskListEntry")({TaskArn: S.optional(S.String), Status: S.optional(S.String), Name: S.optional(S.String), TaskMode: S.optional(S.String)}) {}
export const TaskList = S.Array(TaskListEntry);
export class CreateLocationFsxOntapResponse extends S.Class<CreateLocationFsxOntapResponse>("CreateLocationFsxOntapResponse")({LocationArn: S.optional(S.String)}) {}
export class CreateTaskRequest extends S.Class<CreateTaskRequest>("CreateTaskRequest")({SourceLocationArn: S.String, DestinationLocationArn: S.String, CloudWatchLogGroupArn: S.optional(S.String), Name: S.optional(S.String), Options: S.optional(Options), Excludes: S.optional(FilterList), Schedule: S.optional(TaskSchedule), Tags: S.optional(InputTagList), Includes: S.optional(FilterList), ManifestConfig: S.optional(ManifestConfig), TaskReportConfig: S.optional(TaskReportConfig), TaskMode: S.optional(S.String)}) {}
export class ListLocationsResponse extends S.Class<ListLocationsResponse>("ListLocationsResponse")({Locations: S.optional(LocationList), NextToken: S.optional(S.String)}) {}
export class ListTasksResponse extends S.Class<ListTasksResponse>("ListTasksResponse")({Tasks: S.optional(TaskList), NextToken: S.optional(S.String)}) {}
export class CreateTaskResponse extends S.Class<CreateTaskResponse>("CreateTaskResponse")({TaskArn: S.optional(S.String)}) {}

//# Errors
export class InternalExceptionError extends S.TaggedError<InternalExceptionError>()("InternalException", InternalException.fields) {};
export class InvalidRequestExceptionError extends S.TaggedError<InvalidRequestExceptionError>()("InvalidRequestException", InvalidRequestException.fields) {};

//# Operations
export const deleteLocation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DeleteLocation" }, DeleteLocationRequest, DeleteLocationResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteTask = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DeleteTask" }, DeleteTaskRequest, DeleteTaskResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.TagResource" }, TagResourceRequest, TagResourceResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAgent = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateAgent" }, UpdateAgentRequest, UpdateAgentResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationAzureBlob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationAzureBlob" }, UpdateLocationAzureBlobRequest, UpdateLocationAzureBlobResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationEfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationEfs" }, UpdateLocationEfsRequest, UpdateLocationEfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationFsxLustre = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationFsxLustre" }, UpdateLocationFsxLustreRequest, UpdateLocationFsxLustreResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationFsxOpenZfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationFsxOpenZfs" }, UpdateLocationFsxOpenZfsRequest, UpdateLocationFsxOpenZfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationFsxWindows = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationFsxWindows" }, UpdateLocationFsxWindowsRequest, UpdateLocationFsxWindowsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationHdfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationHdfs" }, UpdateLocationHdfsRequest, UpdateLocationHdfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationNfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationNfs" }, UpdateLocationNfsRequest, UpdateLocationNfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationObjectStorage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationObjectStorage" }, UpdateLocationObjectStorageRequest, UpdateLocationObjectStorageResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationS3 = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationS3" }, UpdateLocationS3Request, UpdateLocationS3Response, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationSmb = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationSmb" }, UpdateLocationSmbRequest, UpdateLocationSmbResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateTask = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateTask" }, UpdateTaskRequest, UpdateTaskResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateTaskExecution = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateTaskExecution" }, UpdateTaskExecutionRequest, UpdateTaskExecutionResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const cancelTaskExecution = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CancelTaskExecution" }, CancelTaskExecutionRequest, CancelTaskExecutionResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationFsxLustre = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationFsxLustre" }, CreateLocationFsxLustreRequest, CreateLocationFsxLustreResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationFsxOpenZfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationFsxOpenZfs" }, CreateLocationFsxOpenZfsRequest, CreateLocationFsxOpenZfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationFsxWindows = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationFsxWindows" }, CreateLocationFsxWindowsRequest, CreateLocationFsxWindowsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationObjectStorage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationObjectStorage" }, CreateLocationObjectStorageRequest, CreateLocationObjectStorageResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAgent = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DeleteAgent" }, DeleteAgentRequest, DeleteAgentResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationEfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationEfs" }, DescribeLocationEfsRequest, DescribeLocationEfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationFsxLustre = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationFsxLustre" }, DescribeLocationFsxLustreRequest, DescribeLocationFsxLustreResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationFsxOntap = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationFsxOntap" }, DescribeLocationFsxOntapRequest, DescribeLocationFsxOntapResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationFsxOpenZfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationFsxOpenZfs" }, DescribeLocationFsxOpenZfsRequest, DescribeLocationFsxOpenZfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationFsxWindows = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationFsxWindows" }, DescribeLocationFsxWindowsRequest, DescribeLocationFsxWindowsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationHdfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationHdfs" }, DescribeLocationHdfsRequest, DescribeLocationHdfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationNfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationNfs" }, DescribeLocationNfsRequest, DescribeLocationNfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationObjectStorage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationObjectStorage" }, DescribeLocationObjectStorageRequest, DescribeLocationObjectStorageResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationS3 = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationS3" }, DescribeLocationS3Request, DescribeLocationS3Response, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationSmb = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationSmb" }, DescribeLocationSmbRequest, DescribeLocationSmbResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const startTaskExecution = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.StartTaskExecution" }, StartTaskExecutionRequest, StartTaskExecutionResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createAgent = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateAgent" }, CreateAgentRequest, CreateAgentResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationAzureBlob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationAzureBlob" }, CreateLocationAzureBlobRequest, CreateLocationAzureBlobResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationEfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationEfs" }, CreateLocationEfsRequest, CreateLocationEfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationHdfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationHdfs" }, CreateLocationHdfsRequest, CreateLocationHdfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationNfs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationNfs" }, CreateLocationNfsRequest, CreateLocationNfsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationS3 = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationS3" }, CreateLocationS3Request, CreateLocationS3Response, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationSmb = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationSmb" }, CreateLocationSmbRequest, CreateLocationSmbResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAgent = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeAgent" }, DescribeAgentRequest, DescribeAgentResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLocationAzureBlob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeLocationAzureBlob" }, DescribeLocationAzureBlobRequest, DescribeLocationAzureBlobResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeTask = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeTask" }, DescribeTaskRequest, DescribeTaskResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeTaskExecution = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.DescribeTaskExecution" }, DescribeTaskExecutionRequest, DescribeTaskExecutionResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listAgents = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.ListAgents" }, ListAgentsRequest, ListAgentsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTaskExecutions = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.ListTaskExecutions" }, ListTaskExecutionsRequest, ListTaskExecutionsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLocationFsxOntap = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.UpdateLocationFsxOntap" }, UpdateLocationFsxOntapRequest, UpdateLocationFsxOntapResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLocationFsxOntap = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateLocationFsxOntap" }, CreateLocationFsxOntapRequest, CreateLocationFsxOntapResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listLocations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.ListLocations" }, ListLocationsRequest, ListLocationsResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTasks = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.ListTasks" }, ListTasksRequest, ListTasksResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createTask = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-11-09", uri: "/", method: "POST", sdkId: "DataSync", sigV4ServiceName: "datasync", name: "FmrsService.CreateTask" }, CreateTaskRequest, CreateTaskResponse, [InternalExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
