import * as S from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const AvailabilityZoneList = S.Array(S.String);
export const SecurityGroupIdentifierList = S.Array(S.String);
export const SubnetIdentifierList = S.Array(S.String);
export const NodeIdentifierList = S.Array(S.String);
export const ClusterNameList = S.Array(S.String);
export const ParameterGroupNameList = S.Array(S.String);
export const SubnetGroupNameList = S.Array(S.String);
export const KeyList = S.Array(S.String);
export class CreateParameterGroupRequest extends S.Class<CreateParameterGroupRequest>("CreateParameterGroupRequest")({ParameterGroupName: S.String, Description: S.optional(S.String)}) {}
export class CreateSubnetGroupRequest extends S.Class<CreateSubnetGroupRequest>("CreateSubnetGroupRequest")({SubnetGroupName: S.String, Description: S.optional(S.String), SubnetIds: SubnetIdentifierList}) {}
export class DecreaseReplicationFactorRequest extends S.Class<DecreaseReplicationFactorRequest>("DecreaseReplicationFactorRequest")({ClusterName: S.String, NewReplicationFactor: S.Number, AvailabilityZones: S.optional(AvailabilityZoneList), NodeIdsToRemove: S.optional(NodeIdentifierList)}) {}
export class DeleteClusterRequest extends S.Class<DeleteClusterRequest>("DeleteClusterRequest")({ClusterName: S.String}) {}
export class DeleteParameterGroupRequest extends S.Class<DeleteParameterGroupRequest>("DeleteParameterGroupRequest")({ParameterGroupName: S.String}) {}
export class DeleteSubnetGroupRequest extends S.Class<DeleteSubnetGroupRequest>("DeleteSubnetGroupRequest")({SubnetGroupName: S.String}) {}
export class DescribeClustersRequest extends S.Class<DescribeClustersRequest>("DescribeClustersRequest")({ClusterNames: S.optional(ClusterNameList), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class DescribeDefaultParametersRequest extends S.Class<DescribeDefaultParametersRequest>("DescribeDefaultParametersRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class DescribeEventsRequest extends S.Class<DescribeEventsRequest>("DescribeEventsRequest")({SourceName: S.optional(S.String), SourceType: S.optional(S.String), StartTime: S.optional(S.Date), EndTime: S.optional(S.Date), Duration: S.optional(S.Number), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class DescribeParameterGroupsRequest extends S.Class<DescribeParameterGroupsRequest>("DescribeParameterGroupsRequest")({ParameterGroupNames: S.optional(ParameterGroupNameList), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class DescribeParametersRequest extends S.Class<DescribeParametersRequest>("DescribeParametersRequest")({ParameterGroupName: S.String, Source: S.optional(S.String), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class DescribeSubnetGroupsRequest extends S.Class<DescribeSubnetGroupsRequest>("DescribeSubnetGroupsRequest")({SubnetGroupNames: S.optional(SubnetGroupNameList), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class IncreaseReplicationFactorRequest extends S.Class<IncreaseReplicationFactorRequest>("IncreaseReplicationFactorRequest")({ClusterName: S.String, NewReplicationFactor: S.Number, AvailabilityZones: S.optional(AvailabilityZoneList)}) {}
export class ListTagsRequest extends S.Class<ListTagsRequest>("ListTagsRequest")({ResourceName: S.String, NextToken: S.optional(S.String)}) {}
export class RebootNodeRequest extends S.Class<RebootNodeRequest>("RebootNodeRequest")({ClusterName: S.String, NodeId: S.String}) {}
export class Tag extends S.Class<Tag>("Tag")({Key: S.optional(S.String), Value: S.optional(S.String)}) {}
export const TagList = S.Array(Tag);
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceName: S.String, Tags: TagList}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceName: S.String, TagKeys: KeyList}) {}
export class UpdateClusterRequest extends S.Class<UpdateClusterRequest>("UpdateClusterRequest")({ClusterName: S.String, Description: S.optional(S.String), PreferredMaintenanceWindow: S.optional(S.String), NotificationTopicArn: S.optional(S.String), NotificationTopicStatus: S.optional(S.String), ParameterGroupName: S.optional(S.String), SecurityGroupIds: S.optional(SecurityGroupIdentifierList)}) {}
export class UpdateSubnetGroupRequest extends S.Class<UpdateSubnetGroupRequest>("UpdateSubnetGroupRequest")({SubnetGroupName: S.String, Description: S.optional(S.String), SubnetIds: S.optional(SubnetIdentifierList)}) {}
export class SSESpecification extends S.Class<SSESpecification>("SSESpecification")({Enabled: S.Boolean}) {}
export class Endpoint extends S.Class<Endpoint>("Endpoint")({Address: S.optional(S.String), Port: S.optional(S.Number), URL: S.optional(S.String)}) {}
export class Node extends S.Class<Node>("Node")({NodeId: S.optional(S.String), Endpoint: S.optional(Endpoint), NodeCreateTime: S.optional(S.Date), AvailabilityZone: S.optional(S.String), NodeStatus: S.optional(S.String), ParameterGroupStatus: S.optional(S.String)}) {}
export const NodeList = S.Array(Node);
export class NotificationConfiguration extends S.Class<NotificationConfiguration>("NotificationConfiguration")({TopicArn: S.optional(S.String), TopicStatus: S.optional(S.String)}) {}
export class SecurityGroupMembership extends S.Class<SecurityGroupMembership>("SecurityGroupMembership")({SecurityGroupIdentifier: S.optional(S.String), Status: S.optional(S.String)}) {}
export const SecurityGroupMembershipList = S.Array(SecurityGroupMembership);
export class ParameterGroupStatus extends S.Class<ParameterGroupStatus>("ParameterGroupStatus")({ParameterGroupName: S.optional(S.String), ParameterApplyStatus: S.optional(S.String), NodeIdsToReboot: S.optional(NodeIdentifierList)}) {}
export class SSEDescription extends S.Class<SSEDescription>("SSEDescription")({Status: S.optional(S.String)}) {}
export class Cluster extends S.Class<Cluster>("Cluster")({ClusterName: S.optional(S.String), Description: S.optional(S.String), ClusterArn: S.optional(S.String), TotalNodes: S.optional(S.Number), ActiveNodes: S.optional(S.Number), NodeType: S.optional(S.String), Status: S.optional(S.String), ClusterDiscoveryEndpoint: S.optional(Endpoint), NodeIdsToRemove: S.optional(NodeIdentifierList), Nodes: S.optional(NodeList), PreferredMaintenanceWindow: S.optional(S.String), NotificationConfiguration: S.optional(NotificationConfiguration), SubnetGroup: S.optional(S.String), SecurityGroups: S.optional(SecurityGroupMembershipList), IamRoleArn: S.optional(S.String), ParameterGroup: S.optional(ParameterGroupStatus), SSEDescription: S.optional(SSEDescription), ClusterEndpointEncryptionType: S.optional(S.String), NetworkType: S.optional(S.String)}) {}
export const ClusterList = S.Array(Cluster);
export class ParameterGroup extends S.Class<ParameterGroup>("ParameterGroup")({ParameterGroupName: S.optional(S.String), Description: S.optional(S.String)}) {}
export const ParameterGroupList = S.Array(ParameterGroup);
export const NetworkTypeList = S.Array(S.String);
export class Subnet extends S.Class<Subnet>("Subnet")({SubnetIdentifier: S.optional(S.String), SubnetAvailabilityZone: S.optional(S.String), SupportedNetworkTypes: S.optional(NetworkTypeList)}) {}
export const SubnetList = S.Array(Subnet);
export class SubnetGroup extends S.Class<SubnetGroup>("SubnetGroup")({SubnetGroupName: S.optional(S.String), Description: S.optional(S.String), VpcId: S.optional(S.String), Subnets: S.optional(SubnetList), SupportedNetworkTypes: S.optional(NetworkTypeList)}) {}
export const SubnetGroupList = S.Array(SubnetGroup);
export class ParameterNameValue extends S.Class<ParameterNameValue>("ParameterNameValue")({ParameterName: S.optional(S.String), ParameterValue: S.optional(S.String)}) {}
export const ParameterNameValueList = S.Array(ParameterNameValue);
export class CreateClusterRequest extends S.Class<CreateClusterRequest>("CreateClusterRequest")({ClusterName: S.String, NodeType: S.String, Description: S.optional(S.String), ReplicationFactor: S.Number, AvailabilityZones: S.optional(AvailabilityZoneList), SubnetGroupName: S.optional(S.String), SecurityGroupIds: S.optional(SecurityGroupIdentifierList), PreferredMaintenanceWindow: S.optional(S.String), NotificationTopicArn: S.optional(S.String), IamRoleArn: S.String, ParameterGroupName: S.optional(S.String), Tags: S.optional(TagList), SSESpecification: S.optional(SSESpecification), ClusterEndpointEncryptionType: S.optional(S.String), NetworkType: S.optional(S.String)}) {}
export class DeleteClusterResponse extends S.Class<DeleteClusterResponse>("DeleteClusterResponse")({Cluster: S.optional(Cluster)}) {}
export class DeleteParameterGroupResponse extends S.Class<DeleteParameterGroupResponse>("DeleteParameterGroupResponse")({DeletionMessage: S.optional(S.String)}) {}
export class DeleteSubnetGroupResponse extends S.Class<DeleteSubnetGroupResponse>("DeleteSubnetGroupResponse")({DeletionMessage: S.optional(S.String)}) {}
export class DescribeClustersResponse extends S.Class<DescribeClustersResponse>("DescribeClustersResponse")({NextToken: S.optional(S.String), Clusters: S.optional(ClusterList)}) {}
export class DescribeParameterGroupsResponse extends S.Class<DescribeParameterGroupsResponse>("DescribeParameterGroupsResponse")({NextToken: S.optional(S.String), ParameterGroups: S.optional(ParameterGroupList)}) {}
export class NodeTypeSpecificValue extends S.Class<NodeTypeSpecificValue>("NodeTypeSpecificValue")({NodeType: S.optional(S.String), Value: S.optional(S.String)}) {}
export const NodeTypeSpecificValueList = S.Array(NodeTypeSpecificValue);
export class Parameter extends S.Class<Parameter>("Parameter")({ParameterName: S.optional(S.String), ParameterType: S.optional(S.String), ParameterValue: S.optional(S.String), NodeTypeSpecificValues: S.optional(NodeTypeSpecificValueList), Description: S.optional(S.String), Source: S.optional(S.String), DataType: S.optional(S.String), AllowedValues: S.optional(S.String), IsModifiable: S.optional(S.String), ChangeType: S.optional(S.String)}) {}
export const ParameterList = S.Array(Parameter);
export class DescribeParametersResponse extends S.Class<DescribeParametersResponse>("DescribeParametersResponse")({NextToken: S.optional(S.String), Parameters: S.optional(ParameterList)}) {}
export class DescribeSubnetGroupsResponse extends S.Class<DescribeSubnetGroupsResponse>("DescribeSubnetGroupsResponse")({NextToken: S.optional(S.String), SubnetGroups: S.optional(SubnetGroupList)}) {}
export class IncreaseReplicationFactorResponse extends S.Class<IncreaseReplicationFactorResponse>("IncreaseReplicationFactorResponse")({Cluster: S.optional(Cluster)}) {}
export class ListTagsResponse extends S.Class<ListTagsResponse>("ListTagsResponse")({Tags: S.optional(TagList), NextToken: S.optional(S.String)}) {}
export class RebootNodeResponse extends S.Class<RebootNodeResponse>("RebootNodeResponse")({Cluster: S.optional(Cluster)}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({Tags: S.optional(TagList)}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({Tags: S.optional(TagList)}) {}
export class UpdateClusterResponse extends S.Class<UpdateClusterResponse>("UpdateClusterResponse")({Cluster: S.optional(Cluster)}) {}
export class UpdateParameterGroupRequest extends S.Class<UpdateParameterGroupRequest>("UpdateParameterGroupRequest")({ParameterGroupName: S.String, ParameterNameValues: ParameterNameValueList}) {}
export class UpdateSubnetGroupResponse extends S.Class<UpdateSubnetGroupResponse>("UpdateSubnetGroupResponse")({SubnetGroup: S.optional(SubnetGroup)}) {}
export class Event extends S.Class<Event>("Event")({SourceName: S.optional(S.String), SourceType: S.optional(S.String), Message: S.optional(S.String), Date: S.optional(S.Date)}) {}
export const EventList = S.Array(Event);
export class CreateClusterResponse extends S.Class<CreateClusterResponse>("CreateClusterResponse")({Cluster: S.optional(Cluster)}) {}
export class CreateParameterGroupResponse extends S.Class<CreateParameterGroupResponse>("CreateParameterGroupResponse")({ParameterGroup: S.optional(ParameterGroup)}) {}
export class ClusterNotFoundFault extends S.Class<ClusterNotFoundFault>("ClusterNotFoundFault")({message: S.optional(S.String)}) {}
export class InvalidParameterCombinationException extends S.Class<InvalidParameterCombinationException>("InvalidParameterCombinationException")({message: S.optional(S.String)}) {}
export class ServiceLinkedRoleNotFoundFault extends S.Class<ServiceLinkedRoleNotFoundFault>("ServiceLinkedRoleNotFoundFault")({message: S.optional(S.String)}) {}
export class InvalidParameterValueException extends S.Class<InvalidParameterValueException>("InvalidParameterValueException")({message: S.optional(S.String)}) {}
export class DescribeEventsResponse extends S.Class<DescribeEventsResponse>("DescribeEventsResponse")({NextToken: S.optional(S.String), Events: S.optional(EventList)}) {}
export class ParameterGroupNotFoundFault extends S.Class<ParameterGroupNotFoundFault>("ParameterGroupNotFoundFault")({message: S.optional(S.String)}) {}
export class SubnetGroupNotFoundFault extends S.Class<SubnetGroupNotFoundFault>("SubnetGroupNotFoundFault")({message: S.optional(S.String)}) {}
export class InsufficientClusterCapacityFault extends S.Class<InsufficientClusterCapacityFault>("InsufficientClusterCapacityFault")({message: S.optional(S.String)}) {}
export class InvalidARNFault extends S.Class<InvalidARNFault>("InvalidARNFault")({message: S.optional(S.String)}) {}
export class InvalidClusterStateFault extends S.Class<InvalidClusterStateFault>("InvalidClusterStateFault")({message: S.optional(S.String)}) {}
export class TagQuotaPerResourceExceeded extends S.Class<TagQuotaPerResourceExceeded>("TagQuotaPerResourceExceeded")({message: S.optional(S.String)}) {}
export class TagNotFoundFault extends S.Class<TagNotFoundFault>("TagNotFoundFault")({message: S.optional(S.String)}) {}
export class InvalidParameterGroupStateFault extends S.Class<InvalidParameterGroupStateFault>("InvalidParameterGroupStateFault")({message: S.optional(S.String)}) {}
export class UpdateParameterGroupResponse extends S.Class<UpdateParameterGroupResponse>("UpdateParameterGroupResponse")({ParameterGroup: S.optional(ParameterGroup)}) {}
export class InvalidSubnet extends S.Class<InvalidSubnet>("InvalidSubnet")({message: S.optional(S.String)}) {}
export class ClusterAlreadyExistsFault extends S.Class<ClusterAlreadyExistsFault>("ClusterAlreadyExistsFault")({message: S.optional(S.String)}) {}
export class ParameterGroupAlreadyExistsFault extends S.Class<ParameterGroupAlreadyExistsFault>("ParameterGroupAlreadyExistsFault")({message: S.optional(S.String)}) {}
export class CreateSubnetGroupResponse extends S.Class<CreateSubnetGroupResponse>("CreateSubnetGroupResponse")({SubnetGroup: S.optional(SubnetGroup)}) {}
export class DecreaseReplicationFactorResponse extends S.Class<DecreaseReplicationFactorResponse>("DecreaseReplicationFactorResponse")({Cluster: S.optional(Cluster)}) {}
export class SubnetGroupInUseFault extends S.Class<SubnetGroupInUseFault>("SubnetGroupInUseFault")({message: S.optional(S.String)}) {}
export class DescribeDefaultParametersResponse extends S.Class<DescribeDefaultParametersResponse>("DescribeDefaultParametersResponse")({NextToken: S.optional(S.String), Parameters: S.optional(ParameterList)}) {}
export class InvalidVPCNetworkStateFault extends S.Class<InvalidVPCNetworkStateFault>("InvalidVPCNetworkStateFault")({message: S.optional(S.String)}) {}
export class NodeNotFoundFault extends S.Class<NodeNotFoundFault>("NodeNotFoundFault")({message: S.optional(S.String)}) {}
export class SubnetInUse extends S.Class<SubnetInUse>("SubnetInUse")({message: S.optional(S.String)}) {}
export class ClusterQuotaForCustomerExceededFault extends S.Class<ClusterQuotaForCustomerExceededFault>("ClusterQuotaForCustomerExceededFault")({message: S.optional(S.String)}) {}
export class ParameterGroupQuotaExceededFault extends S.Class<ParameterGroupQuotaExceededFault>("ParameterGroupQuotaExceededFault")({message: S.optional(S.String)}) {}
export class SubnetGroupAlreadyExistsFault extends S.Class<SubnetGroupAlreadyExistsFault>("SubnetGroupAlreadyExistsFault")({message: S.optional(S.String)}) {}
export class NodeQuotaForClusterExceededFault extends S.Class<NodeQuotaForClusterExceededFault>("NodeQuotaForClusterExceededFault")({message: S.optional(S.String)}) {}
export class SubnetNotAllowedFault extends S.Class<SubnetNotAllowedFault>("SubnetNotAllowedFault")({message: S.optional(S.String)}) {}
export class NodeQuotaForCustomerExceededFault extends S.Class<NodeQuotaForCustomerExceededFault>("NodeQuotaForCustomerExceededFault")({message: S.optional(S.String)}) {}
export class ServiceQuotaExceededException extends S.Class<ServiceQuotaExceededException>("ServiceQuotaExceededException")({}) {}
export class SubnetGroupQuotaExceededFault extends S.Class<SubnetGroupQuotaExceededFault>("SubnetGroupQuotaExceededFault")({message: S.optional(S.String)}) {}
export class SubnetQuotaExceededFault extends S.Class<SubnetQuotaExceededFault>("SubnetQuotaExceededFault")({message: S.optional(S.String)}) {}

//# Errors
export class ClusterNotFoundFaultError extends S.TaggedError<ClusterNotFoundFaultError>()("ClusterNotFoundFault", ClusterNotFoundFault.fields) {};
export class InvalidParameterCombinationExceptionError extends S.TaggedError<InvalidParameterCombinationExceptionError>()("InvalidParameterCombinationException", InvalidParameterCombinationException.fields) {};
export class InvalidParameterValueExceptionError extends S.TaggedError<InvalidParameterValueExceptionError>()("InvalidParameterValueException", InvalidParameterValueException.fields) {};
export class ParameterGroupNotFoundFaultError extends S.TaggedError<ParameterGroupNotFoundFaultError>()("ParameterGroupNotFoundFault", ParameterGroupNotFoundFault.fields) {};
export class ServiceLinkedRoleNotFoundFaultError extends S.TaggedError<ServiceLinkedRoleNotFoundFaultError>()("ServiceLinkedRoleNotFoundFault", ServiceLinkedRoleNotFoundFault.fields) {};
export class InvalidARNFaultError extends S.TaggedError<InvalidARNFaultError>()("InvalidARNFault", InvalidARNFault.fields) {};
export class InvalidClusterStateFaultError extends S.TaggedError<InvalidClusterStateFaultError>()("InvalidClusterStateFault", InvalidClusterStateFault.fields) {};
export class InvalidParameterGroupStateFaultError extends S.TaggedError<InvalidParameterGroupStateFaultError>()("InvalidParameterGroupStateFault", InvalidParameterGroupStateFault.fields) {};
export class SubnetGroupNotFoundFaultError extends S.TaggedError<SubnetGroupNotFoundFaultError>()("SubnetGroupNotFoundFault", SubnetGroupNotFoundFault.fields) {};
export class InsufficientClusterCapacityFaultError extends S.TaggedError<InsufficientClusterCapacityFaultError>()("InsufficientClusterCapacityFault", InsufficientClusterCapacityFault.fields) {};
export class TagQuotaPerResourceExceededError extends S.TaggedError<TagQuotaPerResourceExceededError>()("TagQuotaPerResourceExceeded", TagQuotaPerResourceExceeded.fields) {};
export class TagNotFoundFaultError extends S.TaggedError<TagNotFoundFaultError>()("TagNotFoundFault", TagNotFoundFault.fields) {};
export class InvalidSubnetError extends S.TaggedError<InvalidSubnetError>()("InvalidSubnet", InvalidSubnet.fields) {};
export class ClusterAlreadyExistsFaultError extends S.TaggedError<ClusterAlreadyExistsFaultError>()("ClusterAlreadyExistsFault", ClusterAlreadyExistsFault.fields) {};
export class ParameterGroupAlreadyExistsFaultError extends S.TaggedError<ParameterGroupAlreadyExistsFaultError>()("ParameterGroupAlreadyExistsFault", ParameterGroupAlreadyExistsFault.fields) {};
export class NodeNotFoundFaultError extends S.TaggedError<NodeNotFoundFaultError>()("NodeNotFoundFault", NodeNotFoundFault.fields) {};
export class SubnetGroupInUseFaultError extends S.TaggedError<SubnetGroupInUseFaultError>()("SubnetGroupInUseFault", SubnetGroupInUseFault.fields) {};
export class InvalidVPCNetworkStateFaultError extends S.TaggedError<InvalidVPCNetworkStateFaultError>()("InvalidVPCNetworkStateFault", InvalidVPCNetworkStateFault.fields) {};
export class SubnetInUseError extends S.TaggedError<SubnetInUseError>()("SubnetInUse", SubnetInUse.fields) {};
export class ClusterQuotaForCustomerExceededFaultError extends S.TaggedError<ClusterQuotaForCustomerExceededFaultError>()("ClusterQuotaForCustomerExceededFault", ClusterQuotaForCustomerExceededFault.fields) {};
export class NodeQuotaForClusterExceededFaultError extends S.TaggedError<NodeQuotaForClusterExceededFaultError>()("NodeQuotaForClusterExceededFault", NodeQuotaForClusterExceededFault.fields) {};
export class ParameterGroupQuotaExceededFaultError extends S.TaggedError<ParameterGroupQuotaExceededFaultError>()("ParameterGroupQuotaExceededFault", ParameterGroupQuotaExceededFault.fields) {};
export class SubnetGroupAlreadyExistsFaultError extends S.TaggedError<SubnetGroupAlreadyExistsFaultError>()("SubnetGroupAlreadyExistsFault", SubnetGroupAlreadyExistsFault.fields) {};
export class NodeQuotaForCustomerExceededFaultError extends S.TaggedError<NodeQuotaForCustomerExceededFaultError>()("NodeQuotaForCustomerExceededFault", NodeQuotaForCustomerExceededFault.fields) {};
export class SubnetNotAllowedFaultError extends S.TaggedError<SubnetNotAllowedFaultError>()("SubnetNotAllowedFault", SubnetNotAllowedFault.fields) {};
export class ServiceQuotaExceededExceptionError extends S.TaggedError<ServiceQuotaExceededExceptionError>()("ServiceQuotaExceededException", ServiceQuotaExceededException.fields) {};
export class SubnetGroupQuotaExceededFaultError extends S.TaggedError<SubnetGroupQuotaExceededFaultError>()("SubnetGroupQuotaExceededFault", SubnetGroupQuotaExceededFault.fields) {};
export class SubnetQuotaExceededFaultError extends S.TaggedError<SubnetQuotaExceededFaultError>()("SubnetQuotaExceededFault", SubnetQuotaExceededFault.fields) {};

//# Operations
export const describeParameters = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.DescribeParameters" }, DescribeParametersRequest, DescribeParametersResponse, [InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, ParameterGroupNotFoundFaultError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteCluster = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.DeleteCluster" }, DeleteClusterRequest, DeleteClusterResponse, [ClusterNotFoundFaultError, InvalidClusterStateFaultError, InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteParameterGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.DeleteParameterGroup" }, DeleteParameterGroupRequest, DeleteParameterGroupResponse, [InvalidParameterCombinationExceptionError, InvalidParameterGroupStateFaultError, InvalidParameterValueExceptionError, ParameterGroupNotFoundFaultError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeClusters = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.DescribeClusters" }, DescribeClustersRequest, DescribeClustersResponse, [ClusterNotFoundFaultError, InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeEvents = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.DescribeEvents" }, DescribeEventsRequest, DescribeEventsResponse, [InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeParameterGroups = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.DescribeParameterGroups" }, DescribeParameterGroupsRequest, DescribeParameterGroupsResponse, [InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, ParameterGroupNotFoundFaultError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeSubnetGroups = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.DescribeSubnetGroups" }, DescribeSubnetGroupsRequest, DescribeSubnetGroupsResponse, [ServiceLinkedRoleNotFoundFaultError, SubnetGroupNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTags = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.ListTags" }, ListTagsRequest, ListTagsResponse, [ClusterNotFoundFaultError, InvalidARNFaultError, InvalidClusterStateFaultError, InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.TagResource" }, TagResourceRequest, TagResourceResponse, [ClusterNotFoundFaultError, InvalidARNFaultError, InvalidClusterStateFaultError, InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, ServiceLinkedRoleNotFoundFaultError, TagQuotaPerResourceExceededError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [ClusterNotFoundFaultError, InvalidARNFaultError, InvalidClusterStateFaultError, InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, ServiceLinkedRoleNotFoundFaultError, TagNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateCluster = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.UpdateCluster" }, UpdateClusterRequest, UpdateClusterResponse, [ClusterNotFoundFaultError, InvalidClusterStateFaultError, InvalidParameterCombinationExceptionError, InvalidParameterGroupStateFaultError, InvalidParameterValueExceptionError, ParameterGroupNotFoundFaultError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateParameterGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.UpdateParameterGroup" }, UpdateParameterGroupRequest, UpdateParameterGroupResponse, [InvalidParameterCombinationExceptionError, InvalidParameterGroupStateFaultError, InvalidParameterValueExceptionError, ParameterGroupNotFoundFaultError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const decreaseReplicationFactor = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.DecreaseReplicationFactor" }, DecreaseReplicationFactorRequest, DecreaseReplicationFactorResponse, [ClusterNotFoundFaultError, InvalidClusterStateFaultError, InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, NodeNotFoundFaultError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteSubnetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.DeleteSubnetGroup" }, DeleteSubnetGroupRequest, DeleteSubnetGroupResponse, [ServiceLinkedRoleNotFoundFaultError, SubnetGroupInUseFaultError, SubnetGroupNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeDefaultParameters = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.DescribeDefaultParameters" }, DescribeDefaultParametersRequest, DescribeDefaultParametersResponse, [InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const rebootNode = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.RebootNode" }, RebootNodeRequest, RebootNodeResponse, [ClusterNotFoundFaultError, InvalidClusterStateFaultError, InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, NodeNotFoundFaultError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createParameterGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.CreateParameterGroup" }, CreateParameterGroupRequest, CreateParameterGroupResponse, [InvalidParameterCombinationExceptionError, InvalidParameterGroupStateFaultError, InvalidParameterValueExceptionError, ParameterGroupAlreadyExistsFaultError, ParameterGroupQuotaExceededFaultError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const increaseReplicationFactor = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.IncreaseReplicationFactor" }, IncreaseReplicationFactorRequest, IncreaseReplicationFactorResponse, [ClusterNotFoundFaultError, InsufficientClusterCapacityFaultError, InvalidClusterStateFaultError, InvalidParameterCombinationExceptionError, InvalidParameterValueExceptionError, InvalidVPCNetworkStateFaultError, NodeQuotaForClusterExceededFaultError, NodeQuotaForCustomerExceededFaultError, ServiceLinkedRoleNotFoundFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createCluster = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.CreateCluster" }, CreateClusterRequest, CreateClusterResponse, [ClusterAlreadyExistsFaultError, ClusterQuotaForCustomerExceededFaultError, InsufficientClusterCapacityFaultError, InvalidClusterStateFaultError, InvalidParameterCombinationExceptionError, InvalidParameterGroupStateFaultError, InvalidParameterValueExceptionError, InvalidVPCNetworkStateFaultError, NodeQuotaForClusterExceededFaultError, NodeQuotaForCustomerExceededFaultError, ParameterGroupNotFoundFaultError, ServiceLinkedRoleNotFoundFaultError, ServiceQuotaExceededExceptionError, SubnetGroupNotFoundFaultError, TagQuotaPerResourceExceededError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createSubnetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.CreateSubnetGroup" }, CreateSubnetGroupRequest, CreateSubnetGroupResponse, [InvalidSubnetError, ServiceLinkedRoleNotFoundFaultError, SubnetGroupAlreadyExistsFaultError, SubnetGroupQuotaExceededFaultError, SubnetNotAllowedFaultError, SubnetQuotaExceededFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateSubnetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-04-19", uri: "/", method: "POST", sdkId: "DAX", sigV4ServiceName: "dax", name: "AmazonDAXV3.UpdateSubnetGroup" }, UpdateSubnetGroupRequest, UpdateSubnetGroupResponse, [InvalidSubnetError, ServiceLinkedRoleNotFoundFaultError, SubnetGroupNotFoundFaultError, SubnetInUseError, SubnetNotAllowedFaultError, SubnetQuotaExceededFaultError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
