import * as S from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const QueueIds = S.Array(S.String);
export const FleetIds = S.Array(S.String);
export const UsageGroupBy = S.Array(S.String);
export const UsageStatistics = S.Array(S.String);
export const StringList = S.Array(S.String);
export class CreateQueueFleetAssociationRequest extends S.Class<CreateQueueFleetAssociationRequest>("CreateQueueFleetAssociationRequest")({farmId: S.String, queueId: S.String, fleetId: S.String}) {}
export class CreateQueueFleetAssociationResponse extends S.Class<CreateQueueFleetAssociationResponse>("CreateQueueFleetAssociationResponse")({}) {}
export class CreateQueueLimitAssociationRequest extends S.Class<CreateQueueLimitAssociationRequest>("CreateQueueLimitAssociationRequest")({farmId: S.String, queueId: S.String, limitId: S.String}) {}
export class CreateQueueLimitAssociationResponse extends S.Class<CreateQueueLimitAssociationResponse>("CreateQueueLimitAssociationResponse")({}) {}
export class DeleteQueueFleetAssociationRequest extends S.Class<DeleteQueueFleetAssociationRequest>("DeleteQueueFleetAssociationRequest")({farmId: S.String, queueId: S.String, fleetId: S.String}) {}
export class DeleteQueueFleetAssociationResponse extends S.Class<DeleteQueueFleetAssociationResponse>("DeleteQueueFleetAssociationResponse")({}) {}
export class DeleteQueueLimitAssociationRequest extends S.Class<DeleteQueueLimitAssociationRequest>("DeleteQueueLimitAssociationRequest")({farmId: S.String, queueId: S.String, limitId: S.String}) {}
export class DeleteQueueLimitAssociationResponse extends S.Class<DeleteQueueLimitAssociationResponse>("DeleteQueueLimitAssociationResponse")({}) {}
export class GetQueueFleetAssociationRequest extends S.Class<GetQueueFleetAssociationRequest>("GetQueueFleetAssociationRequest")({farmId: S.String, queueId: S.String, fleetId: S.String}) {}
export class GetQueueLimitAssociationRequest extends S.Class<GetQueueLimitAssociationRequest>("GetQueueLimitAssociationRequest")({farmId: S.String, queueId: S.String, limitId: S.String}) {}
export class GetSessionsStatisticsAggregationRequest extends S.Class<GetSessionsStatisticsAggregationRequest>("GetSessionsStatisticsAggregationRequest")({farmId: S.String, aggregationId: S.String, maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export class ListAvailableMeteredProductsRequest extends S.Class<ListAvailableMeteredProductsRequest>("ListAvailableMeteredProductsRequest")({nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListQueueFleetAssociationsRequest extends S.Class<ListQueueFleetAssociationsRequest>("ListQueueFleetAssociationsRequest")({farmId: S.String, queueId: S.optional(S.String), fleetId: S.optional(S.String), nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListQueueLimitAssociationsRequest extends S.Class<ListQueueLimitAssociationsRequest>("ListQueueLimitAssociationsRequest")({farmId: S.String, queueId: S.optional(S.String), limitId: S.optional(S.String), nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({resourceArn: S.String}) {}
export class SearchGroupedFilterExpressions extends S.Class<SearchGroupedFilterExpressions>("SearchGroupedFilterExpressions")({filters: S.suspend(() => SearchFilterExpressions), operator: S.String}) {}
export class UserJobsFirst extends S.Class<UserJobsFirst>("UserJobsFirst")({userIdentityId: S.String}) {}
export class FieldSortExpression extends S.Class<FieldSortExpression>("FieldSortExpression")({sortOrder: S.String, name: S.String}) {}
export class ParameterSortExpression extends S.Class<ParameterSortExpression>("ParameterSortExpression")({sortOrder: S.String, name: S.String}) {}
export const SearchSortExpression = S.Union(UserJobsFirst, FieldSortExpression, ParameterSortExpression);
export const SearchSortExpressions = S.Array(SearchSortExpression);
export class SearchStepsRequest extends S.Class<SearchStepsRequest>("SearchStepsRequest")({farmId: S.String, queueIds: QueueIds, jobId: S.optional(S.String), filterExpressions: S.optional(SearchGroupedFilterExpressions), sortExpressions: S.optional(SearchSortExpressions), itemOffset: S.Number, pageSize: S.optional(S.Number)}) {}
export class SearchTasksRequest extends S.Class<SearchTasksRequest>("SearchTasksRequest")({farmId: S.String, queueIds: QueueIds, jobId: S.optional(S.String), filterExpressions: S.optional(SearchGroupedFilterExpressions), sortExpressions: S.optional(SearchSortExpressions), itemOffset: S.Number, pageSize: S.optional(S.Number)}) {}
export class SearchWorkersRequest extends S.Class<SearchWorkersRequest>("SearchWorkersRequest")({farmId: S.String, fleetIds: FleetIds, filterExpressions: S.optional(SearchGroupedFilterExpressions), sortExpressions: S.optional(SearchSortExpressions), itemOffset: S.Number, pageSize: S.optional(S.Number)}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({resourceArn: S.String, tagKeys: StringList}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class UpdateQueueFleetAssociationRequest extends S.Class<UpdateQueueFleetAssociationRequest>("UpdateQueueFleetAssociationRequest")({farmId: S.String, queueId: S.String, fleetId: S.String, status: S.String}) {}
export class UpdateQueueFleetAssociationResponse extends S.Class<UpdateQueueFleetAssociationResponse>("UpdateQueueFleetAssociationResponse")({}) {}
export class UpdateQueueLimitAssociationRequest extends S.Class<UpdateQueueLimitAssociationRequest>("UpdateQueueLimitAssociationRequest")({farmId: S.String, queueId: S.String, limitId: S.String, status: S.String}) {}
export class UpdateQueueLimitAssociationResponse extends S.Class<UpdateQueueLimitAssociationResponse>("UpdateQueueLimitAssociationResponse")({}) {}
export const SessionsStatisticsResources = S.Union(QueueIds, FleetIds);
export const Tags = S.Record({key: S.String, value: S.String});
export class InternalServerErrorException extends S.Class<InternalServerErrorException>("InternalServerErrorException")({message: S.String, retryAfterSeconds: S.optional(H.Header("Retry-After", S.Number))}) {}
export const ExceptionContext = S.Record({key: S.String, value: S.String});
export class ConflictException extends S.Class<ConflictException>("ConflictException")({message: S.String, reason: S.String, resourceId: S.String, resourceType: S.String, context: S.optional(ExceptionContext)}) {}
export class ResourceNotFoundException extends S.Class<ResourceNotFoundException>("ResourceNotFoundException")({message: S.String, resourceId: S.String, resourceType: S.String, context: S.optional(ExceptionContext)}) {}
export class GetQueueFleetAssociationResponse extends S.Class<GetQueueFleetAssociationResponse>("GetQueueFleetAssociationResponse")({queueId: S.String, fleetId: S.String, status: S.String, createdAt: S.Date, createdBy: S.String, updatedAt: S.optional(S.Date), updatedBy: S.optional(S.String)}) {}
export class GetQueueLimitAssociationResponse extends S.Class<GetQueueLimitAssociationResponse>("GetQueueLimitAssociationResponse")({createdAt: S.Date, createdBy: S.String, updatedAt: S.optional(S.Date), updatedBy: S.optional(S.String), queueId: S.String, limitId: S.String, status: S.String}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({tags: S.optional(Tags)}) {}
export class StartSessionsStatisticsAggregationRequest extends S.Class<StartSessionsStatisticsAggregationRequest>("StartSessionsStatisticsAggregationRequest")({farmId: S.String, resourceIds: SessionsStatisticsResources, startTime: S.Date, endTime: S.Date, timezone: S.optional(S.String), period: S.optional(S.String), groupBy: UsageGroupBy, statistics: UsageStatistics}) {}
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({resourceArn: S.String, tags: S.optional(Tags)}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class ThrottlingException extends S.Class<ThrottlingException>("ThrottlingException")({message: S.String, serviceCode: S.optional(S.String), quotaCode: S.optional(S.String), retryAfterSeconds: S.optional(H.Header("Retry-After", S.Number)), context: S.optional(ExceptionContext)}) {}
export class MeteredProductSummary extends S.Class<MeteredProductSummary>("MeteredProductSummary")({productId: S.String, family: S.String, vendor: S.String, port: S.Number}) {}
export const MeteredProductSummaryList = S.Array(MeteredProductSummary);
export class QueueFleetAssociationSummary extends S.Class<QueueFleetAssociationSummary>("QueueFleetAssociationSummary")({queueId: S.String, fleetId: S.String, status: S.String, createdAt: S.Date, createdBy: S.String, updatedAt: S.optional(S.Date), updatedBy: S.optional(S.String)}) {}
export const QueueFleetAssociationSummaries = S.Array(QueueFleetAssociationSummary);
export class QueueLimitAssociationSummary extends S.Class<QueueLimitAssociationSummary>("QueueLimitAssociationSummary")({createdAt: S.Date, createdBy: S.String, updatedAt: S.optional(S.Date), updatedBy: S.optional(S.String), queueId: S.String, limitId: S.String, status: S.String}) {}
export const QueueLimitAssociationSummaries = S.Array(QueueLimitAssociationSummary);
export class ValidationExceptionField extends S.Class<ValidationExceptionField>("ValidationExceptionField")({name: S.String, message: S.String}) {}
export const ValidationExceptionFieldList = S.Array(ValidationExceptionField);
export class DateTimeFilterExpression extends S.Class<DateTimeFilterExpression>("DateTimeFilterExpression")({name: S.String, operator: S.String, dateTime: S.Date}) {}
export class ParameterFilterExpression extends S.Class<ParameterFilterExpression>("ParameterFilterExpression")({name: S.String, operator: S.String, value: S.String}) {}
export class SearchTermFilterExpression extends S.Class<SearchTermFilterExpression>("SearchTermFilterExpression")({searchTerm: S.String, matchType: S.optional(S.String)}) {}
export class StringFilterExpression extends S.Class<StringFilterExpression>("StringFilterExpression")({name: S.String, operator: S.String, value: S.String}) {}
export class AccessDeniedException extends S.Class<AccessDeniedException>("AccessDeniedException")({message: S.String, context: S.optional(ExceptionContext)}) {}
export class ListAvailableMeteredProductsResponse extends S.Class<ListAvailableMeteredProductsResponse>("ListAvailableMeteredProductsResponse")({meteredProducts: MeteredProductSummaryList, nextToken: S.optional(S.String)}) {}
export class ListQueueFleetAssociationsResponse extends S.Class<ListQueueFleetAssociationsResponse>("ListQueueFleetAssociationsResponse")({queueFleetAssociations: QueueFleetAssociationSummaries, nextToken: S.optional(S.String)}) {}
export class ListQueueLimitAssociationsResponse extends S.Class<ListQueueLimitAssociationsResponse>("ListQueueLimitAssociationsResponse")({queueLimitAssociations: QueueLimitAssociationSummaries, nextToken: S.optional(S.String)}) {}
export class StartSessionsStatisticsAggregationResponse extends S.Class<StartSessionsStatisticsAggregationResponse>("StartSessionsStatisticsAggregationResponse")({aggregationId: S.String}) {}
export class ValidationException extends S.Class<ValidationException>("ValidationException")({message: S.String, reason: S.String, fieldList: S.optional(ValidationExceptionFieldList), context: S.optional(ExceptionContext)}) {}
export class Stats extends S.Class<Stats>("Stats")({min: S.optional(S.Number), max: S.optional(S.Number), avg: S.optional(S.Number), sum: S.optional(S.Number)}) {}
export type SearchFilterExpression = DateTimeFilterExpression | ParameterFilterExpression | SearchTermFilterExpression | StringFilterExpression | SearchGroupedFilterExpressions;
export const SearchFilterExpression = S.Union(DateTimeFilterExpression, ParameterFilterExpression, SearchTermFilterExpression, StringFilterExpression, S.suspend((): S.Schema<SearchGroupedFilterExpressions> => SearchGroupedFilterExpressions)) as any as S.Schema<SearchFilterExpression>;
export type SearchFilterExpressions = SearchFilterExpression[];
export const SearchFilterExpressions = S.Array(S.suspend(() => SearchFilterExpression)) as any as S.Schema<SearchFilterExpressions>;
export const TaskRunStatusCounts = S.Record({key: S.String, value: S.Number});
export const IpV4Addresses = S.Array(S.String);
export const IpV6Addresses = S.Array(S.String);
export class Statistics extends S.Class<Statistics>("Statistics")({queueId: S.optional(S.String), fleetId: S.optional(S.String), jobId: S.optional(S.String), jobName: S.optional(S.String), userId: S.optional(S.String), usageType: S.optional(S.String), licenseProduct: S.optional(S.String), instanceType: S.optional(S.String), count: S.Number, costInUsd: Stats, runtimeInSeconds: Stats, aggregationStartTime: S.optional(S.Date), aggregationEndTime: S.optional(S.Date)}) {}
export const StatisticsList = S.Array(Statistics);
export class StepParameter extends S.Class<StepParameter>("StepParameter")({name: S.String, type: S.String}) {}
export const StepParameterList = S.Array(StepParameter);
export const TaskParameterValue = S.Union(S.String, S.String, S.String, S.String, S.String);
export class IpAddresses extends S.Class<IpAddresses>("IpAddresses")({ipV4Addresses: S.optional(IpV4Addresses), ipV6Addresses: S.optional(IpV6Addresses)}) {}
export class GetSessionsStatisticsAggregationResponse extends S.Class<GetSessionsStatisticsAggregationResponse>("GetSessionsStatisticsAggregationResponse")({statistics: S.optional(StatisticsList), nextToken: S.optional(S.String), status: S.String, statusMessage: S.optional(S.String)}) {}
export class SearchJobsRequest extends S.Class<SearchJobsRequest>("SearchJobsRequest")({farmId: S.String, queueIds: QueueIds, filterExpressions: S.optional(SearchGroupedFilterExpressions), sortExpressions: S.optional(SearchSortExpressions), itemOffset: S.Number, pageSize: S.optional(S.Number)}) {}
export class ParameterSpace extends S.Class<ParameterSpace>("ParameterSpace")({parameters: StepParameterList, combination: S.optional(S.String)}) {}
export const TaskParameters = S.Record({key: S.String, value: TaskParameterValue});
export class HostPropertiesResponse extends S.Class<HostPropertiesResponse>("HostPropertiesResponse")({ipAddresses: S.optional(IpAddresses), hostName: S.optional(S.String), ec2InstanceArn: S.optional(S.String), ec2InstanceType: S.optional(S.String)}) {}
export class StepSearchSummary extends S.Class<StepSearchSummary>("StepSearchSummary")({stepId: S.optional(S.String), jobId: S.optional(S.String), queueId: S.optional(S.String), name: S.optional(S.String), lifecycleStatus: S.optional(S.String), lifecycleStatusMessage: S.optional(S.String), taskRunStatus: S.optional(S.String), targetTaskRunStatus: S.optional(S.String), taskRunStatusCounts: S.optional(TaskRunStatusCounts), taskFailureRetryCount: S.optional(S.Number), createdAt: S.optional(S.Date), createdBy: S.optional(S.String), startedAt: S.optional(S.Date), endedAt: S.optional(S.Date), updatedAt: S.optional(S.Date), updatedBy: S.optional(S.String), parameterSpace: S.optional(ParameterSpace)}) {}
export const StepSearchSummaries = S.Array(StepSearchSummary);
export class TaskSearchSummary extends S.Class<TaskSearchSummary>("TaskSearchSummary")({taskId: S.optional(S.String), stepId: S.optional(S.String), jobId: S.optional(S.String), queueId: S.optional(S.String), runStatus: S.optional(S.String), targetRunStatus: S.optional(S.String), parameters: S.optional(TaskParameters), failureRetryCount: S.optional(S.Number), startedAt: S.optional(S.Date), endedAt: S.optional(S.Date), updatedAt: S.optional(S.Date), updatedBy: S.optional(S.String)}) {}
export const TaskSearchSummaries = S.Array(TaskSearchSummary);
export class WorkerSearchSummary extends S.Class<WorkerSearchSummary>("WorkerSearchSummary")({fleetId: S.optional(S.String), workerId: S.optional(S.String), status: S.optional(S.String), hostProperties: S.optional(HostPropertiesResponse), createdBy: S.optional(S.String), createdAt: S.optional(S.Date), updatedBy: S.optional(S.String), updatedAt: S.optional(S.Date)}) {}
export const WorkerSearchSummaries = S.Array(WorkerSearchSummary);
export class SearchStepsResponse extends S.Class<SearchStepsResponse>("SearchStepsResponse")({steps: StepSearchSummaries, nextItemOffset: S.optional(S.Number), totalResults: S.Number}) {}
export class SearchTasksResponse extends S.Class<SearchTasksResponse>("SearchTasksResponse")({tasks: TaskSearchSummaries, nextItemOffset: S.optional(S.Number), totalResults: S.Number}) {}
export class SearchWorkersResponse extends S.Class<SearchWorkersResponse>("SearchWorkersResponse")({workers: WorkerSearchSummaries, nextItemOffset: S.optional(S.Number), totalResults: S.Number}) {}
export const JobParameter = S.Union(S.String, S.String, S.String, S.String);
export const JobParameters = S.Record({key: S.String, value: JobParameter});
export class JobSearchSummary extends S.Class<JobSearchSummary>("JobSearchSummary")({jobId: S.optional(S.String), queueId: S.optional(S.String), name: S.optional(S.String), lifecycleStatus: S.optional(S.String), lifecycleStatusMessage: S.optional(S.String), taskRunStatus: S.optional(S.String), targetTaskRunStatus: S.optional(S.String), taskRunStatusCounts: S.optional(TaskRunStatusCounts), taskFailureRetryCount: S.optional(S.Number), priority: S.optional(S.Number), maxFailedTasksCount: S.optional(S.Number), maxRetriesPerTask: S.optional(S.Number), createdBy: S.optional(S.String), createdAt: S.optional(S.Date), endedAt: S.optional(S.Date), startedAt: S.optional(S.Date), updatedAt: S.optional(S.Date), updatedBy: S.optional(S.String), jobParameters: S.optional(JobParameters), maxWorkerCount: S.optional(S.Number), sourceJobId: S.optional(S.String)}) {}
export const JobSearchSummaries = S.Array(JobSearchSummary);
export class SearchJobsResponse extends S.Class<SearchJobsResponse>("SearchJobsResponse")({jobs: JobSearchSummaries, nextItemOffset: S.optional(S.Number), totalResults: S.Number}) {}

//# Errors
export class AccessDeniedExceptionError extends S.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class ConflictExceptionError extends S.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class InternalServerErrorExceptionError extends S.TaggedError<InternalServerErrorExceptionError>()("InternalServerErrorException", InternalServerErrorException.fields) {};
export class ResourceNotFoundExceptionError extends S.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ThrottlingExceptionError extends S.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class ValidationExceptionError extends S.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};

//# Operations
export const updateQueueLimitAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/queue-limit-associations/{queueId}/{limitId}", method: "PATCH", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.UpdateQueueLimitAssociation" }, UpdateQueueLimitAssociationRequest, UpdateQueueLimitAssociationResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createQueueLimitAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/queue-limit-associations", method: "PUT", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.CreateQueueLimitAssociation" }, CreateQueueLimitAssociationRequest, CreateQueueLimitAssociationResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteQueueFleetAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/queue-fleet-associations/{queueId}/{fleetId}", method: "DELETE", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.DeleteQueueFleetAssociation" }, DeleteQueueFleetAssociationRequest, DeleteQueueFleetAssociationResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteQueueLimitAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/queue-limit-associations/{queueId}/{limitId}", method: "DELETE", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.DeleteQueueLimitAssociation" }, DeleteQueueLimitAssociationRequest, DeleteQueueLimitAssociationResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getQueueFleetAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/queue-fleet-associations/{queueId}/{fleetId}", method: "GET", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.GetQueueFleetAssociation" }, GetQueueFleetAssociationRequest, GetQueueFleetAssociationResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getQueueLimitAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/queue-limit-associations/{queueId}/{limitId}", method: "GET", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.GetQueueLimitAssociation" }, GetQueueLimitAssociationRequest, GetQueueLimitAssociationResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/tags/{resourceArn}", method: "GET", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/tags/{resourceArn}", method: "POST", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.TagResource" }, TagResourceRequest, TagResourceResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/tags/{resourceArn}", method: "DELETE", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createQueueFleetAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/queue-fleet-associations", method: "PUT", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.CreateQueueFleetAssociation" }, CreateQueueFleetAssociationRequest, CreateQueueFleetAssociationResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAvailableMeteredProducts = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/metered-products", method: "GET", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.ListAvailableMeteredProducts" }, ListAvailableMeteredProductsRequest, ListAvailableMeteredProductsResponse, [InternalServerErrorExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listQueueFleetAssociations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/queue-fleet-associations", method: "GET", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.ListQueueFleetAssociations" }, ListQueueFleetAssociationsRequest, ListQueueFleetAssociationsResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listQueueLimitAssociations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/queue-limit-associations", method: "GET", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.ListQueueLimitAssociations" }, ListQueueLimitAssociationsRequest, ListQueueLimitAssociationsResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const startSessionsStatisticsAggregation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/sessions-statistics-aggregation", method: "POST", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.StartSessionsStatisticsAggregation" }, StartSessionsStatisticsAggregationRequest, StartSessionsStatisticsAggregationResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateQueueFleetAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/queue-fleet-associations/{queueId}/{fleetId}", method: "PATCH", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.UpdateQueueFleetAssociation" }, UpdateQueueFleetAssociationRequest, UpdateQueueFleetAssociationResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSessionsStatisticsAggregation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/sessions-statistics-aggregation", method: "GET", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.GetSessionsStatisticsAggregation" }, GetSessionsStatisticsAggregationRequest, GetSessionsStatisticsAggregationResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const searchSteps = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/search/steps", method: "POST", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.SearchSteps" }, SearchStepsRequest, SearchStepsResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const searchTasks = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/search/tasks", method: "POST", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.SearchTasks" }, SearchTasksRequest, SearchTasksResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const searchWorkers = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/search/workers", method: "POST", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.SearchWorkers" }, SearchWorkersRequest, SearchWorkersResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const searchJobs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2023-10-12", uri: "/2023-10-12/farms/{farmId}/search/jobs", method: "POST", sdkId: "deadline", sigV4ServiceName: "deadline", name: "Deadline.SearchJobs" }, SearchJobsRequest, SearchJobsResponse, [AccessDeniedExceptionError, InternalServerErrorExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
