import * as S from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const SecurityGroups = S.Array(S.String);
export const TagKeys = S.Array(S.String);
export class Tag extends S.Class<Tag>("Tag")({Key: S.String, Value: S.String}) {}
export const Tags = S.Array(Tag);
export class CreateFileSystemRequest extends S.Class<CreateFileSystemRequest>("CreateFileSystemRequest")({CreationToken: S.String, PerformanceMode: S.optional(S.String), Encrypted: S.optional(S.Boolean), KmsKeyId: S.optional(S.String), ThroughputMode: S.optional(S.String), ProvisionedThroughputInMibps: S.optional(S.Number), AvailabilityZoneName: S.optional(S.String), Backup: S.optional(S.Boolean), Tags: S.optional(Tags)}) {}
export class CreateMountTargetRequest extends S.Class<CreateMountTargetRequest>("CreateMountTargetRequest")({FileSystemId: S.String, SubnetId: S.String, IpAddress: S.optional(S.String), Ipv6Address: S.optional(S.String), IpAddressType: S.optional(S.String), SecurityGroups: S.optional(SecurityGroups)}) {}
export class CreateTagsRequest extends S.Class<CreateTagsRequest>("CreateTagsRequest")({FileSystemId: S.String, Tags: Tags}) {}
export class DeleteAccessPointRequest extends S.Class<DeleteAccessPointRequest>("DeleteAccessPointRequest")({AccessPointId: S.String}) {}
export class DeleteFileSystemRequest extends S.Class<DeleteFileSystemRequest>("DeleteFileSystemRequest")({FileSystemId: S.String}) {}
export class DeleteFileSystemPolicyRequest extends S.Class<DeleteFileSystemPolicyRequest>("DeleteFileSystemPolicyRequest")({FileSystemId: S.String}) {}
export class DeleteMountTargetRequest extends S.Class<DeleteMountTargetRequest>("DeleteMountTargetRequest")({MountTargetId: S.String}) {}
export class DeleteReplicationConfigurationRequest extends S.Class<DeleteReplicationConfigurationRequest>("DeleteReplicationConfigurationRequest")({SourceFileSystemId: S.String, DeletionMode: S.optional(S.String)}) {}
export class DeleteTagsRequest extends S.Class<DeleteTagsRequest>("DeleteTagsRequest")({FileSystemId: S.String, TagKeys: TagKeys}) {}
export class DescribeAccessPointsRequest extends S.Class<DescribeAccessPointsRequest>("DescribeAccessPointsRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), AccessPointId: S.optional(S.String), FileSystemId: S.optional(S.String)}) {}
export class DescribeAccountPreferencesRequest extends S.Class<DescribeAccountPreferencesRequest>("DescribeAccountPreferencesRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class DescribeBackupPolicyRequest extends S.Class<DescribeBackupPolicyRequest>("DescribeBackupPolicyRequest")({FileSystemId: S.String}) {}
export class DescribeFileSystemPolicyRequest extends S.Class<DescribeFileSystemPolicyRequest>("DescribeFileSystemPolicyRequest")({FileSystemId: S.String}) {}
export class DescribeFileSystemsRequest extends S.Class<DescribeFileSystemsRequest>("DescribeFileSystemsRequest")({MaxItems: S.optional(S.Number), Marker: S.optional(S.String), CreationToken: S.optional(S.String), FileSystemId: S.optional(S.String)}) {}
export class DescribeLifecycleConfigurationRequest extends S.Class<DescribeLifecycleConfigurationRequest>("DescribeLifecycleConfigurationRequest")({FileSystemId: S.String}) {}
export class DescribeMountTargetsRequest extends S.Class<DescribeMountTargetsRequest>("DescribeMountTargetsRequest")({MaxItems: S.optional(S.Number), Marker: S.optional(S.String), FileSystemId: S.optional(S.String), MountTargetId: S.optional(S.String), AccessPointId: S.optional(S.String)}) {}
export class DescribeMountTargetSecurityGroupsRequest extends S.Class<DescribeMountTargetSecurityGroupsRequest>("DescribeMountTargetSecurityGroupsRequest")({MountTargetId: S.String}) {}
export class DescribeReplicationConfigurationsRequest extends S.Class<DescribeReplicationConfigurationsRequest>("DescribeReplicationConfigurationsRequest")({FileSystemId: S.optional(S.String), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class DescribeTagsRequest extends S.Class<DescribeTagsRequest>("DescribeTagsRequest")({MaxItems: S.optional(S.Number), Marker: S.optional(S.String), FileSystemId: S.String}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceId: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ModifyMountTargetSecurityGroupsRequest extends S.Class<ModifyMountTargetSecurityGroupsRequest>("ModifyMountTargetSecurityGroupsRequest")({MountTargetId: S.String, SecurityGroups: S.optional(SecurityGroups)}) {}
export class PutAccountPreferencesRequest extends S.Class<PutAccountPreferencesRequest>("PutAccountPreferencesRequest")({ResourceIdType: S.String}) {}
export class PutFileSystemPolicyRequest extends S.Class<PutFileSystemPolicyRequest>("PutFileSystemPolicyRequest")({FileSystemId: S.String, Policy: S.String, BypassPolicyLockoutSafetyCheck: S.optional(S.Boolean)}) {}
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceId: S.String, Tags: Tags}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceId: S.String, TagKeys: TagKeys}) {}
export class UpdateFileSystemRequest extends S.Class<UpdateFileSystemRequest>("UpdateFileSystemRequest")({FileSystemId: S.String, ThroughputMode: S.optional(S.String), ProvisionedThroughputInMibps: S.optional(S.Number)}) {}
export class UpdateFileSystemProtectionRequest extends S.Class<UpdateFileSystemProtectionRequest>("UpdateFileSystemProtectionRequest")({FileSystemId: S.String, ReplicationOverwriteProtection: S.optional(S.String)}) {}
export const SecondaryGids = S.Array(S.Number);
export class PosixUser extends S.Class<PosixUser>("PosixUser")({Uid: S.Number, Gid: S.Number, SecondaryGids: S.optional(SecondaryGids)}) {}
export class DestinationToCreate extends S.Class<DestinationToCreate>("DestinationToCreate")({Region: S.optional(S.String), AvailabilityZoneName: S.optional(S.String), KmsKeyId: S.optional(S.String), FileSystemId: S.optional(S.String), RoleArn: S.optional(S.String)}) {}
export const DestinationsToCreate = S.Array(DestinationToCreate);
export class FileSystemSize extends S.Class<FileSystemSize>("FileSystemSize")({Value: S.Number, Timestamp: S.optional(S.Date), ValueInIA: S.optional(S.Number), ValueInStandard: S.optional(S.Number), ValueInArchive: S.optional(S.Number)}) {}
export class FileSystemProtectionDescription extends S.Class<FileSystemProtectionDescription>("FileSystemProtectionDescription")({ReplicationOverwriteProtection: S.optional(S.String)}) {}
export class FileSystemDescription extends S.Class<FileSystemDescription>("FileSystemDescription")({OwnerId: S.String, CreationToken: S.String, FileSystemId: S.String, FileSystemArn: S.optional(S.String), CreationTime: S.Date, LifeCycleState: S.String, Name: S.optional(S.String), NumberOfMountTargets: S.Number, SizeInBytes: FileSystemSize, PerformanceMode: S.String, Encrypted: S.optional(S.Boolean), KmsKeyId: S.optional(S.String), ThroughputMode: S.optional(S.String), ProvisionedThroughputInMibps: S.optional(S.Number), AvailabilityZoneName: S.optional(S.String), AvailabilityZoneId: S.optional(S.String), Tags: Tags, FileSystemProtection: S.optional(FileSystemProtectionDescription)}) {}
export const FileSystemDescriptions = S.Array(FileSystemDescription);
export class MountTargetDescription extends S.Class<MountTargetDescription>("MountTargetDescription")({OwnerId: S.optional(S.String), MountTargetId: S.String, FileSystemId: S.String, SubnetId: S.String, LifeCycleState: S.String, IpAddress: S.optional(S.String), Ipv6Address: S.optional(S.String), NetworkInterfaceId: S.optional(S.String), AvailabilityZoneId: S.optional(S.String), AvailabilityZoneName: S.optional(S.String), VpcId: S.optional(S.String)}) {}
export const MountTargetDescriptions = S.Array(MountTargetDescription);
export class BackupPolicy extends S.Class<BackupPolicy>("BackupPolicy")({Status: S.String}) {}
export class LifecyclePolicy extends S.Class<LifecyclePolicy>("LifecyclePolicy")({TransitionToIA: S.optional(S.String), TransitionToPrimaryStorageClass: S.optional(S.String), TransitionToArchive: S.optional(S.String)}) {}
export const LifecyclePolicies = S.Array(LifecyclePolicy);
export class CreateReplicationConfigurationRequest extends S.Class<CreateReplicationConfigurationRequest>("CreateReplicationConfigurationRequest")({SourceFileSystemId: S.String, Destinations: DestinationsToCreate}) {}
export class BadRequest extends S.Class<BadRequest>("BadRequest")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class AccessPointNotFound extends S.Class<AccessPointNotFound>("AccessPointNotFound")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class FileSystemInUse extends S.Class<FileSystemInUse>("FileSystemInUse")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class FileSystemNotFound extends S.Class<FileSystemNotFound>("FileSystemNotFound")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class DependencyTimeout extends S.Class<DependencyTimeout>("DependencyTimeout")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class InternalServerError extends S.Class<InternalServerError>("InternalServerError")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class BackupPolicyDescription extends S.Class<BackupPolicyDescription>("BackupPolicyDescription")({BackupPolicy: S.optional(BackupPolicy)}) {}
export class FileSystemPolicyDescription extends S.Class<FileSystemPolicyDescription>("FileSystemPolicyDescription")({FileSystemId: S.optional(S.String), Policy: S.optional(S.String)}) {}
export class DescribeFileSystemsResponse extends S.Class<DescribeFileSystemsResponse>("DescribeFileSystemsResponse")({Marker: S.optional(S.String), FileSystems: S.optional(FileSystemDescriptions), NextMarker: S.optional(S.String)}) {}
export class LifecycleConfigurationDescription extends S.Class<LifecycleConfigurationDescription>("LifecycleConfigurationDescription")({LifecyclePolicies: S.optional(LifecyclePolicies)}) {}
export class DescribeMountTargetsResponse extends S.Class<DescribeMountTargetsResponse>("DescribeMountTargetsResponse")({Marker: S.optional(S.String), MountTargets: S.optional(MountTargetDescriptions), NextMarker: S.optional(S.String)}) {}
export class DescribeMountTargetSecurityGroupsResponse extends S.Class<DescribeMountTargetSecurityGroupsResponse>("DescribeMountTargetSecurityGroupsResponse")({SecurityGroups: SecurityGroups}) {}
export class DescribeTagsResponse extends S.Class<DescribeTagsResponse>("DescribeTagsResponse")({Marker: S.optional(S.String), Tags: Tags, NextMarker: S.optional(S.String)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: S.optional(Tags), NextToken: S.optional(S.String)}) {}
export class IncorrectMountTargetState extends S.Class<IncorrectMountTargetState>("IncorrectMountTargetState")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export const Resources = S.Array(S.String);
export class ResourceIdPreference extends S.Class<ResourceIdPreference>("ResourceIdPreference")({ResourceIdType: S.optional(S.String), Resources: S.optional(Resources)}) {}
export class PutAccountPreferencesResponse extends S.Class<PutAccountPreferencesResponse>("PutAccountPreferencesResponse")({ResourceIdPreference: S.optional(ResourceIdPreference)}) {}
export class PutBackupPolicyRequest extends S.Class<PutBackupPolicyRequest>("PutBackupPolicyRequest")({FileSystemId: S.String, BackupPolicy: BackupPolicy}) {}
export class IncorrectFileSystemLifeCycleState extends S.Class<IncorrectFileSystemLifeCycleState>("IncorrectFileSystemLifeCycleState")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class PutLifecycleConfigurationRequest extends S.Class<PutLifecycleConfigurationRequest>("PutLifecycleConfigurationRequest")({FileSystemId: S.String, LifecyclePolicies: LifecyclePolicies}) {}
export class InsufficientThroughputCapacity extends S.Class<InsufficientThroughputCapacity>("InsufficientThroughputCapacity")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class CreationInfo extends S.Class<CreationInfo>("CreationInfo")({OwnerUid: S.Number, OwnerGid: S.Number, Permissions: S.String}) {}
export class RootDirectory extends S.Class<RootDirectory>("RootDirectory")({Path: S.optional(S.String), CreationInfo: S.optional(CreationInfo)}) {}
export class AccessPointDescription extends S.Class<AccessPointDescription>("AccessPointDescription")({ClientToken: S.optional(S.String), Name: S.optional(S.String), Tags: S.optional(Tags), AccessPointId: S.optional(S.String), AccessPointArn: S.optional(S.String), FileSystemId: S.optional(S.String), PosixUser: S.optional(PosixUser), RootDirectory: S.optional(RootDirectory), OwnerId: S.optional(S.String), LifeCycleState: S.optional(S.String)}) {}
export const AccessPointDescriptions = S.Array(AccessPointDescription);
export class CreateAccessPointRequest extends S.Class<CreateAccessPointRequest>("CreateAccessPointRequest")({ClientToken: S.String, Tags: S.optional(Tags), FileSystemId: S.String, PosixUser: S.optional(PosixUser), RootDirectory: S.optional(RootDirectory)}) {}
export class AvailabilityZonesMismatch extends S.Class<AvailabilityZonesMismatch>("AvailabilityZonesMismatch")({ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ConflictException extends S.Class<ConflictException>("ConflictException")({ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {}
export class MountTargetNotFound extends S.Class<MountTargetNotFound>("MountTargetNotFound")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class ReplicationNotFound extends S.Class<ReplicationNotFound>("ReplicationNotFound")({ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {}
export class DescribeAccessPointsResponse extends S.Class<DescribeAccessPointsResponse>("DescribeAccessPointsResponse")({AccessPoints: S.optional(AccessPointDescriptions), NextToken: S.optional(S.String)}) {}
export class DescribeAccountPreferencesResponse extends S.Class<DescribeAccountPreferencesResponse>("DescribeAccountPreferencesResponse")({ResourceIdPreference: S.optional(ResourceIdPreference), NextToken: S.optional(S.String)}) {}
export class PolicyNotFound extends S.Class<PolicyNotFound>("PolicyNotFound")({ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {}
export class SecurityGroupLimitExceeded extends S.Class<SecurityGroupLimitExceeded>("SecurityGroupLimitExceeded")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class ValidationException extends S.Class<ValidationException>("ValidationException")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class InvalidPolicyException extends S.Class<InvalidPolicyException>("InvalidPolicyException")({ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {}
export class ThroughputLimitExceeded extends S.Class<ThroughputLimitExceeded>("ThroughputLimitExceeded")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class ReplicationAlreadyExists extends S.Class<ReplicationAlreadyExists>("ReplicationAlreadyExists")({ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {}
export class Destination extends S.Class<Destination>("Destination")({Status: S.String, FileSystemId: S.String, Region: S.String, LastReplicatedTimestamp: S.optional(S.Date), OwnerId: S.optional(S.String), StatusMessage: S.optional(S.String), RoleArn: S.optional(S.String)}) {}
export const Destinations = S.Array(Destination);
export class ReplicationConfigurationDescription extends S.Class<ReplicationConfigurationDescription>("ReplicationConfigurationDescription")({SourceFileSystemId: S.String, SourceFileSystemRegion: S.String, SourceFileSystemArn: S.String, OriginalSourceFileSystemArn: S.String, CreationTime: S.Date, Destinations: Destinations, SourceFileSystemOwnerId: S.optional(S.String)}) {}
export const ReplicationConfigurationDescriptions = S.Array(ReplicationConfigurationDescription);
export class AccessPointAlreadyExists extends S.Class<AccessPointAlreadyExists>("AccessPointAlreadyExists")({ErrorCode: S.String, Message: S.optional(S.String), AccessPointId: S.String}) {}
export class FileSystemAlreadyExists extends S.Class<FileSystemAlreadyExists>("FileSystemAlreadyExists")({ErrorCode: S.String, Message: S.optional(S.String), FileSystemId: S.String}) {}
export class IpAddressInUse extends S.Class<IpAddressInUse>("IpAddressInUse")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class FileSystemLimitExceeded extends S.Class<FileSystemLimitExceeded>("FileSystemLimitExceeded")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class DescribeReplicationConfigurationsResponse extends S.Class<DescribeReplicationConfigurationsResponse>("DescribeReplicationConfigurationsResponse")({Replications: S.optional(ReplicationConfigurationDescriptions), NextToken: S.optional(S.String)}) {}
export class SecurityGroupNotFound extends S.Class<SecurityGroupNotFound>("SecurityGroupNotFound")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class TooManyRequests extends S.Class<TooManyRequests>("TooManyRequests")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class AccessPointLimitExceeded extends S.Class<AccessPointLimitExceeded>("AccessPointLimitExceeded")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class UnsupportedAvailabilityZone extends S.Class<UnsupportedAvailabilityZone>("UnsupportedAvailabilityZone")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class MountTargetConflict extends S.Class<MountTargetConflict>("MountTargetConflict")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class ThrottlingException extends S.Class<ThrottlingException>("ThrottlingException")({ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {}
export class NetworkInterfaceLimitExceeded extends S.Class<NetworkInterfaceLimitExceeded>("NetworkInterfaceLimitExceeded")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class NoFreeAddressesInSubnet extends S.Class<NoFreeAddressesInSubnet>("NoFreeAddressesInSubnet")({ErrorCode: S.String, Message: S.optional(S.String)}) {}
export class SubnetNotFound extends S.Class<SubnetNotFound>("SubnetNotFound")({ErrorCode: S.String, Message: S.optional(S.String)}) {}

//# Errors
export class BadRequestError extends S.TaggedError<BadRequestError>()("BadRequest", BadRequest.fields) {};
export class FileSystemNotFoundError extends S.TaggedError<FileSystemNotFoundError>()("FileSystemNotFound", FileSystemNotFound.fields) {};
export class InternalServerErrorError extends S.TaggedError<InternalServerErrorError>()("InternalServerError", InternalServerError.fields) {};
export class AccessPointNotFoundError extends S.TaggedError<AccessPointNotFoundError>()("AccessPointNotFound", AccessPointNotFound.fields) {};
export class IncorrectFileSystemLifeCycleStateError extends S.TaggedError<IncorrectFileSystemLifeCycleStateError>()("IncorrectFileSystemLifeCycleState", IncorrectFileSystemLifeCycleState.fields) {};
export class FileSystemInUseError extends S.TaggedError<FileSystemInUseError>()("FileSystemInUse", FileSystemInUse.fields) {};
export class DependencyTimeoutError extends S.TaggedError<DependencyTimeoutError>()("DependencyTimeout", DependencyTimeout.fields) {};
export class PolicyNotFoundError extends S.TaggedError<PolicyNotFoundError>()("PolicyNotFound", PolicyNotFound.fields) {};
export class MountTargetNotFoundError extends S.TaggedError<MountTargetNotFoundError>()("MountTargetNotFound", MountTargetNotFound.fields) {};
export class IncorrectMountTargetStateError extends S.TaggedError<IncorrectMountTargetStateError>()("IncorrectMountTargetState", IncorrectMountTargetState.fields) {};
export class InsufficientThroughputCapacityError extends S.TaggedError<InsufficientThroughputCapacityError>()("InsufficientThroughputCapacity", InsufficientThroughputCapacity.fields) {};
export class AvailabilityZonesMismatchError extends S.TaggedError<AvailabilityZonesMismatchError>()("AvailabilityZonesMismatch", AvailabilityZonesMismatch.fields) {};
export class ConflictExceptionError extends S.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class ReplicationNotFoundError extends S.TaggedError<ReplicationNotFoundError>()("ReplicationNotFound", ReplicationNotFound.fields) {};
export class ValidationExceptionError extends S.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};
export class SecurityGroupLimitExceededError extends S.TaggedError<SecurityGroupLimitExceededError>()("SecurityGroupLimitExceeded", SecurityGroupLimitExceeded.fields) {};
export class InvalidPolicyExceptionError extends S.TaggedError<InvalidPolicyExceptionError>()("InvalidPolicyException", InvalidPolicyException.fields) {};
export class ThroughputLimitExceededError extends S.TaggedError<ThroughputLimitExceededError>()("ThroughputLimitExceeded", ThroughputLimitExceeded.fields) {};
export class ReplicationAlreadyExistsError extends S.TaggedError<ReplicationAlreadyExistsError>()("ReplicationAlreadyExists", ReplicationAlreadyExists.fields) {};
export class TooManyRequestsError extends S.TaggedError<TooManyRequestsError>()("TooManyRequests", TooManyRequests.fields) {};
export class AccessPointAlreadyExistsError extends S.TaggedError<AccessPointAlreadyExistsError>()("AccessPointAlreadyExists", AccessPointAlreadyExists.fields) {};
export class FileSystemAlreadyExistsError extends S.TaggedError<FileSystemAlreadyExistsError>()("FileSystemAlreadyExists", FileSystemAlreadyExists.fields) {};
export class FileSystemLimitExceededError extends S.TaggedError<FileSystemLimitExceededError>()("FileSystemLimitExceeded", FileSystemLimitExceeded.fields) {};
export class IpAddressInUseError extends S.TaggedError<IpAddressInUseError>()("IpAddressInUse", IpAddressInUse.fields) {};
export class UnsupportedAvailabilityZoneError extends S.TaggedError<UnsupportedAvailabilityZoneError>()("UnsupportedAvailabilityZone", UnsupportedAvailabilityZone.fields) {};
export class SecurityGroupNotFoundError extends S.TaggedError<SecurityGroupNotFoundError>()("SecurityGroupNotFound", SecurityGroupNotFound.fields) {};
export class AccessPointLimitExceededError extends S.TaggedError<AccessPointLimitExceededError>()("AccessPointLimitExceeded", AccessPointLimitExceeded.fields) {};
export class MountTargetConflictError extends S.TaggedError<MountTargetConflictError>()("MountTargetConflict", MountTargetConflict.fields) {};
export class ThrottlingExceptionError extends S.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class NetworkInterfaceLimitExceededError extends S.TaggedError<NetworkInterfaceLimitExceededError>()("NetworkInterfaceLimitExceeded", NetworkInterfaceLimitExceeded.fields) {};
export class NoFreeAddressesInSubnetError extends S.TaggedError<NoFreeAddressesInSubnetError>()("NoFreeAddressesInSubnet", NoFreeAddressesInSubnet.fields) {};
export class SubnetNotFoundError extends S.TaggedError<SubnetNotFoundError>()("SubnetNotFound", SubnetNotFound.fields) {};

//# Operations
export const deleteTags = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/delete-tags/{FileSystemId}", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteTags" }, DeleteTagsRequest, S.Struct({}), [BadRequestError, FileSystemNotFoundError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/resource-tags/{ResourceId}", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.TagResource" }, TagResourceRequest, S.Struct({}), [AccessPointNotFoundError, BadRequestError, FileSystemNotFoundError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/resource-tags/{ResourceId}", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.UntagResource" }, UntagResourceRequest, S.Struct({}), [AccessPointNotFoundError, BadRequestError, FileSystemNotFoundError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createTags = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/create-tags/{FileSystemId}", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.CreateTags" }, CreateTagsRequest, S.Struct({}), [BadRequestError, FileSystemNotFoundError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAccessPoint = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/access-points/{AccessPointId}", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteAccessPoint" }, DeleteAccessPointRequest, S.Struct({}), [AccessPointNotFoundError, BadRequestError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteFileSystem = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteFileSystem" }, DeleteFileSystemRequest, S.Struct({}), [BadRequestError, FileSystemInUseError, FileSystemNotFoundError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteFileSystemPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/policy", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteFileSystemPolicy" }, DeleteFileSystemPolicyRequest, S.Struct({}), [BadRequestError, FileSystemNotFoundError, IncorrectFileSystemLifeCycleStateError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeFileSystemPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/policy", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeFileSystemPolicy" }, DescribeFileSystemPolicyRequest, FileSystemPolicyDescription, [BadRequestError, FileSystemNotFoundError, InternalServerErrorError, PolicyNotFoundError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeFileSystems = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeFileSystems" }, DescribeFileSystemsRequest, DescribeFileSystemsResponse, [BadRequestError, FileSystemNotFoundError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLifecycleConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/lifecycle-configuration", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeLifecycleConfiguration" }, DescribeLifecycleConfigurationRequest, LifecycleConfigurationDescription, [BadRequestError, FileSystemNotFoundError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeMountTargets = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/mount-targets", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeMountTargets" }, DescribeMountTargetsRequest, DescribeMountTargetsResponse, [AccessPointNotFoundError, BadRequestError, FileSystemNotFoundError, InternalServerErrorError, MountTargetNotFoundError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeMountTargetSecurityGroups = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/mount-targets/{MountTargetId}/security-groups", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeMountTargetSecurityGroups" }, DescribeMountTargetSecurityGroupsRequest, DescribeMountTargetSecurityGroupsResponse, [BadRequestError, IncorrectMountTargetStateError, InternalServerErrorError, MountTargetNotFoundError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeTags = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/tags/{FileSystemId}", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeTags" }, DescribeTagsRequest, DescribeTagsResponse, [BadRequestError, FileSystemNotFoundError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/resource-tags/{ResourceId}", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [AccessPointNotFoundError, BadRequestError, FileSystemNotFoundError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putAccountPreferences = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/account-preferences", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.PutAccountPreferences" }, PutAccountPreferencesRequest, PutAccountPreferencesResponse, [BadRequestError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putLifecycleConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/lifecycle-configuration", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.PutLifecycleConfiguration" }, PutLifecycleConfigurationRequest, LifecycleConfigurationDescription, [BadRequestError, FileSystemNotFoundError, IncorrectFileSystemLifeCycleStateError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteMountTarget = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/mount-targets/{MountTargetId}", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteMountTarget" }, DeleteMountTargetRequest, S.Struct({}), [BadRequestError, DependencyTimeoutError, InternalServerErrorError, MountTargetNotFoundError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteReplicationConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{SourceFileSystemId}/replication-configuration", method: "DELETE", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DeleteReplicationConfiguration" }, DeleteReplicationConfigurationRequest, S.Struct({}), [BadRequestError, FileSystemNotFoundError, InternalServerErrorError, ReplicationNotFoundError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAccessPoints = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/access-points", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeAccessPoints" }, DescribeAccessPointsRequest, DescribeAccessPointsResponse, [AccessPointNotFoundError, BadRequestError, FileSystemNotFoundError, InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAccountPreferences = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/account-preferences", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeAccountPreferences" }, DescribeAccountPreferencesRequest, DescribeAccountPreferencesResponse, [InternalServerErrorError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeBackupPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/backup-policy", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeBackupPolicy" }, DescribeBackupPolicyRequest, BackupPolicyDescription, [BadRequestError, FileSystemNotFoundError, InternalServerErrorError, PolicyNotFoundError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putBackupPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/backup-policy", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.PutBackupPolicy" }, PutBackupPolicyRequest, BackupPolicyDescription, [BadRequestError, FileSystemNotFoundError, IncorrectFileSystemLifeCycleStateError, InternalServerErrorError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putFileSystemPolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/policy", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.PutFileSystemPolicy" }, PutFileSystemPolicyRequest, FileSystemPolicyDescription, [BadRequestError, FileSystemNotFoundError, IncorrectFileSystemLifeCycleStateError, InternalServerErrorError, InvalidPolicyExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateFileSystemProtection = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}/protection", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.UpdateFileSystemProtection" }, UpdateFileSystemProtectionRequest, FileSystemProtectionDescription, [BadRequestError, FileSystemNotFoundError, IncorrectFileSystemLifeCycleStateError, InsufficientThroughputCapacityError, InternalServerErrorError, ReplicationAlreadyExistsError, ThroughputLimitExceededError, TooManyRequestsError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createReplicationConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{SourceFileSystemId}/replication-configuration", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.CreateReplicationConfiguration" }, CreateReplicationConfigurationRequest, ReplicationConfigurationDescription, [BadRequestError, ConflictExceptionError, FileSystemLimitExceededError, FileSystemNotFoundError, IncorrectFileSystemLifeCycleStateError, InsufficientThroughputCapacityError, InternalServerErrorError, ReplicationNotFoundError, ThroughputLimitExceededError, UnsupportedAvailabilityZoneError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeReplicationConfigurations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/replication-configurations", method: "GET", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.DescribeReplicationConfigurations" }, DescribeReplicationConfigurationsRequest, DescribeReplicationConfigurationsResponse, [BadRequestError, FileSystemNotFoundError, InternalServerErrorError, ReplicationNotFoundError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const modifyMountTargetSecurityGroups = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/mount-targets/{MountTargetId}/security-groups", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.ModifyMountTargetSecurityGroups" }, ModifyMountTargetSecurityGroupsRequest, S.Struct({}), [BadRequestError, IncorrectMountTargetStateError, InternalServerErrorError, MountTargetNotFoundError, SecurityGroupLimitExceededError, SecurityGroupNotFoundError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateFileSystem = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems/{FileSystemId}", method: "PUT", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.UpdateFileSystem" }, UpdateFileSystemRequest, FileSystemDescription, [BadRequestError, FileSystemNotFoundError, IncorrectFileSystemLifeCycleStateError, InsufficientThroughputCapacityError, InternalServerErrorError, ThroughputLimitExceededError, TooManyRequestsError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createFileSystem = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/file-systems", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.CreateFileSystem" }, CreateFileSystemRequest, FileSystemDescription, [BadRequestError, FileSystemAlreadyExistsError, FileSystemLimitExceededError, InsufficientThroughputCapacityError, InternalServerErrorError, ThroughputLimitExceededError, UnsupportedAvailabilityZoneError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createAccessPoint = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/access-points", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.CreateAccessPoint" }, CreateAccessPointRequest, AccessPointDescription, [AccessPointAlreadyExistsError, AccessPointLimitExceededError, BadRequestError, FileSystemNotFoundError, IncorrectFileSystemLifeCycleStateError, InternalServerErrorError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createMountTarget = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2015-02-01", uri: "/2015-02-01/mount-targets", method: "POST", sdkId: "EFS", sigV4ServiceName: "elasticfilesystem", name: "MagnolioAPIService_v20150201.CreateMountTarget" }, CreateMountTargetRequest, MountTargetDescription, [AvailabilityZonesMismatchError, BadRequestError, FileSystemNotFoundError, IncorrectFileSystemLifeCycleStateError, InternalServerErrorError, IpAddressInUseError, MountTargetConflictError, NetworkInterfaceLimitExceededError, NoFreeAddressesInSubnetError, SecurityGroupLimitExceededError, SecurityGroupNotFoundError, SubnetNotFoundError, UnsupportedAvailabilityZoneError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
