import { Schema} from "effect"
import { FormatXMLRequest, FormatXMLResponse, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
const TagKeyList = Schema.Array(Schema.String)
const CreateTargetAccountConfigurationRequest = Schema.Struct({clientToken: Schema.optional(Schema.String), experimentTemplateId: Schema.String, accountId: Schema.String, roleArn: Schema.String, description: Schema.optional(Schema.String)})
const DeleteExperimentTemplateRequest = Schema.Struct({id: Schema.String})
const DeleteTargetAccountConfigurationRequest = Schema.Struct({experimentTemplateId: Schema.String, accountId: Schema.String})
const GetActionRequest = Schema.Struct({id: Schema.String})
const GetExperimentRequest = Schema.Struct({id: Schema.String})
const GetExperimentTargetAccountConfigurationRequest = Schema.Struct({experimentId: Schema.String, accountId: Schema.String})
const GetExperimentTemplateRequest = Schema.Struct({id: Schema.String})
const GetSafetyLeverRequest = Schema.Struct({id: Schema.String})
const GetTargetAccountConfigurationRequest = Schema.Struct({experimentTemplateId: Schema.String, accountId: Schema.String})
const GetTargetResourceTypeRequest = Schema.Struct({resourceType: Schema.String})
const ListActionsRequest = Schema.Struct({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)})
const ListExperimentResolvedTargetsRequest = Schema.Struct({experimentId: Schema.String, maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String), targetName: Schema.optional(Schema.String)})
const ListExperimentsRequest = Schema.Struct({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String), experimentTemplateId: Schema.optional(Schema.String)})
const ListExperimentTargetAccountConfigurationsRequest = Schema.Struct({experimentId: Schema.String, nextToken: Schema.optional(Schema.String)})
const ListExperimentTemplatesRequest = Schema.Struct({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)})
const ListTagsForResourceRequest = Schema.Struct({resourceArn: Schema.String})
const ListTargetAccountConfigurationsRequest = Schema.Struct({experimentTemplateId: Schema.String, maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)})
const ListTargetResourceTypesRequest = Schema.Struct({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)})
const StopExperimentRequest = Schema.Struct({id: Schema.String})
const TagResourceRequest = Schema.Struct({resourceArn: Schema.String, tags: TagMap})
const TagResourceResponse = Schema.Struct({})
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "POST", sdkId: "fis", sigV4ServiceName: "fis", name: "TagResource" }, TagResourceRequest, TagResourceResponse, Schema.Void), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UntagResourceRequest = Schema.Struct({resourceArn: Schema.String, tagKeys: Schema.optional(TagKeyList)})
const UntagResourceResponse = Schema.Struct({})
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "fis", sigV4ServiceName: "fis", name: "UntagResource" }, UntagResourceRequest, UntagResourceResponse, Schema.Void), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateTargetAccountConfigurationRequest = Schema.Struct({experimentTemplateId: Schema.String, accountId: Schema.String, roleArn: Schema.optional(Schema.String), description: Schema.optional(Schema.String)})
const CreateExperimentTemplateStopConditionInput = Schema.Struct({source: Schema.String, value: Schema.optional(Schema.String)})
const CreateExperimentTemplateStopConditionInputList = Schema.Array(CreateExperimentTemplateStopConditionInput)
const TagMap = Schema.Record({key: Schema.String, value: Schema.String})
const CreateExperimentTemplateExperimentOptionsInput = Schema.Struct({accountTargeting: Schema.optional(Schema.String), emptyTargetResolutionMode: Schema.optional(Schema.String)})
const StartExperimentExperimentOptionsInput = Schema.Struct({actionsMode: Schema.optional(Schema.String)})
const UpdateExperimentTemplateStopConditionInput = Schema.Struct({source: Schema.String, value: Schema.optional(Schema.String)})
const UpdateExperimentTemplateStopConditionInputList = Schema.Array(UpdateExperimentTemplateStopConditionInput)
const UpdateExperimentTemplateLogConfigurationInput = Schema.Struct({cloudWatchLogsConfiguration: Schema.optional(ExperimentTemplateCloudWatchLogsLogConfigurationInput), s3Configuration: Schema.optional(ExperimentTemplateS3LogConfigurationInput), logSchemaVersion: Schema.optional(Schema.Number)})
const UpdateExperimentTemplateExperimentOptionsInput = Schema.Struct({emptyTargetResolutionMode: Schema.optional(Schema.String)})
const UpdateExperimentTemplateReportConfigurationInput = Schema.Struct({outputs: Schema.optional(ExperimentTemplateReportConfigurationOutputsInput), dataSources: Schema.optional(ExperimentTemplateReportConfigurationDataSourcesInput), preExperimentDuration: Schema.optional(Schema.String), postExperimentDuration: Schema.optional(Schema.String)})
const UpdateSafetyLeverStateInput = Schema.Struct({status: Schema.String, reason: Schema.String})
const ResourceArnList = Schema.Array(Schema.String)
const ExperimentTemplateActionStartAfterList = Schema.Array(Schema.String)
const DeleteTargetAccountConfigurationResponse = Schema.Struct({targetAccountConfiguration: Schema.optional(TargetAccountConfiguration)})
const GetExperimentTemplateResponse = Schema.Struct({experimentTemplate: Schema.optional(ExperimentTemplate)})
const GetTargetAccountConfigurationResponse = Schema.Struct({targetAccountConfiguration: Schema.optional(TargetAccountConfiguration)})
export const GetTargetAccountConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experimentTemplates/{experimentTemplateId}/targetAccountConfigurations/{accountId}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "GetTargetAccountConfiguration" }, GetTargetAccountConfigurationRequest, GetTargetAccountConfigurationResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListTagsForResourceResponse = Schema.Struct({tags: Schema.optional(TagMap)})
export const ListTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, Schema.Void), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const StartExperimentRequest = Schema.Struct({clientToken: Schema.String, experimentTemplateId: Schema.String, experimentOptions: Schema.optional(StartExperimentExperimentOptionsInput), tags: Schema.optional(TagMap)})
const StopExperimentResponse = Schema.Struct({experiment: Schema.optional(Experiment)})
export const StopExperiment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experiments/{id}", method: "DELETE", sdkId: "fis", sigV4ServiceName: "fis", name: "StopExperiment" }, StopExperimentRequest, StopExperimentResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateSafetyLeverStateRequest = Schema.Struct({id: Schema.String, state: UpdateSafetyLeverStateInput})
const UpdateTargetAccountConfigurationResponse = Schema.Struct({targetAccountConfiguration: Schema.optional(TargetAccountConfiguration)})
export const UpdateTargetAccountConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experimentTemplates/{experimentTemplateId}/targetAccountConfigurations/{accountId}", method: "PATCH", sdkId: "fis", sigV4ServiceName: "fis", name: "UpdateTargetAccountConfiguration" }, UpdateTargetAccountConfigurationRequest, UpdateTargetAccountConfigurationResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ExperimentTemplateCloudWatchLogsLogConfigurationInput = Schema.Struct({logGroupArn: Schema.String})
const ExperimentTemplateS3LogConfigurationInput = Schema.Struct({bucketName: Schema.String, prefix: Schema.optional(Schema.String)})
const UpdateExperimentTemplateTargetInput = Schema.Struct({resourceType: Schema.String, resourceArns: Schema.optional(ResourceArnList), resourceTags: Schema.optional(TagMap), filters: Schema.optional(ExperimentTemplateTargetFilterInputList), selectionMode: Schema.String, parameters: Schema.optional(ExperimentTemplateTargetParameterMap)})
const UpdateExperimentTemplateActionInputItem = Schema.Struct({actionId: Schema.optional(Schema.String), description: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentTemplateActionParameterMap), targets: Schema.optional(ExperimentTemplateActionTargetMap), startAfter: Schema.optional(ExperimentTemplateActionStartAfterList)})
const ExperimentTemplateTargetFilterValues = Schema.Array(Schema.String)
const CreateExperimentTemplateLogConfigurationInput = Schema.Struct({cloudWatchLogsConfiguration: Schema.optional(ExperimentTemplateCloudWatchLogsLogConfigurationInput), s3Configuration: Schema.optional(ExperimentTemplateS3LogConfigurationInput), logSchemaVersion: Schema.Number})
const TargetAccountConfiguration = Schema.Struct({roleArn: Schema.optional(Schema.String), accountId: Schema.optional(Schema.String), description: Schema.optional(Schema.String)})
const ExperimentTargetAccountConfiguration = Schema.Struct({roleArn: Schema.optional(Schema.String), accountId: Schema.optional(Schema.String), description: Schema.optional(Schema.String)})
const ActionSummary = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), targets: Schema.optional(ActionTargetMap), tags: Schema.optional(TagMap)})
const ActionSummaryList = Schema.Array(ActionSummary)
const ExperimentSummary = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), experimentTemplateId: Schema.optional(Schema.String), state: Schema.optional(ExperimentState), creationTime: Schema.optional(Schema.Date), tags: Schema.optional(TagMap), experimentOptions: Schema.optional(ExperimentOptions)})
const ExperimentSummaryList = Schema.Array(ExperimentSummary)
const ExperimentTargetAccountConfigurationSummary = Schema.Struct({roleArn: Schema.optional(Schema.String), accountId: Schema.optional(Schema.String), description: Schema.optional(Schema.String)})
const ExperimentTargetAccountConfigurationList = Schema.Array(ExperimentTargetAccountConfigurationSummary)
const ExperimentTemplateSummary = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), creationTime: Schema.optional(Schema.Date), lastUpdateTime: Schema.optional(Schema.Date), tags: Schema.optional(TagMap)})
const ExperimentTemplateSummaryList = Schema.Array(ExperimentTemplateSummary)
const TargetAccountConfigurationSummary = Schema.Struct({roleArn: Schema.optional(Schema.String), accountId: Schema.optional(Schema.String), description: Schema.optional(Schema.String)})
const TargetAccountConfigurationList = Schema.Array(TargetAccountConfigurationSummary)
const TargetResourceTypeSummary = Schema.Struct({resourceType: Schema.optional(Schema.String), description: Schema.optional(Schema.String)})
const TargetResourceTypeSummaryList = Schema.Array(TargetResourceTypeSummary)
const UpdateExperimentTemplateTargetInputMap = Schema.Record({key: Schema.String, value: UpdateExperimentTemplateTargetInput})
const UpdateExperimentTemplateActionInputMap = Schema.Record({key: Schema.String, value: UpdateExperimentTemplateActionInputItem})
const ExperimentTemplateTargetInputFilter = Schema.Struct({path: Schema.String, values: ExperimentTemplateTargetFilterValues})
const ExperimentTemplateTargetFilterInputList = Schema.Array(ExperimentTemplateTargetInputFilter)
const ExperimentTemplateTargetParameterMap = Schema.Record({key: Schema.String, value: Schema.String})
const ExperimentTemplateActionParameterMap = Schema.Record({key: Schema.String, value: Schema.String})
const ExperimentTemplateActionTargetMap = Schema.Record({key: Schema.String, value: Schema.String})
const ReportConfigurationS3OutputInput = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)})
const ReportConfigurationCloudWatchDashboardInput = Schema.Struct({dashboardIdentifier: Schema.optional(Schema.String)})
const ReportConfigurationCloudWatchDashboardInputList = Schema.Array(ReportConfigurationCloudWatchDashboardInput)
const CreateTargetAccountConfigurationResponse = Schema.Struct({targetAccountConfiguration: Schema.optional(TargetAccountConfiguration)})
const ResourceNotFoundException = Schema.Struct({message: Schema.optional(Schema.String)})
export const DeleteTargetAccountConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experimentTemplates/{experimentTemplateId}/targetAccountConfigurations/{accountId}", method: "DELETE", sdkId: "fis", sigV4ServiceName: "fis", name: "DeleteTargetAccountConfiguration" }, DeleteTargetAccountConfigurationRequest, DeleteTargetAccountConfigurationResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetExperimentTargetAccountConfigurationResponse = Schema.Struct({targetAccountConfiguration: Schema.optional(ExperimentTargetAccountConfiguration)})
export const GetExperimentTargetAccountConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experiments/{experimentId}/targetAccountConfigurations/{accountId}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "GetExperimentTargetAccountConfiguration" }, GetExperimentTargetAccountConfigurationRequest, GetExperimentTargetAccountConfigurationResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ValidationException = Schema.Struct({message: Schema.optional(Schema.String)})
export const GetExperimentTemplate = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experimentTemplates/{id}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "GetExperimentTemplate" }, GetExperimentTemplateRequest, GetExperimentTemplateResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListActionsResponse = Schema.Struct({actions: Schema.optional(ActionSummaryList), nextToken: Schema.optional(Schema.String)})
export const ListActions = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/actions", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "ListActions" }, ListActionsRequest, ListActionsResponse, ErrorAnnotation("ValidationException", ValidationException)), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListExperimentsResponse = Schema.Struct({experiments: Schema.optional(ExperimentSummaryList), nextToken: Schema.optional(Schema.String)})
export const ListExperiments = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experiments", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "ListExperiments" }, ListExperimentsRequest, ListExperimentsResponse, ErrorAnnotation("ValidationException", ValidationException)), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListExperimentTargetAccountConfigurationsResponse = Schema.Struct({targetAccountConfigurations: Schema.optional(ExperimentTargetAccountConfigurationList), nextToken: Schema.optional(Schema.String)})
export const ListExperimentTargetAccountConfigurations = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experiments/{experimentId}/targetAccountConfigurations", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "ListExperimentTargetAccountConfigurations" }, ListExperimentTargetAccountConfigurationsRequest, ListExperimentTargetAccountConfigurationsResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListExperimentTemplatesResponse = Schema.Struct({experimentTemplates: Schema.optional(ExperimentTemplateSummaryList), nextToken: Schema.optional(Schema.String)})
export const ListExperimentTemplates = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experimentTemplates", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "ListExperimentTemplates" }, ListExperimentTemplatesRequest, ListExperimentTemplatesResponse, ErrorAnnotation("ValidationException", ValidationException)), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListTargetAccountConfigurationsResponse = Schema.Struct({targetAccountConfigurations: Schema.optional(TargetAccountConfigurationList), nextToken: Schema.optional(Schema.String)})
export const ListTargetAccountConfigurations = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experimentTemplates/{experimentTemplateId}/targetAccountConfigurations", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "ListTargetAccountConfigurations" }, ListTargetAccountConfigurationsRequest, ListTargetAccountConfigurationsResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListTargetResourceTypesResponse = Schema.Struct({targetResourceTypes: Schema.optional(TargetResourceTypeSummaryList), nextToken: Schema.optional(Schema.String)})
export const ListTargetResourceTypes = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/targetResourceTypes", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "ListTargetResourceTypes" }, ListTargetResourceTypesRequest, ListTargetResourceTypesResponse, ErrorAnnotation("ValidationException", ValidationException)), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const StartExperimentResponse = Schema.Struct({experiment: Schema.optional(Experiment)})
const UpdateExperimentTemplateRequest = Schema.Struct({id: Schema.String, description: Schema.optional(Schema.String), stopConditions: Schema.optional(UpdateExperimentTemplateStopConditionInputList), targets: Schema.optional(UpdateExperimentTemplateTargetInputMap), actions: Schema.optional(UpdateExperimentTemplateActionInputMap), roleArn: Schema.optional(Schema.String), logConfiguration: Schema.optional(UpdateExperimentTemplateLogConfigurationInput), experimentOptions: Schema.optional(UpdateExperimentTemplateExperimentOptionsInput), experimentReportConfiguration: Schema.optional(UpdateExperimentTemplateReportConfigurationInput)})
const UpdateSafetyLeverStateResponse = Schema.Struct({safetyLever: Schema.optional(SafetyLever)})
export const UpdateSafetyLeverState = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/safetyLevers/{id}/state", method: "PATCH", sdkId: "fis", sigV4ServiceName: "fis", name: "UpdateSafetyLeverState" }, UpdateSafetyLeverStateRequest, UpdateSafetyLeverStateResponse, Schema.Union(ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateExperimentTemplateTargetInput = Schema.Struct({resourceType: Schema.String, resourceArns: Schema.optional(ResourceArnList), resourceTags: Schema.optional(TagMap), filters: Schema.optional(ExperimentTemplateTargetFilterInputList), selectionMode: Schema.String, parameters: Schema.optional(ExperimentTemplateTargetParameterMap)})
const CreateExperimentTemplateActionInput = Schema.Struct({actionId: Schema.String, description: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentTemplateActionParameterMap), targets: Schema.optional(ExperimentTemplateActionTargetMap), startAfter: Schema.optional(ExperimentTemplateActionStartAfterList)})
const ExperimentTemplateReportConfigurationOutputsInput = Schema.Struct({s3Configuration: Schema.optional(ReportConfigurationS3OutputInput)})
const ExperimentTemplateReportConfigurationDataSourcesInput = Schema.Struct({cloudWatchDashboards: Schema.optional(ReportConfigurationCloudWatchDashboardInputList)})
const ExperimentTemplateStopCondition = Schema.Struct({source: Schema.optional(Schema.String), value: Schema.optional(Schema.String)})
const ExperimentTemplateStopConditionList = Schema.Array(ExperimentTemplateStopCondition)
const ExperimentTemplateExperimentOptions = Schema.Struct({accountTargeting: Schema.optional(Schema.String), emptyTargetResolutionMode: Schema.optional(Schema.String)})
const ExperimentStopCondition = Schema.Struct({source: Schema.optional(Schema.String), value: Schema.optional(Schema.String)})
const ExperimentStopConditionList = Schema.Array(ExperimentStopCondition)
const ExperimentOptions = Schema.Struct({accountTargeting: Schema.optional(Schema.String), emptyTargetResolutionMode: Schema.optional(Schema.String), actionsMode: Schema.optional(Schema.String)})
const SafetyLeverState = Schema.Struct({status: Schema.optional(Schema.String), reason: Schema.optional(Schema.String)})
const TargetInformationMap = Schema.Record({key: Schema.String, value: Schema.String})
const ExperimentActionStartAfterList = Schema.Array(Schema.String)
const CreateExperimentTemplateTargetInputMap = Schema.Record({key: Schema.String, value: CreateExperimentTemplateTargetInput})
const CreateExperimentTemplateActionInputMap = Schema.Record({key: Schema.String, value: CreateExperimentTemplateActionInput})
const CreateExperimentTemplateReportConfigurationInput = Schema.Struct({outputs: Schema.optional(ExperimentTemplateReportConfigurationOutputsInput), dataSources: Schema.optional(ExperimentTemplateReportConfigurationDataSourcesInput), preExperimentDuration: Schema.optional(Schema.String), postExperimentDuration: Schema.optional(Schema.String)})
const SafetyLever = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), state: Schema.optional(SafetyLeverState)})
const ResolvedTarget = Schema.Struct({resourceType: Schema.optional(Schema.String), targetName: Schema.optional(Schema.String), targetInformation: Schema.optional(TargetInformationMap)})
const ResolvedTargetList = Schema.Array(ResolvedTarget)
const ExperimentTemplateAction = Schema.Struct({actionId: Schema.optional(Schema.String), description: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentTemplateActionParameterMap), targets: Schema.optional(ExperimentTemplateActionTargetMap), startAfter: Schema.optional(ExperimentTemplateActionStartAfterList)})
const ExperimentTemplateCloudWatchLogsLogConfiguration = Schema.Struct({logGroupArn: Schema.optional(Schema.String)})
const ExperimentTemplateS3LogConfiguration = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)})
const ActionParameter = Schema.Struct({description: Schema.optional(Schema.String), required: Schema.optional(Schema.Boolean)})
const ActionTarget = Schema.Struct({resourceType: Schema.optional(Schema.String)})
const ExperimentError = Schema.Struct({accountId: Schema.optional(Schema.String), code: Schema.optional(Schema.String), location: Schema.optional(Schema.String)})
const ExperimentCloudWatchLogsLogConfiguration = Schema.Struct({logGroupArn: Schema.optional(Schema.String)})
const ExperimentS3LogConfiguration = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)})
const ExperimentReportS3Report = Schema.Struct({arn: Schema.optional(Schema.String), reportType: Schema.optional(Schema.String)})
const ExperimentReportS3ReportList = Schema.Array(ExperimentReportS3Report)
const TargetResourceTypeParameter = Schema.Struct({description: Schema.optional(Schema.String), required: Schema.optional(Schema.Boolean)})
const CreateExperimentTemplateRequest = Schema.Struct({clientToken: Schema.String, description: Schema.String, stopConditions: CreateExperimentTemplateStopConditionInputList, targets: Schema.optional(CreateExperimentTemplateTargetInputMap), actions: CreateExperimentTemplateActionInputMap, roleArn: Schema.String, tags: Schema.optional(TagMap), logConfiguration: Schema.optional(CreateExperimentTemplateLogConfigurationInput), experimentOptions: Schema.optional(CreateExperimentTemplateExperimentOptionsInput), experimentReportConfiguration: Schema.optional(CreateExperimentTemplateReportConfigurationInput)})
const ConflictException = Schema.Struct({message: Schema.optional(Schema.String)})
export const CreateTargetAccountConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experimentTemplates/{experimentTemplateId}/targetAccountConfigurations/{accountId}", method: "POST", sdkId: "fis", sigV4ServiceName: "fis", name: "CreateTargetAccountConfiguration" }, CreateTargetAccountConfigurationRequest, CreateTargetAccountConfigurationResponse, Schema.Union(ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ExperimentTargetFilterValues = Schema.Array(Schema.String)
const GetSafetyLeverResponse = Schema.Struct({safetyLever: Schema.optional(SafetyLever)})
export const GetSafetyLever = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/safetyLevers/{id}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "GetSafetyLever" }, GetSafetyLeverRequest, GetSafetyLeverResponse, ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException)), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListExperimentResolvedTargetsResponse = Schema.Struct({resolvedTargets: Schema.optional(ResolvedTargetList), nextToken: Schema.optional(Schema.String)})
export const ListExperimentResolvedTargets = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experiments/{experimentId}/resolvedTargets", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "ListExperimentResolvedTargets" }, ListExperimentResolvedTargetsRequest, ListExperimentResolvedTargetsResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ServiceQuotaExceededException = Schema.Struct({message: Schema.optional(Schema.String)})
export const StartExperiment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experiments", method: "POST", sdkId: "fis", sigV4ServiceName: "fis", name: "StartExperiment" }, StartExperimentRequest, StartExperimentResponse, Schema.Union(ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateExperimentTemplateResponse = Schema.Struct({experimentTemplate: Schema.optional(ExperimentTemplate)})
export const UpdateExperimentTemplate = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experimentTemplates/{id}", method: "PATCH", sdkId: "fis", sigV4ServiceName: "fis", name: "UpdateExperimentTemplate" }, UpdateExperimentTemplateRequest, UpdateExperimentTemplateResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ExperimentTemplateActionMap = Schema.Record({key: Schema.String, value: ExperimentTemplateAction})
const ExperimentTemplateLogConfiguration = Schema.Struct({cloudWatchLogsConfiguration: Schema.optional(ExperimentTemplateCloudWatchLogsLogConfiguration), s3Configuration: Schema.optional(ExperimentTemplateS3LogConfiguration), logSchemaVersion: Schema.optional(Schema.Number)})
const ActionParameterMap = Schema.Record({key: Schema.String, value: ActionParameter})
const ActionTargetMap = Schema.Record({key: Schema.String, value: ActionTarget})
const ExperimentState = Schema.Struct({status: Schema.optional(Schema.String), reason: Schema.optional(Schema.String), error: Schema.optional(ExperimentError)})
const ExperimentLogConfiguration = Schema.Struct({cloudWatchLogsConfiguration: Schema.optional(ExperimentCloudWatchLogsLogConfiguration), s3Configuration: Schema.optional(ExperimentS3LogConfiguration), logSchemaVersion: Schema.optional(Schema.Number)})
const TargetResourceTypeParameterMap = Schema.Record({key: Schema.String, value: TargetResourceTypeParameter})
const ExperimentTemplateTargetFilter = Schema.Struct({path: Schema.optional(Schema.String), values: Schema.optional(ExperimentTemplateTargetFilterValues)})
const ExperimentTemplateTargetFilterList = Schema.Array(ExperimentTemplateTargetFilter)
const ReportConfigurationS3Output = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)})
const ExperimentTemplateReportConfigurationCloudWatchDashboard = Schema.Struct({dashboardIdentifier: Schema.optional(Schema.String)})
const ExperimentTemplateReportConfigurationCloudWatchDashboardList = Schema.Array(ExperimentTemplateReportConfigurationCloudWatchDashboard)
const ExperimentTargetFilter = Schema.Struct({path: Schema.optional(Schema.String), values: Schema.optional(ExperimentTargetFilterValues)})
const ExperimentTargetFilterList = Schema.Array(ExperimentTargetFilter)
const ExperimentTargetParameterMap = Schema.Record({key: Schema.String, value: Schema.String})
const ExperimentActionParameterMap = Schema.Record({key: Schema.String, value: Schema.String})
const ExperimentActionTargetMap = Schema.Record({key: Schema.String, value: Schema.String})
const ExperimentActionState = Schema.Struct({status: Schema.optional(Schema.String), reason: Schema.optional(Schema.String)})
const ExperimentReportConfigurationOutputsS3Configuration = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)})
const ExperimentReportConfigurationCloudWatchDashboard = Schema.Struct({dashboardIdentifier: Schema.optional(Schema.String)})
const ExperimentReportConfigurationCloudWatchDashboardList = Schema.Array(ExperimentReportConfigurationCloudWatchDashboard)
const ExperimentReportError = Schema.Struct({code: Schema.optional(Schema.String)})
const Action = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), parameters: Schema.optional(ActionParameterMap), targets: Schema.optional(ActionTargetMap), tags: Schema.optional(TagMap)})
const TargetResourceType = Schema.Struct({resourceType: Schema.optional(Schema.String), description: Schema.optional(Schema.String), parameters: Schema.optional(TargetResourceTypeParameterMap)})
const ExperimentTemplateTarget = Schema.Struct({resourceType: Schema.optional(Schema.String), resourceArns: Schema.optional(ResourceArnList), resourceTags: Schema.optional(TagMap), filters: Schema.optional(ExperimentTemplateTargetFilterList), selectionMode: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentTemplateTargetParameterMap)})
const ExperimentTemplateReportConfigurationOutputs = Schema.Struct({s3Configuration: Schema.optional(ReportConfigurationS3Output)})
const ExperimentTemplateReportConfigurationDataSources = Schema.Struct({cloudWatchDashboards: Schema.optional(ExperimentTemplateReportConfigurationCloudWatchDashboardList)})
const ExperimentTarget = Schema.Struct({resourceType: Schema.optional(Schema.String), resourceArns: Schema.optional(ResourceArnList), resourceTags: Schema.optional(TagMap), filters: Schema.optional(ExperimentTargetFilterList), selectionMode: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentTargetParameterMap)})
const ExperimentAction = Schema.Struct({actionId: Schema.optional(Schema.String), description: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentActionParameterMap), targets: Schema.optional(ExperimentActionTargetMap), startAfter: Schema.optional(ExperimentActionStartAfterList), state: Schema.optional(ExperimentActionState), startTime: Schema.optional(Schema.Date), endTime: Schema.optional(Schema.Date)})
const ExperimentReportConfigurationOutputs = Schema.Struct({s3Configuration: Schema.optional(ExperimentReportConfigurationOutputsS3Configuration)})
const ExperimentReportConfigurationDataSources = Schema.Struct({cloudWatchDashboards: Schema.optional(ExperimentReportConfigurationCloudWatchDashboardList)})
const ExperimentReportState = Schema.Struct({status: Schema.optional(Schema.String), reason: Schema.optional(Schema.String), error: Schema.optional(ExperimentReportError)})
const CreateExperimentTemplateResponse = Schema.Struct({experimentTemplate: Schema.optional(ExperimentTemplate)})
export const CreateExperimentTemplate = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experimentTemplates", method: "POST", sdkId: "fis", sigV4ServiceName: "fis", name: "CreateExperimentTemplate" }, CreateExperimentTemplateRequest, CreateExperimentTemplateResponse, Schema.Union(ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetActionResponse = Schema.Struct({action: Schema.optional(Action)})
export const GetAction = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/actions/{id}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "GetAction" }, GetActionRequest, GetActionResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetTargetResourceTypeResponse = Schema.Struct({targetResourceType: Schema.optional(TargetResourceType)})
export const GetTargetResourceType = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/targetResourceTypes/{resourceType}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "GetTargetResourceType" }, GetTargetResourceTypeRequest, GetTargetResourceTypeResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ExperimentTemplateTargetMap = Schema.Record({key: Schema.String, value: ExperimentTemplateTarget})
const ExperimentTemplateReportConfiguration = Schema.Struct({outputs: Schema.optional(ExperimentTemplateReportConfigurationOutputs), dataSources: Schema.optional(ExperimentTemplateReportConfigurationDataSources), preExperimentDuration: Schema.optional(Schema.String), postExperimentDuration: Schema.optional(Schema.String)})
const ExperimentTargetMap = Schema.Record({key: Schema.String, value: ExperimentTarget})
const ExperimentActionMap = Schema.Record({key: Schema.String, value: ExperimentAction})
const ExperimentReportConfiguration = Schema.Struct({outputs: Schema.optional(ExperimentReportConfigurationOutputs), dataSources: Schema.optional(ExperimentReportConfigurationDataSources), preExperimentDuration: Schema.optional(Schema.String), postExperimentDuration: Schema.optional(Schema.String)})
const ExperimentReport = Schema.Struct({state: Schema.optional(ExperimentReportState), s3Reports: Schema.optional(ExperimentReportS3ReportList)})
const ExperimentTemplate = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), targets: Schema.optional(ExperimentTemplateTargetMap), actions: Schema.optional(ExperimentTemplateActionMap), stopConditions: Schema.optional(ExperimentTemplateStopConditionList), creationTime: Schema.optional(Schema.Date), lastUpdateTime: Schema.optional(Schema.Date), roleArn: Schema.optional(Schema.String), tags: Schema.optional(TagMap), logConfiguration: Schema.optional(ExperimentTemplateLogConfiguration), experimentOptions: Schema.optional(ExperimentTemplateExperimentOptions), targetAccountConfigurationsCount: Schema.optional(Schema.Number), experimentReportConfiguration: Schema.optional(ExperimentTemplateReportConfiguration)})
const Experiment = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), experimentTemplateId: Schema.optional(Schema.String), roleArn: Schema.optional(Schema.String), state: Schema.optional(ExperimentState), targets: Schema.optional(ExperimentTargetMap), actions: Schema.optional(ExperimentActionMap), stopConditions: Schema.optional(ExperimentStopConditionList), creationTime: Schema.optional(Schema.Date), startTime: Schema.optional(Schema.Date), endTime: Schema.optional(Schema.Date), tags: Schema.optional(TagMap), logConfiguration: Schema.optional(ExperimentLogConfiguration), experimentOptions: Schema.optional(ExperimentOptions), targetAccountConfigurationsCount: Schema.optional(Schema.Number), experimentReportConfiguration: Schema.optional(ExperimentReportConfiguration), experimentReport: Schema.optional(ExperimentReport)})
const DeleteExperimentTemplateResponse = Schema.Struct({experimentTemplate: Schema.optional(ExperimentTemplate)})
export const DeleteExperimentTemplate = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experimentTemplates/{id}", method: "DELETE", sdkId: "fis", sigV4ServiceName: "fis", name: "DeleteExperimentTemplate" }, DeleteExperimentTemplateRequest, DeleteExperimentTemplateResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetExperimentResponse = Schema.Struct({experiment: Schema.optional(Experiment)})
export const GetExperiment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/experiments/{id}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "GetExperiment" }, GetExperimentRequest, GetExperimentResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
