import { Schema} from "effect"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import { Operation, Path, Header, StreamBody, Body } from "../schema-helpers.ts";

//# Schemas
export const TagKeyList = Schema.Array(Schema.String);
export const CreateTargetAccountConfigurationRequest = Schema.Struct({clientToken: Schema.optional(Schema.String), experimentTemplateId: Schema.String, accountId: Schema.String, roleArn: Schema.String, description: Schema.optional(Schema.String)});
export const DeleteExperimentTemplateRequest = Schema.Struct({id: Schema.String});
export const DeleteTargetAccountConfigurationRequest = Schema.Struct({experimentTemplateId: Schema.String, accountId: Schema.String});
export const GetActionRequest = Schema.Struct({id: Schema.String});
export const GetExperimentRequest = Schema.Struct({id: Schema.String});
export const GetExperimentTargetAccountConfigurationRequest = Schema.Struct({experimentId: Schema.String, accountId: Schema.String});
export const GetExperimentTemplateRequest = Schema.Struct({id: Schema.String});
export const GetSafetyLeverRequest = Schema.Struct({id: Schema.String});
export const GetTargetAccountConfigurationRequest = Schema.Struct({experimentTemplateId: Schema.String, accountId: Schema.String});
export const GetTargetResourceTypeRequest = Schema.Struct({resourceType: Schema.String});
export const ListActionsRequest = Schema.Struct({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)});
export const ListExperimentResolvedTargetsRequest = Schema.Struct({experimentId: Schema.String, maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String), targetName: Schema.optional(Schema.String)});
export const ListExperimentsRequest = Schema.Struct({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String), experimentTemplateId: Schema.optional(Schema.String)});
export const ListExperimentTargetAccountConfigurationsRequest = Schema.Struct({experimentId: Schema.String, nextToken: Schema.optional(Schema.String)});
export const ListExperimentTemplatesRequest = Schema.Struct({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)});
export const ListTagsForResourceRequest = Schema.Struct({resourceArn: Schema.String});
export const ListTargetAccountConfigurationsRequest = Schema.Struct({experimentTemplateId: Schema.String, maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)});
export const ListTargetResourceTypesRequest = Schema.Struct({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)});
export const StopExperimentRequest = Schema.Struct({id: Schema.String});
export const TagMap = Schema.Record({key: Schema.String, value: Schema.String});
export const TagResourceRequest = Schema.Struct({resourceArn: Schema.String, tags: TagMap});
export const TagResourceResponse = Schema.Struct({});
export const UntagResourceRequest = Schema.Struct({resourceArn: Schema.String, tagKeys: Schema.optional(TagKeyList)});
export const UntagResourceResponse = Schema.Struct({});
export const UpdateTargetAccountConfigurationRequest = Schema.Struct({experimentTemplateId: Schema.String, accountId: Schema.String, roleArn: Schema.optional(Schema.String), description: Schema.optional(Schema.String)});
export const CreateExperimentTemplateStopConditionInput = Schema.Struct({source: Schema.String, value: Schema.optional(Schema.String)});
export const CreateExperimentTemplateStopConditionInputList = Schema.Array(CreateExperimentTemplateStopConditionInput);
export const CreateExperimentTemplateExperimentOptionsInput = Schema.Struct({accountTargeting: Schema.optional(Schema.String), emptyTargetResolutionMode: Schema.optional(Schema.String)});
export const StartExperimentExperimentOptionsInput = Schema.Struct({actionsMode: Schema.optional(Schema.String)});
export const UpdateExperimentTemplateStopConditionInput = Schema.Struct({source: Schema.String, value: Schema.optional(Schema.String)});
export const UpdateExperimentTemplateStopConditionInputList = Schema.Array(UpdateExperimentTemplateStopConditionInput);
export const ExperimentTemplateCloudWatchLogsLogConfigurationInput = Schema.Struct({logGroupArn: Schema.String});
export const ExperimentTemplateS3LogConfigurationInput = Schema.Struct({bucketName: Schema.String, prefix: Schema.optional(Schema.String)});
export const UpdateExperimentTemplateLogConfigurationInput = Schema.Struct({cloudWatchLogsConfiguration: Schema.optional(ExperimentTemplateCloudWatchLogsLogConfigurationInput), s3Configuration: Schema.optional(ExperimentTemplateS3LogConfigurationInput), logSchemaVersion: Schema.optional(Schema.Number)});
export const UpdateExperimentTemplateExperimentOptionsInput = Schema.Struct({emptyTargetResolutionMode: Schema.optional(Schema.String)});
export const ReportConfigurationS3OutputInput = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)});
export const ExperimentTemplateReportConfigurationOutputsInput = Schema.Struct({s3Configuration: Schema.optional(ReportConfigurationS3OutputInput)});
export const ReportConfigurationCloudWatchDashboardInput = Schema.Struct({dashboardIdentifier: Schema.optional(Schema.String)});
export const ReportConfigurationCloudWatchDashboardInputList = Schema.Array(ReportConfigurationCloudWatchDashboardInput);
export const ExperimentTemplateReportConfigurationDataSourcesInput = Schema.Struct({cloudWatchDashboards: Schema.optional(ReportConfigurationCloudWatchDashboardInputList)});
export const UpdateExperimentTemplateReportConfigurationInput = Schema.Struct({outputs: Schema.optional(ExperimentTemplateReportConfigurationOutputsInput), dataSources: Schema.optional(ExperimentTemplateReportConfigurationDataSourcesInput), preExperimentDuration: Schema.optional(Schema.String), postExperimentDuration: Schema.optional(Schema.String)});
export const UpdateSafetyLeverStateInput = Schema.Struct({status: Schema.String, reason: Schema.String});
export const ResourceArnList = Schema.Array(Schema.String);
export const ExperimentTemplateActionStartAfterList = Schema.Array(Schema.String);
export const TargetAccountConfiguration = Schema.Struct({roleArn: Schema.optional(Schema.String), accountId: Schema.optional(Schema.String), description: Schema.optional(Schema.String)});
export const DeleteTargetAccountConfigurationResponse = Schema.Struct({targetAccountConfiguration: Schema.optional(TargetAccountConfiguration)});
export const ExperimentTemplateTargetFilterValues = Schema.Array(Schema.String);
export const ExperimentTemplateTargetFilter = Schema.Struct({path: Schema.optional(Schema.String), values: Schema.optional(ExperimentTemplateTargetFilterValues)});
export const ExperimentTemplateTargetFilterList = Schema.Array(ExperimentTemplateTargetFilter);
export const ExperimentTemplateTargetParameterMap = Schema.Record({key: Schema.String, value: Schema.String});
export const ExperimentTemplateTarget = Schema.Struct({resourceType: Schema.optional(Schema.String), resourceArns: Schema.optional(ResourceArnList), resourceTags: Schema.optional(TagMap), filters: Schema.optional(ExperimentTemplateTargetFilterList), selectionMode: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentTemplateTargetParameterMap)});
export const ExperimentTemplateTargetMap = Schema.Record({key: Schema.String, value: ExperimentTemplateTarget});
export const ExperimentTemplateActionParameterMap = Schema.Record({key: Schema.String, value: Schema.String});
export const ExperimentTemplateActionTargetMap = Schema.Record({key: Schema.String, value: Schema.String});
export const ExperimentTemplateAction = Schema.Struct({actionId: Schema.optional(Schema.String), description: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentTemplateActionParameterMap), targets: Schema.optional(ExperimentTemplateActionTargetMap), startAfter: Schema.optional(ExperimentTemplateActionStartAfterList)});
export const ExperimentTemplateActionMap = Schema.Record({key: Schema.String, value: ExperimentTemplateAction});
export const ExperimentTemplateStopCondition = Schema.Struct({source: Schema.optional(Schema.String), value: Schema.optional(Schema.String)});
export const ExperimentTemplateStopConditionList = Schema.Array(ExperimentTemplateStopCondition);
export const ExperimentTemplateCloudWatchLogsLogConfiguration = Schema.Struct({logGroupArn: Schema.optional(Schema.String)});
export const ExperimentTemplateS3LogConfiguration = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)});
export const ExperimentTemplateLogConfiguration = Schema.Struct({cloudWatchLogsConfiguration: Schema.optional(ExperimentTemplateCloudWatchLogsLogConfiguration), s3Configuration: Schema.optional(ExperimentTemplateS3LogConfiguration), logSchemaVersion: Schema.optional(Schema.Number)});
export const ExperimentTemplateExperimentOptions = Schema.Struct({accountTargeting: Schema.optional(Schema.String), emptyTargetResolutionMode: Schema.optional(Schema.String)});
export const ReportConfigurationS3Output = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)});
export const ExperimentTemplateReportConfigurationOutputs = Schema.Struct({s3Configuration: Schema.optional(ReportConfigurationS3Output)});
export const ExperimentTemplateReportConfigurationCloudWatchDashboard = Schema.Struct({dashboardIdentifier: Schema.optional(Schema.String)});
export const ExperimentTemplateReportConfigurationCloudWatchDashboardList = Schema.Array(ExperimentTemplateReportConfigurationCloudWatchDashboard);
export const ExperimentTemplateReportConfigurationDataSources = Schema.Struct({cloudWatchDashboards: Schema.optional(ExperimentTemplateReportConfigurationCloudWatchDashboardList)});
export const ExperimentTemplateReportConfiguration = Schema.Struct({outputs: Schema.optional(ExperimentTemplateReportConfigurationOutputs), dataSources: Schema.optional(ExperimentTemplateReportConfigurationDataSources), preExperimentDuration: Schema.optional(Schema.String), postExperimentDuration: Schema.optional(Schema.String)});
export const ExperimentTemplate = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), targets: Schema.optional(ExperimentTemplateTargetMap), actions: Schema.optional(ExperimentTemplateActionMap), stopConditions: Schema.optional(ExperimentTemplateStopConditionList), creationTime: Schema.optional(Schema.Date), lastUpdateTime: Schema.optional(Schema.Date), roleArn: Schema.optional(Schema.String), tags: Schema.optional(TagMap), logConfiguration: Schema.optional(ExperimentTemplateLogConfiguration), experimentOptions: Schema.optional(ExperimentTemplateExperimentOptions), targetAccountConfigurationsCount: Schema.optional(Schema.Number), experimentReportConfiguration: Schema.optional(ExperimentTemplateReportConfiguration)});
export const GetExperimentTemplateResponse = Schema.Struct({experimentTemplate: Schema.optional(ExperimentTemplate)});
export const GetTargetAccountConfigurationResponse = Schema.Struct({targetAccountConfiguration: Schema.optional(TargetAccountConfiguration)});
export const ListTagsForResourceResponse = Schema.Struct({tags: Schema.optional(TagMap)});
export const StartExperimentRequest = Schema.Struct({clientToken: Schema.String, experimentTemplateId: Schema.String, experimentOptions: Schema.optional(StartExperimentExperimentOptionsInput), tags: Schema.optional(TagMap)});
export const ExperimentError = Schema.Struct({accountId: Schema.optional(Schema.String), code: Schema.optional(Schema.String), location: Schema.optional(Schema.String)});
export const ExperimentState = Schema.Struct({status: Schema.optional(Schema.String), reason: Schema.optional(Schema.String), error: Schema.optional(ExperimentError)});
export const ExperimentTargetFilterValues = Schema.Array(Schema.String);
export const ExperimentTargetFilter = Schema.Struct({path: Schema.optional(Schema.String), values: Schema.optional(ExperimentTargetFilterValues)});
export const ExperimentTargetFilterList = Schema.Array(ExperimentTargetFilter);
export const ExperimentTargetParameterMap = Schema.Record({key: Schema.String, value: Schema.String});
export const ExperimentTarget = Schema.Struct({resourceType: Schema.optional(Schema.String), resourceArns: Schema.optional(ResourceArnList), resourceTags: Schema.optional(TagMap), filters: Schema.optional(ExperimentTargetFilterList), selectionMode: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentTargetParameterMap)});
export const ExperimentTargetMap = Schema.Record({key: Schema.String, value: ExperimentTarget});
export const ExperimentActionParameterMap = Schema.Record({key: Schema.String, value: Schema.String});
export const ExperimentActionTargetMap = Schema.Record({key: Schema.String, value: Schema.String});
export const ExperimentActionStartAfterList = Schema.Array(Schema.String);
export const ExperimentActionState = Schema.Struct({status: Schema.optional(Schema.String), reason: Schema.optional(Schema.String)});
export const ExperimentAction = Schema.Struct({actionId: Schema.optional(Schema.String), description: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentActionParameterMap), targets: Schema.optional(ExperimentActionTargetMap), startAfter: Schema.optional(ExperimentActionStartAfterList), state: Schema.optional(ExperimentActionState), startTime: Schema.optional(Schema.Date), endTime: Schema.optional(Schema.Date)});
export const ExperimentActionMap = Schema.Record({key: Schema.String, value: ExperimentAction});
export const ExperimentStopCondition = Schema.Struct({source: Schema.optional(Schema.String), value: Schema.optional(Schema.String)});
export const ExperimentStopConditionList = Schema.Array(ExperimentStopCondition);
export const ExperimentCloudWatchLogsLogConfiguration = Schema.Struct({logGroupArn: Schema.optional(Schema.String)});
export const ExperimentS3LogConfiguration = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)});
export const ExperimentLogConfiguration = Schema.Struct({cloudWatchLogsConfiguration: Schema.optional(ExperimentCloudWatchLogsLogConfiguration), s3Configuration: Schema.optional(ExperimentS3LogConfiguration), logSchemaVersion: Schema.optional(Schema.Number)});
export const ExperimentOptions = Schema.Struct({accountTargeting: Schema.optional(Schema.String), emptyTargetResolutionMode: Schema.optional(Schema.String), actionsMode: Schema.optional(Schema.String)});
export const ExperimentReportConfigurationOutputsS3Configuration = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)});
export const ExperimentReportConfigurationOutputs = Schema.Struct({s3Configuration: Schema.optional(ExperimentReportConfigurationOutputsS3Configuration)});
export const ExperimentReportConfigurationCloudWatchDashboard = Schema.Struct({dashboardIdentifier: Schema.optional(Schema.String)});
export const ExperimentReportConfigurationCloudWatchDashboardList = Schema.Array(ExperimentReportConfigurationCloudWatchDashboard);
export const ExperimentReportConfigurationDataSources = Schema.Struct({cloudWatchDashboards: Schema.optional(ExperimentReportConfigurationCloudWatchDashboardList)});
export const ExperimentReportConfiguration = Schema.Struct({outputs: Schema.optional(ExperimentReportConfigurationOutputs), dataSources: Schema.optional(ExperimentReportConfigurationDataSources), preExperimentDuration: Schema.optional(Schema.String), postExperimentDuration: Schema.optional(Schema.String)});
export const ExperimentReportError = Schema.Struct({code: Schema.optional(Schema.String)});
export const ExperimentReportState = Schema.Struct({status: Schema.optional(Schema.String), reason: Schema.optional(Schema.String), error: Schema.optional(ExperimentReportError)});
export const ExperimentReportS3Report = Schema.Struct({arn: Schema.optional(Schema.String), reportType: Schema.optional(Schema.String)});
export const ExperimentReportS3ReportList = Schema.Array(ExperimentReportS3Report);
export const ExperimentReport = Schema.Struct({state: Schema.optional(ExperimentReportState), s3Reports: Schema.optional(ExperimentReportS3ReportList)});
export const Experiment = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), experimentTemplateId: Schema.optional(Schema.String), roleArn: Schema.optional(Schema.String), state: Schema.optional(ExperimentState), targets: Schema.optional(ExperimentTargetMap), actions: Schema.optional(ExperimentActionMap), stopConditions: Schema.optional(ExperimentStopConditionList), creationTime: Schema.optional(Schema.Date), startTime: Schema.optional(Schema.Date), endTime: Schema.optional(Schema.Date), tags: Schema.optional(TagMap), logConfiguration: Schema.optional(ExperimentLogConfiguration), experimentOptions: Schema.optional(ExperimentOptions), targetAccountConfigurationsCount: Schema.optional(Schema.Number), experimentReportConfiguration: Schema.optional(ExperimentReportConfiguration), experimentReport: Schema.optional(ExperimentReport)});
export const StopExperimentResponse = Schema.Struct({experiment: Schema.optional(Experiment)});
export const UpdateSafetyLeverStateRequest = Schema.Struct({id: Schema.String, state: UpdateSafetyLeverStateInput});
export const UpdateTargetAccountConfigurationResponse = Schema.Struct({targetAccountConfiguration: Schema.optional(TargetAccountConfiguration)});
export const ExperimentTemplateTargetInputFilter = Schema.Struct({path: Schema.String, values: ExperimentTemplateTargetFilterValues});
export const ExperimentTemplateTargetFilterInputList = Schema.Array(ExperimentTemplateTargetInputFilter);
export const UpdateExperimentTemplateTargetInput = Schema.Struct({resourceType: Schema.String, resourceArns: Schema.optional(ResourceArnList), resourceTags: Schema.optional(TagMap), filters: Schema.optional(ExperimentTemplateTargetFilterInputList), selectionMode: Schema.String, parameters: Schema.optional(ExperimentTemplateTargetParameterMap)});
export const UpdateExperimentTemplateActionInputItem = Schema.Struct({actionId: Schema.optional(Schema.String), description: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentTemplateActionParameterMap), targets: Schema.optional(ExperimentTemplateActionTargetMap), startAfter: Schema.optional(ExperimentTemplateActionStartAfterList)});
export const CreateExperimentTemplateLogConfigurationInput = Schema.Struct({cloudWatchLogsConfiguration: Schema.optional(ExperimentTemplateCloudWatchLogsLogConfigurationInput), s3Configuration: Schema.optional(ExperimentTemplateS3LogConfigurationInput), logSchemaVersion: Schema.Number});
export const ExperimentTargetAccountConfiguration = Schema.Struct({roleArn: Schema.optional(Schema.String), accountId: Schema.optional(Schema.String), description: Schema.optional(Schema.String)});
export const ActionTarget = Schema.Struct({resourceType: Schema.optional(Schema.String)});
export const ActionTargetMap = Schema.Record({key: Schema.String, value: ActionTarget});
export const ActionSummary = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), targets: Schema.optional(ActionTargetMap), tags: Schema.optional(TagMap)});
export const ActionSummaryList = Schema.Array(ActionSummary);
export const ExperimentSummary = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), experimentTemplateId: Schema.optional(Schema.String), state: Schema.optional(ExperimentState), creationTime: Schema.optional(Schema.Date), tags: Schema.optional(TagMap), experimentOptions: Schema.optional(ExperimentOptions)});
export const ExperimentSummaryList = Schema.Array(ExperimentSummary);
export const ExperimentTargetAccountConfigurationSummary = Schema.Struct({roleArn: Schema.optional(Schema.String), accountId: Schema.optional(Schema.String), description: Schema.optional(Schema.String)});
export const ExperimentTargetAccountConfigurationList = Schema.Array(ExperimentTargetAccountConfigurationSummary);
export const ExperimentTemplateSummary = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), creationTime: Schema.optional(Schema.Date), lastUpdateTime: Schema.optional(Schema.Date), tags: Schema.optional(TagMap)});
export const ExperimentTemplateSummaryList = Schema.Array(ExperimentTemplateSummary);
export const TargetAccountConfigurationSummary = Schema.Struct({roleArn: Schema.optional(Schema.String), accountId: Schema.optional(Schema.String), description: Schema.optional(Schema.String)});
export const TargetAccountConfigurationList = Schema.Array(TargetAccountConfigurationSummary);
export const TargetResourceTypeSummary = Schema.Struct({resourceType: Schema.optional(Schema.String), description: Schema.optional(Schema.String)});
export const TargetResourceTypeSummaryList = Schema.Array(TargetResourceTypeSummary);
export const UpdateExperimentTemplateTargetInputMap = Schema.Record({key: Schema.String, value: UpdateExperimentTemplateTargetInput});
export const UpdateExperimentTemplateActionInputMap = Schema.Record({key: Schema.String, value: UpdateExperimentTemplateActionInputItem});
export const CreateTargetAccountConfigurationResponse = Schema.Struct({targetAccountConfiguration: Schema.optional(TargetAccountConfiguration)});
export const ResourceNotFoundException = Schema.Struct({message: Schema.optional(Schema.String)});
export const GetExperimentTargetAccountConfigurationResponse = Schema.Struct({targetAccountConfiguration: Schema.optional(ExperimentTargetAccountConfiguration)});
export const ValidationException = Schema.Struct({message: Schema.optional(Schema.String)});
export const ListActionsResponse = Schema.Struct({actions: Schema.optional(ActionSummaryList), nextToken: Schema.optional(Schema.String)});
export const ListExperimentsResponse = Schema.Struct({experiments: Schema.optional(ExperimentSummaryList), nextToken: Schema.optional(Schema.String)});
export const ListExperimentTargetAccountConfigurationsResponse = Schema.Struct({targetAccountConfigurations: Schema.optional(ExperimentTargetAccountConfigurationList), nextToken: Schema.optional(Schema.String)});
export const ListExperimentTemplatesResponse = Schema.Struct({experimentTemplates: Schema.optional(ExperimentTemplateSummaryList), nextToken: Schema.optional(Schema.String)});
export const ListTargetAccountConfigurationsResponse = Schema.Struct({targetAccountConfigurations: Schema.optional(TargetAccountConfigurationList), nextToken: Schema.optional(Schema.String)});
export const ListTargetResourceTypesResponse = Schema.Struct({targetResourceTypes: Schema.optional(TargetResourceTypeSummaryList), nextToken: Schema.optional(Schema.String)});
export const StartExperimentResponse = Schema.Struct({experiment: Schema.optional(Experiment)});
export const UpdateExperimentTemplateRequest = Schema.Struct({id: Schema.String, description: Schema.optional(Schema.String), stopConditions: Schema.optional(UpdateExperimentTemplateStopConditionInputList), targets: Schema.optional(UpdateExperimentTemplateTargetInputMap), actions: Schema.optional(UpdateExperimentTemplateActionInputMap), roleArn: Schema.optional(Schema.String), logConfiguration: Schema.optional(UpdateExperimentTemplateLogConfigurationInput), experimentOptions: Schema.optional(UpdateExperimentTemplateExperimentOptionsInput), experimentReportConfiguration: Schema.optional(UpdateExperimentTemplateReportConfigurationInput)});
export const SafetyLeverState = Schema.Struct({status: Schema.optional(Schema.String), reason: Schema.optional(Schema.String)});
export const SafetyLever = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), state: Schema.optional(SafetyLeverState)});
export const UpdateSafetyLeverStateResponse = Schema.Struct({safetyLever: Schema.optional(SafetyLever)});
export const CreateExperimentTemplateTargetInput = Schema.Struct({resourceType: Schema.String, resourceArns: Schema.optional(ResourceArnList), resourceTags: Schema.optional(TagMap), filters: Schema.optional(ExperimentTemplateTargetFilterInputList), selectionMode: Schema.String, parameters: Schema.optional(ExperimentTemplateTargetParameterMap)});
export const CreateExperimentTemplateActionInput = Schema.Struct({actionId: Schema.String, description: Schema.optional(Schema.String), parameters: Schema.optional(ExperimentTemplateActionParameterMap), targets: Schema.optional(ExperimentTemplateActionTargetMap), startAfter: Schema.optional(ExperimentTemplateActionStartAfterList)});
export const TargetInformationMap = Schema.Record({key: Schema.String, value: Schema.String});
export const CreateExperimentTemplateTargetInputMap = Schema.Record({key: Schema.String, value: CreateExperimentTemplateTargetInput});
export const CreateExperimentTemplateActionInputMap = Schema.Record({key: Schema.String, value: CreateExperimentTemplateActionInput});
export const CreateExperimentTemplateReportConfigurationInput = Schema.Struct({outputs: Schema.optional(ExperimentTemplateReportConfigurationOutputsInput), dataSources: Schema.optional(ExperimentTemplateReportConfigurationDataSourcesInput), preExperimentDuration: Schema.optional(Schema.String), postExperimentDuration: Schema.optional(Schema.String)});
export const ResolvedTarget = Schema.Struct({resourceType: Schema.optional(Schema.String), targetName: Schema.optional(Schema.String), targetInformation: Schema.optional(TargetInformationMap)});
export const ResolvedTargetList = Schema.Array(ResolvedTarget);
export const ActionParameter = Schema.Struct({description: Schema.optional(Schema.String), required: Schema.optional(Schema.Boolean)});
export const TargetResourceTypeParameter = Schema.Struct({description: Schema.optional(Schema.String), required: Schema.optional(Schema.Boolean)});
export const CreateExperimentTemplateRequest = Schema.Struct({clientToken: Schema.String, description: Schema.String, stopConditions: CreateExperimentTemplateStopConditionInputList, targets: Schema.optional(CreateExperimentTemplateTargetInputMap), actions: CreateExperimentTemplateActionInputMap, roleArn: Schema.String, tags: Schema.optional(TagMap), logConfiguration: Schema.optional(CreateExperimentTemplateLogConfigurationInput), experimentOptions: Schema.optional(CreateExperimentTemplateExperimentOptionsInput), experimentReportConfiguration: Schema.optional(CreateExperimentTemplateReportConfigurationInput)});
export const ConflictException = Schema.Struct({message: Schema.optional(Schema.String)});
export const GetSafetyLeverResponse = Schema.Struct({safetyLever: Schema.optional(SafetyLever)});
export const ListExperimentResolvedTargetsResponse = Schema.Struct({resolvedTargets: Schema.optional(ResolvedTargetList), nextToken: Schema.optional(Schema.String)});
export const ServiceQuotaExceededException = Schema.Struct({message: Schema.optional(Schema.String)});
export const UpdateExperimentTemplateResponse = Schema.Struct({experimentTemplate: Schema.optional(ExperimentTemplate)});
export const ActionParameterMap = Schema.Record({key: Schema.String, value: ActionParameter});
export const TargetResourceTypeParameterMap = Schema.Record({key: Schema.String, value: TargetResourceTypeParameter});
export const Action = Schema.Struct({id: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), parameters: Schema.optional(ActionParameterMap), targets: Schema.optional(ActionTargetMap), tags: Schema.optional(TagMap)});
export const TargetResourceType = Schema.Struct({resourceType: Schema.optional(Schema.String), description: Schema.optional(Schema.String), parameters: Schema.optional(TargetResourceTypeParameterMap)});
export const CreateExperimentTemplateResponse = Schema.Struct({experimentTemplate: Schema.optional(ExperimentTemplate)});
export const GetActionResponse = Schema.Struct({action: Schema.optional(Action)});
export const GetTargetResourceTypeResponse = Schema.Struct({targetResourceType: Schema.optional(TargetResourceType)});
export const DeleteExperimentTemplateResponse = Schema.Struct({experimentTemplate: Schema.optional(ExperimentTemplate)});
export const GetExperimentResponse = Schema.Struct({experiment: Schema.optional(Experiment)});

//# Errors
export class ResourceNotFoundExceptionError extends Schema.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException) {};
export class ValidationExceptionError extends Schema.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException) {};
export class ConflictExceptionError extends Schema.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException) {};
export class ServiceQuotaExceededExceptionError extends Schema.TaggedError<ServiceQuotaExceededExceptionError>()("ServiceQuotaExceededException", ServiceQuotaExceededException) {};

//# Operations
export const tagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/tags/{resourceArn}", method: "POST", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.TagResource" }, TagResourceRequest, TagResourceResponse, []), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.UntagResource" }, UntagResourceRequest, UntagResourceResponse, []), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getTargetAccountConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experimentTemplates/{experimentTemplateId}/targetAccountConfigurations/{accountId}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.GetTargetAccountConfiguration" }, GetTargetAccountConfigurationRequest, GetTargetAccountConfigurationResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/tags/{resourceArn}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, []), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const stopExperiment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experiments/{id}", method: "DELETE", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.StopExperiment" }, StopExperimentRequest, StopExperimentResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateTargetAccountConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experimentTemplates/{experimentTemplateId}/targetAccountConfigurations/{accountId}", method: "PATCH", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.UpdateTargetAccountConfiguration" }, UpdateTargetAccountConfigurationRequest, UpdateTargetAccountConfigurationResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteTargetAccountConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experimentTemplates/{experimentTemplateId}/targetAccountConfigurations/{accountId}", method: "DELETE", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.DeleteTargetAccountConfiguration" }, DeleteTargetAccountConfigurationRequest, DeleteTargetAccountConfigurationResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getExperimentTargetAccountConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experiments/{experimentId}/targetAccountConfigurations/{accountId}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.GetExperimentTargetAccountConfiguration" }, GetExperimentTargetAccountConfigurationRequest, GetExperimentTargetAccountConfigurationResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getExperimentTemplate = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experimentTemplates/{id}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.GetExperimentTemplate" }, GetExperimentTemplateRequest, GetExperimentTemplateResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listActions = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/actions", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.ListActions" }, ListActionsRequest, ListActionsResponse, [ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listExperiments = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experiments", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.ListExperiments" }, ListExperimentsRequest, ListExperimentsResponse, [ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listExperimentTargetAccountConfigurations = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experiments/{experimentId}/targetAccountConfigurations", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.ListExperimentTargetAccountConfigurations" }, ListExperimentTargetAccountConfigurationsRequest, ListExperimentTargetAccountConfigurationsResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listExperimentTemplates = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experimentTemplates", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.ListExperimentTemplates" }, ListExperimentTemplatesRequest, ListExperimentTemplatesResponse, [ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTargetAccountConfigurations = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experimentTemplates/{experimentTemplateId}/targetAccountConfigurations", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.ListTargetAccountConfigurations" }, ListTargetAccountConfigurationsRequest, ListTargetAccountConfigurationsResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTargetResourceTypes = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/targetResourceTypes", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.ListTargetResourceTypes" }, ListTargetResourceTypesRequest, ListTargetResourceTypesResponse, [ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateSafetyLeverState = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/safetyLevers/{id}/state", method: "PATCH", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.UpdateSafetyLeverState" }, UpdateSafetyLeverStateRequest, UpdateSafetyLeverStateResponse, [ConflictExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createTargetAccountConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experimentTemplates/{experimentTemplateId}/targetAccountConfigurations/{accountId}", method: "POST", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.CreateTargetAccountConfiguration" }, CreateTargetAccountConfigurationRequest, CreateTargetAccountConfigurationResponse, [ConflictExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSafetyLever = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/safetyLevers/{id}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.GetSafetyLever" }, GetSafetyLeverRequest, GetSafetyLeverResponse, [ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listExperimentResolvedTargets = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experiments/{experimentId}/resolvedTargets", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.ListExperimentResolvedTargets" }, ListExperimentResolvedTargetsRequest, ListExperimentResolvedTargetsResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const startExperiment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experiments", method: "POST", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.StartExperiment" }, StartExperimentRequest, StartExperimentResponse, [ConflictExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateExperimentTemplate = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experimentTemplates/{id}", method: "PATCH", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.UpdateExperimentTemplate" }, UpdateExperimentTemplateRequest, UpdateExperimentTemplateResponse, [ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createExperimentTemplate = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experimentTemplates", method: "POST", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.CreateExperimentTemplate" }, CreateExperimentTemplateRequest, CreateExperimentTemplateResponse, [ConflictExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getAction = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/actions/{id}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.GetAction" }, GetActionRequest, GetActionResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getTargetResourceType = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/targetResourceTypes/{resourceType}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.GetTargetResourceType" }, GetTargetResourceTypeRequest, GetTargetResourceTypeResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteExperimentTemplate = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experimentTemplates/{id}", method: "DELETE", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.DeleteExperimentTemplate" }, DeleteExperimentTemplateRequest, DeleteExperimentTemplateResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getExperiment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-12-01", uri: "/experiments/{id}", method: "GET", sdkId: "fis", sigV4ServiceName: "fis", name: "FaultInjectionSimulator.GetExperiment" }, GetExperimentRequest, GetExperimentResponse, [ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
