import * as S from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const ForecastTypes = S.Array(S.String);
export const ForecastDimensions = S.Array(S.String);
export const ArnList = S.Array(S.String);
export const WhatIfForecastArnListForExport = S.Array(S.String);
export const TagKeys = S.Array(S.String);
export class Tag extends S.Class<Tag>("Tag")({Key: S.String, Value: S.String}) {}
export const Tags = S.Array(Tag);
export class CreateDatasetGroupRequest extends S.Class<CreateDatasetGroupRequest>("CreateDatasetGroupRequest")({DatasetGroupName: S.String, Domain: S.String, DatasetArns: S.optional(ArnList), Tags: S.optional(Tags)}) {}
export class S3Config extends S.Class<S3Config>("S3Config")({Path: S.String, RoleArn: S.String, KMSKeyArn: S.optional(S.String)}) {}
export class DataDestination extends S.Class<DataDestination>("DataDestination")({S3Config: S3Config}) {}
export class CreateForecastExportJobRequest extends S.Class<CreateForecastExportJobRequest>("CreateForecastExportJobRequest")({ForecastExportJobName: S.String, ForecastArn: S.String, Destination: DataDestination, Tags: S.optional(Tags), Format: S.optional(S.String)}) {}
export class CreateMonitorRequest extends S.Class<CreateMonitorRequest>("CreateMonitorRequest")({MonitorName: S.String, ResourceArn: S.String, Tags: S.optional(Tags)}) {}
export class CreatePredictorBacktestExportJobRequest extends S.Class<CreatePredictorBacktestExportJobRequest>("CreatePredictorBacktestExportJobRequest")({PredictorBacktestExportJobName: S.String, PredictorArn: S.String, Destination: DataDestination, Tags: S.optional(Tags), Format: S.optional(S.String)}) {}
export class DataSource extends S.Class<DataSource>("DataSource")({S3Config: S3Config}) {}
export class SchemaAttribute extends S.Class<SchemaAttribute>("SchemaAttribute")({AttributeName: S.optional(S.String), AttributeType: S.optional(S.String)}) {}
export const SchemaAttributes = S.Array(SchemaAttribute);
export class Schema extends S.Class<Schema>("Schema")({Attributes: S.optional(SchemaAttributes)}) {}
export class TimeSeriesIdentifiers extends S.Class<TimeSeriesIdentifiers>("TimeSeriesIdentifiers")({DataSource: S.optional(DataSource), Schema: S.optional(Schema), Format: S.optional(S.String)}) {}
export class TimeSeriesSelector extends S.Class<TimeSeriesSelector>("TimeSeriesSelector")({TimeSeriesIdentifiers: S.optional(TimeSeriesIdentifiers)}) {}
export class CreateWhatIfAnalysisRequest extends S.Class<CreateWhatIfAnalysisRequest>("CreateWhatIfAnalysisRequest")({WhatIfAnalysisName: S.String, ForecastArn: S.String, TimeSeriesSelector: S.optional(TimeSeriesSelector), Tags: S.optional(Tags)}) {}
export class CreateWhatIfForecastExportRequest extends S.Class<CreateWhatIfForecastExportRequest>("CreateWhatIfForecastExportRequest")({WhatIfForecastExportName: S.String, WhatIfForecastArns: WhatIfForecastArnListForExport, Destination: DataDestination, Tags: S.optional(Tags), Format: S.optional(S.String)}) {}
export class DeleteDatasetRequest extends S.Class<DeleteDatasetRequest>("DeleteDatasetRequest")({DatasetArn: S.String}) {}
export class DeleteDatasetGroupRequest extends S.Class<DeleteDatasetGroupRequest>("DeleteDatasetGroupRequest")({DatasetGroupArn: S.String}) {}
export class DeleteDatasetImportJobRequest extends S.Class<DeleteDatasetImportJobRequest>("DeleteDatasetImportJobRequest")({DatasetImportJobArn: S.String}) {}
export class DeleteExplainabilityRequest extends S.Class<DeleteExplainabilityRequest>("DeleteExplainabilityRequest")({ExplainabilityArn: S.String}) {}
export class DeleteExplainabilityExportRequest extends S.Class<DeleteExplainabilityExportRequest>("DeleteExplainabilityExportRequest")({ExplainabilityExportArn: S.String}) {}
export class DeleteForecastRequest extends S.Class<DeleteForecastRequest>("DeleteForecastRequest")({ForecastArn: S.String}) {}
export class DeleteForecastExportJobRequest extends S.Class<DeleteForecastExportJobRequest>("DeleteForecastExportJobRequest")({ForecastExportJobArn: S.String}) {}
export class DeleteMonitorRequest extends S.Class<DeleteMonitorRequest>("DeleteMonitorRequest")({MonitorArn: S.String}) {}
export class DeletePredictorRequest extends S.Class<DeletePredictorRequest>("DeletePredictorRequest")({PredictorArn: S.String}) {}
export class DeletePredictorBacktestExportJobRequest extends S.Class<DeletePredictorBacktestExportJobRequest>("DeletePredictorBacktestExportJobRequest")({PredictorBacktestExportJobArn: S.String}) {}
export class DeleteResourceTreeRequest extends S.Class<DeleteResourceTreeRequest>("DeleteResourceTreeRequest")({ResourceArn: S.String}) {}
export class DeleteWhatIfAnalysisRequest extends S.Class<DeleteWhatIfAnalysisRequest>("DeleteWhatIfAnalysisRequest")({WhatIfAnalysisArn: S.String}) {}
export class DeleteWhatIfForecastRequest extends S.Class<DeleteWhatIfForecastRequest>("DeleteWhatIfForecastRequest")({WhatIfForecastArn: S.String}) {}
export class DeleteWhatIfForecastExportRequest extends S.Class<DeleteWhatIfForecastExportRequest>("DeleteWhatIfForecastExportRequest")({WhatIfForecastExportArn: S.String}) {}
export class DescribeAutoPredictorRequest extends S.Class<DescribeAutoPredictorRequest>("DescribeAutoPredictorRequest")({PredictorArn: S.String}) {}
export class DescribeDatasetRequest extends S.Class<DescribeDatasetRequest>("DescribeDatasetRequest")({DatasetArn: S.String}) {}
export class DescribeDatasetGroupRequest extends S.Class<DescribeDatasetGroupRequest>("DescribeDatasetGroupRequest")({DatasetGroupArn: S.String}) {}
export class DescribeDatasetImportJobRequest extends S.Class<DescribeDatasetImportJobRequest>("DescribeDatasetImportJobRequest")({DatasetImportJobArn: S.String}) {}
export class DescribeExplainabilityRequest extends S.Class<DescribeExplainabilityRequest>("DescribeExplainabilityRequest")({ExplainabilityArn: S.String}) {}
export class DescribeExplainabilityExportRequest extends S.Class<DescribeExplainabilityExportRequest>("DescribeExplainabilityExportRequest")({ExplainabilityExportArn: S.String}) {}
export class DescribeForecastRequest extends S.Class<DescribeForecastRequest>("DescribeForecastRequest")({ForecastArn: S.String}) {}
export class DescribeForecastExportJobRequest extends S.Class<DescribeForecastExportJobRequest>("DescribeForecastExportJobRequest")({ForecastExportJobArn: S.String}) {}
export class DescribeMonitorRequest extends S.Class<DescribeMonitorRequest>("DescribeMonitorRequest")({MonitorArn: S.String}) {}
export class DescribePredictorRequest extends S.Class<DescribePredictorRequest>("DescribePredictorRequest")({PredictorArn: S.String}) {}
export class DescribePredictorBacktestExportJobRequest extends S.Class<DescribePredictorBacktestExportJobRequest>("DescribePredictorBacktestExportJobRequest")({PredictorBacktestExportJobArn: S.String}) {}
export class DescribeWhatIfAnalysisRequest extends S.Class<DescribeWhatIfAnalysisRequest>("DescribeWhatIfAnalysisRequest")({WhatIfAnalysisArn: S.String}) {}
export class DescribeWhatIfForecastRequest extends S.Class<DescribeWhatIfForecastRequest>("DescribeWhatIfForecastRequest")({WhatIfForecastArn: S.String}) {}
export class DescribeWhatIfForecastExportRequest extends S.Class<DescribeWhatIfForecastExportRequest>("DescribeWhatIfForecastExportRequest")({WhatIfForecastExportArn: S.String}) {}
export class GetAccuracyMetricsRequest extends S.Class<GetAccuracyMetricsRequest>("GetAccuracyMetricsRequest")({PredictorArn: S.String}) {}
export class ListDatasetGroupsRequest extends S.Class<ListDatasetGroupsRequest>("ListDatasetGroupsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListDatasetsRequest extends S.Class<ListDatasetsRequest>("ListDatasetsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class Filter extends S.Class<Filter>("Filter")({Key: S.String, Value: S.String, Condition: S.String}) {}
export const Filters = S.Array(Filter);
export class ListExplainabilitiesRequest extends S.Class<ListExplainabilitiesRequest>("ListExplainabilitiesRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ListExplainabilityExportsRequest extends S.Class<ListExplainabilityExportsRequest>("ListExplainabilityExportsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ListForecastExportJobsRequest extends S.Class<ListForecastExportJobsRequest>("ListForecastExportJobsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ListForecastsRequest extends S.Class<ListForecastsRequest>("ListForecastsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ListMonitorEvaluationsRequest extends S.Class<ListMonitorEvaluationsRequest>("ListMonitorEvaluationsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), MonitorArn: S.String, Filters: S.optional(Filters)}) {}
export class ListMonitorsRequest extends S.Class<ListMonitorsRequest>("ListMonitorsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ListPredictorBacktestExportJobsRequest extends S.Class<ListPredictorBacktestExportJobsRequest>("ListPredictorBacktestExportJobsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ListPredictorsRequest extends S.Class<ListPredictorsRequest>("ListPredictorsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceArn: S.String}) {}
export class ListWhatIfAnalysesRequest extends S.Class<ListWhatIfAnalysesRequest>("ListWhatIfAnalysesRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ListWhatIfForecastExportsRequest extends S.Class<ListWhatIfForecastExportsRequest>("ListWhatIfForecastExportsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ListWhatIfForecastsRequest extends S.Class<ListWhatIfForecastsRequest>("ListWhatIfForecastsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ResumeResourceRequest extends S.Class<ResumeResourceRequest>("ResumeResourceRequest")({ResourceArn: S.String}) {}
export class StopResourceRequest extends S.Class<StopResourceRequest>("StopResourceRequest")({ResourceArn: S.String}) {}
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceArn: S.String, Tags: Tags}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceArn: S.String, TagKeys: TagKeys}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class UpdateDatasetGroupRequest extends S.Class<UpdateDatasetGroupRequest>("UpdateDatasetGroupRequest")({DatasetGroupArn: S.String, DatasetArns: ArnList}) {}
export class UpdateDatasetGroupResponse extends S.Class<UpdateDatasetGroupResponse>("UpdateDatasetGroupResponse")({}) {}
export class EncryptionConfig extends S.Class<EncryptionConfig>("EncryptionConfig")({RoleArn: S.String, KMSKeyArn: S.String}) {}
export class MonitorConfig extends S.Class<MonitorConfig>("MonitorConfig")({MonitorName: S.String}) {}
export class TimeAlignmentBoundary extends S.Class<TimeAlignmentBoundary>("TimeAlignmentBoundary")({Month: S.optional(S.String), DayOfMonth: S.optional(S.Number), DayOfWeek: S.optional(S.String), Hour: S.optional(S.Number)}) {}
export class ExplainabilityConfig extends S.Class<ExplainabilityConfig>("ExplainabilityConfig")({TimeSeriesGranularity: S.String, TimePointGranularity: S.String}) {}
export const TrainingParameters = S.Record({key: S.String, value: S.String});
export class EvaluationParameters extends S.Class<EvaluationParameters>("EvaluationParameters")({NumberOfBacktestWindows: S.optional(S.Number), BackTestWindowOffset: S.optional(S.Number)}) {}
export class TimeSeriesReplacementsDataSource extends S.Class<TimeSeriesReplacementsDataSource>("TimeSeriesReplacementsDataSource")({S3Config: S3Config, Schema: Schema, Format: S.optional(S.String), TimestampFormat: S.optional(S.String)}) {}
export const LongArnList = S.Array(S.String);
export class CreateDatasetGroupResponse extends S.Class<CreateDatasetGroupResponse>("CreateDatasetGroupResponse")({DatasetGroupArn: S.optional(S.String)}) {}
export class CreateExplainabilityRequest extends S.Class<CreateExplainabilityRequest>("CreateExplainabilityRequest")({ExplainabilityName: S.String, ResourceArn: S.String, ExplainabilityConfig: ExplainabilityConfig, DataSource: S.optional(DataSource), Schema: S.optional(Schema), EnableVisualization: S.optional(S.Boolean), StartDateTime: S.optional(S.String), EndDateTime: S.optional(S.String), Tags: S.optional(Tags)}) {}
export class CreateExplainabilityExportRequest extends S.Class<CreateExplainabilityExportRequest>("CreateExplainabilityExportRequest")({ExplainabilityExportName: S.String, ExplainabilityArn: S.String, Destination: DataDestination, Tags: S.optional(Tags), Format: S.optional(S.String)}) {}
export class CreateForecastExportJobResponse extends S.Class<CreateForecastExportJobResponse>("CreateForecastExportJobResponse")({ForecastExportJobArn: S.optional(S.String)}) {}
export class CreateMonitorResponse extends S.Class<CreateMonitorResponse>("CreateMonitorResponse")({MonitorArn: S.optional(S.String)}) {}
export class CreatePredictorBacktestExportJobResponse extends S.Class<CreatePredictorBacktestExportJobResponse>("CreatePredictorBacktestExportJobResponse")({PredictorBacktestExportJobArn: S.optional(S.String)}) {}
export class CreateWhatIfAnalysisResponse extends S.Class<CreateWhatIfAnalysisResponse>("CreateWhatIfAnalysisResponse")({WhatIfAnalysisArn: S.optional(S.String)}) {}
export class CreateWhatIfForecastExportResponse extends S.Class<CreateWhatIfForecastExportResponse>("CreateWhatIfForecastExportResponse")({WhatIfForecastExportArn: S.optional(S.String)}) {}
export class DescribeDatasetResponse extends S.Class<DescribeDatasetResponse>("DescribeDatasetResponse")({DatasetArn: S.optional(S.String), DatasetName: S.optional(S.String), Domain: S.optional(S.String), DatasetType: S.optional(S.String), DataFrequency: S.optional(S.String), Schema: S.optional(Schema), EncryptionConfig: S.optional(EncryptionConfig), Status: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export class DescribeDatasetGroupResponse extends S.Class<DescribeDatasetGroupResponse>("DescribeDatasetGroupResponse")({DatasetGroupName: S.optional(S.String), DatasetGroupArn: S.optional(S.String), DatasetArns: S.optional(ArnList), Domain: S.optional(S.String), Status: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export class DescribeExplainabilityResponse extends S.Class<DescribeExplainabilityResponse>("DescribeExplainabilityResponse")({ExplainabilityArn: S.optional(S.String), ExplainabilityName: S.optional(S.String), ResourceArn: S.optional(S.String), ExplainabilityConfig: S.optional(ExplainabilityConfig), EnableVisualization: S.optional(S.Boolean), DataSource: S.optional(DataSource), Schema: S.optional(Schema), StartDateTime: S.optional(S.String), EndDateTime: S.optional(S.String), EstimatedTimeRemainingInMinutes: S.optional(S.Number), Message: S.optional(S.String), Status: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export class DescribeExplainabilityExportResponse extends S.Class<DescribeExplainabilityExportResponse>("DescribeExplainabilityExportResponse")({ExplainabilityExportArn: S.optional(S.String), ExplainabilityExportName: S.optional(S.String), ExplainabilityArn: S.optional(S.String), Destination: S.optional(DataDestination), Message: S.optional(S.String), Status: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), Format: S.optional(S.String)}) {}
export class DescribeForecastResponse extends S.Class<DescribeForecastResponse>("DescribeForecastResponse")({ForecastArn: S.optional(S.String), ForecastName: S.optional(S.String), ForecastTypes: S.optional(ForecastTypes), PredictorArn: S.optional(S.String), DatasetGroupArn: S.optional(S.String), EstimatedTimeRemainingInMinutes: S.optional(S.Number), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), TimeSeriesSelector: S.optional(TimeSeriesSelector)}) {}
export class DescribeForecastExportJobResponse extends S.Class<DescribeForecastExportJobResponse>("DescribeForecastExportJobResponse")({ForecastExportJobArn: S.optional(S.String), ForecastExportJobName: S.optional(S.String), ForecastArn: S.optional(S.String), Destination: S.optional(DataDestination), Message: S.optional(S.String), Status: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), Format: S.optional(S.String)}) {}
export class DescribePredictorBacktestExportJobResponse extends S.Class<DescribePredictorBacktestExportJobResponse>("DescribePredictorBacktestExportJobResponse")({PredictorBacktestExportJobArn: S.optional(S.String), PredictorBacktestExportJobName: S.optional(S.String), PredictorArn: S.optional(S.String), Destination: S.optional(DataDestination), Message: S.optional(S.String), Status: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), Format: S.optional(S.String)}) {}
export class DescribeWhatIfAnalysisResponse extends S.Class<DescribeWhatIfAnalysisResponse>("DescribeWhatIfAnalysisResponse")({WhatIfAnalysisName: S.optional(S.String), WhatIfAnalysisArn: S.optional(S.String), ForecastArn: S.optional(S.String), EstimatedTimeRemainingInMinutes: S.optional(S.Number), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), TimeSeriesSelector: S.optional(TimeSeriesSelector)}) {}
export class Action extends S.Class<Action>("Action")({AttributeName: S.String, Operation: S.String, Value: S.Number}) {}
export class TimeSeriesCondition extends S.Class<TimeSeriesCondition>("TimeSeriesCondition")({AttributeName: S.String, AttributeValue: S.String, Condition: S.String}) {}
export const TimeSeriesConditions = S.Array(TimeSeriesCondition);
export class TimeSeriesTransformation extends S.Class<TimeSeriesTransformation>("TimeSeriesTransformation")({Action: S.optional(Action), TimeSeriesConditions: S.optional(TimeSeriesConditions)}) {}
export const TimeSeriesTransformations = S.Array(TimeSeriesTransformation);
export class DescribeWhatIfForecastResponse extends S.Class<DescribeWhatIfForecastResponse>("DescribeWhatIfForecastResponse")({WhatIfForecastName: S.optional(S.String), WhatIfForecastArn: S.optional(S.String), WhatIfAnalysisArn: S.optional(S.String), EstimatedTimeRemainingInMinutes: S.optional(S.Number), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), TimeSeriesTransformations: S.optional(TimeSeriesTransformations), TimeSeriesReplacementsDataSource: S.optional(TimeSeriesReplacementsDataSource), ForecastTypes: S.optional(ForecastTypes)}) {}
export class DescribeWhatIfForecastExportResponse extends S.Class<DescribeWhatIfForecastExportResponse>("DescribeWhatIfForecastExportResponse")({WhatIfForecastExportArn: S.optional(S.String), WhatIfForecastExportName: S.optional(S.String), WhatIfForecastArns: S.optional(LongArnList), Destination: S.optional(DataDestination), Message: S.optional(S.String), Status: S.optional(S.String), CreationTime: S.optional(S.Date), EstimatedTimeRemainingInMinutes: S.optional(S.Number), LastModificationTime: S.optional(S.Date), Format: S.optional(S.String)}) {}
export class ListDatasetImportJobsRequest extends S.Class<ListDatasetImportJobsRequest>("ListDatasetImportJobsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: S.optional(Tags)}) {}
export class SupplementaryFeature extends S.Class<SupplementaryFeature>("SupplementaryFeature")({Name: S.String, Value: S.String}) {}
export const SupplementaryFeatures = S.Array(SupplementaryFeature);
export const Values = S.Array(S.String);
export class InputDataConfig extends S.Class<InputDataConfig>("InputDataConfig")({DatasetGroupArn: S.String, SupplementaryFeatures: S.optional(SupplementaryFeatures)}) {}
export class ReferencePredictorSummary extends S.Class<ReferencePredictorSummary>("ReferencePredictorSummary")({Arn: S.optional(S.String), State: S.optional(S.String)}) {}
export class ExplainabilityInfo extends S.Class<ExplainabilityInfo>("ExplainabilityInfo")({ExplainabilityArn: S.optional(S.String), Status: S.optional(S.String)}) {}
export class MonitorInfo extends S.Class<MonitorInfo>("MonitorInfo")({MonitorArn: S.optional(S.String), Status: S.optional(S.String)}) {}
export class DatasetGroupSummary extends S.Class<DatasetGroupSummary>("DatasetGroupSummary")({DatasetGroupArn: S.optional(S.String), DatasetGroupName: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const DatasetGroups = S.Array(DatasetGroupSummary);
export class DatasetSummary extends S.Class<DatasetSummary>("DatasetSummary")({DatasetArn: S.optional(S.String), DatasetName: S.optional(S.String), DatasetType: S.optional(S.String), Domain: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const Datasets = S.Array(DatasetSummary);
export class ExplainabilitySummary extends S.Class<ExplainabilitySummary>("ExplainabilitySummary")({ExplainabilityArn: S.optional(S.String), ExplainabilityName: S.optional(S.String), ResourceArn: S.optional(S.String), ExplainabilityConfig: S.optional(ExplainabilityConfig), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const Explainabilities = S.Array(ExplainabilitySummary);
export class ExplainabilityExportSummary extends S.Class<ExplainabilityExportSummary>("ExplainabilityExportSummary")({ExplainabilityExportArn: S.optional(S.String), ExplainabilityExportName: S.optional(S.String), Destination: S.optional(DataDestination), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const ExplainabilityExports = S.Array(ExplainabilityExportSummary);
export class ForecastExportJobSummary extends S.Class<ForecastExportJobSummary>("ForecastExportJobSummary")({ForecastExportJobArn: S.optional(S.String), ForecastExportJobName: S.optional(S.String), Destination: S.optional(DataDestination), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const ForecastExportJobs = S.Array(ForecastExportJobSummary);
export class ForecastSummary extends S.Class<ForecastSummary>("ForecastSummary")({ForecastArn: S.optional(S.String), ForecastName: S.optional(S.String), PredictorArn: S.optional(S.String), CreatedUsingAutoPredictor: S.optional(S.Boolean), DatasetGroupArn: S.optional(S.String), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const Forecasts = S.Array(ForecastSummary);
export class MonitorSummary extends S.Class<MonitorSummary>("MonitorSummary")({MonitorArn: S.optional(S.String), MonitorName: S.optional(S.String), ResourceArn: S.optional(S.String), Status: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const Monitors = S.Array(MonitorSummary);
export class PredictorBacktestExportJobSummary extends S.Class<PredictorBacktestExportJobSummary>("PredictorBacktestExportJobSummary")({PredictorBacktestExportJobArn: S.optional(S.String), PredictorBacktestExportJobName: S.optional(S.String), Destination: S.optional(DataDestination), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const PredictorBacktestExportJobs = S.Array(PredictorBacktestExportJobSummary);
export class PredictorSummary extends S.Class<PredictorSummary>("PredictorSummary")({PredictorArn: S.optional(S.String), PredictorName: S.optional(S.String), DatasetGroupArn: S.optional(S.String), IsAutoPredictor: S.optional(S.Boolean), ReferencePredictorSummary: S.optional(ReferencePredictorSummary), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const Predictors = S.Array(PredictorSummary);
export class WhatIfAnalysisSummary extends S.Class<WhatIfAnalysisSummary>("WhatIfAnalysisSummary")({WhatIfAnalysisArn: S.optional(S.String), WhatIfAnalysisName: S.optional(S.String), ForecastArn: S.optional(S.String), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const WhatIfAnalyses = S.Array(WhatIfAnalysisSummary);
export class WhatIfForecastExportSummary extends S.Class<WhatIfForecastExportSummary>("WhatIfForecastExportSummary")({WhatIfForecastExportArn: S.optional(S.String), WhatIfForecastArns: S.optional(WhatIfForecastArnListForExport), WhatIfForecastExportName: S.optional(S.String), Destination: S.optional(DataDestination), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const WhatIfForecastExports = S.Array(WhatIfForecastExportSummary);
export class WhatIfForecastSummary extends S.Class<WhatIfForecastSummary>("WhatIfForecastSummary")({WhatIfForecastArn: S.optional(S.String), WhatIfForecastName: S.optional(S.String), WhatIfAnalysisArn: S.optional(S.String), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date)}) {}
export const WhatIfForecasts = S.Array(WhatIfForecastSummary);
export const Transformations = S.Record({key: S.String, value: S.String});
export const Configuration = S.Record({key: S.String, value: Values});
export class CategoricalParameterRange extends S.Class<CategoricalParameterRange>("CategoricalParameterRange")({Name: S.String, Values: Values}) {}
export const CategoricalParameterRanges = S.Array(CategoricalParameterRange);
export class ContinuousParameterRange extends S.Class<ContinuousParameterRange>("ContinuousParameterRange")({Name: S.String, MaxValue: S.Number, MinValue: S.Number, ScalingType: S.optional(S.String)}) {}
export const ContinuousParameterRanges = S.Array(ContinuousParameterRange);
export class IntegerParameterRange extends S.Class<IntegerParameterRange>("IntegerParameterRange")({Name: S.String, MaxValue: S.Number, MinValue: S.Number, ScalingType: S.optional(S.String)}) {}
export const IntegerParameterRanges = S.Array(IntegerParameterRange);
export class CreateDatasetRequest extends S.Class<CreateDatasetRequest>("CreateDatasetRequest")({DatasetName: S.String, Domain: S.String, DatasetType: S.String, DataFrequency: S.optional(S.String), Schema: Schema, EncryptionConfig: S.optional(EncryptionConfig), Tags: S.optional(Tags)}) {}
export class CreateDatasetImportJobRequest extends S.Class<CreateDatasetImportJobRequest>("CreateDatasetImportJobRequest")({DatasetImportJobName: S.String, DatasetArn: S.String, DataSource: DataSource, TimestampFormat: S.optional(S.String), TimeZone: S.optional(S.String), UseGeolocationForTimeZone: S.optional(S.Boolean), GeolocationFormat: S.optional(S.String), Tags: S.optional(Tags), Format: S.optional(S.String), ImportMode: S.optional(S.String)}) {}
export class CreateExplainabilityResponse extends S.Class<CreateExplainabilityResponse>("CreateExplainabilityResponse")({ExplainabilityArn: S.optional(S.String)}) {}
export class CreateExplainabilityExportResponse extends S.Class<CreateExplainabilityExportResponse>("CreateExplainabilityExportResponse")({ExplainabilityExportArn: S.optional(S.String)}) {}
export class CreateForecastRequest extends S.Class<CreateForecastRequest>("CreateForecastRequest")({ForecastName: S.String, PredictorArn: S.String, ForecastTypes: S.optional(ForecastTypes), Tags: S.optional(Tags), TimeSeriesSelector: S.optional(TimeSeriesSelector)}) {}
export class CreateWhatIfForecastRequest extends S.Class<CreateWhatIfForecastRequest>("CreateWhatIfForecastRequest")({WhatIfForecastName: S.String, WhatIfAnalysisArn: S.String, TimeSeriesTransformations: S.optional(TimeSeriesTransformations), TimeSeriesReplacementsDataSource: S.optional(TimeSeriesReplacementsDataSource), Tags: S.optional(Tags)}) {}
export class AttributeConfig extends S.Class<AttributeConfig>("AttributeConfig")({AttributeName: S.String, Transformations: Transformations}) {}
export const AttributeConfigs = S.Array(AttributeConfig);
export class AdditionalDataset extends S.Class<AdditionalDataset>("AdditionalDataset")({Name: S.String, Configuration: S.optional(Configuration)}) {}
export const AdditionalDatasets = S.Array(AdditionalDataset);
export class DataConfig extends S.Class<DataConfig>("DataConfig")({DatasetGroupArn: S.String, AttributeConfigs: S.optional(AttributeConfigs), AdditionalDatasets: S.optional(AdditionalDatasets)}) {}
export class DescribeAutoPredictorResponse extends S.Class<DescribeAutoPredictorResponse>("DescribeAutoPredictorResponse")({PredictorArn: S.optional(S.String), PredictorName: S.optional(S.String), ForecastHorizon: S.optional(S.Number), ForecastTypes: S.optional(ForecastTypes), ForecastFrequency: S.optional(S.String), ForecastDimensions: S.optional(ForecastDimensions), DatasetImportJobArns: S.optional(ArnList), DataConfig: S.optional(DataConfig), EncryptionConfig: S.optional(EncryptionConfig), ReferencePredictorSummary: S.optional(ReferencePredictorSummary), EstimatedTimeRemainingInMinutes: S.optional(S.Number), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), OptimizationMetric: S.optional(S.String), ExplainabilityInfo: S.optional(ExplainabilityInfo), MonitorInfo: S.optional(MonitorInfo), TimeAlignmentBoundary: S.optional(TimeAlignmentBoundary)}) {}
export class ListDatasetGroupsResponse extends S.Class<ListDatasetGroupsResponse>("ListDatasetGroupsResponse")({DatasetGroups: S.optional(DatasetGroups), NextToken: S.optional(S.String)}) {}
export class ListDatasetsResponse extends S.Class<ListDatasetsResponse>("ListDatasetsResponse")({Datasets: S.optional(Datasets), NextToken: S.optional(S.String)}) {}
export class ListExplainabilitiesResponse extends S.Class<ListExplainabilitiesResponse>("ListExplainabilitiesResponse")({Explainabilities: S.optional(Explainabilities), NextToken: S.optional(S.String)}) {}
export class ListExplainabilityExportsResponse extends S.Class<ListExplainabilityExportsResponse>("ListExplainabilityExportsResponse")({ExplainabilityExports: S.optional(ExplainabilityExports), NextToken: S.optional(S.String)}) {}
export class ListForecastExportJobsResponse extends S.Class<ListForecastExportJobsResponse>("ListForecastExportJobsResponse")({ForecastExportJobs: S.optional(ForecastExportJobs), NextToken: S.optional(S.String)}) {}
export class ListForecastsResponse extends S.Class<ListForecastsResponse>("ListForecastsResponse")({Forecasts: S.optional(Forecasts), NextToken: S.optional(S.String)}) {}
export class ListMonitorsResponse extends S.Class<ListMonitorsResponse>("ListMonitorsResponse")({Monitors: S.optional(Monitors), NextToken: S.optional(S.String)}) {}
export class ListPredictorBacktestExportJobsResponse extends S.Class<ListPredictorBacktestExportJobsResponse>("ListPredictorBacktestExportJobsResponse")({PredictorBacktestExportJobs: S.optional(PredictorBacktestExportJobs), NextToken: S.optional(S.String)}) {}
export class ListPredictorsResponse extends S.Class<ListPredictorsResponse>("ListPredictorsResponse")({Predictors: S.optional(Predictors), NextToken: S.optional(S.String)}) {}
export class ListWhatIfAnalysesResponse extends S.Class<ListWhatIfAnalysesResponse>("ListWhatIfAnalysesResponse")({WhatIfAnalyses: S.optional(WhatIfAnalyses), NextToken: S.optional(S.String)}) {}
export class ListWhatIfForecastExportsResponse extends S.Class<ListWhatIfForecastExportsResponse>("ListWhatIfForecastExportsResponse")({WhatIfForecastExports: S.optional(WhatIfForecastExports), NextToken: S.optional(S.String)}) {}
export class ListWhatIfForecastsResponse extends S.Class<ListWhatIfForecastsResponse>("ListWhatIfForecastsResponse")({WhatIfForecasts: S.optional(WhatIfForecasts), NextToken: S.optional(S.String)}) {}
export class ParameterRanges extends S.Class<ParameterRanges>("ParameterRanges")({CategoricalParameterRanges: S.optional(CategoricalParameterRanges), ContinuousParameterRanges: S.optional(ContinuousParameterRanges), IntegerParameterRanges: S.optional(IntegerParameterRanges)}) {}
export class Statistics extends S.Class<Statistics>("Statistics")({Count: S.optional(S.Number), CountDistinct: S.optional(S.Number), CountNull: S.optional(S.Number), CountNan: S.optional(S.Number), Min: S.optional(S.String), Max: S.optional(S.String), Avg: S.optional(S.Number), Stddev: S.optional(S.Number), CountLong: S.optional(S.Number), CountDistinctLong: S.optional(S.Number), CountNullLong: S.optional(S.Number), CountNanLong: S.optional(S.Number)}) {}
export class PredictorEvent extends S.Class<PredictorEvent>("PredictorEvent")({Detail: S.optional(S.String), Datetime: S.optional(S.Date)}) {}
export class MonitorDataSource extends S.Class<MonitorDataSource>("MonitorDataSource")({DatasetImportJobArn: S.optional(S.String), ForecastArn: S.optional(S.String), PredictorArn: S.optional(S.String)}) {}
export class MetricResult extends S.Class<MetricResult>("MetricResult")({MetricName: S.optional(S.String), MetricValue: S.optional(S.Number)}) {}
export const MetricResults = S.Array(MetricResult);
export const FeaturizationMethodParameters = S.Record({key: S.String, value: S.String});
export class HyperParameterTuningJobConfig extends S.Class<HyperParameterTuningJobConfig>("HyperParameterTuningJobConfig")({ParameterRanges: S.optional(ParameterRanges)}) {}
export const FieldStatistics = S.Record({key: S.String, value: Statistics});
export class DatasetImportJobSummary extends S.Class<DatasetImportJobSummary>("DatasetImportJobSummary")({DatasetImportJobArn: S.optional(S.String), DatasetImportJobName: S.optional(S.String), DataSource: S.optional(DataSource), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), ImportMode: S.optional(S.String)}) {}
export const DatasetImportJobs = S.Array(DatasetImportJobSummary);
export class PredictorMonitorEvaluation extends S.Class<PredictorMonitorEvaluation>("PredictorMonitorEvaluation")({ResourceArn: S.optional(S.String), MonitorArn: S.optional(S.String), EvaluationTime: S.optional(S.Date), EvaluationState: S.optional(S.String), WindowStartDatetime: S.optional(S.Date), WindowEndDatetime: S.optional(S.Date), PredictorEvent: S.optional(PredictorEvent), MonitorDataSource: S.optional(MonitorDataSource), MetricResults: S.optional(MetricResults), NumItemsEvaluated: S.optional(S.Number), Message: S.optional(S.String)}) {}
export const PredictorMonitorEvaluations = S.Array(PredictorMonitorEvaluation);
export class FeaturizationMethod extends S.Class<FeaturizationMethod>("FeaturizationMethod")({FeaturizationMethodName: S.String, FeaturizationMethodParameters: S.optional(FeaturizationMethodParameters)}) {}
export const FeaturizationPipeline = S.Array(FeaturizationMethod);
export class BaselineMetric extends S.Class<BaselineMetric>("BaselineMetric")({Name: S.optional(S.String), Value: S.optional(S.Number)}) {}
export const BaselineMetrics = S.Array(BaselineMetric);
export class TestWindowSummary extends S.Class<TestWindowSummary>("TestWindowSummary")({TestWindowStart: S.optional(S.Date), TestWindowEnd: S.optional(S.Date), Status: S.optional(S.String), Message: S.optional(S.String)}) {}
export const TestWindowDetails = S.Array(TestWindowSummary);
export class CreateAutoPredictorRequest extends S.Class<CreateAutoPredictorRequest>("CreateAutoPredictorRequest")({PredictorName: S.String, ForecastHorizon: S.optional(S.Number), ForecastTypes: S.optional(ForecastTypes), ForecastDimensions: S.optional(ForecastDimensions), ForecastFrequency: S.optional(S.String), DataConfig: S.optional(DataConfig), EncryptionConfig: S.optional(EncryptionConfig), ReferencePredictorArn: S.optional(S.String), OptimizationMetric: S.optional(S.String), ExplainPredictor: S.optional(S.Boolean), Tags: S.optional(Tags), MonitorConfig: S.optional(MonitorConfig), TimeAlignmentBoundary: S.optional(TimeAlignmentBoundary)}) {}
export class CreateDatasetResponse extends S.Class<CreateDatasetResponse>("CreateDatasetResponse")({DatasetArn: S.optional(S.String)}) {}
export class CreateDatasetImportJobResponse extends S.Class<CreateDatasetImportJobResponse>("CreateDatasetImportJobResponse")({DatasetImportJobArn: S.optional(S.String)}) {}
export class CreateForecastResponse extends S.Class<CreateForecastResponse>("CreateForecastResponse")({ForecastArn: S.optional(S.String)}) {}
export class CreateWhatIfForecastResponse extends S.Class<CreateWhatIfForecastResponse>("CreateWhatIfForecastResponse")({WhatIfForecastArn: S.optional(S.String)}) {}
export class DescribeDatasetImportJobResponse extends S.Class<DescribeDatasetImportJobResponse>("DescribeDatasetImportJobResponse")({DatasetImportJobName: S.optional(S.String), DatasetImportJobArn: S.optional(S.String), DatasetArn: S.optional(S.String), TimestampFormat: S.optional(S.String), TimeZone: S.optional(S.String), UseGeolocationForTimeZone: S.optional(S.Boolean), GeolocationFormat: S.optional(S.String), DataSource: S.optional(DataSource), EstimatedTimeRemainingInMinutes: S.optional(S.Number), FieldStatistics: S.optional(FieldStatistics), DataSize: S.optional(S.Number), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), Format: S.optional(S.String), ImportMode: S.optional(S.String)}) {}
export class ListDatasetImportJobsResponse extends S.Class<ListDatasetImportJobsResponse>("ListDatasetImportJobsResponse")({DatasetImportJobs: S.optional(DatasetImportJobs), NextToken: S.optional(S.String)}) {}
export class ListMonitorEvaluationsResponse extends S.Class<ListMonitorEvaluationsResponse>("ListMonitorEvaluationsResponse")({NextToken: S.optional(S.String), PredictorMonitorEvaluations: S.optional(PredictorMonitorEvaluations)}) {}
export class Featurization extends S.Class<Featurization>("Featurization")({AttributeName: S.String, FeaturizationPipeline: S.optional(FeaturizationPipeline)}) {}
export const Featurizations = S.Array(Featurization);
export class PredictorBaseline extends S.Class<PredictorBaseline>("PredictorBaseline")({BaselineMetrics: S.optional(BaselineMetrics)}) {}
export class PredictorExecution extends S.Class<PredictorExecution>("PredictorExecution")({AlgorithmArn: S.optional(S.String), TestWindows: S.optional(TestWindowDetails)}) {}
export const PredictorExecutions = S.Array(PredictorExecution);
export class WeightedQuantileLoss extends S.Class<WeightedQuantileLoss>("WeightedQuantileLoss")({Quantile: S.optional(S.Number), LossValue: S.optional(S.Number)}) {}
export const WeightedQuantileLosses = S.Array(WeightedQuantileLoss);
export class ErrorMetric extends S.Class<ErrorMetric>("ErrorMetric")({ForecastType: S.optional(S.String), WAPE: S.optional(S.Number), RMSE: S.optional(S.Number), MASE: S.optional(S.Number), MAPE: S.optional(S.Number)}) {}
export const ErrorMetrics = S.Array(ErrorMetric);
export class FeaturizationConfig extends S.Class<FeaturizationConfig>("FeaturizationConfig")({ForecastFrequency: S.String, ForecastDimensions: S.optional(ForecastDimensions), Featurizations: S.optional(Featurizations)}) {}
export class Baseline extends S.Class<Baseline>("Baseline")({PredictorBaseline: S.optional(PredictorBaseline)}) {}
export class PredictorExecutionDetails extends S.Class<PredictorExecutionDetails>("PredictorExecutionDetails")({PredictorExecutions: S.optional(PredictorExecutions)}) {}
export class Metrics extends S.Class<Metrics>("Metrics")({RMSE: S.optional(S.Number), WeightedQuantileLosses: S.optional(WeightedQuantileLosses), ErrorMetrics: S.optional(ErrorMetrics), AverageWeightedQuantileLoss: S.optional(S.Number)}) {}
export class CreateAutoPredictorResponse extends S.Class<CreateAutoPredictorResponse>("CreateAutoPredictorResponse")({PredictorArn: S.optional(S.String)}) {}
export class CreatePredictorRequest extends S.Class<CreatePredictorRequest>("CreatePredictorRequest")({PredictorName: S.String, AlgorithmArn: S.optional(S.String), ForecastHorizon: S.Number, ForecastTypes: S.optional(ForecastTypes), PerformAutoML: S.optional(S.Boolean), AutoMLOverrideStrategy: S.optional(S.String), PerformHPO: S.optional(S.Boolean), TrainingParameters: S.optional(TrainingParameters), EvaluationParameters: S.optional(EvaluationParameters), HPOConfig: S.optional(HyperParameterTuningJobConfig), InputDataConfig: InputDataConfig, FeaturizationConfig: FeaturizationConfig, EncryptionConfig: S.optional(EncryptionConfig), Tags: S.optional(Tags), OptimizationMetric: S.optional(S.String)}) {}
export class DescribeMonitorResponse extends S.Class<DescribeMonitorResponse>("DescribeMonitorResponse")({MonitorName: S.optional(S.String), MonitorArn: S.optional(S.String), ResourceArn: S.optional(S.String), Status: S.optional(S.String), LastEvaluationTime: S.optional(S.Date), LastEvaluationState: S.optional(S.String), Baseline: S.optional(Baseline), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), EstimatedEvaluationTimeRemainingInMinutes: S.optional(S.Number)}) {}
export class DescribePredictorResponse extends S.Class<DescribePredictorResponse>("DescribePredictorResponse")({PredictorArn: S.optional(S.String), PredictorName: S.optional(S.String), AlgorithmArn: S.optional(S.String), AutoMLAlgorithmArns: S.optional(ArnList), ForecastHorizon: S.optional(S.Number), ForecastTypes: S.optional(ForecastTypes), PerformAutoML: S.optional(S.Boolean), AutoMLOverrideStrategy: S.optional(S.String), PerformHPO: S.optional(S.Boolean), TrainingParameters: S.optional(TrainingParameters), EvaluationParameters: S.optional(EvaluationParameters), HPOConfig: S.optional(HyperParameterTuningJobConfig), InputDataConfig: S.optional(InputDataConfig), FeaturizationConfig: S.optional(FeaturizationConfig), EncryptionConfig: S.optional(EncryptionConfig), PredictorExecutionDetails: S.optional(PredictorExecutionDetails), EstimatedTimeRemainingInMinutes: S.optional(S.Number), IsAutoPredictor: S.optional(S.Boolean), DatasetImportJobArns: S.optional(ArnList), Status: S.optional(S.String), Message: S.optional(S.String), CreationTime: S.optional(S.Date), LastModificationTime: S.optional(S.Date), OptimizationMetric: S.optional(S.String)}) {}
export class WindowSummary extends S.Class<WindowSummary>("WindowSummary")({TestWindowStart: S.optional(S.Date), TestWindowEnd: S.optional(S.Date), ItemCount: S.optional(S.Number), EvaluationType: S.optional(S.String), Metrics: S.optional(Metrics)}) {}
export const TestWindows = S.Array(WindowSummary);
export class EvaluationResult extends S.Class<EvaluationResult>("EvaluationResult")({AlgorithmArn: S.optional(S.String), TestWindows: S.optional(TestWindows)}) {}
export const PredictorEvaluationResults = S.Array(EvaluationResult);
export class CreatePredictorResponse extends S.Class<CreatePredictorResponse>("CreatePredictorResponse")({PredictorArn: S.optional(S.String)}) {}
export class GetAccuracyMetricsResponse extends S.Class<GetAccuracyMetricsResponse>("GetAccuracyMetricsResponse")({PredictorEvaluationResults: S.optional(PredictorEvaluationResults), IsAutoPredictor: S.optional(S.Boolean), AutoMLOverrideStrategy: S.optional(S.String), OptimizationMetric: S.optional(S.String)}) {}

//# Errors
export class InvalidInputException extends S.TaggedError<InvalidInputException>()("InvalidInputException", {}) {};
export class ResourceInUseException extends S.TaggedError<ResourceInUseException>()("ResourceInUseException", {}) {};
export class ResourceNotFoundException extends S.TaggedError<ResourceNotFoundException>()("ResourceNotFoundException", {}) {};
export class LimitExceededException extends S.TaggedError<LimitExceededException>()("LimitExceededException", {}) {};
export class ResourceAlreadyExistsException extends S.TaggedError<ResourceAlreadyExistsException>()("ResourceAlreadyExistsException", {}) {};
export class InvalidNextTokenException extends S.TaggedError<InvalidNextTokenException>()("InvalidNextTokenException", {}) {};

//# Operations
export const deleteExplainability = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteExplainability" }, DeleteExplainabilityRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteExplainabilityExport = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteExplainabilityExport" }, DeleteExplainabilityExportRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteForecast = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteForecast" }, DeleteForecastRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteForecastExportJob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteForecastExportJob" }, DeleteForecastExportJobRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteMonitor = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteMonitor" }, DeleteMonitorRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deletePredictor = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeletePredictor" }, DeletePredictorRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deletePredictorBacktestExportJob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeletePredictorBacktestExportJob" }, DeletePredictorBacktestExportJobRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteResourceTree = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteResourceTree" }, DeleteResourceTreeRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteWhatIfAnalysis = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteWhatIfAnalysis" }, DeleteWhatIfAnalysisRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteWhatIfForecast = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteWhatIfForecast" }, DeleteWhatIfForecastRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteWhatIfForecastExport = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteWhatIfForecastExport" }, DeleteWhatIfForecastExportRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const stopResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.StopResource" }, StopResourceRequest, S.Struct({}), [InvalidInputException, LimitExceededException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.TagResource" }, TagResourceRequest, TagResourceResponse, [InvalidInputException, LimitExceededException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateDatasetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.UpdateDatasetGroup" }, UpdateDatasetGroupRequest, UpdateDatasetGroupResponse, [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createForecastExportJob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateForecastExportJob" }, CreateForecastExportJobRequest, CreateForecastExportJobResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createMonitor = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateMonitor" }, CreateMonitorRequest, CreateMonitorResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createPredictorBacktestExportJob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreatePredictorBacktestExportJob" }, CreatePredictorBacktestExportJobRequest, CreatePredictorBacktestExportJobResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createWhatIfAnalysis = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateWhatIfAnalysis" }, CreateWhatIfAnalysisRequest, CreateWhatIfAnalysisResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createWhatIfForecastExport = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateWhatIfForecastExport" }, CreateWhatIfForecastExportRequest, CreateWhatIfForecastExportResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteDataset = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteDataset" }, DeleteDatasetRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteDatasetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteDatasetGroup" }, DeleteDatasetGroupRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteDatasetImportJob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DeleteDatasetImportJob" }, DeleteDatasetImportJobRequest, S.Struct({}), [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeDataset = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeDataset" }, DescribeDatasetRequest, DescribeDatasetResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeDatasetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeDatasetGroup" }, DescribeDatasetGroupRequest, DescribeDatasetGroupResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeExplainability = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeExplainability" }, DescribeExplainabilityRequest, DescribeExplainabilityResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeExplainabilityExport = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeExplainabilityExport" }, DescribeExplainabilityExportRequest, DescribeExplainabilityExportResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeForecast = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeForecast" }, DescribeForecastRequest, DescribeForecastResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeForecastExportJob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeForecastExportJob" }, DescribeForecastExportJobRequest, DescribeForecastExportJobResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describePredictorBacktestExportJob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribePredictorBacktestExportJob" }, DescribePredictorBacktestExportJobRequest, DescribePredictorBacktestExportJobResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeWhatIfAnalysis = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeWhatIfAnalysis" }, DescribeWhatIfAnalysisRequest, DescribeWhatIfAnalysisResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeWhatIfForecast = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeWhatIfForecast" }, DescribeWhatIfForecastRequest, DescribeWhatIfForecastResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeWhatIfForecastExport = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeWhatIfForecastExport" }, DescribeWhatIfForecastExportRequest, DescribeWhatIfForecastExportResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const resumeResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ResumeResource" }, ResumeResourceRequest, S.Struct({}), [InvalidInputException, LimitExceededException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createDatasetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateDatasetGroup" }, CreateDatasetGroupRequest, CreateDatasetGroupResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createExplainability = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateExplainability" }, CreateExplainabilityRequest, CreateExplainabilityResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createExplainabilityExport = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateExplainabilityExport" }, CreateExplainabilityExportRequest, CreateExplainabilityExportResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAutoPredictor = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeAutoPredictor" }, DescribeAutoPredictorRequest, DescribeAutoPredictorResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listDatasets = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListDatasets" }, ListDatasetsRequest, ListDatasetsResponse, [InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listExplainabilities = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListExplainabilities" }, ListExplainabilitiesRequest, ListExplainabilitiesResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listExplainabilityExports = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListExplainabilityExports" }, ListExplainabilityExportsRequest, ListExplainabilityExportsResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listForecastExportJobs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListForecastExportJobs" }, ListForecastExportJobsRequest, ListForecastExportJobsResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listForecasts = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListForecasts" }, ListForecastsRequest, ListForecastsResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listMonitors = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListMonitors" }, ListMonitorsRequest, ListMonitorsResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listPredictorBacktestExportJobs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListPredictorBacktestExportJobs" }, ListPredictorBacktestExportJobsRequest, ListPredictorBacktestExportJobsResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listPredictors = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListPredictors" }, ListPredictorsRequest, ListPredictorsResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listWhatIfAnalyses = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListWhatIfAnalyses" }, ListWhatIfAnalysesRequest, ListWhatIfAnalysesResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listWhatIfForecastExports = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListWhatIfForecastExports" }, ListWhatIfForecastExportsRequest, ListWhatIfForecastExportsResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listWhatIfForecasts = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListWhatIfForecasts" }, ListWhatIfForecastsRequest, ListWhatIfForecastsResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createDataset = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateDataset" }, CreateDatasetRequest, CreateDatasetResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createDatasetImportJob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateDatasetImportJob" }, CreateDatasetImportJobRequest, CreateDatasetImportJobResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createForecast = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateForecast" }, CreateForecastRequest, CreateForecastResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createWhatIfForecast = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateWhatIfForecast" }, CreateWhatIfForecastRequest, CreateWhatIfForecastResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeDatasetImportJob = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeDatasetImportJob" }, DescribeDatasetImportJobRequest, DescribeDatasetImportJobResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listDatasetGroups = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListDatasetGroups" }, ListDatasetGroupsRequest, ListDatasetGroupsResponse, [InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listDatasetImportJobs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListDatasetImportJobs" }, ListDatasetImportJobsRequest, ListDatasetImportJobsResponse, [InvalidInputException, InvalidNextTokenException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listMonitorEvaluations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.ListMonitorEvaluations" }, ListMonitorEvaluationsRequest, ListMonitorEvaluationsResponse, [InvalidInputException, InvalidNextTokenException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createAutoPredictor = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreateAutoPredictor" }, CreateAutoPredictorRequest, CreateAutoPredictorResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeMonitor = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribeMonitor" }, DescribeMonitorRequest, DescribeMonitorResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describePredictor = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.DescribePredictor" }, DescribePredictorRequest, DescribePredictorResponse, [InvalidInputException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createPredictor = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.CreatePredictor" }, CreatePredictorRequest, CreatePredictorResponse, [InvalidInputException, LimitExceededException, ResourceAlreadyExistsException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getAccuracyMetrics = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-06-26", uri: "/", method: "POST", sdkId: "forecast", sigV4ServiceName: "forecast", name: "AmazonForecast.GetAccuracyMetrics" }, GetAccuracyMetricsRequest, GetAccuracyMetricsResponse, [InvalidInputException, ResourceInUseException, ResourceNotFoundException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
