import { Schema} from "effect"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import { Operation, Path, Header, StreamBody, Body } from "../schema-helpers.ts";

//# Schemas
export class DisassociateServiceRoleFromAccountRequest extends Schema.Class<DisassociateServiceRoleFromAccountRequest>("DisassociateServiceRoleFromAccountRequest")({}) {}
export class GetServiceRoleForAccountRequest extends Schema.Class<GetServiceRoleForAccountRequest>("GetServiceRoleForAccountRequest")({}) {}
export const TagKeyList = Schema.Array(Schema.String);
export class AssociateServiceRoleToAccountRequest extends Schema.Class<AssociateServiceRoleToAccountRequest>("AssociateServiceRoleToAccountRequest")({roleArn: Schema.String}) {}
export class CancelDeploymentRequest extends Schema.Class<CancelDeploymentRequest>("CancelDeploymentRequest")({deploymentId: Schema.String}) {}
export class DeleteComponentRequest extends Schema.Class<DeleteComponentRequest>("DeleteComponentRequest")({arn: Schema.String}) {}
export class DeleteCoreDeviceRequest extends Schema.Class<DeleteCoreDeviceRequest>("DeleteCoreDeviceRequest")({coreDeviceThingName: Schema.String}) {}
export class DeleteDeploymentRequest extends Schema.Class<DeleteDeploymentRequest>("DeleteDeploymentRequest")({deploymentId: Schema.String}) {}
export class DescribeComponentRequest extends Schema.Class<DescribeComponentRequest>("DescribeComponentRequest")({arn: Schema.String}) {}
export class DisassociateServiceRoleFromAccountResponse extends Schema.Class<DisassociateServiceRoleFromAccountResponse>("DisassociateServiceRoleFromAccountResponse")({disassociatedAt: Schema.optional(Schema.String)}) {}
export class GetComponentRequest extends Schema.Class<GetComponentRequest>("GetComponentRequest")({recipeOutputFormat: Schema.optional(Schema.String), arn: Schema.String}) {}
export class GetComponentVersionArtifactRequest extends Schema.Class<GetComponentVersionArtifactRequest>("GetComponentVersionArtifactRequest")({arn: Schema.String, artifactName: Schema.String, s3EndpointType: Schema.optional(Schema.String), iotEndpointType: Schema.optional(Header("x-amz-iot-endpoint-type"))}) {}
export class GetConnectivityInfoRequest extends Schema.Class<GetConnectivityInfoRequest>("GetConnectivityInfoRequest")({thingName: Schema.String}) {}
export class GetCoreDeviceRequest extends Schema.Class<GetCoreDeviceRequest>("GetCoreDeviceRequest")({coreDeviceThingName: Schema.String}) {}
export class GetDeploymentRequest extends Schema.Class<GetDeploymentRequest>("GetDeploymentRequest")({deploymentId: Schema.String}) {}
export class GetServiceRoleForAccountResponse extends Schema.Class<GetServiceRoleForAccountResponse>("GetServiceRoleForAccountResponse")({associatedAt: Schema.optional(Schema.String), roleArn: Schema.optional(Schema.String)}) {}
export class ListClientDevicesAssociatedWithCoreDeviceRequest extends Schema.Class<ListClientDevicesAssociatedWithCoreDeviceRequest>("ListClientDevicesAssociatedWithCoreDeviceRequest")({coreDeviceThingName: Schema.String, maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListComponentsRequest extends Schema.Class<ListComponentsRequest>("ListComponentsRequest")({scope: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListComponentVersionsRequest extends Schema.Class<ListComponentVersionsRequest>("ListComponentVersionsRequest")({arn: Schema.String, maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListCoreDevicesRequest extends Schema.Class<ListCoreDevicesRequest>("ListCoreDevicesRequest")({thingGroupArn: Schema.optional(Schema.String), status: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String), runtime: Schema.optional(Schema.String)}) {}
export class ListDeploymentsRequest extends Schema.Class<ListDeploymentsRequest>("ListDeploymentsRequest")({targetArn: Schema.optional(Schema.String), historyFilter: Schema.optional(Schema.String), parentTargetArn: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListEffectiveDeploymentsRequest extends Schema.Class<ListEffectiveDeploymentsRequest>("ListEffectiveDeploymentsRequest")({coreDeviceThingName: Schema.String, maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListInstalledComponentsRequest extends Schema.Class<ListInstalledComponentsRequest>("ListInstalledComponentsRequest")({coreDeviceThingName: Schema.String, maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String), topologyFilter: Schema.optional(Schema.String)}) {}
export class ListTagsForResourceRequest extends Schema.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({resourceArn: Schema.String}) {}
export const TagMap = Schema.Record({key: Schema.String, value: Schema.String});
export class TagResourceRequest extends Schema.Class<TagResourceRequest>("TagResourceRequest")({resourceArn: Schema.String, tags: TagMap}) {}
export class TagResourceResponse extends Schema.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends Schema.Class<UntagResourceRequest>("UntagResourceRequest")({resourceArn: Schema.String, tagKeys: TagKeyList}) {}
export class UntagResourceResponse extends Schema.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export const PlatformAttributesMap = Schema.Record({key: Schema.String, value: Schema.String});
export class ComponentPlatform extends Schema.Class<ComponentPlatform>("ComponentPlatform")({name: Schema.optional(Schema.String), attributes: Schema.optional(PlatformAttributesMap)}) {}
export const ComponentPlatformList = Schema.Array(ComponentPlatform);
export class AssociateClientDeviceWithCoreDeviceEntry extends Schema.Class<AssociateClientDeviceWithCoreDeviceEntry>("AssociateClientDeviceWithCoreDeviceEntry")({thingName: Schema.String}) {}
export const AssociateClientDeviceWithCoreDeviceEntryList = Schema.Array(AssociateClientDeviceWithCoreDeviceEntry);
export class DisassociateClientDeviceFromCoreDeviceEntry extends Schema.Class<DisassociateClientDeviceFromCoreDeviceEntry>("DisassociateClientDeviceFromCoreDeviceEntry")({thingName: Schema.String}) {}
export const DisassociateClientDeviceFromCoreDeviceEntryList = Schema.Array(DisassociateClientDeviceFromCoreDeviceEntry);
export class ConnectivityInfo extends Schema.Class<ConnectivityInfo>("ConnectivityInfo")({id: Schema.optional(Schema.String), hostAddress: Schema.optional(Schema.String), portNumber: Schema.optional(Schema.Number), metadata: Schema.optional(Schema.String)}) {}
export const connectivityInfoList = Schema.Array(ConnectivityInfo);
export const LambdaExecArgsList = Schema.Array(Schema.String);
export class AssociateServiceRoleToAccountResponse extends Schema.Class<AssociateServiceRoleToAccountResponse>("AssociateServiceRoleToAccountResponse")({associatedAt: Schema.optional(Schema.String)}) {}
export class BatchAssociateClientDeviceWithCoreDeviceRequest extends Schema.Class<BatchAssociateClientDeviceWithCoreDeviceRequest>("BatchAssociateClientDeviceWithCoreDeviceRequest")({entries: Schema.optional(AssociateClientDeviceWithCoreDeviceEntryList), coreDeviceThingName: Schema.String}) {}
export class BatchDisassociateClientDeviceFromCoreDeviceRequest extends Schema.Class<BatchDisassociateClientDeviceFromCoreDeviceRequest>("BatchDisassociateClientDeviceFromCoreDeviceRequest")({entries: Schema.optional(DisassociateClientDeviceFromCoreDeviceEntryList), coreDeviceThingName: Schema.String}) {}
export class CancelDeploymentResponse extends Schema.Class<CancelDeploymentResponse>("CancelDeploymentResponse")({message: Schema.optional(Schema.String)}) {}
export class AccessDeniedException extends Schema.Class<AccessDeniedException>("AccessDeniedException")({message: Schema.String}) {}
export class ConflictException extends Schema.Class<ConflictException>("ConflictException")({message: Schema.String, resourceId: Schema.String, resourceType: Schema.String}) {}
export class InternalServerException extends Schema.Class<InternalServerException>("InternalServerException")({message: Schema.String, retryAfterSeconds: Schema.optional(Header("Retry-After", Schema.Number))}) {}
export class GetComponentResponse extends Schema.Class<GetComponentResponse>("GetComponentResponse")({recipeOutputFormat: Schema.String, recipe: StreamBody(), tags: Schema.optional(TagMap)}) {}
export class GetComponentVersionArtifactResponse extends Schema.Class<GetComponentVersionArtifactResponse>("GetComponentVersionArtifactResponse")({preSignedUrl: Schema.String}) {}
export class GetConnectivityInfoResponse extends Schema.Class<GetConnectivityInfoResponse>("GetConnectivityInfoResponse")({connectivityInfo: Schema.optional(connectivityInfoList), message: Schema.optional(Schema.String)}) {}
export class GetCoreDeviceResponse extends Schema.Class<GetCoreDeviceResponse>("GetCoreDeviceResponse")({coreDeviceThingName: Schema.optional(Schema.String), coreVersion: Schema.optional(Schema.String), platform: Schema.optional(Schema.String), architecture: Schema.optional(Schema.String), runtime: Schema.optional(Schema.String), status: Schema.optional(Schema.String), lastStatusUpdateTimestamp: Schema.optional(Schema.Date), tags: Schema.optional(TagMap)}) {}
export const ComponentConfigurationPathList = Schema.Array(Schema.String);
export class ComponentConfigurationUpdate extends Schema.Class<ComponentConfigurationUpdate>("ComponentConfigurationUpdate")({merge: Schema.optional(Schema.String), reset: Schema.optional(ComponentConfigurationPathList)}) {}
export class SystemResourceLimits extends Schema.Class<SystemResourceLimits>("SystemResourceLimits")({memory: Schema.optional(Schema.Number), cpus: Schema.optional(Schema.Number)}) {}
export class ComponentRunWith extends Schema.Class<ComponentRunWith>("ComponentRunWith")({posixUser: Schema.optional(Schema.String), systemResourceLimits: Schema.optional(SystemResourceLimits), windowsUser: Schema.optional(Schema.String)}) {}
export class ComponentDeploymentSpecification extends Schema.Class<ComponentDeploymentSpecification>("ComponentDeploymentSpecification")({componentVersion: Schema.String, configurationUpdate: Schema.optional(ComponentConfigurationUpdate), runWith: Schema.optional(ComponentRunWith)}) {}
export const ComponentDeploymentSpecifications = Schema.Record({key: Schema.String, value: ComponentDeploymentSpecification});
export class DeploymentComponentUpdatePolicy extends Schema.Class<DeploymentComponentUpdatePolicy>("DeploymentComponentUpdatePolicy")({timeoutInSeconds: Schema.optional(Schema.Number), action: Schema.optional(Schema.String)}) {}
export class DeploymentConfigurationValidationPolicy extends Schema.Class<DeploymentConfigurationValidationPolicy>("DeploymentConfigurationValidationPolicy")({timeoutInSeconds: Schema.optional(Schema.Number)}) {}
export class DeploymentPolicies extends Schema.Class<DeploymentPolicies>("DeploymentPolicies")({failureHandlingPolicy: Schema.optional(Schema.String), componentUpdatePolicy: Schema.optional(DeploymentComponentUpdatePolicy), configurationValidationPolicy: Schema.optional(DeploymentConfigurationValidationPolicy)}) {}
export class IoTJobRateIncreaseCriteria extends Schema.Class<IoTJobRateIncreaseCriteria>("IoTJobRateIncreaseCriteria")({numberOfNotifiedThings: Schema.optional(Schema.Number), numberOfSucceededThings: Schema.optional(Schema.Number)}) {}
export class IoTJobExponentialRolloutRate extends Schema.Class<IoTJobExponentialRolloutRate>("IoTJobExponentialRolloutRate")({baseRatePerMinute: Schema.Number, incrementFactor: Schema.Number, rateIncreaseCriteria: IoTJobRateIncreaseCriteria}) {}
export class IoTJobExecutionsRolloutConfig extends Schema.Class<IoTJobExecutionsRolloutConfig>("IoTJobExecutionsRolloutConfig")({exponentialRate: Schema.optional(IoTJobExponentialRolloutRate), maximumPerMinute: Schema.optional(Schema.Number)}) {}
export class IoTJobAbortCriteria extends Schema.Class<IoTJobAbortCriteria>("IoTJobAbortCriteria")({failureType: Schema.String, action: Schema.String, thresholdPercentage: Schema.Number, minNumberOfExecutedThings: Schema.Number}) {}
export const IoTJobAbortCriteriaList = Schema.Array(IoTJobAbortCriteria);
export class IoTJobAbortConfig extends Schema.Class<IoTJobAbortConfig>("IoTJobAbortConfig")({criteriaList: IoTJobAbortCriteriaList}) {}
export class IoTJobTimeoutConfig extends Schema.Class<IoTJobTimeoutConfig>("IoTJobTimeoutConfig")({inProgressTimeoutInMinutes: Schema.optional(Schema.Number)}) {}
export class DeploymentIoTJobConfiguration extends Schema.Class<DeploymentIoTJobConfiguration>("DeploymentIoTJobConfiguration")({jobExecutionsRolloutConfig: Schema.optional(IoTJobExecutionsRolloutConfig), abortConfig: Schema.optional(IoTJobAbortConfig), timeoutConfig: Schema.optional(IoTJobTimeoutConfig)}) {}
export class GetDeploymentResponse extends Schema.Class<GetDeploymentResponse>("GetDeploymentResponse")({targetArn: Schema.optional(Schema.String), revisionId: Schema.optional(Schema.String), deploymentId: Schema.optional(Schema.String), deploymentName: Schema.optional(Schema.String), deploymentStatus: Schema.optional(Schema.String), iotJobId: Schema.optional(Schema.String), iotJobArn: Schema.optional(Schema.String), components: Schema.optional(ComponentDeploymentSpecifications), deploymentPolicies: Schema.optional(DeploymentPolicies), iotJobConfiguration: Schema.optional(DeploymentIoTJobConfiguration), creationTimestamp: Schema.optional(Schema.Date), isLatestForTarget: Schema.optional(Schema.Boolean), parentTargetArn: Schema.optional(Schema.String), tags: Schema.optional(TagMap)}) {}
export class ListTagsForResourceResponse extends Schema.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({tags: Schema.optional(TagMap)}) {}
export class ResourceNotFoundException extends Schema.Class<ResourceNotFoundException>("ResourceNotFoundException")({message: Schema.String, resourceId: Schema.String, resourceType: Schema.String}) {}
export class UpdateConnectivityInfoRequest extends Schema.Class<UpdateConnectivityInfoRequest>("UpdateConnectivityInfoRequest")({thingName: Schema.String, connectivityInfo: connectivityInfoList}) {}
export const InstalledComponentLifecycleStatusCodeList = Schema.Array(Schema.String);
export const ComponentVersionRequirementMap = Schema.Record({key: Schema.String, value: Schema.String});
export class AssociatedClientDevice extends Schema.Class<AssociatedClientDevice>("AssociatedClientDevice")({thingName: Schema.optional(Schema.String), associationTimestamp: Schema.optional(Schema.Date)}) {}
export const AssociatedClientDeviceList = Schema.Array(AssociatedClientDevice);
export class ComponentVersionListItem extends Schema.Class<ComponentVersionListItem>("ComponentVersionListItem")({componentName: Schema.optional(Schema.String), componentVersion: Schema.optional(Schema.String), arn: Schema.optional(Schema.String)}) {}
export const ComponentVersionList = Schema.Array(ComponentVersionListItem);
export class CoreDevice extends Schema.Class<CoreDevice>("CoreDevice")({coreDeviceThingName: Schema.optional(Schema.String), status: Schema.optional(Schema.String), lastStatusUpdateTimestamp: Schema.optional(Schema.Date), platform: Schema.optional(Schema.String), architecture: Schema.optional(Schema.String), runtime: Schema.optional(Schema.String)}) {}
export const CoreDevicesList = Schema.Array(CoreDevice);
export class Deployment extends Schema.Class<Deployment>("Deployment")({targetArn: Schema.optional(Schema.String), revisionId: Schema.optional(Schema.String), deploymentId: Schema.optional(Schema.String), deploymentName: Schema.optional(Schema.String), creationTimestamp: Schema.optional(Schema.Date), deploymentStatus: Schema.optional(Schema.String), isLatestForTarget: Schema.optional(Schema.Boolean), parentTargetArn: Schema.optional(Schema.String)}) {}
export const DeploymentList = Schema.Array(Deployment);
export class InstalledComponent extends Schema.Class<InstalledComponent>("InstalledComponent")({componentName: Schema.optional(Schema.String), componentVersion: Schema.optional(Schema.String), lifecycleState: Schema.optional(Schema.String), lifecycleStateDetails: Schema.optional(Schema.String), isRoot: Schema.optional(Schema.Boolean), lastStatusChangeTimestamp: Schema.optional(Schema.Date), lastReportedTimestamp: Schema.optional(Schema.Date), lastInstallationSource: Schema.optional(Schema.String), lifecycleStatusCodes: Schema.optional(InstalledComponentLifecycleStatusCodeList)}) {}
export const InstalledComponentList = Schema.Array(InstalledComponent);
export class ComponentCandidate extends Schema.Class<ComponentCandidate>("ComponentCandidate")({componentName: Schema.optional(Schema.String), componentVersion: Schema.optional(Schema.String), versionRequirements: Schema.optional(ComponentVersionRequirementMap)}) {}
export const ComponentCandidateList = Schema.Array(ComponentCandidate);
export class ValidationExceptionField extends Schema.Class<ValidationExceptionField>("ValidationExceptionField")({name: Schema.String, message: Schema.String}) {}
export const ValidationExceptionFieldList = Schema.Array(ValidationExceptionField);
export class ComponentDependencyRequirement extends Schema.Class<ComponentDependencyRequirement>("ComponentDependencyRequirement")({versionRequirement: Schema.optional(Schema.String), dependencyType: Schema.optional(Schema.String)}) {}
export class LambdaEventSource extends Schema.Class<LambdaEventSource>("LambdaEventSource")({topic: Schema.String, type: Schema.String}) {}
export const LambdaEventSourceList = Schema.Array(LambdaEventSource);
export const LambdaEnvironmentVariables = Schema.Record({key: Schema.String, value: Schema.String});
export const EffectiveDeploymentErrorStack = Schema.Array(Schema.String);
export const EffectiveDeploymentErrorTypeList = Schema.Array(Schema.String);
export class ThrottlingException extends Schema.Class<ThrottlingException>("ThrottlingException")({message: Schema.String, quotaCode: Schema.optional(Schema.String), serviceCode: Schema.optional(Schema.String), retryAfterSeconds: Schema.optional(Header("Retry-After", Schema.Number))}) {}
export class ListClientDevicesAssociatedWithCoreDeviceResponse extends Schema.Class<ListClientDevicesAssociatedWithCoreDeviceResponse>("ListClientDevicesAssociatedWithCoreDeviceResponse")({associatedClientDevices: Schema.optional(AssociatedClientDeviceList), nextToken: Schema.optional(Schema.String)}) {}
export class ListComponentVersionsResponse extends Schema.Class<ListComponentVersionsResponse>("ListComponentVersionsResponse")({componentVersions: Schema.optional(ComponentVersionList), nextToken: Schema.optional(Schema.String)}) {}
export class ListCoreDevicesResponse extends Schema.Class<ListCoreDevicesResponse>("ListCoreDevicesResponse")({coreDevices: Schema.optional(CoreDevicesList), nextToken: Schema.optional(Schema.String)}) {}
export class ListDeploymentsResponse extends Schema.Class<ListDeploymentsResponse>("ListDeploymentsResponse")({deployments: Schema.optional(DeploymentList), nextToken: Schema.optional(Schema.String)}) {}
export class ListInstalledComponentsResponse extends Schema.Class<ListInstalledComponentsResponse>("ListInstalledComponentsResponse")({installedComponents: Schema.optional(InstalledComponentList), nextToken: Schema.optional(Schema.String)}) {}
export class ResolveComponentCandidatesRequest extends Schema.Class<ResolveComponentCandidatesRequest>("ResolveComponentCandidatesRequest")({platform: Schema.optional(ComponentPlatform), componentCandidates: Schema.optional(ComponentCandidateList)}) {}
export class ValidationException extends Schema.Class<ValidationException>("ValidationException")({message: Schema.String, reason: Schema.optional(Schema.String), fields: Schema.optional(ValidationExceptionFieldList)}) {}
export class UpdateConnectivityInfoResponse extends Schema.Class<UpdateConnectivityInfoResponse>("UpdateConnectivityInfoResponse")({version: Schema.optional(Schema.String), message: Schema.optional(Schema.String)}) {}
export const ComponentDependencyMap = Schema.Record({key: Schema.String, value: ComponentDependencyRequirement});
export const StringMap = Schema.Record({key: Schema.String, value: Schema.String});
export class ComponentLatestVersion extends Schema.Class<ComponentLatestVersion>("ComponentLatestVersion")({arn: Schema.optional(Schema.String), componentVersion: Schema.optional(Schema.String), creationTimestamp: Schema.optional(Schema.Date), description: Schema.optional(Schema.String), publisher: Schema.optional(Schema.String), platforms: Schema.optional(ComponentPlatformList)}) {}
export class EffectiveDeploymentStatusDetails extends Schema.Class<EffectiveDeploymentStatusDetails>("EffectiveDeploymentStatusDetails")({errorStack: Schema.optional(EffectiveDeploymentErrorStack), errorTypes: Schema.optional(EffectiveDeploymentErrorTypeList)}) {}
export class AssociateClientDeviceWithCoreDeviceErrorEntry extends Schema.Class<AssociateClientDeviceWithCoreDeviceErrorEntry>("AssociateClientDeviceWithCoreDeviceErrorEntry")({thingName: Schema.optional(Schema.String), code: Schema.optional(Schema.String), message: Schema.optional(Schema.String)}) {}
export const AssociateClientDeviceWithCoreDeviceErrorList = Schema.Array(AssociateClientDeviceWithCoreDeviceErrorEntry);
export class DisassociateClientDeviceFromCoreDeviceErrorEntry extends Schema.Class<DisassociateClientDeviceFromCoreDeviceErrorEntry>("DisassociateClientDeviceFromCoreDeviceErrorEntry")({thingName: Schema.optional(Schema.String), code: Schema.optional(Schema.String), message: Schema.optional(Schema.String)}) {}
export const DisassociateClientDeviceFromCoreDeviceErrorList = Schema.Array(DisassociateClientDeviceFromCoreDeviceErrorEntry);
export class CloudComponentStatus extends Schema.Class<CloudComponentStatus>("CloudComponentStatus")({componentState: Schema.optional(Schema.String), message: Schema.optional(Schema.String), errors: Schema.optional(StringMap), vendorGuidance: Schema.optional(Schema.String), vendorGuidanceMessage: Schema.optional(Schema.String)}) {}
export class Component extends Schema.Class<Component>("Component")({arn: Schema.optional(Schema.String), componentName: Schema.optional(Schema.String), latestVersion: Schema.optional(ComponentLatestVersion)}) {}
export const ComponentList = Schema.Array(Component);
export class EffectiveDeployment extends Schema.Class<EffectiveDeployment>("EffectiveDeployment")({deploymentId: Schema.String, deploymentName: Schema.String, iotJobId: Schema.optional(Schema.String), iotJobArn: Schema.optional(Schema.String), description: Schema.optional(Schema.String), targetArn: Schema.String, coreDeviceExecutionStatus: Schema.String, reason: Schema.optional(Schema.String), creationTimestamp: Schema.Date, modifiedTimestamp: Schema.Date, statusDetails: Schema.optional(EffectiveDeploymentStatusDetails)}) {}
export const EffectiveDeploymentsList = Schema.Array(EffectiveDeployment);
export class BatchAssociateClientDeviceWithCoreDeviceResponse extends Schema.Class<BatchAssociateClientDeviceWithCoreDeviceResponse>("BatchAssociateClientDeviceWithCoreDeviceResponse")({errorEntries: Schema.optional(AssociateClientDeviceWithCoreDeviceErrorList)}) {}
export class BatchDisassociateClientDeviceFromCoreDeviceResponse extends Schema.Class<BatchDisassociateClientDeviceFromCoreDeviceResponse>("BatchDisassociateClientDeviceFromCoreDeviceResponse")({errorEntries: Schema.optional(DisassociateClientDeviceFromCoreDeviceErrorList)}) {}
export class LambdaVolumeMount extends Schema.Class<LambdaVolumeMount>("LambdaVolumeMount")({sourcePath: Schema.String, destinationPath: Schema.String, permission: Schema.optional(Schema.String), addGroupOwner: Schema.optional(Schema.Boolean)}) {}
export const LambdaVolumeList = Schema.Array(LambdaVolumeMount);
export class LambdaDeviceMount extends Schema.Class<LambdaDeviceMount>("LambdaDeviceMount")({path: Schema.String, permission: Schema.optional(Schema.String), addGroupOwner: Schema.optional(Schema.Boolean)}) {}
export const LambdaDeviceList = Schema.Array(LambdaDeviceMount);
export class DescribeComponentResponse extends Schema.Class<DescribeComponentResponse>("DescribeComponentResponse")({arn: Schema.optional(Schema.String), componentName: Schema.optional(Schema.String), componentVersion: Schema.optional(Schema.String), creationTimestamp: Schema.optional(Schema.Date), publisher: Schema.optional(Schema.String), description: Schema.optional(Schema.String), status: Schema.optional(CloudComponentStatus), platforms: Schema.optional(ComponentPlatformList), tags: Schema.optional(TagMap)}) {}
export class ListComponentsResponse extends Schema.Class<ListComponentsResponse>("ListComponentsResponse")({components: Schema.optional(ComponentList), nextToken: Schema.optional(Schema.String)}) {}
export class ListEffectiveDeploymentsResponse extends Schema.Class<ListEffectiveDeploymentsResponse>("ListEffectiveDeploymentsResponse")({effectiveDeployments: Schema.optional(EffectiveDeploymentsList), nextToken: Schema.optional(Schema.String)}) {}
export class LambdaContainerParams extends Schema.Class<LambdaContainerParams>("LambdaContainerParams")({memorySizeInKB: Schema.optional(Schema.Number), mountROSysfs: Schema.optional(Schema.Boolean), volumes: Schema.optional(LambdaVolumeList), devices: Schema.optional(LambdaDeviceList)}) {}
export class ResolvedComponentVersion extends Schema.Class<ResolvedComponentVersion>("ResolvedComponentVersion")({arn: Schema.optional(Schema.String), componentName: Schema.optional(Schema.String), componentVersion: Schema.optional(Schema.String), recipe: Schema.optional(StreamBody()), vendorGuidance: Schema.optional(Schema.String), message: Schema.optional(Schema.String)}) {}
export const ResolvedComponentVersionsList = Schema.Array(ResolvedComponentVersion);
export class LambdaLinuxProcessParams extends Schema.Class<LambdaLinuxProcessParams>("LambdaLinuxProcessParams")({isolationMode: Schema.optional(Schema.String), containerParams: Schema.optional(LambdaContainerParams)}) {}
export class CreateDeploymentRequest extends Schema.Class<CreateDeploymentRequest>("CreateDeploymentRequest")({targetArn: Schema.String, deploymentName: Schema.optional(Schema.String), components: Schema.optional(ComponentDeploymentSpecifications), iotJobConfiguration: Schema.optional(DeploymentIoTJobConfiguration), deploymentPolicies: Schema.optional(DeploymentPolicies), parentTargetArn: Schema.optional(Schema.String), tags: Schema.optional(TagMap), clientToken: Schema.optional(Schema.String)}) {}
export class ResolveComponentCandidatesResponse extends Schema.Class<ResolveComponentCandidatesResponse>("ResolveComponentCandidatesResponse")({resolvedComponentVersions: Schema.optional(ResolvedComponentVersionsList)}) {}
export class LambdaExecutionParameters extends Schema.Class<LambdaExecutionParameters>("LambdaExecutionParameters")({eventSources: Schema.optional(LambdaEventSourceList), maxQueueSize: Schema.optional(Schema.Number), maxInstancesCount: Schema.optional(Schema.Number), maxIdleTimeInSeconds: Schema.optional(Schema.Number), timeoutInSeconds: Schema.optional(Schema.Number), statusTimeoutInSeconds: Schema.optional(Schema.Number), pinned: Schema.optional(Schema.Boolean), inputPayloadEncodingType: Schema.optional(Schema.String), execArgs: Schema.optional(LambdaExecArgsList), environmentVariables: Schema.optional(LambdaEnvironmentVariables), linuxProcessParams: Schema.optional(LambdaLinuxProcessParams)}) {}
export class LambdaFunctionRecipeSource extends Schema.Class<LambdaFunctionRecipeSource>("LambdaFunctionRecipeSource")({lambdaArn: Schema.String, componentName: Schema.optional(Schema.String), componentVersion: Schema.optional(Schema.String), componentPlatforms: Schema.optional(ComponentPlatformList), componentDependencies: Schema.optional(ComponentDependencyMap), componentLambdaParameters: Schema.optional(LambdaExecutionParameters)}) {}
export class CreateComponentVersionRequest extends Schema.Class<CreateComponentVersionRequest>("CreateComponentVersionRequest")({inlineRecipe: Schema.optional(StreamBody()), lambdaFunction: Schema.optional(LambdaFunctionRecipeSource), tags: Schema.optional(TagMap), clientToken: Schema.optional(Schema.String)}) {}
export class CreateDeploymentResponse extends Schema.Class<CreateDeploymentResponse>("CreateDeploymentResponse")({deploymentId: Schema.optional(Schema.String), iotJobId: Schema.optional(Schema.String), iotJobArn: Schema.optional(Schema.String)}) {}
export class CreateComponentVersionResponse extends Schema.Class<CreateComponentVersionResponse>("CreateComponentVersionResponse")({arn: Schema.optional(Schema.String), componentName: Schema.String, componentVersion: Schema.String, creationTimestamp: Schema.Date, status: CloudComponentStatus}) {}
export class RequestAlreadyInProgressException extends Schema.Class<RequestAlreadyInProgressException>("RequestAlreadyInProgressException")({message: Schema.String}) {}
export class ServiceQuotaExceededException extends Schema.Class<ServiceQuotaExceededException>("ServiceQuotaExceededException")({message: Schema.String, resourceId: Schema.optional(Schema.String), resourceType: Schema.optional(Schema.String), quotaCode: Schema.String, serviceCode: Schema.String}) {}

//# Errors
export class AccessDeniedExceptionError extends Schema.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class ConflictExceptionError extends Schema.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class InternalServerExceptionError extends Schema.TaggedError<InternalServerExceptionError>()("InternalServerException", InternalServerException.fields) {};
export class ResourceNotFoundExceptionError extends Schema.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ValidationExceptionError extends Schema.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};
export class ThrottlingExceptionError extends Schema.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class RequestAlreadyInProgressExceptionError extends Schema.TaggedError<RequestAlreadyInProgressExceptionError>()("RequestAlreadyInProgressException", RequestAlreadyInProgressException.fields) {};
export class ServiceQuotaExceededExceptionError extends Schema.TaggedError<ServiceQuotaExceededExceptionError>()("ServiceQuotaExceededException", ServiceQuotaExceededException.fields) {};

//# Operations
export const disassociateServiceRoleFromAccount = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/servicerole", method: "DELETE", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.DisassociateServiceRoleFromAccount" }, DisassociateServiceRoleFromAccountRequest, DisassociateServiceRoleFromAccountResponse, [InternalServerExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getServiceRoleForAccount = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/servicerole", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.GetServiceRoleForAccount" }, GetServiceRoleForAccountRequest, GetServiceRoleForAccountResponse, [InternalServerExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const associateServiceRoleToAccount = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/servicerole", method: "PUT", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.AssociateServiceRoleToAccount" }, AssociateServiceRoleToAccountRequest, AssociateServiceRoleToAccountResponse, [InternalServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteComponent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/components/{arn}", method: "DELETE", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.DeleteComponent" }, DeleteComponentRequest, Schema.Struct({}), [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteCoreDevice = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/coreDevices/{coreDeviceThingName}", method: "DELETE", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.DeleteCoreDevice" }, DeleteCoreDeviceRequest, Schema.Struct({}), [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteDeployment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/deployments/{deploymentId}", method: "DELETE", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.DeleteDeployment" }, DeleteDeploymentRequest, Schema.Struct({}), [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getComponent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/components/{arn}", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.GetComponent" }, GetComponentRequest, GetComponentResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getComponentVersionArtifact = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/components/{arn}/artifacts/{artifactName+}", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.GetComponentVersionArtifact" }, GetComponentVersionArtifactRequest, GetComponentVersionArtifactResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getConnectivityInfo = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/things/{thingName}/connectivityInfo", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.GetConnectivityInfo" }, GetConnectivityInfoRequest, GetConnectivityInfoResponse, [InternalServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getCoreDevice = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/coreDevices/{coreDeviceThingName}", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.GetCoreDevice" }, GetCoreDeviceRequest, GetCoreDeviceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getDeployment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/deployments/{deploymentId}", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.GetDeployment" }, GetDeploymentRequest, GetDeploymentResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/tags/{resourceArn}", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/tags/{resourceArn}", method: "POST", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.TagResource" }, TagResourceRequest, TagResourceResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const cancelDeployment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/deployments/{deploymentId}/cancel", method: "POST", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.CancelDeployment" }, CancelDeploymentRequest, CancelDeploymentResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listClientDevicesAssociatedWithCoreDevice = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/coreDevices/{coreDeviceThingName}/associatedClientDevices", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.ListClientDevicesAssociatedWithCoreDevice" }, ListClientDevicesAssociatedWithCoreDeviceRequest, ListClientDevicesAssociatedWithCoreDeviceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listComponentVersions = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/components/{arn}/versions", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.ListComponentVersions" }, ListComponentVersionsRequest, ListComponentVersionsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listCoreDevices = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/coreDevices", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.ListCoreDevices" }, ListCoreDevicesRequest, ListCoreDevicesResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listDeployments = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/deployments", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.ListDeployments" }, ListDeploymentsRequest, ListDeploymentsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listInstalledComponents = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/coreDevices/{coreDeviceThingName}/installedComponents", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.ListInstalledComponents" }, ListInstalledComponentsRequest, ListInstalledComponentsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateConnectivityInfo = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/things/{thingName}/connectivityInfo", method: "PUT", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.UpdateConnectivityInfo" }, UpdateConnectivityInfoRequest, UpdateConnectivityInfoResponse, [InternalServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const batchAssociateClientDeviceWithCoreDevice = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/coreDevices/{coreDeviceThingName}/associateClientDevices", method: "POST", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.BatchAssociateClientDeviceWithCoreDevice" }, BatchAssociateClientDeviceWithCoreDeviceRequest, BatchAssociateClientDeviceWithCoreDeviceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const batchDisassociateClientDeviceFromCoreDevice = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/coreDevices/{coreDeviceThingName}/disassociateClientDevices", method: "POST", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.BatchDisassociateClientDeviceFromCoreDevice" }, BatchDisassociateClientDeviceFromCoreDeviceRequest, BatchDisassociateClientDeviceFromCoreDeviceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeComponent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/components/{arn}/metadata", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.DescribeComponent" }, DescribeComponentRequest, DescribeComponentResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listComponents = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/components", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.ListComponents" }, ListComponentsRequest, ListComponentsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listEffectiveDeployments = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/coreDevices/{coreDeviceThingName}/effectiveDeployments", method: "GET", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.ListEffectiveDeployments" }, ListEffectiveDeploymentsRequest, ListEffectiveDeploymentsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const resolveComponentCandidates = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/resolveComponentCandidates", method: "POST", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.ResolveComponentCandidates" }, ResolveComponentCandidatesRequest, ResolveComponentCandidatesResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createDeployment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/deployments", method: "POST", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.CreateDeployment" }, CreateDeploymentRequest, CreateDeploymentResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, RequestAlreadyInProgressExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createComponentVersion = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-11-30", uri: "/greengrass/v2/createComponentVersion", method: "POST", sdkId: "GreengrassV2", sigV4ServiceName: "greengrass", name: "GreengrassV2.CreateComponentVersion" }, CreateComponentVersionRequest, CreateComponentVersionResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, RequestAlreadyInProgressExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
