import { Schema} from "effect"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
export const ResourceNotFoundException = Schema.Struct({ResourceType: Schema.optional(Schema.String), ResourceId: Schema.optional(Schema.String), Reason: Schema.optional(Schema.String), Message: Schema.optional(Schema.String), RequestId: Schema.optional(Schema.String)});
export const GetGroupMembershipIdResponse = Schema.Struct({MembershipId: Schema.String, IdentityStoreId: Schema.String});
export const GroupMemberships = Schema.Array(GroupMembership);
export const GetGroupIdResponse = Schema.Struct({GroupId: Schema.String, IdentityStoreId: Schema.String});
export const ValidationException = Schema.Struct({Message: Schema.optional(Schema.String), RequestId: Schema.optional(Schema.String), Reason: Schema.optional(Schema.String)});
export const GroupMembership = Schema.Struct({IdentityStoreId: Schema.String, MembershipId: Schema.optional(Schema.String), GroupId: Schema.optional(Schema.String), MemberId: Schema.optional(MemberId), CreatedAt: Schema.optional(Schema.Date), UpdatedAt: Schema.optional(Schema.Date), CreatedBy: Schema.optional(Schema.String), UpdatedBy: Schema.optional(Schema.String)});
export const GroupMembershipExistenceResults = Schema.Array(GroupMembershipExistenceResult);
export const GroupMembershipExistenceResult = Schema.Struct({GroupId: Schema.optional(Schema.String), MemberId: Schema.optional(MemberId), MembershipExists: Schema.optional(Schema.Boolean)});
export const UniqueAttribute = Schema.Struct({AttributePath: Schema.String, AttributeValue: Schema.JsonValue});
export const ExternalId = Schema.Struct({Issuer: Schema.String, Id: Schema.String});
export const GetUserIdResponse = Schema.Struct({IdentityStoreId: Schema.String, UserId: Schema.String});
export const IsMemberInGroupsResponse = Schema.Struct({Results: GroupMembershipExistenceResults});
export const ListGroupMembershipsForMemberResponse = Schema.Struct({GroupMemberships: GroupMemberships, NextToken: Schema.optional(Schema.String)});
export const MemberId = Schema.Union(Schema.String);
export const AlternateIdentifier = Schema.Union(ExternalId, UniqueAttribute);
export const ListGroupMembershipsForMemberRequest = Schema.Struct({IdentityStoreId: Schema.String, MemberId: MemberId, MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)});
export const IsMemberInGroupsRequest = Schema.Struct({IdentityStoreId: Schema.String, MemberId: MemberId, GroupIds: GroupIds});
export const GetUserIdRequest = Schema.Struct({IdentityStoreId: Schema.String, AlternateIdentifier: AlternateIdentifier});
export const GetGroupMembershipIdRequest = Schema.Struct({IdentityStoreId: Schema.String, GroupId: Schema.String, MemberId: MemberId});
export const GroupIds = Schema.Array(Schema.String);
export const GetGroupIdRequest = Schema.Struct({IdentityStoreId: Schema.String, AlternateIdentifier: AlternateIdentifier});
export const GetUserId = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/", method: "POST", sdkId: "identitystore", sigV4ServiceName: "identitystore", name: "AWSIdentityStore.GetUserId" }, GetUserIdRequest, GetUserIdResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const IsMemberInGroups = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/", method: "POST", sdkId: "identitystore", sigV4ServiceName: "identitystore", name: "AWSIdentityStore.IsMemberInGroups" }, IsMemberInGroupsRequest, IsMemberInGroupsResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const ListGroupMembershipsForMember = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/", method: "POST", sdkId: "identitystore", sigV4ServiceName: "identitystore", name: "AWSIdentityStore.ListGroupMembershipsForMember" }, ListGroupMembershipsForMemberRequest, ListGroupMembershipsForMemberResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const GetGroupId = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/", method: "POST", sdkId: "identitystore", sigV4ServiceName: "identitystore", name: "AWSIdentityStore.GetGroupId" }, GetGroupIdRequest, GetGroupIdResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const GetGroupMembershipId = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/", method: "POST", sdkId: "identitystore", sigV4ServiceName: "identitystore", name: "AWSIdentityStore.GetGroupMembershipId" }, GetGroupMembershipIdRequest, GetGroupMembershipIdResponse, Schema.Union(ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
