import * as S from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export class DescribeLoggingOptionsRequest extends S.Class<DescribeLoggingOptionsRequest>("DescribeLoggingOptionsRequest")({}) {}
export const TagKeys = S.Array(S.String);
export class DeleteAlarmModelRequest extends S.Class<DeleteAlarmModelRequest>("DeleteAlarmModelRequest")({alarmModelName: S.String}) {}
export class DeleteAlarmModelResponse extends S.Class<DeleteAlarmModelResponse>("DeleteAlarmModelResponse")({}) {}
export class DeleteDetectorModelRequest extends S.Class<DeleteDetectorModelRequest>("DeleteDetectorModelRequest")({detectorModelName: S.String}) {}
export class DeleteDetectorModelResponse extends S.Class<DeleteDetectorModelResponse>("DeleteDetectorModelResponse")({}) {}
export class DeleteInputRequest extends S.Class<DeleteInputRequest>("DeleteInputRequest")({inputName: S.String}) {}
export class DeleteInputResponse extends S.Class<DeleteInputResponse>("DeleteInputResponse")({}) {}
export class DescribeAlarmModelRequest extends S.Class<DescribeAlarmModelRequest>("DescribeAlarmModelRequest")({alarmModelName: S.String, alarmModelVersion: S.optional(S.String)}) {}
export class DescribeDetectorModelRequest extends S.Class<DescribeDetectorModelRequest>("DescribeDetectorModelRequest")({detectorModelName: S.String, detectorModelVersion: S.optional(S.String)}) {}
export class DescribeDetectorModelAnalysisRequest extends S.Class<DescribeDetectorModelAnalysisRequest>("DescribeDetectorModelAnalysisRequest")({analysisId: S.String}) {}
export class DescribeInputRequest extends S.Class<DescribeInputRequest>("DescribeInputRequest")({inputName: S.String}) {}
export class GetDetectorModelAnalysisResultsRequest extends S.Class<GetDetectorModelAnalysisResultsRequest>("GetDetectorModelAnalysisResultsRequest")({analysisId: S.String, nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListAlarmModelsRequest extends S.Class<ListAlarmModelsRequest>("ListAlarmModelsRequest")({nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListAlarmModelVersionsRequest extends S.Class<ListAlarmModelVersionsRequest>("ListAlarmModelVersionsRequest")({alarmModelName: S.String, nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListDetectorModelsRequest extends S.Class<ListDetectorModelsRequest>("ListDetectorModelsRequest")({nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListDetectorModelVersionsRequest extends S.Class<ListDetectorModelVersionsRequest>("ListDetectorModelVersionsRequest")({detectorModelName: S.String, nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListInputsRequest extends S.Class<ListInputsRequest>("ListInputsRequest")({nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({resourceArn: S.String}) {}
export class DetectorDebugOption extends S.Class<DetectorDebugOption>("DetectorDebugOption")({detectorModelName: S.String, keyValue: S.optional(S.String)}) {}
export const DetectorDebugOptions = S.Array(DetectorDebugOption);
export class LoggingOptions extends S.Class<LoggingOptions>("LoggingOptions")({roleArn: S.String, level: S.String, enabled: S.Boolean, detectorDebugOptions: S.optional(DetectorDebugOptions)}) {}
export class PutLoggingOptionsRequest extends S.Class<PutLoggingOptionsRequest>("PutLoggingOptionsRequest")({loggingOptions: LoggingOptions}) {}
export class SetVariableAction extends S.Class<SetVariableAction>("SetVariableAction")({variableName: S.String, value: S.String}) {}
export class Payload extends S.Class<Payload>("Payload")({contentExpression: S.String, type: S.String}) {}
export class SNSTopicPublishAction extends S.Class<SNSTopicPublishAction>("SNSTopicPublishAction")({targetArn: S.String, payload: S.optional(Payload)}) {}
export class IotTopicPublishAction extends S.Class<IotTopicPublishAction>("IotTopicPublishAction")({mqttTopic: S.String, payload: S.optional(Payload)}) {}
export class SetTimerAction extends S.Class<SetTimerAction>("SetTimerAction")({timerName: S.String, seconds: S.optional(S.Number), durationExpression: S.optional(S.String)}) {}
export class ClearTimerAction extends S.Class<ClearTimerAction>("ClearTimerAction")({timerName: S.String}) {}
export class ResetTimerAction extends S.Class<ResetTimerAction>("ResetTimerAction")({timerName: S.String}) {}
export class LambdaAction extends S.Class<LambdaAction>("LambdaAction")({functionArn: S.String, payload: S.optional(Payload)}) {}
export class IotEventsAction extends S.Class<IotEventsAction>("IotEventsAction")({inputName: S.String, payload: S.optional(Payload)}) {}
export class SqsAction extends S.Class<SqsAction>("SqsAction")({queueUrl: S.String, useBase64: S.optional(S.Boolean), payload: S.optional(Payload)}) {}
export class FirehoseAction extends S.Class<FirehoseAction>("FirehoseAction")({deliveryStreamName: S.String, separator: S.optional(S.String), payload: S.optional(Payload)}) {}
export class DynamoDBAction extends S.Class<DynamoDBAction>("DynamoDBAction")({hashKeyType: S.optional(S.String), hashKeyField: S.String, hashKeyValue: S.String, rangeKeyType: S.optional(S.String), rangeKeyField: S.optional(S.String), rangeKeyValue: S.optional(S.String), operation: S.optional(S.String), payloadField: S.optional(S.String), tableName: S.String, payload: S.optional(Payload)}) {}
export class DynamoDBv2Action extends S.Class<DynamoDBv2Action>("DynamoDBv2Action")({tableName: S.String, payload: S.optional(Payload)}) {}
export class AssetPropertyVariant extends S.Class<AssetPropertyVariant>("AssetPropertyVariant")({stringValue: S.optional(S.String), integerValue: S.optional(S.String), doubleValue: S.optional(S.String), booleanValue: S.optional(S.String)}) {}
export class AssetPropertyTimestamp extends S.Class<AssetPropertyTimestamp>("AssetPropertyTimestamp")({timeInSeconds: S.String, offsetInNanos: S.optional(S.String)}) {}
export class AssetPropertyValue extends S.Class<AssetPropertyValue>("AssetPropertyValue")({value: S.optional(AssetPropertyVariant), timestamp: S.optional(AssetPropertyTimestamp), quality: S.optional(S.String)}) {}
export class IotSiteWiseAction extends S.Class<IotSiteWiseAction>("IotSiteWiseAction")({entryId: S.optional(S.String), assetId: S.optional(S.String), propertyId: S.optional(S.String), propertyAlias: S.optional(S.String), propertyValue: S.optional(AssetPropertyValue)}) {}
export class Action extends S.Class<Action>("Action")({setVariable: S.optional(SetVariableAction), sns: S.optional(SNSTopicPublishAction), iotTopicPublish: S.optional(IotTopicPublishAction), setTimer: S.optional(SetTimerAction), clearTimer: S.optional(ClearTimerAction), resetTimer: S.optional(ResetTimerAction), lambda: S.optional(LambdaAction), iotEvents: S.optional(IotEventsAction), sqs: S.optional(SqsAction), firehose: S.optional(FirehoseAction), dynamoDB: S.optional(DynamoDBAction), dynamoDBv2: S.optional(DynamoDBv2Action), iotSiteWise: S.optional(IotSiteWiseAction)}) {}
export const Actions = S.Array(Action);
export class Event extends S.Class<Event>("Event")({eventName: S.String, condition: S.optional(S.String), actions: S.optional(Actions)}) {}
export const Events = S.Array(Event);
export class TransitionEvent extends S.Class<TransitionEvent>("TransitionEvent")({eventName: S.String, condition: S.String, actions: S.optional(Actions), nextState: S.String}) {}
export const TransitionEvents = S.Array(TransitionEvent);
export class OnInputLifecycle extends S.Class<OnInputLifecycle>("OnInputLifecycle")({events: S.optional(Events), transitionEvents: S.optional(TransitionEvents)}) {}
export class OnEnterLifecycle extends S.Class<OnEnterLifecycle>("OnEnterLifecycle")({events: S.optional(Events)}) {}
export class OnExitLifecycle extends S.Class<OnExitLifecycle>("OnExitLifecycle")({events: S.optional(Events)}) {}
export class State extends S.Class<State>("State")({stateName: S.String, onInput: S.optional(OnInputLifecycle), onEnter: S.optional(OnEnterLifecycle), onExit: S.optional(OnExitLifecycle)}) {}
export const States = S.Array(State);
export class DetectorModelDefinition extends S.Class<DetectorModelDefinition>("DetectorModelDefinition")({states: States, initialStateName: S.String}) {}
export class StartDetectorModelAnalysisRequest extends S.Class<StartDetectorModelAnalysisRequest>("StartDetectorModelAnalysisRequest")({detectorModelDefinition: DetectorModelDefinition}) {}
export class Tag extends S.Class<Tag>("Tag")({key: S.String, value: S.String}) {}
export const Tags = S.Array(Tag);
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({resourceArn: S.String, tags: Tags}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({resourceArn: S.String, tagKeys: TagKeys}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class SimpleRule extends S.Class<SimpleRule>("SimpleRule")({inputProperty: S.String, comparisonOperator: S.String, threshold: S.String}) {}
export class AlarmRule extends S.Class<AlarmRule>("AlarmRule")({simpleRule: S.optional(SimpleRule)}) {}
export class NotificationTargetActions extends S.Class<NotificationTargetActions>("NotificationTargetActions")({lambdaAction: S.optional(LambdaAction)}) {}
export class SSOIdentity extends S.Class<SSOIdentity>("SSOIdentity")({identityStoreId: S.String, userId: S.optional(S.String)}) {}
export class RecipientDetail extends S.Class<RecipientDetail>("RecipientDetail")({ssoIdentity: S.optional(SSOIdentity)}) {}
export const RecipientDetails = S.Array(RecipientDetail);
export class SMSConfiguration extends S.Class<SMSConfiguration>("SMSConfiguration")({senderId: S.optional(S.String), additionalMessage: S.optional(S.String), recipients: RecipientDetails}) {}
export const SMSConfigurations = S.Array(SMSConfiguration);
export class EmailContent extends S.Class<EmailContent>("EmailContent")({subject: S.optional(S.String), additionalMessage: S.optional(S.String)}) {}
export class EmailRecipients extends S.Class<EmailRecipients>("EmailRecipients")({to: S.optional(RecipientDetails)}) {}
export class EmailConfiguration extends S.Class<EmailConfiguration>("EmailConfiguration")({from: S.String, content: S.optional(EmailContent), recipients: EmailRecipients}) {}
export const EmailConfigurations = S.Array(EmailConfiguration);
export class NotificationAction extends S.Class<NotificationAction>("NotificationAction")({action: NotificationTargetActions, smsConfigurations: S.optional(SMSConfigurations), emailConfigurations: S.optional(EmailConfigurations)}) {}
export const NotificationActions = S.Array(NotificationAction);
export class AlarmNotification extends S.Class<AlarmNotification>("AlarmNotification")({notificationActions: S.optional(NotificationActions)}) {}
export class AlarmAction extends S.Class<AlarmAction>("AlarmAction")({sns: S.optional(SNSTopicPublishAction), iotTopicPublish: S.optional(IotTopicPublishAction), lambda: S.optional(LambdaAction), iotEvents: S.optional(IotEventsAction), sqs: S.optional(SqsAction), firehose: S.optional(FirehoseAction), dynamoDB: S.optional(DynamoDBAction), dynamoDBv2: S.optional(DynamoDBv2Action), iotSiteWise: S.optional(IotSiteWiseAction)}) {}
export const AlarmActions = S.Array(AlarmAction);
export class AlarmEventActions extends S.Class<AlarmEventActions>("AlarmEventActions")({alarmActions: S.optional(AlarmActions)}) {}
export class InitializationConfiguration extends S.Class<InitializationConfiguration>("InitializationConfiguration")({disabledOnInitialization: S.Boolean}) {}
export class AcknowledgeFlow extends S.Class<AcknowledgeFlow>("AcknowledgeFlow")({enabled: S.Boolean}) {}
export class AlarmCapabilities extends S.Class<AlarmCapabilities>("AlarmCapabilities")({initializationConfiguration: S.optional(InitializationConfiguration), acknowledgeFlow: S.optional(AcknowledgeFlow)}) {}
export class UpdateAlarmModelRequest extends S.Class<UpdateAlarmModelRequest>("UpdateAlarmModelRequest")({alarmModelName: S.String, alarmModelDescription: S.optional(S.String), roleArn: S.String, severity: S.optional(S.Number), alarmRule: AlarmRule, alarmNotification: S.optional(AlarmNotification), alarmEventActions: S.optional(AlarmEventActions), alarmCapabilities: S.optional(AlarmCapabilities)}) {}
export class UpdateDetectorModelRequest extends S.Class<UpdateDetectorModelRequest>("UpdateDetectorModelRequest")({detectorModelName: S.String, detectorModelDefinition: DetectorModelDefinition, detectorModelDescription: S.optional(S.String), roleArn: S.String, evaluationMethod: S.optional(S.String)}) {}
export class Attribute extends S.Class<Attribute>("Attribute")({jsonPath: S.String}) {}
export const Attributes = S.Array(Attribute);
export class InputDefinition extends S.Class<InputDefinition>("InputDefinition")({attributes: Attributes}) {}
export class UpdateInputRequest extends S.Class<UpdateInputRequest>("UpdateInputRequest")({inputName: S.String, inputDescription: S.optional(S.String), inputDefinition: InputDefinition}) {}
export class InternalFailureException extends S.Class<InternalFailureException>("InternalFailureException")({message: S.optional(S.String)}) {}
export class InvalidRequestException extends S.Class<InvalidRequestException>("InvalidRequestException")({message: S.optional(S.String)}) {}
export class ResourceInUseException extends S.Class<ResourceInUseException>("ResourceInUseException")({message: S.optional(S.String)}) {}
export class DescribeAlarmModelResponse extends S.Class<DescribeAlarmModelResponse>("DescribeAlarmModelResponse")({creationTime: S.optional(S.Date), alarmModelArn: S.optional(S.String), alarmModelVersion: S.optional(S.String), lastUpdateTime: S.optional(S.Date), status: S.optional(S.String), statusMessage: S.optional(S.String), alarmModelName: S.optional(S.String), alarmModelDescription: S.optional(S.String), roleArn: S.optional(S.String), key: S.optional(S.String), severity: S.optional(S.Number), alarmRule: S.optional(AlarmRule), alarmNotification: S.optional(AlarmNotification), alarmEventActions: S.optional(AlarmEventActions), alarmCapabilities: S.optional(AlarmCapabilities)}) {}
export class DescribeDetectorModelAnalysisResponse extends S.Class<DescribeDetectorModelAnalysisResponse>("DescribeDetectorModelAnalysisResponse")({status: S.optional(S.String)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({tags: S.optional(Tags)}) {}
export class ServiceUnavailableException extends S.Class<ServiceUnavailableException>("ServiceUnavailableException")({message: S.optional(S.String)}) {}
export class StartDetectorModelAnalysisResponse extends S.Class<StartDetectorModelAnalysisResponse>("StartDetectorModelAnalysisResponse")({analysisId: S.optional(S.String)}) {}
export class LimitExceededException extends S.Class<LimitExceededException>("LimitExceededException")({message: S.optional(S.String)}) {}
export class ResourceNotFoundException extends S.Class<ResourceNotFoundException>("ResourceNotFoundException")({message: S.optional(S.String)}) {}
export class UpdateAlarmModelResponse extends S.Class<UpdateAlarmModelResponse>("UpdateAlarmModelResponse")({creationTime: S.optional(S.Date), alarmModelArn: S.optional(S.String), alarmModelVersion: S.optional(S.String), lastUpdateTime: S.optional(S.Date), status: S.optional(S.String)}) {}
export class IotEventsInputIdentifier extends S.Class<IotEventsInputIdentifier>("IotEventsInputIdentifier")({inputName: S.String}) {}
export class DetectorModelConfiguration extends S.Class<DetectorModelConfiguration>("DetectorModelConfiguration")({detectorModelName: S.optional(S.String), detectorModelVersion: S.optional(S.String), detectorModelDescription: S.optional(S.String), detectorModelArn: S.optional(S.String), roleArn: S.optional(S.String), creationTime: S.optional(S.Date), lastUpdateTime: S.optional(S.Date), status: S.optional(S.String), key: S.optional(S.String), evaluationMethod: S.optional(S.String)}) {}
export class DetectorModel extends S.Class<DetectorModel>("DetectorModel")({detectorModelDefinition: S.optional(DetectorModelDefinition), detectorModelConfiguration: S.optional(DetectorModelConfiguration)}) {}
export class InputConfiguration extends S.Class<InputConfiguration>("InputConfiguration")({inputName: S.String, inputDescription: S.optional(S.String), inputArn: S.String, creationTime: S.Date, lastUpdateTime: S.Date, status: S.String}) {}
export class Input extends S.Class<Input>("Input")({inputConfiguration: S.optional(InputConfiguration), inputDefinition: S.optional(InputDefinition)}) {}
export class AlarmModelSummary extends S.Class<AlarmModelSummary>("AlarmModelSummary")({creationTime: S.optional(S.Date), alarmModelDescription: S.optional(S.String), alarmModelName: S.optional(S.String)}) {}
export const AlarmModelSummaries = S.Array(AlarmModelSummary);
export class AlarmModelVersionSummary extends S.Class<AlarmModelVersionSummary>("AlarmModelVersionSummary")({alarmModelName: S.optional(S.String), alarmModelArn: S.optional(S.String), alarmModelVersion: S.optional(S.String), roleArn: S.optional(S.String), creationTime: S.optional(S.Date), lastUpdateTime: S.optional(S.Date), status: S.optional(S.String), statusMessage: S.optional(S.String)}) {}
export const AlarmModelVersionSummaries = S.Array(AlarmModelVersionSummary);
export class DetectorModelSummary extends S.Class<DetectorModelSummary>("DetectorModelSummary")({detectorModelName: S.optional(S.String), detectorModelDescription: S.optional(S.String), creationTime: S.optional(S.Date)}) {}
export const DetectorModelSummaries = S.Array(DetectorModelSummary);
export class DetectorModelVersionSummary extends S.Class<DetectorModelVersionSummary>("DetectorModelVersionSummary")({detectorModelName: S.optional(S.String), detectorModelVersion: S.optional(S.String), detectorModelArn: S.optional(S.String), roleArn: S.optional(S.String), creationTime: S.optional(S.Date), lastUpdateTime: S.optional(S.Date), status: S.optional(S.String), evaluationMethod: S.optional(S.String)}) {}
export const DetectorModelVersionSummaries = S.Array(DetectorModelVersionSummary);
export class InputSummary extends S.Class<InputSummary>("InputSummary")({inputName: S.optional(S.String), inputDescription: S.optional(S.String), inputArn: S.optional(S.String), creationTime: S.optional(S.Date), lastUpdateTime: S.optional(S.Date), status: S.optional(S.String)}) {}
export const InputSummaries = S.Array(InputSummary);
export class IotSiteWiseAssetModelPropertyIdentifier extends S.Class<IotSiteWiseAssetModelPropertyIdentifier>("IotSiteWiseAssetModelPropertyIdentifier")({assetModelId: S.String, propertyId: S.String}) {}
export class CreateInputRequest extends S.Class<CreateInputRequest>("CreateInputRequest")({inputName: S.String, inputDescription: S.optional(S.String), inputDefinition: InputDefinition, tags: S.optional(Tags)}) {}
export class ThrottlingException extends S.Class<ThrottlingException>("ThrottlingException")({message: S.optional(S.String)}) {}
export class DescribeDetectorModelResponse extends S.Class<DescribeDetectorModelResponse>("DescribeDetectorModelResponse")({detectorModel: S.optional(DetectorModel)}) {}
export class DescribeInputResponse extends S.Class<DescribeInputResponse>("DescribeInputResponse")({input: S.optional(Input)}) {}
export class DescribeLoggingOptionsResponse extends S.Class<DescribeLoggingOptionsResponse>("DescribeLoggingOptionsResponse")({loggingOptions: S.optional(LoggingOptions)}) {}
export class ListAlarmModelsResponse extends S.Class<ListAlarmModelsResponse>("ListAlarmModelsResponse")({alarmModelSummaries: S.optional(AlarmModelSummaries), nextToken: S.optional(S.String)}) {}
export class ListAlarmModelVersionsResponse extends S.Class<ListAlarmModelVersionsResponse>("ListAlarmModelVersionsResponse")({alarmModelVersionSummaries: S.optional(AlarmModelVersionSummaries), nextToken: S.optional(S.String)}) {}
export class ListDetectorModelsResponse extends S.Class<ListDetectorModelsResponse>("ListDetectorModelsResponse")({detectorModelSummaries: S.optional(DetectorModelSummaries), nextToken: S.optional(S.String)}) {}
export class ListDetectorModelVersionsResponse extends S.Class<ListDetectorModelVersionsResponse>("ListDetectorModelVersionsResponse")({detectorModelVersionSummaries: S.optional(DetectorModelVersionSummaries), nextToken: S.optional(S.String)}) {}
export class ListInputsResponse extends S.Class<ListInputsResponse>("ListInputsResponse")({inputSummaries: S.optional(InputSummaries), nextToken: S.optional(S.String)}) {}
export class UnsupportedOperationException extends S.Class<UnsupportedOperationException>("UnsupportedOperationException")({message: S.optional(S.String)}) {}
export class UpdateDetectorModelResponse extends S.Class<UpdateDetectorModelResponse>("UpdateDetectorModelResponse")({detectorModelConfiguration: S.optional(DetectorModelConfiguration)}) {}
export class UpdateInputResponse extends S.Class<UpdateInputResponse>("UpdateInputResponse")({inputConfiguration: S.optional(InputConfiguration)}) {}
export class AnalysisResultLocation extends S.Class<AnalysisResultLocation>("AnalysisResultLocation")({path: S.optional(S.String)}) {}
export const AnalysisResultLocations = S.Array(AnalysisResultLocation);
export class IotSiteWiseInputIdentifier extends S.Class<IotSiteWiseInputIdentifier>("IotSiteWiseInputIdentifier")({iotSiteWiseAssetModelPropertyIdentifier: S.optional(IotSiteWiseAssetModelPropertyIdentifier)}) {}
export class AnalysisResult extends S.Class<AnalysisResult>("AnalysisResult")({type: S.optional(S.String), level: S.optional(S.String), message: S.optional(S.String), locations: S.optional(AnalysisResultLocations)}) {}
export const AnalysisResults = S.Array(AnalysisResult);
export class InputIdentifier extends S.Class<InputIdentifier>("InputIdentifier")({iotEventsInputIdentifier: S.optional(IotEventsInputIdentifier), iotSiteWiseInputIdentifier: S.optional(IotSiteWiseInputIdentifier)}) {}
export class CreateInputResponse extends S.Class<CreateInputResponse>("CreateInputResponse")({inputConfiguration: S.optional(InputConfiguration)}) {}
export class GetDetectorModelAnalysisResultsResponse extends S.Class<GetDetectorModelAnalysisResultsResponse>("GetDetectorModelAnalysisResultsResponse")({analysisResults: S.optional(AnalysisResults), nextToken: S.optional(S.String)}) {}
export class ListInputRoutingsRequest extends S.Class<ListInputRoutingsRequest>("ListInputRoutingsRequest")({inputIdentifier: InputIdentifier, maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export class ResourceAlreadyExistsException extends S.Class<ResourceAlreadyExistsException>("ResourceAlreadyExistsException")({message: S.optional(S.String), resourceId: S.optional(S.String), resourceArn: S.optional(S.String)}) {}
export class RoutedResource extends S.Class<RoutedResource>("RoutedResource")({name: S.optional(S.String), arn: S.optional(S.String)}) {}
export const RoutedResources = S.Array(RoutedResource);
export class CreateAlarmModelRequest extends S.Class<CreateAlarmModelRequest>("CreateAlarmModelRequest")({alarmModelName: S.String, alarmModelDescription: S.optional(S.String), roleArn: S.String, tags: S.optional(Tags), key: S.optional(S.String), severity: S.optional(S.Number), alarmRule: AlarmRule, alarmNotification: S.optional(AlarmNotification), alarmEventActions: S.optional(AlarmEventActions), alarmCapabilities: S.optional(AlarmCapabilities)}) {}
export class ListInputRoutingsResponse extends S.Class<ListInputRoutingsResponse>("ListInputRoutingsResponse")({routedResources: S.optional(RoutedResources), nextToken: S.optional(S.String)}) {}
export class CreateAlarmModelResponse extends S.Class<CreateAlarmModelResponse>("CreateAlarmModelResponse")({creationTime: S.optional(S.Date), alarmModelArn: S.optional(S.String), alarmModelVersion: S.optional(S.String), lastUpdateTime: S.optional(S.Date), status: S.optional(S.String)}) {}
export class CreateDetectorModelRequest extends S.Class<CreateDetectorModelRequest>("CreateDetectorModelRequest")({detectorModelName: S.String, detectorModelDefinition: DetectorModelDefinition, detectorModelDescription: S.optional(S.String), key: S.optional(S.String), roleArn: S.String, tags: S.optional(Tags), evaluationMethod: S.optional(S.String)}) {}
export class CreateDetectorModelResponse extends S.Class<CreateDetectorModelResponse>("CreateDetectorModelResponse")({detectorModelConfiguration: S.optional(DetectorModelConfiguration)}) {}

//# Errors
export class InternalFailureExceptionError extends S.TaggedError<InternalFailureExceptionError>()("InternalFailureException", InternalFailureException.fields) {};
export class InvalidRequestExceptionError extends S.TaggedError<InvalidRequestExceptionError>()("InvalidRequestException", InvalidRequestException.fields) {};
export class ResourceInUseExceptionError extends S.TaggedError<ResourceInUseExceptionError>()("ResourceInUseException", ResourceInUseException.fields) {};
export class ResourceNotFoundExceptionError extends S.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ServiceUnavailableExceptionError extends S.TaggedError<ServiceUnavailableExceptionError>()("ServiceUnavailableException", ServiceUnavailableException.fields) {};
export class ThrottlingExceptionError extends S.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class LimitExceededExceptionError extends S.TaggedError<LimitExceededExceptionError>()("LimitExceededException", LimitExceededException.fields) {};
export class UnsupportedOperationExceptionError extends S.TaggedError<UnsupportedOperationExceptionError>()("UnsupportedOperationException", UnsupportedOperationException.fields) {};
export class ResourceAlreadyExistsExceptionError extends S.TaggedError<ResourceAlreadyExistsExceptionError>()("ResourceAlreadyExistsException", ResourceAlreadyExistsException.fields) {};

//# Operations
export const deleteDetectorModel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/detector-models/{detectorModelName}", method: "DELETE", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.DeleteDetectorModel" }, DeleteDetectorModelRequest, DeleteDetectorModelResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceInUseExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteInput = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/inputs/{inputName}", method: "DELETE", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.DeleteInput" }, DeleteInputRequest, DeleteInputResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceInUseExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAlarmModel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/alarm-models/{alarmModelName}", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.DescribeAlarmModel" }, DescribeAlarmModelRequest, DescribeAlarmModelResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeDetectorModelAnalysis = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/analysis/detector-models/{analysisId}", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.DescribeDetectorModelAnalysis" }, DescribeDetectorModelAnalysisRequest, DescribeDetectorModelAnalysisResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/tags", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceInUseExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const startDetectorModelAnalysis = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/analysis/detector-models", method: "POST", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.StartDetectorModelAnalysis" }, StartDetectorModelAnalysisRequest, StartDetectorModelAnalysisResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/tags", method: "POST", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.TagResource" }, TagResourceRequest, TagResourceResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError, ResourceInUseExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/tags", method: "DELETE", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceInUseExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAlarmModel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/alarm-models/{alarmModelName}", method: "POST", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.UpdateAlarmModel" }, UpdateAlarmModelRequest, UpdateAlarmModelResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceInUseExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAlarmModel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/alarm-models/{alarmModelName}", method: "DELETE", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.DeleteAlarmModel" }, DeleteAlarmModelRequest, DeleteAlarmModelResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceInUseExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeDetectorModel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/detector-models/{detectorModelName}", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.DescribeDetectorModel" }, DescribeDetectorModelRequest, DescribeDetectorModelResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeInput = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/inputs/{inputName}", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.DescribeInput" }, DescribeInputRequest, DescribeInputResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeLoggingOptions = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/logging", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.DescribeLoggingOptions" }, DescribeLoggingOptionsRequest, DescribeLoggingOptionsResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnsupportedOperationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAlarmModels = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/alarm-models", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.ListAlarmModels" }, ListAlarmModelsRequest, ListAlarmModelsResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAlarmModelVersions = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/alarm-models/{alarmModelName}/versions", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.ListAlarmModelVersions" }, ListAlarmModelVersionsRequest, ListAlarmModelVersionsResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listDetectorModels = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/detector-models", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.ListDetectorModels" }, ListDetectorModelsRequest, ListDetectorModelsResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listDetectorModelVersions = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/detector-models/{detectorModelName}/versions", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.ListDetectorModelVersions" }, ListDetectorModelVersionsRequest, ListDetectorModelVersionsResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listInputs = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/inputs", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.ListInputs" }, ListInputsRequest, ListInputsResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putLoggingOptions = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/logging", method: "PUT", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.PutLoggingOptions" }, PutLoggingOptionsRequest, S.Struct({}), [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceInUseExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError, UnsupportedOperationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateDetectorModel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/detector-models/{detectorModelName}", method: "POST", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.UpdateDetectorModel" }, UpdateDetectorModelRequest, UpdateDetectorModelResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceInUseExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateInput = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/inputs/{inputName}", method: "PUT", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.UpdateInput" }, UpdateInputRequest, UpdateInputResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceInUseExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getDetectorModelAnalysisResults = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/analysis/detector-models/{analysisId}/results", method: "GET", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.GetDetectorModelAnalysisResults" }, GetDetectorModelAnalysisResultsRequest, GetDetectorModelAnalysisResultsResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createInput = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/inputs", method: "POST", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.CreateInput" }, CreateInputRequest, CreateInputResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceAlreadyExistsExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listInputRoutings = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/input-routings", method: "POST", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.ListInputRoutings" }, ListInputRoutingsRequest, ListInputRoutingsResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createAlarmModel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/alarm-models", method: "POST", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.CreateAlarmModel" }, CreateAlarmModelRequest, CreateAlarmModelResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError, ResourceAlreadyExistsExceptionError, ResourceInUseExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createDetectorModel = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-07-27", uri: "/detector-models", method: "POST", sdkId: "IoT Events", sigV4ServiceName: "iotevents", name: "IotColumboService.CreateDetectorModel" }, CreateDetectorModelRequest, CreateDetectorModelResponse, [InternalFailureExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError, ResourceAlreadyExistsExceptionError, ResourceInUseExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
