import { Schema} from "effect"
import { FormatAwsJSON10Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import { Operation, Path, Header, StreamBody, Body } from "../schema-helpers.ts";

//# Schemas
export class GetEncryptionConfigurationRequest extends Schema.Class<GetEncryptionConfigurationRequest>("GetEncryptionConfigurationRequest")({}) {}
export class GetLoggingOptionsRequest extends Schema.Class<GetLoggingOptionsRequest>("GetLoggingOptionsRequest")({}) {}
export class GetRegisterAccountStatusRequest extends Schema.Class<GetRegisterAccountStatusRequest>("GetRegisterAccountStatusRequest")({}) {}
export const TagKeyList = Schema.Array(Schema.String);
export class GetEncryptionConfigurationResponse extends Schema.Class<GetEncryptionConfigurationResponse>("GetEncryptionConfigurationResponse")({kmsKeyId: Schema.optional(Schema.String), encryptionStatus: Schema.String, encryptionType: Schema.String, errorMessage: Schema.optional(Schema.String), creationTime: Schema.optional(Schema.Date), lastModificationTime: Schema.optional(Schema.Date)}) {}
export class GetVehicleStatusRequest extends Schema.Class<GetVehicleStatusRequest>("GetVehicleStatusRequest")({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), vehicleName: Schema.String}) {}
export class ListTagsForResourceRequest extends Schema.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceARN: Schema.String}) {}
export class PutEncryptionConfigurationRequest extends Schema.Class<PutEncryptionConfigurationRequest>("PutEncryptionConfigurationRequest")({kmsKeyId: Schema.optional(Schema.String), encryptionType: Schema.String}) {}
export class CloudWatchLogDeliveryOptions extends Schema.Class<CloudWatchLogDeliveryOptions>("CloudWatchLogDeliveryOptions")({logType: Schema.String, logGroupName: Schema.optional(Schema.String)}) {}
export class PutLoggingOptionsRequest extends Schema.Class<PutLoggingOptionsRequest>("PutLoggingOptionsRequest")({cloudWatchLogDelivery: CloudWatchLogDeliveryOptions}) {}
export class PutLoggingOptionsResponse extends Schema.Class<PutLoggingOptionsResponse>("PutLoggingOptionsResponse")({}) {}
export class UntagResourceRequest extends Schema.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceARN: Schema.String, TagKeys: TagKeyList}) {}
export class UntagResourceResponse extends Schema.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export const StateTemplateAssociationIdentifiers = Schema.Array(Schema.String);
export const attributesMap = Schema.Record({key: Schema.String, value: Schema.String});
export class TimePeriod extends Schema.Class<TimePeriod>("TimePeriod")({unit: Schema.String, value: Schema.Number}) {}
export class PeriodicStateTemplateUpdateStrategy extends Schema.Class<PeriodicStateTemplateUpdateStrategy>("PeriodicStateTemplateUpdateStrategy")({stateTemplateUpdateRate: TimePeriod}) {}
export class OnChangeStateTemplateUpdateStrategy extends Schema.Class<OnChangeStateTemplateUpdateStrategy>("OnChangeStateTemplateUpdateStrategy")({}) {}
export const StateTemplateUpdateStrategy = Schema.Union(PeriodicStateTemplateUpdateStrategy, OnChangeStateTemplateUpdateStrategy);
export class StateTemplateAssociation extends Schema.Class<StateTemplateAssociation>("StateTemplateAssociation")({identifier: Schema.String, stateTemplateUpdateStrategy: StateTemplateUpdateStrategy}) {}
export const StateTemplateAssociations = Schema.Array(StateTemplateAssociation);
export class UpdateVehicleRequestItem extends Schema.Class<UpdateVehicleRequestItem>("UpdateVehicleRequestItem")({vehicleName: Schema.String, modelManifestArn: Schema.optional(Schema.String), decoderManifestArn: Schema.optional(Schema.String), attributes: Schema.optional(attributesMap), attributeUpdateMode: Schema.optional(Schema.String), stateTemplatesToAdd: Schema.optional(StateTemplateAssociations), stateTemplatesToRemove: Schema.optional(StateTemplateAssociationIdentifiers), stateTemplatesToUpdate: Schema.optional(StateTemplateAssociations)}) {}
export const updateVehicleRequestItems = Schema.Array(UpdateVehicleRequestItem);
export class TimestreamRegistrationResponse extends Schema.Class<TimestreamRegistrationResponse>("TimestreamRegistrationResponse")({timestreamDatabaseName: Schema.String, timestreamTableName: Schema.String, timestreamDatabaseArn: Schema.optional(Schema.String), timestreamTableArn: Schema.optional(Schema.String), registrationStatus: Schema.String, errorMessage: Schema.optional(Schema.String)}) {}
export class IamRegistrationResponse extends Schema.Class<IamRegistrationResponse>("IamRegistrationResponse")({roleArn: Schema.String, registrationStatus: Schema.String, errorMessage: Schema.optional(Schema.String)}) {}
export class TimestreamResources extends Schema.Class<TimestreamResources>("TimestreamResources")({timestreamDatabaseName: Schema.String, timestreamTableName: Schema.String}) {}
export class IamResources extends Schema.Class<IamResources>("IamResources")({roleArn: Schema.String}) {}
export class Tag extends Schema.Class<Tag>("Tag")({Key: Schema.String, Value: Schema.String}) {}
export const TagList = Schema.Array(Tag);
export class BatchUpdateVehicleRequest extends Schema.Class<BatchUpdateVehicleRequest>("BatchUpdateVehicleRequest")({vehicles: updateVehicleRequestItems}) {}
export class AccessDeniedException extends Schema.Class<AccessDeniedException>("AccessDeniedException")({message: Schema.String}) {}
export class GetLoggingOptionsResponse extends Schema.Class<GetLoggingOptionsResponse>("GetLoggingOptionsResponse")({cloudWatchLogDelivery: CloudWatchLogDeliveryOptions}) {}
export class GetRegisterAccountStatusResponse extends Schema.Class<GetRegisterAccountStatusResponse>("GetRegisterAccountStatusResponse")({customerAccountId: Schema.String, accountStatus: Schema.String, timestreamRegistrationResponse: Schema.optional(TimestreamRegistrationResponse), iamRegistrationResponse: IamRegistrationResponse, creationTime: Schema.Date, lastModificationTime: Schema.Date}) {}
export class ListTagsForResourceResponse extends Schema.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: Schema.optional(TagList)}) {}
export class PutEncryptionConfigurationResponse extends Schema.Class<PutEncryptionConfigurationResponse>("PutEncryptionConfigurationResponse")({kmsKeyId: Schema.optional(Schema.String), encryptionStatus: Schema.String, encryptionType: Schema.String}) {}
export class ConflictException extends Schema.Class<ConflictException>("ConflictException")({message: Schema.String, resource: Schema.String, resourceType: Schema.String}) {}
export class RegisterAccountRequest extends Schema.Class<RegisterAccountRequest>("RegisterAccountRequest")({timestreamResources: Schema.optional(TimestreamResources), iamResources: Schema.optional(IamResources)}) {}
export class TagResourceRequest extends Schema.Class<TagResourceRequest>("TagResourceRequest")({ResourceARN: Schema.String, Tags: TagList}) {}
export class TagResourceResponse extends Schema.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class InternalServerException extends Schema.Class<InternalServerException>("InternalServerException")({message: Schema.String, retryAfterSeconds: Schema.optional(Header("Retry-After", Schema.Number))}) {}
export class VehicleStatus extends Schema.Class<VehicleStatus>("VehicleStatus")({campaignName: Schema.optional(Schema.String), vehicleName: Schema.optional(Schema.String), status: Schema.optional(Schema.String)}) {}
export const VehicleStatusList = Schema.Array(VehicleStatus);
export class ResourceNotFoundException extends Schema.Class<ResourceNotFoundException>("ResourceNotFoundException")({message: Schema.String, resourceId: Schema.String, resourceType: Schema.String}) {}
export class ThrottlingException extends Schema.Class<ThrottlingException>("ThrottlingException")({message: Schema.String, quotaCode: Schema.optional(Schema.String), serviceCode: Schema.optional(Schema.String), retryAfterSeconds: Schema.optional(Header("Retry-After", Schema.Number))}) {}
export class GetVehicleStatusResponse extends Schema.Class<GetVehicleStatusResponse>("GetVehicleStatusResponse")({campaigns: Schema.optional(VehicleStatusList), nextToken: Schema.optional(Schema.String)}) {}
export class RegisterAccountResponse extends Schema.Class<RegisterAccountResponse>("RegisterAccountResponse")({registerAccountStatus: Schema.String, timestreamResources: Schema.optional(TimestreamResources), iamResources: IamResources, creationTime: Schema.Date, lastModificationTime: Schema.Date}) {}
export class UpdateVehicleResponseItem extends Schema.Class<UpdateVehicleResponseItem>("UpdateVehicleResponseItem")({vehicleName: Schema.optional(Schema.String), arn: Schema.optional(Schema.String)}) {}
export const updateVehicleResponseItems = Schema.Array(UpdateVehicleResponseItem);
export class UpdateVehicleError extends Schema.Class<UpdateVehicleError>("UpdateVehicleError")({vehicleName: Schema.optional(Schema.String), code: Schema.optional(Schema.Number), message: Schema.optional(Schema.String)}) {}
export const updateVehicleErrors = Schema.Array(UpdateVehicleError);
export class ValidationExceptionField extends Schema.Class<ValidationExceptionField>("ValidationExceptionField")({name: Schema.String, message: Schema.String}) {}
export const ValidationExceptionFieldList = Schema.Array(ValidationExceptionField);
export class BatchUpdateVehicleResponse extends Schema.Class<BatchUpdateVehicleResponse>("BatchUpdateVehicleResponse")({vehicles: Schema.optional(updateVehicleResponseItems), errors: Schema.optional(updateVehicleErrors)}) {}
export class ValidationException extends Schema.Class<ValidationException>("ValidationException")({message: Schema.String, reason: Schema.optional(Schema.String), fieldList: Schema.optional(ValidationExceptionFieldList)}) {}
export class LimitExceededException extends Schema.Class<LimitExceededException>("LimitExceededException")({message: Schema.String, resourceId: Schema.String, resourceType: Schema.String}) {}
export class CreateVehicleRequestItem extends Schema.Class<CreateVehicleRequestItem>("CreateVehicleRequestItem")({vehicleName: Schema.String, modelManifestArn: Schema.String, decoderManifestArn: Schema.String, attributes: Schema.optional(attributesMap), associationBehavior: Schema.optional(Schema.String), tags: Schema.optional(TagList), stateTemplates: Schema.optional(StateTemplateAssociations)}) {}
export const createVehicleRequestItems = Schema.Array(CreateVehicleRequestItem);
export class BatchCreateVehicleRequest extends Schema.Class<BatchCreateVehicleRequest>("BatchCreateVehicleRequest")({vehicles: createVehicleRequestItems}) {}
export class CreateVehicleResponseItem extends Schema.Class<CreateVehicleResponseItem>("CreateVehicleResponseItem")({vehicleName: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), thingArn: Schema.optional(Schema.String)}) {}
export const createVehicleResponses = Schema.Array(CreateVehicleResponseItem);
export class CreateVehicleError extends Schema.Class<CreateVehicleError>("CreateVehicleError")({vehicleName: Schema.optional(Schema.String), code: Schema.optional(Schema.String), message: Schema.optional(Schema.String)}) {}
export const createVehicleErrors = Schema.Array(CreateVehicleError);
export class BatchCreateVehicleResponse extends Schema.Class<BatchCreateVehicleResponse>("BatchCreateVehicleResponse")({vehicles: Schema.optional(createVehicleResponses), errors: Schema.optional(createVehicleErrors)}) {}

//# Errors
export class AccessDeniedExceptionError extends Schema.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class InternalServerExceptionError extends Schema.TaggedError<InternalServerExceptionError>()("InternalServerException", InternalServerException.fields) {};
export class ResourceNotFoundExceptionError extends Schema.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ThrottlingExceptionError extends Schema.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class ValidationExceptionError extends Schema.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};
export class ConflictExceptionError extends Schema.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class LimitExceededExceptionError extends Schema.TaggedError<LimitExceededExceptionError>()("LimitExceededException", LimitExceededException.fields) {};

//# Operations
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/tags", method: "GET", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const putEncryptionConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/encryptionConfiguration", method: "POST", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.PutEncryptionConfiguration" }, PutEncryptionConfigurationRequest, PutEncryptionConfigurationResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const putLoggingOptions = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/loggingOptions", method: "PUT", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.PutLoggingOptions" }, PutLoggingOptionsRequest, PutLoggingOptionsResponse, [AccessDeniedExceptionError, ConflictExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/tags", method: "POST", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.TagResource" }, TagResourceRequest, TagResourceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/tags", method: "DELETE", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getEncryptionConfiguration = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/encryptionConfiguration", method: "GET", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.GetEncryptionConfiguration" }, GetEncryptionConfigurationRequest, GetEncryptionConfigurationResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getLoggingOptions = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/loggingOptions", method: "GET", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.GetLoggingOptions" }, GetLoggingOptionsRequest, GetLoggingOptionsResponse, [AccessDeniedExceptionError, ThrottlingExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getVehicleStatus = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/vehicles/{vehicleName}/status", method: "GET", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.GetVehicleStatus" }, GetVehicleStatusRequest, GetVehicleStatusResponse, [AccessDeniedExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const registerAccount = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/account/registration", method: "POST", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.RegisterAccount" }, RegisterAccountRequest, RegisterAccountResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getRegisterAccountStatus = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/account/registration_status", method: "GET", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.GetRegisterAccountStatus" }, GetRegisterAccountStatusRequest, GetRegisterAccountStatusResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const batchUpdateVehicle = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/vehicles", method: "PUT", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.BatchUpdateVehicle" }, BatchUpdateVehicleRequest, BatchUpdateVehicleResponse, [AccessDeniedExceptionError, InternalServerExceptionError, LimitExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
export const batchCreateVehicle = /*#__PURE__*/ makeOperation(() => Operation({ version: "2021-06-17", uri: "/vehicles", method: "POST", sdkId: "IoTFleetWise", sigV4ServiceName: "iotfleetwise", name: "IoTAutobahnControlPlane.BatchCreateVehicle" }, BatchCreateVehicleRequest, BatchCreateVehicleResponse, [AccessDeniedExceptionError, InternalServerExceptionError, LimitExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON10Request, FormatJSONResponse, FormatAwsRestJSONError);
