import { Schema} from "effect"
import { FormatXMLRequest, FormatXMLResponse, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
const GetServiceSettingsRequest = Schema.Struct({})
const StringList = Schema.Array(Schema.String)
const SubscriptionProviderSourceList = Schema.Array(Schema.String)
const TagKeyList = Schema.Array(Schema.String)
const DeregisterSubscriptionProviderRequest = Schema.Struct({SubscriptionProviderArn: Schema.String})
const DeregisterSubscriptionProviderResponse = Schema.Struct({})
const GetRegisteredSubscriptionProviderRequest = Schema.Struct({SubscriptionProviderArn: Schema.String})
const ListLinuxSubscriptionsRequest = Schema.Struct({Filters: Schema.optional(FilterList), MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)})
const ListRegisteredSubscriptionProvidersRequest = Schema.Struct({SubscriptionProviderSources: Schema.optional(SubscriptionProviderSourceList), MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)})
const ListTagsForResourceRequest = Schema.Struct({resourceArn: Schema.String})
const TagResourceRequest = Schema.Struct({resourceArn: Schema.String, tags: Tags})
const TagResourceResponse = Schema.Struct({})
const UntagResourceRequest = Schema.Struct({resourceArn: Schema.String, tagKeys: TagKeyList})
const UntagResourceResponse = Schema.Struct({})
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "UntagResource" }, UntagResourceRequest, UntagResourceResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateServiceSettingsRequest = Schema.Struct({LinuxSubscriptionsDiscovery: Schema.String, LinuxSubscriptionsDiscoverySettings: LinuxSubscriptionsDiscoverySettings, AllowUpdate: Schema.optional(Schema.Boolean)})
const LinuxSubscriptionsDiscoverySettings = Schema.Struct({SourceRegions: StringList, OrganizationIntegration: Schema.String})
const StringMap = Schema.Record({key: Schema.String, value: Schema.String})
const Filter = Schema.Struct({Name: Schema.optional(Schema.String), Values: Schema.optional(StringList), Operator: Schema.optional(Schema.String)})
const FilterList = Schema.Array(Filter)
const Tags = Schema.Record({key: Schema.String, value: Schema.String})
const InternalServerException = Schema.Struct({message: Schema.optional(Schema.String)})
const GetRegisteredSubscriptionProviderResponse = Schema.Struct({SubscriptionProviderArn: Schema.optional(Schema.String), SubscriptionProviderSource: Schema.optional(Schema.String), SecretArn: Schema.optional(Schema.String), SubscriptionProviderStatus: Schema.optional(Schema.String), SubscriptionProviderStatusMessage: Schema.optional(Schema.String), LastSuccessfulDataRetrievalTime: Schema.optional(Schema.String)})
const GetServiceSettingsResponse = Schema.Struct({LinuxSubscriptionsDiscovery: Schema.optional(Schema.String), LinuxSubscriptionsDiscoverySettings: Schema.optional(LinuxSubscriptionsDiscoverySettings), Status: Schema.optional(Schema.String), StatusMessage: Schema.optional(StringMap), HomeRegions: Schema.optional(StringList)})
export const GetServiceSettings = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/subscription/GetServiceSettings", method: "POST", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "GetServiceSettings" }, GetServiceSettingsRequest, GetServiceSettingsResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListLinuxSubscriptionInstancesRequest = Schema.Struct({Filters: Schema.optional(FilterList), MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)})
const ListTagsForResourceResponse = Schema.Struct({tags: Schema.optional(Tags)})
export const ListTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "GET", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const RegisterSubscriptionProviderRequest = Schema.Struct({SubscriptionProviderSource: Schema.String, SecretArn: Schema.String, Tags: Schema.optional(Tags)})
const ResourceNotFoundException = Schema.Struct({message: Schema.optional(Schema.String)})
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "PUT", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "TagResource" }, TagResourceRequest, TagResourceResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateServiceSettingsResponse = Schema.Struct({LinuxSubscriptionsDiscovery: Schema.optional(Schema.String), LinuxSubscriptionsDiscoverySettings: Schema.optional(LinuxSubscriptionsDiscoverySettings), Status: Schema.optional(Schema.String), StatusMessage: Schema.optional(StringMap), HomeRegions: Schema.optional(StringList)})
export const UpdateServiceSettings = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/subscription/UpdateServiceSettings", method: "POST", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "UpdateServiceSettings" }, UpdateServiceSettingsRequest, UpdateServiceSettingsResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Subscription = Schema.Struct({Name: Schema.optional(Schema.String), Type: Schema.optional(Schema.String), InstanceCount: Schema.optional(Schema.Number)})
const SubscriptionList = Schema.Array(Subscription)
const RegisteredSubscriptionProvider = Schema.Struct({SubscriptionProviderArn: Schema.optional(Schema.String), SubscriptionProviderSource: Schema.optional(Schema.String), SecretArn: Schema.optional(Schema.String), SubscriptionProviderStatus: Schema.optional(Schema.String), SubscriptionProviderStatusMessage: Schema.optional(Schema.String), LastSuccessfulDataRetrievalTime: Schema.optional(Schema.String)})
const RegisteredSubscriptionProviderList = Schema.Array(RegisteredSubscriptionProvider)
const ThrottlingException = Schema.Struct({message: Schema.optional(Schema.String)})
export const DeregisterSubscriptionProvider = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/subscription/DeregisterSubscriptionProvider", method: "POST", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "DeregisterSubscriptionProvider" }, DeregisterSubscriptionProviderRequest, DeregisterSubscriptionProviderResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ValidationException = Schema.Struct({message: Schema.optional(Schema.String)})
export const GetRegisteredSubscriptionProvider = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/subscription/GetRegisteredSubscriptionProvider", method: "POST", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "GetRegisteredSubscriptionProvider" }, GetRegisteredSubscriptionProviderRequest, GetRegisteredSubscriptionProviderResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListLinuxSubscriptionsResponse = Schema.Struct({Subscriptions: Schema.optional(SubscriptionList), NextToken: Schema.optional(Schema.String)})
export const ListLinuxSubscriptions = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/subscription/ListLinuxSubscriptions", method: "POST", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "ListLinuxSubscriptions" }, ListLinuxSubscriptionsRequest, ListLinuxSubscriptionsResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListRegisteredSubscriptionProvidersResponse = Schema.Struct({RegisteredSubscriptionProviders: Schema.optional(RegisteredSubscriptionProviderList), NextToken: Schema.optional(Schema.String)})
export const ListRegisteredSubscriptionProviders = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/subscription/ListRegisteredSubscriptionProviders", method: "POST", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "ListRegisteredSubscriptionProviders" }, ListRegisteredSubscriptionProvidersRequest, ListRegisteredSubscriptionProvidersResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const RegisterSubscriptionProviderResponse = Schema.Struct({SubscriptionProviderSource: Schema.optional(Schema.String), SubscriptionProviderArn: Schema.optional(Schema.String), SubscriptionProviderStatus: Schema.optional(Schema.String)})
export const RegisterSubscriptionProvider = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/subscription/RegisterSubscriptionProvider", method: "POST", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "RegisterSubscriptionProvider" }, RegisterSubscriptionProviderRequest, RegisterSubscriptionProviderResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ProductCodeList = Schema.Array(Schema.String)
const Instance = Schema.Struct({AmiId: Schema.optional(Schema.String), InstanceID: Schema.optional(Schema.String), InstanceType: Schema.optional(Schema.String), AccountID: Schema.optional(Schema.String), Status: Schema.optional(Schema.String), Region: Schema.optional(Schema.String), UsageOperation: Schema.optional(Schema.String), ProductCode: Schema.optional(ProductCodeList), LastUpdatedTime: Schema.optional(Schema.String), SubscriptionName: Schema.optional(Schema.String), OsVersion: Schema.optional(Schema.String), SubscriptionProviderCreateTime: Schema.optional(Schema.String), SubscriptionProviderUpdateTime: Schema.optional(Schema.String), DualSubscription: Schema.optional(Schema.String), RegisteredWithSubscriptionProvider: Schema.optional(Schema.String)})
const InstanceList = Schema.Array(Instance)
const ListLinuxSubscriptionInstancesResponse = Schema.Struct({Instances: Schema.optional(InstanceList), NextToken: Schema.optional(Schema.String)})
export const ListLinuxSubscriptionInstances = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/subscription/ListLinuxSubscriptionInstances", method: "POST", sdkId: "License Manager Linux Subscriptions", sigV4ServiceName: "license-manager-linux-subscriptions", name: "ListLinuxSubscriptionInstances" }, ListLinuxSubscriptionInstancesRequest, ListLinuxSubscriptionInstancesResponse, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
