import * as S from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export class GetServiceSettingsRequest extends S.Class<GetServiceSettingsRequest>("GetServiceSettingsRequest")({}) {}
export const PrincipalArnList = S.Array(S.String);
export const AllowedOperationList = S.Array(S.String);
export const LicenseAssetRulesetArnList = S.Array(S.String);
export const StringList = S.Array(S.String);
export const ReportTypeList = S.Array(S.String);
export const ArnList = S.Array(S.String);
export const MaxSize3StringList = S.Array(S.String);
export const FilterValues = S.Array(S.String);
export class Filter extends S.Class<Filter>("Filter")({Name: S.optional(S.String), Values: S.optional(FilterValues)}) {}
export const Filters = S.Array(Filter);
export const TagKeyList = S.Array(S.String);
export class AcceptGrantRequest extends S.Class<AcceptGrantRequest>("AcceptGrantRequest")({GrantArn: S.String}) {}
export class CheckInLicenseRequest extends S.Class<CheckInLicenseRequest>("CheckInLicenseRequest")({LicenseConsumptionToken: S.String, Beneficiary: S.optional(S.String)}) {}
export class CheckInLicenseResponse extends S.Class<CheckInLicenseResponse>("CheckInLicenseResponse")({}) {}
export class EntitlementData extends S.Class<EntitlementData>("EntitlementData")({Name: S.String, Value: S.optional(S.String), Unit: S.String}) {}
export const EntitlementDataList = S.Array(EntitlementData);
export class CheckoutLicenseRequest extends S.Class<CheckoutLicenseRequest>("CheckoutLicenseRequest")({ProductSKU: S.String, CheckoutType: S.String, KeyFingerprint: S.String, Entitlements: EntitlementDataList, ClientToken: S.String, Beneficiary: S.optional(S.String), NodeId: S.optional(S.String)}) {}
export class Issuer extends S.Class<Issuer>("Issuer")({Name: S.String, SignKey: S.optional(S.String)}) {}
export class DatetimeRange extends S.Class<DatetimeRange>("DatetimeRange")({Begin: S.String, End: S.optional(S.String)}) {}
export class Metadata extends S.Class<Metadata>("Metadata")({Name: S.optional(S.String), Value: S.optional(S.String)}) {}
export const MetadataList = S.Array(Metadata);
export class Entitlement extends S.Class<Entitlement>("Entitlement")({Name: S.String, Value: S.optional(S.String), MaxCount: S.optional(S.Number), Overage: S.optional(S.Boolean), Unit: S.String, AllowCheckIn: S.optional(S.Boolean)}) {}
export const EntitlementList = S.Array(Entitlement);
export class ProvisionalConfiguration extends S.Class<ProvisionalConfiguration>("ProvisionalConfiguration")({MaxTimeToLiveInMinutes: S.Number}) {}
export class BorrowConfiguration extends S.Class<BorrowConfiguration>("BorrowConfiguration")({AllowEarlyCheckIn: S.Boolean, MaxTimeToLiveInMinutes: S.Number}) {}
export class ConsumptionConfiguration extends S.Class<ConsumptionConfiguration>("ConsumptionConfiguration")({RenewType: S.optional(S.String), ProvisionalConfiguration: S.optional(ProvisionalConfiguration), BorrowConfiguration: S.optional(BorrowConfiguration)}) {}
export class CreateLicenseVersionRequest extends S.Class<CreateLicenseVersionRequest>("CreateLicenseVersionRequest")({LicenseArn: S.String, LicenseName: S.String, ProductName: S.String, Issuer: Issuer, HomeRegion: S.String, Validity: DatetimeRange, LicenseMetadata: S.optional(MetadataList), Entitlements: EntitlementList, ConsumptionConfiguration: ConsumptionConfiguration, Status: S.String, ClientToken: S.String, SourceVersion: S.optional(S.String)}) {}
export class CreateTokenRequest extends S.Class<CreateTokenRequest>("CreateTokenRequest")({LicenseArn: S.String, RoleArns: S.optional(ArnList), ExpirationInDays: S.optional(S.Number), TokenProperties: S.optional(MaxSize3StringList), ClientToken: S.String}) {}
export class DeleteGrantRequest extends S.Class<DeleteGrantRequest>("DeleteGrantRequest")({GrantArn: S.String, StatusReason: S.optional(S.String), Version: S.String}) {}
export class DeleteLicenseRequest extends S.Class<DeleteLicenseRequest>("DeleteLicenseRequest")({LicenseArn: S.String, SourceVersion: S.String}) {}
export class DeleteLicenseAssetGroupRequest extends S.Class<DeleteLicenseAssetGroupRequest>("DeleteLicenseAssetGroupRequest")({LicenseAssetGroupArn: S.String}) {}
export class DeleteLicenseAssetRulesetRequest extends S.Class<DeleteLicenseAssetRulesetRequest>("DeleteLicenseAssetRulesetRequest")({LicenseAssetRulesetArn: S.String}) {}
export class DeleteLicenseAssetRulesetResponse extends S.Class<DeleteLicenseAssetRulesetResponse>("DeleteLicenseAssetRulesetResponse")({}) {}
export class DeleteLicenseConfigurationRequest extends S.Class<DeleteLicenseConfigurationRequest>("DeleteLicenseConfigurationRequest")({LicenseConfigurationArn: S.String}) {}
export class DeleteLicenseConfigurationResponse extends S.Class<DeleteLicenseConfigurationResponse>("DeleteLicenseConfigurationResponse")({}) {}
export class DeleteLicenseManagerReportGeneratorRequest extends S.Class<DeleteLicenseManagerReportGeneratorRequest>("DeleteLicenseManagerReportGeneratorRequest")({LicenseManagerReportGeneratorArn: S.String}) {}
export class DeleteLicenseManagerReportGeneratorResponse extends S.Class<DeleteLicenseManagerReportGeneratorResponse>("DeleteLicenseManagerReportGeneratorResponse")({}) {}
export class DeleteTokenRequest extends S.Class<DeleteTokenRequest>("DeleteTokenRequest")({TokenId: S.String}) {}
export class DeleteTokenResponse extends S.Class<DeleteTokenResponse>("DeleteTokenResponse")({}) {}
export class ExtendLicenseConsumptionRequest extends S.Class<ExtendLicenseConsumptionRequest>("ExtendLicenseConsumptionRequest")({LicenseConsumptionToken: S.String, DryRun: S.optional(S.Boolean)}) {}
export class GetAccessTokenRequest extends S.Class<GetAccessTokenRequest>("GetAccessTokenRequest")({Token: S.String, TokenProperties: S.optional(MaxSize3StringList)}) {}
export class GetGrantRequest extends S.Class<GetGrantRequest>("GetGrantRequest")({GrantArn: S.String, Version: S.optional(S.String)}) {}
export class GetLicenseRequest extends S.Class<GetLicenseRequest>("GetLicenseRequest")({LicenseArn: S.String, Version: S.optional(S.String)}) {}
export class GetLicenseAssetGroupRequest extends S.Class<GetLicenseAssetGroupRequest>("GetLicenseAssetGroupRequest")({LicenseAssetGroupArn: S.String}) {}
export class GetLicenseAssetRulesetRequest extends S.Class<GetLicenseAssetRulesetRequest>("GetLicenseAssetRulesetRequest")({LicenseAssetRulesetArn: S.String}) {}
export class GetLicenseConfigurationRequest extends S.Class<GetLicenseConfigurationRequest>("GetLicenseConfigurationRequest")({LicenseConfigurationArn: S.String}) {}
export class GetLicenseConversionTaskRequest extends S.Class<GetLicenseConversionTaskRequest>("GetLicenseConversionTaskRequest")({LicenseConversionTaskId: S.String}) {}
export class GetLicenseManagerReportGeneratorRequest extends S.Class<GetLicenseManagerReportGeneratorRequest>("GetLicenseManagerReportGeneratorRequest")({LicenseManagerReportGeneratorArn: S.String}) {}
export class GetLicenseUsageRequest extends S.Class<GetLicenseUsageRequest>("GetLicenseUsageRequest")({LicenseArn: S.String}) {}
export class ListAssetsForLicenseAssetGroupRequest extends S.Class<ListAssetsForLicenseAssetGroupRequest>("ListAssetsForLicenseAssetGroupRequest")({LicenseAssetGroupArn: S.String, AssetType: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListAssociationsForLicenseConfigurationRequest extends S.Class<ListAssociationsForLicenseConfigurationRequest>("ListAssociationsForLicenseConfigurationRequest")({LicenseConfigurationArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListFailuresForLicenseConfigurationOperationsRequest extends S.Class<ListFailuresForLicenseConfigurationOperationsRequest>("ListFailuresForLicenseConfigurationOperationsRequest")({LicenseConfigurationArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListLicenseAssetGroupsRequest extends S.Class<ListLicenseAssetGroupsRequest>("ListLicenseAssetGroupsRequest")({Filters: S.optional(Filters), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListLicenseAssetRulesetsRequest extends S.Class<ListLicenseAssetRulesetsRequest>("ListLicenseAssetRulesetsRequest")({Filters: S.optional(Filters), ShowAWSManagedLicenseAssetRulesets: S.optional(S.Boolean), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListLicenseConfigurationsRequest extends S.Class<ListLicenseConfigurationsRequest>("ListLicenseConfigurationsRequest")({LicenseConfigurationArns: S.optional(StringList), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), Filters: S.optional(Filters)}) {}
export class ListLicenseConfigurationsForOrganizationRequest extends S.Class<ListLicenseConfigurationsForOrganizationRequest>("ListLicenseConfigurationsForOrganizationRequest")({LicenseConfigurationArns: S.optional(StringList), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), Filters: S.optional(Filters)}) {}
export class ListLicenseConversionTasksRequest extends S.Class<ListLicenseConversionTasksRequest>("ListLicenseConversionTasksRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), Filters: S.optional(Filters)}) {}
export const FilterList = S.Array(Filter);
export class ListLicenseManagerReportGeneratorsRequest extends S.Class<ListLicenseManagerReportGeneratorsRequest>("ListLicenseManagerReportGeneratorsRequest")({Filters: S.optional(FilterList), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListLicensesRequest extends S.Class<ListLicensesRequest>("ListLicensesRequest")({LicenseArns: S.optional(ArnList), Filters: S.optional(FilterList), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListLicenseSpecificationsForResourceRequest extends S.Class<ListLicenseSpecificationsForResourceRequest>("ListLicenseSpecificationsForResourceRequest")({ResourceArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class ListLicenseVersionsRequest extends S.Class<ListLicenseVersionsRequest>("ListLicenseVersionsRequest")({LicenseArn: S.String, NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListReceivedGrantsRequest extends S.Class<ListReceivedGrantsRequest>("ListReceivedGrantsRequest")({GrantArns: S.optional(ArnList), Filters: S.optional(FilterList), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListReceivedGrantsForOrganizationRequest extends S.Class<ListReceivedGrantsForOrganizationRequest>("ListReceivedGrantsForOrganizationRequest")({LicenseArn: S.String, Filters: S.optional(FilterList), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListReceivedLicensesRequest extends S.Class<ListReceivedLicensesRequest>("ListReceivedLicensesRequest")({LicenseArns: S.optional(ArnList), Filters: S.optional(FilterList), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListReceivedLicensesForOrganizationRequest extends S.Class<ListReceivedLicensesForOrganizationRequest>("ListReceivedLicensesForOrganizationRequest")({Filters: S.optional(FilterList), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({ResourceArn: S.String}) {}
export class ListTokensRequest extends S.Class<ListTokensRequest>("ListTokensRequest")({TokenIds: S.optional(StringList), Filters: S.optional(FilterList), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListUsageForLicenseConfigurationRequest extends S.Class<ListUsageForLicenseConfigurationRequest>("ListUsageForLicenseConfigurationRequest")({LicenseConfigurationArn: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), Filters: S.optional(Filters)}) {}
export class RejectGrantRequest extends S.Class<RejectGrantRequest>("RejectGrantRequest")({GrantArn: S.String}) {}
export class Tag extends S.Class<Tag>("Tag")({Key: S.optional(S.String), Value: S.optional(S.String)}) {}
export const TagList = S.Array(Tag);
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({ResourceArn: S.String, Tags: TagList}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({ResourceArn: S.String, TagKeys: TagKeyList}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class LicenseAssetGroupConfiguration extends S.Class<LicenseAssetGroupConfiguration>("LicenseAssetGroupConfiguration")({UsageDimension: S.optional(S.String)}) {}
export const LicenseAssetGroupConfigurationList = S.Array(LicenseAssetGroupConfiguration);
export class LicenseAssetGroupProperty extends S.Class<LicenseAssetGroupProperty>("LicenseAssetGroupProperty")({Key: S.String, Value: S.String}) {}
export const LicenseAssetGroupPropertyList = S.Array(LicenseAssetGroupProperty);
export class UpdateLicenseAssetGroupRequest extends S.Class<UpdateLicenseAssetGroupRequest>("UpdateLicenseAssetGroupRequest")({Name: S.optional(S.String), Description: S.optional(S.String), LicenseAssetGroupConfigurations: S.optional(LicenseAssetGroupConfigurationList), AssociatedLicenseAssetRulesetARNs: LicenseAssetRulesetArnList, Properties: S.optional(LicenseAssetGroupPropertyList), LicenseAssetGroupArn: S.String, Status: S.optional(S.String), ClientToken: S.String}) {}
export class MatchingRuleStatement extends S.Class<MatchingRuleStatement>("MatchingRuleStatement")({KeyToMatch: S.String, Constraint: S.String, ValueToMatch: StringList}) {}
export const MatchingRuleStatementList = S.Array(MatchingRuleStatement);
export class ScriptRuleStatement extends S.Class<ScriptRuleStatement>("ScriptRuleStatement")({KeyToMatch: S.String, Script: S.String}) {}
export const ScriptRuleStatementList = S.Array(ScriptRuleStatement);
export class AndRuleStatement extends S.Class<AndRuleStatement>("AndRuleStatement")({MatchingRuleStatements: S.optional(MatchingRuleStatementList), ScriptRuleStatements: S.optional(ScriptRuleStatementList)}) {}
export class OrRuleStatement extends S.Class<OrRuleStatement>("OrRuleStatement")({MatchingRuleStatements: S.optional(MatchingRuleStatementList), ScriptRuleStatements: S.optional(ScriptRuleStatementList)}) {}
export class LicenseConfigurationRuleStatement extends S.Class<LicenseConfigurationRuleStatement>("LicenseConfigurationRuleStatement")({AndRuleStatement: S.optional(AndRuleStatement), OrRuleStatement: S.optional(OrRuleStatement), MatchingRuleStatement: S.optional(MatchingRuleStatement)}) {}
export class LicenseRuleStatement extends S.Class<LicenseRuleStatement>("LicenseRuleStatement")({AndRuleStatement: S.optional(AndRuleStatement), OrRuleStatement: S.optional(OrRuleStatement), MatchingRuleStatement: S.optional(MatchingRuleStatement)}) {}
export class InstanceRuleStatement extends S.Class<InstanceRuleStatement>("InstanceRuleStatement")({AndRuleStatement: S.optional(AndRuleStatement), OrRuleStatement: S.optional(OrRuleStatement), MatchingRuleStatement: S.optional(MatchingRuleStatement), ScriptRuleStatement: S.optional(ScriptRuleStatement)}) {}
export class RuleStatement extends S.Class<RuleStatement>("RuleStatement")({LicenseConfigurationRuleStatement: S.optional(LicenseConfigurationRuleStatement), LicenseRuleStatement: S.optional(LicenseRuleStatement), InstanceRuleStatement: S.optional(InstanceRuleStatement)}) {}
export class LicenseAssetRule extends S.Class<LicenseAssetRule>("LicenseAssetRule")({RuleStatement: RuleStatement}) {}
export const LicenseAssetRuleList = S.Array(LicenseAssetRule);
export class UpdateLicenseAssetRulesetRequest extends S.Class<UpdateLicenseAssetRulesetRequest>("UpdateLicenseAssetRulesetRequest")({Name: S.optional(S.String), Description: S.optional(S.String), Rules: LicenseAssetRuleList, LicenseAssetRulesetArn: S.String, ClientToken: S.String}) {}
export class ProductInformationFilter extends S.Class<ProductInformationFilter>("ProductInformationFilter")({ProductInformationFilterName: S.String, ProductInformationFilterValue: S.optional(StringList), ProductInformationFilterComparator: S.String}) {}
export const ProductInformationFilterList = S.Array(ProductInformationFilter);
export class ProductInformation extends S.Class<ProductInformation>("ProductInformation")({ResourceType: S.String, ProductInformationFilterList: ProductInformationFilterList}) {}
export const ProductInformationList = S.Array(ProductInformation);
export class UpdateLicenseConfigurationRequest extends S.Class<UpdateLicenseConfigurationRequest>("UpdateLicenseConfigurationRequest")({LicenseConfigurationArn: S.String, LicenseConfigurationStatus: S.optional(S.String), LicenseRules: S.optional(StringList), LicenseCount: S.optional(S.Number), LicenseCountHardLimit: S.optional(S.Boolean), Name: S.optional(S.String), Description: S.optional(S.String), ProductInformationList: S.optional(ProductInformationList), DisassociateWhenNotFound: S.optional(S.Boolean), LicenseExpiry: S.optional(S.Number)}) {}
export class UpdateLicenseConfigurationResponse extends S.Class<UpdateLicenseConfigurationResponse>("UpdateLicenseConfigurationResponse")({}) {}
export class ReportContext extends S.Class<ReportContext>("ReportContext")({licenseConfigurationArns: S.optional(ArnList), licenseAssetGroupArns: S.optional(ArnList), reportStartDate: S.optional(S.Date), reportEndDate: S.optional(S.Date)}) {}
export class ReportFrequency extends S.Class<ReportFrequency>("ReportFrequency")({value: S.optional(S.Number), period: S.optional(S.String)}) {}
export class UpdateLicenseManagerReportGeneratorRequest extends S.Class<UpdateLicenseManagerReportGeneratorRequest>("UpdateLicenseManagerReportGeneratorRequest")({LicenseManagerReportGeneratorArn: S.String, ReportGeneratorName: S.String, Type: ReportTypeList, ReportContext: ReportContext, ReportFrequency: ReportFrequency, ClientToken: S.String, Description: S.optional(S.String)}) {}
export class UpdateLicenseManagerReportGeneratorResponse extends S.Class<UpdateLicenseManagerReportGeneratorResponse>("UpdateLicenseManagerReportGeneratorResponse")({}) {}
export class OrganizationConfiguration extends S.Class<OrganizationConfiguration>("OrganizationConfiguration")({EnableIntegration: S.Boolean}) {}
export class UpdateServiceSettingsRequest extends S.Class<UpdateServiceSettingsRequest>("UpdateServiceSettingsRequest")({S3BucketArn: S.optional(S.String), SnsTopicArn: S.optional(S.String), OrganizationConfiguration: S.optional(OrganizationConfiguration), EnableCrossAccountsDiscovery: S.optional(S.Boolean), EnabledDiscoverySourceRegions: S.optional(StringList)}) {}
export class UpdateServiceSettingsResponse extends S.Class<UpdateServiceSettingsResponse>("UpdateServiceSettingsResponse")({}) {}
export class Options extends S.Class<Options>("Options")({ActivationOverrideBehavior: S.optional(S.String)}) {}
export class LicenseAssetGroup extends S.Class<LicenseAssetGroup>("LicenseAssetGroup")({Name: S.String, Description: S.optional(S.String), LicenseAssetGroupConfigurations: S.optional(LicenseAssetGroupConfigurationList), AssociatedLicenseAssetRulesetARNs: LicenseAssetRulesetArnList, Properties: S.optional(LicenseAssetGroupPropertyList), LicenseAssetGroupArn: S.String, Status: S.String, StatusMessage: S.optional(S.String), LatestUsageAnalysisTime: S.optional(S.Date), LatestResourceDiscoveryTime: S.optional(S.Date)}) {}
export const LicenseAssetGroupList = S.Array(LicenseAssetGroup);
export class LicenseAssetRuleset extends S.Class<LicenseAssetRuleset>("LicenseAssetRuleset")({Name: S.String, Description: S.optional(S.String), Rules: LicenseAssetRuleList, LicenseAssetRulesetArn: S.String}) {}
export const LicenseAssetRulesetList = S.Array(LicenseAssetRuleset);
export class S3Location extends S.Class<S3Location>("S3Location")({bucket: S.optional(S.String), keyPrefix: S.optional(S.String)}) {}
export class ReportGenerator extends S.Class<ReportGenerator>("ReportGenerator")({ReportGeneratorName: S.optional(S.String), ReportType: S.optional(ReportTypeList), ReportContext: S.optional(ReportContext), ReportFrequency: S.optional(ReportFrequency), LicenseManagerReportGeneratorArn: S.optional(S.String), LastRunStatus: S.optional(S.String), LastRunFailureReason: S.optional(S.String), LastReportGenerationTime: S.optional(S.String), ReportCreatorAccount: S.optional(S.String), Description: S.optional(S.String), S3Location: S.optional(S3Location), CreateTime: S.optional(S.String), Tags: S.optional(TagList)}) {}
export const ReportGeneratorList = S.Array(ReportGenerator);
export class IssuerDetails extends S.Class<IssuerDetails>("IssuerDetails")({Name: S.optional(S.String), SignKey: S.optional(S.String), KeyFingerprint: S.optional(S.String)}) {}
export class License extends S.Class<License>("License")({LicenseArn: S.optional(S.String), LicenseName: S.optional(S.String), ProductName: S.optional(S.String), ProductSKU: S.optional(S.String), Issuer: S.optional(IssuerDetails), HomeRegion: S.optional(S.String), Status: S.optional(S.String), Validity: S.optional(DatetimeRange), Beneficiary: S.optional(S.String), Entitlements: S.optional(EntitlementList), ConsumptionConfiguration: S.optional(ConsumptionConfiguration), LicenseMetadata: S.optional(MetadataList), CreateTime: S.optional(S.String), Version: S.optional(S.String)}) {}
export const LicenseList = S.Array(License);
export class Grant extends S.Class<Grant>("Grant")({GrantArn: S.String, GrantName: S.String, ParentArn: S.String, LicenseArn: S.String, GranteePrincipalArn: S.String, HomeRegion: S.String, GrantStatus: S.String, StatusReason: S.optional(S.String), Version: S.String, GrantedOperations: AllowedOperationList, Options: S.optional(Options)}) {}
export const GrantList = S.Array(Grant);
export class InventoryFilter extends S.Class<InventoryFilter>("InventoryFilter")({Name: S.String, Condition: S.String, Value: S.optional(S.String)}) {}
export const InventoryFilterList = S.Array(InventoryFilter);
export class LicenseSpecification extends S.Class<LicenseSpecification>("LicenseSpecification")({LicenseConfigurationArn: S.String, AmiAssociationScope: S.optional(S.String)}) {}
export const LicenseSpecifications = S.Array(LicenseSpecification);
export class AcceptGrantResponse extends S.Class<AcceptGrantResponse>("AcceptGrantResponse")({GrantArn: S.optional(S.String), Status: S.optional(S.String), Version: S.optional(S.String)}) {}
export class AccessDeniedException extends S.Class<AccessDeniedException>("AccessDeniedException")({Message: S.optional(S.String)}) {}
export class CheckoutBorrowLicenseRequest extends S.Class<CheckoutBorrowLicenseRequest>("CheckoutBorrowLicenseRequest")({LicenseArn: S.String, Entitlements: EntitlementDataList, DigitalSignatureMethod: S.String, NodeId: S.optional(S.String), CheckoutMetadata: S.optional(MetadataList), ClientToken: S.String}) {}
export class CheckoutLicenseResponse extends S.Class<CheckoutLicenseResponse>("CheckoutLicenseResponse")({CheckoutType: S.optional(S.String), LicenseConsumptionToken: S.optional(S.String), EntitlementsAllowed: S.optional(EntitlementDataList), SignedToken: S.optional(S.String), NodeId: S.optional(S.String), IssuedAt: S.optional(S.String), Expiration: S.optional(S.String), LicenseArn: S.optional(S.String)}) {}
export class CreateGrantRequest extends S.Class<CreateGrantRequest>("CreateGrantRequest")({ClientToken: S.String, GrantName: S.String, LicenseArn: S.String, Principals: PrincipalArnList, HomeRegion: S.String, AllowedOperations: AllowedOperationList, Tags: S.optional(TagList)}) {}
export class CreateGrantVersionRequest extends S.Class<CreateGrantVersionRequest>("CreateGrantVersionRequest")({ClientToken: S.String, GrantArn: S.String, GrantName: S.optional(S.String), AllowedOperations: S.optional(AllowedOperationList), Status: S.optional(S.String), StatusReason: S.optional(S.String), SourceVersion: S.optional(S.String), Options: S.optional(Options)}) {}
export class CreateLicenseAssetGroupRequest extends S.Class<CreateLicenseAssetGroupRequest>("CreateLicenseAssetGroupRequest")({Name: S.String, Description: S.optional(S.String), LicenseAssetGroupConfigurations: LicenseAssetGroupConfigurationList, AssociatedLicenseAssetRulesetARNs: LicenseAssetRulesetArnList, Properties: S.optional(LicenseAssetGroupPropertyList), Tags: S.optional(TagList), ClientToken: S.String}) {}
export class CreateLicenseManagerReportGeneratorRequest extends S.Class<CreateLicenseManagerReportGeneratorRequest>("CreateLicenseManagerReportGeneratorRequest")({ReportGeneratorName: S.String, Type: ReportTypeList, ReportContext: ReportContext, ReportFrequency: ReportFrequency, ClientToken: S.String, Description: S.optional(S.String), Tags: S.optional(TagList)}) {}
export class CreateLicenseVersionResponse extends S.Class<CreateLicenseVersionResponse>("CreateLicenseVersionResponse")({LicenseArn: S.optional(S.String), Version: S.optional(S.String), Status: S.optional(S.String)}) {}
export class CreateTokenResponse extends S.Class<CreateTokenResponse>("CreateTokenResponse")({TokenId: S.optional(S.String), TokenType: S.optional(S.String), Token: S.optional(S.String)}) {}
export class DeleteGrantResponse extends S.Class<DeleteGrantResponse>("DeleteGrantResponse")({GrantArn: S.optional(S.String), Status: S.optional(S.String), Version: S.optional(S.String)}) {}
export class DeleteLicenseResponse extends S.Class<DeleteLicenseResponse>("DeleteLicenseResponse")({Status: S.optional(S.String), DeletionDate: S.optional(S.String)}) {}
export class DeleteLicenseAssetGroupResponse extends S.Class<DeleteLicenseAssetGroupResponse>("DeleteLicenseAssetGroupResponse")({Status: S.String}) {}
export class AuthorizationException extends S.Class<AuthorizationException>("AuthorizationException")({Message: S.optional(S.String)}) {}
export class InvalidParameterValueException extends S.Class<InvalidParameterValueException>("InvalidParameterValueException")({Message: S.optional(S.String)}) {}
export class RateLimitExceededException extends S.Class<RateLimitExceededException>("RateLimitExceededException")({Message: S.optional(S.String)}) {}
export class RedirectException extends S.Class<RedirectException>("RedirectException")({Location: S.optional(H.Header("Location")), Message: S.optional(S.String)}) {}
export class ExtendLicenseConsumptionResponse extends S.Class<ExtendLicenseConsumptionResponse>("ExtendLicenseConsumptionResponse")({LicenseConsumptionToken: S.optional(S.String), Expiration: S.optional(S.String)}) {}
export class GetAccessTokenResponse extends S.Class<GetAccessTokenResponse>("GetAccessTokenResponse")({AccessToken: S.optional(S.String)}) {}
export class ProductCodeListItem extends S.Class<ProductCodeListItem>("ProductCodeListItem")({ProductCodeId: S.String, ProductCodeType: S.String}) {}
export const ProductCodeList = S.Array(ProductCodeListItem);
export class LicenseConversionContext extends S.Class<LicenseConversionContext>("LicenseConversionContext")({UsageOperation: S.optional(S.String), ProductCodes: S.optional(ProductCodeList)}) {}
export class GetLicenseConversionTaskResponse extends S.Class<GetLicenseConversionTaskResponse>("GetLicenseConversionTaskResponse")({LicenseConversionTaskId: S.optional(S.String), ResourceArn: S.optional(S.String), SourceLicenseContext: S.optional(LicenseConversionContext), DestinationLicenseContext: S.optional(LicenseConversionContext), StatusMessage: S.optional(S.String), Status: S.optional(S.String), StartTime: S.optional(S.Date), LicenseConversionTime: S.optional(S.Date), EndTime: S.optional(S.Date)}) {}
export class ListDistributedGrantsRequest extends S.Class<ListDistributedGrantsRequest>("ListDistributedGrantsRequest")({GrantArns: S.optional(ArnList), Filters: S.optional(FilterList), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListLicenseAssetGroupsResponse extends S.Class<ListLicenseAssetGroupsResponse>("ListLicenseAssetGroupsResponse")({LicenseAssetGroups: S.optional(LicenseAssetGroupList), NextToken: S.optional(S.String)}) {}
export class ListLicenseAssetRulesetsResponse extends S.Class<ListLicenseAssetRulesetsResponse>("ListLicenseAssetRulesetsResponse")({LicenseAssetRulesets: S.optional(LicenseAssetRulesetList), NextToken: S.optional(S.String)}) {}
export class ConsumedLicenseSummary extends S.Class<ConsumedLicenseSummary>("ConsumedLicenseSummary")({ResourceType: S.optional(S.String), ConsumedLicenses: S.optional(S.Number)}) {}
export const ConsumedLicenseSummaryList = S.Array(ConsumedLicenseSummary);
export class ManagedResourceSummary extends S.Class<ManagedResourceSummary>("ManagedResourceSummary")({ResourceType: S.optional(S.String), AssociationCount: S.optional(S.Number)}) {}
export const ManagedResourceSummaryList = S.Array(ManagedResourceSummary);
export class AutomatedDiscoveryInformation extends S.Class<AutomatedDiscoveryInformation>("AutomatedDiscoveryInformation")({LastRunTime: S.optional(S.Date)}) {}
export class LicenseConfiguration extends S.Class<LicenseConfiguration>("LicenseConfiguration")({LicenseConfigurationId: S.optional(S.String), LicenseConfigurationArn: S.optional(S.String), Name: S.optional(S.String), Description: S.optional(S.String), LicenseCountingType: S.optional(S.String), LicenseRules: S.optional(StringList), LicenseCount: S.optional(S.Number), LicenseCountHardLimit: S.optional(S.Boolean), DisassociateWhenNotFound: S.optional(S.Boolean), ConsumedLicenses: S.optional(S.Number), Status: S.optional(S.String), OwnerAccountId: S.optional(S.String), ConsumedLicenseSummaryList: S.optional(ConsumedLicenseSummaryList), ManagedResourceSummaryList: S.optional(ManagedResourceSummaryList), ProductInformationList: S.optional(ProductInformationList), AutomatedDiscoveryInformation: S.optional(AutomatedDiscoveryInformation), LicenseExpiry: S.optional(S.Number)}) {}
export const LicenseConfigurations = S.Array(LicenseConfiguration);
export class ListLicenseConfigurationsForOrganizationResponse extends S.Class<ListLicenseConfigurationsForOrganizationResponse>("ListLicenseConfigurationsForOrganizationResponse")({LicenseConfigurations: S.optional(LicenseConfigurations), NextToken: S.optional(S.String)}) {}
export class ListLicenseManagerReportGeneratorsResponse extends S.Class<ListLicenseManagerReportGeneratorsResponse>("ListLicenseManagerReportGeneratorsResponse")({ReportGenerators: S.optional(ReportGeneratorList), NextToken: S.optional(S.String)}) {}
export class ListLicensesResponse extends S.Class<ListLicensesResponse>("ListLicensesResponse")({Licenses: S.optional(LicenseList), NextToken: S.optional(S.String)}) {}
export class ListLicenseSpecificationsForResourceResponse extends S.Class<ListLicenseSpecificationsForResourceResponse>("ListLicenseSpecificationsForResourceResponse")({LicenseSpecifications: S.optional(LicenseSpecifications), NextToken: S.optional(S.String)}) {}
export class ListLicenseVersionsResponse extends S.Class<ListLicenseVersionsResponse>("ListLicenseVersionsResponse")({Licenses: S.optional(LicenseList), NextToken: S.optional(S.String)}) {}
export class ListReceivedGrantsResponse extends S.Class<ListReceivedGrantsResponse>("ListReceivedGrantsResponse")({Grants: S.optional(GrantList), NextToken: S.optional(S.String)}) {}
export class ListReceivedGrantsForOrganizationResponse extends S.Class<ListReceivedGrantsForOrganizationResponse>("ListReceivedGrantsForOrganizationResponse")({Grants: S.optional(GrantList), NextToken: S.optional(S.String)}) {}
export class ReceivedMetadata extends S.Class<ReceivedMetadata>("ReceivedMetadata")({ReceivedStatus: S.optional(S.String), ReceivedStatusReason: S.optional(S.String), AllowedOperations: S.optional(AllowedOperationList)}) {}
export class GrantedLicense extends S.Class<GrantedLicense>("GrantedLicense")({LicenseArn: S.optional(S.String), LicenseName: S.optional(S.String), ProductName: S.optional(S.String), ProductSKU: S.optional(S.String), Issuer: S.optional(IssuerDetails), HomeRegion: S.optional(S.String), Status: S.optional(S.String), Validity: S.optional(DatetimeRange), Beneficiary: S.optional(S.String), Entitlements: S.optional(EntitlementList), ConsumptionConfiguration: S.optional(ConsumptionConfiguration), LicenseMetadata: S.optional(MetadataList), CreateTime: S.optional(S.String), Version: S.optional(S.String), ReceivedMetadata: S.optional(ReceivedMetadata)}) {}
export const GrantedLicenseList = S.Array(GrantedLicense);
export class ListReceivedLicensesForOrganizationResponse extends S.Class<ListReceivedLicensesForOrganizationResponse>("ListReceivedLicensesForOrganizationResponse")({Licenses: S.optional(GrantedLicenseList), NextToken: S.optional(S.String)}) {}
export class ListResourceInventoryRequest extends S.Class<ListResourceInventoryRequest>("ListResourceInventoryRequest")({MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), Filters: S.optional(InventoryFilterList)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Tags: S.optional(TagList)}) {}
export class RejectGrantResponse extends S.Class<RejectGrantResponse>("RejectGrantResponse")({GrantArn: S.optional(S.String), Status: S.optional(S.String), Version: S.optional(S.String)}) {}
export class ServerInternalException extends S.Class<ServerInternalException>("ServerInternalException")({Message: S.optional(S.String)}) {}
export class ValidationException extends S.Class<ValidationException>("ValidationException")({Message: S.optional(S.String)}) {}
export class UpdateLicenseAssetGroupResponse extends S.Class<UpdateLicenseAssetGroupResponse>("UpdateLicenseAssetGroupResponse")({LicenseAssetGroupArn: S.String, Status: S.String}) {}
export class UpdateLicenseAssetRulesetResponse extends S.Class<UpdateLicenseAssetRulesetResponse>("UpdateLicenseAssetRulesetResponse")({LicenseAssetRulesetArn: S.String}) {}
export class ConflictException extends S.Class<ConflictException>("ConflictException")({Message: S.optional(S.String)}) {}
export class ResourceLimitExceededException extends S.Class<ResourceLimitExceededException>("ResourceLimitExceededException")({Message: S.optional(S.String)}) {}
export class UpdateLicenseSpecificationsForResourceRequest extends S.Class<UpdateLicenseSpecificationsForResourceRequest>("UpdateLicenseSpecificationsForResourceRequest")({ResourceArn: S.String, AddLicenseSpecifications: S.optional(LicenseSpecifications), RemoveLicenseSpecifications: S.optional(LicenseSpecifications)}) {}
export class UpdateLicenseSpecificationsForResourceResponse extends S.Class<UpdateLicenseSpecificationsForResourceResponse>("UpdateLicenseSpecificationsForResourceResponse")({}) {}
export class CrossAccountDiscoveryServiceStatus extends S.Class<CrossAccountDiscoveryServiceStatus>("CrossAccountDiscoveryServiceStatus")({Message: S.optional(S.String)}) {}
export class Asset extends S.Class<Asset>("Asset")({AssetArn: S.optional(S.String), LatestAssetDiscoveryTime: S.optional(S.Date)}) {}
export const AssetList = S.Array(Asset);
export class LicenseConfigurationAssociation extends S.Class<LicenseConfigurationAssociation>("LicenseConfigurationAssociation")({ResourceArn: S.optional(S.String), ResourceType: S.optional(S.String), ResourceOwnerId: S.optional(S.String), AssociationTime: S.optional(S.Date), AmiAssociationScope: S.optional(S.String)}) {}
export const LicenseConfigurationAssociations = S.Array(LicenseConfigurationAssociation);
export class LicenseOperationFailure extends S.Class<LicenseOperationFailure>("LicenseOperationFailure")({ResourceArn: S.optional(S.String), ResourceType: S.optional(S.String), ErrorMessage: S.optional(S.String), FailureTime: S.optional(S.Date), OperationName: S.optional(S.String), ResourceOwnerId: S.optional(S.String), OperationRequestedBy: S.optional(S.String), MetadataList: S.optional(MetadataList)}) {}
export const LicenseOperationFailureList = S.Array(LicenseOperationFailure);
export class LicenseConversionTask extends S.Class<LicenseConversionTask>("LicenseConversionTask")({LicenseConversionTaskId: S.optional(S.String), ResourceArn: S.optional(S.String), SourceLicenseContext: S.optional(LicenseConversionContext), DestinationLicenseContext: S.optional(LicenseConversionContext), Status: S.optional(S.String), StatusMessage: S.optional(S.String), StartTime: S.optional(S.Date), LicenseConversionTime: S.optional(S.Date), EndTime: S.optional(S.Date)}) {}
export const LicenseConversionTasks = S.Array(LicenseConversionTask);
export class TokenData extends S.Class<TokenData>("TokenData")({TokenId: S.optional(S.String), TokenType: S.optional(S.String), LicenseArn: S.optional(S.String), ExpirationTime: S.optional(S.String), TokenProperties: S.optional(MaxSize3StringList), RoleArns: S.optional(ArnList), Status: S.optional(S.String)}) {}
export const TokenList = S.Array(TokenData);
export class LicenseConfigurationUsage extends S.Class<LicenseConfigurationUsage>("LicenseConfigurationUsage")({ResourceArn: S.optional(S.String), ResourceType: S.optional(S.String), ResourceStatus: S.optional(S.String), ResourceOwnerId: S.optional(S.String), AssociationTime: S.optional(S.Date), ConsumedLicenses: S.optional(S.Number)}) {}
export const LicenseConfigurationUsageList = S.Array(LicenseConfigurationUsage);
export class ResourceNotFoundException extends S.Class<ResourceNotFoundException>("ResourceNotFoundException")({Message: S.optional(S.String)}) {}
export class CheckoutBorrowLicenseResponse extends S.Class<CheckoutBorrowLicenseResponse>("CheckoutBorrowLicenseResponse")({LicenseArn: S.optional(S.String), LicenseConsumptionToken: S.optional(S.String), EntitlementsAllowed: S.optional(EntitlementDataList), NodeId: S.optional(S.String), SignedToken: S.optional(S.String), IssuedAt: S.optional(S.String), Expiration: S.optional(S.String), CheckoutMetadata: S.optional(MetadataList)}) {}
export class NoEntitlementsAllowedException extends S.Class<NoEntitlementsAllowedException>("NoEntitlementsAllowedException")({Message: S.optional(S.String)}) {}
export class CreateGrantResponse extends S.Class<CreateGrantResponse>("CreateGrantResponse")({GrantArn: S.optional(S.String), Status: S.optional(S.String), Version: S.optional(S.String)}) {}
export class CreateGrantVersionResponse extends S.Class<CreateGrantVersionResponse>("CreateGrantVersionResponse")({GrantArn: S.optional(S.String), Status: S.optional(S.String), Version: S.optional(S.String)}) {}
export class CreateLicenseRequest extends S.Class<CreateLicenseRequest>("CreateLicenseRequest")({LicenseName: S.String, ProductName: S.String, ProductSKU: S.String, Issuer: Issuer, HomeRegion: S.String, Validity: DatetimeRange, Entitlements: EntitlementList, Beneficiary: S.String, ConsumptionConfiguration: ConsumptionConfiguration, LicenseMetadata: S.optional(MetadataList), ClientToken: S.String, Tags: S.optional(TagList)}) {}
export class CreateLicenseAssetGroupResponse extends S.Class<CreateLicenseAssetGroupResponse>("CreateLicenseAssetGroupResponse")({LicenseAssetGroupArn: S.String, Status: S.String}) {}
export class CreateLicenseConfigurationRequest extends S.Class<CreateLicenseConfigurationRequest>("CreateLicenseConfigurationRequest")({Name: S.String, Description: S.optional(S.String), LicenseCountingType: S.String, LicenseCount: S.optional(S.Number), LicenseCountHardLimit: S.optional(S.Boolean), LicenseRules: S.optional(StringList), Tags: S.optional(TagList), DisassociateWhenNotFound: S.optional(S.Boolean), ProductInformationList: S.optional(ProductInformationList), LicenseExpiry: S.optional(S.Number)}) {}
export class CreateLicenseConversionTaskForResourceRequest extends S.Class<CreateLicenseConversionTaskForResourceRequest>("CreateLicenseConversionTaskForResourceRequest")({ResourceArn: S.String, SourceLicenseContext: LicenseConversionContext, DestinationLicenseContext: LicenseConversionContext}) {}
export class CreateLicenseManagerReportGeneratorResponse extends S.Class<CreateLicenseManagerReportGeneratorResponse>("CreateLicenseManagerReportGeneratorResponse")({LicenseManagerReportGeneratorArn: S.optional(S.String)}) {}
export class GetGrantResponse extends S.Class<GetGrantResponse>("GetGrantResponse")({Grant: S.optional(Grant)}) {}
export class GetLicenseAssetGroupResponse extends S.Class<GetLicenseAssetGroupResponse>("GetLicenseAssetGroupResponse")({LicenseAssetGroup: LicenseAssetGroup}) {}
export class GetLicenseAssetRulesetResponse extends S.Class<GetLicenseAssetRulesetResponse>("GetLicenseAssetRulesetResponse")({LicenseAssetRuleset: LicenseAssetRuleset}) {}
export class GetLicenseConfigurationResponse extends S.Class<GetLicenseConfigurationResponse>("GetLicenseConfigurationResponse")({LicenseConfigurationId: S.optional(S.String), LicenseConfigurationArn: S.optional(S.String), Name: S.optional(S.String), Description: S.optional(S.String), LicenseCountingType: S.optional(S.String), LicenseRules: S.optional(StringList), LicenseCount: S.optional(S.Number), LicenseCountHardLimit: S.optional(S.Boolean), ConsumedLicenses: S.optional(S.Number), Status: S.optional(S.String), OwnerAccountId: S.optional(S.String), ConsumedLicenseSummaryList: S.optional(ConsumedLicenseSummaryList), ManagedResourceSummaryList: S.optional(ManagedResourceSummaryList), Tags: S.optional(TagList), ProductInformationList: S.optional(ProductInformationList), AutomatedDiscoveryInformation: S.optional(AutomatedDiscoveryInformation), DisassociateWhenNotFound: S.optional(S.Boolean), LicenseExpiry: S.optional(S.Number)}) {}
export class ListAssetsForLicenseAssetGroupResponse extends S.Class<ListAssetsForLicenseAssetGroupResponse>("ListAssetsForLicenseAssetGroupResponse")({Assets: S.optional(AssetList), NextToken: S.optional(S.String)}) {}
export class ListAssociationsForLicenseConfigurationResponse extends S.Class<ListAssociationsForLicenseConfigurationResponse>("ListAssociationsForLicenseConfigurationResponse")({LicenseConfigurationAssociations: S.optional(LicenseConfigurationAssociations), NextToken: S.optional(S.String)}) {}
export class ListDistributedGrantsResponse extends S.Class<ListDistributedGrantsResponse>("ListDistributedGrantsResponse")({Grants: S.optional(GrantList), NextToken: S.optional(S.String)}) {}
export class ListFailuresForLicenseConfigurationOperationsResponse extends S.Class<ListFailuresForLicenseConfigurationOperationsResponse>("ListFailuresForLicenseConfigurationOperationsResponse")({LicenseOperationFailureList: S.optional(LicenseOperationFailureList), NextToken: S.optional(S.String)}) {}
export class ListLicenseConfigurationsResponse extends S.Class<ListLicenseConfigurationsResponse>("ListLicenseConfigurationsResponse")({LicenseConfigurations: S.optional(LicenseConfigurations), NextToken: S.optional(S.String)}) {}
export class FilterLimitExceededException extends S.Class<FilterLimitExceededException>("FilterLimitExceededException")({Message: S.optional(S.String)}) {}
export class ListLicenseConversionTasksResponse extends S.Class<ListLicenseConversionTasksResponse>("ListLicenseConversionTasksResponse")({LicenseConversionTasks: S.optional(LicenseConversionTasks), NextToken: S.optional(S.String)}) {}
export class ListTokensResponse extends S.Class<ListTokensResponse>("ListTokensResponse")({Tokens: S.optional(TokenList), NextToken: S.optional(S.String)}) {}
export class ListUsageForLicenseConfigurationResponse extends S.Class<ListUsageForLicenseConfigurationResponse>("ListUsageForLicenseConfigurationResponse")({LicenseConfigurationUsageList: S.optional(LicenseConfigurationUsageList), NextToken: S.optional(S.String)}) {}
export class InvalidResourceStateException extends S.Class<InvalidResourceStateException>("InvalidResourceStateException")({Message: S.optional(S.String)}) {}
export class EntitlementUsage extends S.Class<EntitlementUsage>("EntitlementUsage")({Name: S.String, ConsumedValue: S.String, MaxCount: S.optional(S.String), Unit: S.String}) {}
export const EntitlementUsageList = S.Array(EntitlementUsage);
export class RegionStatus extends S.Class<RegionStatus>("RegionStatus")({Status: S.optional(S.String)}) {}
export class LicenseUsage extends S.Class<LicenseUsage>("LicenseUsage")({EntitlementUsages: S.optional(EntitlementUsageList)}) {}
export class ResourceInventory extends S.Class<ResourceInventory>("ResourceInventory")({ResourceId: S.optional(S.String), ResourceType: S.optional(S.String), ResourceArn: S.optional(S.String), Platform: S.optional(S.String), PlatformVersion: S.optional(S.String), ResourceOwningAccountId: S.optional(S.String), MarketplaceProductCodes: S.optional(StringList), UsageOperation: S.optional(S.String), AmiId: S.optional(S.String), HostId: S.optional(S.String), Region: S.optional(S.String), InstanceType: S.optional(S.String)}) {}
export const ResourceInventoryList = S.Array(ResourceInventory);
export const RegionStatusMap = S.Record({key: S.String, value: RegionStatus});
export class EntitlementNotAllowedException extends S.Class<EntitlementNotAllowedException>("EntitlementNotAllowedException")({Message: S.optional(S.String)}) {}
export class UnsupportedDigitalSignatureMethodException extends S.Class<UnsupportedDigitalSignatureMethodException>("UnsupportedDigitalSignatureMethodException")({Message: S.optional(S.String)}) {}
export class CreateLicenseResponse extends S.Class<CreateLicenseResponse>("CreateLicenseResponse")({LicenseArn: S.optional(S.String), Status: S.optional(S.String), Version: S.optional(S.String)}) {}
export class CreateLicenseConfigurationResponse extends S.Class<CreateLicenseConfigurationResponse>("CreateLicenseConfigurationResponse")({LicenseConfigurationArn: S.optional(S.String)}) {}
export class CreateLicenseConversionTaskForResourceResponse extends S.Class<CreateLicenseConversionTaskForResourceResponse>("CreateLicenseConversionTaskForResourceResponse")({LicenseConversionTaskId: S.optional(S.String)}) {}
export class GetLicenseResponse extends S.Class<GetLicenseResponse>("GetLicenseResponse")({License: S.optional(License)}) {}
export class GetLicenseManagerReportGeneratorResponse extends S.Class<GetLicenseManagerReportGeneratorResponse>("GetLicenseManagerReportGeneratorResponse")({ReportGenerator: S.optional(ReportGenerator)}) {}
export class GetLicenseUsageResponse extends S.Class<GetLicenseUsageResponse>("GetLicenseUsageResponse")({LicenseUsage: S.optional(LicenseUsage)}) {}
export class ListReceivedLicensesResponse extends S.Class<ListReceivedLicensesResponse>("ListReceivedLicensesResponse")({Licenses: S.optional(GrantedLicenseList), NextToken: S.optional(S.String)}) {}
export class ListResourceInventoryResponse extends S.Class<ListResourceInventoryResponse>("ListResourceInventoryResponse")({ResourceInventoryList: S.optional(ResourceInventoryList), NextToken: S.optional(S.String)}) {}
export class LicenseUsageException extends S.Class<LicenseUsageException>("LicenseUsageException")({Message: S.optional(S.String)}) {}
export class CrossRegionDiscoveryStatus extends S.Class<CrossRegionDiscoveryStatus>("CrossRegionDiscoveryStatus")({Message: S.optional(RegionStatusMap)}) {}
export class ServiceStatus extends S.Class<ServiceStatus>("ServiceStatus")({CrossAccountDiscovery: S.optional(CrossAccountDiscoveryServiceStatus), CrossRegionDiscovery: S.optional(CrossRegionDiscoveryStatus)}) {}
export class CreateLicenseAssetRulesetRequest extends S.Class<CreateLicenseAssetRulesetRequest>("CreateLicenseAssetRulesetRequest")({Name: S.String, Description: S.optional(S.String), Rules: LicenseAssetRuleList, Tags: S.optional(TagList), ClientToken: S.String}) {}
export class GetServiceSettingsResponse extends S.Class<GetServiceSettingsResponse>("GetServiceSettingsResponse")({S3BucketArn: S.optional(S.String), SnsTopicArn: S.optional(S.String), OrganizationConfiguration: S.optional(OrganizationConfiguration), EnableCrossAccountsDiscovery: S.optional(S.Boolean), LicenseManagerResourceShareArn: S.optional(S.String), CrossRegionDiscoveryHomeRegion: S.optional(S.String), CrossRegionDiscoverySourceRegions: S.optional(StringList), ServiceStatus: S.optional(ServiceStatus)}) {}
export class FailedDependencyException extends S.Class<FailedDependencyException>("FailedDependencyException")({Message: S.optional(S.String), ErrorCode: S.optional(S.String)}) {}
export class CreateLicenseAssetRulesetResponse extends S.Class<CreateLicenseAssetRulesetResponse>("CreateLicenseAssetRulesetResponse")({LicenseAssetRulesetArn: S.String}) {}

//# Errors
export class AccessDeniedExceptionError extends S.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class AuthorizationExceptionError extends S.TaggedError<AuthorizationExceptionError>()("AuthorizationException", AuthorizationException.fields) {};
export class InvalidParameterValueExceptionError extends S.TaggedError<InvalidParameterValueExceptionError>()("InvalidParameterValueException", InvalidParameterValueException.fields) {};
export class RateLimitExceededExceptionError extends S.TaggedError<RateLimitExceededExceptionError>()("RateLimitExceededException", RateLimitExceededException.fields) {};
export class ServerInternalExceptionError extends S.TaggedError<ServerInternalExceptionError>()("ServerInternalException", ServerInternalException.fields) {};
export class ConflictExceptionError extends S.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class ValidationExceptionError extends S.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};
export class ResourceLimitExceededExceptionError extends S.TaggedError<ResourceLimitExceededExceptionError>()("ResourceLimitExceededException", ResourceLimitExceededException.fields) {};
export class RedirectExceptionError extends S.TaggedError<RedirectExceptionError>()("RedirectException", RedirectException.fields) {};
export class ResourceNotFoundExceptionError extends S.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class NoEntitlementsAllowedExceptionError extends S.TaggedError<NoEntitlementsAllowedExceptionError>()("NoEntitlementsAllowedException", NoEntitlementsAllowedException.fields) {};
export class FilterLimitExceededExceptionError extends S.TaggedError<FilterLimitExceededExceptionError>()("FilterLimitExceededException", FilterLimitExceededException.fields) {};
export class InvalidResourceStateExceptionError extends S.TaggedError<InvalidResourceStateExceptionError>()("InvalidResourceStateException", InvalidResourceStateException.fields) {};
export class EntitlementNotAllowedExceptionError extends S.TaggedError<EntitlementNotAllowedExceptionError>()("EntitlementNotAllowedException", EntitlementNotAllowedException.fields) {};
export class UnsupportedDigitalSignatureMethodExceptionError extends S.TaggedError<UnsupportedDigitalSignatureMethodExceptionError>()("UnsupportedDigitalSignatureMethodException", UnsupportedDigitalSignatureMethodException.fields) {};
export class LicenseUsageExceptionError extends S.TaggedError<LicenseUsageExceptionError>()("LicenseUsageException", LicenseUsageException.fields) {};
export class FailedDependencyExceptionError extends S.TaggedError<FailedDependencyExceptionError>()("FailedDependencyException", FailedDependencyException.fields) {};

//# Operations
export const updateServiceSettings = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.UpdateServiceSettings" }, UpdateServiceSettingsRequest, UpdateServiceSettingsResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, ConflictExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const acceptGrant = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.AcceptGrant" }, AcceptGrantRequest, AcceptGrantResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLicenseVersion = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CreateLicenseVersion" }, CreateLicenseVersionRequest, CreateLicenseVersionResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, ConflictExceptionError, RateLimitExceededExceptionError, RedirectExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createToken = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CreateToken" }, CreateTokenRequest, CreateTokenResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, RateLimitExceededExceptionError, RedirectExceptionError, ResourceLimitExceededExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteGrant = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.DeleteGrant" }, DeleteGrantRequest, DeleteGrantResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteLicense = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.DeleteLicense" }, DeleteLicenseRequest, DeleteLicenseResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, ConflictExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, RedirectExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteLicenseAssetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.DeleteLicenseAssetGroup" }, DeleteLicenseAssetGroupRequest, DeleteLicenseAssetGroupResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteLicenseAssetRuleset = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.DeleteLicenseAssetRuleset" }, DeleteLicenseAssetRulesetRequest, DeleteLicenseAssetRulesetResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteLicenseConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.DeleteLicenseConfiguration" }, DeleteLicenseConfigurationRequest, DeleteLicenseConfigurationResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteLicenseManagerReportGenerator = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.DeleteLicenseManagerReportGenerator" }, DeleteLicenseManagerReportGeneratorRequest, DeleteLicenseManagerReportGeneratorResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteToken = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.DeleteToken" }, DeleteTokenRequest, DeleteTokenResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, RateLimitExceededExceptionError, RedirectExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const extendLicenseConsumption = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ExtendLicenseConsumption" }, ExtendLicenseConsumptionRequest, ExtendLicenseConsumptionResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getAccessToken = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.GetAccessToken" }, GetAccessTokenRequest, GetAccessTokenResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getLicenseConversionTask = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.GetLicenseConversionTask" }, GetLicenseConversionTaskRequest, GetLicenseConversionTaskResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listLicenseAssetGroups = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListLicenseAssetGroups" }, ListLicenseAssetGroupsRequest, ListLicenseAssetGroupsResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listLicenseAssetRulesets = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListLicenseAssetRulesets" }, ListLicenseAssetRulesetsRequest, ListLicenseAssetRulesetsResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listLicenseManagerReportGenerators = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListLicenseManagerReportGenerators" }, ListLicenseManagerReportGeneratorsRequest, ListLicenseManagerReportGeneratorsResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listLicenses = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListLicenses" }, ListLicensesRequest, ListLicensesResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listLicenseSpecificationsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListLicenseSpecificationsForResource" }, ListLicenseSpecificationsForResourceRequest, ListLicenseSpecificationsForResourceResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listLicenseVersions = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListLicenseVersions" }, ListLicenseVersionsRequest, ListLicenseVersionsResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listReceivedGrants = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListReceivedGrants" }, ListReceivedGrantsRequest, ListReceivedGrantsResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listReceivedGrantsForOrganization = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListReceivedGrantsForOrganization" }, ListReceivedGrantsForOrganizationRequest, ListReceivedGrantsForOrganizationResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listReceivedLicensesForOrganization = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListReceivedLicensesForOrganization" }, ListReceivedLicensesForOrganizationRequest, ListReceivedLicensesForOrganizationResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const rejectGrant = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.RejectGrant" }, RejectGrantRequest, RejectGrantResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.TagResource" }, TagResourceRequest, TagResourceResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLicenseAssetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.UpdateLicenseAssetGroup" }, UpdateLicenseAssetGroupRequest, UpdateLicenseAssetGroupResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLicenseAssetRuleset = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.UpdateLicenseAssetRuleset" }, UpdateLicenseAssetRulesetRequest, UpdateLicenseAssetRulesetResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLicenseConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.UpdateLicenseConfiguration" }, UpdateLicenseConfigurationRequest, UpdateLicenseConfigurationResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, ConflictExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLicenseManagerReportGenerator = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.UpdateLicenseManagerReportGenerator" }, UpdateLicenseManagerReportGeneratorRequest, UpdateLicenseManagerReportGeneratorResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const checkInLicense = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CheckInLicense" }, CheckInLicenseRequest, CheckInLicenseResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, ConflictExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createGrant = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CreateGrant" }, CreateGrantRequest, CreateGrantResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createGrantVersion = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CreateGrantVersion" }, CreateGrantVersionRequest, CreateGrantVersionResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLicenseAssetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CreateLicenseAssetGroup" }, CreateLicenseAssetGroupRequest, CreateLicenseAssetGroupResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLicenseManagerReportGenerator = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CreateLicenseManagerReportGenerator" }, CreateLicenseManagerReportGeneratorRequest, CreateLicenseManagerReportGeneratorResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getGrant = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.GetGrant" }, GetGrantRequest, GetGrantResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getLicenseAssetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.GetLicenseAssetGroup" }, GetLicenseAssetGroupRequest, GetLicenseAssetGroupResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getLicenseAssetRuleset = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.GetLicenseAssetRuleset" }, GetLicenseAssetRulesetRequest, GetLicenseAssetRulesetResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getLicenseConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.GetLicenseConfiguration" }, GetLicenseConfigurationRequest, GetLicenseConfigurationResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listAssetsForLicenseAssetGroup = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListAssetsForLicenseAssetGroup" }, ListAssetsForLicenseAssetGroupRequest, ListAssetsForLicenseAssetGroupResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listAssociationsForLicenseConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListAssociationsForLicenseConfiguration" }, ListAssociationsForLicenseConfigurationRequest, ListAssociationsForLicenseConfigurationResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, FilterLimitExceededExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listDistributedGrants = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListDistributedGrants" }, ListDistributedGrantsRequest, ListDistributedGrantsResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listFailuresForLicenseConfigurationOperations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListFailuresForLicenseConfigurationOperations" }, ListFailuresForLicenseConfigurationOperationsRequest, ListFailuresForLicenseConfigurationOperationsResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listLicenseConfigurations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListLicenseConfigurations" }, ListLicenseConfigurationsRequest, ListLicenseConfigurationsResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, FilterLimitExceededExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listLicenseConfigurationsForOrganization = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListLicenseConfigurationsForOrganization" }, ListLicenseConfigurationsForOrganizationRequest, ListLicenseConfigurationsForOrganizationResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, FilterLimitExceededExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listLicenseConversionTasks = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListLicenseConversionTasks" }, ListLicenseConversionTasksRequest, ListLicenseConversionTasksResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTokens = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListTokens" }, ListTokensRequest, ListTokensResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listUsageForLicenseConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListUsageForLicenseConfiguration" }, ListUsageForLicenseConfigurationRequest, ListUsageForLicenseConfigurationResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, FilterLimitExceededExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const checkoutBorrowLicense = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CheckoutBorrowLicense" }, CheckoutBorrowLicenseRequest, CheckoutBorrowLicenseResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, EntitlementNotAllowedExceptionError, InvalidParameterValueExceptionError, NoEntitlementsAllowedExceptionError, RateLimitExceededExceptionError, RedirectExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, UnsupportedDigitalSignatureMethodExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const checkoutLicense = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CheckoutLicense" }, CheckoutLicenseRequest, CheckoutLicenseResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, NoEntitlementsAllowedExceptionError, RateLimitExceededExceptionError, RedirectExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, UnsupportedDigitalSignatureMethodExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLicense = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CreateLicense" }, CreateLicenseRequest, CreateLicenseResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, RedirectExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLicenseConfiguration = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CreateLicenseConfiguration" }, CreateLicenseConfigurationRequest, CreateLicenseConfigurationResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLicenseConversionTaskForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CreateLicenseConversionTaskForResource" }, CreateLicenseConversionTaskForResourceRequest, CreateLicenseConversionTaskForResourceResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getLicense = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.GetLicense" }, GetLicenseRequest, GetLicenseResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getLicenseManagerReportGenerator = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.GetLicenseManagerReportGenerator" }, GetLicenseManagerReportGeneratorRequest, GetLicenseManagerReportGeneratorResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ResourceNotFoundExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getLicenseUsage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.GetLicenseUsage" }, GetLicenseUsageRequest, GetLicenseUsageResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listReceivedLicenses = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListReceivedLicenses" }, ListReceivedLicensesRequest, ListReceivedLicensesResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ResourceLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateLicenseSpecificationsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.UpdateLicenseSpecificationsForResource" }, UpdateLicenseSpecificationsForResourceRequest, UpdateLicenseSpecificationsForResourceResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, ConflictExceptionError, InvalidParameterValueExceptionError, InvalidResourceStateExceptionError, LicenseUsageExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getServiceSettings = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.GetServiceSettings" }, GetServiceSettingsRequest, GetServiceSettingsResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listResourceInventory = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.ListResourceInventory" }, ListResourceInventoryRequest, ListResourceInventoryResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, FailedDependencyExceptionError, FilterLimitExceededExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createLicenseAssetRuleset = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-08-01", uri: "/", method: "POST", sdkId: "License Manager", sigV4ServiceName: "license-manager", name: "AWSLicenseManager.CreateLicenseAssetRuleset" }, CreateLicenseAssetRulesetRequest, CreateLicenseAssetRulesetResponse, [AccessDeniedExceptionError, AuthorizationExceptionError, InvalidParameterValueExceptionError, RateLimitExceededExceptionError, ServerInternalExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
