import { Schema} from "effect"
import { FormatXMLRequest, FormatXMLResponse, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
const TagKeyList = Schema.Array(Schema.String)
const DeleteImageSetRequest = Schema.Struct({datastoreId: Schema.String, imageSetId: Schema.String})
const GetDICOMImportJobRequest = Schema.Struct({datastoreId: Schema.String, jobId: Schema.String})
const GetImageSetRequest = Schema.Struct({datastoreId: Schema.String, imageSetId: Schema.String, versionId: Schema.optional(Schema.String)})
const GetImageSetMetadataRequest = Schema.Struct({datastoreId: Schema.String, imageSetId: Schema.String, versionId: Schema.optional(Schema.String)})
const ListDICOMImportJobsRequest = Schema.Struct({datastoreId: Schema.String, jobStatus: Schema.optional(Schema.String), nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)})
const ListImageSetVersionsRequest = Schema.Struct({datastoreId: Schema.String, imageSetId: Schema.String, nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)})
const ListTagsForResourceRequest = Schema.Struct({resourceArn: Schema.String})
const StartDICOMImportJobRequest = Schema.Struct({jobName: Schema.optional(Schema.String), dataAccessRoleArn: Schema.String, clientToken: Schema.String, datastoreId: Schema.String, inputS3Uri: Schema.String, outputS3Uri: Schema.String, inputOwnerAccountId: Schema.optional(Schema.String)})
const UntagResourceRequest = Schema.Struct({resourceArn: Schema.String, tagKeys: TagKeyList})
const UntagResourceResponse = Schema.Struct({})
const ImageFrameInformation = Schema.Struct({imageFrameId: Schema.String})
const TagMap = Schema.Record({key: Schema.String, value: Schema.String})
const DeleteImageSetResponse = Schema.Struct({datastoreId: Schema.String, imageSetId: Schema.String, imageSetState: Schema.String, imageSetWorkflowStatus: Schema.String})
const GetImageFrameRequest = Schema.Struct({datastoreId: Schema.String, imageSetId: Schema.String, imageFrameInformation: Body("undefined", ImageFrameInformation)})
const GetImageSetMetadataResponse = Schema.Struct({imageSetMetadataBlob: Body("undefined", StreamBody()), contentType: Schema.optional(Header("Content-Type")), contentEncoding: Schema.optional(Header("Content-Encoding"))})
const ListTagsForResourceResponse = Schema.Struct({tags: TagMap})
const StartDICOMImportJobResponse = Schema.Struct({datastoreId: Schema.String, jobId: Schema.String, jobStatus: Schema.String, submittedAt: Schema.Date})
const TagResourceRequest = Schema.Struct({resourceArn: Schema.String, tags: TagMap})
const TagResourceResponse = Schema.Struct({})
const AccessDeniedException = Schema.Struct({message: Schema.String})
const CopyDestinationImageSet = Schema.Struct({imageSetId: Schema.String, latestVersionId: Schema.String})
const Sort = Schema.Struct({sortOrder: Schema.String, sortField: Schema.String})
const DICOMUpdates = Schema.Struct({removableAttributes: Schema.optional(StreamBody()), updatableAttributes: Schema.optional(StreamBody())})
const DICOMImportJobProperties = Schema.Struct({jobId: Schema.String, jobName: Schema.String, jobStatus: Schema.String, datastoreId: Schema.String, dataAccessRoleArn: Schema.String, endedAt: Schema.optional(Schema.Date), submittedAt: Schema.optional(Schema.Date), inputS3Uri: Schema.String, outputS3Uri: Schema.String, message: Schema.optional(Schema.String)})
const Overrides = Schema.Struct({forced: Schema.optional(Schema.Boolean)})
const DICOMImportJobSummary = Schema.Struct({jobId: Schema.String, jobName: Schema.String, jobStatus: Schema.String, datastoreId: Schema.String, dataAccessRoleArn: Schema.optional(Schema.String), endedAt: Schema.optional(Schema.Date), submittedAt: Schema.optional(Schema.Date), message: Schema.optional(Schema.String)})
const DICOMImportJobSummaries = Schema.Array(DICOMImportJobSummary)
const ImageSetProperties = Schema.Struct({imageSetId: Schema.String, versionId: Schema.String, imageSetState: Schema.String, ImageSetWorkflowStatus: Schema.optional(Schema.String), createdAt: Schema.optional(Schema.Date), updatedAt: Schema.optional(Schema.Date), deletedAt: Schema.optional(Schema.Date), message: Schema.optional(Schema.String), overrides: Schema.optional(Overrides), isPrimary: Schema.optional(Schema.Boolean)})
const ImageSetPropertiesList = Schema.Array(ImageSetProperties)
const MetadataUpdates = Schema.Union(DICOMUpdates, Schema.String)
const MetadataCopies = Schema.Struct({copiableAttributes: Schema.String})
const ConflictException = Schema.Struct({message: Schema.String})
export const DeleteImageSet = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/datastore/{datastoreId}/imageSet/{imageSetId}/deleteImageSet", method: "POST", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "DeleteImageSet" }, DeleteImageSetRequest, DeleteImageSetResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetDICOMImportJobResponse = Schema.Struct({jobProperties: DICOMImportJobProperties})
export const GetDICOMImportJob = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/getDICOMImportJob/datastore/{datastoreId}/job/{jobId}", method: "GET", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "GetDICOMImportJob" }, GetDICOMImportJobRequest, GetDICOMImportJobResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetImageFrameResponse = Schema.Struct({imageFrameBlob: Body("undefined", StreamBody()), contentType: Schema.optional(Header("Content-Type"))})
export const GetImageFrame = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/datastore/{datastoreId}/imageSet/{imageSetId}/getImageFrame", method: "POST", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "GetImageFrame" }, GetImageFrameRequest, GetImageFrameResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetImageSetResponse = Schema.Struct({datastoreId: Schema.String, imageSetId: Schema.String, versionId: Schema.String, imageSetState: Schema.String, imageSetWorkflowStatus: Schema.optional(Schema.String), createdAt: Schema.optional(Schema.Date), updatedAt: Schema.optional(Schema.Date), deletedAt: Schema.optional(Schema.Date), message: Schema.optional(Schema.String), imageSetArn: Schema.optional(Schema.String), overrides: Schema.optional(Overrides), isPrimary: Schema.optional(Schema.Boolean), lastAccessedAt: Schema.optional(Schema.Date), storageTier: Schema.optional(Schema.String)})
export const GetImageSet = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/datastore/{datastoreId}/imageSet/{imageSetId}/getImageSet", method: "POST", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "GetImageSet" }, GetImageSetRequest, GetImageSetResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const InternalServerException = Schema.Struct({message: Schema.String})
export const GetImageSetMetadata = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/datastore/{datastoreId}/imageSet/{imageSetId}/getImageSetMetadata", method: "POST", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "GetImageSetMetadata" }, GetImageSetMetadataRequest, GetImageSetMetadataResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListDICOMImportJobsResponse = Schema.Struct({jobSummaries: DICOMImportJobSummaries, nextToken: Schema.optional(Schema.String)})
export const ListDICOMImportJobs = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/listDICOMImportJobs/datastore/{datastoreId}", method: "GET", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "ListDICOMImportJobs" }, ListDICOMImportJobsRequest, ListDICOMImportJobsResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListImageSetVersionsResponse = Schema.Struct({imageSetPropertiesList: ImageSetPropertiesList, nextToken: Schema.optional(Schema.String)})
export const ListImageSetVersions = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/datastore/{datastoreId}/imageSet/{imageSetId}/listImageSetVersions", method: "POST", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "ListImageSetVersions" }, ListImageSetVersionsRequest, ListImageSetVersionsResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ResourceNotFoundException = Schema.Struct({message: Schema.String})
export const ListTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "GET", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ServiceQuotaExceededException = Schema.Struct({message: Schema.String})
export const StartDICOMImportJob = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/startDICOMImportJob/datastore/{datastoreId}", method: "POST", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "StartDICOMImportJob" }, StartDICOMImportJobRequest, StartDICOMImportJobResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ThrottlingException = Schema.Struct({message: Schema.String})
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "POST", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "TagResource" }, TagResourceRequest, TagResourceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ValidationException = Schema.Struct({message: Schema.String})
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "UntagResource" }, UntagResourceRequest, UntagResourceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateImageSetMetadataRequest = Schema.Struct({datastoreId: Schema.String, imageSetId: Schema.String, latestVersionId: Schema.String, force: Schema.optional(Schema.Boolean), updateImageSetMetadataUpdates: Body("undefined", MetadataUpdates)})
const CopySourceImageSetInformation = Schema.Struct({latestVersionId: Schema.String, DICOMCopies: Schema.optional(MetadataCopies)})
const DICOMStudyDateAndTime = Schema.Struct({DICOMStudyDate: Schema.String, DICOMStudyTime: Schema.optional(Schema.String)})
const CopyImageSetInformation = Schema.Struct({sourceImageSet: CopySourceImageSetInformation, destinationImageSet: Schema.optional(CopyDestinationImageSet)})
const SearchByAttributeValue = Schema.Union(Schema.String, Schema.String, Schema.String, Schema.String, Schema.String, Schema.Date, Schema.Date, DICOMStudyDateAndTime, Schema.Boolean)
const SearchByAttributeValues = Schema.Array(SearchByAttributeValue)
const CopyImageSetRequest = Schema.Struct({datastoreId: Schema.String, sourceImageSetId: Schema.String, copyImageSetInformation: Body("undefined", CopyImageSetInformation), force: Schema.optional(Schema.Boolean), promoteToPrimary: Schema.optional(Schema.Boolean)})
const UpdateImageSetMetadataResponse = Schema.Struct({datastoreId: Schema.String, imageSetId: Schema.String, latestVersionId: Schema.String, imageSetState: Schema.String, imageSetWorkflowStatus: Schema.optional(Schema.String), createdAt: Schema.optional(Schema.Date), updatedAt: Schema.optional(Schema.Date), message: Schema.optional(Schema.String)})
export const UpdateImageSetMetadata = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/datastore/{datastoreId}/imageSet/{imageSetId}/updateImageSetMetadata", method: "POST", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "UpdateImageSetMetadata" }, UpdateImageSetMetadataRequest, UpdateImageSetMetadataResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const SearchFilter = Schema.Struct({values: SearchByAttributeValues, operator: Schema.String})
const SearchFilters = Schema.Array(SearchFilter)
const SearchCriteria = Schema.Struct({filters: Schema.optional(SearchFilters), sort: Schema.optional(Sort)})
const SearchImageSetsRequest = Schema.Struct({datastoreId: Schema.String, searchCriteria: Schema.optional(Body("undefined", SearchCriteria)), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)})
const CopySourceImageSetProperties = Schema.Struct({imageSetId: Schema.String, latestVersionId: Schema.String, imageSetState: Schema.optional(Schema.String), imageSetWorkflowStatus: Schema.optional(Schema.String), createdAt: Schema.optional(Schema.Date), updatedAt: Schema.optional(Schema.Date), imageSetArn: Schema.optional(Schema.String)})
const CopyDestinationImageSetProperties = Schema.Struct({imageSetId: Schema.String, latestVersionId: Schema.String, imageSetState: Schema.optional(Schema.String), imageSetWorkflowStatus: Schema.optional(Schema.String), createdAt: Schema.optional(Schema.Date), updatedAt: Schema.optional(Schema.Date), imageSetArn: Schema.optional(Schema.String)})
const CopyImageSetResponse = Schema.Struct({datastoreId: Schema.String, sourceImageSetProperties: CopySourceImageSetProperties, destinationImageSetProperties: CopyDestinationImageSetProperties})
export const CopyImageSet = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/datastore/{datastoreId}/imageSet/{sourceImageSetId}/copyImageSet", method: "POST", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "CopyImageSet" }, CopyImageSetRequest, CopyImageSetResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DICOMTags = Schema.Struct({DICOMPatientId: Schema.optional(Schema.String), DICOMPatientName: Schema.optional(Schema.String), DICOMPatientBirthDate: Schema.optional(Schema.String), DICOMPatientSex: Schema.optional(Schema.String), DICOMStudyInstanceUID: Schema.optional(Schema.String), DICOMStudyId: Schema.optional(Schema.String), DICOMStudyDescription: Schema.optional(Schema.String), DICOMNumberOfStudyRelatedSeries: Schema.optional(Schema.Number), DICOMNumberOfStudyRelatedInstances: Schema.optional(Schema.Number), DICOMAccessionNumber: Schema.optional(Schema.String), DICOMSeriesInstanceUID: Schema.optional(Schema.String), DICOMSeriesModality: Schema.optional(Schema.String), DICOMSeriesBodyPart: Schema.optional(Schema.String), DICOMSeriesNumber: Schema.optional(Schema.Number), DICOMStudyDate: Schema.optional(Schema.String), DICOMStudyTime: Schema.optional(Schema.String)})
const ImageSetsMetadataSummary = Schema.Struct({imageSetId: Schema.String, version: Schema.optional(Schema.Number), createdAt: Schema.optional(Schema.Date), updatedAt: Schema.optional(Schema.Date), lastAccessedAt: Schema.optional(Schema.Date), storageTier: Schema.optional(Schema.String), DICOMTags: Schema.optional(DICOMTags), isPrimary: Schema.optional(Schema.Boolean)})
const ImageSetsMetadataSummaries = Schema.Array(ImageSetsMetadataSummary)
const SearchImageSetsResponse = Schema.Struct({imageSetsMetadataSummaries: ImageSetsMetadataSummaries, sort: Schema.optional(Sort), nextToken: Schema.optional(Schema.String)})
export const SearchImageSets = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/datastore/{datastoreId}/searchImageSets", method: "POST", sdkId: "Medical Imaging", sigV4ServiceName: "medical-imaging", name: "SearchImageSets" }, SearchImageSetsRequest, SearchImageSetsResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
