import * as S from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const ApplicationIds = S.Array(S.String);
export class CreateProgressUpdateStreamRequest extends S.Class<CreateProgressUpdateStreamRequest>("CreateProgressUpdateStreamRequest")({ProgressUpdateStreamName: S.String, DryRun: S.optional(S.Boolean)}) {}
export class CreateProgressUpdateStreamResult extends S.Class<CreateProgressUpdateStreamResult>("CreateProgressUpdateStreamResult")({}) {}
export class DeleteProgressUpdateStreamRequest extends S.Class<DeleteProgressUpdateStreamRequest>("DeleteProgressUpdateStreamRequest")({ProgressUpdateStreamName: S.String, DryRun: S.optional(S.Boolean)}) {}
export class DeleteProgressUpdateStreamResult extends S.Class<DeleteProgressUpdateStreamResult>("DeleteProgressUpdateStreamResult")({}) {}
export class DescribeApplicationStateRequest extends S.Class<DescribeApplicationStateRequest>("DescribeApplicationStateRequest")({ApplicationId: S.String}) {}
export class DescribeMigrationTaskRequest extends S.Class<DescribeMigrationTaskRequest>("DescribeMigrationTaskRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String}) {}
export class DisassociateCreatedArtifactRequest extends S.Class<DisassociateCreatedArtifactRequest>("DisassociateCreatedArtifactRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, CreatedArtifactName: S.String, DryRun: S.optional(S.Boolean)}) {}
export class DisassociateCreatedArtifactResult extends S.Class<DisassociateCreatedArtifactResult>("DisassociateCreatedArtifactResult")({}) {}
export class DisassociateDiscoveredResourceRequest extends S.Class<DisassociateDiscoveredResourceRequest>("DisassociateDiscoveredResourceRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, ConfigurationId: S.String, DryRun: S.optional(S.Boolean)}) {}
export class DisassociateDiscoveredResourceResult extends S.Class<DisassociateDiscoveredResourceResult>("DisassociateDiscoveredResourceResult")({}) {}
export class DisassociateSourceResourceRequest extends S.Class<DisassociateSourceResourceRequest>("DisassociateSourceResourceRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, SourceResourceName: S.String, DryRun: S.optional(S.Boolean)}) {}
export class DisassociateSourceResourceResult extends S.Class<DisassociateSourceResourceResult>("DisassociateSourceResourceResult")({}) {}
export class ImportMigrationTaskRequest extends S.Class<ImportMigrationTaskRequest>("ImportMigrationTaskRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, DryRun: S.optional(S.Boolean)}) {}
export class ImportMigrationTaskResult extends S.Class<ImportMigrationTaskResult>("ImportMigrationTaskResult")({}) {}
export class ListApplicationStatesRequest extends S.Class<ListApplicationStatesRequest>("ListApplicationStatesRequest")({ApplicationIds: S.optional(ApplicationIds), NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListCreatedArtifactsRequest extends S.Class<ListCreatedArtifactsRequest>("ListCreatedArtifactsRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListDiscoveredResourcesRequest extends S.Class<ListDiscoveredResourcesRequest>("ListDiscoveredResourcesRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListMigrationTasksRequest extends S.Class<ListMigrationTasksRequest>("ListMigrationTasksRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number), ResourceName: S.optional(S.String)}) {}
export class ListMigrationTaskUpdatesRequest extends S.Class<ListMigrationTaskUpdatesRequest>("ListMigrationTaskUpdatesRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListProgressUpdateStreamsRequest extends S.Class<ListProgressUpdateStreamsRequest>("ListProgressUpdateStreamsRequest")({NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class ListSourceResourcesRequest extends S.Class<ListSourceResourcesRequest>("ListSourceResourcesRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, NextToken: S.optional(S.String), MaxResults: S.optional(S.Number)}) {}
export class NotifyApplicationStateRequest extends S.Class<NotifyApplicationStateRequest>("NotifyApplicationStateRequest")({ApplicationId: S.String, Status: S.String, UpdateDateTime: S.optional(S.Date), DryRun: S.optional(S.Boolean)}) {}
export class NotifyApplicationStateResult extends S.Class<NotifyApplicationStateResult>("NotifyApplicationStateResult")({}) {}
export class CreatedArtifact extends S.Class<CreatedArtifact>("CreatedArtifact")({Name: S.String, Description: S.optional(S.String)}) {}
export class DiscoveredResource extends S.Class<DiscoveredResource>("DiscoveredResource")({ConfigurationId: S.String, Description: S.optional(S.String)}) {}
export class SourceResource extends S.Class<SourceResource>("SourceResource")({Name: S.String, Description: S.optional(S.String), StatusDetail: S.optional(S.String)}) {}
export const CreatedArtifactList = S.Array(CreatedArtifact);
export const DiscoveredResourceList = S.Array(DiscoveredResource);
export const SourceResourceList = S.Array(SourceResource);
export class Task extends S.Class<Task>("Task")({Status: S.String, StatusDetail: S.optional(S.String), ProgressPercent: S.optional(S.Number)}) {}
export class ResourceAttribute extends S.Class<ResourceAttribute>("ResourceAttribute")({Type: S.String, Value: S.String}) {}
export const ResourceAttributeList = S.Array(ResourceAttribute);
export class AssociateCreatedArtifactRequest extends S.Class<AssociateCreatedArtifactRequest>("AssociateCreatedArtifactRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, CreatedArtifact: CreatedArtifact, DryRun: S.optional(S.Boolean)}) {}
export class AssociateCreatedArtifactResult extends S.Class<AssociateCreatedArtifactResult>("AssociateCreatedArtifactResult")({}) {}
export class AssociateDiscoveredResourceRequest extends S.Class<AssociateDiscoveredResourceRequest>("AssociateDiscoveredResourceRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, DiscoveredResource: DiscoveredResource, DryRun: S.optional(S.Boolean)}) {}
export class AssociateDiscoveredResourceResult extends S.Class<AssociateDiscoveredResourceResult>("AssociateDiscoveredResourceResult")({}) {}
export class AssociateSourceResourceRequest extends S.Class<AssociateSourceResourceRequest>("AssociateSourceResourceRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, SourceResource: SourceResource, DryRun: S.optional(S.Boolean)}) {}
export class AssociateSourceResourceResult extends S.Class<AssociateSourceResourceResult>("AssociateSourceResourceResult")({}) {}
export class DescribeApplicationStateResult extends S.Class<DescribeApplicationStateResult>("DescribeApplicationStateResult")({ApplicationStatus: S.optional(S.String), LastUpdatedTime: S.optional(S.Date)}) {}
export class ListCreatedArtifactsResult extends S.Class<ListCreatedArtifactsResult>("ListCreatedArtifactsResult")({NextToken: S.optional(S.String), CreatedArtifactList: S.optional(CreatedArtifactList)}) {}
export class ListDiscoveredResourcesResult extends S.Class<ListDiscoveredResourcesResult>("ListDiscoveredResourcesResult")({NextToken: S.optional(S.String), DiscoveredResourceList: S.optional(DiscoveredResourceList)}) {}
export class ListSourceResourcesResult extends S.Class<ListSourceResourcesResult>("ListSourceResourcesResult")({NextToken: S.optional(S.String), SourceResourceList: S.optional(SourceResourceList)}) {}
export class NotifyMigrationTaskStateRequest extends S.Class<NotifyMigrationTaskStateRequest>("NotifyMigrationTaskStateRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, Task: Task, UpdateDateTime: S.Date, NextUpdateSeconds: S.Number, DryRun: S.optional(S.Boolean)}) {}
export class NotifyMigrationTaskStateResult extends S.Class<NotifyMigrationTaskStateResult>("NotifyMigrationTaskStateResult")({}) {}
export class PutResourceAttributesRequest extends S.Class<PutResourceAttributesRequest>("PutResourceAttributesRequest")({ProgressUpdateStream: S.String, MigrationTaskName: S.String, ResourceAttributeList: ResourceAttributeList, DryRun: S.optional(S.Boolean)}) {}
export class PutResourceAttributesResult extends S.Class<PutResourceAttributesResult>("PutResourceAttributesResult")({}) {}
export const LatestResourceAttributeList = S.Array(ResourceAttribute);
export class MigrationTask extends S.Class<MigrationTask>("MigrationTask")({ProgressUpdateStream: S.optional(S.String), MigrationTaskName: S.optional(S.String), Task: S.optional(Task), UpdateDateTime: S.optional(S.Date), ResourceAttributeList: S.optional(LatestResourceAttributeList)}) {}
export class ApplicationState extends S.Class<ApplicationState>("ApplicationState")({ApplicationId: S.optional(S.String), ApplicationStatus: S.optional(S.String), LastUpdatedTime: S.optional(S.Date)}) {}
export const ApplicationStateList = S.Array(ApplicationState);
export class MigrationTaskSummary extends S.Class<MigrationTaskSummary>("MigrationTaskSummary")({ProgressUpdateStream: S.optional(S.String), MigrationTaskName: S.optional(S.String), Status: S.optional(S.String), ProgressPercent: S.optional(S.Number), StatusDetail: S.optional(S.String), UpdateDateTime: S.optional(S.Date)}) {}
export const MigrationTaskSummaryList = S.Array(MigrationTaskSummary);
export class MigrationTaskUpdate extends S.Class<MigrationTaskUpdate>("MigrationTaskUpdate")({UpdateDateTime: S.optional(S.Date), UpdateType: S.optional(S.String), MigrationTaskState: S.optional(Task)}) {}
export const MigrationTaskUpdateList = S.Array(MigrationTaskUpdate);
export class ProgressUpdateStreamSummary extends S.Class<ProgressUpdateStreamSummary>("ProgressUpdateStreamSummary")({ProgressUpdateStreamName: S.optional(S.String)}) {}
export const ProgressUpdateStreamSummaryList = S.Array(ProgressUpdateStreamSummary);
export class DescribeMigrationTaskResult extends S.Class<DescribeMigrationTaskResult>("DescribeMigrationTaskResult")({MigrationTask: S.optional(MigrationTask)}) {}
export class ListApplicationStatesResult extends S.Class<ListApplicationStatesResult>("ListApplicationStatesResult")({ApplicationStateList: S.optional(ApplicationStateList), NextToken: S.optional(S.String)}) {}
export class ListMigrationTasksResult extends S.Class<ListMigrationTasksResult>("ListMigrationTasksResult")({NextToken: S.optional(S.String), MigrationTaskSummaryList: S.optional(MigrationTaskSummaryList)}) {}
export class ListMigrationTaskUpdatesResult extends S.Class<ListMigrationTaskUpdatesResult>("ListMigrationTaskUpdatesResult")({NextToken: S.optional(S.String), MigrationTaskUpdateList: S.optional(MigrationTaskUpdateList)}) {}
export class ListProgressUpdateStreamsResult extends S.Class<ListProgressUpdateStreamsResult>("ListProgressUpdateStreamsResult")({ProgressUpdateStreamSummaryList: S.optional(ProgressUpdateStreamSummaryList), NextToken: S.optional(S.String)}) {}

//# Errors
export class AccessDeniedException extends S.TaggedError<AccessDeniedException>()("AccessDeniedException", {}) {};
export class DryRunOperation extends S.TaggedError<DryRunOperation>()("DryRunOperation", {}) {};
export class HomeRegionNotSetException extends S.TaggedError<HomeRegionNotSetException>()("HomeRegionNotSetException", {}) {};
export class InternalServerError extends S.TaggedError<InternalServerError>()("InternalServerError", {}) {};
export class InvalidInputException extends S.TaggedError<InvalidInputException>()("InvalidInputException", {}) {};
export class ResourceNotFoundException extends S.TaggedError<ResourceNotFoundException>()("ResourceNotFoundException", {}) {};
export class PolicyErrorException extends S.TaggedError<PolicyErrorException>()("PolicyErrorException", {}) {};
export class ServiceUnavailableException extends S.TaggedError<ServiceUnavailableException>()("ServiceUnavailableException", {}) {};
export class ThrottlingException extends S.TaggedError<ThrottlingException>()("ThrottlingException", {}) {};
export class UnauthorizedOperation extends S.TaggedError<UnauthorizedOperation>()("UnauthorizedOperation", {}) {};

//# Operations
export const createProgressUpdateStream = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.CreateProgressUpdateStream" }, CreateProgressUpdateStreamRequest, CreateProgressUpdateStreamResult, [AccessDeniedException, DryRunOperation, HomeRegionNotSetException, InternalServerError, InvalidInputException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteProgressUpdateStream = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.DeleteProgressUpdateStream" }, DeleteProgressUpdateStreamRequest, DeleteProgressUpdateStreamResult, [AccessDeniedException, DryRunOperation, HomeRegionNotSetException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeApplicationState = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.DescribeApplicationState" }, DescribeApplicationStateRequest, DescribeApplicationStateResult, [AccessDeniedException, HomeRegionNotSetException, InternalServerError, InvalidInputException, PolicyErrorException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const disassociateCreatedArtifact = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.DisassociateCreatedArtifact" }, DisassociateCreatedArtifactRequest, DisassociateCreatedArtifactResult, [AccessDeniedException, DryRunOperation, HomeRegionNotSetException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const disassociateDiscoveredResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.DisassociateDiscoveredResource" }, DisassociateDiscoveredResourceRequest, DisassociateDiscoveredResourceResult, [AccessDeniedException, DryRunOperation, HomeRegionNotSetException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const disassociateSourceResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.DisassociateSourceResource" }, DisassociateSourceResourceRequest, DisassociateSourceResourceResult, [AccessDeniedException, DryRunOperation, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const importMigrationTask = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.ImportMigrationTask" }, ImportMigrationTaskRequest, ImportMigrationTaskResult, [AccessDeniedException, DryRunOperation, HomeRegionNotSetException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listCreatedArtifacts = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.ListCreatedArtifacts" }, ListCreatedArtifactsRequest, ListCreatedArtifactsResult, [AccessDeniedException, HomeRegionNotSetException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listDiscoveredResources = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.ListDiscoveredResources" }, ListDiscoveredResourcesRequest, ListDiscoveredResourcesResult, [AccessDeniedException, HomeRegionNotSetException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listSourceResources = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.ListSourceResources" }, ListSourceResourcesRequest, ListSourceResourcesResult, [AccessDeniedException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const notifyApplicationState = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.NotifyApplicationState" }, NotifyApplicationStateRequest, NotifyApplicationStateResult, [AccessDeniedException, DryRunOperation, HomeRegionNotSetException, InternalServerError, InvalidInputException, PolicyErrorException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const notifyMigrationTaskState = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.NotifyMigrationTaskState" }, NotifyMigrationTaskStateRequest, NotifyMigrationTaskStateResult, [AccessDeniedException, DryRunOperation, HomeRegionNotSetException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const putResourceAttributes = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.PutResourceAttributes" }, PutResourceAttributesRequest, PutResourceAttributesResult, [AccessDeniedException, DryRunOperation, HomeRegionNotSetException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const associateCreatedArtifact = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.AssociateCreatedArtifact" }, AssociateCreatedArtifactRequest, AssociateCreatedArtifactResult, [AccessDeniedException, DryRunOperation, HomeRegionNotSetException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const associateDiscoveredResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.AssociateDiscoveredResource" }, AssociateDiscoveredResourceRequest, AssociateDiscoveredResourceResult, [AccessDeniedException, DryRunOperation, HomeRegionNotSetException, InternalServerError, InvalidInputException, PolicyErrorException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const associateSourceResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.AssociateSourceResource" }, AssociateSourceResourceRequest, AssociateSourceResourceResult, [AccessDeniedException, DryRunOperation, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException, UnauthorizedOperation]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeMigrationTask = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.DescribeMigrationTask" }, DescribeMigrationTaskRequest, DescribeMigrationTaskResult, [AccessDeniedException, HomeRegionNotSetException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listApplicationStates = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.ListApplicationStates" }, ListApplicationStatesRequest, ListApplicationStatesResult, [AccessDeniedException, HomeRegionNotSetException, InternalServerError, InvalidInputException, ServiceUnavailableException, ThrottlingException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listMigrationTasks = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.ListMigrationTasks" }, ListMigrationTasksRequest, ListMigrationTasksResult, [AccessDeniedException, HomeRegionNotSetException, InternalServerError, InvalidInputException, PolicyErrorException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listMigrationTaskUpdates = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.ListMigrationTaskUpdates" }, ListMigrationTaskUpdatesRequest, ListMigrationTaskUpdatesResult, [AccessDeniedException, InternalServerError, InvalidInputException, ResourceNotFoundException, ServiceUnavailableException, ThrottlingException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listProgressUpdateStreams = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-05-31", uri: "/", method: "POST", sdkId: "Migration Hub", sigV4ServiceName: "mgh", name: "AWSMigrationHub.ListProgressUpdateStreams" }, ListProgressUpdateStreamsRequest, ListProgressUpdateStreamsResult, [AccessDeniedException, HomeRegionNotSetException, InternalServerError, InvalidInputException, ServiceUnavailableException, ThrottlingException]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
