import { Schema} from "effect"
import { FormatXMLRequest, FormatXMLResponse, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
const TagKeyList = Schema.Array(Schema.String)
const CreateCliTokenRequest = Schema.Struct({Name: Schema.String})
const CreateWebLoginTokenRequest = Schema.Struct({Name: Schema.String})
const DeleteEnvironmentInput = Schema.Struct({Name: Schema.String})
const DeleteEnvironmentOutput = Schema.Struct({})
const GetEnvironmentInput = Schema.Struct({Name: Schema.String})
const InvokeRestApiRequest = Schema.Struct({Name: Schema.String, Path: Schema.String, Method: Schema.String, QueryParameters: Schema.optional(Schema.JsonValue), Body: Schema.optional(Schema.JsonValue)})
const ListEnvironmentsInput = Schema.Struct({NextToken: Schema.optional(Schema.String), MaxResults: Schema.optional(Schema.Number)})
const ListTagsForResourceInput = Schema.Struct({ResourceArn: Schema.String})
const TagResourceInput = Schema.Struct({ResourceArn: Schema.String, Tags: TagMap})
const TagResourceOutput = Schema.Struct({})
const UntagResourceInput = Schema.Struct({ResourceArn: Schema.String, tagKeys: TagKeyList})
const UntagResourceOutput = Schema.Struct({})
const SubnetList = Schema.Array(Schema.String)
const SecurityGroupList = Schema.Array(Schema.String)
const NetworkConfiguration = Schema.Struct({SubnetIds: Schema.optional(SubnetList), SecurityGroupIds: Schema.optional(SecurityGroupList)})
const AirflowConfigurationOptions = Schema.Record({key: Schema.String, value: Schema.String})
const TagMap = Schema.Record({key: Schema.String, value: Schema.String})
const EnvironmentList = Schema.Array(Schema.String)
const UpdateNetworkConfigurationInput = Schema.Struct({SecurityGroupIds: SecurityGroupList})
const CreateCliTokenResponse = Schema.Struct({CliToken: Schema.optional(Schema.String), WebServerHostname: Schema.optional(Schema.String)})
export const CreateCliToken = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/clitoken/{Name}", method: "POST", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "CreateCliToken" }, CreateCliTokenRequest, CreateCliTokenResponse, ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException)), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateWebLoginTokenResponse = Schema.Struct({WebToken: Schema.optional(Schema.String), WebServerHostname: Schema.optional(Schema.String), IamIdentity: Schema.optional(Schema.String), AirflowIdentity: Schema.optional(Schema.String)})
const InternalServerException = Schema.Struct({message: Schema.optional(Schema.String)})
export const DeleteEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/environments/{Name}", method: "DELETE", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "DeleteEnvironment" }, DeleteEnvironmentInput, DeleteEnvironmentOutput, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const InvokeRestApiResponse = Schema.Struct({RestApiStatusCode: Schema.optional(Schema.Number), RestApiResponse: Schema.optional(Schema.JsonValue)})
const ListEnvironmentsOutput = Schema.Struct({Environments: EnvironmentList, NextToken: Schema.optional(Schema.String)})
export const ListEnvironments = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/environments", method: "GET", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "ListEnvironments" }, ListEnvironmentsInput, ListEnvironmentsOutput, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListTagsForResourceOutput = Schema.Struct({Tags: Schema.optional(TagMap)})
export const ListTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{ResourceArn}", method: "GET", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "ListTagsForResource" }, ListTagsForResourceInput, ListTagsForResourceOutput, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ResourceNotFoundException = Schema.Struct({message: Schema.optional(Schema.String)})
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{ResourceArn}", method: "POST", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "TagResource" }, TagResourceInput, TagResourceOutput, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ValidationException = Schema.Struct({message: Schema.optional(Schema.String)})
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{ResourceArn}", method: "DELETE", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "UntagResource" }, UntagResourceInput, UntagResourceOutput, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateEnvironmentInput = Schema.Struct({Name: Schema.String, ExecutionRoleArn: Schema.optional(Schema.String), AirflowConfigurationOptions: Schema.optional(AirflowConfigurationOptions), AirflowVersion: Schema.optional(Schema.String), DagS3Path: Schema.optional(Schema.String), EnvironmentClass: Schema.optional(Schema.String), LoggingConfiguration: Schema.optional(LoggingConfigurationInput), MaxWorkers: Schema.optional(Schema.Number), MinWorkers: Schema.optional(Schema.Number), MaxWebservers: Schema.optional(Schema.Number), MinWebservers: Schema.optional(Schema.Number), WorkerReplacementStrategy: Schema.optional(Schema.String), NetworkConfiguration: Schema.optional(UpdateNetworkConfigurationInput), PluginsS3Path: Schema.optional(Schema.String), PluginsS3ObjectVersion: Schema.optional(Schema.String), RequirementsS3Path: Schema.optional(Schema.String), RequirementsS3ObjectVersion: Schema.optional(Schema.String), Schedulers: Schema.optional(Schema.Number), SourceBucketArn: Schema.optional(Schema.String), StartupScriptS3Path: Schema.optional(Schema.String), StartupScriptS3ObjectVersion: Schema.optional(Schema.String), WebserverAccessMode: Schema.optional(Schema.String), WeeklyMaintenanceWindowStart: Schema.optional(Schema.String)})
const ModuleLoggingConfigurationInput = Schema.Struct({Enabled: Schema.Boolean, LogLevel: Schema.String})
const Dimension = Schema.Struct({Name: Schema.String, Value: Schema.String})
const Dimensions = Schema.Array(Dimension)
const StatisticSet = Schema.Struct({SampleCount: Schema.optional(Schema.Number), Sum: Schema.optional(Schema.Number), Minimum: Schema.optional(Schema.Number), Maximum: Schema.optional(Schema.Number)})
const LoggingConfigurationInput = Schema.Struct({DagProcessingLogs: Schema.optional(ModuleLoggingConfigurationInput), SchedulerLogs: Schema.optional(ModuleLoggingConfigurationInput), WebserverLogs: Schema.optional(ModuleLoggingConfigurationInput), WorkerLogs: Schema.optional(ModuleLoggingConfigurationInput), TaskLogs: Schema.optional(ModuleLoggingConfigurationInput)})
const MetricDatum = Schema.Struct({MetricName: Schema.String, Timestamp: Schema.Date, Dimensions: Schema.optional(Dimensions), Value: Schema.optional(Schema.Number), Unit: Schema.optional(Schema.String), StatisticValues: Schema.optional(StatisticSet)})
const MetricData = Schema.Array(MetricDatum)
const CreateEnvironmentInput = Schema.Struct({Name: Schema.String, ExecutionRoleArn: Schema.String, SourceBucketArn: Schema.String, DagS3Path: Schema.String, NetworkConfiguration: NetworkConfiguration, PluginsS3Path: Schema.optional(Schema.String), PluginsS3ObjectVersion: Schema.optional(Schema.String), RequirementsS3Path: Schema.optional(Schema.String), RequirementsS3ObjectVersion: Schema.optional(Schema.String), StartupScriptS3Path: Schema.optional(Schema.String), StartupScriptS3ObjectVersion: Schema.optional(Schema.String), AirflowConfigurationOptions: Schema.optional(AirflowConfigurationOptions), EnvironmentClass: Schema.optional(Schema.String), MaxWorkers: Schema.optional(Schema.Number), KmsKey: Schema.optional(Schema.String), AirflowVersion: Schema.optional(Schema.String), LoggingConfiguration: Schema.optional(LoggingConfigurationInput), WeeklyMaintenanceWindowStart: Schema.optional(Schema.String), Tags: Schema.optional(TagMap), WebserverAccessMode: Schema.optional(Schema.String), MinWorkers: Schema.optional(Schema.Number), Schedulers: Schema.optional(Schema.Number), EndpointManagement: Schema.optional(Schema.String), MinWebservers: Schema.optional(Schema.Number), MaxWebservers: Schema.optional(Schema.Number)})
const AccessDeniedException = Schema.Struct({Message: Schema.optional(Schema.String)})
export const CreateWebLoginToken = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/webtoken/{Name}", method: "POST", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "CreateWebLoginToken" }, CreateWebLoginTokenRequest, CreateWebLoginTokenResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const RestApiClientException = Schema.Struct({RestApiStatusCode: Schema.optional(Schema.Number), RestApiResponse: Schema.optional(Schema.JsonValue)})
const PublishMetricsInput = Schema.Struct({EnvironmentName: Schema.String, MetricData: MetricData})
const PublishMetricsOutput = Schema.Struct({})
export const PublishMetrics = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/metrics/environments/{EnvironmentName}", method: "POST", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "PublishMetrics" }, PublishMetricsInput, PublishMetricsOutput, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateEnvironmentOutput = Schema.Struct({Arn: Schema.optional(Schema.String)})
export const UpdateEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/environments/{Name}", method: "PATCH", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "UpdateEnvironment" }, UpdateEnvironmentInput, UpdateEnvironmentOutput, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ModuleLoggingConfiguration = Schema.Struct({Enabled: Schema.optional(Schema.Boolean), LogLevel: Schema.optional(Schema.String), CloudWatchLogGroupArn: Schema.optional(Schema.String)})
const UpdateError = Schema.Struct({ErrorCode: Schema.optional(Schema.String), ErrorMessage: Schema.optional(Schema.String)})
const CreateEnvironmentOutput = Schema.Struct({Arn: Schema.optional(Schema.String)})
export const CreateEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/environments/{Name}", method: "PUT", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "CreateEnvironment" }, CreateEnvironmentInput, CreateEnvironmentOutput, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const RestApiServerException = Schema.Struct({RestApiStatusCode: Schema.optional(Schema.Number), RestApiResponse: Schema.optional(Schema.JsonValue)})
export const InvokeRestApi = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/restapi/{Name}", method: "POST", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "InvokeRestApi" }, InvokeRestApiRequest, InvokeRestApiResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("RestApiClientException", RestApiClientException), ErrorAnnotation("RestApiServerException", RestApiServerException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const LoggingConfiguration = Schema.Struct({DagProcessingLogs: Schema.optional(ModuleLoggingConfiguration), SchedulerLogs: Schema.optional(ModuleLoggingConfiguration), WebserverLogs: Schema.optional(ModuleLoggingConfiguration), WorkerLogs: Schema.optional(ModuleLoggingConfiguration), TaskLogs: Schema.optional(ModuleLoggingConfiguration)})
const LastUpdate = Schema.Struct({Status: Schema.optional(Schema.String), CreatedAt: Schema.optional(Schema.Date), Error: Schema.optional(UpdateError), Source: Schema.optional(Schema.String), WorkerReplacementStrategy: Schema.optional(Schema.String)})
const Environment = Schema.Struct({Name: Schema.optional(Schema.String), Status: Schema.optional(Schema.String), Arn: Schema.optional(Schema.String), CreatedAt: Schema.optional(Schema.Date), WebserverUrl: Schema.optional(Schema.String), ExecutionRoleArn: Schema.optional(Schema.String), ServiceRoleArn: Schema.optional(Schema.String), KmsKey: Schema.optional(Schema.String), AirflowVersion: Schema.optional(Schema.String), SourceBucketArn: Schema.optional(Schema.String), DagS3Path: Schema.optional(Schema.String), PluginsS3Path: Schema.optional(Schema.String), PluginsS3ObjectVersion: Schema.optional(Schema.String), RequirementsS3Path: Schema.optional(Schema.String), RequirementsS3ObjectVersion: Schema.optional(Schema.String), StartupScriptS3Path: Schema.optional(Schema.String), StartupScriptS3ObjectVersion: Schema.optional(Schema.String), AirflowConfigurationOptions: Schema.optional(AirflowConfigurationOptions), EnvironmentClass: Schema.optional(Schema.String), MaxWorkers: Schema.optional(Schema.Number), NetworkConfiguration: Schema.optional(NetworkConfiguration), LoggingConfiguration: Schema.optional(LoggingConfiguration), LastUpdate: Schema.optional(LastUpdate), WeeklyMaintenanceWindowStart: Schema.optional(Schema.String), Tags: Schema.optional(TagMap), WebserverAccessMode: Schema.optional(Schema.String), MinWorkers: Schema.optional(Schema.Number), Schedulers: Schema.optional(Schema.Number), WebserverVpcEndpointService: Schema.optional(Schema.String), DatabaseVpcEndpointService: Schema.optional(Schema.String), CeleryExecutorQueue: Schema.optional(Schema.String), EndpointManagement: Schema.optional(Schema.String), MinWebservers: Schema.optional(Schema.Number), MaxWebservers: Schema.optional(Schema.Number)})
const GetEnvironmentOutput = Schema.Struct({Environment: Schema.optional(Environment)})
export const GetEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/environments/{Name}", method: "GET", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "GetEnvironment" }, GetEnvironmentInput, GetEnvironmentOutput, Schema.Union(ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
