import * as Schema from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import { Operation, Path, Header, StreamBody, Body } from "../schema-helpers.ts";

//# Schemas
export const TagKeyList = Schema.Array(Schema.String);
export class CreateCliTokenRequest extends Schema.Class<CreateCliTokenRequest>("CreateCliTokenRequest")({Name: Schema.String}) {}
export class CreateWebLoginTokenRequest extends Schema.Class<CreateWebLoginTokenRequest>("CreateWebLoginTokenRequest")({Name: Schema.String}) {}
export class DeleteEnvironmentInput extends Schema.Class<DeleteEnvironmentInput>("DeleteEnvironmentInput")({Name: Schema.String}) {}
export class DeleteEnvironmentOutput extends Schema.Class<DeleteEnvironmentOutput>("DeleteEnvironmentOutput")({}) {}
export class GetEnvironmentInput extends Schema.Class<GetEnvironmentInput>("GetEnvironmentInput")({Name: Schema.String}) {}
export class InvokeRestApiRequest extends Schema.Class<InvokeRestApiRequest>("InvokeRestApiRequest")({Name: Schema.String, Path: Schema.String, Method: Schema.String, QueryParameters: Schema.optional(Schema.Any), Body: Schema.optional(Schema.JsonValue)}) {}
export class ListEnvironmentsInput extends Schema.Class<ListEnvironmentsInput>("ListEnvironmentsInput")({NextToken: Schema.optional(Schema.String), MaxResults: Schema.optional(Schema.Number)}) {}
export class ListTagsForResourceInput extends Schema.Class<ListTagsForResourceInput>("ListTagsForResourceInput")({ResourceArn: Schema.String}) {}
export const TagMap = Schema.Record({key: Schema.String, value: Schema.String});
export class TagResourceInput extends Schema.Class<TagResourceInput>("TagResourceInput")({ResourceArn: Schema.String, Tags: TagMap}) {}
export class TagResourceOutput extends Schema.Class<TagResourceOutput>("TagResourceOutput")({}) {}
export class UntagResourceInput extends Schema.Class<UntagResourceInput>("UntagResourceInput")({ResourceArn: Schema.String, tagKeys: TagKeyList}) {}
export class UntagResourceOutput extends Schema.Class<UntagResourceOutput>("UntagResourceOutput")({}) {}
export const SubnetList = Schema.Array(Schema.String);
export const SecurityGroupList = Schema.Array(Schema.String);
export class NetworkConfiguration extends Schema.Class<NetworkConfiguration>("NetworkConfiguration")({SubnetIds: Schema.optional(SubnetList), SecurityGroupIds: Schema.optional(SecurityGroupList)}) {}
export const AirflowConfigurationOptions = Schema.Record({key: Schema.String, value: Schema.String});
export const EnvironmentList = Schema.Array(Schema.String);
export class UpdateNetworkConfigurationInput extends Schema.Class<UpdateNetworkConfigurationInput>("UpdateNetworkConfigurationInput")({SecurityGroupIds: SecurityGroupList}) {}
export class CreateCliTokenResponse extends Schema.Class<CreateCliTokenResponse>("CreateCliTokenResponse")({CliToken: Schema.optional(Schema.String), WebServerHostname: Schema.optional(Schema.String)}) {}
export class CreateWebLoginTokenResponse extends Schema.Class<CreateWebLoginTokenResponse>("CreateWebLoginTokenResponse")({WebToken: Schema.optional(Schema.String), WebServerHostname: Schema.optional(Schema.String), IamIdentity: Schema.optional(Schema.String), AirflowIdentity: Schema.optional(Schema.String)}) {}
export class InternalServerException extends Schema.Class<InternalServerException>("InternalServerException")({message: Schema.optional(Schema.String)}) {}
export class InvokeRestApiResponse extends Schema.Class<InvokeRestApiResponse>("InvokeRestApiResponse")({RestApiStatusCode: Schema.optional(Schema.Number), RestApiResponse: Schema.optional(Schema.JsonValue)}) {}
export class ListEnvironmentsOutput extends Schema.Class<ListEnvironmentsOutput>("ListEnvironmentsOutput")({Environments: EnvironmentList, NextToken: Schema.optional(Schema.String)}) {}
export class ListTagsForResourceOutput extends Schema.Class<ListTagsForResourceOutput>("ListTagsForResourceOutput")({Tags: Schema.optional(TagMap)}) {}
export class ResourceNotFoundException extends Schema.Class<ResourceNotFoundException>("ResourceNotFoundException")({message: Schema.optional(Schema.String)}) {}
export class ValidationException extends Schema.Class<ValidationException>("ValidationException")({message: Schema.optional(Schema.String)}) {}
export class ModuleLoggingConfigurationInput extends Schema.Class<ModuleLoggingConfigurationInput>("ModuleLoggingConfigurationInput")({Enabled: Schema.Boolean, LogLevel: Schema.String}) {}
export class LoggingConfigurationInput extends Schema.Class<LoggingConfigurationInput>("LoggingConfigurationInput")({DagProcessingLogs: Schema.optional(ModuleLoggingConfigurationInput), SchedulerLogs: Schema.optional(ModuleLoggingConfigurationInput), WebserverLogs: Schema.optional(ModuleLoggingConfigurationInput), WorkerLogs: Schema.optional(ModuleLoggingConfigurationInput), TaskLogs: Schema.optional(ModuleLoggingConfigurationInput)}) {}
export class UpdateEnvironmentInput extends Schema.Class<UpdateEnvironmentInput>("UpdateEnvironmentInput")({Name: Schema.String, ExecutionRoleArn: Schema.optional(Schema.String), AirflowConfigurationOptions: Schema.optional(AirflowConfigurationOptions), AirflowVersion: Schema.optional(Schema.String), DagS3Path: Schema.optional(Schema.String), EnvironmentClass: Schema.optional(Schema.String), LoggingConfiguration: Schema.optional(LoggingConfigurationInput), MaxWorkers: Schema.optional(Schema.Number), MinWorkers: Schema.optional(Schema.Number), MaxWebservers: Schema.optional(Schema.Number), MinWebservers: Schema.optional(Schema.Number), WorkerReplacementStrategy: Schema.optional(Schema.String), NetworkConfiguration: Schema.optional(UpdateNetworkConfigurationInput), PluginsS3Path: Schema.optional(Schema.String), PluginsS3ObjectVersion: Schema.optional(Schema.String), RequirementsS3Path: Schema.optional(Schema.String), RequirementsS3ObjectVersion: Schema.optional(Schema.String), Schedulers: Schema.optional(Schema.Number), SourceBucketArn: Schema.optional(Schema.String), StartupScriptS3Path: Schema.optional(Schema.String), StartupScriptS3ObjectVersion: Schema.optional(Schema.String), WebserverAccessMode: Schema.optional(Schema.String), WeeklyMaintenanceWindowStart: Schema.optional(Schema.String)}) {}
export class Dimension extends Schema.Class<Dimension>("Dimension")({Name: Schema.String, Value: Schema.String}) {}
export const Dimensions = Schema.Array(Dimension);
export class StatisticSet extends Schema.Class<StatisticSet>("StatisticSet")({SampleCount: Schema.optional(Schema.Number), Sum: Schema.optional(Schema.Number), Minimum: Schema.optional(Schema.Number), Maximum: Schema.optional(Schema.Number)}) {}
export class MetricDatum extends Schema.Class<MetricDatum>("MetricDatum")({MetricName: Schema.String, Timestamp: Schema.Date, Dimensions: Schema.optional(Dimensions), Value: Schema.optional(Schema.Number), Unit: Schema.optional(Schema.String), StatisticValues: Schema.optional(StatisticSet)}) {}
export const MetricData = Schema.Array(MetricDatum);
export class CreateEnvironmentInput extends Schema.Class<CreateEnvironmentInput>("CreateEnvironmentInput")({Name: Schema.String, ExecutionRoleArn: Schema.String, SourceBucketArn: Schema.String, DagS3Path: Schema.String, NetworkConfiguration: NetworkConfiguration, PluginsS3Path: Schema.optional(Schema.String), PluginsS3ObjectVersion: Schema.optional(Schema.String), RequirementsS3Path: Schema.optional(Schema.String), RequirementsS3ObjectVersion: Schema.optional(Schema.String), StartupScriptS3Path: Schema.optional(Schema.String), StartupScriptS3ObjectVersion: Schema.optional(Schema.String), AirflowConfigurationOptions: Schema.optional(AirflowConfigurationOptions), EnvironmentClass: Schema.optional(Schema.String), MaxWorkers: Schema.optional(Schema.Number), KmsKey: Schema.optional(Schema.String), AirflowVersion: Schema.optional(Schema.String), LoggingConfiguration: Schema.optional(LoggingConfigurationInput), WeeklyMaintenanceWindowStart: Schema.optional(Schema.String), Tags: Schema.optional(TagMap), WebserverAccessMode: Schema.optional(Schema.String), MinWorkers: Schema.optional(Schema.Number), Schedulers: Schema.optional(Schema.Number), EndpointManagement: Schema.optional(Schema.String), MinWebservers: Schema.optional(Schema.Number), MaxWebservers: Schema.optional(Schema.Number)}) {}
export class AccessDeniedException extends Schema.Class<AccessDeniedException>("AccessDeniedException")({Message: Schema.optional(Schema.String)}) {}
export class RestApiClientException extends Schema.Class<RestApiClientException>("RestApiClientException")({RestApiStatusCode: Schema.optional(Schema.Number), RestApiResponse: Schema.optional(Schema.JsonValue)}) {}
export class PublishMetricsInput extends Schema.Class<PublishMetricsInput>("PublishMetricsInput")({EnvironmentName: Schema.String, MetricData: MetricData}) {}
export class PublishMetricsOutput extends Schema.Class<PublishMetricsOutput>("PublishMetricsOutput")({}) {}
export class UpdateEnvironmentOutput extends Schema.Class<UpdateEnvironmentOutput>("UpdateEnvironmentOutput")({Arn: Schema.optional(Schema.String)}) {}
export class ModuleLoggingConfiguration extends Schema.Class<ModuleLoggingConfiguration>("ModuleLoggingConfiguration")({Enabled: Schema.optional(Schema.Boolean), LogLevel: Schema.optional(Schema.String), CloudWatchLogGroupArn: Schema.optional(Schema.String)}) {}
export class UpdateError extends Schema.Class<UpdateError>("UpdateError")({ErrorCode: Schema.optional(Schema.String), ErrorMessage: Schema.optional(Schema.String)}) {}
export class CreateEnvironmentOutput extends Schema.Class<CreateEnvironmentOutput>("CreateEnvironmentOutput")({Arn: Schema.optional(Schema.String)}) {}
export class RestApiServerException extends Schema.Class<RestApiServerException>("RestApiServerException")({RestApiStatusCode: Schema.optional(Schema.Number), RestApiResponse: Schema.optional(Schema.JsonValue)}) {}
export class LoggingConfiguration extends Schema.Class<LoggingConfiguration>("LoggingConfiguration")({DagProcessingLogs: Schema.optional(ModuleLoggingConfiguration), SchedulerLogs: Schema.optional(ModuleLoggingConfiguration), WebserverLogs: Schema.optional(ModuleLoggingConfiguration), WorkerLogs: Schema.optional(ModuleLoggingConfiguration), TaskLogs: Schema.optional(ModuleLoggingConfiguration)}) {}
export class LastUpdate extends Schema.Class<LastUpdate>("LastUpdate")({Status: Schema.optional(Schema.String), CreatedAt: Schema.optional(Schema.Date), Error: Schema.optional(UpdateError), Source: Schema.optional(Schema.String), WorkerReplacementStrategy: Schema.optional(Schema.String)}) {}
export class Environment extends Schema.Class<Environment>("Environment")({Name: Schema.optional(Schema.String), Status: Schema.optional(Schema.String), Arn: Schema.optional(Schema.String), CreatedAt: Schema.optional(Schema.Date), WebserverUrl: Schema.optional(Schema.String), ExecutionRoleArn: Schema.optional(Schema.String), ServiceRoleArn: Schema.optional(Schema.String), KmsKey: Schema.optional(Schema.String), AirflowVersion: Schema.optional(Schema.String), SourceBucketArn: Schema.optional(Schema.String), DagS3Path: Schema.optional(Schema.String), PluginsS3Path: Schema.optional(Schema.String), PluginsS3ObjectVersion: Schema.optional(Schema.String), RequirementsS3Path: Schema.optional(Schema.String), RequirementsS3ObjectVersion: Schema.optional(Schema.String), StartupScriptS3Path: Schema.optional(Schema.String), StartupScriptS3ObjectVersion: Schema.optional(Schema.String), AirflowConfigurationOptions: Schema.optional(AirflowConfigurationOptions), EnvironmentClass: Schema.optional(Schema.String), MaxWorkers: Schema.optional(Schema.Number), NetworkConfiguration: Schema.optional(NetworkConfiguration), LoggingConfiguration: Schema.optional(LoggingConfiguration), LastUpdate: Schema.optional(LastUpdate), WeeklyMaintenanceWindowStart: Schema.optional(Schema.String), Tags: Schema.optional(TagMap), WebserverAccessMode: Schema.optional(Schema.String), MinWorkers: Schema.optional(Schema.Number), Schedulers: Schema.optional(Schema.Number), WebserverVpcEndpointService: Schema.optional(Schema.String), DatabaseVpcEndpointService: Schema.optional(Schema.String), CeleryExecutorQueue: Schema.optional(Schema.String), EndpointManagement: Schema.optional(Schema.String), MinWebservers: Schema.optional(Schema.Number), MaxWebservers: Schema.optional(Schema.Number)}) {}
export class GetEnvironmentOutput extends Schema.Class<GetEnvironmentOutput>("GetEnvironmentOutput")({Environment: Schema.optional(Environment)}) {}

//# Errors
export class InternalServerExceptionError extends Schema.TaggedError<InternalServerExceptionError>()("InternalServerException", InternalServerException.fields) {};
export class ResourceNotFoundExceptionError extends Schema.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ValidationExceptionError extends Schema.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};
export class AccessDeniedExceptionError extends Schema.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class RestApiClientExceptionError extends Schema.TaggedError<RestApiClientExceptionError>()("RestApiClientException", RestApiClientException.fields) {};
export class RestApiServerExceptionError extends Schema.TaggedError<RestApiServerExceptionError>()("RestApiServerException", RestApiServerException.fields) {};

//# Operations
export const createCliToken = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/clitoken/{Name}", method: "POST", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.CreateCliToken" }, CreateCliTokenRequest, CreateCliTokenResponse, [ResourceNotFoundExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/environments/{Name}", method: "DELETE", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.DeleteEnvironment" }, DeleteEnvironmentInput, DeleteEnvironmentOutput, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listEnvironments = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/environments", method: "GET", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.ListEnvironments" }, ListEnvironmentsInput, ListEnvironmentsOutput, [InternalServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/tags/{ResourceArn}", method: "GET", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.ListTagsForResource" }, ListTagsForResourceInput, ListTagsForResourceOutput, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/tags/{ResourceArn}", method: "POST", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.TagResource" }, TagResourceInput, TagResourceOutput, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/tags/{ResourceArn}", method: "DELETE", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.UntagResource" }, UntagResourceInput, UntagResourceOutput, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createWebLoginToken = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/webtoken/{Name}", method: "POST", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.CreateWebLoginToken" }, CreateWebLoginTokenRequest, CreateWebLoginTokenResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const publishMetrics = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/metrics/environments/{EnvironmentName}", method: "POST", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.PublishMetrics" }, PublishMetricsInput, PublishMetricsOutput, [InternalServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/environments/{Name}", method: "PATCH", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.UpdateEnvironment" }, UpdateEnvironmentInput, UpdateEnvironmentOutput, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/environments/{Name}", method: "PUT", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.CreateEnvironment" }, CreateEnvironmentInput, CreateEnvironmentOutput, [InternalServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const invokeRestApi = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/restapi/{Name}", method: "POST", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.InvokeRestApi" }, InvokeRestApiRequest, InvokeRestApiResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, RestApiClientExceptionError, RestApiServerExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-07-01", uri: "/environments/{Name}", method: "GET", sdkId: "MWAA", sigV4ServiceName: "airflow", name: "AmazonMWAA.GetEnvironment" }, GetEnvironmentInput, GetEnvironmentOutput, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
