import { Schema} from "effect"
import { FormatXMLRequest, FormatXMLResponse, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
const DeleteS3AccessPolicyRequest = Schema.Struct({s3AccessPointArn: Schema.String})
const DeleteS3AccessPolicyResponse = Schema.Struct({})
const GetS3AccessPolicyRequest = Schema.Struct({s3AccessPointArn: Schema.String})
const PutS3AccessPolicyRequest = Schema.Struct({s3AccessPointArn: Schema.String, s3AccessPolicy: Schema.String})
const AccessDeniedException = Schema.Struct({message: Schema.String})
const GetS3AccessPolicyResponse = Schema.Struct({s3AccessPointArn: Schema.optional(Schema.String), storeId: Schema.optional(Schema.String), storeType: Schema.optional(Schema.String), updateTime: Schema.optional(Schema.Date), s3AccessPolicy: Schema.String})
const PutS3AccessPolicyResponse = Schema.Struct({s3AccessPointArn: Schema.optional(Schema.String), storeId: Schema.optional(Schema.String), storeType: Schema.optional(Schema.String)})
const InternalServerException = Schema.Struct({message: Schema.String})
const NotSupportedOperationException = Schema.Struct({message: Schema.String})
const RequestTimeoutException = Schema.Struct({message: Schema.String})
const ResourceNotFoundException = Schema.Struct({message: Schema.String})
const ServiceQuotaExceededException = Schema.Struct({message: Schema.String})
export const GetS3AccessPolicy = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/s3accesspolicy/{s3AccessPointArn}", method: "GET", sdkId: "Omics", sigV4ServiceName: "omics", name: "GetS3AccessPolicy" }, GetS3AccessPolicyRequest, GetS3AccessPolicyResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("NotSupportedOperationException", NotSupportedOperationException), ErrorAnnotation("RequestTimeoutException", RequestTimeoutException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ThrottlingException = Schema.Struct({message: Schema.String})
export const PutS3AccessPolicy = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/s3accesspolicy/{s3AccessPointArn}", method: "PUT", sdkId: "Omics", sigV4ServiceName: "omics", name: "PutS3AccessPolicy" }, PutS3AccessPolicyRequest, PutS3AccessPolicyResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("NotSupportedOperationException", NotSupportedOperationException), ErrorAnnotation("RequestTimeoutException", RequestTimeoutException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ValidationException = Schema.Struct({message: Schema.String})
export const DeleteS3AccessPolicy = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/s3accesspolicy/{s3AccessPointArn}", method: "DELETE", sdkId: "Omics", sigV4ServiceName: "omics", name: "DeleteS3AccessPolicy" }, DeleteS3AccessPolicyRequest, DeleteS3AccessPolicyResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("NotSupportedOperationException", NotSupportedOperationException), ErrorAnnotation("RequestTimeoutException", RequestTimeoutException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
