import { Schema} from "effect"
import { FormatXMLRequest, FormatXMLResponse, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
const DeleteCategoryInputList = Schema.Array(Schema.String)
const CategoryIdList = Schema.Array(Schema.String)
const TagKeys = Schema.Array(Schema.String)
const AssociateLibraryItemReviewInput = Schema.Struct({instanceId: Header("instance-id"), libraryItemId: Schema.String})
const AssociateQAppWithUserInput = Schema.Struct({instanceId: Header("instance-id"), appId: Schema.String})
const BatchDeleteCategoryInput = Schema.Struct({instanceId: Header("instance-id"), categories: DeleteCategoryInputList})
const CreateLibraryItemInput = Schema.Struct({instanceId: Header("instance-id"), appId: Schema.String, appVersion: Schema.Number, categories: CategoryIdList})
const CreatePresignedUrlInput = Schema.Struct({instanceId: Header("instance-id"), cardId: Schema.String, appId: Schema.String, fileContentsSha256: Schema.String, fileName: Schema.String, scope: Schema.String, sessionId: Schema.optional(Schema.String)})
const DeleteLibraryItemInput = Schema.Struct({instanceId: Header("instance-id"), libraryItemId: Schema.String})
const DeleteQAppInput = Schema.Struct({instanceId: Header("instance-id"), appId: Schema.String})
const DescribeQAppPermissionsInput = Schema.Struct({instanceId: Header("instance-id"), appId: Schema.String})
const DisassociateLibraryItemReviewInput = Schema.Struct({instanceId: Header("instance-id"), libraryItemId: Schema.String})
const DisassociateQAppFromUserInput = Schema.Struct({instanceId: Header("instance-id"), appId: Schema.String})
const ExportQAppSessionDataInput = Schema.Struct({instanceId: Header("instance-id"), sessionId: Schema.String})
const GetLibraryItemInput = Schema.Struct({instanceId: Header("instance-id"), libraryItemId: Schema.String, appId: Schema.optional(Schema.String)})
const GetQAppInput = Schema.Struct({instanceId: Header("instance-id"), appId: Schema.String, appVersion: Schema.optional(Schema.Number)})
const GetQAppSessionInput = Schema.Struct({instanceId: Header("instance-id"), sessionId: Schema.String})
const GetQAppSessionMetadataInput = Schema.Struct({instanceId: Header("instance-id"), sessionId: Schema.String})
const ImportDocumentInput = Schema.Struct({instanceId: Header("instance-id"), cardId: Schema.String, appId: Schema.String, fileContentsBase64: Schema.String, fileName: Schema.String, scope: Schema.String, sessionId: Schema.optional(Schema.String)})
const ListCategoriesInput = Schema.Struct({instanceId: Header("instance-id")})
const ListLibraryItemsInput = Schema.Struct({instanceId: Header("instance-id"), limit: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String), categoryId: Schema.optional(Schema.String)})
const ListQAppsInput = Schema.Struct({instanceId: Header("instance-id"), limit: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)})
const ListQAppSessionDataInput = Schema.Struct({instanceId: Header("instance-id"), sessionId: Schema.String})
const ListTagsForResourceRequest = Schema.Struct({resourceARN: Schema.String})
const StopQAppSessionInput = Schema.Struct({instanceId: Header("instance-id"), sessionId: Schema.String})
const UntagResourceRequest = Schema.Struct({resourceARN: Schema.String, tagKeys: TagKeys})
const UntagResourceResponse = Schema.Struct({})
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceARN}", method: "DELETE", sdkId: "QApps", sigV4ServiceName: "qapps", name: "UntagResource" }, UntagResourceRequest, UntagResourceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateLibraryItemInput = Schema.Struct({instanceId: Header("instance-id"), libraryItemId: Schema.String, status: Schema.optional(Schema.String), categories: Schema.optional(CategoryIdList)})
const UpdateLibraryItemMetadataInput = Schema.Struct({instanceId: Header("instance-id"), libraryItemId: Schema.String, isVerified: Schema.optional(Schema.Boolean)})
export const UpdateLibraryItemMetadata = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.updateItemMetadata", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "UpdateLibraryItemMetadata" }, UpdateLibraryItemMetadataInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateQAppInput = Schema.Struct({instanceId: Header("instance-id"), appId: Schema.String, title: Schema.optional(Schema.String), description: Schema.optional(Schema.String), appDefinition: Schema.optional(AppDefinitionInput)})
const UpdateQAppSessionInput = Schema.Struct({instanceId: Header("instance-id"), sessionId: Schema.String, values: Schema.optional(CardValueList)})
const BatchCreateCategoryInputCategory = Schema.Struct({id: Schema.optional(Schema.String), title: Schema.String, color: Schema.optional(Schema.String)})
const BatchCreateCategoryInputCategoryList = Schema.Array(BatchCreateCategoryInputCategory)
const CategoryInput = Schema.Struct({id: Schema.String, title: Schema.String, color: Schema.optional(Schema.String)})
const CategoryListInput = Schema.Array(CategoryInput)
const TagMap = Schema.Record({key: Schema.String, value: Schema.String})
const AppRequiredCapabilities = Schema.Array(Schema.String)
const CategoriesList = Schema.Array(Category)
const Tags = Schema.Record({key: Schema.String, value: Schema.String})
const PermissionInput = Schema.Struct({action: Schema.String, principal: Schema.String})
const PermissionsInputList = Schema.Array(PermissionInput)
const SessionSharingConfiguration = Schema.Struct({enabled: Schema.Boolean, acceptResponses: Schema.optional(Schema.Boolean), revealCards: Schema.optional(Schema.Boolean)})
const AccessDeniedException = Schema.Struct({message: Schema.String})
export const AssociateLibraryItemReview = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.associateItemRating", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "AssociateLibraryItemReview" }, AssociateLibraryItemReviewInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const InternalServerException = Schema.Struct({message: Schema.String, retryAfterSeconds: Schema.optional(Header("Retry-After", Schema.Number))})
export const AssociateQAppWithUser = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.install", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "AssociateQAppWithUser" }, AssociateQAppWithUserInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const BatchCreateCategoryInput = Schema.Struct({instanceId: Header("instance-id"), categories: BatchCreateCategoryInputCategoryList})
export const BatchCreateCategory = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.createCategories", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "BatchCreateCategory" }, BatchCreateCategoryInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ConflictException = Schema.Struct({message: Schema.String, resourceId: Schema.String, resourceType: Schema.String})
export const BatchDeleteCategory = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.deleteCategories", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "BatchDeleteCategory" }, BatchDeleteCategoryInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const BatchUpdateCategoryInput = Schema.Struct({instanceId: Header("instance-id"), categories: CategoryListInput})
export const BatchUpdateCategory = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.updateCategories", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "BatchUpdateCategory" }, BatchUpdateCategoryInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const CreateLibraryItemOutput = Schema.Struct({libraryItemId: Schema.String, status: Schema.String, createdAt: Schema.Date, createdBy: Schema.String, updatedAt: Schema.optional(Schema.Date), updatedBy: Schema.optional(Schema.String), ratingCount: Schema.Number, isVerified: Schema.optional(Schema.Boolean)})
export const CreateLibraryItem = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.createItem", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "CreateLibraryItem" }, CreateLibraryItemInput, CreateLibraryItemOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ResourceNotFoundException = Schema.Struct({message: Schema.String, resourceId: Schema.String, resourceType: Schema.String})
export const DeleteLibraryItem = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.deleteItem", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "DeleteLibraryItem" }, DeleteLibraryItemInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ThrottlingException = Schema.Struct({message: Schema.String, serviceCode: Schema.String, quotaCode: Schema.String, retryAfterSeconds: Schema.optional(Header("Retry-After", Schema.Number))})
export const DeleteQApp = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.delete", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "DeleteQApp" }, DeleteQAppInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ServiceQuotaExceededException = Schema.Struct({message: Schema.String, resourceId: Schema.String, resourceType: Schema.String, serviceCode: Schema.String, quotaCode: Schema.String})
export const DisassociateLibraryItemReview = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.disassociateItemRating", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "DisassociateLibraryItemReview" }, DisassociateLibraryItemReviewInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UnauthorizedException = Schema.Struct({message: Schema.String})
export const DisassociateQAppFromUser = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.uninstall", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "DisassociateQAppFromUser" }, DisassociateQAppFromUserInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ExportQAppSessionDataOutput = Schema.Struct({csvFileLink: Schema.String, expiresAt: Schema.Date, sessionArn: Schema.String})
export const ExportQAppSessionData = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/runtime.exportQAppSessionData", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "ExportQAppSessionData" }, ExportQAppSessionDataInput, ExportQAppSessionDataOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetQAppSessionMetadataOutput = Schema.Struct({sessionId: Schema.String, sessionArn: Schema.String, sessionName: Schema.optional(Schema.String), sharingConfiguration: SessionSharingConfiguration, sessionOwner: Schema.optional(Schema.Boolean)})
export const GetQAppSessionMetadata = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/runtime.getQAppSessionMetadata", method: "GET", sdkId: "QApps", sigV4ServiceName: "qapps", name: "GetQAppSessionMetadata" }, GetQAppSessionMetadataInput, GetQAppSessionMetadataOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ImportDocumentOutput = Schema.Struct({fileId: Schema.optional(Schema.String)})
const ListCategoriesOutput = Schema.Struct({categories: Schema.optional(CategoriesList)})
export const ListCategories = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.listCategories", method: "GET", sdkId: "QApps", sigV4ServiceName: "qapps", name: "ListCategories" }, ListCategoriesInput, ListCategoriesOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListTagsForResourceResponse = Schema.Struct({tags: Schema.optional(Tags)})
export const ListTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceARN}", method: "GET", sdkId: "QApps", sigV4ServiceName: "qapps", name: "ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ValidationException = Schema.Struct({message: Schema.String})
export const StopQAppSession = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/runtime.deleteMiniAppRun", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "StopQAppSession" }, StopQAppSessionInput, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const TagResourceRequest = Schema.Struct({resourceARN: Schema.String, tags: Tags})
const TagResourceResponse = Schema.Struct({})
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceARN}", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "TagResource" }, TagResourceRequest, TagResourceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateLibraryItemOutput = Schema.Struct({libraryItemId: Schema.String, appId: Schema.String, appVersion: Schema.Number, categories: CategoryList, status: Schema.String, createdAt: Schema.Date, createdBy: Schema.String, updatedAt: Schema.optional(Schema.Date), updatedBy: Schema.optional(Schema.String), ratingCount: Schema.Number, isRatedByUser: Schema.optional(Schema.Boolean), userCount: Schema.optional(Schema.Number), isVerified: Schema.optional(Schema.Boolean)})
export const UpdateLibraryItem = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.updateItem", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "UpdateLibraryItem" }, UpdateLibraryItemInput, UpdateLibraryItemOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateQAppOutput = Schema.Struct({appId: Schema.String, appArn: Schema.String, title: Schema.String, description: Schema.optional(Schema.String), initialPrompt: Schema.optional(Schema.String), appVersion: Schema.Number, status: Schema.String, createdAt: Schema.Date, createdBy: Schema.String, updatedAt: Schema.Date, updatedBy: Schema.String, requiredCapabilities: Schema.optional(AppRequiredCapabilities)})
export const UpdateQApp = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.update", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "UpdateQApp" }, UpdateQAppInput, UpdateQAppOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ContentTooLargeException", ContentTooLargeException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateQAppPermissionsInput = Schema.Struct({instanceId: Header("instance-id"), appId: Schema.String, grantPermissions: Schema.optional(PermissionsInputList), revokePermissions: Schema.optional(PermissionsInputList)})
const UpdateQAppSessionOutput = Schema.Struct({sessionId: Schema.String, sessionArn: Schema.String})
export const UpdateQAppSession = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/runtime.updateQAppSession", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "UpdateQAppSession" }, UpdateQAppSessionInput, UpdateQAppSessionOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateQAppSessionMetadataInput = Schema.Struct({instanceId: Header("instance-id"), sessionId: Schema.String, sessionName: Schema.optional(Schema.String), sharingConfiguration: SessionSharingConfiguration})
const ConversationMessage = Schema.Struct({body: Schema.String, type: Schema.String})
const MessageList = Schema.Array(ConversationMessage)
const SubmissionMutation = Schema.Struct({submissionId: Schema.String, mutationType: Schema.String})
const PresignedUrlFields = Schema.Record({key: Schema.String, value: Schema.String})
const Category = Schema.Struct({id: Schema.String, title: Schema.String, color: Schema.optional(Schema.String), appCount: Schema.optional(Schema.Number)})
const CategoryList = Schema.Array(Category)
const LibraryItemMember = Schema.Struct({libraryItemId: Schema.String, appId: Schema.String, appVersion: Schema.Number, categories: CategoryList, status: Schema.String, createdAt: Schema.Date, createdBy: Schema.String, updatedAt: Schema.optional(Schema.Date), updatedBy: Schema.optional(Schema.String), ratingCount: Schema.Number, isRatedByUser: Schema.optional(Schema.Boolean), userCount: Schema.optional(Schema.Number), isVerified: Schema.optional(Schema.Boolean)})
const LibraryItemList = Schema.Array(LibraryItemMember)
const UserAppItem = Schema.Struct({appId: Schema.String, appArn: Schema.String, title: Schema.String, description: Schema.optional(Schema.String), createdAt: Schema.Date, canEdit: Schema.optional(Schema.Boolean), status: Schema.optional(Schema.String), isVerified: Schema.optional(Schema.Boolean)})
const UserAppsList = Schema.Array(UserAppItem)
const PredictQAppInputOptions = Schema.Union(MessageList, Schema.String)
const CardValue = Schema.Struct({cardId: Schema.String, value: Schema.String, submissionMutation: Schema.optional(SubmissionMutation)})
const CardValueList = Schema.Array(CardValue)
const TextInputCardInput = Schema.Struct({title: Schema.String, id: Schema.String, type: Schema.String, placeholder: Schema.optional(Schema.String), defaultValue: Schema.optional(Schema.String)})
const QPluginCardInput = Schema.Struct({title: Schema.String, id: Schema.String, type: Schema.String, prompt: Schema.String, pluginId: Schema.String, actionIdentifier: Schema.optional(Schema.String)})
const FileUploadCardInput = Schema.Struct({title: Schema.String, id: Schema.String, type: Schema.String, filename: Schema.optional(Schema.String), fileId: Schema.optional(Schema.String), allowOverride: Schema.optional(Schema.Boolean)})
const CreatePresignedUrlOutput = Schema.Struct({fileId: Schema.String, presignedUrl: Schema.String, presignedUrlFields: PresignedUrlFields, presignedUrlExpiration: Schema.Date})
export const CreatePresignedUrl = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.createPresignedUrl", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "CreatePresignedUrl" }, CreatePresignedUrlInput, CreatePresignedUrlOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const AttributeFilters = Schema.Array(AttributeFilter)
const GetLibraryItemOutput = Schema.Struct({libraryItemId: Schema.String, appId: Schema.String, appVersion: Schema.Number, categories: CategoryList, status: Schema.String, createdAt: Schema.Date, createdBy: Schema.String, updatedAt: Schema.optional(Schema.Date), updatedBy: Schema.optional(Schema.String), ratingCount: Schema.Number, isRatedByUser: Schema.optional(Schema.Boolean), userCount: Schema.optional(Schema.Number), isVerified: Schema.optional(Schema.Boolean)})
export const GetLibraryItem = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.getItem", method: "GET", sdkId: "QApps", sigV4ServiceName: "qapps", name: "GetLibraryItem" }, GetLibraryItemInput, GetLibraryItemOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ContentTooLargeException = Schema.Struct({message: Schema.String, resourceId: Schema.String, resourceType: Schema.String})
export const ImportDocument = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.importDocument", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "ImportDocument" }, ImportDocumentInput, ImportDocumentOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ContentTooLargeException", ContentTooLargeException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListLibraryItemsOutput = Schema.Struct({libraryItems: Schema.optional(LibraryItemList), nextToken: Schema.optional(Schema.String)})
export const ListLibraryItems = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/catalog.list", method: "GET", sdkId: "QApps", sigV4ServiceName: "qapps", name: "ListLibraryItems" }, ListLibraryItemsInput, ListLibraryItemsOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListQAppsOutput = Schema.Struct({apps: UserAppsList, nextToken: Schema.optional(Schema.String)})
export const ListQApps = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.list", method: "GET", sdkId: "QApps", sigV4ServiceName: "qapps", name: "ListQApps" }, ListQAppsInput, ListQAppsOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const PredictQAppInput = Schema.Struct({instanceId: Header("instance-id"), options: Schema.optional(PredictQAppInputOptions)})
const StartQAppSessionInput = Schema.Struct({instanceId: Header("instance-id"), appId: Schema.String, appVersion: Schema.Number, initialValues: Schema.optional(CardValueList), sessionId: Schema.optional(Schema.String), tags: Schema.optional(TagMap)})
const UpdateQAppPermissionsOutput = Schema.Struct({resourceArn: Schema.optional(Schema.String), appId: Schema.optional(Schema.String), permissions: Schema.optional(PermissionsOutputList)})
export const UpdateQAppPermissions = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.updateQAppPermissions", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "UpdateQAppPermissions" }, UpdateQAppPermissionsInput, UpdateQAppPermissionsOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateQAppSessionMetadataOutput = Schema.Struct({sessionId: Schema.String, sessionArn: Schema.String, sessionName: Schema.optional(Schema.String), sharingConfiguration: SessionSharingConfiguration})
export const UpdateQAppSessionMetadata = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/runtime.updateQAppSessionMetadata", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "UpdateQAppSessionMetadata" }, UpdateQAppSessionMetadataInput, UpdateQAppSessionMetadataOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const PrincipalOutput = Schema.Struct({userId: Schema.optional(Schema.String), userType: Schema.optional(Schema.String), email: Schema.optional(Schema.String)})
const User = Schema.Struct({userId: Schema.optional(Schema.String)})
const FormInputCardMetadata = Schema.Struct({schema: Schema.JsonValue})
const DependencyList = Schema.Array(Schema.String)
const MemoryReferenceList = Schema.Array(Schema.String)
const PermissionOutput = Schema.Struct({action: Schema.String, principal: PrincipalOutput})
const PermissionsOutputList = Schema.Array(PermissionOutput)
const QAppSessionData = Schema.Struct({cardId: Schema.String, value: Schema.optional(Schema.JsonValue), user: User, submissionId: Schema.optional(Schema.String), timestamp: Schema.optional(Schema.Date)})
const QAppSessionDataList = Schema.Array(QAppSessionData)
const FormInputCardInput = Schema.Struct({title: Schema.String, id: Schema.String, type: Schema.String, metadata: FormInputCardMetadata, computeMode: Schema.optional(Schema.String)})
const TextInputCard = Schema.Struct({id: Schema.String, title: Schema.String, dependencies: DependencyList, type: Schema.String, placeholder: Schema.optional(Schema.String), defaultValue: Schema.optional(Schema.String)})
const QQueryCard = Schema.Struct({id: Schema.String, title: Schema.String, dependencies: DependencyList, type: Schema.String, prompt: Schema.String, outputSource: Schema.String, attributeFilter: Schema.optional(AttributeFilter), memoryReferences: Schema.optional(MemoryReferenceList)})
const QPluginCard = Schema.Struct({id: Schema.String, title: Schema.String, dependencies: DependencyList, type: Schema.String, prompt: Schema.String, pluginType: Schema.String, pluginId: Schema.String, actionIdentifier: Schema.optional(Schema.String)})
const FileUploadCard = Schema.Struct({id: Schema.String, title: Schema.String, dependencies: DependencyList, type: Schema.String, filename: Schema.optional(Schema.String), fileId: Schema.optional(Schema.String), allowOverride: Schema.optional(Schema.Boolean)})
const FormInputCard = Schema.Struct({id: Schema.String, title: Schema.String, dependencies: DependencyList, type: Schema.String, metadata: FormInputCardMetadata, computeMode: Schema.optional(Schema.String)})
const Submission = Schema.Struct({value: Schema.optional(Schema.JsonValue), submissionId: Schema.optional(Schema.String), timestamp: Schema.optional(Schema.Date)})
const SubmissionList = Schema.Array(Submission)
const DescribeQAppPermissionsOutput = Schema.Struct({resourceArn: Schema.optional(Schema.String), appId: Schema.optional(Schema.String), permissions: Schema.optional(PermissionsOutputList)})
export const DescribeQAppPermissions = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.describeQAppPermissions", method: "GET", sdkId: "QApps", sigV4ServiceName: "qapps", name: "DescribeQAppPermissions" }, DescribeQAppPermissionsInput, DescribeQAppPermissionsOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListQAppSessionDataOutput = Schema.Struct({sessionId: Schema.String, sessionArn: Schema.String, sessionData: Schema.optional(QAppSessionDataList), nextToken: Schema.optional(Schema.String)})
export const ListQAppSessionData = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/runtime.listQAppSessionData", method: "GET", sdkId: "QApps", sigV4ServiceName: "qapps", name: "ListQAppSessionData" }, ListQAppSessionDataInput, ListQAppSessionDataOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const StartQAppSessionOutput = Schema.Struct({sessionId: Schema.String, sessionArn: Schema.String})
export const StartQAppSession = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/runtime.startQAppSession", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "StartQAppSession" }, StartQAppSessionInput, StartQAppSessionOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DocumentAttributeStringListValue = Schema.Array(Schema.String)
const Card = Schema.Union(TextInputCard, QQueryCard, QPluginCard, FileUploadCard, FormInputCard)
const CardModelList = Schema.Array(Card)
const CardStatus = Schema.Struct({currentState: Schema.String, currentValue: Schema.String, submissions: Schema.optional(SubmissionList)})
const DocumentAttributeValue = Schema.Union(Schema.String, DocumentAttributeStringListValue, Schema.Number, Schema.Date)
const AppDefinition = Schema.Struct({appDefinitionVersion: Schema.String, cards: CardModelList, canEdit: Schema.optional(Schema.Boolean)})
const CardStatusMap = Schema.Record({key: Schema.String, value: CardStatus})
const PredictAppDefinition = Schema.Struct({title: Schema.String, description: Schema.optional(Schema.String), appDefinition: AppDefinitionInput})
const DocumentAttribute = Schema.Struct({name: Schema.String, value: DocumentAttributeValue})
const GetQAppOutput = Schema.Struct({appId: Schema.String, appArn: Schema.String, title: Schema.String, description: Schema.optional(Schema.String), initialPrompt: Schema.optional(Schema.String), appVersion: Schema.Number, status: Schema.String, createdAt: Schema.Date, createdBy: Schema.String, updatedAt: Schema.Date, updatedBy: Schema.String, requiredCapabilities: Schema.optional(AppRequiredCapabilities), appDefinition: AppDefinition})
export const GetQApp = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.get", method: "GET", sdkId: "QApps", sigV4ServiceName: "qapps", name: "GetQApp" }, GetQAppInput, GetQAppOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetQAppSessionOutput = Schema.Struct({sessionId: Schema.String, sessionArn: Schema.String, sessionName: Schema.optional(Schema.String), appVersion: Schema.optional(Schema.Number), latestPublishedAppVersion: Schema.optional(Schema.Number), status: Schema.String, cardStatus: CardStatusMap, userIsHost: Schema.optional(Schema.Boolean)})
export const GetQAppSession = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/runtime.getQAppSession", method: "GET", sdkId: "QApps", sigV4ServiceName: "qapps", name: "GetQAppSession" }, GetQAppSessionInput, GetQAppSessionOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const PredictQAppOutput = Schema.Struct({app: PredictAppDefinition, problemStatement: Schema.String})
export const PredictQApp = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.predictQApp", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "PredictQApp" }, PredictQAppInput, PredictQAppOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const AttributeFilter = Schema.Struct({andAllFilters: Schema.optional(AttributeFilters), orAllFilters: Schema.optional(AttributeFilters), notFilter: Schema.optional(AttributeFilter), equalsTo: Schema.optional(DocumentAttribute), containsAll: Schema.optional(DocumentAttribute), containsAny: Schema.optional(DocumentAttribute), greaterThan: Schema.optional(DocumentAttribute), greaterThanOrEquals: Schema.optional(DocumentAttribute), lessThan: Schema.optional(DocumentAttribute), lessThanOrEquals: Schema.optional(DocumentAttribute)})
const QQueryCardInput = Schema.Struct({title: Schema.String, id: Schema.String, type: Schema.String, prompt: Schema.String, outputSource: Schema.optional(Schema.String), attributeFilter: Schema.optional(AttributeFilter)})
const CardInput = Schema.Union(TextInputCardInput, QQueryCardInput, QPluginCardInput, FileUploadCardInput, FormInputCardInput)
const CardList = Schema.Array(CardInput)
const AppDefinitionInput = Schema.Struct({cards: CardList, initialPrompt: Schema.optional(Schema.String)})
const CreateQAppInput = Schema.Struct({instanceId: Header("instance-id"), title: Schema.String, description: Schema.optional(Schema.String), appDefinition: AppDefinitionInput, tags: Schema.optional(TagMap)})
const CreateQAppOutput = Schema.Struct({appId: Schema.String, appArn: Schema.String, title: Schema.String, description: Schema.optional(Schema.String), initialPrompt: Schema.optional(Schema.String), appVersion: Schema.Number, status: Schema.String, createdAt: Schema.Date, createdBy: Schema.String, updatedAt: Schema.Date, updatedBy: Schema.String, requiredCapabilities: Schema.optional(AppRequiredCapabilities)})
export const CreateQApp = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/apps.create", method: "POST", sdkId: "QApps", sigV4ServiceName: "qapps", name: "CreateQApp" }, CreateQAppInput, CreateQAppOutput, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("ContentTooLargeException", ContentTooLargeException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("UnauthorizedException", UnauthorizedException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
