import * as S from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const WorkgroupNameList = S.Array(S.String);
export const TagKeyList = S.Array(S.String);
export class CreateCustomDomainAssociationRequest extends S.Class<CreateCustomDomainAssociationRequest>("CreateCustomDomainAssociationRequest")({workgroupName: S.String, customDomainName: S.String, customDomainCertificateArn: S.String}) {}
export class DeleteCustomDomainAssociationRequest extends S.Class<DeleteCustomDomainAssociationRequest>("DeleteCustomDomainAssociationRequest")({workgroupName: S.String, customDomainName: S.String}) {}
export class DeleteCustomDomainAssociationResponse extends S.Class<DeleteCustomDomainAssociationResponse>("DeleteCustomDomainAssociationResponse")({}) {}
export class DeleteResourcePolicyRequest extends S.Class<DeleteResourcePolicyRequest>("DeleteResourcePolicyRequest")({resourceArn: S.String}) {}
export class DeleteResourcePolicyResponse extends S.Class<DeleteResourcePolicyResponse>("DeleteResourcePolicyResponse")({}) {}
export class GetCredentialsRequest extends S.Class<GetCredentialsRequest>("GetCredentialsRequest")({dbName: S.optional(S.String), durationSeconds: S.optional(S.Number), workgroupName: S.optional(S.String), customDomainName: S.optional(S.String)}) {}
export class GetCustomDomainAssociationRequest extends S.Class<GetCustomDomainAssociationRequest>("GetCustomDomainAssociationRequest")({customDomainName: S.String, workgroupName: S.String}) {}
export class GetIdentityCenterAuthTokenRequest extends S.Class<GetIdentityCenterAuthTokenRequest>("GetIdentityCenterAuthTokenRequest")({workgroupNames: WorkgroupNameList}) {}
export class GetResourcePolicyRequest extends S.Class<GetResourcePolicyRequest>("GetResourcePolicyRequest")({resourceArn: S.String}) {}
export class GetTrackRequest extends S.Class<GetTrackRequest>("GetTrackRequest")({trackName: S.String}) {}
export class ListCustomDomainAssociationsRequest extends S.Class<ListCustomDomainAssociationsRequest>("ListCustomDomainAssociationsRequest")({nextToken: S.optional(S.String), maxResults: S.optional(S.Number), customDomainName: S.optional(S.String), customDomainCertificateArn: S.optional(S.String)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({resourceArn: S.String}) {}
export class ListTracksRequest extends S.Class<ListTracksRequest>("ListTracksRequest")({nextToken: S.optional(S.String), maxResults: S.optional(S.Number)}) {}
export class PutResourcePolicyRequest extends S.Class<PutResourcePolicyRequest>("PutResourcePolicyRequest")({resourceArn: S.String, policy: S.String}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({resourceArn: S.String, tagKeys: TagKeyList}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class UpdateCustomDomainAssociationRequest extends S.Class<UpdateCustomDomainAssociationRequest>("UpdateCustomDomainAssociationRequest")({workgroupName: S.String, customDomainName: S.String, customDomainCertificateArn: S.String}) {}
export class UpdateTarget extends S.Class<UpdateTarget>("UpdateTarget")({trackName: S.optional(S.String), workgroupVersion: S.optional(S.String)}) {}
export const UpdateTargetsList = S.Array(UpdateTarget);
export class ServerlessTrack extends S.Class<ServerlessTrack>("ServerlessTrack")({trackName: S.optional(S.String), workgroupVersion: S.optional(S.String), updateTargets: S.optional(UpdateTargetsList)}) {}
export const TrackList = S.Array(ServerlessTrack);
export class Tag extends S.Class<Tag>("Tag")({key: S.String, value: S.String}) {}
export const TagList = S.Array(Tag);
export class CreateCustomDomainAssociationResponse extends S.Class<CreateCustomDomainAssociationResponse>("CreateCustomDomainAssociationResponse")({customDomainName: S.optional(S.String), workgroupName: S.optional(S.String), customDomainCertificateArn: S.optional(S.String), customDomainCertificateExpiryTime: S.optional(S.Date)}) {}
export class AccessDeniedException extends S.Class<AccessDeniedException>("AccessDeniedException")({code: S.optional(S.String), message: S.optional(S.String)}) {}
export class InternalServerException extends S.Class<InternalServerException>("InternalServerException")({message: S.String}) {}
export class GetCredentialsResponse extends S.Class<GetCredentialsResponse>("GetCredentialsResponse")({dbUser: S.optional(S.String), dbPassword: S.optional(S.String), expiration: S.optional(S.Date), nextRefreshTime: S.optional(S.Date)}) {}
export class GetCustomDomainAssociationResponse extends S.Class<GetCustomDomainAssociationResponse>("GetCustomDomainAssociationResponse")({customDomainName: S.optional(S.String), workgroupName: S.optional(S.String), customDomainCertificateArn: S.optional(S.String), customDomainCertificateExpiryTime: S.optional(S.Date)}) {}
export class GetIdentityCenterAuthTokenResponse extends S.Class<GetIdentityCenterAuthTokenResponse>("GetIdentityCenterAuthTokenResponse")({token: S.optional(S.String), expirationTime: S.optional(S.Date)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({tags: S.optional(TagList)}) {}
export class ListTracksResponse extends S.Class<ListTracksResponse>("ListTracksResponse")({tracks: S.optional(TrackList), nextToken: S.optional(S.String)}) {}
export class ResourcePolicy extends S.Class<ResourcePolicy>("ResourcePolicy")({resourceArn: S.optional(S.String), policy: S.optional(S.String)}) {}
export class PutResourcePolicyResponse extends S.Class<PutResourcePolicyResponse>("PutResourcePolicyResponse")({resourcePolicy: S.optional(ResourcePolicy)}) {}
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({resourceArn: S.String, tags: TagList}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class ResourceNotFoundException extends S.Class<ResourceNotFoundException>("ResourceNotFoundException")({message: S.String, resourceName: S.optional(S.String)}) {}
export class UpdateCustomDomainAssociationResponse extends S.Class<UpdateCustomDomainAssociationResponse>("UpdateCustomDomainAssociationResponse")({customDomainName: S.optional(S.String), workgroupName: S.optional(S.String), customDomainCertificateArn: S.optional(S.String), customDomainCertificateExpiryTime: S.optional(S.Date)}) {}
export class Association extends S.Class<Association>("Association")({customDomainCertificateArn: S.optional(S.String), customDomainCertificateExpiryTime: S.optional(S.Date), customDomainName: S.optional(S.String), workgroupName: S.optional(S.String)}) {}
export const AssociationList = S.Array(Association);
export class ConflictException extends S.Class<ConflictException>("ConflictException")({message: S.String}) {}
export class ThrottlingException extends S.Class<ThrottlingException>("ThrottlingException")({code: S.optional(S.String), message: S.optional(S.String)}) {}
export class ValidationException extends S.Class<ValidationException>("ValidationException")({message: S.String}) {}
export class DryRunException extends S.Class<DryRunException>("DryRunException")({message: S.String}) {}
export class GetResourcePolicyResponse extends S.Class<GetResourcePolicyResponse>("GetResourcePolicyResponse")({resourcePolicy: S.optional(ResourcePolicy)}) {}
export class ListCustomDomainAssociationsResponse extends S.Class<ListCustomDomainAssociationsResponse>("ListCustomDomainAssociationsResponse")({nextToken: S.optional(S.String), associations: S.optional(AssociationList)}) {}
export class InvalidPaginationException extends S.Class<InvalidPaginationException>("InvalidPaginationException")({message: S.String}) {}
export class ServiceQuotaExceededException extends S.Class<ServiceQuotaExceededException>("ServiceQuotaExceededException")({message: S.String}) {}
export class TooManyTagsException extends S.Class<TooManyTagsException>("TooManyTagsException")({message: S.optional(S.String), resourceName: S.optional(S.String)}) {}
export class GetTrackResponse extends S.Class<GetTrackResponse>("GetTrackResponse")({track: S.optional(ServerlessTrack)}) {}

//# Errors
export class InternalServerExceptionError extends S.TaggedError<InternalServerExceptionError>()("InternalServerException", InternalServerException.fields) {};
export class AccessDeniedExceptionError extends S.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class ConflictExceptionError extends S.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class ResourceNotFoundExceptionError extends S.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ValidationExceptionError extends S.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};
export class ThrottlingExceptionError extends S.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class DryRunExceptionError extends S.TaggedError<DryRunExceptionError>()("DryRunException", DryRunException.fields) {};
export class InvalidPaginationExceptionError extends S.TaggedError<InvalidPaginationExceptionError>()("InvalidPaginationException", InvalidPaginationException.fields) {};
export class ServiceQuotaExceededExceptionError extends S.TaggedError<ServiceQuotaExceededExceptionError>()("ServiceQuotaExceededException", ServiceQuotaExceededException.fields) {};
export class TooManyTagsExceptionError extends S.TaggedError<TooManyTagsExceptionError>()("TooManyTagsException", TooManyTagsException.fields) {};

//# Operations
export const getCredentials = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.GetCredentials" }, GetCredentialsRequest, GetCredentialsResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getCustomDomainAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.GetCustomDomainAssociation" }, GetCustomDomainAssociationRequest, GetCustomDomainAssociationResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateCustomDomainAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.UpdateCustomDomainAssociation" }, UpdateCustomDomainAssociationRequest, UpdateCustomDomainAssociationResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createCustomDomainAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.CreateCustomDomainAssociation" }, CreateCustomDomainAssociationRequest, CreateCustomDomainAssociationResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteCustomDomainAssociation = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.DeleteCustomDomainAssociation" }, DeleteCustomDomainAssociationRequest, DeleteCustomDomainAssociationResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteResourcePolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.DeleteResourcePolicy" }, DeleteResourcePolicyRequest, DeleteResourcePolicyResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getIdentityCenterAuthToken = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.GetIdentityCenterAuthToken" }, GetIdentityCenterAuthTokenRequest, GetIdentityCenterAuthTokenResponse, [AccessDeniedExceptionError, ConflictExceptionError, DryRunExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getResourcePolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.GetResourcePolicy" }, GetResourcePolicyRequest, GetResourcePolicyResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listCustomDomainAssociations = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.ListCustomDomainAssociations" }, ListCustomDomainAssociationsRequest, ListCustomDomainAssociationsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, InvalidPaginationExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTracks = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.ListTracks" }, ListTracksRequest, ListTracksResponse, [AccessDeniedExceptionError, InternalServerExceptionError, InvalidPaginationExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const putResourcePolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.PutResourcePolicy" }, PutResourcePolicyRequest, PutResourcePolicyResponse, [ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.TagResource" }, TagResourceRequest, TagResourceResponse, [InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, TooManyTagsExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getTrack = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2021-04-21", uri: "/", method: "POST", sdkId: "Redshift Serverless", sigV4ServiceName: "redshift-serverless", name: "RedshiftServerless.GetTrack" }, GetTrackRequest, GetTrackResponse, [AccessDeniedExceptionError, ConflictExceptionError, DryRunExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
