import { Schema} from "effect"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import { Operation, Path, Header, StreamBody, Body } from "../schema-helpers.ts";

//# Schemas
export const AppComponentNameList = Schema.Array(Schema.String);
export const RecommendationIdList = Schema.Array(Schema.String);
export const RenderRecommendationTypeList = Schema.Array(Schema.String);
export const ArnList = Schema.Array(Schema.String);
export class TerraformSource extends Schema.Class<TerraformSource>("TerraformSource")({s3StateFileUrl: Schema.String}) {}
export const TerraformSourceList = Schema.Array(TerraformSource);
export const AssessmentStatusList = Schema.Array(Schema.String);
export const RecommendationTemplateStatusList = Schema.Array(Schema.String);
export const EntityNameList = Schema.Array(Schema.String);
export const String255List = Schema.Array(Schema.String);
export const TagKeyList = Schema.Array(Schema.String);
export const TagMap = Schema.Record({key: Schema.String, value: Schema.String});
export class CreateRecommendationTemplateRequest extends Schema.Class<CreateRecommendationTemplateRequest>("CreateRecommendationTemplateRequest")({recommendationIds: Schema.optional(RecommendationIdList), format: Schema.optional(Schema.String), recommendationTypes: Schema.optional(RenderRecommendationTypeList), assessmentArn: Schema.String, name: Schema.String, clientToken: Schema.optional(Schema.String), tags: Schema.optional(TagMap), bucketName: Schema.optional(Schema.String)}) {}
export class DeleteAppRequest extends Schema.Class<DeleteAppRequest>("DeleteAppRequest")({appArn: Schema.String, forceDelete: Schema.optional(Schema.Boolean), clientToken: Schema.optional(Schema.String)}) {}
export class DeleteAppAssessmentRequest extends Schema.Class<DeleteAppAssessmentRequest>("DeleteAppAssessmentRequest")({assessmentArn: Schema.String, clientToken: Schema.optional(Schema.String)}) {}
export class DeleteAppVersionAppComponentRequest extends Schema.Class<DeleteAppVersionAppComponentRequest>("DeleteAppVersionAppComponentRequest")({appArn: Schema.String, id: Schema.String, clientToken: Schema.optional(Schema.String)}) {}
export class LogicalResourceId extends Schema.Class<LogicalResourceId>("LogicalResourceId")({identifier: Schema.String, logicalStackName: Schema.optional(Schema.String), resourceGroupName: Schema.optional(Schema.String), terraformSourceName: Schema.optional(Schema.String), eksSourceName: Schema.optional(Schema.String)}) {}
export class DeleteAppVersionResourceRequest extends Schema.Class<DeleteAppVersionResourceRequest>("DeleteAppVersionResourceRequest")({appArn: Schema.String, resourceName: Schema.optional(Schema.String), logicalResourceId: Schema.optional(LogicalResourceId), physicalResourceId: Schema.optional(Schema.String), awsRegion: Schema.optional(Schema.String), awsAccountId: Schema.optional(Schema.String), clientToken: Schema.optional(Schema.String)}) {}
export class DeleteRecommendationTemplateRequest extends Schema.Class<DeleteRecommendationTemplateRequest>("DeleteRecommendationTemplateRequest")({recommendationTemplateArn: Schema.String, clientToken: Schema.optional(Schema.String)}) {}
export class DeleteResiliencyPolicyRequest extends Schema.Class<DeleteResiliencyPolicyRequest>("DeleteResiliencyPolicyRequest")({policyArn: Schema.String, clientToken: Schema.optional(Schema.String)}) {}
export class DescribeAppRequest extends Schema.Class<DescribeAppRequest>("DescribeAppRequest")({appArn: Schema.String}) {}
export class DescribeAppAssessmentRequest extends Schema.Class<DescribeAppAssessmentRequest>("DescribeAppAssessmentRequest")({assessmentArn: Schema.String}) {}
export class DescribeAppVersionRequest extends Schema.Class<DescribeAppVersionRequest>("DescribeAppVersionRequest")({appArn: Schema.String, appVersion: Schema.String}) {}
export class DescribeAppVersionAppComponentRequest extends Schema.Class<DescribeAppVersionAppComponentRequest>("DescribeAppVersionAppComponentRequest")({appArn: Schema.String, appVersion: Schema.String, id: Schema.String}) {}
export class DescribeAppVersionResourceRequest extends Schema.Class<DescribeAppVersionResourceRequest>("DescribeAppVersionResourceRequest")({appArn: Schema.String, appVersion: Schema.String, resourceName: Schema.optional(Schema.String), logicalResourceId: Schema.optional(LogicalResourceId), physicalResourceId: Schema.optional(Schema.String), awsRegion: Schema.optional(Schema.String), awsAccountId: Schema.optional(Schema.String)}) {}
export class DescribeAppVersionResourcesResolutionStatusRequest extends Schema.Class<DescribeAppVersionResourcesResolutionStatusRequest>("DescribeAppVersionResourcesResolutionStatusRequest")({appArn: Schema.String, appVersion: Schema.String, resolutionId: Schema.optional(Schema.String)}) {}
export class DescribeAppVersionTemplateRequest extends Schema.Class<DescribeAppVersionTemplateRequest>("DescribeAppVersionTemplateRequest")({appArn: Schema.String, appVersion: Schema.String}) {}
export class DescribeDraftAppVersionResourcesImportStatusRequest extends Schema.Class<DescribeDraftAppVersionResourcesImportStatusRequest>("DescribeDraftAppVersionResourcesImportStatusRequest")({appArn: Schema.String}) {}
export class DescribeMetricsExportRequest extends Schema.Class<DescribeMetricsExportRequest>("DescribeMetricsExportRequest")({metricsExportId: Schema.String}) {}
export class DescribeResiliencyPolicyRequest extends Schema.Class<DescribeResiliencyPolicyRequest>("DescribeResiliencyPolicyRequest")({policyArn: Schema.String}) {}
export class DescribeResourceGroupingRecommendationTaskRequest extends Schema.Class<DescribeResourceGroupingRecommendationTaskRequest>("DescribeResourceGroupingRecommendationTaskRequest")({appArn: Schema.String, groupingId: Schema.optional(Schema.String)}) {}
export class ListAlarmRecommendationsRequest extends Schema.Class<ListAlarmRecommendationsRequest>("ListAlarmRecommendationsRequest")({assessmentArn: Schema.String, nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListAppAssessmentComplianceDriftsRequest extends Schema.Class<ListAppAssessmentComplianceDriftsRequest>("ListAppAssessmentComplianceDriftsRequest")({assessmentArn: Schema.String, nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListAppAssessmentResourceDriftsRequest extends Schema.Class<ListAppAssessmentResourceDriftsRequest>("ListAppAssessmentResourceDriftsRequest")({assessmentArn: Schema.String, nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListAppAssessmentsRequest extends Schema.Class<ListAppAssessmentsRequest>("ListAppAssessmentsRequest")({appArn: Schema.optional(Schema.String), assessmentName: Schema.optional(Schema.String), assessmentStatus: Schema.optional(AssessmentStatusList), complianceStatus: Schema.optional(Schema.String), invoker: Schema.optional(Schema.String), reverseOrder: Schema.optional(Schema.Boolean), nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListAppComponentCompliancesRequest extends Schema.Class<ListAppComponentCompliancesRequest>("ListAppComponentCompliancesRequest")({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), assessmentArn: Schema.String}) {}
export class ListAppComponentRecommendationsRequest extends Schema.Class<ListAppComponentRecommendationsRequest>("ListAppComponentRecommendationsRequest")({assessmentArn: Schema.String, nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListAppInputSourcesRequest extends Schema.Class<ListAppInputSourcesRequest>("ListAppInputSourcesRequest")({appArn: Schema.String, appVersion: Schema.String, nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListAppsRequest extends Schema.Class<ListAppsRequest>("ListAppsRequest")({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), name: Schema.optional(Schema.String), appArn: Schema.optional(Schema.String), fromLastAssessmentTime: Schema.optional(Schema.Date), toLastAssessmentTime: Schema.optional(Schema.Date), reverseOrder: Schema.optional(Schema.Boolean), awsApplicationArn: Schema.optional(Schema.String)}) {}
export class ListAppVersionAppComponentsRequest extends Schema.Class<ListAppVersionAppComponentsRequest>("ListAppVersionAppComponentsRequest")({appArn: Schema.String, appVersion: Schema.String, nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListAppVersionResourceMappingsRequest extends Schema.Class<ListAppVersionResourceMappingsRequest>("ListAppVersionResourceMappingsRequest")({appArn: Schema.String, appVersion: Schema.String, nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListAppVersionResourcesRequest extends Schema.Class<ListAppVersionResourcesRequest>("ListAppVersionResourcesRequest")({appArn: Schema.String, appVersion: Schema.String, resolutionId: Schema.optional(Schema.String), nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListAppVersionsRequest extends Schema.Class<ListAppVersionsRequest>("ListAppVersionsRequest")({appArn: Schema.String, nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), startTime: Schema.optional(Schema.Date), endTime: Schema.optional(Schema.Date)}) {}
export class ListRecommendationTemplatesRequest extends Schema.Class<ListRecommendationTemplatesRequest>("ListRecommendationTemplatesRequest")({assessmentArn: Schema.optional(Schema.String), reverseOrder: Schema.optional(Schema.Boolean), status: Schema.optional(RecommendationTemplateStatusList), recommendationTemplateArn: Schema.optional(Schema.String), name: Schema.optional(Schema.String), nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListResiliencyPoliciesRequest extends Schema.Class<ListResiliencyPoliciesRequest>("ListResiliencyPoliciesRequest")({policyName: Schema.optional(Schema.String), nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListResourceGroupingRecommendationsRequest extends Schema.Class<ListResourceGroupingRecommendationsRequest>("ListResourceGroupingRecommendationsRequest")({appArn: Schema.optional(Schema.String), nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListSopRecommendationsRequest extends Schema.Class<ListSopRecommendationsRequest>("ListSopRecommendationsRequest")({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), assessmentArn: Schema.String}) {}
export class ListSuggestedResiliencyPoliciesRequest extends Schema.Class<ListSuggestedResiliencyPoliciesRequest>("ListSuggestedResiliencyPoliciesRequest")({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class ListTagsForResourceRequest extends Schema.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({resourceArn: Schema.String}) {}
export class ListTestRecommendationsRequest extends Schema.Class<ListTestRecommendationsRequest>("ListTestRecommendationsRequest")({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), assessmentArn: Schema.String}) {}
export class ListUnsupportedAppVersionResourcesRequest extends Schema.Class<ListUnsupportedAppVersionResourcesRequest>("ListUnsupportedAppVersionResourcesRequest")({appArn: Schema.String, appVersion: Schema.String, resolutionId: Schema.optional(Schema.String), nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)}) {}
export class PublishAppVersionRequest extends Schema.Class<PublishAppVersionRequest>("PublishAppVersionRequest")({appArn: Schema.String, versionName: Schema.optional(Schema.String)}) {}
export class PutDraftAppVersionTemplateRequest extends Schema.Class<PutDraftAppVersionTemplateRequest>("PutDraftAppVersionTemplateRequest")({appArn: Schema.String, appTemplateBody: Schema.String}) {}
export class RemoveDraftAppVersionResourceMappingsRequest extends Schema.Class<RemoveDraftAppVersionResourceMappingsRequest>("RemoveDraftAppVersionResourceMappingsRequest")({appArn: Schema.String, resourceNames: Schema.optional(EntityNameList), logicalStackNames: Schema.optional(String255List), appRegistryAppNames: Schema.optional(EntityNameList), resourceGroupNames: Schema.optional(EntityNameList), terraformSourceNames: Schema.optional(String255List), eksSourceNames: Schema.optional(String255List)}) {}
export class ResolveAppVersionResourcesRequest extends Schema.Class<ResolveAppVersionResourcesRequest>("ResolveAppVersionResourcesRequest")({appArn: Schema.String, appVersion: Schema.String}) {}
export class StartAppAssessmentRequest extends Schema.Class<StartAppAssessmentRequest>("StartAppAssessmentRequest")({appArn: Schema.String, appVersion: Schema.String, assessmentName: Schema.String, clientToken: Schema.optional(Schema.String), tags: Schema.optional(TagMap)}) {}
export class StartMetricsExportRequest extends Schema.Class<StartMetricsExportRequest>("StartMetricsExportRequest")({bucketName: Schema.optional(Schema.String), clientToken: Schema.optional(Schema.String)}) {}
export class StartResourceGroupingRecommendationTaskRequest extends Schema.Class<StartResourceGroupingRecommendationTaskRequest>("StartResourceGroupingRecommendationTaskRequest")({appArn: Schema.String}) {}
export class TagResourceRequest extends Schema.Class<TagResourceRequest>("TagResourceRequest")({resourceArn: Schema.String, tags: TagMap}) {}
export class TagResourceResponse extends Schema.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends Schema.Class<UntagResourceRequest>("UntagResourceRequest")({resourceArn: Schema.String, tagKeys: TagKeyList}) {}
export class UntagResourceResponse extends Schema.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export const IamRoleArnList = Schema.Array(Schema.String);
export class PermissionModel extends Schema.Class<PermissionModel>("PermissionModel")({type: Schema.String, invokerRoleName: Schema.optional(Schema.String), crossAccountRoleArns: Schema.optional(IamRoleArnList)}) {}
export class EventSubscription extends Schema.Class<EventSubscription>("EventSubscription")({name: Schema.String, eventType: Schema.String, snsTopicArn: Schema.optional(Schema.String)}) {}
export const EventSubscriptionList = Schema.Array(EventSubscription);
export class UpdateAppRequest extends Schema.Class<UpdateAppRequest>("UpdateAppRequest")({appArn: Schema.String, description: Schema.optional(Schema.String), policyArn: Schema.optional(Schema.String), clearResiliencyPolicyArn: Schema.optional(Schema.Boolean), assessmentSchedule: Schema.optional(Schema.String), permissionModel: Schema.optional(PermissionModel), eventSubscriptions: Schema.optional(EventSubscriptionList)}) {}
export const AdditionalInfoValueList = Schema.Array(Schema.String);
export const AdditionalInfoMap = Schema.Record({key: Schema.String, value: AdditionalInfoValueList});
export class UpdateAppVersionRequest extends Schema.Class<UpdateAppVersionRequest>("UpdateAppVersionRequest")({appArn: Schema.String, additionalInfo: Schema.optional(AdditionalInfoMap)}) {}
export class UpdateAppVersionAppComponentRequest extends Schema.Class<UpdateAppVersionAppComponentRequest>("UpdateAppVersionAppComponentRequest")({appArn: Schema.String, id: Schema.String, name: Schema.optional(Schema.String), type: Schema.optional(Schema.String), additionalInfo: Schema.optional(AdditionalInfoMap)}) {}
export class UpdateAppVersionResourceRequest extends Schema.Class<UpdateAppVersionResourceRequest>("UpdateAppVersionResourceRequest")({appArn: Schema.String, resourceName: Schema.optional(Schema.String), logicalResourceId: Schema.optional(LogicalResourceId), physicalResourceId: Schema.optional(Schema.String), awsRegion: Schema.optional(Schema.String), awsAccountId: Schema.optional(Schema.String), resourceType: Schema.optional(Schema.String), appComponents: Schema.optional(AppComponentNameList), additionalInfo: Schema.optional(AdditionalInfoMap), excluded: Schema.optional(Schema.Boolean)}) {}
export class FailurePolicy extends Schema.Class<FailurePolicy>("FailurePolicy")({rtoInSecs: Schema.Number, rpoInSecs: Schema.Number}) {}
export const DisruptionPolicy = Schema.Record({key: Schema.String, value: FailurePolicy});
export class UpdateResiliencyPolicyRequest extends Schema.Class<UpdateResiliencyPolicyRequest>("UpdateResiliencyPolicyRequest")({policyArn: Schema.String, policyName: Schema.optional(Schema.String), policyDescription: Schema.optional(Schema.String), dataLocationConstraint: Schema.optional(Schema.String), tier: Schema.optional(Schema.String), policy: Schema.optional(DisruptionPolicy)}) {}
export const EksNamespaceList = Schema.Array(Schema.String);
export class AcceptGroupingRecommendationEntry extends Schema.Class<AcceptGroupingRecommendationEntry>("AcceptGroupingRecommendationEntry")({groupingRecommendationId: Schema.String}) {}
export const AcceptGroupingRecommendationEntries = Schema.Array(AcceptGroupingRecommendationEntry);
export class EksSourceClusterNamespace extends Schema.Class<EksSourceClusterNamespace>("EksSourceClusterNamespace")({eksClusterArn: Schema.String, namespace: Schema.String}) {}
export class EksSource extends Schema.Class<EksSource>("EksSource")({eksClusterArn: Schema.String, namespaces: EksNamespaceList}) {}
export const EksSourceList = Schema.Array(EksSource);
export class AppComponent extends Schema.Class<AppComponent>("AppComponent")({name: Schema.String, type: Schema.String, id: Schema.optional(Schema.String), additionalInfo: Schema.optional(AdditionalInfoMap)}) {}
export const AppComponentList = Schema.Array(AppComponent);
export class PhysicalResourceId extends Schema.Class<PhysicalResourceId>("PhysicalResourceId")({identifier: Schema.String, type: Schema.String, awsRegion: Schema.optional(Schema.String), awsAccountId: Schema.optional(Schema.String)}) {}
export class PhysicalResource extends Schema.Class<PhysicalResource>("PhysicalResource")({resourceName: Schema.optional(Schema.String), logicalResourceId: LogicalResourceId, physicalResourceId: PhysicalResourceId, resourceType: Schema.String, appComponents: Schema.optional(AppComponentList), additionalInfo: Schema.optional(AdditionalInfoMap), excluded: Schema.optional(Schema.Boolean), sourceType: Schema.optional(Schema.String), parentResourceName: Schema.optional(Schema.String)}) {}
export const PhysicalResourceList = Schema.Array(PhysicalResource);
export class Field extends Schema.Class<Field>("Field")({name: Schema.String, aggregation: Schema.optional(Schema.String)}) {}
export const FieldList = Schema.Array(Field);
export class Condition extends Schema.Class<Condition>("Condition")({field: Schema.String, operator: Schema.String, value: Schema.optional(Schema.String)}) {}
export const ConditionList = Schema.Array(Condition);
export class Sort extends Schema.Class<Sort>("Sort")({field: Schema.String, ascending: Schema.optional(Schema.Boolean)}) {}
export const SortList = Schema.Array(Sort);
export class S3Location extends Schema.Class<S3Location>("S3Location")({bucket: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)}) {}
export class RecommendationTemplate extends Schema.Class<RecommendationTemplate>("RecommendationTemplate")({templatesLocation: Schema.optional(S3Location), assessmentArn: Schema.String, appArn: Schema.optional(Schema.String), recommendationIds: Schema.optional(RecommendationIdList), recommendationTypes: RenderRecommendationTypeList, format: Schema.String, recommendationTemplateArn: Schema.String, message: Schema.optional(Schema.String), status: Schema.String, name: Schema.String, startTime: Schema.optional(Schema.Date), endTime: Schema.optional(Schema.Date), tags: Schema.optional(TagMap), needsReplacements: Schema.optional(Schema.Boolean)}) {}
export const RecommendationTemplateList = Schema.Array(RecommendationTemplate);
export class ResiliencyPolicy extends Schema.Class<ResiliencyPolicy>("ResiliencyPolicy")({policyArn: Schema.optional(Schema.String), policyName: Schema.optional(Schema.String), policyDescription: Schema.optional(Schema.String), dataLocationConstraint: Schema.optional(Schema.String), tier: Schema.optional(Schema.String), estimatedCostTier: Schema.optional(Schema.String), policy: Schema.optional(DisruptionPolicy), creationTime: Schema.optional(Schema.Date), tags: Schema.optional(TagMap)}) {}
export const ResiliencyPolicies = Schema.Array(ResiliencyPolicy);
export class RejectGroupingRecommendationEntry extends Schema.Class<RejectGroupingRecommendationEntry>("RejectGroupingRecommendationEntry")({groupingRecommendationId: Schema.String, rejectionReason: Schema.optional(Schema.String)}) {}
export const RejectGroupingRecommendationEntries = Schema.Array(RejectGroupingRecommendationEntry);
export class AcceptResourceGroupingRecommendationsRequest extends Schema.Class<AcceptResourceGroupingRecommendationsRequest>("AcceptResourceGroupingRecommendationsRequest")({appArn: Schema.String, entries: AcceptGroupingRecommendationEntries}) {}
export class CreateAppRequest extends Schema.Class<CreateAppRequest>("CreateAppRequest")({name: Schema.String, description: Schema.optional(Schema.String), policyArn: Schema.optional(Schema.String), tags: Schema.optional(TagMap), clientToken: Schema.optional(Schema.String), assessmentSchedule: Schema.optional(Schema.String), permissionModel: Schema.optional(PermissionModel), eventSubscriptions: Schema.optional(EventSubscriptionList), awsApplicationArn: Schema.optional(Schema.String)}) {}
export class CreateAppVersionAppComponentRequest extends Schema.Class<CreateAppVersionAppComponentRequest>("CreateAppVersionAppComponentRequest")({appArn: Schema.String, id: Schema.optional(Schema.String), name: Schema.String, type: Schema.String, additionalInfo: Schema.optional(AdditionalInfoMap), clientToken: Schema.optional(Schema.String)}) {}
export class CreateAppVersionResourceRequest extends Schema.Class<CreateAppVersionResourceRequest>("CreateAppVersionResourceRequest")({appArn: Schema.String, resourceName: Schema.optional(Schema.String), logicalResourceId: LogicalResourceId, physicalResourceId: Schema.String, awsRegion: Schema.optional(Schema.String), awsAccountId: Schema.optional(Schema.String), resourceType: Schema.String, appComponents: AppComponentNameList, additionalInfo: Schema.optional(AdditionalInfoMap), clientToken: Schema.optional(Schema.String)}) {}
export class DeleteAppResponse extends Schema.Class<DeleteAppResponse>("DeleteAppResponse")({appArn: Schema.String}) {}
export class DeleteAppAssessmentResponse extends Schema.Class<DeleteAppAssessmentResponse>("DeleteAppAssessmentResponse")({assessmentArn: Schema.String, assessmentStatus: Schema.String}) {}
export class DeleteAppInputSourceRequest extends Schema.Class<DeleteAppInputSourceRequest>("DeleteAppInputSourceRequest")({appArn: Schema.String, sourceArn: Schema.optional(Schema.String), terraformSource: Schema.optional(TerraformSource), clientToken: Schema.optional(Schema.String), eksSourceClusterNamespace: Schema.optional(EksSourceClusterNamespace)}) {}
export class DeleteRecommendationTemplateResponse extends Schema.Class<DeleteRecommendationTemplateResponse>("DeleteRecommendationTemplateResponse")({recommendationTemplateArn: Schema.String, status: Schema.String}) {}
export class DeleteResiliencyPolicyResponse extends Schema.Class<DeleteResiliencyPolicyResponse>("DeleteResiliencyPolicyResponse")({policyArn: Schema.String}) {}
export class DescribeAppVersionResponse extends Schema.Class<DescribeAppVersionResponse>("DescribeAppVersionResponse")({appArn: Schema.String, appVersion: Schema.String, additionalInfo: Schema.optional(AdditionalInfoMap)}) {}
export class DescribeAppVersionAppComponentResponse extends Schema.Class<DescribeAppVersionAppComponentResponse>("DescribeAppVersionAppComponentResponse")({appArn: Schema.String, appVersion: Schema.String, appComponent: Schema.optional(AppComponent)}) {}
export class DescribeAppVersionResourceResponse extends Schema.Class<DescribeAppVersionResourceResponse>("DescribeAppVersionResourceResponse")({appArn: Schema.String, appVersion: Schema.String, physicalResource: Schema.optional(PhysicalResource)}) {}
export class DescribeAppVersionResourcesResolutionStatusResponse extends Schema.Class<DescribeAppVersionResourcesResolutionStatusResponse>("DescribeAppVersionResourcesResolutionStatusResponse")({appArn: Schema.String, appVersion: Schema.String, resolutionId: Schema.String, status: Schema.String, errorMessage: Schema.optional(Schema.String)}) {}
export class DescribeAppVersionTemplateResponse extends Schema.Class<DescribeAppVersionTemplateResponse>("DescribeAppVersionTemplateResponse")({appArn: Schema.String, appVersion: Schema.String, appTemplateBody: Schema.String}) {}
export class DescribeResourceGroupingRecommendationTaskResponse extends Schema.Class<DescribeResourceGroupingRecommendationTaskResponse>("DescribeResourceGroupingRecommendationTaskResponse")({groupingId: Schema.String, status: Schema.String, errorMessage: Schema.optional(Schema.String)}) {}
export class ImportResourcesToDraftAppVersionRequest extends Schema.Class<ImportResourcesToDraftAppVersionRequest>("ImportResourcesToDraftAppVersionRequest")({appArn: Schema.String, sourceArns: Schema.optional(ArnList), terraformSources: Schema.optional(TerraformSourceList), importStrategy: Schema.optional(Schema.String), eksSources: Schema.optional(EksSourceList)}) {}
export class ListAppVersionAppComponentsResponse extends Schema.Class<ListAppVersionAppComponentsResponse>("ListAppVersionAppComponentsResponse")({appArn: Schema.String, appVersion: Schema.String, appComponents: Schema.optional(AppComponentList), nextToken: Schema.optional(Schema.String)}) {}
export class ResourceMapping extends Schema.Class<ResourceMapping>("ResourceMapping")({resourceName: Schema.optional(Schema.String), logicalStackName: Schema.optional(Schema.String), appRegistryAppName: Schema.optional(Schema.String), resourceGroupName: Schema.optional(Schema.String), mappingType: Schema.String, physicalResourceId: PhysicalResourceId, terraformSourceName: Schema.optional(Schema.String), eksSourceName: Schema.optional(Schema.String)}) {}
export const ResourceMappingList = Schema.Array(ResourceMapping);
export class ListAppVersionResourceMappingsResponse extends Schema.Class<ListAppVersionResourceMappingsResponse>("ListAppVersionResourceMappingsResponse")({resourceMappings: ResourceMappingList, nextToken: Schema.optional(Schema.String)}) {}
export class ListAppVersionResourcesResponse extends Schema.Class<ListAppVersionResourcesResponse>("ListAppVersionResourcesResponse")({physicalResources: PhysicalResourceList, resolutionId: Schema.String, nextToken: Schema.optional(Schema.String)}) {}
export class ListMetricsRequest extends Schema.Class<ListMetricsRequest>("ListMetricsRequest")({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), fields: Schema.optional(FieldList), dataSource: Schema.optional(Schema.String), conditions: Schema.optional(ConditionList), sorts: Schema.optional(SortList)}) {}
export class ListRecommendationTemplatesResponse extends Schema.Class<ListRecommendationTemplatesResponse>("ListRecommendationTemplatesResponse")({nextToken: Schema.optional(Schema.String), recommendationTemplates: Schema.optional(RecommendationTemplateList)}) {}
export class ListResiliencyPoliciesResponse extends Schema.Class<ListResiliencyPoliciesResponse>("ListResiliencyPoliciesResponse")({resiliencyPolicies: ResiliencyPolicies, nextToken: Schema.optional(Schema.String)}) {}
export class ListSuggestedResiliencyPoliciesResponse extends Schema.Class<ListSuggestedResiliencyPoliciesResponse>("ListSuggestedResiliencyPoliciesResponse")({resiliencyPolicies: ResiliencyPolicies, nextToken: Schema.optional(Schema.String)}) {}
export class ListTagsForResourceResponse extends Schema.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({tags: Schema.optional(TagMap)}) {}
export class PublishAppVersionResponse extends Schema.Class<PublishAppVersionResponse>("PublishAppVersionResponse")({appArn: Schema.String, appVersion: Schema.optional(Schema.String), identifier: Schema.optional(Schema.Number), versionName: Schema.optional(Schema.String)}) {}
export class PutDraftAppVersionTemplateResponse extends Schema.Class<PutDraftAppVersionTemplateResponse>("PutDraftAppVersionTemplateResponse")({appArn: Schema.optional(Schema.String), appVersion: Schema.optional(Schema.String)}) {}
export class RejectResourceGroupingRecommendationsRequest extends Schema.Class<RejectResourceGroupingRecommendationsRequest>("RejectResourceGroupingRecommendationsRequest")({appArn: Schema.String, entries: RejectGroupingRecommendationEntries}) {}
export class RemoveDraftAppVersionResourceMappingsResponse extends Schema.Class<RemoveDraftAppVersionResourceMappingsResponse>("RemoveDraftAppVersionResourceMappingsResponse")({appArn: Schema.optional(Schema.String), appVersion: Schema.optional(Schema.String)}) {}
export class ResolveAppVersionResourcesResponse extends Schema.Class<ResolveAppVersionResourcesResponse>("ResolveAppVersionResourcesResponse")({appArn: Schema.String, appVersion: Schema.String, resolutionId: Schema.String, status: Schema.String}) {}
export class Cost extends Schema.Class<Cost>("Cost")({amount: Schema.Number, currency: Schema.String, frequency: Schema.String}) {}
export const DisruptionResiliencyScore = Schema.Record({key: Schema.String, value: Schema.Number});
export class ScoringComponentResiliencyScore extends Schema.Class<ScoringComponentResiliencyScore>("ScoringComponentResiliencyScore")({score: Schema.optional(Schema.Number), possibleScore: Schema.optional(Schema.Number), outstandingCount: Schema.optional(Schema.Number), excludedCount: Schema.optional(Schema.Number)}) {}
export const ScoringComponentResiliencyScores = Schema.Record({key: Schema.String, value: ScoringComponentResiliencyScore});
export class ResiliencyScore extends Schema.Class<ResiliencyScore>("ResiliencyScore")({score: Schema.Number, disruptionScore: DisruptionResiliencyScore, componentScore: Schema.optional(ScoringComponentResiliencyScores)}) {}
export class DisruptionCompliance extends Schema.Class<DisruptionCompliance>("DisruptionCompliance")({achievableRtoInSecs: Schema.optional(Schema.Number), currentRtoInSecs: Schema.optional(Schema.Number), rtoReferenceId: Schema.optional(Schema.String), rtoDescription: Schema.optional(Schema.String), currentRpoInSecs: Schema.optional(Schema.Number), rpoReferenceId: Schema.optional(Schema.String), rpoDescription: Schema.optional(Schema.String), complianceStatus: Schema.String, achievableRpoInSecs: Schema.optional(Schema.Number), message: Schema.optional(Schema.String)}) {}
export const AssessmentCompliance = Schema.Record({key: Schema.String, value: DisruptionCompliance});
export class ResourceError extends Schema.Class<ResourceError>("ResourceError")({logicalResourceId: Schema.optional(Schema.String), physicalResourceId: Schema.optional(Schema.String), reason: Schema.optional(Schema.String)}) {}
export const ResourceErrorList = Schema.Array(ResourceError);
export class ResourceErrorsDetails extends Schema.Class<ResourceErrorsDetails>("ResourceErrorsDetails")({resourceErrors: Schema.optional(ResourceErrorList), hasMoreErrors: Schema.optional(Schema.Boolean)}) {}
export class AssessmentRiskRecommendation extends Schema.Class<AssessmentRiskRecommendation>("AssessmentRiskRecommendation")({risk: Schema.optional(Schema.String), recommendation: Schema.optional(Schema.String), appComponents: Schema.optional(AppComponentNameList)}) {}
export const AssessmentRiskRecommendationList = Schema.Array(AssessmentRiskRecommendation);
export class AssessmentSummary extends Schema.Class<AssessmentSummary>("AssessmentSummary")({summary: Schema.optional(Schema.String), riskRecommendations: Schema.optional(AssessmentRiskRecommendationList)}) {}
export class AppAssessment extends Schema.Class<AppAssessment>("AppAssessment")({appArn: Schema.optional(Schema.String), appVersion: Schema.optional(Schema.String), invoker: Schema.String, cost: Schema.optional(Cost), resiliencyScore: Schema.optional(ResiliencyScore), compliance: Schema.optional(AssessmentCompliance), complianceStatus: Schema.optional(Schema.String), assessmentStatus: Schema.String, startTime: Schema.optional(Schema.Date), endTime: Schema.optional(Schema.Date), message: Schema.optional(Schema.String), assessmentName: Schema.optional(Schema.String), assessmentArn: Schema.String, policy: Schema.optional(ResiliencyPolicy), tags: Schema.optional(TagMap), resourceErrorsDetails: Schema.optional(ResourceErrorsDetails), versionName: Schema.optional(Schema.String), driftStatus: Schema.optional(Schema.String), summary: Schema.optional(AssessmentSummary)}) {}
export class StartAppAssessmentResponse extends Schema.Class<StartAppAssessmentResponse>("StartAppAssessmentResponse")({assessment: AppAssessment}) {}
export class StartMetricsExportResponse extends Schema.Class<StartMetricsExportResponse>("StartMetricsExportResponse")({metricsExportId: Schema.String, status: Schema.String}) {}
export class StartResourceGroupingRecommendationTaskResponse extends Schema.Class<StartResourceGroupingRecommendationTaskResponse>("StartResourceGroupingRecommendationTaskResponse")({appArn: Schema.String, groupingId: Schema.String, status: Schema.String, errorMessage: Schema.optional(Schema.String)}) {}
export class AccessDeniedException extends Schema.Class<AccessDeniedException>("AccessDeniedException")({message: Schema.optional(Schema.String)}) {}
export class InternalServerException extends Schema.Class<InternalServerException>("InternalServerException")({message: Schema.optional(Schema.String)}) {}
export class App extends Schema.Class<App>("App")({appArn: Schema.String, name: Schema.String, description: Schema.optional(Schema.String), policyArn: Schema.optional(Schema.String), creationTime: Schema.Date, status: Schema.optional(Schema.String), complianceStatus: Schema.optional(Schema.String), lastAppComplianceEvaluationTime: Schema.optional(Schema.Date), resiliencyScore: Schema.optional(Schema.Number), lastResiliencyScoreEvaluationTime: Schema.optional(Schema.Date), tags: Schema.optional(TagMap), assessmentSchedule: Schema.optional(Schema.String), permissionModel: Schema.optional(PermissionModel), eventSubscriptions: Schema.optional(EventSubscriptionList), driftStatus: Schema.optional(Schema.String), lastDriftEvaluationTime: Schema.optional(Schema.Date), rtoInSecs: Schema.optional(Schema.Number), rpoInSecs: Schema.optional(Schema.Number), awsApplicationArn: Schema.optional(Schema.String)}) {}
export class UpdateAppResponse extends Schema.Class<UpdateAppResponse>("UpdateAppResponse")({app: App}) {}
export class UpdateAppVersionResponse extends Schema.Class<UpdateAppVersionResponse>("UpdateAppVersionResponse")({appArn: Schema.String, appVersion: Schema.String, additionalInfo: Schema.optional(AdditionalInfoMap)}) {}
export class UpdateAppVersionAppComponentResponse extends Schema.Class<UpdateAppVersionAppComponentResponse>("UpdateAppVersionAppComponentResponse")({appArn: Schema.String, appVersion: Schema.String, appComponent: Schema.optional(AppComponent)}) {}
export class UpdateAppVersionResourceResponse extends Schema.Class<UpdateAppVersionResourceResponse>("UpdateAppVersionResourceResponse")({appArn: Schema.String, appVersion: Schema.String, physicalResource: Schema.optional(PhysicalResource)}) {}
export class UpdateResiliencyPolicyResponse extends Schema.Class<UpdateResiliencyPolicyResponse>("UpdateResiliencyPolicyResponse")({policy: ResiliencyPolicy}) {}
export class UpdateRecommendationStatusItem extends Schema.Class<UpdateRecommendationStatusItem>("UpdateRecommendationStatusItem")({resourceId: Schema.optional(Schema.String), targetAccountId: Schema.optional(Schema.String), targetRegion: Schema.optional(Schema.String)}) {}
export const AlarmReferenceIdList = Schema.Array(Schema.String);
export class UpdateRecommendationStatusRequestEntry extends Schema.Class<UpdateRecommendationStatusRequestEntry>("UpdateRecommendationStatusRequestEntry")({entryId: Schema.String, referenceId: Schema.String, item: Schema.optional(UpdateRecommendationStatusItem), excluded: Schema.Boolean, appComponentId: Schema.optional(Schema.String), excludeReason: Schema.optional(Schema.String)}) {}
export const UpdateRecommendationStatusRequestEntries = Schema.Array(UpdateRecommendationStatusRequestEntry);
export class ErrorDetail extends Schema.Class<ErrorDetail>("ErrorDetail")({errorMessage: Schema.optional(Schema.String)}) {}
export const ErrorDetailList = Schema.Array(ErrorDetail);
export class ComplianceDrift extends Schema.Class<ComplianceDrift>("ComplianceDrift")({entityId: Schema.optional(Schema.String), entityType: Schema.optional(Schema.String), driftType: Schema.optional(Schema.String), appId: Schema.optional(Schema.String), appVersion: Schema.optional(Schema.String), expectedReferenceId: Schema.optional(Schema.String), expectedValue: Schema.optional(AssessmentCompliance), actualReferenceId: Schema.optional(Schema.String), actualValue: Schema.optional(AssessmentCompliance), diffType: Schema.optional(Schema.String)}) {}
export const ComplianceDriftList = Schema.Array(ComplianceDrift);
export class AppAssessmentSummary extends Schema.Class<AppAssessmentSummary>("AppAssessmentSummary")({appArn: Schema.optional(Schema.String), appVersion: Schema.optional(Schema.String), assessmentStatus: Schema.String, invoker: Schema.optional(Schema.String), startTime: Schema.optional(Schema.Date), endTime: Schema.optional(Schema.Date), message: Schema.optional(Schema.String), assessmentName: Schema.optional(Schema.String), assessmentArn: Schema.String, complianceStatus: Schema.optional(Schema.String), cost: Schema.optional(Cost), resiliencyScore: Schema.optional(Schema.Number), versionName: Schema.optional(Schema.String), driftStatus: Schema.optional(Schema.String)}) {}
export const AppAssessmentSummaryList = Schema.Array(AppAssessmentSummary);
export class AppComponentCompliance extends Schema.Class<AppComponentCompliance>("AppComponentCompliance")({cost: Schema.optional(Cost), appComponentName: Schema.optional(Schema.String), compliance: Schema.optional(AssessmentCompliance), message: Schema.optional(Schema.String), status: Schema.optional(Schema.String), resiliencyScore: Schema.optional(ResiliencyScore)}) {}
export const ComponentCompliancesList = Schema.Array(AppComponentCompliance);
export class AppInputSource extends Schema.Class<AppInputSource>("AppInputSource")({sourceName: Schema.optional(Schema.String), importType: Schema.String, sourceArn: Schema.optional(Schema.String), terraformSource: Schema.optional(TerraformSource), resourceCount: Schema.optional(Schema.Number), eksSourceClusterNamespace: Schema.optional(EksSourceClusterNamespace)}) {}
export const AppInputSourceList = Schema.Array(AppInputSource);
export class AppSummary extends Schema.Class<AppSummary>("AppSummary")({appArn: Schema.String, name: Schema.String, description: Schema.optional(Schema.String), creationTime: Schema.Date, complianceStatus: Schema.optional(Schema.String), resiliencyScore: Schema.optional(Schema.Number), assessmentSchedule: Schema.optional(Schema.String), status: Schema.optional(Schema.String), driftStatus: Schema.optional(Schema.String), lastAppComplianceEvaluationTime: Schema.optional(Schema.Date), rtoInSecs: Schema.optional(Schema.Number), rpoInSecs: Schema.optional(Schema.Number), awsApplicationArn: Schema.optional(Schema.String)}) {}
export const AppSummaryList = Schema.Array(AppSummary);
export class AppVersionSummary extends Schema.Class<AppVersionSummary>("AppVersionSummary")({appVersion: Schema.String, identifier: Schema.optional(Schema.Number), creationTime: Schema.optional(Schema.Date), versionName: Schema.optional(Schema.String)}) {}
export const AppVersionList = Schema.Array(AppVersionSummary);
export const Row = Schema.Array(Schema.String);
export const RowList = Schema.Array(Row);
export class Experiment extends Schema.Class<Experiment>("Experiment")({experimentArn: Schema.optional(Schema.String), experimentTemplateId: Schema.optional(Schema.String)}) {}
export class Alarm extends Schema.Class<Alarm>("Alarm")({alarmArn: Schema.optional(Schema.String), source: Schema.optional(Schema.String)}) {}
export class RecommendationItem extends Schema.Class<RecommendationItem>("RecommendationItem")({resourceId: Schema.optional(Schema.String), targetAccountId: Schema.optional(Schema.String), targetRegion: Schema.optional(Schema.String), alreadyImplemented: Schema.optional(Schema.Boolean), excluded: Schema.optional(Schema.Boolean), excludeReason: Schema.optional(Schema.String), latestDiscoveredExperiment: Schema.optional(Experiment), discoveredAlarm: Schema.optional(Alarm)}) {}
export const RecommendationItemList = Schema.Array(RecommendationItem);
export class SopRecommendation extends Schema.Class<SopRecommendation>("SopRecommendation")({serviceType: Schema.String, appComponentName: Schema.optional(Schema.String), description: Schema.optional(Schema.String), recommendationId: Schema.String, name: Schema.optional(Schema.String), items: Schema.optional(RecommendationItemList), referenceId: Schema.String, prerequisite: Schema.optional(Schema.String), recommendationStatus: Schema.optional(Schema.String)}) {}
export const SopRecommendationList = Schema.Array(SopRecommendation);
export class TestRecommendation extends Schema.Class<TestRecommendation>("TestRecommendation")({recommendationId: Schema.optional(Schema.String), referenceId: Schema.String, appComponentId: Schema.optional(Schema.String), appComponentName: Schema.optional(Schema.String), name: Schema.optional(Schema.String), intent: Schema.optional(Schema.String), risk: Schema.optional(Schema.String), type: Schema.optional(Schema.String), description: Schema.optional(Schema.String), items: Schema.optional(RecommendationItemList), prerequisite: Schema.optional(Schema.String), dependsOnAlarms: Schema.optional(AlarmReferenceIdList), recommendationStatus: Schema.optional(Schema.String)}) {}
export const TestRecommendationList = Schema.Array(TestRecommendation);
export class UnsupportedResource extends Schema.Class<UnsupportedResource>("UnsupportedResource")({logicalResourceId: LogicalResourceId, physicalResourceId: PhysicalResourceId, resourceType: Schema.String, unsupportedResourceStatus: Schema.optional(Schema.String)}) {}
export const UnsupportedResourceList = Schema.Array(UnsupportedResource);
export const SuggestedChangesList = Schema.Array(Schema.String);
export class AddDraftAppVersionResourceMappingsRequest extends Schema.Class<AddDraftAppVersionResourceMappingsRequest>("AddDraftAppVersionResourceMappingsRequest")({appArn: Schema.String, resourceMappings: ResourceMappingList}) {}
export class BatchUpdateRecommendationStatusRequest extends Schema.Class<BatchUpdateRecommendationStatusRequest>("BatchUpdateRecommendationStatusRequest")({appArn: Schema.String, requestEntries: UpdateRecommendationStatusRequestEntries}) {}
export class CreateAppResponse extends Schema.Class<CreateAppResponse>("CreateAppResponse")({app: App}) {}
export class CreateAppVersionAppComponentResponse extends Schema.Class<CreateAppVersionAppComponentResponse>("CreateAppVersionAppComponentResponse")({appArn: Schema.String, appVersion: Schema.String, appComponent: Schema.optional(AppComponent)}) {}
export class CreateAppVersionResourceResponse extends Schema.Class<CreateAppVersionResourceResponse>("CreateAppVersionResourceResponse")({appArn: Schema.String, appVersion: Schema.String, physicalResource: Schema.optional(PhysicalResource)}) {}
export class CreateRecommendationTemplateResponse extends Schema.Class<CreateRecommendationTemplateResponse>("CreateRecommendationTemplateResponse")({recommendationTemplate: Schema.optional(RecommendationTemplate)}) {}
export class CreateResiliencyPolicyRequest extends Schema.Class<CreateResiliencyPolicyRequest>("CreateResiliencyPolicyRequest")({policyName: Schema.String, policyDescription: Schema.optional(Schema.String), dataLocationConstraint: Schema.optional(Schema.String), tier: Schema.String, policy: DisruptionPolicy, clientToken: Schema.optional(Schema.String), tags: Schema.optional(TagMap)}) {}
export class ConflictException extends Schema.Class<ConflictException>("ConflictException")({message: Schema.optional(Schema.String), resourceId: Schema.optional(Schema.String), resourceType: Schema.optional(Schema.String)}) {}
export class ResourceNotFoundException extends Schema.Class<ResourceNotFoundException>("ResourceNotFoundException")({message: Schema.optional(Schema.String), resourceId: Schema.optional(Schema.String), resourceType: Schema.optional(Schema.String)}) {}
export class DeleteAppInputSourceResponse extends Schema.Class<DeleteAppInputSourceResponse>("DeleteAppInputSourceResponse")({appArn: Schema.optional(Schema.String), appInputSource: Schema.optional(AppInputSource)}) {}
export class DeleteAppVersionAppComponentResponse extends Schema.Class<DeleteAppVersionAppComponentResponse>("DeleteAppVersionAppComponentResponse")({appArn: Schema.String, appVersion: Schema.String, appComponent: Schema.optional(AppComponent)}) {}
export class DeleteAppVersionResourceResponse extends Schema.Class<DeleteAppVersionResourceResponse>("DeleteAppVersionResourceResponse")({appArn: Schema.String, appVersion: Schema.String, physicalResource: Schema.optional(PhysicalResource)}) {}
export class ThrottlingException extends Schema.Class<ThrottlingException>("ThrottlingException")({message: Schema.optional(Schema.String), retryAfterSeconds: Schema.optional(Schema.Number)}) {}
export class ValidationException extends Schema.Class<ValidationException>("ValidationException")({message: Schema.optional(Schema.String)}) {}
export class DescribeAppResponse extends Schema.Class<DescribeAppResponse>("DescribeAppResponse")({app: App}) {}
export class DescribeDraftAppVersionResourcesImportStatusResponse extends Schema.Class<DescribeDraftAppVersionResourcesImportStatusResponse>("DescribeDraftAppVersionResourcesImportStatusResponse")({appArn: Schema.String, appVersion: Schema.String, status: Schema.String, statusChangeTime: Schema.Date, errorMessage: Schema.optional(Schema.String), errorDetails: Schema.optional(ErrorDetailList)}) {}
export class DescribeMetricsExportResponse extends Schema.Class<DescribeMetricsExportResponse>("DescribeMetricsExportResponse")({metricsExportId: Schema.String, status: Schema.String, exportLocation: Schema.optional(S3Location), errorMessage: Schema.optional(Schema.String)}) {}
export class DescribeResiliencyPolicyResponse extends Schema.Class<DescribeResiliencyPolicyResponse>("DescribeResiliencyPolicyResponse")({policy: ResiliencyPolicy}) {}
export class ImportResourcesToDraftAppVersionResponse extends Schema.Class<ImportResourcesToDraftAppVersionResponse>("ImportResourcesToDraftAppVersionResponse")({appArn: Schema.String, appVersion: Schema.String, sourceArns: Schema.optional(ArnList), status: Schema.String, terraformSources: Schema.optional(TerraformSourceList), eksSources: Schema.optional(EksSourceList)}) {}
export class ListAppAssessmentComplianceDriftsResponse extends Schema.Class<ListAppAssessmentComplianceDriftsResponse>("ListAppAssessmentComplianceDriftsResponse")({complianceDrifts: ComplianceDriftList, nextToken: Schema.optional(Schema.String)}) {}
export class ListAppAssessmentsResponse extends Schema.Class<ListAppAssessmentsResponse>("ListAppAssessmentsResponse")({nextToken: Schema.optional(Schema.String), assessmentSummaries: AppAssessmentSummaryList}) {}
export class ListAppComponentCompliancesResponse extends Schema.Class<ListAppComponentCompliancesResponse>("ListAppComponentCompliancesResponse")({componentCompliances: ComponentCompliancesList, nextToken: Schema.optional(Schema.String)}) {}
export class ListAppInputSourcesResponse extends Schema.Class<ListAppInputSourcesResponse>("ListAppInputSourcesResponse")({appInputSources: AppInputSourceList, nextToken: Schema.optional(Schema.String)}) {}
export class ListAppsResponse extends Schema.Class<ListAppsResponse>("ListAppsResponse")({appSummaries: AppSummaryList, nextToken: Schema.optional(Schema.String)}) {}
export class ListAppVersionsResponse extends Schema.Class<ListAppVersionsResponse>("ListAppVersionsResponse")({appVersions: AppVersionList, nextToken: Schema.optional(Schema.String)}) {}
export class ListMetricsResponse extends Schema.Class<ListMetricsResponse>("ListMetricsResponse")({rows: RowList, nextToken: Schema.optional(Schema.String)}) {}
export class ListSopRecommendationsResponse extends Schema.Class<ListSopRecommendationsResponse>("ListSopRecommendationsResponse")({nextToken: Schema.optional(Schema.String), sopRecommendations: SopRecommendationList}) {}
export class ListTestRecommendationsResponse extends Schema.Class<ListTestRecommendationsResponse>("ListTestRecommendationsResponse")({nextToken: Schema.optional(Schema.String), testRecommendations: TestRecommendationList}) {}
export class ListUnsupportedAppVersionResourcesResponse extends Schema.Class<ListUnsupportedAppVersionResourcesResponse>("ListUnsupportedAppVersionResourcesResponse")({unsupportedResources: UnsupportedResourceList, resolutionId: Schema.String, nextToken: Schema.optional(Schema.String)}) {}
export class FailedGroupingRecommendationEntry extends Schema.Class<FailedGroupingRecommendationEntry>("FailedGroupingRecommendationEntry")({groupingRecommendationId: Schema.String, errorMessage: Schema.String}) {}
export const FailedGroupingRecommendationEntries = Schema.Array(FailedGroupingRecommendationEntry);
export class RejectResourceGroupingRecommendationsResponse extends Schema.Class<RejectResourceGroupingRecommendationsResponse>("RejectResourceGroupingRecommendationsResponse")({appArn: Schema.String, failedEntries: FailedGroupingRecommendationEntries}) {}
export class ServiceQuotaExceededException extends Schema.Class<ServiceQuotaExceededException>("ServiceQuotaExceededException")({message: Schema.optional(Schema.String)}) {}
export class ResourceIdentifier extends Schema.Class<ResourceIdentifier>("ResourceIdentifier")({logicalResourceId: Schema.optional(LogicalResourceId), resourceType: Schema.optional(Schema.String)}) {}
export class GroupingAppComponent extends Schema.Class<GroupingAppComponent>("GroupingAppComponent")({appComponentId: Schema.String, appComponentType: Schema.String, appComponentName: Schema.String}) {}
export class GroupingResource extends Schema.Class<GroupingResource>("GroupingResource")({resourceName: Schema.String, resourceType: Schema.String, physicalResourceId: PhysicalResourceId, logicalResourceId: LogicalResourceId, sourceAppComponentIds: String255List}) {}
export const GroupingResourceList = Schema.Array(GroupingResource);
export class ResourceDrift extends Schema.Class<ResourceDrift>("ResourceDrift")({appArn: Schema.optional(Schema.String), appVersion: Schema.optional(Schema.String), referenceId: Schema.optional(Schema.String), resourceIdentifier: Schema.optional(ResourceIdentifier), diffType: Schema.optional(Schema.String)}) {}
export const ResourceDriftList = Schema.Array(ResourceDrift);
export class GroupingRecommendation extends Schema.Class<GroupingRecommendation>("GroupingRecommendation")({groupingRecommendationId: Schema.String, groupingAppComponent: GroupingAppComponent, resources: GroupingResourceList, score: Schema.Number, recommendationReasons: String255List, status: Schema.String, confidenceLevel: Schema.String, creationTime: Schema.Date, rejectionReason: Schema.optional(Schema.String)}) {}
export const GroupingRecommendationList = Schema.Array(GroupingRecommendation);
export class AcceptResourceGroupingRecommendationsResponse extends Schema.Class<AcceptResourceGroupingRecommendationsResponse>("AcceptResourceGroupingRecommendationsResponse")({appArn: Schema.String, failedEntries: FailedGroupingRecommendationEntries}) {}
export class AddDraftAppVersionResourceMappingsResponse extends Schema.Class<AddDraftAppVersionResourceMappingsResponse>("AddDraftAppVersionResourceMappingsResponse")({appArn: Schema.String, appVersion: Schema.String, resourceMappings: ResourceMappingList}) {}
export class CreateResiliencyPolicyResponse extends Schema.Class<CreateResiliencyPolicyResponse>("CreateResiliencyPolicyResponse")({policy: ResiliencyPolicy}) {}
export class ListAppAssessmentResourceDriftsResponse extends Schema.Class<ListAppAssessmentResourceDriftsResponse>("ListAppAssessmentResourceDriftsResponse")({resourceDrifts: ResourceDriftList, nextToken: Schema.optional(Schema.String)}) {}
export class ListResourceGroupingRecommendationsResponse extends Schema.Class<ListResourceGroupingRecommendationsResponse>("ListResourceGroupingRecommendationsResponse")({groupingRecommendations: GroupingRecommendationList, nextToken: Schema.optional(Schema.String)}) {}
export class RecommendationDisruptionCompliance extends Schema.Class<RecommendationDisruptionCompliance>("RecommendationDisruptionCompliance")({expectedComplianceStatus: Schema.String, expectedRtoInSecs: Schema.optional(Schema.Number), expectedRtoDescription: Schema.optional(Schema.String), expectedRpoInSecs: Schema.optional(Schema.Number), expectedRpoDescription: Schema.optional(Schema.String)}) {}
export class BatchUpdateRecommendationStatusSuccessfulEntry extends Schema.Class<BatchUpdateRecommendationStatusSuccessfulEntry>("BatchUpdateRecommendationStatusSuccessfulEntry")({entryId: Schema.String, referenceId: Schema.String, item: Schema.optional(UpdateRecommendationStatusItem), excluded: Schema.Boolean, appComponentId: Schema.optional(Schema.String), excludeReason: Schema.optional(Schema.String)}) {}
export const BatchUpdateRecommendationStatusSuccessfulEntries = Schema.Array(BatchUpdateRecommendationStatusSuccessfulEntry);
export class BatchUpdateRecommendationStatusFailedEntry extends Schema.Class<BatchUpdateRecommendationStatusFailedEntry>("BatchUpdateRecommendationStatusFailedEntry")({entryId: Schema.String, errorMessage: Schema.String}) {}
export const BatchUpdateRecommendationStatusFailedEntries = Schema.Array(BatchUpdateRecommendationStatusFailedEntry);
export class AlarmRecommendation extends Schema.Class<AlarmRecommendation>("AlarmRecommendation")({recommendationId: Schema.String, referenceId: Schema.String, name: Schema.String, description: Schema.optional(Schema.String), type: Schema.String, appComponentName: Schema.optional(Schema.String), items: Schema.optional(RecommendationItemList), prerequisite: Schema.optional(Schema.String), appComponentNames: Schema.optional(AppComponentNameList), recommendationStatus: Schema.optional(Schema.String)}) {}
export const AlarmRecommendationList = Schema.Array(AlarmRecommendation);
export const RecommendationCompliance = Schema.Record({key: Schema.String, value: RecommendationDisruptionCompliance});
export class BatchUpdateRecommendationStatusResponse extends Schema.Class<BatchUpdateRecommendationStatusResponse>("BatchUpdateRecommendationStatusResponse")({appArn: Schema.String, successfulEntries: BatchUpdateRecommendationStatusSuccessfulEntries, failedEntries: BatchUpdateRecommendationStatusFailedEntries}) {}
export class ListAlarmRecommendationsResponse extends Schema.Class<ListAlarmRecommendationsResponse>("ListAlarmRecommendationsResponse")({alarmRecommendations: AlarmRecommendationList, nextToken: Schema.optional(Schema.String)}) {}
export class ConfigRecommendation extends Schema.Class<ConfigRecommendation>("ConfigRecommendation")({cost: Schema.optional(Cost), appComponentName: Schema.optional(Schema.String), compliance: Schema.optional(AssessmentCompliance), recommendationCompliance: Schema.optional(RecommendationCompliance), optimizationType: Schema.String, name: Schema.String, description: Schema.optional(Schema.String), suggestedChanges: Schema.optional(SuggestedChangesList), haArchitecture: Schema.optional(Schema.String), referenceId: Schema.String}) {}
export const ConfigRecommendationList = Schema.Array(ConfigRecommendation);
export class ComponentRecommendation extends Schema.Class<ComponentRecommendation>("ComponentRecommendation")({appComponentName: Schema.String, recommendationStatus: Schema.String, configRecommendations: ConfigRecommendationList}) {}
export const ComponentRecommendationList = Schema.Array(ComponentRecommendation);
export class DescribeAppAssessmentResponse extends Schema.Class<DescribeAppAssessmentResponse>("DescribeAppAssessmentResponse")({assessment: AppAssessment}) {}
export class ListAppComponentRecommendationsResponse extends Schema.Class<ListAppComponentRecommendationsResponse>("ListAppComponentRecommendationsResponse")({componentRecommendations: ComponentRecommendationList, nextToken: Schema.optional(Schema.String)}) {}

//# Errors
export class AccessDeniedExceptionError extends Schema.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class ConflictExceptionError extends Schema.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class InternalServerExceptionError extends Schema.TaggedError<InternalServerExceptionError>()("InternalServerException", InternalServerException.fields) {};
export class ResourceNotFoundExceptionError extends Schema.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ThrottlingExceptionError extends Schema.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class ValidationExceptionError extends Schema.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};
export class ServiceQuotaExceededExceptionError extends Schema.TaggedError<ServiceQuotaExceededExceptionError>()("ServiceQuotaExceededException", ServiceQuotaExceededException.fields) {};

//# Operations
export const describeAppVersion = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-app-version", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeAppVersion" }, DescribeAppVersionRequest, DescribeAppVersionResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAppVersionAppComponent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-app-version-app-component", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeAppVersionAppComponent" }, DescribeAppVersionAppComponentRequest, DescribeAppVersionAppComponentResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAppVersionResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-app-version-resource", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeAppVersionResource" }, DescribeAppVersionResourceRequest, DescribeAppVersionResourceResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAppVersionResourcesResolutionStatus = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-app-version-resources-resolution-status", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeAppVersionResourcesResolutionStatus" }, DescribeAppVersionResourcesResolutionStatusRequest, DescribeAppVersionResourcesResolutionStatusResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAppVersionTemplate = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-app-version-template", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeAppVersionTemplate" }, DescribeAppVersionTemplateRequest, DescribeAppVersionTemplateResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeResourceGroupingRecommendationTask = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-resource-grouping-recommendation-task", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeResourceGroupingRecommendationTask" }, DescribeResourceGroupingRecommendationTaskRequest, DescribeResourceGroupingRecommendationTaskResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppVersionAppComponents = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-app-version-app-components", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAppVersionAppComponents" }, ListAppVersionAppComponentsRequest, ListAppVersionAppComponentsResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppVersionResourceMappings = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-app-version-resource-mappings", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAppVersionResourceMappings" }, ListAppVersionResourceMappingsRequest, ListAppVersionResourceMappingsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppVersionResources = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-app-version-resources", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAppVersionResources" }, ListAppVersionResourcesRequest, ListAppVersionResourcesResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listRecommendationTemplates = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-recommendation-templates", method: "GET", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListRecommendationTemplates" }, ListRecommendationTemplatesRequest, ListRecommendationTemplatesResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listResiliencyPolicies = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-resiliency-policies", method: "GET", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListResiliencyPolicies" }, ListResiliencyPoliciesRequest, ListResiliencyPoliciesResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listSuggestedResiliencyPolicies = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-suggested-resiliency-policies", method: "GET", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListSuggestedResiliencyPolicies" }, ListSuggestedResiliencyPoliciesRequest, ListSuggestedResiliencyPoliciesResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/tags/{resourceArn}", method: "GET", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const publishAppVersion = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/publish-app-version", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.PublishAppVersion" }, PublishAppVersionRequest, PublishAppVersionResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putDraftAppVersionTemplate = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/put-draft-app-version-template", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.PutDraftAppVersionTemplate" }, PutDraftAppVersionTemplateRequest, PutDraftAppVersionTemplateResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const removeDraftAppVersionResourceMappings = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/remove-draft-app-version-resource-mappings", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.RemoveDraftAppVersionResourceMappings" }, RemoveDraftAppVersionResourceMappingsRequest, RemoveDraftAppVersionResourceMappingsResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const resolveAppVersionResources = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/resolve-app-version-resources", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ResolveAppVersionResources" }, ResolveAppVersionResourcesRequest, ResolveAppVersionResourcesResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const startMetricsExport = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/start-metrics-export", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.StartMetricsExport" }, StartMetricsExportRequest, StartMetricsExportResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const startResourceGroupingRecommendationTask = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/start-resource-grouping-recommendation-task", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.StartResourceGroupingRecommendationTask" }, StartResourceGroupingRecommendationTaskRequest, StartResourceGroupingRecommendationTaskResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/tags/{resourceArn}", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.TagResource" }, TagResourceRequest, TagResourceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateApp = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/update-app", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.UpdateApp" }, UpdateAppRequest, UpdateAppResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAppVersion = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/update-app-version", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.UpdateAppVersion" }, UpdateAppVersionRequest, UpdateAppVersionResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAppVersionAppComponent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/update-app-version-app-component", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.UpdateAppVersionAppComponent" }, UpdateAppVersionAppComponentRequest, UpdateAppVersionAppComponentResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAppVersionResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/update-app-version-resource", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.UpdateAppVersionResource" }, UpdateAppVersionResourceRequest, UpdateAppVersionResourceResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateResiliencyPolicy = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/update-resiliency-policy", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.UpdateResiliencyPolicy" }, UpdateResiliencyPolicyRequest, UpdateResiliencyPolicyResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createApp = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/create-app", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.CreateApp" }, CreateAppRequest, CreateAppResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createAppVersionAppComponent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/create-app-version-app-component", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.CreateAppVersionAppComponent" }, CreateAppVersionAppComponentRequest, CreateAppVersionAppComponentResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createAppVersionResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/create-app-version-resource", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.CreateAppVersionResource" }, CreateAppVersionResourceRequest, CreateAppVersionResourceResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createRecommendationTemplate = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/create-recommendation-template", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.CreateRecommendationTemplate" }, CreateRecommendationTemplateRequest, CreateRecommendationTemplateResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteApp = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/delete-app", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DeleteApp" }, DeleteAppRequest, DeleteAppResponse, [ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAppAssessment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/delete-app-assessment", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DeleteAppAssessment" }, DeleteAppAssessmentRequest, DeleteAppAssessmentResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAppInputSource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/delete-app-input-source", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DeleteAppInputSource" }, DeleteAppInputSourceRequest, DeleteAppInputSourceResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAppVersionAppComponent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/delete-app-version-app-component", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DeleteAppVersionAppComponent" }, DeleteAppVersionAppComponentRequest, DeleteAppVersionAppComponentResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAppVersionResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/delete-app-version-resource", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DeleteAppVersionResource" }, DeleteAppVersionResourceRequest, DeleteAppVersionResourceResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteRecommendationTemplate = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/delete-recommendation-template", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DeleteRecommendationTemplate" }, DeleteRecommendationTemplateRequest, DeleteRecommendationTemplateResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteResiliencyPolicy = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/delete-resiliency-policy", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DeleteResiliencyPolicy" }, DeleteResiliencyPolicyRequest, DeleteResiliencyPolicyResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeApp = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-app", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeApp" }, DescribeAppRequest, DescribeAppResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeDraftAppVersionResourcesImportStatus = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-draft-app-version-resources-import-status", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeDraftAppVersionResourcesImportStatus" }, DescribeDraftAppVersionResourcesImportStatusRequest, DescribeDraftAppVersionResourcesImportStatusResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeMetricsExport = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-metrics-export", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeMetricsExport" }, DescribeMetricsExportRequest, DescribeMetricsExportResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeResiliencyPolicy = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-resiliency-policy", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeResiliencyPolicy" }, DescribeResiliencyPolicyRequest, DescribeResiliencyPolicyResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const importResourcesToDraftAppVersion = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/import-resources-to-draft-app-version", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ImportResourcesToDraftAppVersion" }, ImportResourcesToDraftAppVersionRequest, ImportResourcesToDraftAppVersionResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppAssessmentComplianceDrifts = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-app-assessment-compliance-drifts", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAppAssessmentComplianceDrifts" }, ListAppAssessmentComplianceDriftsRequest, ListAppAssessmentComplianceDriftsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppAssessments = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-app-assessments", method: "GET", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAppAssessments" }, ListAppAssessmentsRequest, ListAppAssessmentsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppComponentCompliances = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-app-component-compliances", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAppComponentCompliances" }, ListAppComponentCompliancesRequest, ListAppComponentCompliancesResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppInputSources = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-app-input-sources", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAppInputSources" }, ListAppInputSourcesRequest, ListAppInputSourcesResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listApps = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-apps", method: "GET", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListApps" }, ListAppsRequest, ListAppsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppVersions = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-app-versions", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAppVersions" }, ListAppVersionsRequest, ListAppVersionsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listMetrics = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-metrics", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListMetrics" }, ListMetricsRequest, ListMetricsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listSopRecommendations = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-sop-recommendations", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListSopRecommendations" }, ListSopRecommendationsRequest, ListSopRecommendationsResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTestRecommendations = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-test-recommendations", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListTestRecommendations" }, ListTestRecommendationsRequest, ListTestRecommendationsResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listUnsupportedAppVersionResources = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-unsupported-app-version-resources", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListUnsupportedAppVersionResources" }, ListUnsupportedAppVersionResourcesRequest, ListUnsupportedAppVersionResourcesResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const rejectResourceGroupingRecommendations = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/reject-resource-grouping-recommendations", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.RejectResourceGroupingRecommendations" }, RejectResourceGroupingRecommendationsRequest, RejectResourceGroupingRecommendationsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const startAppAssessment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/start-app-assessment", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.StartAppAssessment" }, StartAppAssessmentRequest, StartAppAssessmentResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const acceptResourceGroupingRecommendations = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/accept-resource-grouping-recommendations", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.AcceptResourceGroupingRecommendations" }, AcceptResourceGroupingRecommendationsRequest, AcceptResourceGroupingRecommendationsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const addDraftAppVersionResourceMappings = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/add-draft-app-version-resource-mappings", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.AddDraftAppVersionResourceMappings" }, AddDraftAppVersionResourceMappingsRequest, AddDraftAppVersionResourceMappingsResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createResiliencyPolicy = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/create-resiliency-policy", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.CreateResiliencyPolicy" }, CreateResiliencyPolicyRequest, CreateResiliencyPolicyResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppAssessmentResourceDrifts = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-app-assessment-resource-drifts", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAppAssessmentResourceDrifts" }, ListAppAssessmentResourceDriftsRequest, ListAppAssessmentResourceDriftsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listResourceGroupingRecommendations = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-resource-grouping-recommendations", method: "GET", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListResourceGroupingRecommendations" }, ListResourceGroupingRecommendationsRequest, ListResourceGroupingRecommendationsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const batchUpdateRecommendationStatus = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/batch-update-recommendation-status", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.BatchUpdateRecommendationStatus" }, BatchUpdateRecommendationStatusRequest, BatchUpdateRecommendationStatusResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAlarmRecommendations = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-alarm-recommendations", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAlarmRecommendations" }, ListAlarmRecommendationsRequest, ListAlarmRecommendationsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAppAssessment = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/describe-app-assessment", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.DescribeAppAssessment" }, DescribeAppAssessmentRequest, DescribeAppAssessmentResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listAppComponentRecommendations = /*#__PURE__*/ makeOperation(() => Operation({ version: "2020-04-30", uri: "/list-app-component-recommendations", method: "POST", sdkId: "resiliencehub", sigV4ServiceName: "resiliencehub", name: "AwsResilienceHub.ListAppComponentRecommendations" }, ListAppComponentRecommendationsRequest, ListAppComponentRecommendationsResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
