import * as S from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const SecretIdListType = S.Array(S.String);
export const SecretVersionStagesType = S.Array(S.String);
export const RemoveReplicaRegionListType = S.Array(S.String);
export const TagKeyListType = S.Array(S.String);
export class CancelRotateSecretRequest extends S.Class<CancelRotateSecretRequest>("CancelRotateSecretRequest")({SecretId: S.String}) {}
export class DeleteResourcePolicyRequest extends S.Class<DeleteResourcePolicyRequest>("DeleteResourcePolicyRequest")({SecretId: S.String}) {}
export class DeleteSecretRequest extends S.Class<DeleteSecretRequest>("DeleteSecretRequest")({SecretId: S.String, RecoveryWindowInDays: S.optional(S.Number), ForceDeleteWithoutRecovery: S.optional(S.Boolean)}) {}
export class DescribeSecretRequest extends S.Class<DescribeSecretRequest>("DescribeSecretRequest")({SecretId: S.String}) {}
export class GetRandomPasswordRequest extends S.Class<GetRandomPasswordRequest>("GetRandomPasswordRequest")({PasswordLength: S.optional(S.Number), ExcludeCharacters: S.optional(S.String), ExcludeNumbers: S.optional(S.Boolean), ExcludePunctuation: S.optional(S.Boolean), ExcludeUppercase: S.optional(S.Boolean), ExcludeLowercase: S.optional(S.Boolean), IncludeSpace: S.optional(S.Boolean), RequireEachIncludedType: S.optional(S.Boolean)}) {}
export class GetResourcePolicyRequest extends S.Class<GetResourcePolicyRequest>("GetResourcePolicyRequest")({SecretId: S.String}) {}
export class GetSecretValueRequest extends S.Class<GetSecretValueRequest>("GetSecretValueRequest")({SecretId: S.String, VersionId: S.optional(S.String), VersionStage: S.optional(S.String)}) {}
export const FilterValuesStringList = S.Array(S.String);
export class Filter extends S.Class<Filter>("Filter")({Key: S.optional(S.String), Values: S.optional(FilterValuesStringList)}) {}
export const FiltersListType = S.Array(Filter);
export class ListSecretsRequest extends S.Class<ListSecretsRequest>("ListSecretsRequest")({IncludePlannedDeletion: S.optional(S.Boolean), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), Filters: S.optional(FiltersListType), SortOrder: S.optional(S.String), SortBy: S.optional(S.String)}) {}
export class ListSecretVersionIdsRequest extends S.Class<ListSecretVersionIdsRequest>("ListSecretVersionIdsRequest")({SecretId: S.String, MaxResults: S.optional(S.Number), NextToken: S.optional(S.String), IncludeDeprecated: S.optional(S.Boolean)}) {}
export class PutResourcePolicyRequest extends S.Class<PutResourcePolicyRequest>("PutResourcePolicyRequest")({SecretId: S.String, ResourcePolicy: S.String, BlockPublicPolicy: S.optional(S.Boolean)}) {}
export class PutSecretValueRequest extends S.Class<PutSecretValueRequest>("PutSecretValueRequest")({SecretId: S.String, ClientRequestToken: S.optional(S.String), SecretBinary: S.optional(H.StreamBody()), SecretString: S.optional(S.String), VersionStages: S.optional(SecretVersionStagesType), RotationToken: S.optional(S.String)}) {}
export class RemoveRegionsFromReplicationRequest extends S.Class<RemoveRegionsFromReplicationRequest>("RemoveRegionsFromReplicationRequest")({SecretId: S.String, RemoveReplicaRegions: RemoveReplicaRegionListType}) {}
export class ReplicaRegionType extends S.Class<ReplicaRegionType>("ReplicaRegionType")({Region: S.optional(S.String), KmsKeyId: S.optional(S.String)}) {}
export const AddReplicaRegionListType = S.Array(ReplicaRegionType);
export class ReplicateSecretToRegionsRequest extends S.Class<ReplicateSecretToRegionsRequest>("ReplicateSecretToRegionsRequest")({SecretId: S.String, AddReplicaRegions: AddReplicaRegionListType, ForceOverwriteReplicaSecret: S.optional(S.Boolean)}) {}
export class RestoreSecretRequest extends S.Class<RestoreSecretRequest>("RestoreSecretRequest")({SecretId: S.String}) {}
export class StopReplicationToReplicaRequest extends S.Class<StopReplicationToReplicaRequest>("StopReplicationToReplicaRequest")({SecretId: S.String}) {}
export class Tag extends S.Class<Tag>("Tag")({Key: S.optional(S.String), Value: S.optional(S.String)}) {}
export const TagListType = S.Array(Tag);
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({SecretId: S.String, Tags: TagListType}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({SecretId: S.String, TagKeys: TagKeyListType}) {}
export class UpdateSecretRequest extends S.Class<UpdateSecretRequest>("UpdateSecretRequest")({SecretId: S.String, ClientRequestToken: S.optional(S.String), Description: S.optional(S.String), KmsKeyId: S.optional(S.String), SecretBinary: S.optional(H.StreamBody()), SecretString: S.optional(S.String), Type: S.optional(S.String)}) {}
export class UpdateSecretVersionStageRequest extends S.Class<UpdateSecretVersionStageRequest>("UpdateSecretVersionStageRequest")({SecretId: S.String, VersionStage: S.String, RemoveFromVersionId: S.optional(S.String), MoveToVersionId: S.optional(S.String)}) {}
export class ValidateResourcePolicyRequest extends S.Class<ValidateResourcePolicyRequest>("ValidateResourcePolicyRequest")({SecretId: S.optional(S.String), ResourcePolicy: S.String}) {}
export class RotationRulesType extends S.Class<RotationRulesType>("RotationRulesType")({AutomaticallyAfterDays: S.optional(S.Number), Duration: S.optional(S.String), ScheduleExpression: S.optional(S.String)}) {}
export class ExternalSecretRotationMetadataItem extends S.Class<ExternalSecretRotationMetadataItem>("ExternalSecretRotationMetadataItem")({Key: S.optional(S.String), Value: S.optional(S.String)}) {}
export const ExternalSecretRotationMetadataType = S.Array(ExternalSecretRotationMetadataItem);
export class BatchGetSecretValueRequest extends S.Class<BatchGetSecretValueRequest>("BatchGetSecretValueRequest")({SecretIdList: S.optional(SecretIdListType), Filters: S.optional(FiltersListType), MaxResults: S.optional(S.Number), NextToken: S.optional(S.String)}) {}
export class CancelRotateSecretResponse extends S.Class<CancelRotateSecretResponse>("CancelRotateSecretResponse")({ARN: S.optional(S.String), Name: S.optional(S.String), VersionId: S.optional(S.String)}) {}
export class CreateSecretRequest extends S.Class<CreateSecretRequest>("CreateSecretRequest")({Name: S.String, ClientRequestToken: S.optional(S.String), Description: S.optional(S.String), KmsKeyId: S.optional(S.String), SecretBinary: S.optional(H.StreamBody()), SecretString: S.optional(S.String), Tags: S.optional(TagListType), AddReplicaRegions: S.optional(AddReplicaRegionListType), ForceOverwriteReplicaSecret: S.optional(S.Boolean), Type: S.optional(S.String)}) {}
export class DeleteResourcePolicyResponse extends S.Class<DeleteResourcePolicyResponse>("DeleteResourcePolicyResponse")({ARN: S.optional(S.String), Name: S.optional(S.String)}) {}
export class DeleteSecretResponse extends S.Class<DeleteSecretResponse>("DeleteSecretResponse")({ARN: S.optional(S.String), Name: S.optional(S.String), DeletionDate: S.optional(S.Date)}) {}
export class GetRandomPasswordResponse extends S.Class<GetRandomPasswordResponse>("GetRandomPasswordResponse")({RandomPassword: S.optional(S.String)}) {}
export class GetResourcePolicyResponse extends S.Class<GetResourcePolicyResponse>("GetResourcePolicyResponse")({ARN: S.optional(S.String), Name: S.optional(S.String), ResourcePolicy: S.optional(S.String)}) {}
export class GetSecretValueResponse extends S.Class<GetSecretValueResponse>("GetSecretValueResponse")({ARN: S.optional(S.String), Name: S.optional(S.String), VersionId: S.optional(S.String), SecretBinary: S.optional(H.StreamBody()), SecretString: S.optional(S.String), VersionStages: S.optional(SecretVersionStagesType), CreatedDate: S.optional(S.Date)}) {}
export class PutResourcePolicyResponse extends S.Class<PutResourcePolicyResponse>("PutResourcePolicyResponse")({ARN: S.optional(S.String), Name: S.optional(S.String)}) {}
export class PutSecretValueResponse extends S.Class<PutSecretValueResponse>("PutSecretValueResponse")({ARN: S.optional(S.String), Name: S.optional(S.String), VersionId: S.optional(S.String), VersionStages: S.optional(SecretVersionStagesType)}) {}
export class ReplicationStatusType extends S.Class<ReplicationStatusType>("ReplicationStatusType")({Region: S.optional(S.String), KmsKeyId: S.optional(S.String), Status: S.optional(S.String), StatusMessage: S.optional(S.String), LastAccessedDate: S.optional(S.Date)}) {}
export const ReplicationStatusListType = S.Array(ReplicationStatusType);
export class RemoveRegionsFromReplicationResponse extends S.Class<RemoveRegionsFromReplicationResponse>("RemoveRegionsFromReplicationResponse")({ARN: S.optional(S.String), ReplicationStatus: S.optional(ReplicationStatusListType)}) {}
export class ReplicateSecretToRegionsResponse extends S.Class<ReplicateSecretToRegionsResponse>("ReplicateSecretToRegionsResponse")({ARN: S.optional(S.String), ReplicationStatus: S.optional(ReplicationStatusListType)}) {}
export class RestoreSecretResponse extends S.Class<RestoreSecretResponse>("RestoreSecretResponse")({ARN: S.optional(S.String), Name: S.optional(S.String)}) {}
export class RotateSecretRequest extends S.Class<RotateSecretRequest>("RotateSecretRequest")({SecretId: S.String, ClientRequestToken: S.optional(S.String), RotationLambdaARN: S.optional(S.String), RotationRules: S.optional(RotationRulesType), ExternalSecretRotationMetadata: S.optional(ExternalSecretRotationMetadataType), ExternalSecretRotationRoleArn: S.optional(S.String), RotateImmediately: S.optional(S.Boolean)}) {}
export class StopReplicationToReplicaResponse extends S.Class<StopReplicationToReplicaResponse>("StopReplicationToReplicaResponse")({ARN: S.optional(S.String)}) {}
export class InternalServiceError extends S.Class<InternalServiceError>("InternalServiceError")({Message: S.optional(S.String)}) {}
export class InvalidParameterException extends S.Class<InvalidParameterException>("InvalidParameterException")({Message: S.optional(S.String)}) {}
export class UpdateSecretResponse extends S.Class<UpdateSecretResponse>("UpdateSecretResponse")({ARN: S.optional(S.String), Name: S.optional(S.String), VersionId: S.optional(S.String)}) {}
export class UpdateSecretVersionStageResponse extends S.Class<UpdateSecretVersionStageResponse>("UpdateSecretVersionStageResponse")({ARN: S.optional(S.String), Name: S.optional(S.String)}) {}
export const KmsKeyIdListType = S.Array(S.String);
export const SecretVersionsToStagesMapType = S.Record({key: S.String, value: SecretVersionStagesType});
export class SecretListEntry extends S.Class<SecretListEntry>("SecretListEntry")({ARN: S.optional(S.String), Name: S.optional(S.String), Type: S.optional(S.String), Description: S.optional(S.String), KmsKeyId: S.optional(S.String), RotationEnabled: S.optional(S.Boolean), RotationLambdaARN: S.optional(S.String), RotationRules: S.optional(RotationRulesType), ExternalSecretRotationMetadata: S.optional(ExternalSecretRotationMetadataType), ExternalSecretRotationRoleArn: S.optional(S.String), LastRotatedDate: S.optional(S.Date), LastChangedDate: S.optional(S.Date), LastAccessedDate: S.optional(S.Date), DeletedDate: S.optional(S.Date), NextRotationDate: S.optional(S.Date), Tags: S.optional(TagListType), SecretVersionsToStages: S.optional(SecretVersionsToStagesMapType), OwningService: S.optional(S.String), CreatedDate: S.optional(S.Date), PrimaryRegion: S.optional(S.String)}) {}
export const SecretListType = S.Array(SecretListEntry);
export class SecretVersionsListEntry extends S.Class<SecretVersionsListEntry>("SecretVersionsListEntry")({VersionId: S.optional(S.String), VersionStages: S.optional(SecretVersionStagesType), LastAccessedDate: S.optional(S.Date), CreatedDate: S.optional(S.Date), KmsKeyIds: S.optional(KmsKeyIdListType)}) {}
export const SecretVersionsListType = S.Array(SecretVersionsListEntry);
export class ValidationErrorsEntry extends S.Class<ValidationErrorsEntry>("ValidationErrorsEntry")({CheckName: S.optional(S.String), ErrorMessage: S.optional(S.String)}) {}
export const ValidationErrorsType = S.Array(ValidationErrorsEntry);
export class InvalidRequestException extends S.Class<InvalidRequestException>("InvalidRequestException")({Message: S.optional(S.String)}) {}
export class CreateSecretResponse extends S.Class<CreateSecretResponse>("CreateSecretResponse")({ARN: S.optional(S.String), Name: S.optional(S.String), VersionId: S.optional(S.String), ReplicationStatus: S.optional(ReplicationStatusListType)}) {}
export class ResourceNotFoundException extends S.Class<ResourceNotFoundException>("ResourceNotFoundException")({Message: S.optional(S.String)}) {}
export class DescribeSecretResponse extends S.Class<DescribeSecretResponse>("DescribeSecretResponse")({ARN: S.optional(S.String), Name: S.optional(S.String), Type: S.optional(S.String), Description: S.optional(S.String), KmsKeyId: S.optional(S.String), RotationEnabled: S.optional(S.Boolean), RotationLambdaARN: S.optional(S.String), RotationRules: S.optional(RotationRulesType), ExternalSecretRotationMetadata: S.optional(ExternalSecretRotationMetadataType), ExternalSecretRotationRoleArn: S.optional(S.String), LastRotatedDate: S.optional(S.Date), LastChangedDate: S.optional(S.Date), LastAccessedDate: S.optional(S.Date), DeletedDate: S.optional(S.Date), NextRotationDate: S.optional(S.Date), Tags: S.optional(TagListType), VersionIdsToStages: S.optional(SecretVersionsToStagesMapType), OwningService: S.optional(S.String), CreatedDate: S.optional(S.Date), PrimaryRegion: S.optional(S.String), ReplicationStatus: S.optional(ReplicationStatusListType)}) {}
export class DecryptionFailure extends S.Class<DecryptionFailure>("DecryptionFailure")({Message: S.optional(S.String)}) {}
export class ListSecretsResponse extends S.Class<ListSecretsResponse>("ListSecretsResponse")({SecretList: S.optional(SecretListType), NextToken: S.optional(S.String)}) {}
export class ListSecretVersionIdsResponse extends S.Class<ListSecretVersionIdsResponse>("ListSecretVersionIdsResponse")({Versions: S.optional(SecretVersionsListType), NextToken: S.optional(S.String), ARN: S.optional(S.String), Name: S.optional(S.String)}) {}
export class MalformedPolicyDocumentException extends S.Class<MalformedPolicyDocumentException>("MalformedPolicyDocumentException")({Message: S.optional(S.String)}) {}
export class EncryptionFailure extends S.Class<EncryptionFailure>("EncryptionFailure")({Message: S.optional(S.String)}) {}
export class RotateSecretResponse extends S.Class<RotateSecretResponse>("RotateSecretResponse")({ARN: S.optional(S.String), Name: S.optional(S.String), VersionId: S.optional(S.String)}) {}
export class LimitExceededException extends S.Class<LimitExceededException>("LimitExceededException")({Message: S.optional(S.String)}) {}
export class ValidateResourcePolicyResponse extends S.Class<ValidateResourcePolicyResponse>("ValidateResourcePolicyResponse")({PolicyValidationPassed: S.optional(S.Boolean), ValidationErrors: S.optional(ValidationErrorsType)}) {}
export class SecretValueEntry extends S.Class<SecretValueEntry>("SecretValueEntry")({ARN: S.optional(S.String), Name: S.optional(S.String), VersionId: S.optional(S.String), SecretBinary: S.optional(H.StreamBody()), SecretString: S.optional(S.String), VersionStages: S.optional(SecretVersionStagesType), CreatedDate: S.optional(S.Date)}) {}
export const SecretValuesType = S.Array(SecretValueEntry);
export class APIErrorType extends S.Class<APIErrorType>("APIErrorType")({SecretId: S.optional(S.String), ErrorCode: S.optional(S.String), Message: S.optional(S.String)}) {}
export const APIErrorListType = S.Array(APIErrorType);
export class BatchGetSecretValueResponse extends S.Class<BatchGetSecretValueResponse>("BatchGetSecretValueResponse")({SecretValues: S.optional(SecretValuesType), NextToken: S.optional(S.String), Errors: S.optional(APIErrorListType)}) {}
export class PreconditionNotMetException extends S.Class<PreconditionNotMetException>("PreconditionNotMetException")({Message: S.optional(S.String)}) {}
export class InvalidNextTokenException extends S.Class<InvalidNextTokenException>("InvalidNextTokenException")({Message: S.optional(S.String)}) {}
export class PublicPolicyException extends S.Class<PublicPolicyException>("PublicPolicyException")({Message: S.optional(S.String)}) {}
export class ResourceExistsException extends S.Class<ResourceExistsException>("ResourceExistsException")({Message: S.optional(S.String)}) {}

//# Errors
export class InternalServiceErrorError extends S.TaggedError<InternalServiceErrorError>()("InternalServiceError", InternalServiceError.fields) {};
export class InvalidParameterExceptionError extends S.TaggedError<InvalidParameterExceptionError>()("InvalidParameterException", InvalidParameterException.fields) {};
export class InvalidRequestExceptionError extends S.TaggedError<InvalidRequestExceptionError>()("InvalidRequestException", InvalidRequestException.fields) {};
export class ResourceNotFoundExceptionError extends S.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class DecryptionFailureError extends S.TaggedError<DecryptionFailureError>()("DecryptionFailure", DecryptionFailure.fields) {};
export class EncryptionFailureError extends S.TaggedError<EncryptionFailureError>()("EncryptionFailure", EncryptionFailure.fields) {};
export class LimitExceededExceptionError extends S.TaggedError<LimitExceededExceptionError>()("LimitExceededException", LimitExceededException.fields) {};
export class MalformedPolicyDocumentExceptionError extends S.TaggedError<MalformedPolicyDocumentExceptionError>()("MalformedPolicyDocumentException", MalformedPolicyDocumentException.fields) {};
export class InvalidNextTokenExceptionError extends S.TaggedError<InvalidNextTokenExceptionError>()("InvalidNextTokenException", InvalidNextTokenException.fields) {};
export class PreconditionNotMetExceptionError extends S.TaggedError<PreconditionNotMetExceptionError>()("PreconditionNotMetException", PreconditionNotMetException.fields) {};
export class ResourceExistsExceptionError extends S.TaggedError<ResourceExistsExceptionError>()("ResourceExistsException", ResourceExistsException.fields) {};
export class PublicPolicyExceptionError extends S.TaggedError<PublicPolicyExceptionError>()("PublicPolicyException", PublicPolicyException.fields) {};

//# Operations
export const deleteSecret = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.DeleteSecret" }, DeleteSecretRequest, DeleteSecretResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getRandomPassword = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.GetRandomPassword" }, GetRandomPasswordRequest, GetRandomPasswordResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getResourcePolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.GetResourcePolicy" }, GetResourcePolicyRequest, GetResourcePolicyResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const removeRegionsFromReplication = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.RemoveRegionsFromReplication" }, RemoveRegionsFromReplicationRequest, RemoveRegionsFromReplicationResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const replicateSecretToRegions = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.ReplicateSecretToRegions" }, ReplicateSecretToRegionsRequest, ReplicateSecretToRegionsResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const restoreSecret = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.RestoreSecret" }, RestoreSecretRequest, RestoreSecretResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const stopReplicationToReplica = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.StopReplicationToReplica" }, StopReplicationToReplicaRequest, StopReplicationToReplicaResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.TagResource" }, TagResourceRequest, S.Struct({}), [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.UntagResource" }, UntagResourceRequest, S.Struct({}), [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateSecretVersionStage = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.UpdateSecretVersionStage" }, UpdateSecretVersionStageRequest, UpdateSecretVersionStageResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const cancelRotateSecret = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.CancelRotateSecret" }, CancelRotateSecretRequest, CancelRotateSecretResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteResourcePolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.DeleteResourcePolicy" }, DeleteResourcePolicyRequest, DeleteResourcePolicyResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeSecret = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.DescribeSecret" }, DescribeSecretRequest, DescribeSecretResponse, [InternalServiceErrorError, InvalidParameterExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const getSecretValue = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.GetSecretValue" }, GetSecretValueRequest, GetSecretValueResponse, [DecryptionFailureError, InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listSecretVersionIds = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.ListSecretVersionIds" }, ListSecretVersionIdsRequest, ListSecretVersionIdsResponse, [InternalServiceErrorError, InvalidNextTokenExceptionError, InvalidParameterExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const rotateSecret = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.RotateSecret" }, RotateSecretRequest, RotateSecretResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateSecret = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.UpdateSecret" }, UpdateSecretRequest, UpdateSecretResponse, [DecryptionFailureError, EncryptionFailureError, InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError, MalformedPolicyDocumentExceptionError, PreconditionNotMetExceptionError, ResourceExistsExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const validateResourcePolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.ValidateResourcePolicy" }, ValidateResourcePolicyRequest, ValidateResourcePolicyResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, MalformedPolicyDocumentExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const batchGetSecretValue = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.BatchGetSecretValue" }, BatchGetSecretValueRequest, BatchGetSecretValueResponse, [DecryptionFailureError, InternalServiceErrorError, InvalidNextTokenExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createSecret = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.CreateSecret" }, CreateSecretRequest, CreateSecretResponse, [DecryptionFailureError, EncryptionFailureError, InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError, MalformedPolicyDocumentExceptionError, PreconditionNotMetExceptionError, ResourceExistsExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listSecrets = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.ListSecrets" }, ListSecretsRequest, ListSecretsResponse, [InternalServiceErrorError, InvalidNextTokenExceptionError, InvalidParameterExceptionError, InvalidRequestExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const putResourcePolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.PutResourcePolicy" }, PutResourcePolicyRequest, PutResourcePolicyResponse, [InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, MalformedPolicyDocumentExceptionError, PublicPolicyExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const putSecretValue = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2017-10-17", uri: "/", method: "POST", sdkId: "Secrets Manager", sigV4ServiceName: "secretsmanager", name: "secretsmanager.PutSecretValue" }, PutSecretValueRequest, PutSecretValueResponse, [DecryptionFailureError, EncryptionFailureError, InternalServiceErrorError, InvalidParameterExceptionError, InvalidRequestExceptionError, LimitExceededExceptionError, ResourceExistsExceptionError, ResourceNotFoundExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
