import { Schema} from "effect"
import { FormatXMLRequest, FormatXMLResponse, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
const CertificateHashes = Schema.Array(Schema.String)
const Statuses = Schema.Array(Schema.String)
const TagKeyList = Schema.Array(Schema.String)
const AddProfilePermissionRequest = Schema.Struct({profileName: Schema.String, profileVersion: Schema.optional(Schema.String), action: Schema.String, principal: Schema.String, revisionId: Schema.optional(Schema.String), statementId: Schema.String})
const CancelSigningProfileRequest = Schema.Struct({profileName: Schema.String})
const DescribeSigningJobRequest = Schema.Struct({jobId: Schema.String})
const GetRevocationStatusRequest = Schema.Struct({signatureTimestamp: Schema.Date, platformId: Schema.String, profileVersionArn: Schema.String, jobArn: Schema.String, certificateHashes: CertificateHashes})
const GetSigningPlatformRequest = Schema.Struct({platformId: Schema.String})
const GetSigningProfileRequest = Schema.Struct({profileName: Schema.String, profileOwner: Schema.optional(Schema.String)})
const ListProfilePermissionsRequest = Schema.Struct({profileName: Schema.String, nextToken: Schema.optional(Schema.String)})
const ListSigningJobsRequest = Schema.Struct({status: Schema.optional(Schema.String), platformId: Schema.optional(Schema.String), requestedBy: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String), isRevoked: Schema.optional(Schema.Boolean), signatureExpiresBefore: Schema.optional(Schema.Date), signatureExpiresAfter: Schema.optional(Schema.Date), jobInvoker: Schema.optional(Schema.String)})
const ListSigningPlatformsRequest = Schema.Struct({category: Schema.optional(Schema.String), partner: Schema.optional(Schema.String), target: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)})
const ListSigningProfilesRequest = Schema.Struct({includeCanceled: Schema.optional(Schema.Boolean), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String), platformId: Schema.optional(Schema.String), statuses: Schema.optional(Statuses)})
const ListTagsForResourceRequest = Schema.Struct({resourceArn: Schema.String})
const RemoveProfilePermissionRequest = Schema.Struct({profileName: Schema.String, revisionId: Schema.String, statementId: Schema.String})
const RevokeSignatureRequest = Schema.Struct({jobId: Schema.String, jobOwner: Schema.optional(Schema.String), reason: Schema.String})
const RevokeSigningProfileRequest = Schema.Struct({profileName: Schema.String, profileVersion: Schema.String, reason: Schema.String, effectiveTime: Schema.Date})
const SignPayloadRequest = Schema.Struct({profileName: Schema.String, profileOwner: Schema.optional(Schema.String), payload: StreamBody(), payloadFormat: Schema.String})
const TagResourceRequest = Schema.Struct({resourceArn: Schema.String, tags: TagMap})
const TagResourceResponse = Schema.Struct({})
const UntagResourceRequest = Schema.Struct({resourceArn: Schema.String, tagKeys: TagKeyList})
const UntagResourceResponse = Schema.Struct({})
const RevokedEntities = Schema.Array(Schema.String)
const SigningMaterial = Schema.Struct({certificateArn: Schema.String})
const SignatureValidityPeriod = Schema.Struct({value: Schema.optional(Schema.Number), type: Schema.optional(Schema.String)})
const SigningParameters = Schema.Record({key: Schema.String, value: Schema.String})
const TagMap = Schema.Record({key: Schema.String, value: Schema.String})
const AddProfilePermissionResponse = Schema.Struct({revisionId: Schema.optional(Schema.String)})
const AccessDeniedException = Schema.Struct({message: Schema.optional(Schema.String), code: Schema.optional(Schema.String)})
const GetRevocationStatusResponse = Schema.Struct({revokedEntities: Schema.optional(RevokedEntities)})
const ListTagsForResourceResponse = Schema.Struct({tags: Schema.optional(TagMap)})
export const ListTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "GET", sdkId: "signer", sigV4ServiceName: "signer", name: "ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const RemoveProfilePermissionResponse = Schema.Struct({revisionId: Schema.optional(Schema.String)})
export const RemoveProfilePermission = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-profiles/{profileName}/permissions/{statementId}", method: "DELETE", sdkId: "signer", sigV4ServiceName: "signer", name: "RemoveProfilePermission" }, RemoveProfilePermissionRequest, RemoveProfilePermissionResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const InternalServiceErrorException = Schema.Struct({message: Schema.optional(Schema.String), code: Schema.optional(Schema.String)})
export const RevokeSignature = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-jobs/{jobId}/revoke", method: "PUT", sdkId: "signer", sigV4ServiceName: "signer", name: "RevokeSignature" }, RevokeSignatureRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ResourceNotFoundException = Schema.Struct({message: Schema.optional(Schema.String), code: Schema.optional(Schema.String)})
export const RevokeSigningProfile = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-profiles/{profileName}/revoke", method: "PUT", sdkId: "signer", sigV4ServiceName: "signer", name: "RevokeSigningProfile" }, RevokeSigningProfileRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const BadRequestException = Schema.Struct({message: Schema.optional(Schema.String), code: Schema.optional(Schema.String)})
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "POST", sdkId: "signer", sigV4ServiceName: "signer", name: "TagResource" }, TagResourceRequest, TagResourceResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const NotFoundException = Schema.Struct({message: Schema.optional(Schema.String), code: Schema.optional(Schema.String)})
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "signer", sigV4ServiceName: "signer", name: "UntagResource" }, UntagResourceRequest, UntagResourceResponse, Schema.Union(ErrorAnnotation("BadRequestException", BadRequestException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("NotFoundException", NotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ImageFormats = Schema.Array(Schema.String)
const SigningConfigurationOverrides = Schema.Struct({encryptionAlgorithm: Schema.optional(Schema.String), hashAlgorithm: Schema.optional(Schema.String)})
const S3Source = Schema.Struct({bucketName: Schema.String, key: Schema.String, version: Schema.String})
const S3Destination = Schema.Struct({bucketName: Schema.optional(Schema.String), prefix: Schema.optional(Schema.String)})
const SigningJobRevocationRecord = Schema.Struct({reason: Schema.optional(Schema.String), revokedAt: Schema.optional(Schema.Date), revokedBy: Schema.optional(Schema.String)})
const SigningImageFormat = Schema.Struct({supportedFormats: ImageFormats, defaultFormat: Schema.String})
const SigningProfileRevocationRecord = Schema.Struct({revocationEffectiveFrom: Schema.optional(Schema.Date), revokedAt: Schema.optional(Schema.Date), revokedBy: Schema.optional(Schema.String)})
const Permission = Schema.Struct({action: Schema.optional(Schema.String), principal: Schema.optional(Schema.String), statementId: Schema.optional(Schema.String), profileVersion: Schema.optional(Schema.String)})
const Permissions = Schema.Array(Permission)
const SigningJob = Schema.Struct({jobId: Schema.optional(Schema.String), source: Schema.optional(Source), signedObject: Schema.optional(SignedObject), signingMaterial: Schema.optional(SigningMaterial), createdAt: Schema.optional(Schema.Date), status: Schema.optional(Schema.String), isRevoked: Schema.optional(Schema.Boolean), profileName: Schema.optional(Schema.String), profileVersion: Schema.optional(Schema.String), platformId: Schema.optional(Schema.String), platformDisplayName: Schema.optional(Schema.String), signatureExpiresAt: Schema.optional(Schema.Date), jobOwner: Schema.optional(Schema.String), jobInvoker: Schema.optional(Schema.String)})
const SigningJobs = Schema.Array(SigningJob)
const SigningPlatform = Schema.Struct({platformId: Schema.optional(Schema.String), displayName: Schema.optional(Schema.String), partner: Schema.optional(Schema.String), target: Schema.optional(Schema.String), category: Schema.optional(Schema.String), signingConfiguration: Schema.optional(SigningConfiguration), signingImageFormat: Schema.optional(SigningImageFormat), maxSizeInMB: Schema.optional(Schema.Number), revocationSupported: Schema.optional(Schema.Boolean)})
const SigningPlatforms = Schema.Array(SigningPlatform)
const SigningProfile = Schema.Struct({profileName: Schema.optional(Schema.String), profileVersion: Schema.optional(Schema.String), profileVersionArn: Schema.optional(Schema.String), signingMaterial: Schema.optional(SigningMaterial), signatureValidityPeriod: Schema.optional(SignatureValidityPeriod), platformId: Schema.optional(Schema.String), platformDisplayName: Schema.optional(Schema.String), signingParameters: Schema.optional(SigningParameters), status: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), tags: Schema.optional(TagMap)})
const SigningProfiles = Schema.Array(SigningProfile)
const SigningPlatformOverrides = Schema.Struct({signingConfiguration: Schema.optional(SigningConfigurationOverrides), signingImageFormat: Schema.optional(Schema.String)})
const Metadata = Schema.Record({key: Schema.String, value: Schema.String})
const Source = Schema.Struct({s3: Schema.optional(S3Source)})
const Destination = Schema.Struct({s3: Schema.optional(S3Destination)})
const EncryptionAlgorithms = Schema.Array(Schema.String)
const HashAlgorithms = Schema.Array(Schema.String)
const ConflictException = Schema.Struct({message: Schema.optional(Schema.String), code: Schema.optional(Schema.String)})
const TooManyRequestsException = Schema.Struct({message: Schema.optional(Schema.String), code: Schema.optional(Schema.String)})
export const CancelSigningProfile = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-profiles/{profileName}", method: "DELETE", sdkId: "signer", sigV4ServiceName: "signer", name: "CancelSigningProfile" }, CancelSigningProfileRequest, Schema.Struct({}), Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ValidationException = Schema.Struct({message: Schema.optional(Schema.String), code: Schema.optional(Schema.String)})
export const GetRevocationStatus = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/revocations", method: "GET", sdkId: "signer", sigV4ServiceName: "signer", name: "GetRevocationStatus" }, GetRevocationStatusRequest, GetRevocationStatusResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetSigningProfileResponse = Schema.Struct({profileName: Schema.optional(Schema.String), profileVersion: Schema.optional(Schema.String), profileVersionArn: Schema.optional(Schema.String), revocationRecord: Schema.optional(SigningProfileRevocationRecord), signingMaterial: Schema.optional(SigningMaterial), platformId: Schema.optional(Schema.String), platformDisplayName: Schema.optional(Schema.String), signatureValidityPeriod: Schema.optional(SignatureValidityPeriod), overrides: Schema.optional(SigningPlatformOverrides), signingParameters: Schema.optional(SigningParameters), status: Schema.optional(Schema.String), statusReason: Schema.optional(Schema.String), arn: Schema.optional(Schema.String), tags: Schema.optional(TagMap)})
export const GetSigningProfile = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-profiles/{profileName}", method: "GET", sdkId: "signer", sigV4ServiceName: "signer", name: "GetSigningProfile" }, GetSigningProfileRequest, GetSigningProfileResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListProfilePermissionsResponse = Schema.Struct({revisionId: Schema.optional(Schema.String), policySizeBytes: Schema.optional(Schema.Number), permissions: Schema.optional(Permissions), nextToken: Schema.optional(Schema.String)})
export const ListProfilePermissions = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-profiles/{profileName}/permissions", method: "GET", sdkId: "signer", sigV4ServiceName: "signer", name: "ListProfilePermissions" }, ListProfilePermissionsRequest, ListProfilePermissionsResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListSigningJobsResponse = Schema.Struct({jobs: Schema.optional(SigningJobs), nextToken: Schema.optional(Schema.String)})
export const ListSigningJobs = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-jobs", method: "GET", sdkId: "signer", sigV4ServiceName: "signer", name: "ListSigningJobs" }, ListSigningJobsRequest, ListSigningJobsResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListSigningPlatformsResponse = Schema.Struct({platforms: Schema.optional(SigningPlatforms), nextToken: Schema.optional(Schema.String)})
export const ListSigningPlatforms = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-platforms", method: "GET", sdkId: "signer", sigV4ServiceName: "signer", name: "ListSigningPlatforms" }, ListSigningPlatformsRequest, ListSigningPlatformsResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListSigningProfilesResponse = Schema.Struct({profiles: Schema.optional(SigningProfiles), nextToken: Schema.optional(Schema.String)})
export const ListSigningProfiles = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-profiles", method: "GET", sdkId: "signer", sigV4ServiceName: "signer", name: "ListSigningProfiles" }, ListSigningProfilesRequest, ListSigningProfilesResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const PutSigningProfileRequest = Schema.Struct({profileName: Schema.String, signingMaterial: Schema.optional(SigningMaterial), signatureValidityPeriod: Schema.optional(SignatureValidityPeriod), platformId: Schema.String, overrides: Schema.optional(SigningPlatformOverrides), signingParameters: Schema.optional(SigningParameters), tags: Schema.optional(TagMap)})
const SignPayloadResponse = Schema.Struct({jobId: Schema.optional(Schema.String), jobOwner: Schema.optional(Schema.String), metadata: Schema.optional(Metadata), signature: Schema.optional(StreamBody())})
export const SignPayload = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-jobs/with-payload", method: "POST", sdkId: "signer", sigV4ServiceName: "signer", name: "SignPayload" }, SignPayloadRequest, SignPayloadResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const StartSigningJobRequest = Schema.Struct({source: Source, destination: Destination, profileName: Schema.String, clientRequestToken: Schema.String, profileOwner: Schema.optional(Schema.String)})
const S3SignedObject = Schema.Struct({bucketName: Schema.optional(Schema.String), key: Schema.optional(Schema.String)})
const EncryptionAlgorithmOptions = Schema.Struct({allowedValues: EncryptionAlgorithms, defaultValue: Schema.String})
const HashAlgorithmOptions = Schema.Struct({allowedValues: HashAlgorithms, defaultValue: Schema.String})
const SignedObject = Schema.Struct({s3: Schema.optional(S3SignedObject)})
const SigningConfiguration = Schema.Struct({encryptionAlgorithmOptions: EncryptionAlgorithmOptions, hashAlgorithmOptions: HashAlgorithmOptions})
const ServiceLimitExceededException = Schema.Struct({message: Schema.optional(Schema.String), code: Schema.optional(Schema.String)})
export const AddProfilePermission = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-profiles/{profileName}/permissions", method: "POST", sdkId: "signer", sigV4ServiceName: "signer", name: "AddProfilePermission" }, AddProfilePermissionRequest, AddProfilePermissionResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceLimitExceededException", ServiceLimitExceededException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const DescribeSigningJobResponse = Schema.Struct({jobId: Schema.optional(Schema.String), source: Schema.optional(Source), signingMaterial: Schema.optional(SigningMaterial), platformId: Schema.optional(Schema.String), platformDisplayName: Schema.optional(Schema.String), profileName: Schema.optional(Schema.String), profileVersion: Schema.optional(Schema.String), overrides: Schema.optional(SigningPlatformOverrides), signingParameters: Schema.optional(SigningParameters), createdAt: Schema.optional(Schema.Date), completedAt: Schema.optional(Schema.Date), signatureExpiresAt: Schema.optional(Schema.Date), requestedBy: Schema.optional(Schema.String), status: Schema.optional(Schema.String), statusReason: Schema.optional(Schema.String), revocationRecord: Schema.optional(SigningJobRevocationRecord), signedObject: Schema.optional(SignedObject), jobOwner: Schema.optional(Schema.String), jobInvoker: Schema.optional(Schema.String)})
export const DescribeSigningJob = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-jobs/{jobId}", method: "GET", sdkId: "signer", sigV4ServiceName: "signer", name: "DescribeSigningJob" }, DescribeSigningJobRequest, DescribeSigningJobResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetSigningPlatformResponse = Schema.Struct({platformId: Schema.optional(Schema.String), displayName: Schema.optional(Schema.String), partner: Schema.optional(Schema.String), target: Schema.optional(Schema.String), category: Schema.optional(Schema.String), signingConfiguration: Schema.optional(SigningConfiguration), signingImageFormat: Schema.optional(SigningImageFormat), maxSizeInMB: Schema.optional(Schema.Number), revocationSupported: Schema.optional(Schema.Boolean)})
export const GetSigningPlatform = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-platforms/{platformId}", method: "GET", sdkId: "signer", sigV4ServiceName: "signer", name: "GetSigningPlatform" }, GetSigningPlatformRequest, GetSigningPlatformResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const PutSigningProfileResponse = Schema.Struct({arn: Schema.optional(Schema.String), profileVersion: Schema.optional(Schema.String), profileVersionArn: Schema.optional(Schema.String)})
export const PutSigningProfile = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-profiles/{profileName}", method: "PUT", sdkId: "signer", sigV4ServiceName: "signer", name: "PutSigningProfile" }, PutSigningProfileRequest, PutSigningProfileResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const StartSigningJobResponse = Schema.Struct({jobId: Schema.optional(Schema.String), jobOwner: Schema.optional(Schema.String)})
const ThrottlingException = Schema.Struct({message: Schema.optional(Schema.String), code: Schema.optional(Schema.String)})
export const StartSigningJob = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/signing-jobs", method: "POST", sdkId: "signer", sigV4ServiceName: "signer", name: "StartSigningJob" }, StartSigningJobRequest, StartSigningJobResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServiceErrorException", InternalServiceErrorException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("TooManyRequestsException", TooManyRequestsException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
