import * as S from "effect/Schema"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import * as H from "../schema-helpers.ts";

//# Schemas
export const FindingIdList = S.Array(S.String);
export const EngagementSet = S.Array(S.String);
export const TagKeyList = S.Array(S.String);
export class BatchGetIncidentFindingsInput extends S.Class<BatchGetIncidentFindingsInput>("BatchGetIncidentFindingsInput")({incidentRecordArn: S.String, findingIds: FindingIdList}) {}
export class DeleteIncidentRecordInput extends S.Class<DeleteIncidentRecordInput>("DeleteIncidentRecordInput")({arn: S.String}) {}
export class DeleteIncidentRecordOutput extends S.Class<DeleteIncidentRecordOutput>("DeleteIncidentRecordOutput")({}) {}
export class DeleteReplicationSetInput extends S.Class<DeleteReplicationSetInput>("DeleteReplicationSetInput")({arn: S.String}) {}
export class DeleteReplicationSetOutput extends S.Class<DeleteReplicationSetOutput>("DeleteReplicationSetOutput")({}) {}
export class DeleteResourcePolicyInput extends S.Class<DeleteResourcePolicyInput>("DeleteResourcePolicyInput")({resourceArn: S.String, policyId: S.String}) {}
export class DeleteResourcePolicyOutput extends S.Class<DeleteResourcePolicyOutput>("DeleteResourcePolicyOutput")({}) {}
export class DeleteResponsePlanInput extends S.Class<DeleteResponsePlanInput>("DeleteResponsePlanInput")({arn: S.String}) {}
export class DeleteResponsePlanOutput extends S.Class<DeleteResponsePlanOutput>("DeleteResponsePlanOutput")({}) {}
export class DeleteTimelineEventInput extends S.Class<DeleteTimelineEventInput>("DeleteTimelineEventInput")({incidentRecordArn: S.String, eventId: S.String}) {}
export class DeleteTimelineEventOutput extends S.Class<DeleteTimelineEventOutput>("DeleteTimelineEventOutput")({}) {}
export class GetIncidentRecordInput extends S.Class<GetIncidentRecordInput>("GetIncidentRecordInput")({arn: S.String}) {}
export class GetReplicationSetInput extends S.Class<GetReplicationSetInput>("GetReplicationSetInput")({arn: S.String}) {}
export class GetResourcePoliciesInput extends S.Class<GetResourcePoliciesInput>("GetResourcePoliciesInput")({resourceArn: S.String, maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export class GetResponsePlanInput extends S.Class<GetResponsePlanInput>("GetResponsePlanInput")({arn: S.String}) {}
export class GetTimelineEventInput extends S.Class<GetTimelineEventInput>("GetTimelineEventInput")({incidentRecordArn: S.String, eventId: S.String}) {}
export class ListIncidentFindingsInput extends S.Class<ListIncidentFindingsInput>("ListIncidentFindingsInput")({incidentRecordArn: S.String, maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export class ListRelatedItemsInput extends S.Class<ListRelatedItemsInput>("ListRelatedItemsInput")({incidentRecordArn: S.String, maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export class ListReplicationSetsInput extends S.Class<ListReplicationSetsInput>("ListReplicationSetsInput")({maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export class ListResponsePlansInput extends S.Class<ListResponsePlansInput>("ListResponsePlansInput")({maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export class ListTagsForResourceRequest extends S.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({resourceArn: S.String}) {}
export const StringList = S.Array(S.String);
export const IntegerList = S.Array(S.Number);
export const AttributeValueList = S.Union(StringList, IntegerList);
export const Condition = S.Union(S.Date, S.Date, AttributeValueList);
export class Filter extends S.Class<Filter>("Filter")({key: S.String, condition: Condition}) {}
export const FilterList = S.Array(Filter);
export class ListTimelineEventsInput extends S.Class<ListTimelineEventsInput>("ListTimelineEventsInput")({incidentRecordArn: S.String, filters: S.optional(FilterList), sortBy: S.optional(S.String), sortOrder: S.optional(S.String), maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export class PutResourcePolicyInput extends S.Class<PutResourcePolicyInput>("PutResourcePolicyInput")({resourceArn: S.String, policy: S.String}) {}
export const TagMap = S.Record({key: S.String, value: S.String});
export class TagResourceRequest extends S.Class<TagResourceRequest>("TagResourceRequest")({resourceArn: S.String, tags: TagMap}) {}
export class TagResourceResponse extends S.Class<TagResourceResponse>("TagResourceResponse")({}) {}
export class UntagResourceRequest extends S.Class<UntagResourceRequest>("UntagResourceRequest")({resourceArn: S.String, tagKeys: TagKeyList}) {}
export class UntagResourceResponse extends S.Class<UntagResourceResponse>("UntagResourceResponse")({}) {}
export class UpdateDeletionProtectionInput extends S.Class<UpdateDeletionProtectionInput>("UpdateDeletionProtectionInput")({arn: S.String, deletionProtected: S.Boolean, clientToken: S.optional(S.String)}) {}
export class UpdateDeletionProtectionOutput extends S.Class<UpdateDeletionProtectionOutput>("UpdateDeletionProtectionOutput")({}) {}
export const EventReference = S.Union(S.String, S.String);
export const EventReferenceList = S.Array(EventReference);
export class UpdateTimelineEventInput extends S.Class<UpdateTimelineEventInput>("UpdateTimelineEventInput")({clientToken: S.optional(S.String), incidentRecordArn: S.String, eventId: S.String, eventTime: S.optional(S.Date), eventType: S.optional(S.String), eventData: S.optional(S.String), eventReferences: S.optional(EventReferenceList)}) {}
export class UpdateTimelineEventOutput extends S.Class<UpdateTimelineEventOutput>("UpdateTimelineEventOutput")({}) {}
export class EmptyChatChannel extends S.Class<EmptyChatChannel>("EmptyChatChannel")({}) {}
export const ChatbotSnsConfigurationSet = S.Array(S.String);
export const NotificationTargetItem = S.Union(S.String);
export const NotificationTargetSet = S.Array(NotificationTargetItem);
export class IncidentTemplate extends S.Class<IncidentTemplate>("IncidentTemplate")({title: S.String, impact: S.Number, summary: S.optional(S.String), dedupeString: S.optional(S.String), notificationTargets: S.optional(NotificationTargetSet), incidentTags: S.optional(TagMap)}) {}
export const ChatChannel = S.Union(EmptyChatChannel, ChatbotSnsConfigurationSet);
export const ReplicationSetArnList = S.Array(S.String);
export class TriggerDetails extends S.Class<TriggerDetails>("TriggerDetails")({source: S.String, triggerArn: S.optional(S.String), timestamp: S.Date, rawData: S.optional(S.String)}) {}
export class PagerDutyIncidentDetail extends S.Class<PagerDutyIncidentDetail>("PagerDutyIncidentDetail")({id: S.String, autoResolve: S.optional(S.Boolean), secretId: S.optional(S.String)}) {}
export const ItemValue = S.Union(S.String, S.String, S.String, PagerDutyIncidentDetail);
export class ItemIdentifier extends S.Class<ItemIdentifier>("ItemIdentifier")({value: ItemValue, type: S.String}) {}
export class RelatedItem extends S.Class<RelatedItem>("RelatedItem")({identifier: ItemIdentifier, title: S.optional(S.String), generatedId: S.optional(S.String)}) {}
export const RelatedItemsUpdate = S.Union(RelatedItem, ItemIdentifier);
export const TagMapUpdate = S.Record({key: S.String, value: S.String});
export class CreateTimelineEventInput extends S.Class<CreateTimelineEventInput>("CreateTimelineEventInput")({clientToken: S.optional(S.String), incidentRecordArn: S.String, eventTime: S.Date, eventType: S.String, eventData: S.String, eventReferences: S.optional(EventReferenceList)}) {}
export class AccessDeniedException extends S.Class<AccessDeniedException>("AccessDeniedException")({message: S.String}) {}
export class InternalServerException extends S.Class<InternalServerException>("InternalServerException")({message: S.String}) {}
export class ResourceNotFoundException extends S.Class<ResourceNotFoundException>("ResourceNotFoundException")({message: S.String, resourceIdentifier: S.optional(S.String), resourceType: S.optional(S.String)}) {}
export class ThrottlingException extends S.Class<ThrottlingException>("ThrottlingException")({message: S.String, serviceCode: S.String, quotaCode: S.String}) {}
export class ValidationException extends S.Class<ValidationException>("ValidationException")({message: S.String}) {}
export const SsmParameterValues = S.Array(S.String);
export const SsmParameters = S.Record({key: S.String, value: SsmParameterValues});
export const DynamicSsmParameterValue = S.Union(S.String);
export const DynamicSsmParameters = S.Record({key: S.String, value: DynamicSsmParameterValue});
export class SsmAutomation extends S.Class<SsmAutomation>("SsmAutomation")({roleArn: S.String, documentName: S.String, documentVersion: S.optional(S.String), targetAccount: S.optional(S.String), parameters: S.optional(SsmParameters), dynamicParameters: S.optional(DynamicSsmParameters)}) {}
export const Action = S.Union(SsmAutomation);
export const ActionsList = S.Array(Action);
export class PagerDutyIncidentConfiguration extends S.Class<PagerDutyIncidentConfiguration>("PagerDutyIncidentConfiguration")({serviceId: S.String}) {}
export class PagerDutyConfiguration extends S.Class<PagerDutyConfiguration>("PagerDutyConfiguration")({name: S.String, secretId: S.String, pagerDutyIncidentConfiguration: PagerDutyIncidentConfiguration}) {}
export const Integration = S.Union(PagerDutyConfiguration);
export const Integrations = S.Array(Integration);
export class GetResponsePlanOutput extends S.Class<GetResponsePlanOutput>("GetResponsePlanOutput")({arn: S.String, name: S.String, displayName: S.optional(S.String), incidentTemplate: IncidentTemplate, chatChannel: S.optional(ChatChannel), engagements: S.optional(EngagementSet), actions: S.optional(ActionsList), integrations: S.optional(Integrations)}) {}
export const RelatedItemList = S.Array(RelatedItem);
export class ListRelatedItemsOutput extends S.Class<ListRelatedItemsOutput>("ListRelatedItemsOutput")({relatedItems: RelatedItemList, nextToken: S.optional(S.String)}) {}
export class ListReplicationSetsOutput extends S.Class<ListReplicationSetsOutput>("ListReplicationSetsOutput")({replicationSetArns: ReplicationSetArnList, nextToken: S.optional(S.String)}) {}
export class ListTagsForResourceResponse extends S.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({tags: TagMap}) {}
export class PutResourcePolicyOutput extends S.Class<PutResourcePolicyOutput>("PutResourcePolicyOutput")({policyId: S.String}) {}
export class ConflictException extends S.Class<ConflictException>("ConflictException")({message: S.String, resourceIdentifier: S.optional(S.String), resourceType: S.optional(S.String), retryAfter: S.optional(S.Date)}) {}
export class UpdateIncidentRecordInput extends S.Class<UpdateIncidentRecordInput>("UpdateIncidentRecordInput")({clientToken: S.optional(S.String), arn: S.String, title: S.optional(S.String), summary: S.optional(S.String), impact: S.optional(S.Number), status: S.optional(S.String), chatChannel: S.optional(ChatChannel), notificationTargets: S.optional(NotificationTargetSet)}) {}
export class UpdateIncidentRecordOutput extends S.Class<UpdateIncidentRecordOutput>("UpdateIncidentRecordOutput")({}) {}
export class UpdateRelatedItemsInput extends S.Class<UpdateRelatedItemsInput>("UpdateRelatedItemsInput")({clientToken: S.optional(S.String), incidentRecordArn: S.String, relatedItemsUpdate: RelatedItemsUpdate}) {}
export class UpdateRelatedItemsOutput extends S.Class<UpdateRelatedItemsOutput>("UpdateRelatedItemsOutput")({}) {}
export class UpdateResponsePlanInput extends S.Class<UpdateResponsePlanInput>("UpdateResponsePlanInput")({clientToken: S.optional(S.String), arn: S.String, displayName: S.optional(S.String), incidentTemplateTitle: S.optional(S.String), incidentTemplateImpact: S.optional(S.Number), incidentTemplateSummary: S.optional(S.String), incidentTemplateDedupeString: S.optional(S.String), incidentTemplateNotificationTargets: S.optional(NotificationTargetSet), chatChannel: S.optional(ChatChannel), engagements: S.optional(EngagementSet), actions: S.optional(ActionsList), incidentTemplateTags: S.optional(TagMapUpdate), integrations: S.optional(Integrations)}) {}
export class UpdateResponsePlanOutput extends S.Class<UpdateResponsePlanOutput>("UpdateResponsePlanOutput")({}) {}
export class RegionMapInputValue extends S.Class<RegionMapInputValue>("RegionMapInputValue")({sseKmsKeyId: S.optional(S.String)}) {}
export class AddRegionAction extends S.Class<AddRegionAction>("AddRegionAction")({regionName: S.String, sseKmsKeyId: S.optional(S.String)}) {}
export class DeleteRegionAction extends S.Class<DeleteRegionAction>("DeleteRegionAction")({regionName: S.String}) {}
export class BatchGetIncidentFindingsError extends S.Class<BatchGetIncidentFindingsError>("BatchGetIncidentFindingsError")({findingId: S.String, code: S.String, message: S.String}) {}
export const BatchGetIncidentFindingsErrorList = S.Array(BatchGetIncidentFindingsError);
export const RegionMapInput = S.Record({key: S.String, value: RegionMapInputValue});
export class ResourcePolicy extends S.Class<ResourcePolicy>("ResourcePolicy")({policyDocument: S.String, policyId: S.String, ramResourceShareRegion: S.String}) {}
export const ResourcePolicyList = S.Array(ResourcePolicy);
export class TimelineEvent extends S.Class<TimelineEvent>("TimelineEvent")({incidentRecordArn: S.String, eventId: S.String, eventTime: S.Date, eventUpdatedTime: S.Date, eventType: S.String, eventData: S.String, eventReferences: S.optional(EventReferenceList)}) {}
export class FindingSummary extends S.Class<FindingSummary>("FindingSummary")({id: S.String, lastModifiedTime: S.Date}) {}
export const FindingSummaryList = S.Array(FindingSummary);
export class ResponsePlanSummary extends S.Class<ResponsePlanSummary>("ResponsePlanSummary")({arn: S.String, name: S.String, displayName: S.optional(S.String)}) {}
export const ResponsePlanSummaryList = S.Array(ResponsePlanSummary);
export class EventSummary extends S.Class<EventSummary>("EventSummary")({incidentRecordArn: S.String, eventId: S.String, eventTime: S.Date, eventUpdatedTime: S.Date, eventType: S.String, eventReferences: S.optional(EventReferenceList)}) {}
export const EventSummaryList = S.Array(EventSummary);
export const UpdateReplicationSetAction = S.Union(AddRegionAction, DeleteRegionAction);
export const UpdateActionList = S.Array(UpdateReplicationSetAction);
export class CreateReplicationSetInput extends S.Class<CreateReplicationSetInput>("CreateReplicationSetInput")({regions: RegionMapInput, clientToken: S.optional(S.String), tags: S.optional(TagMap)}) {}
export class CreateTimelineEventOutput extends S.Class<CreateTimelineEventOutput>("CreateTimelineEventOutput")({incidentRecordArn: S.String, eventId: S.String}) {}
export class GetResourcePoliciesOutput extends S.Class<GetResourcePoliciesOutput>("GetResourcePoliciesOutput")({resourcePolicies: ResourcePolicyList, nextToken: S.optional(S.String)}) {}
export class GetTimelineEventOutput extends S.Class<GetTimelineEventOutput>("GetTimelineEventOutput")({event: TimelineEvent}) {}
export class ListIncidentFindingsOutput extends S.Class<ListIncidentFindingsOutput>("ListIncidentFindingsOutput")({findings: FindingSummaryList, nextToken: S.optional(S.String)}) {}
export class ListResponsePlansOutput extends S.Class<ListResponsePlansOutput>("ListResponsePlansOutput")({responsePlanSummaries: ResponsePlanSummaryList, nextToken: S.optional(S.String)}) {}
export class ListTimelineEventsOutput extends S.Class<ListTimelineEventsOutput>("ListTimelineEventsOutput")({eventSummaries: EventSummaryList, nextToken: S.optional(S.String)}) {}
export class ServiceQuotaExceededException extends S.Class<ServiceQuotaExceededException>("ServiceQuotaExceededException")({message: S.String, resourceIdentifier: S.optional(S.String), resourceType: S.optional(S.String), serviceCode: S.String, quotaCode: S.String}) {}
export class UpdateReplicationSetInput extends S.Class<UpdateReplicationSetInput>("UpdateReplicationSetInput")({arn: S.String, actions: UpdateActionList, clientToken: S.optional(S.String)}) {}
export class UpdateReplicationSetOutput extends S.Class<UpdateReplicationSetOutput>("UpdateReplicationSetOutput")({}) {}
export const AutomationExecution = S.Union(S.String);
export const AutomationExecutionSet = S.Array(AutomationExecution);
export class IncidentRecordSource extends S.Class<IncidentRecordSource>("IncidentRecordSource")({createdBy: S.String, invokedBy: S.optional(S.String), resourceArn: S.optional(S.String), source: S.String}) {}
export class IncidentRecord extends S.Class<IncidentRecord>("IncidentRecord")({arn: S.String, title: S.String, summary: S.optional(S.String), status: S.String, impact: S.Number, creationTime: S.Date, resolvedTime: S.optional(S.Date), lastModifiedTime: S.Date, lastModifiedBy: S.String, automationExecutions: S.optional(AutomationExecutionSet), incidentRecordSource: IncidentRecordSource, dedupeString: S.String, chatChannel: S.optional(ChatChannel), notificationTargets: S.optional(NotificationTargetSet)}) {}
export class CodeDeployDeployment extends S.Class<CodeDeployDeployment>("CodeDeployDeployment")({startTime: S.Date, endTime: S.optional(S.Date), deploymentGroupArn: S.String, deploymentId: S.String}) {}
export class CloudFormationStackUpdate extends S.Class<CloudFormationStackUpdate>("CloudFormationStackUpdate")({startTime: S.Date, endTime: S.optional(S.Date), stackArn: S.String}) {}
export class RegionInfo extends S.Class<RegionInfo>("RegionInfo")({sseKmsKeyId: S.optional(S.String), status: S.String, statusMessage: S.optional(S.String), statusUpdateDateTime: S.Date}) {}
export class CreateReplicationSetOutput extends S.Class<CreateReplicationSetOutput>("CreateReplicationSetOutput")({arn: S.String}) {}
export class GetIncidentRecordOutput extends S.Class<GetIncidentRecordOutput>("GetIncidentRecordOutput")({incidentRecord: IncidentRecord}) {}
export class ListIncidentRecordsInput extends S.Class<ListIncidentRecordsInput>("ListIncidentRecordsInput")({filters: S.optional(FilterList), maxResults: S.optional(S.Number), nextToken: S.optional(S.String)}) {}
export const FindingDetails = S.Union(CodeDeployDeployment, CloudFormationStackUpdate);
export const RegionInfoMap = S.Record({key: S.String, value: RegionInfo});
export class Finding extends S.Class<Finding>("Finding")({id: S.String, creationTime: S.Date, lastModifiedTime: S.Date, details: S.optional(FindingDetails)}) {}
export const FindingList = S.Array(Finding);
export class ReplicationSet extends S.Class<ReplicationSet>("ReplicationSet")({arn: S.optional(S.String), regionMap: RegionInfoMap, status: S.String, deletionProtected: S.Boolean, createdTime: S.Date, createdBy: S.String, lastModifiedTime: S.Date, lastModifiedBy: S.String}) {}
export class BatchGetIncidentFindingsOutput extends S.Class<BatchGetIncidentFindingsOutput>("BatchGetIncidentFindingsOutput")({findings: FindingList, errors: BatchGetIncidentFindingsErrorList}) {}
export class CreateResponsePlanInput extends S.Class<CreateResponsePlanInput>("CreateResponsePlanInput")({clientToken: S.optional(S.String), name: S.String, displayName: S.optional(S.String), incidentTemplate: IncidentTemplate, chatChannel: S.optional(ChatChannel), engagements: S.optional(EngagementSet), actions: S.optional(ActionsList), tags: S.optional(TagMap), integrations: S.optional(Integrations)}) {}
export class GetReplicationSetOutput extends S.Class<GetReplicationSetOutput>("GetReplicationSetOutput")({replicationSet: ReplicationSet}) {}
export class StartIncidentInput extends S.Class<StartIncidentInput>("StartIncidentInput")({clientToken: S.optional(S.String), responsePlanArn: S.String, title: S.optional(S.String), impact: S.optional(S.Number), triggerDetails: S.optional(TriggerDetails), relatedItems: S.optional(RelatedItemList)}) {}
export class IncidentRecordSummary extends S.Class<IncidentRecordSummary>("IncidentRecordSummary")({arn: S.String, title: S.String, status: S.String, impact: S.Number, creationTime: S.Date, resolvedTime: S.optional(S.Date), incidentRecordSource: IncidentRecordSource}) {}
export const IncidentRecordSummaryList = S.Array(IncidentRecordSummary);
export class CreateResponsePlanOutput extends S.Class<CreateResponsePlanOutput>("CreateResponsePlanOutput")({arn: S.String}) {}
export class ListIncidentRecordsOutput extends S.Class<ListIncidentRecordsOutput>("ListIncidentRecordsOutput")({incidentRecordSummaries: IncidentRecordSummaryList, nextToken: S.optional(S.String)}) {}
export class StartIncidentOutput extends S.Class<StartIncidentOutput>("StartIncidentOutput")({incidentRecordArn: S.String}) {}

//# Errors
export class AccessDeniedExceptionError extends S.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class InternalServerExceptionError extends S.TaggedError<InternalServerExceptionError>()("InternalServerException", InternalServerException.fields) {};
export class ThrottlingExceptionError extends S.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class ConflictExceptionError extends S.TaggedError<ConflictExceptionError>()("ConflictException", ConflictException.fields) {};
export class ResourceNotFoundExceptionError extends S.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ValidationExceptionError extends S.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};
export class ServiceQuotaExceededExceptionError extends S.TaggedError<ServiceQuotaExceededExceptionError>()("ServiceQuotaExceededException", ServiceQuotaExceededException.fields) {};

//# Operations
export const untagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.UntagResource" }, UntagResourceRequest, UntagResourceResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateDeletionProtection = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/updateDeletionProtection", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.UpdateDeletionProtection" }, UpdateDeletionProtectionInput, UpdateDeletionProtectionOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateTimelineEvent = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/updateTimelineEvent", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.UpdateTimelineEvent" }, UpdateTimelineEventInput, UpdateTimelineEventOutput, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteIncidentRecord = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/deleteIncidentRecord", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.DeleteIncidentRecord" }, DeleteIncidentRecordInput, DeleteIncidentRecordOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteReplicationSet = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/deleteReplicationSet", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.DeleteReplicationSet" }, DeleteReplicationSetInput, DeleteReplicationSetOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteResourcePolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/deleteResourcePolicy", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.DeleteResourcePolicy" }, DeleteResourcePolicyInput, DeleteResourcePolicyOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteResponsePlan = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/deleteResponsePlan", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.DeleteResponsePlan" }, DeleteResponsePlanInput, DeleteResponsePlanOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteTimelineEvent = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/deleteTimelineEvent", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.DeleteTimelineEvent" }, DeleteTimelineEventInput, DeleteTimelineEventOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getResponsePlan = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/getResponsePlan", method: "GET", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.GetResponsePlan" }, GetResponsePlanInput, GetResponsePlanOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listRelatedItems = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/listRelatedItems", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.ListRelatedItems" }, ListRelatedItemsInput, ListRelatedItemsOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listReplicationSets = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/listReplicationSets", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.ListReplicationSets" }, ListReplicationSetsInput, ListReplicationSetsOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/tags/{resourceArn}", method: "GET", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putResourcePolicy = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/putResourcePolicy", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.PutResourcePolicy" }, PutResourcePolicyInput, PutResourcePolicyOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateIncidentRecord = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/updateIncidentRecord", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.UpdateIncidentRecord" }, UpdateIncidentRecordInput, UpdateIncidentRecordOutput, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateRelatedItems = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/updateRelatedItems", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.UpdateRelatedItems" }, UpdateRelatedItemsInput, UpdateRelatedItemsOutput, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateResponsePlan = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/updateResponsePlan", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.UpdateResponsePlan" }, UpdateResponsePlanInput, UpdateResponsePlanOutput, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createTimelineEvent = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/createTimelineEvent", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.CreateTimelineEvent" }, CreateTimelineEventInput, CreateTimelineEventOutput, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getResourcePolicies = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/getResourcePolicies", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.GetResourcePolicies" }, GetResourcePoliciesInput, GetResourcePoliciesOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getTimelineEvent = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/getTimelineEvent", method: "GET", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.GetTimelineEvent" }, GetTimelineEventInput, GetTimelineEventOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listIncidentFindings = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/listIncidentFindings", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.ListIncidentFindings" }, ListIncidentFindingsInput, ListIncidentFindingsOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listResponsePlans = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/listResponsePlans", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.ListResponsePlans" }, ListResponsePlansInput, ListResponsePlansOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTimelineEvents = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/listTimelineEvents", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.ListTimelineEvents" }, ListTimelineEventsInput, ListTimelineEventsOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/tags/{resourceArn}", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.TagResource" }, TagResourceRequest, TagResourceResponse, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateReplicationSet = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/updateReplicationSet", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.UpdateReplicationSet" }, UpdateReplicationSetInput, UpdateReplicationSetOutput, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createReplicationSet = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/createReplicationSet", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.CreateReplicationSet" }, CreateReplicationSetInput, CreateReplicationSetOutput, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getIncidentRecord = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/getIncidentRecord", method: "GET", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.GetIncidentRecord" }, GetIncidentRecordInput, GetIncidentRecordOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const batchGetIncidentFindings = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/batchGetIncidentFindings", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.BatchGetIncidentFindings" }, BatchGetIncidentFindingsInput, BatchGetIncidentFindingsOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getReplicationSet = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/getReplicationSet", method: "GET", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.GetReplicationSet" }, GetReplicationSetInput, GetReplicationSetOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createResponsePlan = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/createResponsePlan", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.CreateResponsePlan" }, CreateResponsePlanInput, CreateResponsePlanOutput, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listIncidentRecords = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/listIncidentRecords", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.ListIncidentRecords" }, ListIncidentRecordsInput, ListIncidentRecordsOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const startIncident = /*#__PURE__*/ makeOperation(() => H.Operation({ version: "2018-05-10", uri: "/startIncident", method: "POST", sdkId: "SSM Incidents", sigV4ServiceName: "ssm-incidents", name: "SSMIncidents.StartIncident" }, StartIncidentInput, StartIncidentOutput, [AccessDeniedExceptionError, ConflictExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
