import { Schema} from "effect"
import { FormatJSONRequest,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import { Operation, Path, Header, StreamBody, Body } from "../schema-helpers.ts";

//# Schemas
export const TagKeys = Schema.Array(Schema.String);
export class CancelSolNetworkOperationInput extends Schema.Class<CancelSolNetworkOperationInput>("CancelSolNetworkOperationInput")({nsLcmOpOccId: Schema.String}) {}
export const TagMap = Schema.Record({key: Schema.String, value: Schema.String});
export class CreateSolNetworkInstanceInput extends Schema.Class<CreateSolNetworkInstanceInput>("CreateSolNetworkInstanceInput")({nsdInfoId: Schema.String, nsName: Schema.String, nsDescription: Schema.optional(Schema.String), tags: Schema.optional(TagMap)}) {}
export class CreateSolNetworkPackageInput extends Schema.Class<CreateSolNetworkPackageInput>("CreateSolNetworkPackageInput")({tags: Schema.optional(TagMap)}) {}
export class DeleteSolFunctionPackageInput extends Schema.Class<DeleteSolFunctionPackageInput>("DeleteSolFunctionPackageInput")({vnfPkgId: Schema.String}) {}
export class DeleteSolNetworkInstanceInput extends Schema.Class<DeleteSolNetworkInstanceInput>("DeleteSolNetworkInstanceInput")({nsInstanceId: Schema.String}) {}
export class DeleteSolNetworkPackageInput extends Schema.Class<DeleteSolNetworkPackageInput>("DeleteSolNetworkPackageInput")({nsdInfoId: Schema.String}) {}
export class GetSolFunctionInstanceInput extends Schema.Class<GetSolFunctionInstanceInput>("GetSolFunctionInstanceInput")({vnfInstanceId: Schema.String}) {}
export class GetSolFunctionPackageInput extends Schema.Class<GetSolFunctionPackageInput>("GetSolFunctionPackageInput")({vnfPkgId: Schema.String}) {}
export class GetSolFunctionPackageContentInput extends Schema.Class<GetSolFunctionPackageContentInput>("GetSolFunctionPackageContentInput")({vnfPkgId: Schema.String, accept: Header("Accept")}) {}
export class GetSolFunctionPackageDescriptorInput extends Schema.Class<GetSolFunctionPackageDescriptorInput>("GetSolFunctionPackageDescriptorInput")({vnfPkgId: Schema.String, accept: Header("Accept")}) {}
export class GetSolNetworkInstanceInput extends Schema.Class<GetSolNetworkInstanceInput>("GetSolNetworkInstanceInput")({nsInstanceId: Schema.String}) {}
export class GetSolNetworkOperationInput extends Schema.Class<GetSolNetworkOperationInput>("GetSolNetworkOperationInput")({nsLcmOpOccId: Schema.String}) {}
export class GetSolNetworkPackageInput extends Schema.Class<GetSolNetworkPackageInput>("GetSolNetworkPackageInput")({nsdInfoId: Schema.String}) {}
export class GetSolNetworkPackageContentInput extends Schema.Class<GetSolNetworkPackageContentInput>("GetSolNetworkPackageContentInput")({nsdInfoId: Schema.String, accept: Header("Accept")}) {}
export class GetSolNetworkPackageDescriptorInput extends Schema.Class<GetSolNetworkPackageDescriptorInput>("GetSolNetworkPackageDescriptorInput")({nsdInfoId: Schema.String}) {}
export class InstantiateSolNetworkInstanceInput extends Schema.Class<InstantiateSolNetworkInstanceInput>("InstantiateSolNetworkInstanceInput")({nsInstanceId: Schema.String, dryRun: Schema.optional(Schema.Boolean), additionalParamsForNs: Schema.optional(Schema.JsonValue), tags: Schema.optional(TagMap)}) {}
export class ListSolFunctionInstancesInput extends Schema.Class<ListSolFunctionInstancesInput>("ListSolFunctionInstancesInput")({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListSolFunctionPackagesInput extends Schema.Class<ListSolFunctionPackagesInput>("ListSolFunctionPackagesInput")({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListSolNetworkInstancesInput extends Schema.Class<ListSolNetworkInstancesInput>("ListSolNetworkInstancesInput")({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListSolNetworkOperationsInput extends Schema.Class<ListSolNetworkOperationsInput>("ListSolNetworkOperationsInput")({nsInstanceId: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListSolNetworkPackagesInput extends Schema.Class<ListSolNetworkPackagesInput>("ListSolNetworkPackagesInput")({maxResults: Schema.optional(Schema.Number), nextToken: Schema.optional(Schema.String)}) {}
export class ListTagsForResourceInput extends Schema.Class<ListTagsForResourceInput>("ListTagsForResourceInput")({resourceArn: Schema.String}) {}
export class PutSolFunctionPackageContentInput extends Schema.Class<PutSolFunctionPackageContentInput>("PutSolFunctionPackageContentInput")({vnfPkgId: Schema.String, contentType: Schema.optional(Header("Content-Type")), file: Body("undefined", StreamBody())}) {}
export class PutSolNetworkPackageContentInput extends Schema.Class<PutSolNetworkPackageContentInput>("PutSolNetworkPackageContentInput")({nsdInfoId: Schema.String, contentType: Schema.optional(Header("Content-Type")), file: Body("undefined", StreamBody())}) {}
export class TagResourceInput extends Schema.Class<TagResourceInput>("TagResourceInput")({resourceArn: Schema.String, tags: TagMap}) {}
export class TagResourceOutput extends Schema.Class<TagResourceOutput>("TagResourceOutput")({}) {}
export class TerminateSolNetworkInstanceInput extends Schema.Class<TerminateSolNetworkInstanceInput>("TerminateSolNetworkInstanceInput")({nsInstanceId: Schema.String, tags: Schema.optional(TagMap)}) {}
export class UntagResourceInput extends Schema.Class<UntagResourceInput>("UntagResourceInput")({resourceArn: Schema.String, tagKeys: TagKeys}) {}
export class UntagResourceOutput extends Schema.Class<UntagResourceOutput>("UntagResourceOutput")({}) {}
export class UpdateSolFunctionPackageInput extends Schema.Class<UpdateSolFunctionPackageInput>("UpdateSolFunctionPackageInput")({vnfPkgId: Schema.String, operationalState: Schema.String}) {}
export class UpdateSolNetworkPackageInput extends Schema.Class<UpdateSolNetworkPackageInput>("UpdateSolNetworkPackageInput")({nsdInfoId: Schema.String, nsdOperationalState: Schema.String}) {}
export class ValidateSolFunctionPackageContentInput extends Schema.Class<ValidateSolFunctionPackageContentInput>("ValidateSolFunctionPackageContentInput")({vnfPkgId: Schema.String, contentType: Schema.optional(Header("Content-Type")), file: Body("undefined", StreamBody())}) {}
export class ValidateSolNetworkPackageContentInput extends Schema.Class<ValidateSolNetworkPackageContentInput>("ValidateSolNetworkPackageContentInput")({nsdInfoId: Schema.String, contentType: Schema.optional(Header("Content-Type")), file: Body("undefined", StreamBody())}) {}
export const VnfPkgIdList = Schema.Array(Schema.String);
export class UpdateSolNetworkModify extends Schema.Class<UpdateSolNetworkModify>("UpdateSolNetworkModify")({vnfInstanceId: Schema.String, vnfConfigurableProperties: Schema.JsonValue}) {}
export class UpdateSolNetworkServiceData extends Schema.Class<UpdateSolNetworkServiceData>("UpdateSolNetworkServiceData")({nsdInfoId: Schema.String, additionalParamsForNs: Schema.optional(Schema.JsonValue)}) {}
export class AccessDeniedException extends Schema.Class<AccessDeniedException>("AccessDeniedException")({message: Schema.String}) {}
export class CreateSolFunctionPackageInput extends Schema.Class<CreateSolFunctionPackageInput>("CreateSolFunctionPackageInput")({tags: Schema.optional(TagMap)}) {}
export class CreateSolNetworkInstanceOutput extends Schema.Class<CreateSolNetworkInstanceOutput>("CreateSolNetworkInstanceOutput")({id: Schema.String, arn: Schema.String, nsdInfoId: Schema.String, nsInstanceName: Schema.String, tags: Schema.optional(TagMap)}) {}
export class CreateSolNetworkPackageOutput extends Schema.Class<CreateSolNetworkPackageOutput>("CreateSolNetworkPackageOutput")({id: Schema.String, arn: Schema.String, nsdOnboardingState: Schema.String, nsdOperationalState: Schema.String, nsdUsageState: Schema.String, tags: Schema.optional(TagMap)}) {}
export class InternalServerException extends Schema.Class<InternalServerException>("InternalServerException")({message: Schema.String}) {}
export class ResourceNotFoundException extends Schema.Class<ResourceNotFoundException>("ResourceNotFoundException")({message: Schema.String}) {}
export class ThrottlingException extends Schema.Class<ThrottlingException>("ThrottlingException")({message: Schema.String}) {}
export class GetSolFunctionPackageContentOutput extends Schema.Class<GetSolFunctionPackageContentOutput>("GetSolFunctionPackageContentOutput")({contentType: Schema.optional(Header("Content-Type")), packageContent: Schema.optional(Body("undefined", StreamBody()))}) {}
export class GetSolFunctionPackageDescriptorOutput extends Schema.Class<GetSolFunctionPackageDescriptorOutput>("GetSolFunctionPackageDescriptorOutput")({contentType: Schema.optional(Header("Content-Type")), vnfd: Schema.optional(Body("undefined", StreamBody()))}) {}
export class GetSolNetworkPackageContentOutput extends Schema.Class<GetSolNetworkPackageContentOutput>("GetSolNetworkPackageContentOutput")({contentType: Schema.optional(Header("Content-Type")), nsdContent: Schema.optional(Body("undefined", StreamBody()))}) {}
export class GetSolNetworkPackageDescriptorOutput extends Schema.Class<GetSolNetworkPackageDescriptorOutput>("GetSolNetworkPackageDescriptorOutput")({contentType: Schema.optional(Header("Content-Type")), nsd: Schema.optional(Body("undefined", StreamBody()))}) {}
export class InstantiateSolNetworkInstanceOutput extends Schema.Class<InstantiateSolNetworkInstanceOutput>("InstantiateSolNetworkInstanceOutput")({nsLcmOpOccId: Schema.String, tags: Schema.optional(TagMap)}) {}
export class ListTagsForResourceOutput extends Schema.Class<ListTagsForResourceOutput>("ListTagsForResourceOutput")({tags: TagMap}) {}
export class ValidationException extends Schema.Class<ValidationException>("ValidationException")({message: Schema.String}) {}
export class TerminateSolNetworkInstanceOutput extends Schema.Class<TerminateSolNetworkInstanceOutput>("TerminateSolNetworkInstanceOutput")({nsLcmOpOccId: Schema.optional(Schema.String), tags: Schema.optional(TagMap)}) {}
export class UpdateSolFunctionPackageOutput extends Schema.Class<UpdateSolFunctionPackageOutput>("UpdateSolFunctionPackageOutput")({operationalState: Schema.String}) {}
export class UpdateSolNetworkInstanceInput extends Schema.Class<UpdateSolNetworkInstanceInput>("UpdateSolNetworkInstanceInput")({nsInstanceId: Schema.String, updateType: Schema.String, modifyVnfInfoData: Schema.optional(UpdateSolNetworkModify), updateNs: Schema.optional(UpdateSolNetworkServiceData), tags: Schema.optional(TagMap)}) {}
export class UpdateSolNetworkPackageOutput extends Schema.Class<UpdateSolNetworkPackageOutput>("UpdateSolNetworkPackageOutput")({nsdOperationalState: Schema.String}) {}
export class GetSolFunctionInstanceMetadata extends Schema.Class<GetSolFunctionInstanceMetadata>("GetSolFunctionInstanceMetadata")({createdAt: Schema.Date, lastModified: Schema.Date}) {}
export class LcmOperationInfo extends Schema.Class<LcmOperationInfo>("LcmOperationInfo")({nsLcmOpOccId: Schema.String}) {}
export class GetSolNetworkInstanceMetadata extends Schema.Class<GetSolNetworkInstanceMetadata>("GetSolNetworkInstanceMetadata")({createdAt: Schema.Date, lastModified: Schema.Date}) {}
export class ProblemDetails extends Schema.Class<ProblemDetails>("ProblemDetails")({detail: Schema.String, title: Schema.optional(Schema.String)}) {}
export class ToscaOverride extends Schema.Class<ToscaOverride>("ToscaOverride")({name: Schema.optional(Schema.String), defaultValue: Schema.optional(Schema.String)}) {}
export const OverrideList = Schema.Array(ToscaOverride);
export class FunctionArtifactMeta extends Schema.Class<FunctionArtifactMeta>("FunctionArtifactMeta")({overrides: Schema.optional(OverrideList)}) {}
export class PutSolFunctionPackageContentMetadata extends Schema.Class<PutSolFunctionPackageContentMetadata>("PutSolFunctionPackageContentMetadata")({vnfd: Schema.optional(FunctionArtifactMeta)}) {}
export class NetworkArtifactMeta extends Schema.Class<NetworkArtifactMeta>("NetworkArtifactMeta")({overrides: Schema.optional(OverrideList)}) {}
export class PutSolNetworkPackageContentMetadata extends Schema.Class<PutSolNetworkPackageContentMetadata>("PutSolNetworkPackageContentMetadata")({nsd: Schema.optional(NetworkArtifactMeta)}) {}
export class ValidateSolFunctionPackageContentMetadata extends Schema.Class<ValidateSolFunctionPackageContentMetadata>("ValidateSolFunctionPackageContentMetadata")({vnfd: Schema.optional(FunctionArtifactMeta)}) {}
export class ValidateSolNetworkPackageContentMetadata extends Schema.Class<ValidateSolNetworkPackageContentMetadata>("ValidateSolNetworkPackageContentMetadata")({nsd: Schema.optional(NetworkArtifactMeta)}) {}
export class CreateSolFunctionPackageOutput extends Schema.Class<CreateSolFunctionPackageOutput>("CreateSolFunctionPackageOutput")({id: Schema.String, arn: Schema.String, onboardingState: Schema.String, operationalState: Schema.String, usageState: Schema.String, tags: Schema.optional(TagMap)}) {}
export class ServiceQuotaExceededException extends Schema.Class<ServiceQuotaExceededException>("ServiceQuotaExceededException")({message: Schema.String}) {}
export class GetSolNetworkInstanceOutput extends Schema.Class<GetSolNetworkInstanceOutput>("GetSolNetworkInstanceOutput")({id: Schema.String, arn: Schema.String, nsInstanceName: Schema.String, nsInstanceDescription: Schema.String, nsdId: Schema.String, nsdInfoId: Schema.String, nsState: Schema.optional(Schema.String), lcmOpInfo: Schema.optional(LcmOperationInfo), metadata: GetSolNetworkInstanceMetadata, tags: Schema.optional(TagMap)}) {}
export class PutSolFunctionPackageContentOutput extends Schema.Class<PutSolFunctionPackageContentOutput>("PutSolFunctionPackageContentOutput")({id: Schema.String, vnfdId: Schema.String, vnfProductName: Schema.String, vnfProvider: Schema.String, vnfdVersion: Schema.String, metadata: PutSolFunctionPackageContentMetadata}) {}
export class PutSolNetworkPackageContentOutput extends Schema.Class<PutSolNetworkPackageContentOutput>("PutSolNetworkPackageContentOutput")({id: Schema.String, arn: Schema.String, nsdId: Schema.String, nsdName: Schema.String, nsdVersion: Schema.String, vnfPkgIds: VnfPkgIdList, metadata: PutSolNetworkPackageContentMetadata}) {}
export class UpdateSolNetworkInstanceOutput extends Schema.Class<UpdateSolNetworkInstanceOutput>("UpdateSolNetworkInstanceOutput")({nsLcmOpOccId: Schema.optional(Schema.String), tags: Schema.optional(TagMap)}) {}
export class ValidateSolFunctionPackageContentOutput extends Schema.Class<ValidateSolFunctionPackageContentOutput>("ValidateSolFunctionPackageContentOutput")({id: Schema.String, vnfdId: Schema.String, vnfProductName: Schema.String, vnfProvider: Schema.String, vnfdVersion: Schema.String, metadata: ValidateSolFunctionPackageContentMetadata}) {}
export class ValidateSolNetworkPackageContentOutput extends Schema.Class<ValidateSolNetworkPackageContentOutput>("ValidateSolNetworkPackageContentOutput")({id: Schema.String, arn: Schema.String, nsdId: Schema.String, nsdName: Schema.String, nsdVersion: Schema.String, vnfPkgIds: VnfPkgIdList, metadata: ValidateSolNetworkPackageContentMetadata}) {}
export class UpdateNsMetadata extends Schema.Class<UpdateNsMetadata>("UpdateNsMetadata")({nsdInfoId: Schema.String, additionalParamsForNs: Schema.optional(Schema.JsonValue)}) {}
export class ModifyVnfInfoMetadata extends Schema.Class<ModifyVnfInfoMetadata>("ModifyVnfInfoMetadata")({vnfInstanceId: Schema.String, vnfConfigurableProperties: Schema.JsonValue}) {}
export class InstantiateMetadata extends Schema.Class<InstantiateMetadata>("InstantiateMetadata")({nsdInfoId: Schema.String, additionalParamsForNs: Schema.optional(Schema.JsonValue)}) {}
export const StringMap = Schema.Record({key: Schema.String, value: Schema.String});
export class ErrorInfo extends Schema.Class<ErrorInfo>("ErrorInfo")({cause: Schema.optional(Schema.String), details: Schema.optional(Schema.String)}) {}
export class GetSolInstantiatedVnfInfo extends Schema.Class<GetSolInstantiatedVnfInfo>("GetSolInstantiatedVnfInfo")({vnfState: Schema.optional(Schema.String)}) {}
export class ListSolFunctionInstanceMetadata extends Schema.Class<ListSolFunctionInstanceMetadata>("ListSolFunctionInstanceMetadata")({createdAt: Schema.Date, lastModified: Schema.Date}) {}
export class ListSolFunctionPackageMetadata extends Schema.Class<ListSolFunctionPackageMetadata>("ListSolFunctionPackageMetadata")({createdAt: Schema.Date, lastModified: Schema.Date}) {}
export class ListSolNetworkInstanceMetadata extends Schema.Class<ListSolNetworkInstanceMetadata>("ListSolNetworkInstanceMetadata")({createdAt: Schema.Date, lastModified: Schema.Date}) {}
export class ListSolNetworkOperationsMetadata extends Schema.Class<ListSolNetworkOperationsMetadata>("ListSolNetworkOperationsMetadata")({nsdInfoId: Schema.optional(Schema.String), vnfInstanceId: Schema.optional(Schema.String), createdAt: Schema.Date, lastModified: Schema.Date}) {}
export class ListSolNetworkPackageMetadata extends Schema.Class<ListSolNetworkPackageMetadata>("ListSolNetworkPackageMetadata")({createdAt: Schema.Date, lastModified: Schema.Date}) {}
export class GetSolNetworkOperationMetadata extends Schema.Class<GetSolNetworkOperationMetadata>("GetSolNetworkOperationMetadata")({updateNsMetadata: Schema.optional(UpdateNsMetadata), modifyVnfInfoMetadata: Schema.optional(ModifyVnfInfoMetadata), instantiateMetadata: Schema.optional(InstantiateMetadata), createdAt: Schema.Date, lastModified: Schema.Date}) {}
export class GetSolNetworkOperationTaskDetails extends Schema.Class<GetSolNetworkOperationTaskDetails>("GetSolNetworkOperationTaskDetails")({taskName: Schema.optional(Schema.String), taskContext: Schema.optional(StringMap), taskErrorDetails: Schema.optional(ErrorInfo), taskStatus: Schema.optional(Schema.String), taskStartTime: Schema.optional(Schema.Date), taskEndTime: Schema.optional(Schema.Date)}) {}
export const GetSolNetworkOperationTasksList = Schema.Array(GetSolNetworkOperationTaskDetails);
export class GetSolNetworkPackageMetadata extends Schema.Class<GetSolNetworkPackageMetadata>("GetSolNetworkPackageMetadata")({nsd: Schema.optional(NetworkArtifactMeta), createdAt: Schema.Date, lastModified: Schema.Date}) {}
export class ListSolFunctionInstanceInfo extends Schema.Class<ListSolFunctionInstanceInfo>("ListSolFunctionInstanceInfo")({id: Schema.String, arn: Schema.String, nsInstanceId: Schema.String, vnfPkgId: Schema.String, vnfPkgName: Schema.optional(Schema.String), instantiationState: Schema.String, instantiatedVnfInfo: Schema.optional(GetSolInstantiatedVnfInfo), metadata: ListSolFunctionInstanceMetadata}) {}
export const ListSolFunctionInstanceResources = Schema.Array(ListSolFunctionInstanceInfo);
export class ListSolFunctionPackageInfo extends Schema.Class<ListSolFunctionPackageInfo>("ListSolFunctionPackageInfo")({id: Schema.String, arn: Schema.String, onboardingState: Schema.String, operationalState: Schema.String, usageState: Schema.String, vnfdId: Schema.optional(Schema.String), vnfProvider: Schema.optional(Schema.String), vnfProductName: Schema.optional(Schema.String), vnfdVersion: Schema.optional(Schema.String), metadata: Schema.optional(ListSolFunctionPackageMetadata)}) {}
export const ListSolFunctionPackageResources = Schema.Array(ListSolFunctionPackageInfo);
export class ListSolNetworkInstanceInfo extends Schema.Class<ListSolNetworkInstanceInfo>("ListSolNetworkInstanceInfo")({id: Schema.String, arn: Schema.String, nsInstanceName: Schema.String, nsInstanceDescription: Schema.String, nsdId: Schema.String, nsdInfoId: Schema.String, nsState: Schema.String, metadata: ListSolNetworkInstanceMetadata}) {}
export const ListSolNetworkInstanceResources = Schema.Array(ListSolNetworkInstanceInfo);
export class ListSolNetworkOperationsInfo extends Schema.Class<ListSolNetworkOperationsInfo>("ListSolNetworkOperationsInfo")({id: Schema.String, arn: Schema.String, operationState: Schema.String, nsInstanceId: Schema.String, lcmOperationType: Schema.String, updateType: Schema.optional(Schema.String), error: Schema.optional(ProblemDetails), metadata: Schema.optional(ListSolNetworkOperationsMetadata)}) {}
export const ListSolNetworkOperationsResources = Schema.Array(ListSolNetworkOperationsInfo);
export class ListSolNetworkPackageInfo extends Schema.Class<ListSolNetworkPackageInfo>("ListSolNetworkPackageInfo")({id: Schema.String, arn: Schema.String, nsdOnboardingState: Schema.String, nsdOperationalState: Schema.String, nsdUsageState: Schema.String, nsdId: Schema.optional(Schema.String), nsdName: Schema.optional(Schema.String), nsdVersion: Schema.optional(Schema.String), nsdDesigner: Schema.optional(Schema.String), nsdInvariantId: Schema.optional(Schema.String), vnfPkgIds: Schema.optional(VnfPkgIdList), metadata: ListSolNetworkPackageMetadata}) {}
export const ListSolNetworkPackageResources = Schema.Array(ListSolNetworkPackageInfo);
export class GetSolVnfcResourceInfoMetadata extends Schema.Class<GetSolVnfcResourceInfoMetadata>("GetSolVnfcResourceInfoMetadata")({nodeGroup: Schema.optional(Schema.String), cluster: Schema.optional(Schema.String), helmChart: Schema.optional(Schema.String)}) {}
export class GetSolNetworkOperationOutput extends Schema.Class<GetSolNetworkOperationOutput>("GetSolNetworkOperationOutput")({id: Schema.optional(Schema.String), arn: Schema.String, operationState: Schema.optional(Schema.String), nsInstanceId: Schema.optional(Schema.String), lcmOperationType: Schema.optional(Schema.String), updateType: Schema.optional(Schema.String), error: Schema.optional(ProblemDetails), metadata: Schema.optional(GetSolNetworkOperationMetadata), tasks: Schema.optional(GetSolNetworkOperationTasksList), tags: Schema.optional(TagMap)}) {}
export class GetSolNetworkPackageOutput extends Schema.Class<GetSolNetworkPackageOutput>("GetSolNetworkPackageOutput")({id: Schema.String, arn: Schema.String, nsdOnboardingState: Schema.String, nsdOperationalState: Schema.String, nsdUsageState: Schema.String, nsdId: Schema.String, nsdName: Schema.String, nsdVersion: Schema.String, vnfPkgIds: VnfPkgIdList, metadata: GetSolNetworkPackageMetadata, tags: Schema.optional(TagMap)}) {}
export class ListSolFunctionInstancesOutput extends Schema.Class<ListSolFunctionInstancesOutput>("ListSolFunctionInstancesOutput")({nextToken: Schema.optional(Schema.String), functionInstances: Schema.optional(ListSolFunctionInstanceResources)}) {}
export class ListSolFunctionPackagesOutput extends Schema.Class<ListSolFunctionPackagesOutput>("ListSolFunctionPackagesOutput")({nextToken: Schema.optional(Schema.String), functionPackages: ListSolFunctionPackageResources}) {}
export class ListSolNetworkInstancesOutput extends Schema.Class<ListSolNetworkInstancesOutput>("ListSolNetworkInstancesOutput")({nextToken: Schema.optional(Schema.String), networkInstances: Schema.optional(ListSolNetworkInstanceResources)}) {}
export class ListSolNetworkOperationsOutput extends Schema.Class<ListSolNetworkOperationsOutput>("ListSolNetworkOperationsOutput")({nextToken: Schema.optional(Schema.String), networkOperations: Schema.optional(ListSolNetworkOperationsResources)}) {}
export class ListSolNetworkPackagesOutput extends Schema.Class<ListSolNetworkPackagesOutput>("ListSolNetworkPackagesOutput")({nextToken: Schema.optional(Schema.String), networkPackages: ListSolNetworkPackageResources}) {}
export class GetSolVnfcResourceInfo extends Schema.Class<GetSolVnfcResourceInfo>("GetSolVnfcResourceInfo")({metadata: Schema.optional(GetSolVnfcResourceInfoMetadata)}) {}
export const GetSolVnfcResourceInfoList = Schema.Array(GetSolVnfcResourceInfo);
export class GetSolVnfInfo extends Schema.Class<GetSolVnfInfo>("GetSolVnfInfo")({vnfState: Schema.optional(Schema.String), vnfcResourceInfo: Schema.optional(GetSolVnfcResourceInfoList)}) {}
export class GetSolFunctionPackageMetadata extends Schema.Class<GetSolFunctionPackageMetadata>("GetSolFunctionPackageMetadata")({vnfd: Schema.optional(FunctionArtifactMeta), createdAt: Schema.Date, lastModified: Schema.Date}) {}
export class GetSolFunctionInstanceOutput extends Schema.Class<GetSolFunctionInstanceOutput>("GetSolFunctionInstanceOutput")({id: Schema.String, arn: Schema.String, nsInstanceId: Schema.String, vnfPkgId: Schema.String, vnfdId: Schema.String, vnfProvider: Schema.optional(Schema.String), vnfProductName: Schema.optional(Schema.String), vnfdVersion: Schema.optional(Schema.String), instantiationState: Schema.String, instantiatedVnfInfo: Schema.optional(GetSolVnfInfo), metadata: GetSolFunctionInstanceMetadata, tags: Schema.optional(TagMap)}) {}
export class GetSolFunctionPackageOutput extends Schema.Class<GetSolFunctionPackageOutput>("GetSolFunctionPackageOutput")({id: Schema.String, arn: Schema.String, onboardingState: Schema.String, operationalState: Schema.String, usageState: Schema.String, vnfdId: Schema.optional(Schema.String), vnfProvider: Schema.optional(Schema.String), vnfProductName: Schema.optional(Schema.String), vnfdVersion: Schema.optional(Schema.String), metadata: Schema.optional(GetSolFunctionPackageMetadata), tags: Schema.optional(TagMap)}) {}

//# Errors
export class AccessDeniedExceptionError extends Schema.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class InternalServerExceptionError extends Schema.TaggedError<InternalServerExceptionError>()("InternalServerException", InternalServerException.fields) {};
export class ResourceNotFoundExceptionError extends Schema.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ThrottlingExceptionError extends Schema.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class ValidationExceptionError extends Schema.TaggedError<ValidationExceptionError>()("ValidationException", ValidationException.fields) {};
export class ServiceQuotaExceededExceptionError extends Schema.TaggedError<ServiceQuotaExceededExceptionError>()("ServiceQuotaExceededException", ServiceQuotaExceededException.fields) {};

//# Operations
export const untagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.UntagResource" }, UntagResourceInput, UntagResourceOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const cancelSolNetworkOperation = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nslcm/v1/ns_lcm_op_occs/{nsLcmOpOccId}/cancel", method: "POST", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.CancelSolNetworkOperation" }, CancelSolNetworkOperationInput, Schema.Struct({}), [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createSolNetworkPackage = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nsd/v1/ns_descriptors", method: "POST", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.CreateSolNetworkPackage" }, CreateSolNetworkPackageInput, CreateSolNetworkPackageOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteSolFunctionPackage = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}", method: "DELETE", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.DeleteSolFunctionPackage" }, DeleteSolFunctionPackageInput, Schema.Struct({}), [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteSolNetworkInstance = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nslcm/v1/ns_instances/{nsInstanceId}", method: "DELETE", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.DeleteSolNetworkInstance" }, DeleteSolNetworkInstanceInput, Schema.Struct({}), [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteSolNetworkPackage = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nsd/v1/ns_descriptors/{nsdInfoId}", method: "DELETE", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.DeleteSolNetworkPackage" }, DeleteSolNetworkPackageInput, Schema.Struct({}), [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSolFunctionPackageContent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}/package_content", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.GetSolFunctionPackageContent" }, GetSolFunctionPackageContentInput, GetSolFunctionPackageContentOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSolFunctionPackageDescriptor = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}/vnfd", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.GetSolFunctionPackageDescriptor" }, GetSolFunctionPackageDescriptorInput, GetSolFunctionPackageDescriptorOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSolNetworkPackageContent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nsd/v1/ns_descriptors/{nsdInfoId}/nsd_content", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.GetSolNetworkPackageContent" }, GetSolNetworkPackageContentInput, GetSolNetworkPackageContentOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSolNetworkPackageDescriptor = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nsd/v1/ns_descriptors/{nsdInfoId}/nsd", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.GetSolNetworkPackageDescriptor" }, GetSolNetworkPackageDescriptorInput, GetSolNetworkPackageDescriptorOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const instantiateSolNetworkInstance = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nslcm/v1/ns_instances/{nsInstanceId}/instantiate", method: "POST", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.InstantiateSolNetworkInstance" }, InstantiateSolNetworkInstanceInput, InstantiateSolNetworkInstanceOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/tags/{resourceArn}", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.ListTagsForResource" }, ListTagsForResourceInput, ListTagsForResourceOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const tagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/tags/{resourceArn}", method: "POST", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.TagResource" }, TagResourceInput, TagResourceOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const terminateSolNetworkInstance = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nslcm/v1/ns_instances/{nsInstanceId}/terminate", method: "POST", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.TerminateSolNetworkInstance" }, TerminateSolNetworkInstanceInput, TerminateSolNetworkInstanceOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateSolFunctionPackage = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}", method: "PATCH", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.UpdateSolFunctionPackage" }, UpdateSolFunctionPackageInput, UpdateSolFunctionPackageOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateSolNetworkPackage = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nsd/v1/ns_descriptors/{nsdInfoId}", method: "PATCH", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.UpdateSolNetworkPackage" }, UpdateSolNetworkPackageInput, UpdateSolNetworkPackageOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createSolFunctionPackage = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnfpkgm/v1/vnf_packages", method: "POST", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.CreateSolFunctionPackage" }, CreateSolFunctionPackageInput, CreateSolFunctionPackageOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const createSolNetworkInstance = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nslcm/v1/ns_instances", method: "POST", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.CreateSolNetworkInstance" }, CreateSolNetworkInstanceInput, CreateSolNetworkInstanceOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSolNetworkInstance = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nslcm/v1/ns_instances/{nsInstanceId}", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.GetSolNetworkInstance" }, GetSolNetworkInstanceInput, GetSolNetworkInstanceOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putSolFunctionPackageContent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}/package_content", method: "PUT", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.PutSolFunctionPackageContent" }, PutSolFunctionPackageContentInput, PutSolFunctionPackageContentOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const putSolNetworkPackageContent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nsd/v1/ns_descriptors/{nsdInfoId}/nsd_content", method: "PUT", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.PutSolNetworkPackageContent" }, PutSolNetworkPackageContentInput, PutSolNetworkPackageContentOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const updateSolNetworkInstance = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nslcm/v1/ns_instances/{nsInstanceId}/update", method: "POST", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.UpdateSolNetworkInstance" }, UpdateSolNetworkInstanceInput, UpdateSolNetworkInstanceOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ServiceQuotaExceededExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const validateSolFunctionPackageContent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}/package_content/validate", method: "PUT", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.ValidateSolFunctionPackageContent" }, ValidateSolFunctionPackageContentInput, ValidateSolFunctionPackageContentOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const validateSolNetworkPackageContent = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nsd/v1/ns_descriptors/{nsdInfoId}/nsd_content/validate", method: "PUT", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.ValidateSolNetworkPackageContent" }, ValidateSolNetworkPackageContentInput, ValidateSolNetworkPackageContentOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSolNetworkOperation = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nslcm/v1/ns_lcm_op_occs/{nsLcmOpOccId}", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.GetSolNetworkOperation" }, GetSolNetworkOperationInput, GetSolNetworkOperationOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSolNetworkPackage = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nsd/v1/ns_descriptors/{nsdInfoId}", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.GetSolNetworkPackage" }, GetSolNetworkPackageInput, GetSolNetworkPackageOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listSolFunctionInstances = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnflcm/v1/vnf_instances", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.ListSolFunctionInstances" }, ListSolFunctionInstancesInput, ListSolFunctionInstancesOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listSolFunctionPackages = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnfpkgm/v1/vnf_packages", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.ListSolFunctionPackages" }, ListSolFunctionPackagesInput, ListSolFunctionPackagesOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listSolNetworkInstances = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nslcm/v1/ns_instances", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.ListSolNetworkInstances" }, ListSolNetworkInstancesInput, ListSolNetworkInstancesOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listSolNetworkOperations = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nslcm/v1/ns_lcm_op_occs", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.ListSolNetworkOperations" }, ListSolNetworkOperationsInput, ListSolNetworkOperationsOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const listSolNetworkPackages = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/nsd/v1/ns_descriptors", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.ListSolNetworkPackages" }, ListSolNetworkPackagesInput, ListSolNetworkPackagesOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSolFunctionInstance = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnflcm/v1/vnf_instances/{vnfInstanceId}", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.GetSolFunctionInstance" }, GetSolFunctionInstanceInput, GetSolFunctionInstanceOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
export const getSolFunctionPackage = /*#__PURE__*/ makeOperation(() => Operation({ version: "2008-10-21", uri: "/sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}", method: "GET", sdkId: "tnb", sigV4ServiceName: "tnb", name: "TNB.GetSolFunctionPackage" }, GetSolFunctionPackageInput, GetSolFunctionPackageOutput, [AccessDeniedExceptionError, InternalServerExceptionError, ResourceNotFoundExceptionError, ThrottlingExceptionError, ValidationExceptionError]), FormatJSONRequest, FormatJSONResponse, FormatAwsRestJSONError);
