import * as Schema from "effect/Schema"
import { FormatAwsJSON11Request,FormatJSONResponse,FormatAwsRestJSONError, makeOperation } from "../client.ts";
import { Operation, Path, Header, StreamBody, Body } from "../schema-helpers.ts";

//# Schemas
export const FilePaths = Schema.Array(Schema.String);
export const TagKeys = Schema.Array(Schema.String);
export class DeleteAccessRequest extends Schema.Class<DeleteAccessRequest>("DeleteAccessRequest")({ServerId: Schema.String, ExternalId: Schema.String}) {}
export class DeleteHostKeyRequest extends Schema.Class<DeleteHostKeyRequest>("DeleteHostKeyRequest")({ServerId: Schema.String, HostKeyId: Schema.String}) {}
export class DeleteSshPublicKeyRequest extends Schema.Class<DeleteSshPublicKeyRequest>("DeleteSshPublicKeyRequest")({ServerId: Schema.String, SshPublicKeyId: Schema.String, UserName: Schema.String}) {}
export class DescribeAccessRequest extends Schema.Class<DescribeAccessRequest>("DescribeAccessRequest")({ServerId: Schema.String, ExternalId: Schema.String}) {}
export class DescribeExecutionRequest extends Schema.Class<DescribeExecutionRequest>("DescribeExecutionRequest")({ExecutionId: Schema.String, WorkflowId: Schema.String}) {}
export class DescribeHostKeyRequest extends Schema.Class<DescribeHostKeyRequest>("DescribeHostKeyRequest")({ServerId: Schema.String, HostKeyId: Schema.String}) {}
export class DescribeSecurityPolicyRequest extends Schema.Class<DescribeSecurityPolicyRequest>("DescribeSecurityPolicyRequest")({SecurityPolicyName: Schema.String}) {}
export class ImportSshPublicKeyRequest extends Schema.Class<ImportSshPublicKeyRequest>("ImportSshPublicKeyRequest")({ServerId: Schema.String, SshPublicKeyBody: Schema.String, UserName: Schema.String}) {}
export class ListAccessesRequest extends Schema.Class<ListAccessesRequest>("ListAccessesRequest")({MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String), ServerId: Schema.String}) {}
export class ListExecutionsRequest extends Schema.Class<ListExecutionsRequest>("ListExecutionsRequest")({MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String), WorkflowId: Schema.String}) {}
export class ListFileTransferResultsRequest extends Schema.Class<ListFileTransferResultsRequest>("ListFileTransferResultsRequest")({ConnectorId: Schema.String, TransferId: Schema.String, NextToken: Schema.optional(Schema.String), MaxResults: Schema.optional(Schema.Number)}) {}
export class ListHostKeysRequest extends Schema.Class<ListHostKeysRequest>("ListHostKeysRequest")({MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String), ServerId: Schema.String}) {}
export class ListSecurityPoliciesRequest extends Schema.Class<ListSecurityPoliciesRequest>("ListSecurityPoliciesRequest")({MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)}) {}
export class ListTagsForResourceRequest extends Schema.Class<ListTagsForResourceRequest>("ListTagsForResourceRequest")({Arn: Schema.String, MaxResults: Schema.optional(Schema.Number), NextToken: Schema.optional(Schema.String)}) {}
export class SendWorkflowStepStateRequest extends Schema.Class<SendWorkflowStepStateRequest>("SendWorkflowStepStateRequest")({WorkflowId: Schema.String, ExecutionId: Schema.String, Token: Schema.String, Status: Schema.String}) {}
export class SendWorkflowStepStateResponse extends Schema.Class<SendWorkflowStepStateResponse>("SendWorkflowStepStateResponse")({}) {}
export class StartDirectoryListingRequest extends Schema.Class<StartDirectoryListingRequest>("StartDirectoryListingRequest")({ConnectorId: Schema.String, RemoteDirectoryPath: Schema.String, MaxItems: Schema.optional(Schema.Number), OutputDirectoryPath: Schema.String}) {}
export class StartFileTransferRequest extends Schema.Class<StartFileTransferRequest>("StartFileTransferRequest")({ConnectorId: Schema.String, SendFilePaths: Schema.optional(FilePaths), RetrieveFilePaths: Schema.optional(FilePaths), LocalDirectoryPath: Schema.optional(Schema.String), RemoteDirectoryPath: Schema.optional(Schema.String)}) {}
export class StartRemoteDeleteRequest extends Schema.Class<StartRemoteDeleteRequest>("StartRemoteDeleteRequest")({ConnectorId: Schema.String, DeletePath: Schema.String}) {}
export class StartRemoteMoveRequest extends Schema.Class<StartRemoteMoveRequest>("StartRemoteMoveRequest")({ConnectorId: Schema.String, SourcePath: Schema.String, TargetPath: Schema.String}) {}
export class StartServerRequest extends Schema.Class<StartServerRequest>("StartServerRequest")({ServerId: Schema.String}) {}
export class StopServerRequest extends Schema.Class<StopServerRequest>("StopServerRequest")({ServerId: Schema.String}) {}
export class Tag extends Schema.Class<Tag>("Tag")({Key: Schema.String, Value: Schema.String}) {}
export const Tags = Schema.Array(Tag);
export class TagResourceRequest extends Schema.Class<TagResourceRequest>("TagResourceRequest")({Arn: Schema.String, Tags: Tags}) {}
export class TestConnectionRequest extends Schema.Class<TestConnectionRequest>("TestConnectionRequest")({ConnectorId: Schema.String}) {}
export class TestIdentityProviderRequest extends Schema.Class<TestIdentityProviderRequest>("TestIdentityProviderRequest")({ServerId: Schema.String, ServerProtocol: Schema.optional(Schema.String), SourceIp: Schema.optional(Schema.String), UserName: Schema.String, UserPassword: Schema.optional(Schema.String)}) {}
export class UntagResourceRequest extends Schema.Class<UntagResourceRequest>("UntagResourceRequest")({Arn: Schema.String, TagKeys: TagKeys}) {}
export class HomeDirectoryMapEntry extends Schema.Class<HomeDirectoryMapEntry>("HomeDirectoryMapEntry")({Entry: Schema.String, Target: Schema.String, Type: Schema.optional(Schema.String)}) {}
export const HomeDirectoryMappings = Schema.Array(HomeDirectoryMapEntry);
export const SecondaryGids = Schema.Array(Schema.Number);
export class PosixProfile extends Schema.Class<PosixProfile>("PosixProfile")({Uid: Schema.Number, Gid: Schema.Number, SecondaryGids: Schema.optional(SecondaryGids)}) {}
export class UpdateAccessRequest extends Schema.Class<UpdateAccessRequest>("UpdateAccessRequest")({HomeDirectory: Schema.optional(Schema.String), HomeDirectoryType: Schema.optional(Schema.String), HomeDirectoryMappings: Schema.optional(HomeDirectoryMappings), Policy: Schema.optional(Schema.String), PosixProfile: Schema.optional(PosixProfile), Role: Schema.optional(Schema.String), ServerId: Schema.String, ExternalId: Schema.String}) {}
export class UpdateHostKeyRequest extends Schema.Class<UpdateHostKeyRequest>("UpdateHostKeyRequest")({ServerId: Schema.String, HostKeyId: Schema.String, Description: Schema.String}) {}
export const SecurityPolicyNames = Schema.Array(Schema.String);
export class CreateAccessRequest extends Schema.Class<CreateAccessRequest>("CreateAccessRequest")({HomeDirectory: Schema.optional(Schema.String), HomeDirectoryType: Schema.optional(Schema.String), HomeDirectoryMappings: Schema.optional(HomeDirectoryMappings), Policy: Schema.optional(Schema.String), PosixProfile: Schema.optional(PosixProfile), Role: Schema.String, ServerId: Schema.String, ExternalId: Schema.String}) {}
export class InternalServiceError extends Schema.Class<InternalServiceError>("InternalServiceError")({Message: Schema.String}) {}
export class InvalidRequestException extends Schema.Class<InvalidRequestException>("InvalidRequestException")({Message: Schema.String}) {}
export class ResourceNotFoundException extends Schema.Class<ResourceNotFoundException>("ResourceNotFoundException")({Message: Schema.String, Resource: Schema.String, ResourceType: Schema.String}) {}
export class ImportHostKeyRequest extends Schema.Class<ImportHostKeyRequest>("ImportHostKeyRequest")({ServerId: Schema.String, HostKeyBody: Schema.String, Description: Schema.optional(Schema.String), Tags: Schema.optional(Tags)}) {}
export class ImportSshPublicKeyResponse extends Schema.Class<ImportSshPublicKeyResponse>("ImportSshPublicKeyResponse")({ServerId: Schema.String, SshPublicKeyId: Schema.String, UserName: Schema.String}) {}
export class ListSecurityPoliciesResponse extends Schema.Class<ListSecurityPoliciesResponse>("ListSecurityPoliciesResponse")({NextToken: Schema.optional(Schema.String), SecurityPolicyNames: SecurityPolicyNames}) {}
export class ListTagsForResourceResponse extends Schema.Class<ListTagsForResourceResponse>("ListTagsForResourceResponse")({Arn: Schema.optional(Schema.String), NextToken: Schema.optional(Schema.String), Tags: Schema.optional(Tags)}) {}
export class AccessDeniedException extends Schema.Class<AccessDeniedException>("AccessDeniedException")({Message: Schema.optional(Schema.String)}) {}
export class StartDirectoryListingResponse extends Schema.Class<StartDirectoryListingResponse>("StartDirectoryListingResponse")({ListingId: Schema.String, OutputFileName: Schema.String}) {}
export class StartFileTransferResponse extends Schema.Class<StartFileTransferResponse>("StartFileTransferResponse")({TransferId: Schema.String}) {}
export class StartRemoteDeleteResponse extends Schema.Class<StartRemoteDeleteResponse>("StartRemoteDeleteResponse")({DeleteId: Schema.String}) {}
export class StartRemoteMoveResponse extends Schema.Class<StartRemoteMoveResponse>("StartRemoteMoveResponse")({MoveId: Schema.String}) {}
export class ServiceUnavailableException extends Schema.Class<ServiceUnavailableException>("ServiceUnavailableException")({Message: Schema.optional(Schema.String)}) {}
export class ThrottlingException extends Schema.Class<ThrottlingException>("ThrottlingException")({RetryAfterSeconds: Schema.optional(Header("Retry-After"))}) {}
export class TestIdentityProviderResponse extends Schema.Class<TestIdentityProviderResponse>("TestIdentityProviderResponse")({Response: Schema.optional(Schema.String), StatusCode: Schema.Number, Message: Schema.optional(Schema.String), Url: Schema.String}) {}
export class UpdateAccessResponse extends Schema.Class<UpdateAccessResponse>("UpdateAccessResponse")({ServerId: Schema.String, ExternalId: Schema.String}) {}
export class UpdateHostKeyResponse extends Schema.Class<UpdateHostKeyResponse>("UpdateHostKeyResponse")({ServerId: Schema.String, HostKeyId: Schema.String}) {}
export const SecurityPolicyOptions = Schema.Array(Schema.String);
export const SecurityPolicyProtocols = Schema.Array(Schema.String);
export class DescribedAccess extends Schema.Class<DescribedAccess>("DescribedAccess")({HomeDirectory: Schema.optional(Schema.String), HomeDirectoryMappings: Schema.optional(HomeDirectoryMappings), HomeDirectoryType: Schema.optional(Schema.String), Policy: Schema.optional(Schema.String), PosixProfile: Schema.optional(PosixProfile), Role: Schema.optional(Schema.String), ExternalId: Schema.optional(Schema.String)}) {}
export class DescribedHostKey extends Schema.Class<DescribedHostKey>("DescribedHostKey")({Arn: Schema.String, HostKeyId: Schema.optional(Schema.String), HostKeyFingerprint: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), Type: Schema.optional(Schema.String), DateImported: Schema.optional(Schema.Date), Tags: Schema.optional(Tags)}) {}
export class DescribedSecurityPolicy extends Schema.Class<DescribedSecurityPolicy>("DescribedSecurityPolicy")({Fips: Schema.optional(Schema.Boolean), SecurityPolicyName: Schema.String, SshCiphers: Schema.optional(SecurityPolicyOptions), SshKexs: Schema.optional(SecurityPolicyOptions), SshMacs: Schema.optional(SecurityPolicyOptions), TlsCiphers: Schema.optional(SecurityPolicyOptions), SshHostKeyAlgorithms: Schema.optional(SecurityPolicyOptions), Type: Schema.optional(Schema.String), Protocols: Schema.optional(SecurityPolicyProtocols)}) {}
export class ListedAccess extends Schema.Class<ListedAccess>("ListedAccess")({HomeDirectory: Schema.optional(Schema.String), HomeDirectoryType: Schema.optional(Schema.String), Role: Schema.optional(Schema.String), ExternalId: Schema.optional(Schema.String)}) {}
export const ListedAccesses = Schema.Array(ListedAccess);
export class S3FileLocation extends Schema.Class<S3FileLocation>("S3FileLocation")({Bucket: Schema.optional(Schema.String), Key: Schema.optional(Schema.String), VersionId: Schema.optional(Schema.String), Etag: Schema.optional(Schema.String)}) {}
export class EfsFileLocation extends Schema.Class<EfsFileLocation>("EfsFileLocation")({FileSystemId: Schema.optional(Schema.String), Path: Schema.optional(Schema.String)}) {}
export class FileLocation extends Schema.Class<FileLocation>("FileLocation")({S3FileLocation: Schema.optional(S3FileLocation), EfsFileLocation: Schema.optional(EfsFileLocation)}) {}
export class UserDetails extends Schema.Class<UserDetails>("UserDetails")({UserName: Schema.String, ServerId: Schema.String, SessionId: Schema.optional(Schema.String)}) {}
export class ServiceMetadata extends Schema.Class<ServiceMetadata>("ServiceMetadata")({UserDetails: UserDetails}) {}
export class ListedExecution extends Schema.Class<ListedExecution>("ListedExecution")({ExecutionId: Schema.optional(Schema.String), InitialFileLocation: Schema.optional(FileLocation), ServiceMetadata: Schema.optional(ServiceMetadata), Status: Schema.optional(Schema.String)}) {}
export const ListedExecutions = Schema.Array(ListedExecution);
export class ConnectorFileTransferResult extends Schema.Class<ConnectorFileTransferResult>("ConnectorFileTransferResult")({FilePath: Schema.String, StatusCode: Schema.String, FailureCode: Schema.optional(Schema.String), FailureMessage: Schema.optional(Schema.String)}) {}
export const ConnectorFileTransferResults = Schema.Array(ConnectorFileTransferResult);
export class ListedHostKey extends Schema.Class<ListedHostKey>("ListedHostKey")({Arn: Schema.String, HostKeyId: Schema.optional(Schema.String), Fingerprint: Schema.optional(Schema.String), Description: Schema.optional(Schema.String), Type: Schema.optional(Schema.String), DateImported: Schema.optional(Schema.Date)}) {}
export const ListedHostKeys = Schema.Array(ListedHostKey);
export class SftpConnectorConnectionDetails extends Schema.Class<SftpConnectorConnectionDetails>("SftpConnectorConnectionDetails")({HostKey: Schema.optional(Schema.String)}) {}
export class CreateAccessResponse extends Schema.Class<CreateAccessResponse>("CreateAccessResponse")({ServerId: Schema.String, ExternalId: Schema.String}) {}
export class DescribeAccessResponse extends Schema.Class<DescribeAccessResponse>("DescribeAccessResponse")({ServerId: Schema.String, Access: DescribedAccess}) {}
export class DescribeHostKeyResponse extends Schema.Class<DescribeHostKeyResponse>("DescribeHostKeyResponse")({HostKey: DescribedHostKey}) {}
export class DescribeSecurityPolicyResponse extends Schema.Class<DescribeSecurityPolicyResponse>("DescribeSecurityPolicyResponse")({SecurityPolicy: DescribedSecurityPolicy}) {}
export class ImportHostKeyResponse extends Schema.Class<ImportHostKeyResponse>("ImportHostKeyResponse")({ServerId: Schema.String, HostKeyId: Schema.String}) {}
export class ResourceExistsException extends Schema.Class<ResourceExistsException>("ResourceExistsException")({Message: Schema.String, Resource: Schema.String, ResourceType: Schema.String}) {}
export class ListAccessesResponse extends Schema.Class<ListAccessesResponse>("ListAccessesResponse")({NextToken: Schema.optional(Schema.String), ServerId: Schema.String, Accesses: ListedAccesses}) {}
export class ListExecutionsResponse extends Schema.Class<ListExecutionsResponse>("ListExecutionsResponse")({NextToken: Schema.optional(Schema.String), WorkflowId: Schema.String, Executions: ListedExecutions}) {}
export class ListFileTransferResultsResponse extends Schema.Class<ListFileTransferResultsResponse>("ListFileTransferResultsResponse")({FileTransferResults: ConnectorFileTransferResults, NextToken: Schema.optional(Schema.String)}) {}
export class ListHostKeysResponse extends Schema.Class<ListHostKeysResponse>("ListHostKeysResponse")({NextToken: Schema.optional(Schema.String), ServerId: Schema.String, HostKeys: ListedHostKeys}) {}
export class InvalidNextTokenException extends Schema.Class<InvalidNextTokenException>("InvalidNextTokenException")({Message: Schema.String}) {}
export class TestConnectionResponse extends Schema.Class<TestConnectionResponse>("TestConnectionResponse")({ConnectorId: Schema.optional(Schema.String), Status: Schema.optional(Schema.String), StatusMessage: Schema.optional(Schema.String), SftpConnectionDetails: Schema.optional(SftpConnectorConnectionDetails)}) {}
export class LoggingConfiguration extends Schema.Class<LoggingConfiguration>("LoggingConfiguration")({LoggingRole: Schema.optional(Schema.String), LogGroupName: Schema.optional(Schema.String)}) {}
export class ExecutionError extends Schema.Class<ExecutionError>("ExecutionError")({Type: Schema.String, Message: Schema.String}) {}
export class ExecutionStepResult extends Schema.Class<ExecutionStepResult>("ExecutionStepResult")({StepType: Schema.optional(Schema.String), Outputs: Schema.optional(Schema.String), Error: Schema.optional(ExecutionError)}) {}
export const ExecutionStepResults = Schema.Array(ExecutionStepResult);
export class ExecutionResults extends Schema.Class<ExecutionResults>("ExecutionResults")({Steps: Schema.optional(ExecutionStepResults), OnExceptionSteps: Schema.optional(ExecutionStepResults)}) {}
export class DescribedExecution extends Schema.Class<DescribedExecution>("DescribedExecution")({ExecutionId: Schema.optional(Schema.String), InitialFileLocation: Schema.optional(FileLocation), ServiceMetadata: Schema.optional(ServiceMetadata), ExecutionRole: Schema.optional(Schema.String), LoggingConfiguration: Schema.optional(LoggingConfiguration), PosixProfile: Schema.optional(PosixProfile), Status: Schema.optional(Schema.String), Results: Schema.optional(ExecutionResults)}) {}
export class DescribeExecutionResponse extends Schema.Class<DescribeExecutionResponse>("DescribeExecutionResponse")({WorkflowId: Schema.String, Execution: DescribedExecution}) {}

//# Errors
export class InternalServiceErrorError extends Schema.TaggedError<InternalServiceErrorError>()("InternalServiceError", InternalServiceError.fields) {};
export class InvalidRequestExceptionError extends Schema.TaggedError<InvalidRequestExceptionError>()("InvalidRequestException", InvalidRequestException.fields) {};
export class ResourceNotFoundExceptionError extends Schema.TaggedError<ResourceNotFoundExceptionError>()("ResourceNotFoundException", ResourceNotFoundException.fields) {};
export class ServiceUnavailableExceptionError extends Schema.TaggedError<ServiceUnavailableExceptionError>()("ServiceUnavailableException", ServiceUnavailableException.fields) {};
export class ThrottlingExceptionError extends Schema.TaggedError<ThrottlingExceptionError>()("ThrottlingException", ThrottlingException.fields) {};
export class InvalidNextTokenExceptionError extends Schema.TaggedError<InvalidNextTokenExceptionError>()("InvalidNextTokenException", InvalidNextTokenException.fields) {};
export class AccessDeniedExceptionError extends Schema.TaggedError<AccessDeniedExceptionError>()("AccessDeniedException", AccessDeniedException.fields) {};
export class ResourceExistsExceptionError extends Schema.TaggedError<ResourceExistsExceptionError>()("ResourceExistsException", ResourceExistsException.fields) {};

//# Operations
export const tagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.TagResource" }, TagResourceRequest, Schema.Struct({}), [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const untagResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.UntagResource" }, UntagResourceRequest, Schema.Struct({}), [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteAccess = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.DeleteAccess" }, DeleteAccessRequest, Schema.Struct({}), [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteHostKey = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.DeleteHostKey" }, DeleteHostKeyRequest, Schema.Struct({}), [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const deleteSshPublicKey = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.DeleteSshPublicKey" }, DeleteSshPublicKeyRequest, Schema.Struct({}), [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, [InternalServiceErrorError, InvalidNextTokenExceptionError, InvalidRequestExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const sendWorkflowStepState = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.SendWorkflowStepState" }, SendWorkflowStepStateRequest, SendWorkflowStepStateResponse, [AccessDeniedExceptionError, InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const startDirectoryListing = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.StartDirectoryListing" }, StartDirectoryListingRequest, StartDirectoryListingResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const startFileTransfer = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.StartFileTransfer" }, StartFileTransferRequest, StartFileTransferResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const startRemoteDelete = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/startRemoteDelete", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.StartRemoteDelete" }, StartRemoteDeleteRequest, StartRemoteDeleteResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const startRemoteMove = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/startRemoteMove", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.StartRemoteMove" }, StartRemoteMoveRequest, StartRemoteMoveResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const startServer = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.StartServer" }, StartServerRequest, Schema.Struct({}), [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const stopServer = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.StopServer" }, StopServerRequest, Schema.Struct({}), [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const testIdentityProvider = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.TestIdentityProvider" }, TestIdentityProviderRequest, TestIdentityProviderResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateAccess = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.UpdateAccess" }, UpdateAccessRequest, UpdateAccessResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceExistsExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const updateHostKey = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.UpdateHostKey" }, UpdateHostKeyRequest, UpdateHostKeyResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const createAccess = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.CreateAccess" }, CreateAccessRequest, CreateAccessResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceExistsExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeAccess = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.DescribeAccess" }, DescribeAccessRequest, DescribeAccessResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeHostKey = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.DescribeHostKey" }, DescribeHostKeyRequest, DescribeHostKeyResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeSecurityPolicy = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.DescribeSecurityPolicy" }, DescribeSecurityPolicyRequest, DescribeSecurityPolicyResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const importHostKey = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.ImportHostKey" }, ImportHostKeyRequest, ImportHostKeyResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceExistsExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const importSshPublicKey = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.ImportSshPublicKey" }, ImportSshPublicKeyRequest, ImportSshPublicKeyResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceExistsExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError, ThrottlingExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listAccesses = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.ListAccesses" }, ListAccessesRequest, ListAccessesResponse, [InternalServiceErrorError, InvalidNextTokenExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listExecutions = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.ListExecutions" }, ListExecutionsRequest, ListExecutionsResponse, [InternalServiceErrorError, InvalidNextTokenExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listFileTransferResults = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/listFileTransferResults", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.ListFileTransferResults" }, ListFileTransferResultsRequest, ListFileTransferResultsResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listHostKeys = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.ListHostKeys" }, ListHostKeysRequest, ListHostKeysResponse, [InternalServiceErrorError, InvalidNextTokenExceptionError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const listSecurityPolicies = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.ListSecurityPolicies" }, ListSecurityPoliciesRequest, ListSecurityPoliciesResponse, [InternalServiceErrorError, InvalidNextTokenExceptionError, InvalidRequestExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const testConnection = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.TestConnection" }, TestConnectionRequest, TestConnectionResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
export const describeExecution = /*#__PURE__*/ makeOperation(() => Operation({ version: "2018-11-05", uri: "/", method: "POST", sdkId: "Transfer", sigV4ServiceName: "transfer", name: "TransferService.DescribeExecution" }, DescribeExecutionRequest, DescribeExecutionResponse, [InternalServiceErrorError, InvalidRequestExceptionError, ResourceNotFoundExceptionError, ServiceUnavailableExceptionError]), FormatAwsJSON11Request, FormatJSONResponse, FormatAwsRestJSONError);
