import { Schema} from "effect"
import { FormatXMLRequest, FormatXMLResponse, makeOperation } from "../client";
import { Operation, Path, Header, StreamBody, Body, ErrorAnnotation } from "../schema-helpers";
const TagKeys = Schema.Array(Schema.String)
const DeleteDeviceRequest = Schema.Struct({id: Schema.String, clientToken: Schema.optional(Schema.String)})
const DeleteDeviceResponse = Schema.Struct({})
const DeleteEnvironmentRequest = Schema.Struct({id: Schema.String, clientToken: Schema.optional(Schema.String)})
const DeleteEnvironmentResponse = Schema.Struct({})
const DeregisterDeviceRequest = Schema.Struct({id: Schema.String, targetDeviceStatus: Schema.optional(Schema.String), clientToken: Schema.optional(Schema.String)})
const DeregisterDeviceResponse = Schema.Struct({})
const GetDeviceRequest = Schema.Struct({id: Schema.String})
const GetEnvironmentRequest = Schema.Struct({id: Schema.String})
const GetSoftwareSetRequest = Schema.Struct({id: Schema.String})
const ListDevicesRequest = Schema.Struct({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)})
const ListEnvironmentsRequest = Schema.Struct({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)})
const ListSoftwareSetsRequest = Schema.Struct({nextToken: Schema.optional(Schema.String), maxResults: Schema.optional(Schema.Number)})
const ListTagsForResourceRequest = Schema.Struct({resourceArn: Schema.String})
const TagResourceRequest = Schema.Struct({resourceArn: Schema.String, tags: TagsMap})
const TagResourceResponse = Schema.Struct({})
const UntagResourceRequest = Schema.Struct({resourceArn: Schema.String, tagKeys: TagKeys})
const UntagResourceResponse = Schema.Struct({})
const UpdateDeviceRequest = Schema.Struct({id: Schema.String, name: Schema.optional(Schema.String), desiredSoftwareSetId: Schema.optional(Schema.String), softwareSetUpdateSchedule: Schema.optional(Schema.String)})
const UpdateEnvironmentRequest = Schema.Struct({id: Schema.String, name: Schema.optional(Schema.String), desktopArn: Schema.optional(Schema.String), desktopEndpoint: Schema.optional(Schema.String), softwareSetUpdateSchedule: Schema.optional(Schema.String), maintenanceWindow: Schema.optional(MaintenanceWindow), softwareSetUpdateMode: Schema.optional(Schema.String), desiredSoftwareSetId: Schema.optional(Schema.String), deviceCreationTags: Schema.optional(DeviceCreationTagsMap)})
const UpdateSoftwareSetRequest = Schema.Struct({id: Schema.String, validationStatus: Schema.String})
const UpdateSoftwareSetResponse = Schema.Struct({})
const DayOfWeekList = Schema.Array(Schema.String)
const MaintenanceWindow = Schema.Struct({type: Schema.String, startTimeHour: Schema.optional(Schema.Number), startTimeMinute: Schema.optional(Schema.Number), endTimeHour: Schema.optional(Schema.Number), endTimeMinute: Schema.optional(Schema.Number), daysOfTheWeek: Schema.optional(DayOfWeekList), applyTimeOf: Schema.optional(Schema.String)})
const TagsMap = Schema.Record({key: Schema.String, value: Schema.String})
const DeviceCreationTagsMap = Schema.Record({key: Schema.String, value: Schema.String})
const CreateEnvironmentRequest = Schema.Struct({name: Schema.optional(Schema.String), desktopArn: Schema.String, desktopEndpoint: Schema.optional(Schema.String), softwareSetUpdateSchedule: Schema.optional(Schema.String), maintenanceWindow: Schema.optional(MaintenanceWindow), softwareSetUpdateMode: Schema.optional(Schema.String), desiredSoftwareSetId: Schema.optional(Schema.String), kmsKeyArn: Schema.optional(Schema.String), clientToken: Schema.optional(Schema.String), tags: Schema.optional(TagsMap), deviceCreationTags: Schema.optional(DeviceCreationTagsMap)})
const AccessDeniedException = Schema.Struct({message: Schema.optional(Schema.String)})
export const DeleteDevice = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/devices/{id}", method: "DELETE", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "DeleteDevice" }, DeleteDeviceRequest, DeleteDeviceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ConflictException = Schema.Struct({message: Schema.optional(Schema.String), resourceId: Schema.optional(Schema.String), resourceType: Schema.optional(Schema.String)})
export const DeleteEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/environments/{id}", method: "DELETE", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "DeleteEnvironment" }, DeleteEnvironmentRequest, DeleteEnvironmentResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const InternalServerException = Schema.Struct({message: Schema.optional(Schema.String), retryAfterSeconds: Schema.optional(Header("Retry-After", Schema.Number))})
export const DeregisterDevice = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/deregister-device/{id}", method: "POST", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "DeregisterDevice" }, DeregisterDeviceRequest, DeregisterDeviceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListTagsForResourceResponse = Schema.Struct({tags: Schema.optional(TagsMap)})
export const ListTagsForResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "GET", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "ListTagsForResource" }, ListTagsForResourceRequest, ListTagsForResourceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ResourceNotFoundException = Schema.Struct({message: Schema.optional(Schema.String), resourceId: Schema.optional(Schema.String), resourceType: Schema.optional(Schema.String)})
export const TagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "POST", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "TagResource" }, TagResourceRequest, TagResourceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ThrottlingException = Schema.Struct({message: Schema.optional(Schema.String), serviceCode: Schema.optional(Schema.String), quotaCode: Schema.optional(Schema.String), retryAfterSeconds: Schema.optional(Header("Retry-After", Schema.Number))})
export const UntagResource = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/tags/{resourceArn}", method: "DELETE", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "UntagResource" }, UntagResourceRequest, UntagResourceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateDeviceResponse = Schema.Struct({device: Schema.optional(DeviceSummary)})
export const UpdateDevice = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/devices/{id}", method: "PATCH", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "UpdateDevice" }, UpdateDeviceRequest, UpdateDeviceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const UpdateEnvironmentResponse = Schema.Struct({environment: Schema.optional(EnvironmentSummary)})
export const UpdateEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/environments/{id}", method: "PATCH", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "UpdateEnvironment" }, UpdateEnvironmentRequest, UpdateEnvironmentResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Device = Schema.Struct({id: Schema.optional(Schema.String), serialNumber: Schema.optional(Schema.String), name: Schema.optional(Schema.String), model: Schema.optional(Schema.String), environmentId: Schema.optional(Schema.String), status: Schema.optional(Schema.String), currentSoftwareSetId: Schema.optional(Schema.String), currentSoftwareSetVersion: Schema.optional(Schema.String), desiredSoftwareSetId: Schema.optional(Schema.String), pendingSoftwareSetId: Schema.optional(Schema.String), pendingSoftwareSetVersion: Schema.optional(Schema.String), softwareSetUpdateSchedule: Schema.optional(Schema.String), softwareSetComplianceStatus: Schema.optional(Schema.String), softwareSetUpdateStatus: Schema.optional(Schema.String), lastConnectedAt: Schema.optional(Schema.Date), lastPostureAt: Schema.optional(Schema.Date), createdAt: Schema.optional(Schema.Date), updatedAt: Schema.optional(Schema.Date), arn: Schema.optional(Schema.String), kmsKeyArn: Schema.optional(Schema.String), lastUserId: Schema.optional(Schema.String)})
const Environment = Schema.Struct({id: Schema.optional(Schema.String), name: Schema.optional(Schema.String), desktopArn: Schema.optional(Schema.String), desktopEndpoint: Schema.optional(Schema.String), desktopType: Schema.optional(Schema.String), activationCode: Schema.optional(Schema.String), registeredDevicesCount: Schema.optional(Schema.Number), softwareSetUpdateSchedule: Schema.optional(Schema.String), maintenanceWindow: Schema.optional(MaintenanceWindow), softwareSetUpdateMode: Schema.optional(Schema.String), desiredSoftwareSetId: Schema.optional(Schema.String), pendingSoftwareSetId: Schema.optional(Schema.String), pendingSoftwareSetVersion: Schema.optional(Schema.String), softwareSetComplianceStatus: Schema.optional(Schema.String), createdAt: Schema.optional(Schema.Date), updatedAt: Schema.optional(Schema.Date), arn: Schema.optional(Schema.String), kmsKeyArn: Schema.optional(Schema.String), deviceCreationTags: Schema.optional(DeviceCreationTagsMap)})
const DeviceSummary = Schema.Struct({id: Schema.optional(Schema.String), serialNumber: Schema.optional(Schema.String), name: Schema.optional(Schema.String), model: Schema.optional(Schema.String), environmentId: Schema.optional(Schema.String), status: Schema.optional(Schema.String), currentSoftwareSetId: Schema.optional(Schema.String), desiredSoftwareSetId: Schema.optional(Schema.String), pendingSoftwareSetId: Schema.optional(Schema.String), softwareSetUpdateSchedule: Schema.optional(Schema.String), lastConnectedAt: Schema.optional(Schema.Date), lastPostureAt: Schema.optional(Schema.Date), createdAt: Schema.optional(Schema.Date), updatedAt: Schema.optional(Schema.Date), arn: Schema.optional(Schema.String), lastUserId: Schema.optional(Schema.String)})
const DeviceList = Schema.Array(DeviceSummary)
const EnvironmentSummary = Schema.Struct({id: Schema.optional(Schema.String), name: Schema.optional(Schema.String), desktopArn: Schema.optional(Schema.String), desktopEndpoint: Schema.optional(Schema.String), desktopType: Schema.optional(Schema.String), activationCode: Schema.optional(Schema.String), softwareSetUpdateSchedule: Schema.optional(Schema.String), maintenanceWindow: Schema.optional(MaintenanceWindow), softwareSetUpdateMode: Schema.optional(Schema.String), desiredSoftwareSetId: Schema.optional(Schema.String), pendingSoftwareSetId: Schema.optional(Schema.String), createdAt: Schema.optional(Schema.Date), updatedAt: Schema.optional(Schema.Date), arn: Schema.optional(Schema.String)})
const EnvironmentList = Schema.Array(EnvironmentSummary)
const SoftwareSetSummary = Schema.Struct({id: Schema.optional(Schema.String), version: Schema.optional(Schema.String), releasedAt: Schema.optional(Schema.Date), supportedUntil: Schema.optional(Schema.Date), validationStatus: Schema.optional(Schema.String), arn: Schema.optional(Schema.String)})
const SoftwareSetList = Schema.Array(SoftwareSetSummary)
const ValidationExceptionField = Schema.Struct({name: Schema.String, message: Schema.String})
const ValidationExceptionFieldList = Schema.Array(ValidationExceptionField)
const CreateEnvironmentResponse = Schema.Struct({environment: Schema.optional(EnvironmentSummary)})
const GetDeviceResponse = Schema.Struct({device: Schema.optional(Device)})
export const GetDevice = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/devices/{id}", method: "GET", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "GetDevice" }, GetDeviceRequest, GetDeviceResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetEnvironmentResponse = Schema.Struct({environment: Schema.optional(Environment)})
export const GetEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/environments/{id}", method: "GET", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "GetEnvironment" }, GetEnvironmentRequest, GetEnvironmentResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListDevicesResponse = Schema.Struct({devices: Schema.optional(DeviceList), nextToken: Schema.optional(Schema.String)})
export const ListDevices = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/devices", method: "GET", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "ListDevices" }, ListDevicesRequest, ListDevicesResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListEnvironmentsResponse = Schema.Struct({environments: Schema.optional(EnvironmentList), nextToken: Schema.optional(Schema.String)})
export const ListEnvironments = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/environments", method: "GET", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "ListEnvironments" }, ListEnvironmentsRequest, ListEnvironmentsResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ListSoftwareSetsResponse = Schema.Struct({softwareSets: Schema.optional(SoftwareSetList), nextToken: Schema.optional(Schema.String)})
export const ListSoftwareSets = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/softwaresets", method: "GET", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "ListSoftwareSets" }, ListSoftwareSetsRequest, ListSoftwareSetsResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const ValidationException = Schema.Struct({message: Schema.optional(Schema.String), reason: Schema.optional(Schema.String), fieldList: Schema.optional(ValidationExceptionFieldList)})
export const UpdateSoftwareSet = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/softwaresets/{id}", method: "PATCH", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "UpdateSoftwareSet" }, UpdateSoftwareSetRequest, UpdateSoftwareSetResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const Software = Schema.Struct({name: Schema.optional(Schema.String), version: Schema.optional(Schema.String)})
const SoftwareList = Schema.Array(Software)
const SoftwareSet = Schema.Struct({id: Schema.optional(Schema.String), version: Schema.optional(Schema.String), releasedAt: Schema.optional(Schema.Date), supportedUntil: Schema.optional(Schema.Date), validationStatus: Schema.optional(Schema.String), software: Schema.optional(SoftwareList), arn: Schema.optional(Schema.String)})
const ServiceQuotaExceededException = Schema.Struct({message: Schema.optional(Schema.String), resourceId: Schema.optional(Schema.String), resourceType: Schema.optional(Schema.String), serviceCode: Schema.optional(Schema.String), quotaCode: Schema.optional(Schema.String)})
export const CreateEnvironment = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/environments", method: "POST", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "CreateEnvironment" }, CreateEnvironmentRequest, CreateEnvironmentResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("ConflictException", ConflictException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ServiceQuotaExceededException", ServiceQuotaExceededException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
const GetSoftwareSetResponse = Schema.Struct({softwareSet: Schema.optional(SoftwareSet)})
export const GetSoftwareSet = /*#__PURE__*/ makeOperation(() => Operation({ uri: "/softwaresets/{id}", method: "GET", sdkId: "WorkSpaces Thin Client", sigV4ServiceName: "thinclient", name: "GetSoftwareSet" }, GetSoftwareSetRequest, GetSoftwareSetResponse, Schema.Union(ErrorAnnotation("AccessDeniedException", AccessDeniedException), ErrorAnnotation("InternalServerException", InternalServerException), ErrorAnnotation("ResourceNotFoundException", ResourceNotFoundException), ErrorAnnotation("ThrottlingException", ThrottlingException), ErrorAnnotation("ValidationException", ValidationException))), FormatXMLRequest, FormatXMLResponse, FormatXMLResponse);
