// Auto-generated by generate-awsquery-metadata.ts. DO NOT EDIT BY HAND.

export interface AwsQueryServiceMeta {
  serviceId: string;
  serviceName: string;
  version: string;
  endpointPrefix?: string;
  operations: Record<string, OperationMeta>;
  shapes: Record<string, ShapeMeta>;
}

export interface OperationMeta {
  name: string;
  input?: string;
  output?: string;
  responseWrapper?: string;
}

export interface ShapeMeta {
  type: ShapeKind;
  xmlName?: string;
  members?: Record<string, MemberMeta>;
  member?: MemberMeta;
  key?: MemberMeta;
  value?: MemberMeta;
  enum?: string[];
  flattened?: boolean;
}

export interface MemberMeta {
  target: string;
  locationName?: string;
  queryName?: string;
  flattened?: boolean;
  timestampFormat?: "iso8601" | "epoch-seconds" | "http-date";
}

export type ShapeKind =
  | "structure"
  | "list"
  | "map"
  | "string"
  | "integer"
  | "boolean"
  | "timestamp"
  | "blob"
  | "enum"
  | "double"
  | "long"
  | "float"
  | "union";
